### ISSUE TITLE
HTTP WebDav issue unsupported auth scheme

### ISSUE THREAD

**Issue by kosli** [PhilippC/keepass2android#1]
fist: thanks for moving to github! much apperciated.

is there an update on that issue here? https://keepass2android.codeplex.com/workitem/664 
as i cannot use keepass2android anymore since i turned on TOTP/2FA/Two-Factor-Authentication in NextCloud :-(

**Comment by PhilippC** [comment]
as mentioned on Codeplex, I cannot work on this without an account for testing.

**Comment by DJCrashdummy** [comment]
a hint: if just any WebDAV-account for testing is needed, you can get one at https://demo.nextcloud.com/ and then under settings you can create an app-password or even install the [TOTP-app](https://apps.nextcloud.com/apps/twofactor_totp) afterwards.

**Comment by kosli** [comment]
@PhilippC Sorry I missed your comment! Happy to provide you an account. Can you provide me a contact email address?
(Thank you for the new release of Keepass2android, that triggered me to check what happened with the issue here :-))

**Comment by PhilippC** [comment]
@kosli thanks for the offer, can you send credentials to crocoapps@gmail.com? Thanks!

**Comment by kosli** [comment]
@PhilippC check your mail. thank you.

**Comment by PhilippC** [comment]
@kosli: thanks a lot! Might take a few weeks until I work on this, but hopefully can include it in the next release!

**Comment by ragnarkarlsson** [comment]
I'm in the same boat as Kosli, currently having to sync the file within the Nextcloud app and then open the local file via Keepass2Android which is not ideal given the ability within K2A to sync exists. If you need any help testing @PhilippC I'm more than happy to assist.

**Comment by PhilippC** [comment]
I was able to reproduce the error thanks to @kosli. I was also able to fix this error by [generating an "App password"](https://help.nextcloud.com/t/how-to-connect-to-webdav-using-totp/7036), so there seems no action required on the KP2A side.

**Comment by kosli** [comment]
now i am puzzled, i thought i always tried it with a app specific password and that there it didn't work. but obviously it works, even when i tried it right now. thank you very much for your tests and confirmation. so i can delete your account?

**Comment by kosli** [comment]
@PhilippC: i tried it on another nextcloud instance where i have TOTP activated, but there it doesn't seem to work with the app specific password. the file seems to get downloaded, but when i enter the password and press on unlock i get the following error message overlay:
  An error occured: Expected ':status'  header not present.
any idea? the difference to that server is that the user authentication is handled by LDAP, but that should have any influence on the app specific passwords,as with other applications/clients it works.

**Comment by PhilippC** [comment]
@kosli please upgrade to the beta channel. You are now experiencing issue #44 which has been fixed already.

**Comment by dugite-code** [comment]
Was trying to figure out why I randomly see this issue myself this is what I found:

Nextcloud has a bad habit of invalidating App Passwords, if this happens in keepass2android you will see the unsupported auth scheme error. 

* If you change you master password all your app passwords are automatically invalidated
* If you're using external authentication and that times out it invalidates all you app passwords i.e. I have IMAP auth and my server was rebooting and a DavDroid poll caused my app passwords to invalidate.
