### ISSUE TITLE
Dark Theme: inconsistent Group edition pop up

### ISSUE THREAD

**Issue by ageru** [PhilippC/keepass2android#10]
### Setup
1) Android 7.1.1
2) K2A v1.01-g

### Steps to reproduce
1) Set K2A to use the dark theme
2) Open a database with groups
3) Edit one of the group

### Actual result
The pop up for group edition shows with white fonts on light gray background, which is difficult to read. The 3 buttons (OC, Cancel, Icon) are with a dark gray background.

### Expected Result
The design of the pop-up should be consistent with the rest of the dark theme and not impede legibility.

Many thanks for your work :)

**Comment by PhilippC** [comment]
this has been fixed in the meantime
