### ISSUE TITLE
[Feature Request] Improve AutoFill for OTP

### ISSUE THREAD

**Issue by mepi0011** [PhilippC/keepass2android#1001]
I have activated the two factor logon for amazon.de.
Keepss does not fill in the OTP password when logging in to Amazon and does not ask to fill it in.
Do I something wrong?
Is a solution for the next release planed?

**Comment by PhilippC** [comment]
I don't think there *is* a solution with the Android Autofill framework to handle this. If you have any information how this could be achieved, please let me know.

**Comment by mepi0011** [comment]
Thank you very much for your answer. Please excuse me if I do not express myself clearly. It may be that I confuse the terms, for example AutoFill.

What I am interested in is the functionality of Keepass2android to login to Amazon with the OTP key!

On my desktop I use KeepassXC and there I have the possibility to set a Auto-Fill sequence for each database entry, see picture below. The example below works fine for the OTP amazon logon with keepassXC.

{USERNAME}{ENTER}{DELAY 1500}{PASSWORD}{ENTER}{DELAY 1500}**{TOTP}**{ENTER}
![Screenshot_20191024_204616](https://user-images.githubusercontent.com/9118135/67516097-4dae9c80-f6a0-11e9-93b9-82597877f0fe.png)

**Comment by PhilippC** [comment]
but this kind of Auto-Type is not using Android's autofill framework, of course, it just emulates key presses. If you enable the KP2A keyboard, you should have keys for Username/Password/TOTP which should make it easy to fill in these values on Android, also.
