### ISSUE TITLE
Main activity name changed?

### ISSUE THREAD

**Issue by xpusostomos** [PhilippC/keepass2android#1005]
Errrm, did the latest release on the playstore today change the main activity entry point name? Because if so, you just broke all the 3rd party icon packs and I woke up this morning and the 3rd party icon has reverted. That means years of waiting for 3rd party icon providers to update them again. It's really really anti-social to change the default entry point name.

If I'm crazy and imagining this, please ignore.

**Comment by PhilippC** [comment]
I don't think this changed, except if you upgraded from a very old version. Even then, I didn.t really change the name, but the build system did so.

**Comment by xpusostomos** [comment]
Umm.. , is it the case that your build system updates the main entry point name on every release? Poking around in the source it kinda looks like that, and you seem to be implying that in your response. If so, that's extremely anti-social also, because it means if people set a custom icon for this app, it gets wiped out every time you make a minor release, and custom icon artists can't target the app. 

Poking around in the AndroidManifest it looks like the main entry point is called an obfuscated md5f0702f468598c68ce18586502249fb40.KeePass.

That's really anti social.

**Comment by PhilippC** [comment]
that's out of my control, but good news: Xamarin 10 comes with a change in this regard, I guess the names will be constant from then on (and I am going to update to Xamarin 10 for the next release).
