### ISSUE TITLE
Onedrive for business edit/delete/add new error

### ISSUE THREAD

**Issue by RonaldMeu** [PhilippC/keepass2android#1008]
Hi,

The app is update recently , and support for onedrive for business is added.
unfortunally the app crashes when its saving the database after a change.
i have to login again to see there is nothing changed.

**Comment by RonaldMeu** [comment]
![Screenshot_20191027-103836_Keepass2Android](https://user-images.githubusercontent.com/57015527/67632688-ea428b80-f8a6-11e9-9244-3385c8157467.jpg)

**Comment by RonaldMeu** [comment]
hi when i make a new database this problem is't there.

**Comment by frankmill** [comment]
hi,

since update it is impossible to save the export-database on onedrive

after signin on microsoft (username, password) and automatic return to keepass the keepass-screenline is black instead of green and the screen itself is empty

**Comment by PhilippC** [comment]
could you please try to enable debug logging in the app settings and post the log after trying again?

**Comment by RonaldMeu** [comment]
Hi , no problem.
i let you know when i've done this

kind regards.
Ronald

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by RonaldMeu** [comment]
Done..  mailed a log..

**Comment by RonaldMeu** [comment]
Hi , can you see whats going wrong inbthis logging ?

kind regards

Ronald

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by PhilippC** [comment]
@RonaldMeu I can't find that message. Could you please re-send?

**Comment by RonaldMeu** [comment]
6-11-2019 21:05:36:200 -- AppSettingsActivity.OnPause
6-11-2019 21:05:40:909 -- AppSettingsActivity.OnStop
6-11-2019 21:05:43:775 -- AppSettingsActivity.OnStart
6-11-2019 21:05:43:822 -- AppSettingsActivity.OnResume
6-11-2019 21:05:43:822 -- DB null
6-11-2019 21:05:44:754 -- AppSettingsActivity.OnPause
6-11-2019 21:05:44:772 -- PasswordActivity.OnStart
6-11-2019 21:05:44:774 -- PasswordActivity.OnResume
6-11-2019 21:05:44:774 -- DB null
6-11-2019 21:05:44:775 -- starting: True, Finishing: False, _performingLoad: False
6-11-2019 21:05:45:419 -- AppSettingsActivity.OnStop
6-11-2019 21:05:45:420 -- AppSettingsActivity.OnDestroyTrue
6-11-2019 21:05:45:577 -- PasswordActivity.OnPause
6-11-2019 21:05:45:601 -- StackBaseActivity.OnActivityResult Canceled/1
6-11-2019 21:05:45:602 -- TryGetFromActivityResult: no data
6-11-2019 21:05:46:81 -- PasswordActivity.OnStop
6-11-2019 21:05:46:92 -- PasswordActivity.OnDestroyTrue
6-11-2019 21:05:49:304 -- Creating application keepass2android.keepass2android. Version=141
6-11-2019 21:05:49:407 -- KeePass.OnCreate
6-11-2019 21:05:49:409 -- KeePass:apptask=
6-11-2019 21:05:49:414 -- Loaded task keepass2android.NullTask
6-11-2019 21:05:49:415 -- KeePass.OnCreate
6-11-2019 21:05:49:426 -- KeePass.OnStart
6-11-2019 21:05:49:426 -- KeePass.OnStart
6-11-2019 21:05:49:501 -- Loaded task keepass2android.NullTask
6-11-2019 21:05:49:555 -- FileSelect.OnCreate
6-11-2019 21:05:49:656 -- FileSelect.OnStart
6-11-2019 21:05:49:941 -- PasswordActivity.OnCreate
6-11-2019 21:05:49:941 -- PasswordActivity:apptask=
6-11-2019 21:05:50:250 -- PasswordActivity.OnStart
6-11-2019 21:05:50:261 -- PasswordActivity.OnResume
6-11-2019 21:05:50:261 -- DB null
6-11-2019 21:05:50:263 -- starting: True, Finishing: False, _performingLoad: False
6-11-2019 21:05:50:298 -- Pre-loading database file starting
6-11-2019 21:05:50:300 -- PasswordActivity.OnPause
6-11-2019 21:05:50:541 -- PasswordActivity.OnResume
6-11-2019 21:05:50:541 -- DB null
6-11-2019 21:05:50:543 -- starting: False, Finishing: False, _performingLoad: False
6-11-2019 21:05:50:576 -- FileSelect.OnStop
6-11-2019 21:05:50:614 -- FileSelect.OnDestroyTrue
6-11-2019 21:05:50:619 -- KeePass.OnStop
6-11-2019 21:05:50:620 -- KeePass.OnDestroyTrue
6-11-2019 21:05:50:620 -- KeePass.OnDestroyTrue
6-11-2019 21:05:53:333 -- Pre-loading database file completed
6-11-2019 21:05:56:606 -- LockingActivity: OnActivityResult 
6-11-2019 21:05:56:608 -- PasswordActivity.OnActivityResult 874348/1000
6-11-2019 21:05:56:610 -- LockingActivity: OnActivityResult 
6-11-2019 21:05:56:610 -- PasswordActivity.OnActivityResult 874348/1004
6-11-2019 21:05:57:90 -- status message: Initializing...
6-11-2019 21:05:57:96 -- status submessage: 
6-11-2019 21:05:57:202 -- status message: Database wordt geladen…
6-11-2019 21:05:57:397 -- status submessage: Hoofdsleutel transformeren…
6-11-2019 21:05:57:437 -- status submessage: Database ontsleutelen…
6-11-2019 21:05:57:448 -- status submessage: Database ontsleutelen…
6-11-2019 21:05:57:460 -- status submessage: Leest database…
6-11-2019 21:06:01:278 -- ReadXmlStreamed: 3815ms
6-11-2019 21:06:01:294 -- status submessage: 
6-11-2019 21:06:01:318 -- LoadDB OK
6-11-2019 21:06:01:347 -- Starting/Updating OngoingNotificationsService. Database Unlocked
6-11-2019 21:06:01:631 -- PasswordActivity.OnPause
6-11-2019 21:06:01:635 -- Timeout start
6-11-2019 21:06:01:663 -- StackBaseActivity.OnActivityResult Ok/1
6-11-2019 21:06:01:664 -- No AppTask in OnActivityResult
6-11-2019 21:06:01:758 -- GroupActivity.OnCreate
6-11-2019 21:06:01:759 -- GroupActivity:apptask=
6-11-2019 21:06:01:762 -- Loaded task keepass2android.NullTask
6-11-2019 21:06:01:829 -- GroupActivity.OnStart
6-11-2019 21:06:01:832 -- GroupActivity.OnResume
6-11-2019 21:06:01:833 -- DatabaseIsUnlocked=True
6-11-2019 21:06:01:833 -- Timeout cancel
6-11-2019 21:06:02:488 -- PasswordActivity.OnStop
6-11-2019 21:06:02:496 -- PasswordActivity.OnDestroyTrue
6-11-2019 21:06:03:620 -- GroupActivity.OnPause
6-11-2019 21:06:03:620 -- Timeout start
6-11-2019 21:06:03:636 -- GroupActivity.OnCreate
6-11-2019 21:06:03:636 -- GroupActivity:apptask=
6-11-2019 21:06:03:638 -- Loaded task keepass2android.NullTask
6-11-2019 21:06:03:675 -- GroupActivity.OnStart
6-11-2019 21:06:03:677 -- GroupActivity.OnResume
6-11-2019 21:06:03:677 -- DatabaseIsUnlocked=True
6-11-2019 21:06:03:677 -- Timeout cancel
6-11-2019 21:06:04:244 -- GroupActivity.OnStop
6-11-2019 21:06:08:50 -- GroupActivity.OnPause
6-11-2019 21:06:08:50 -- Timeout start
6-11-2019 21:06:08:76 -- EntryActivity.OnCreate
6-11-2019 21:06:08:77 -- EntryActivity:apptask=
6-11-2019 21:06:08:239 -- Loaded task keepass2android.NullTask
6-11-2019 21:06:08:286 -- EntryActivity.OnStart
6-11-2019 21:06:08:291 -- EntryActivity.OnResume
6-11-2019 21:06:08:291 -- DatabaseIsUnlocked=True
6-11-2019 21:06:08:292 -- Timeout cancel
6-11-2019 21:06:08:312 -- Received intent to provide access to entry
6-11-2019 21:06:08:852 -- GroupActivity.OnStop
6-11-2019 21:06:11:549 -- status message: Initializing...
6-11-2019 21:06:11:550 -- status submessage: 
6-11-2019 21:06:11:580 -- status message: Item verwijderen…
6-11-2019 21:06:11:592 -- status message: Database wordt opgeslagen…
6-11-2019 21:06:11:595 -- status submessage: Doelbestand op veranderingen controleren…
6-11-2019 21:06:13:520 -- status submessage: 
6-11-2019 21:06:19:196 -- Xml WriteDocument: 5603ms
6-11-2019 21:06:25:519 -- Status Code: InternalServerError
Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.

at Microsoft.Graph.HttpProvider+<SendAsync>d__18.MoveNext () [0x001e4] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Graph.BaseRequest+<SendRequestAsync>d__35.MoveNext () [0x001c6] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Graph.BaseRequest+<SendAsync>d__31`1[T].MoveNext () [0x0008b] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
at keepass2android.Io.OneDrive2FileStorage`1[OneDrive2PrefixContainerType].UploadFile (System.String path, System.IO.MemoryStream stream) [0x0003b] in <3169fd143f40409586dc88385b819b66>:0 
at keepass2android.Io.OneDrive2FileStorage`1+OneDrive2FileStorageWriteTransaction[OneDrive2PrefixContainerType].CommitWrite () [0x0001c] in <3169fd143f40409586dc88385b819b66>:0 
at keepass2android.Database.SaveData () [0x00040] in <3169fd143f40409586dc88385b819b66>:0 
at keepass2android.SaveDb.PerformSaveWithoutCheck (keepass2android.Io.IFileStorage fileStorage, KeePassLib.Serialization.IOConnectionInfo ioc) [0x00010] in <3169fd143f40409586dc88385b819b66>:0 
at keepass2android.SaveDb.Run () [0x00187] in <3169fd143f40409586dc88385b819b66>:0 
6-11-2019 21:06:25:527 -- Locking database
6-11-2019 21:06:25:557 -- OngoingNotificationsService.OnDestroy
6-11-2019 21:06:25:606 -- Finishing md5b85ab5ea2545156b0f09600c184a5178.GroupActivity due to database lock
6-11-2019 21:06:25:615 -- Finishing md5b85ab5ea2545156b0f09600c184a5178.GroupActivity due to database lock
6-11-2019 21:06:25:624 -- Finishing md5b85ab5ea2545156b0f09600c184a5178.EntryActivity due to database lock
6-11-2019 21:06:25:641 -- Stopping clipboard service due to database lock
6-11-2019 21:06:25:655 -- GroupActivity.OnDestroyTrue
6-11-2019 21:06:25:832 -- GroupActivity.OnDestroyTrue
6-11-2019 21:06:25:980 -- EntryActivity.OnPause
6-11-2019 21:06:26:25 -- CopyToClipboardService.OnDestroy
6-11-2019 21:06:26:29 -- Destroyed Show-Notification-Receiver.
6-11-2019 21:06:26:33 -- StackBaseActivity.OnActivityResult 2/0
6-11-2019 21:06:26:34 -- TryGetFromActivityResult: no data
6-11-2019 21:06:26:71 -- FileSelect.OnCreate
6-11-2019 21:06:26:92 -- FileSelect.OnStart
6-11-2019 21:06:26:116 -- PasswordActivity.OnCreate
6-11-2019 21:06:26:117 -- PasswordActivity:apptask=
6-11-2019 21:06:26:210 -- PasswordActivity.OnStart
6-11-2019 21:06:26:212 -- PasswordActivity.OnResume
6-11-2019 21:06:26:212 -- DB null
6-11-2019 21:06:26:213 -- starting: True, Finishing: False, _performingLoad: False
6-11-2019 21:06:26:216 -- Pre-loading database file starting
6-11-2019 21:06:26:225 -- PasswordActivity.OnPause
6-11-2019 21:06:26:320 -- PasswordActivity.OnResume
6-11-2019 21:06:26:321 -- DB null
6-11-2019 21:06:26:322 -- starting: False, Finishing: False, _performingLoad: False
6-11-2019 21:06:26:748 -- FileSelect.OnStop
6-11-2019 21:06:26:814 -- FileSelect.OnDestroyTrue
6-11-2019 21:06:26:817 -- EntryActivity.OnStop
6-11-2019 21:06:26:819 -- EntryActivity.OnDestroyTrue
6-11-2019 21:06:27:371 -- Pre-loading database file completed
6-11-2019 21:06:39:411 -- LockingActivity: OnActivityResult 
6-11-2019 21:06:39:412 -- PasswordActivity.OnActivityResult 874348/1000
6-11-2019 21:06:39:414 -- LockingActivity: OnActivityResult 
6-11-2019 21:06:39:415 -- PasswordActivity.OnActivityResult 874348/1004
6-11-2019 21:06:39:573 -- status message: Initializing...
6-11-2019 21:06:39:575 -- status submessage: 
6-11-2019 21:06:39:654 -- status message: Database wordt geladen…
6-11-2019 21:06:39:802 -- status submessage: Hoofdsleutel transformeren…
6-11-2019 21:06:39:806 -- status submessage: Database ontsleutelen…
6-11-2019 21:06:39:807 -- status submessage: Database ontsleutelen…
6-11-2019 21:06:39:807 -- status submessage: Leest database…
6-11-2019 21:06:43:555 -- ReadXmlStreamed: 3747ms
6-11-2019 21:06:43:558 -- status submessage: 
6-11-2019 21:06:43:569 -- LoadDB OK
6-11-2019 21:06:43:578 -- Starting/Updating OngoingNotificationsService. Database Unlocked
6-11-2019 21:06:43:758 -- PasswordActivity.OnPause
6-11-2019 21:06:43:759 -- Timeout start
6-11-2019 21:06:43:781 -- StackBaseActivity.OnActivityResult Ok/1
6-11-2019 21:06:43:781 -- No AppTask in OnActivityResult
6-11-2019 21:06:43:831 -- GroupActivity.OnCreate
6-11-2019 21:06:43:832 -- GroupActivity:apptask=
6-11-2019 21:06:43:834 -- Loaded task keepass2android.NullTask
6-11-2019 21:06:43:868 -- GroupActivity.OnStart
6-11-2019 21:06:43:870 -- GroupActivity.OnResume
6-11-2019 21:06:43:871 -- DatabaseIsUnlocked=True
6-11-2019 21:06:43:871 -- Timeout cancel
6-11-2019 21:06:44:500 -- PasswordActivity.OnStop
6-11-2019 21:06:44:503 -- PasswordActivity.OnDestroyTrue
6-11-2019 21:06:45:610 -- GroupActivity.OnPause
6-11-2019 21:06:45:610 -- Timeout start
6-11-2019 21:06:45:626 -- GroupActivity.OnCreate
6-11-2019 21:06:45:626 -- GroupActivity:apptask=
6-11-2019 21:06:45:628 -- Loaded task keepass2android.NullTask
6-11-2019 21:06:45:660 -- GroupActivity.OnStart
6-11-2019 21:06:45:661 -- GroupActivity.OnResume
6-11-2019 21:06:45:662 -- DatabaseIsUnlocked=True
6-11-2019 21:06:45:662 -- Timeout cancel
6-11-2019 21:06:46:202 -- GroupActivity.OnStop
6-11-2019 21:06:49:264 -- GroupActivity.OnPause
6-11-2019 21:06:49:265 -- Timeout start
6-11-2019 21:06:49:286 -- EntryActivity.OnCreate
6-11-2019 21:06:49:287 -- EntryActivity:apptask=
6-11-2019 21:06:49:321 -- Loaded task keepass2android.NullTask
6-11-2019 21:06:49:335 -- EntryActivity.OnStart
6-11-2019 21:06:49:337 -- EntryActivity.OnResume
6-11-2019 21:06:49:338 -- DatabaseIsUnlocked=True
6-11-2019 21:06:49:338 -- Timeout cancel
6-11-2019 21:06:49:348 -- Received intent to provide access to entry
6-11-2019 21:06:49:833 -- GroupActivity.OnStop
6-11-2019 21:06:52:62 -- status message: Initializing...
6-11-2019 21:06:52:63 -- status submessage: 
6-11-2019 21:06:52:90 -- status message: Item verwijderen…
6-11-2019 21:06:52:92 -- status message: Database wordt opgeslagen…
6-11-2019 21:06:52:94 -- status submessage: Doelbestand op veranderingen controleren…
6-11-2019 21:06:55:800 -- status submessage: 
6-11-2019 21:07:01:424 -- Xml WriteDocument: 5565ms
6-11-2019 21:07:07:147 -- Status Code: InternalServerError
Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.

at Microsoft.Graph.HttpProvider+<SendAsync>d__18.MoveNext () [0x001e4] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Graph.BaseRequest+<SendRequestAsync>d__35.MoveNext () [0x001c6] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Graph.BaseRequest+<SendAsync>d__31`1[T].MoveNext () [0x0008b] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
at keepass2android.Io.OneDrive2FileStorage`1[OneDrive2PrefixContainerType].UploadFile (System.String path, System.IO.MemoryStream stream) [0x0003b] in <3169fd143f40409586dc88385b819b66>:0 
at keepass2android.Io.OneDrive2FileStorage`1+OneDrive2FileStorageWriteTransaction[OneDrive2PrefixContainerType].CommitWrite () [0x0001c] in <3169fd143f40409586dc88385b819b66>:0 
at keepass2android.Database.SaveData () [0x00040] in <3169fd143f40409586dc88385b819b66>:0 
at keepass2android.SaveDb.PerformSaveWithoutCheck (keepass2android.Io.IFileStorage fileStorage, KeePassLib.Serialization.IOConnectionInfo ioc) [0x00010] in <3169fd143f40409586dc88385b819b66>:0 
at keepass2android.SaveDb.Run () [0x00187] in <3169fd143f40409586dc88385b819b66>:0 
6-11-2019 21:07:07:148 -- Locking database
6-11-2019 21:07:07:186 -- OngoingNotificationsService.OnDestroy
6-11-2019 21:07:07:233 -- Finishing md5b85ab5ea2545156b0f09600c184a5178.GroupActivity due to database lock
6-11-2019 21:07:07:241 -- Finishing md5b85ab5ea2545156b0f09600c184a5178.GroupActivity due to database lock
6-11-2019 21:07:07:251 -- Finishing md5b85ab5ea2545156b0f09600c184a5178.EntryActivity due to database lock
6-11-2019 21:07:07:268 -- Stopping clipboard service due to database lock
6-11-2019 21:07:07:275 -- GroupActivity.OnDestroyTrue
6-11-2019 21:07:07:460 -- GroupActivity.OnDestroyTrue
6-11-2019 21:07:07:606 -- EntryActivity.OnPause
6-11-2019 21:07:07:631 -- CopyToClipboardService.OnDestroy
6-11-2019 21:07:07:634 -- Destroyed Show-Notification-Receiver.
6-11-2019 21:07:07:636 -- StackBaseActivity.OnActivityResult 2/0
6-11-2019 21:07:07:637 -- TryGetFromActivityResult: no data
6-11-2019 21:07:07:673 -- FileSelect.OnCreate
6-11-2019 21:07:07:693 -- FileSelect.OnStart
6-11-2019 21:07:07:714 -- PasswordActivity.OnCreate
6-11-2019 21:07:07:715 -- PasswordActivity:apptask=
6-11-2019 21:07:07:801 -- PasswordActivity.OnStart
6-11-2019 21:07:07:803 -- PasswordActivity.OnResume
6-11-2019 21:07:07:803 -- DB null
6-11-2019 21:07:07:804 -- starting: True, Finishing: False, _performingLoad: False
6-11-2019 21:07:07:806 -- Pre-loading database file starting
6-11-2019 21:07:07:812 -- PasswordActivity.OnPause
6-11-2019 21:07:07:909 -- PasswordActivity.OnResume
6-11-2019 21:07:07:910 -- DB null
6-11-2019 21:07:07:911 -- starting: False, Finishing: False, _performingLoad: False
6-11-2019 21:07:08:344 -- FileSelect.OnStop
6-11-2019 21:07:08:405 -- FileSelect.OnDestroyTrue
6-11-2019 21:07:08:406 -- EntryActivity.OnStop
6-11-2019 21:07:08:408 -- EntryActivity.OnDestroyTrue
6-11-2019 21:07:10:940 -- Pre-loading database file completed
6-11-2019 21:07:11:124 -- PasswordActivity.OnPause
6-11-2019 21:07:11:164 -- AppSettingsActivity.OnCreate
6-11-2019 21:07:11:165 -- AppSettingsActivity:apptask=
6-11-2019 21:07:11:278 -- AppSettingsActivity.OnStart
6-11-2019 21:07:11:280 -- AppSettingsActivity.OnResume
6-11-2019 21:07:11:280 -- DB null
6-11-2019 21:07:11:719 -- PasswordActivity.OnStop

**Comment by PhilippC** [comment]
thanks a lot for the log!
I tried to research where this might come from but didn't find something useful yet. Can you please let me know how large the database file is? Is this a personal OneDrive account or OneDrive for Business?

**Comment by RonaldMeu** [comment]
Hi Philipp,

It is 13,8MB database file.
and i use a password and a keyfile.
It is stored onedrive for business.

kind regards,

Ronald

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by PhilippC** [comment]
Could you maybe try with a new, small file without keyfile - just for testing?

**Comment by RonaldMeu** [comment]
Hi Philipp,

I've tested it as you asked.  This works flawless without any error.

regards,

Ronald

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by PhilippC** [comment]
thanks, that's interesting. It means that your account or any of its settings are not the reason.

**Comment by RonaldMeu** [comment]
thats right.  But why can i open my original database and is it possible to edit it but not to sync correctly

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by PhilippC** [comment]
I found the reason for this, please see #1036

**Comment by RonaldMeu** [comment]
Hi , do you think there is a way to overcome this limit with keepass2android ?

Microsoft states:
Use resumable file transfers for files larger than 10 MiB (10,485,760 bytes).
If i read it right,  you did put this in the roadmap for v.109 ?


kind regards,

Ronald

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by PhilippC** [comment]
that's what I am planning to implement in 1.09, yes. For the time being, I suggest you try to reduce the size of the database - I would recommend that anyway to speed up loading and encryption.

**Comment by mgreene76** [comment]
Thanks for your work on resolving this.

For your information, I'm experiencing the same issue.  But my database is only 8.9MB.  Also password and key file, but using OneDrive Personal, not Business.

I tried with a smaller database and it worked fine.
