### ISSUE TITLE
Disconnecting From SMB network throws error and crashes the application

### ISSUE THREAD

**Issue by s-i-m-m** [PhilippC/keepass2android#101]
If you are using a database shared via SMB then when you go onto cellular data and try to re-open keepass2android you will get an error "Android Samba Client has stopped" and the application will crash.

**Comment by PhilippC** [comment]
are you using https://play.google.com/store/apps/details?id=com.google.android.sambadocumentsprovider? or which app?

**Comment by PhilippC** [comment]
closing as no response
