### ISSUE TITLE
Feature Suggestion: Auto Open additional database files

### ISSUE THREAD

**Issue by lparsons** [PhilippC/keepass2android#1019]
I have two KeePass database files, one for my personal passwords and one that I share with my wife containing things like bank accounts, etc. that we share.

I've recently discovered a couple of features in KeePassXC that make that easier to manage, [Auto Open](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/QUICKSTART.md#using-auto-open) and [KeeShare](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/QUICKSTART.md#using-sharing). 

The simplest one is Auto Open. Essentially, when I open my personal database, KeePassXC will automatically open my shared database as well. This makes it simple to have the browser plugin automatically fill entries from either database. I would love a feature such as this for Keepass2Android.

Thanks as always for such a well developed, maintained, and supported KeePass solution on Android.

**Comment by PhilippC** [comment]
Keepass2Android supports the AutoOpen system. Please add details if that's not working for you.

**Comment by lparsons** [comment]
So it.does! Sorry, I hadn't seen that in the docs. So far so good. Thanks.
