### ISSUE TITLE
Regression: Persistent fingerprint unlock overlay

### ISSUE THREAD

**Issue by ginkel** [PhilippC/keepass2android#1024]
Starting with the most recent beta, fingerprint unlock stopped working on my Pixel 3 (Android 10, Nov 19 security updates). While the native fingerprint unlock overlay appears, it does not react to the fingerprint reader and cannot be hidden (by pressing cancel or back). The only way to get it to disappear is to reboot the device.

**Comment by PhilippC** [comment]
this sounds pretty weird. Do you know how to collect a logcat? Can anybody confirm this behavior? I can't reproduce, unfortunately.

**Comment by ginkel** [comment]
Definitely weird. I captured a screenshot when it happened, but can't
reproduce it either. Feel free to close the issue for now.
