### ISSUE TITLE
Brightness goes max when In-Screen Fingerprint active

### ISSUE THREAD

**Issue by slobokot** [PhilippC/keepass2android#1027]
OnePlus 7T. 
Oxygen OS 10.0.4.HD65AA (Android 10)
Keepass 1.07b-r0

I have enabled authorization with fingerprint in Keepass.
When I launch Keepass and it requests fingerprint on the very first screen then all of a sudden brightness of the whole screen is increased to 100%.
Another apps, that ask for fingerprint, for example Bank of America, Chase, Telegram, they all don't have this issue, i.e. screen brightness remains the same and only in-screen fingerprint area has increased brightness.

**Comment by PhilippC** [comment]
I assume this is fixed in 1.08-pre3 because it has a completely different implementation. please reopen if this is not true.
