### ISSUE TITLE
can't disable fingerprint on (new/different) device without FP sensor

### ISSUE THREAD

**Issue by LukeSkywalk3r** [PhilippC/keepass2android#1028]
I moved from my Pixel 2 to a Pixel 4, which doesn't has a FP sensor anymore. I initialized the P4 through Google Cloud Backup. The App settings where transferred, which was nice. My DB is synced via OneCloud. 
Now the P4 showed the fingerprint error on the login screen, to unlock via password, and re-enable FP in the settings. But i can't disable FP inside the DB settings since there is no FP on the System.
I had to delete app data and login to OneCloud again. Opening and changing FP settings on P2 wasn't syncing over to P4 (or I was impatient).

Would it be possible to make the 'disable fingerprint for unlock' Option always visible (regardless of hardware)? Or is this a minor use case?

**Comment by PhilippC** [comment]
I guess this is 1.07b? Could you please switch to 1.08-pre3 (https://play.google.com/apps/testing/keepass2android.keepass2android)? I guess this is fixed then. If not, please reopen.
