### ISSUE TITLE
Crashes on Startup in Oreo / AOSP

### ISSUE THREAD

**Issue by chris42** [PhilippC/keepass2android#103]
Hi there,

just installed it on a fresh build AOSP Oreo. When trying to start the app, it crashes right away.

See attached file for logging info. Can provide others, if you tell me what is needed.

Regards
  Chris

[Keepass2Android-Crash.txt](https://github.com/PhilippC/keepass2android/files/1456073/Keepass2Android-Crash.txt)

**Comment by PhilippC** [comment]
can you please try to uninstall-reboot-reinstall (including reboot!). This helped others to fix broken installations.

**Comment by chris42** [comment]
Hi Philipp,
did what you said, with uninstall, boot, reinstall, boot. Nothing changed. App crashes right on startup with the above mentioned mono-rt error.
Anything else I could try? Is there a way to download an older version of the app, to see if a change in the last versions is causing this?

Regards
  Chris

**Comment by PhilippC** [comment]
older releases are available on https://keepass2android.codeplex.com/releases/view/629934. If one of them works, please also try to update to the latest again.

**Comment by chris42** [comment]
Hi Philipp,

tried "1.01-preview" and it works as usual. Could connect to an owncloud server and open the password file.
When updating to the current version, old behaviour is back. App crashes right on start with the mono-rt exception above.
Will for now disable the updates, to stay on the working version. What can I do to help find the issue for further versions?

Regards
  Chris

**Comment by PhilippC** [comment]
hmm, Xamaran used to have problems with new Android versions every now and then, but this does not occur on all Oreo devices so it might also be related to something different. Do you have anything special on your device?
Version 1.04 will be built with an updated Mono RT, you try that as soon as it's out.

**Comment by chris42** [comment]
It is a clean AOSP build for Sony Xperia X Compact. I am using microg instead of any google frameworks. However out of the exception, it seems to be within mono-rt.
Will check 1.04 as soon as its out.

**Comment by meisanerd** [comment]
As an update, I also have this issue.  1.01-pre4 works for me as well.

Joined the beta, just tested 1.04-pre3, and the same crash is occurring.  Attached is the logcat that I am getting, if that helps you out in any way, or is useful in sending to Xamaran for them to debug.
[crash.txt](https://github.com/PhilippC/keepass2android/files/1639787/crash.txt)

I am also running a Sony device (X Performance, maybe it is something with one of the Sony libraries), AOSP build of Oreo.  I do have the basic version of Google Apps installed on mine (Open Gapps pico).  It was also happening when I was running CarbonROM based on Nougat, but that ROM had a number of other issues as well, so I wasn't sure if it was something with the ROM, or with the App, and didn't bother grabbing log files for it.

**Comment by PhilippC** [comment]
looking deeper into the logs, it seems like the
`audit(0.0:2405): avc: denied { read } for name="uptime" dev="proc"`
is hinting at some problem with the OS configuration. See https://stackoverflow.com/questions/37973039/avc-denied-even-with-proper-policy-added for example.

**Comment by meisanerd** [comment]
Interesting, I'll have to try a different AOSP build for my device and see if that clears it up.  Hopefully I can get to that this weekend.

I do find it a bit odd that it started randomly breaking, though, when I was still running Carbon, as it was clearly an app update that broke it, and not the ROM, as I didn't change anything on it.

**Comment by brenzi** [comment]
confirming this issue. I'm using Sony's AOSP Oreo 8.0 for Sony Xperia XZ1 compact. 1.03 crashes, 1.01 works

**Comment by meisanerd** [comment]
As an update to my previous post, I installed a different version of Oreo for my device, and the latest version of this app from the play store is working again.

**Comment by chris42** [comment]
Can confirm, that with 1.04b the issue is gone on an AOSP Oreo 8.1
