### ISSUE TITLE
Question: Possible to clean the last opened Database History ? 

### ISSUE THREAD

**Issue by skyerjoe** [PhilippC/keepass2android#1030]
Is it possible to clean the "Last opened Database History" ? 

I have some which are deprecreated and i dont want to see them anymore  

best regards

**Comment by PhilippC** [comment]
yes, by clicking the three vertical dots of the history element.

**Comment by skyerjoe** [comment]
i thought there was an mass delete option 

but u right  this is also sufficient 

thnx 

best regards
