### ISSUE TITLE
"Activate search field on start" doesn't work when unlocking via Quick Unlock

### ISSUE THREAD

**Issue by nukem2k5** [PhilippC/keepass2android#1031]
I'm using KP2A Offline on a Pixel 3.  When initially unlocking the database, this feature works.  But subsequent unlocks via Quick Unlock no longer activate the search field.  I'm 99% certain that it used to.

**Comment by PhilippC** [comment]
this was fixed in commit 1701c9142b814cdcd9cc00ec455d4547e32a9562, please wait for 1.08-offline or switch to https://play.google.com/apps/testing/keepass2android.keepass2android
