### ISSUE TITLE
AutoExec item doesn't work with relative path and nextcloud

### ISSUE THREAD

**Issue by pvalsecc** [PhilippC/keepass2android#1033]
On keepassxc, I've setup an AutoOpen entry that opens another DB, using a relative path (URL=`Familly.kdbx`) that contains only the filename. The master DB and the other DB both sits side by side in the same directory on my PC and this directory is synchronized with nextcloud.

On keeppass2android, I can open the master DB through nextcloud. But the opening of the child DB fails with an error that it cannot open the `/Familly.kdbx` file. Looks like the path is not built relative the nextcloud webdav URL (I guess).

I could modify the child DB to point to nextcloud on keepass2android. But then the entry is broken on keepassxc.

**Comment by pvalsecc** [comment]
Work around is to add an entry from the DB settings/configure child DBs and disable the one with a relative path and add one with a nextcloud path. With both entries in AutoOpen, both sides are happy.

**Comment by PhilippC** [comment]
/Familly.kdbx is not a relative path but an absolute one. The "Keepass2 style" solution would be to use {DB_PATH}/Familly.kdbx as path. This would work with KP2A, but I don't know if this is implemented in KeepassXC.

**Comment by pvalsecc** [comment]
> /Familly.kdbx is not a relative path but an absolute one.

Indeed it is. But it's not what I put in the AutoOpen entry. I put a relative path: `Familly.kdbx`
