### ISSUE TITLE
Questions: how to undo the autofill option "do not use autofill for this app"?  + KP2A_URL always the same

### ISSUE THREAD

**Issue by Bug-Ninja** [PhilippC/keepass2android#1037]
I have a question about the autofill. (Android 8.1, lineageos 15.1)

I have enabled auto fill and in any app with a credential field, there will be the option the fill it with Keepass2Android, or to disable autofill for that specific app.
I accidentally tapped the latter for Fennec (Firefox 68.2), but can't find a way to enable it again. How can I do this? Imho this should be possible to alter easily from the settings menu...

A second question: every entry that I use gets edited with a "KP2A_URL_1", but the value is the same for every entry, as it just notes the app URL and not the URL of the website: "androidapp://org.mozilla.fennec_fdroid" . The result is that I get a lot of possible entries to choose from when I wish to enter my credentials on a website. (I do that now from the notification "Keepass2Android AutoFill": I tap on it and it shows me every entry with the app URL instead of the domain. Not what I would expect. I would expect it to show me the entries for the domain name). 
Could someone clarify if this is the expected behaviour?

**Comment by PhilippC** [comment]
you should be able to re-activate this in settings - app - password access - Autofill - disabled autofill targets.

regarding the url detection: "org.mozilla.fennec_fdroid" is whitelisted since 2019-08-20, so if you have 1.07b or later, KP2A should use the URL from the website (if fennec_fdroid corrrectly transmit it).

**Comment by chilliger** [comment]
In android 9 pie this can be found in the Keepass2android settings under "password entry access" - > "autofill service" - > "disabled autofill targets"

**Comment by nedy13** [comment]
I was not able to find this settings in the option structure until I read this comments here. Also checked the FAQs. Maybe you should add this to the FAQs or moving the setting as a top level setting. Thanks for the great app.

**Comment by nedy13** [comment]
> you should be able to re-activate this in settings - app - password access - Autofill - disabled autofill targets.
> 


I was not able to find this settings in the option structure until I read this comments here. Also checked the FAQs. Maybe you should add this to the FAQs or moving the setting as a top level setting. Thanks for the great app.
