### ISSUE TITLE
Can't Unlock database Keepass2Android

### ISSUE THREAD

**Issue by Ronald1949** [PhilippC/keepass2android#1039]
Hello, I am using Keepass2Android on my Samsung S10.  Sumsung updated the software this morning, and now I can't unlock my database.  I am sure of my password.
Regards, Ron Terwijn
Version=V1.07b-r0

**Comment by PhilippC** [comment]
can you try to open the local backup?

**Comment by Ronald1949** [comment]
﻿
Hi Philipp,
Thank you for your response.
No I can’t open / unlock the backup file as well.  
All I get is a password screen, that keeps failing on me.
I have downloaded the “keepass.kbdx” file, and tried to convert to a spreadsheet type file, but all I got is the cryptic text.




Regards,
Ron Terwijn
Meadow Springs, Weastern Australia.

**Comment by Ronald1949** [comment]
Hi Philipp,
I have a screenshot of the error message, but seem not be able to get it attached to this message.
It reads:
Could not access source file: Permission Denial: opening provider com.google.android.gm.sapi.SapiUiProvider from ProcessRecord{686c629d032158:keepass2android.keepass2android/u0a222} (pid=32158, uid=10222) that is not exported from UID 10136.  Loaded file from internal cache.  You can still make changes in the database and synchronise them later.

I hope that this might give you a clue what went wrong?
Regards,
Ron Terwijn

**Comment by Ronald1949** [comment]
Sorry, i don’t like to close yet the issue.
Ron Terwijn

**Comment by PhilippC** [comment]
usually this means that the file was opened with a third-party app involved (e.g. using an app like Dropbox app and opening the file from there). Then after some time, the exported version of the file becomes inaccessible to KP2A. You can try to select "Opne file" and browse to the file again, if you know where it is located.
But before you do so, I would try again with the local backup. What's the error you get there? If it's the one you posted, you are not using the backup I mean. Select "Change database" then enabel "Show local backups " and select the backup for your database. This should work.

**Comment by Ronald1949** [comment]
Hi Philipp, I have tried the various suggestions you gave, with all similar errors results.  One new message is that I have to unlock with password first and then going into settings to a. E. enable my fingerprint security.  I am on holidays at the moment and wen home again I can use my laptop to dragon the various screen shots I have off all the error messages.  Back at th end of this month. Regards Ron Terwijn 

- [ ]

**Comment by pradacr** [comment]
![2019-11 keepass error](https://user-images.githubusercontent.com/1907482/69386325-ef1d1400-0c87-11ea-8c79-c26065e7612c.png)
I sometimes get this same error, I followed your advice and solved it.
Thanks a lot!

**Comment by pradacr** [comment]
By the way, this messages show up for only a moment, wouldn't it be good if they stayed somewhere to have enough time to read them?

**Comment by JordyValentine** [comment]
I had this same issue but I ended up resolving it by forcing kp2a to re-sync with Google drive by importing the database again. The local backup also worked for me.

**Comment by Ronald1949** [comment]
Hi Jordy, how do you do that?

**Comment by JordyValentine** [comment]
If you go to the main page of the app (the one that comes up when you press the change database button) and press on open file you should be able to select your database file and try opening it that way.

**Comment by PhilippC** [comment]
I think everything has been said regarding this issue so I'm closing it.

**Comment by Ronald1949** [comment]
Sorry PhilippC.  I can’t be bother anymore on this issue.  I have uninstalled your program and will never use it again.  You gave a problem with your compatibility on android, and I had to suffer for it.
Thanks, but, no thank you.  Very, very disappointed.
