### ISSUE TITLE
FTP browser doesn't work properly

### ISSUE THREAD

**Issue by kromkrom** [PhilippC/keepass2android#1040]
Sorry for generic issue title, probably should be split into several issues.
Version 1.07b-r0

1. When I try to edit existing FTP entry (added ~1 year ago), app crashes
2. When I try to add a new entry, not setting the base path, it shows a "Loading" throbber, but does nothing unless I kill the application
3. When I add a new entry, while setting the base path to a dir where my file is located, I see my files shown, but can't select, because "Loading" throbber is laid over and in the top bar "Root" seems to be added one after one. After a few minutes the file selection is unlocked and I am able to select a file

**Comment by PhilippC** [comment]
can you please switch to beta (https://play.google.com/apps/testing/keepass2android.keepass2android) which has an updated FTP library. If that doesn't work, please post the FTP server log.

**Comment by PhilippC** [comment]
closing as no response. please re-open if you have further information and tried the beta.

**Comment by kromkrom** [comment]
@PhilippC sorry for quite a delayed response. I've tried out the beta.
FTP browser (points 2 & 3 from the original issue) works now.
But editing existing FTP entry (point 1) still forces app to close.
