### ISSUE TITLE
Feature request:Recognize keepassXC steam TOTP setting

### ISSUE THREAD

**Issue by plusls** [PhilippC/keepass2android#1041]
KeeTrayTOTP for Steam uses the TOTP Settings additional attributes and sets the digits value to S, but keepassXC sets attribute `encoder` to `steam`, likes `otpauth://totp/XXX:xxxxx?secret=xxxxxx&period=30&digits=5&issuer=XXX&encoder=steam`.
I hope kp2a also can recognize encoder setting.

**Comment by PhilippC** [comment]
already implemented in 1.08-pre3 (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by plusls** [comment]
thx

**Comment by nate2014jatc** [comment]
Would you please clarify on how this is implemented?
I cannot get valid TOTP credentials from the android app, when the desktop app generated them flawlessly.

**Comment by PhilippC** [comment]
@nate2014jatc did you try with 1.08? If so, can you share how your entry looks like?

**Comment by mananhiteshkataria** [comment]
> @nate2014jatc did you try with 1.08? If so, can you share how your entry looks like?

I am facing this issue as well on my desktop client it's working fine but on the android client it shows the toto but it's an incorrect entry

**Comment by nate2014jatc** [comment]
My apologies for the delay.
I was previously on 1.07, I am trying now on 1.08-r1.
