### ISSUE TITLE
Clean copied password, android 10

### ISSUE THREAD

**Issue by mfallen** [PhilippC/keepass2android#1042]
Just saw something strange, not sure of new with Android 10.
I use KP2A now a long time, normally I open my entry in the database, then open website, move down the menu, first copy User, paste into field, then copy password, paste as well and log on. Now I recognize that after copying the pe and closing the database (not just quick unlock, really close dB), password is still visible, for example using Chrome. Here I want to enter a address in address bar, since Chrome ??, Chrome as well suggest "copied text" as my next entry - means I can see the password now in "plain text" (sorry, not sure if this is the correct English word, mean readable)...seems to be not cleared out of the clipboard?

Bug, wanted feature, new with Android 10?

**Comment by PhilippC** [comment]
Android's clipboard is insecure and hard to clear. Please use another method of transferring passwords, see https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md
