### ISSUE TITLE
Add relative paths for autoopen url

### ISSUE THREAD

**Issue by stingray21** [PhilippC/keepass2android#1043]
Would it be possible to add relative paths to the autoopen functionality?

Currently, child databases with a relative paths (e.g. `safe.kdbx` or `./safe.kdbx`) don't get found by Keepass2Android. 

Path placeholders (e.g. `{DB_DIR}{ENV_DIRSEP}safe.kdbx`) work in Keepass2Android, but are not compatible with e.g. KeepassXC.

**Comment by PhilippC** [comment]
I don't think this kind of relative paths work in Keepass2, do they?

**Comment by stingray21** [comment]
It works in KeepassXC 

https://github.com/keepassxreboot/keepassxc/pull/1053

**Comment by PhilippC** [comment]
that's not was I was asking. I think the KeepassXC implementation deviates from the original one and I don't see a need to follow this newly introduced variant. There is a definition for solving the problem already.
Until KeepassXC implements the original idea: Both KeepassXC and KP2A support IfDevice which allows to solve the problem as well.

**Comment by stingray21** [comment]
Thank you for clarifying.

Unfortunately, I don't think KeepassXC is supporting *IfDevice* yet. 
https://github.com/keepassxreboot/keepassxc/issues/2871 is still open.

However, the implementation for Keepass2Android solves the problem sufficiently, since KeepassXC seems to just ignore the entry with {DB_DIR}.

For anyone with the same issue, this is my setup:
I now have two entries for the shared database in the AutoOpen folder.
- One entry with a relative Path and the attribute *IfDevice*: `!<Android device ID>`. The ID negated, so that it is ignored by Keepass2Android. 
- Another entry with the *url* `{DB_DIR}/safe.kdbx`. This one will be automatically opened on Keepass2Android.
Not sure if this is the proper way to do it, but it seems to work.

Even though the implementation in Keepass2Android is great (the checkbox in the *edit* section), it would be nice if the documentation on how *IfDevice* works was more easily accessible, and not only in the readme file in a zipped folder of a Keepass extension. It took me quite a while to figure out how to use it.
