### ISSUE TITLE
Fennec F-droid autofill not getting URL?

### ISSUE THREAD

**Issue by Bug-Ninja** [PhilippC/keepass2android#1045]
As a follow-up to https://github.com/PhilippC/keepass2android/issues/1037 (Thank you for helpeing me out with finding the correct setting!)

Fennec (firefox 68.2), Android 8.1, lineageos 15.1). I am using autofill and when I tap an entry field for user name on a website I get 3 options:
1. the last entry I used from the database (eg if I just logged in on the hotmail website, and fo to Yahoo, it will propose to enter Hotmail-data)
2. Fill in using KP2A
3. disable auto-fill

I choose number 2, and it shows me the list of ALL entries I ever used in Fennec with KP2A. (all with the KP2A_URL_1": "androidapp://org.mozilla.fennec_fdroid"). On top of the list it says "search results for  androidapp://org.mozilla.fennec_fdroid", so not the actually URL from the website. Is this the way it should work or is something going wrong?

**Comment by PhilippC** [comment]
what's your app version? It is working with 1.08-pre3 (https://play.google.com/apps/testing/keepass2android.keepass2android) for me with Fennec Fdroid.

**Comment by Bug-Ninja** [comment]
I have 1.07b-pre, the latest offered to me through Play store.
