### ISSUE TITLE
The app is not functioning with non-KP2A keyboard selected upon start

### ISSUE THREAD

**Issue by ksgubanov** [PhilippC/keepass2android#1048]
When opening the app, the "Change keyboard" dialog pops up (why, btw?)
If "Keepass2Android" keyboard is selected, everything works fine.
If any other keyboard (Gboard or SwiftKey in my case) is selected, only blank screen is shown. By clicking back, the previous view is visible for a short moment, then the cycle with the "Change keyboard" dialog is repeated.
If I open any record, the same dialog popes up again (if non-KP2A keyboard is active). Seems that it can be deactivated in settings, but still the availability of app pages should not depend on the keyboard selected at the moment.

Phone: Xiaomi Mi 9T (same problem with MIUI 10 and with buggy MIUI 11)
KP2A version 1.07b-r0

**Comment by PhilippC** [comment]
please go to settings - app - security and disable "use built-in keyboard in KP2A".
