### ISSUE TITLE
Synchronize: apparently no settings

### ISSUE THREAD

**Issue by hierozbosch** [PhilippC/keepass2android#1049]
There seems to be no option under Settings to determine where keepass2android is synchronizing.  When I choose "Synchronize database" (in version 1.07b-r0), I very quickly get a "Files are in sync" message.  However, I have no idea what it is synchronizing with.  At some point I must have set up a sync target, but I can't remember what it is, and I can't find any option under Settings to update it or even find out the current setting.  My best option at this point seems to be to erase all local copies of the database on the device and possibly do a clean re-install.  Am I missing something?  Thanks, I love the app!

**Comment by PhilippC** [comment]
Where is your database located? You can see this on the password screen by pulling the header down?
KP2A works by Opening files from a location of your choice (e.g. Dropbox) and then it will always read from/write to this file. It will also have a local cache copy which can be used while offline.

**Comment by hierozbosch** [comment]
Thanks PhilippC! 

I read your suggestion about the password screen.  I suppose this means
the login screen, when I'm logging into the database.  Haven't tried
pulling the header down (although that sounds obscure). 

However, as I was closing the database, planning to log back in again to
try this, I stumbled on two other answers: 

The best is simply selecting File > Open Recent.  Then it shows what
database file is currently open with full path in blue, followed by
[open]. 

Also, when I clicked File > Close,  I got the following message: 

The current database has been modified: 
C:\\Users\Matt\Desktop\keepass.kdbx 

So there it is.  I needed to know this because I'm making changes on one
device and syncing to another device and the changes don't show up. I
need to know whether both devices are reading from the same database. 

Now I can see that I'm saving to a local drive instead of my shared NAS
drive.  I prefer to keep my database on a local NAS drive and not on
Dropbox because Dropbox is just not part of my day-to-day lifestyle. 

Thanks, 

Matt Hodges 

---

Matthew Hodges
GeoCertify, LLC
e: hodges@geocertify.com

On 2019-11-19 19:45, PhilippC wrote:

> Where is your database located? You can see this on the password screen by pulling the header down?
> KP2A works by Opening files from a location of your choice (e.g. Dropbox) and then it will always read from/write to this file. It will also have a local cache copy which can be used while offline. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/PhilippC/keepass2android/issues/1049?email_source=notifications&amp;email_token=ABAXNH3GNNHAEQL4P5C4WD3QUSCBJA5CNFSM4JOWW32KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEQJHEA#issuecomment-555783056
[2]

**Comment by PhilippC** [comment]
File > Open or File > Close as well as C:\... all sound a lot like you are talking about a Windows tool like Keepass2 or KeepassXC, but this is the issue tracker for Keepass2Android. 
I suggest you put a copy of your database on the NAS. For the Windows tool, either open it from there directly, e.g. through a network share or synchronize it with the NAS using WebDav.
Make sure that you have enabled something like SFTP oder WebDav on the NAS. Then use Keepass2Android's "Open file" and select the file on the NAS. It will have a local (internal) cache copy and will automatically sync with the NAS file if available. If the NAS is not reachable you can still work with the database and sync later.

**Comment by hierozbosch** [comment]
Thanks Philipp,  yes I lost track of what I was doing... I was having
difficulty with the Keepass2Android after all.  I have taken your advice
and re-opened the database directly from the NAS.  Alles gut!

---

Matthew Hodges
GeoCertify, LLC
e: hodges@geocertify.com

On 2019-11-30 03:51, PhilippC wrote:

> File > Open or File > Close as well as C:... all sound a lot like you are talking about a Windows tool like Keepass2 or KeepassXC, but this is the issue tracker for Keepass2Android.
> I suggest you put a copy of your database on the NAS. For the Windows tool, either open it from there directly, e.g. through a network share or synchronize it with the NAS using WebDav.
> Make sure that you have enabled something like SFTP oder WebDav on the NAS. Then use Keepass2Android's "Open file" and select the file on the NAS. It will have a local (internal) cache copy and will automatically sync with the NAS file if available. If the NAS is not reachable you can still work with the database and sync later. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/PhilippC/keepass2android/issues/1049?email_source=notifications&amp;email_token=ABAXNH2UUDIBE4WCTCJ65HLQWISRDA5CNFSM4JOWW32KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFP5PMQ#issuecomment-559929266
[2]

**Comment by PhilippC** [comment]
I'm glad it's working now!
