### ISSUE TITLE
Request: Face Unlock

### ISSUE THREAD

**Issue by madbot69** [PhilippC/keepass2android#1052]
Please add the new face unlock feature (pixel 4/4XL). :-) 

Some password managers have started adding this feature - would love it for keepass2android

**Comment by PhilippC** [comment]
please switch to https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by dolphinkite** [comment]
Hi,

I'm using the offline version of keepass2android (blue icon) and it seems that even though I joined the beta program (link above), I'm not receiving a beta update of the offline version. 

Like others, I want to use the face unlock feature on my Pixel 4.

Is there specific I need to do for this version?

Thanks
