### ISSUE TITLE
Keepass  specific folder in OneDrive

### ISSUE THREAD

**Issue by Uvaly** [PhilippC/keepass2android#1053]
I just installed Keepass2Android because it should allow me to access my KDBX database on OneDrive. I guessed that when opening a OneDrive database, I could choose the Keepass2Android folder as the safest option, without giving Keepass2Android access to my whole OneDrive for business. But from there, I was not able to create a new database ("Cannot get path item without share", and nowhere on the internet to find the meaning of this error) or open an existing one (I don't know which folder on OneDrive I should put my KDBX file in). It may not be a bug, it may be just missing documentation, perhaps just a paragraph in the FAQ section, or it might be that I am unable to find the correct documentation - but actually, I would consider that a bug as well, because I may not be the only person who has no clue about how to set OneDrive up in this way... Thank you so much for this app, and hopefully I will figure out how to use it :)

**Comment by jedanielee** [comment]
I normally use Google Drive. I've been trying to use OneDrive more. Here's a screenshot of the error
 I get.

![Screenshot_20191215-203204](https://user-images.githubusercontent.com/58926917/70879731-53777e80-1f7b-11ea-9bce-2025c850579a.png)

**Comment by davidgaloustov** [comment]
I'm having the same issue.

**Comment by dsent** [comment]
Yep, having the same bug here. Something must've changed in the API.
