### ISSUE TITLE
How to back up the key file?

### ISSUE THREAD

**Issue by Eqatrpfvvzzih** [PhilippC/keepass2android#1056]
I have a keepass2android database. When I open, it requires a password and a key file. It works, I can open it.
I would like to back up this database.
But I cannot.
Because I can export the database itself, and succeeded to copy it through USB cable to my PC. I do not forget the password (I remember it). But where is the key file? I cannot found. Keepass2android, at opening, shows the name (with path) of the key file.
I have initiated a complete file search for that name (in the android file manager), but there is no such file. (Maybe it is so hidden and/or protected, that I cannot make any backup of it?)
There is no way to back up it?
I cannot recall surely but maybe I created this key file with some import. (And deleted the one which I impoted from.) Or I have made keepass2android to generate for me a key file. I do not remember.

**Comment by PhilippC** [comment]
this sounds weird, because KP2A cannot generate keyfiles, it always takes existing ones.
I suggest you change the master password to not use a keyfile (or export as unencrypted xml which you can import into a new database with Keepass2) and then use a newly generated keyfile again.
