### ISSUE TITLE
Try Autofill with Chrome

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#1061]
A user says it's working wiht Bitwarden without accessibility

**Comment by hbiel** [comment]
I'm currently investigating Bitwarden and love the way it works on Android. It still needs the accessibility service for Autofilling in Chrome and other applications but works using the same Autofill popup menu (without having to pull out the notification). Hope this helps! Would love a similar feature for Keepass2Android.

**Comment by finderAUT** [comment]
Did not check for some time now but it is broken for a long time already for KP2A as well as Bitwarden and all the others...
For Bitwarden see https://github.com/bitwarden/mobile/issues/489
Related Chromium Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1015381

**Comment by hbiel** [comment]
Is there a continuous build available from where I can get an apk file including this fix?
