### ISSUE TITLE
Solve a problem

### ISSUE THREAD

**Issue by alsophee** [PhilippC/keepass2android#1068]
When you enter the application it takes a long time and consumes a lot of maga bit just to enter and explore please reduce the entry time

**Comment by Karreg** [comment]
duplicates #883

**Comment by alsophee** [comment]
When you enter the application it takes a long time and consumes a lot of megabits just to enter and explore please reduce the entry time

**Comment by alsophee** [comment]
When you enter the application it takes a long time and consumes a lot of megabits just to enter and explore please reduce the entry time

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PhilippC** [comment]
please stop spamming. As @Karreg mentioned, this was already discussed in #883.

**Comment by alsophee** [comment]
That's just a suggestion that can only be discussed in the problem.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
