### ISSUE TITLE
Enhancement - activate search field upon unlock

### ISSUE THREAD

**Issue by nathaniel-mahieu** [PhilippC/keepass2android#107]
When opening a database the user almost always wants to locate and retrieve an entry immediately. It would improve usability greatly if after entering the master password one could immediately be presented with a keyboard entry filling the search box.

This behavior would be similar to the behavior when opening the app - the password box is active and a keyboard opened.

**Comment by PhilippC** [comment]
but many users don't search by typing but by browsing their folders?

**Comment by nathaniel-mahieu** [comment]
True.

I don't think this change would impede their flow, though.  As presented now the active search box view still contains five folder/entries on a Nexus 5x.  Scrolling and tapping work fine, and clicking through a folder with the keyboard up doesn't add a tap for those users manually browsing to an entry.

For additional consideration, opening a keyboard dialogue can be slow when switching between apps to grab a password. (Is it opening a keyboard systematically slower than closing one?) The primary goal is removing that pause.

For reference I run a Nexus5x. Not sure how obsolete I am in regards to the average user's lag.

**Comment by kevin1979** [comment]
I came here specifically to request the option to enable this functionality. 

First, I really appreciate the app and happily made a beer contribution last year through the Donate app on Google Play. 

Every time I unlock my database the first thing I want to do is search the db. As the db has become bigger over time, it is an even more common occurrence over browsing folders. Probably 80% of the time. 

Having an opt-in *option* of the search field automatically selected would really help my workflow, especially on taller phones where it takes a two-handed adjustment to select the search box up top.

Thanks for the great app, this would make it even greater in my opinion.
