### ISSUE TITLE
FTP no longer working in 1.08-pre3

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#1070]
A user reported on Do., 7. Nov., 09:19 that a file accessed through FTP can be opened with 1.07 but not 1.08. This looks like an issue with switching to FluentFTP.

**Comment by SebastianBerlin** [comment]
I can agree that after switching from WebDAV to FTPS while using the beta version. Back to current stable-version 1.07b-r0 and everything is back to 'normal'.

**Comment by PhilippC** [comment]
the user who reported this originally confirmed that this is fixed in 1.08-r0. @SebastianBerlin  can you confirm, too?

**Comment by PhilippC** [comment]
closing as no response. please re-open if needed.
