### ISSUE TITLE
Copy TOTP automatically when autofilling a login that has one

### ISSUE THREAD

**Issue by serovar** [PhilippC/keepass2android#1072]
Bitwarden and other password managers have this feature that is very convenient when you have to login to websites for which you have a TOTP in their KeePass database entry.

Alternatively, a notification with the option to copy the TOTP could show up after autofilling (so that you don't have to open the entry manually to see it).

![Screenshot_20191211-003412](https://user-images.githubusercontent.com/6732420/70578459-b8129200-1ba5-11ea-97e2-9404c4689376.png)

**Comment by gabrielambuehl** [comment]
Just came here to ask for this, too. I would prefer the notification to copy so that we do not overwrite the clipboard...

**Comment by gabrielambuehl** [comment]
Ok so latest pre release shows the TOTP after searching for an entry, any chance to also get it after using autofill?

**Comment by coalwater** [comment]
> Any chance to also get it after using autofill?

I'm also really missing this feature, i love that i can autofill in a browser or app, but if that login requires otp i have to open the app and do a manual search and open the entry to copy the code from notification.

Would be really nice if you provide a way to easily copy otp code after autofil

**Comment by gabrielambuehl** [comment]
No need to manually search, you can share the site to keepass2android and then get the notification. Obviously not as comfortable as it showing up automatically after autofill.

**Comment by gabrielambuehl** [comment]
I am not totally sure that commit fully works. For some tries in Firefox it worked, for others seemingly not (on github.com no less). If the notification doesn't show up automatically I get it via sharing so in principle it knows about the TOTP...

**Comment by PhilippC** [comment]
@gabrielambuehl how did you test? This commt is not contained in any release I did so far?

**Comment by serovar** [comment]
@PhilippC I think this issue should be reopened, since that commit does not solve the issue. The only way to get the notification to appear remains to open the database entry manually or by sharing the website to the app. I also think that autocopy of the TOTP would be more comfortable, since you have to copy it from the notification anyway (see the Bitwarden solution in the screenshot in the first post).
