### ISSUE TITLE
Fingerprint database unlock

### ISSUE THREAD

**Issue by dasgrischa** [PhilippC/keepass2android#1077]
Some days ago the fingerprint unlock stoped working.

I tried to disable it in settings, it worked. But after I tried to enable it again I'm getting an Java runtime error or something like that. It's a pretty long error screen.

Tried to reinstall today, didn't work.

Running:
op6_O2_Beta_31 
(Oneplus 6 Beta of Android 10)

Any suggestions? 

EDIT:
Reinstalled the app without the Beta program, now it doesn't show the Java error but the app shows a normal Android Error screen that the app stoped working. So not really a progress...

**Comment by PhilippC** [comment]
you might try with KeepassDX or Keepassdroid, I guess it's the same there. Then please contact OnePlus to notify them about this problem. I don't see a solution on my side.

**Comment by dasgrischa** [comment]
Im using this app version btw  1.07b-r0

Tried with both KeepassDX and Keepassdroid, can"t even set it up. So I guess it"s the same issue.

Gonna contact Android support, because I think it"s the Android 10 Beta and not OnePlus update.

But thanks for the answer, Phillipp. Appreciate your work.

Gonna close this thread at the end of the week.

**Comment by PhilippC** [comment]
Android 10 is fine, but OnePlus users are reporting this repeatedly.
