### ISSUE TITLE
Microsoft edge android

### ISSUE THREAD

**Issue by Coryrichter94** [PhilippC/keepass2android#1086]
When trying to fill any website in the Microsoft edge app it pops up with androidapp and doesn't actually show websites. It thinks it's trying to fill an app instead of the website you are currently on.

**Comment by Coryrichter94** [comment]
![Screenshot_20191220-162856](https://user-images.githubusercontent.com/25600777/71294261-fd715500-2345-11ea-821e-e1778b854ec3.png)

**Comment by sba923** [comment]
Same here. Globally, Keepass2Android hasn't been able to guess the entry and thus autofill in web forms for quite a while now. This used to work like a charm! ;-(

**Comment by SESNut** [comment]
still have this problem

**Comment by artgru** [comment]
are there any plans for including the support for new Edge on Android? 
Microsoft is actively developing their main browser based on chromium, so having a working kp2a on that browser would work nicely ;) @PhilippC 

btw. have you considered feature idea donation / project sponsoring here on github?

**Comment by PhilippC** [comment]
I don't think there is anything KP2A can do about this. Is Autofill working with other password managers like Bitwarden?

**Comment by sba923** [comment]
I'm not sure what the issue is. Just filled in a login page in Edge 46.02.4.5145 running on Android 10 using KP2A 1.09a-pre1 and it worked like a charm!

**Comment by artgru** [comment]
Indeed. I've rebooted my phone today and kp2a started filling up my credentials 🗡️ 
So no issue here :P
