### ISSUE TITLE
Autofill ist broken in latest Firefox Beta

### ISSUE THREAD

**Issue by xathon** [PhilippC/keepass2android#1089]
You can enter the app and your credentials, but after taking you back to the browser they are not in the text fields.

Firefox Beta V.68.4

**Comment by kimperator** [comment]
It is even broken in the latest stable release v68.3.0

**Comment by PhilippC** [comment]
I can't reproduce. Using Firefox for Android v68.3.0, going to www.amazon.de (in a new private tab), click the Login ("Anmelden"), click "Autofill" in the email field, select an entry and username will be filled.Click the "Next" ("Weiter") button to continue, same works for the password. Does that work for you (i.e. is it dependant on the target site) or not? Which App version are you using?

**Comment by juhovan** [comment]
I have this issue as well, with amazon.de and any other site.
Firefox Version 68.5.0, keepass2android Version 1.08-r1 and Oxygen OS 10.0.4.GM21BA.
android received an update a while back, not sure if it was broken before that.

**Comment by PhilippC** [comment]
can you record a video demonstrate what exactly you are doing?

**Comment by juhovan** [comment]
Somehow in Firefox it started working again even though nothing has received updates..

I also tested caldav-sync and there it still doesn't work but I'm not 100% certain that it has worked before.
For some reason I can't attach the video but see the URL below:
https://nc.24-7.fi/s/7J9HZsFCeXx9nJg
Keepass blocks its window but it just very briefly flashes as there is only one entry for this app.

**Comment by yaakovfeldman** [comment]
I have the same issue on Firefox 68.5.0. It suddenly stopped working on any site.

**Comment by yaakovfeldman** [comment]
It has started working again. I suspect this is a Firefox issue, as Firefox was behaving strangely today in other ways. I force stopped Firefox (should have restarted phone instead) and all is working.

**Comment by 1251** [comment]
I have a Google Pixel 3a with Android 10, Build QQ3A.200805.001. In Firefox for Android, version 79.0.5, with Keepass2Android 1.087b-r1, the AutoFill is completely unusable. Selecting a username or password field only leads to a very short flash of the AutoFill option. When the Android keyboard is not visible (e.g. if you open the Firefox menu and then go back, so that the keyboard disappears), the AutoFill option stays. But even then, it does not work anymore, because selecting the correct password entry leaves the field blank... I can deliver a screen video if you wish.

**Comment by xathon** [comment]
The same happens in Firefox Beta 80.0.1-beta.2 wit 1.08b-r1. It only flashes up very short, scrolls the screen up a little, and disappears again.

**Comment by 1251** [comment]
@PhilippC maybe re-open this issue?

**Comment by Haini** [comment]
I have the same issue with Firefox 84.1.4 on Android 10 (Huawei P20 Pro) and even in Chrome. 

Brief flashes or no detection at all. Same in Chrome for Android.

**Comment by PhilippC** [comment]
please see #1399 for further discussion
