### ISSUE TITLE
Overwriting clipboard does not work if there can be multiple ones

### ISSUE THREAD

**Issue by xZise** [PhilippC/keepass2android#109]
Hello,
I'm quite happy with Keepass2Android itself, but I noticed that the clipboard on my phone can store multiple items. And in that case it does not actually overwrite the password after a certain time but just enters a new one.

I don't know if it is possible to have a workaround in that without actually modifying the software a lot. I'm using a Samsung Xcover 4 with their "stock" Android.

**Comment by PhilippC** [comment]
you should see a toast message indicating that you need to check if clearing the clipboard works on your system and that you may switch to using the built-in keyboard if it does not. I cannot prevent other apps from logging clipboard contents and remembering these contents, so this cannot be solved.
