### ISSUE TITLE
Fingerprint Not working

### ISSUE THREAD

**Issue by evzhcl** [PhilippC/keepass2android#1090]
Using a new Galaxy S10 the fingerprint sensor seems not to work. 
It appears that it cannot initialise the sensor. 
Using version 1.07b-r0
![IMG-20191223-WA0000](https://user-images.githubusercontent.com/7442941/71378628-d70f1c00-25c8-11ea-896b-fd67674f1972.jpg)

**Comment by vukasin-nikodijevic** [comment]
I have similar message for Xiaomi Mi Note 10 - I'm pretty sure that issue comes because both phones are using `In Screen Finger Print`.

I see other apps like Protonmail, N26, Paypal ... - has no issues with this as FP is presented as popup over the app login page.

**Comment by sniner** [comment]
Same for my OnePlus 7T Pro. That model also comes with an in-screen fingerprint sensor.

**Comment by vukasin-nikodijevic** [comment]
it is fixed in 1.08 pre release - plz check my comment
https://github.com/PhilippC/keepass2android/issues/1025#issuecomment-568911435

**Comment by evzhcl** [comment]
Sadly I cannot join the beta to get 1.08 so I can't test it. The beta program seems to be full. Can some spots be added or is there another way to get 1.08?

**Comment by evzhcl** [comment]
I was able to test it with 1.08 and it works now
