### ISSUE TITLE
Simple Question - how to find all kdbx files 

### ISSUE THREAD

**Issue by thebrenda** [PhilippC/keepass2android#1091]
Not an issue, just a question.

I do not synchronize. Just copy a kdbx file to my android phone. I have deleted all kdbx files from my android but KeePass2Android keeps opening up a copy of my kdbx. With Show Local Backups this are displayed on the bottom of the Open File screen. I can open this file with my password. How can i delete it?

/data/data/keepass2android.keepass2android_nonet/no-backup/contentKeepassbxg.kdbx

**Comment by PhilippC** [comment]
you can do this by clicking the three vertical dots next to the filename.
