### ISSUE TITLE
Feature idea(s): Add "Copy TOTP" to notification

### ISSUE THREAD

**Issue by andschwa** [PhilippC/keepass2android#110]
Hello,

I switched from LastPass to KeePassXC + Keepass2Android synced over Nextcloud, and I love it. After a few months, I've identified three things in K2A I'd like to fix:

## Add "Copy TOTP" to notification

Similar to "Copy User" and "Copy Password" in the entry notification, I would personally find it useful to have "Copy TOTP" when it's in the entry.

I haven't done any Android development, but I'm willing to give it a try, and I'll probably start with this one as I can't imagine it's controversial.

## Better long password handling

I have some _really_ long passwords, and I find that once they're past the width of the screen, when the entry is being displayed, it just gets cut off. You also can't scroll it. Sure, you can copy it, but in the case of giving some my guest Wi-Fi passphrase, or entering a BitLocker recovery key, you have to edit the entry, to bring the password into the Android text entry form, where you can scroll it.

Similarly, when unlocking the database, once your text gets to the side of the screen, it actually gets hidden by the "make visible" eye-shaped overlay button, and this is annoying.

## Make reveal password not move cursor

The final thing that bugs me is that I start to enter my password to unlock the database, then I click the "make visible" button, the cursor moves back to the front, instead of staying put. It's a small thing, but it's annoying.

**Comment by andschwa** [comment]
Just by the way, I tried to get started on this, and honestly gave up. The build process is so bad guys 😦 (and I am intimately familiar with really bad builds).

For anyone interested, these feature requests are up-for-grabs. I am no longer planning to work on them, but I think they'd make an already great app even better.

**Comment by samueltardieu** [comment]
Adding TOTP to notification would be a huge time saver indeed.

**Comment by whitep0wer** [comment]
Exactly what was on my mind for quite a while now. I started using KeePass for TOTP over a year ago and I'm never coming back to separate auth apps again :P
