### ISSUE TITLE
[Bug Report] New Project. I can not add more fields！

### ISSUE THREAD

**Issue by Memorainer** [PhilippC/keepass2android#1105]
I created a new password entry in 1.70b-r0（not offline！）, but I found that the default template page can only fill in one entry, I can not add more? Or, where is the entry point for adding additional entries?
The e.g: http://imgbox.com/PgkpWT2e
Device Environment：
HUAWEI Mate 20 Pro
EMUI 10.0.0（Android 10）

**Comment by PhilippC** [comment]
not sure what you mean "default template page" - the default entry should have + button to add more fields? 
What you observe with a templated entry, however, is a bug which has been fixed recently (please wait for next update), so I'm closing this.
