### ISSUE TITLE
Google will remove Play Store apps that use Accessibility Services for anything except helping disabled users

### ISSUE THREAD

**Issue by okoetter** [PhilippC/keepass2android#111]
The title says it all, you can read more about it here: 
[http://www.androidpolice.com/2017/11/12/google-will-remove-play-store-apps-use-accessibility-services-anything-except-helping-disabled-users/](http://www.androidpolice.com/2017/11/12/google-will-remove-play-store-apps-use-accessibility-services-anything-except-helping-disabled-users/)

If I'm not wrong this will affect Keepass2Android seriously. We have an alternative beginning with Android Oreo once the use of the [Autofill Framework](https://developer.android.com/guide/topics/text/autofill.html) has been implemented in Keepass2Android, but I guess some comfort features in Keepass2Android are lost for older Android versions.

@PhilippC: Did you also get a mail from Google about this?

**Comment by PhilippC** [comment]
yes I did. Will try to create a plugin to compensate for this, but it's really annoying. Anyway, I won't risk being removed from Google Play...

**Comment by DJCrashdummy** [comment]
...another reason to publish via f-droid (#38) or at least akps (https://github.com/PhilippC/keepass2android/issues/38#issuecomment-341652382) (which can be easily included into alternative repos).

**Comment by user8446** [comment]
Is there a way to comment back to google regarding this? There are many legitimate apps that rely on accessibility services - password managers, app locks, button mappers, etc. Maybe if enough developers reach out google might think of an alternative  - like a popup warning like when selecting installation from unknown sources.

**Comment by PhilippC** [comment]
I did not find a way to communicate with Google on this :-(

**Comment by LegoChicken** [comment]
See their recent blog https://android-developers.googleblog.com/2017/11/getting-your-android-app-ready-for.html
"The Autofill API is open for anyone to implement a service. We are actively working with 1Password, Dashlane, Keeper, and LastPass to help them with their implementations towards becoming certified on Android. We will be certifying password managers and adding them to a curated section in the Play Store, which the "Add service" button in settings will link to. If you are a password manager and would like to be certified, please [get in touch](https://docs.google.com/forms/d/e/1FAIpQLScem3Xhk4991YKhX3YtPUZ7_YSuFZGacdH5r5yFO8lrSMQNqA/viewform?usp=sf_link)."

**Comment by okoetter** [comment]
As I wrote the Autofill API is only implemented starting with Android Oreo. Marketshare <0.5% at the moment.

**Comment by pehlm** [comment]
Yes, but it's possible that passwordmanagers can receive reprieve "from possible upcoming removals from the Play Store" as they write on [Androidauthority](https://www.androidauthority.com/lastpass-google-accessibility-services-815528/). So it's important to contact Google.
