### ISSUE TITLE
Logging in to onedrive opens the builtin (samsung) browser instead of the default

### ISSUE THREAD

**Issue by Marwes** [PhilippC/keepass2android#1113]
Opening it in the default would be expected and less of a hassle since it is less likely to be outdated.

**Comment by PhilippC** [comment]
On most devices, you shouldn't see a different app/browser starting but just have a login screen inside thap. But this behavior is out of control of KP2A but defined the by the MSAL library. There have been a few discussions about similar topics (e.g. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/534). I guess they use Samsung browser as a fallback.
