### ISSUE TITLE
Does not ask for a fingerprint and I do not remember the original password

### ISSUE THREAD

**Issue by ruloringlet** [PhilippC/keepass2android#1115]
I have a Note10 + with android 10 (version 1.07b-r0) and it doesn't ask for my fingerprint anymore, I can't access the database because I don't remember the password.
How can I do?
My English is very bad :(

**Comment by bengalih** [comment]
You are out of luck.  Biometric is convenience, you should never misplace your original password.
In order to reset/troubleshoot fingerprint login you must first be logged in.  Without a password this is impossible.

**Comment by PhilippC** [comment]
please also see the documentation at https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md
