### ISSUE TITLE
Request: 2factor Entry type

### ISSUE THREAD

**Issue by brandoncreed** [PhilippC/keepass2android#1116]
Would it be possible to add an entry type which stores 2factor passcode and displays the authentication code when viewed?

**Comment by PhilippC** [comment]
KP2A is already compatible to TrayTOTP, KeeOTp, KeeWeb and KeepassXC. What's missing, though, is a built-in template to easily create new entries with TOTP codes

**Comment by carun** [comment]
It would be great addition to have this feature. :smiley:

**Comment by PhilippC** [comment]
this is now supported with the "configure TOTP" button in the entry edit view. (1.09d will extend this by adding a "Scan QR code" button in the TOTP dialog)
