### ISSUE TITLE
Number row on keyboard

### ISSUE THREAD

**Issue by IByte** [PhilippC/keepass2android#1117]
Hi. I'd like to see an option to turn on a permanently visible number buttons row at the top of the Keepass2Android keyboard, as available in Gboard and many others. Thanks in advance for considering it.

**Comment by feadraug** [comment]
The same question.

**Comment by PhilippC** [comment]
sorry, keyboard is not intended to be any replacement for "real" keyboards and I don't see it's worth putting effort into it.

**Comment by speedwellsoftware** [comment]
@PhilippC actually this keyboard is superior to anysoft, Samsung and stock keyboard for its neat key spacing, quick special key access, secure keepass entry and I just switched to it as my default! I often toe numbers mixed with letters and having a separate row is the only missing feature from anysoft I used before...

**Comment by schuft69** [comment]
Same here, my passwords contain many numbers - adding a permanent number row would speed up my typing enormous.
