### ISSUE TITLE
Keepassxc Challenge, Synchronize database slow

### ISSUE THREAD

**Issue by rajil** [PhilippC/keepass2android#1118]
Hello,
I have am using Keepassxc with Yubikey challenge. The initial login/load from the Nextcloud database is quite quick on Samsung Note 9 (Argon2 default cipher). However, if i do a "Synchronize database.." on a open database the device gets stuck on "Transforming key" for  a long time.

**Comment by PhilippC** [comment]
...for a long time but then finishes, or ..gets stuck forever?

**Comment by rajil** [comment]
I tried it again and this time round it was pretty quick.
