### ISSUE TITLE
Does not open database from google drive

### ISSUE THREAD

**Issue by bunnyhu** [PhilippC/keepass2android#1120]
It does not open my database from my google drive. I try to remove and add again. It see the file when I select, then said: it cannot open the file, working only local version.
It is worked well in the past.

Xiaomi mi9SE , Android 9, latest MIUI stable version.

**Comment by pshem** [comment]
Try the solution from https://github.com/PhilippC/keepass2android/issues/417#issuecomment-397950135

Go to Android settings > Apps > Keepass2 > Permissions, remove the `Contacts` and `Storage` permissions, then add the permissions again. Upon attempting to access a file stored on Google Drive in KeePass you should then see a prompt to allow access and everything should work nicely afterwards.

**Comment by bunnyhu** [comment]
I tried, It does not help. I remove all permission, then restart the app. It ask me the permission, I give it again. Still cannot open the gdrive. I remove the gdrive file, add again, then still cannot open.

**Comment by bunnyhu** [comment]
Actually I solve it. Remove the database, all permission and DELETE THE APP DATA. Then it restart completly, show the what's new dialog etc and then working. So delete the app data that you need.
