### ISSUE TITLE
Feature Request: Allow biometric unlocks in addition to finger print unlocks

### ISSUE THREAD

**Issue by w00tazn** [PhilippC/keepass2android#1123]
Would like to be able to use Android 10's biometric manager to allow face recognition to unlock the keepass database. (Google Pixel 4 does not support fingerprint unlocks)

https://source.android.com/security/biometric

**Comment by kdaq** [comment]
See https://github.com/PhilippC/keepass2android/issues/1082

**Comment by Utini2000** [comment]
Any idea when we will see this beta being released as stable? :)

**Comment by Utini2000** [comment]
Yep, same here for me :D Pixel 4 XL is awesome but the lack of fingerprint/faceunlock is really annoying. Especially with an endless long digit password for the database :S

**Comment by PhilippC** [comment]
already implemented (https://play.google.com/apps/testing/keepass2android.keepass2android)
