### ISSUE TITLE
Hide path to key file

### ISSUE THREAD

**Issue by Bondarz** [PhilippC/keepass2android#1128]
Hello, is it possible to hide the path to the key file somehow? 

With the smartphone, not everyone needs to know where the file is in case of theft.

**Comment by PhilippC** [comment]
there is settings - app - security - remember database. you will have to select the database location each time you start.

**Comment by Gittyperson** [comment]
Just wanted to post about this. Hope you can find a middle way. The option to hide/obfuscate part of the full path/key filename makes a lot of sense security-wise. Sure, disabling 'Recent' items altogether is the nuclear option but it greatly reduces functionality.

**Comment by PhilippC** [comment]
if you use Android filebrowser to browse to your key file, it should show "content://abc.key" and not the full path.

**Comment by Gittyperson** [comment]
I think we are talking about these Keepass2Android screens, not a filebrowser:

1. Change database/Open recent database
2. Unlock database

I use a single SFTP database. In both screens above, the full path is visible. The database is of course locked in both these situations.

**Comment by Gittyperson** [comment]
Don't know how feasible this is, but perhaps an idea would be for the user to assign a 'nickname' to their database(s). So, in 'recent' databases lists only the nickname would appear instead of the full path and filename.

**Comment by Gittyperson** [comment]
Following my previous post: of course there's no need for a special 'nickname': a Database can be named natively. So, if a DB is named, you could simply show the Database name instead of the full path in the "recent databases list".

This would solve everything, in a simple, elegant and meaningful way without exposing the path.

**Comment by balvie** [comment]
When opening the app, the default database is selected. Also, in this dialogue, the name of the key file is visable.. Since the key file name is part of the security, I do not like to have its name visible in this dialogue. So, please make ik invisable.
