### ISSUE TITLE
Truly offline version and no 3rd party file manager support

### ISSUE THREAD

**Issue by kevin789900** [PhilippC/keepass2android#113]
For many months I had noticed that I was getting errors like  "keepass can't open from remote"... while I was using the **offline** keepass2android.  I never looked into this but at some point couple months ago I noticed that it was referencing a cache file in a path used by a 3rd party file manager app (which I deleted a long time ago).  I tried to export the file but that failed also (I believe Philipp has looked into this issue).  I have been waiting for next version to fix so I could export and make a long overdue backup.  I tried re-installing the file manager app hoping it might recreate cache path but still failed.

Now in past couple weeks I cannot even open open my file :-(  After entering my password I get:

> an error ocurred: permission denial: opening provider com.scanvgers.apps.filemanager.provider.ExternalStorageProvider from ProcessRecord{abe36da21:keepass2android.keepass2android_nonet/u0a226} (pid=21, uid=10226) requires android permision. MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS

My request is to make the offline version truly offline:
-show no options about being offline or online, it is only offline
-disable any 3rd party apps / file managers.  I don't want them to have my file or cache it in their path

Side note - I am 99 percent sure I had entered this issue here in github before but I cannot find it.

Thank you!

**Comment by PhilippC** [comment]
feel free to re-open https://github.com/PhilippC/keepass2android/issues/86, but the point of the offline variant is to have a password manager which has **no internet permission**. This proves to users that I am not going to transfer their credentials to m. 
I cannot create new variants for other features which nobody is forced to use or enable.

**Comment by DJCrashdummy** [comment]
@kevin789900 maybe you couldn't find the old issue, because you hadn't looked at the closed issues. :wink:
