### ISSUE TITLE
Bug/Improvement: Focus not on password field when starting app

### ISSUE THREAD

**Issue by Lineflyer** [PhilippC/keepass2android#1132]
I am currently using k2a version 1.08-pre3 on a Samsung Galaxy Tab S4 running Android 9 with the following problem:

Whenever I am starting k2a (either via autofill or just starting the app from its icon) it comes up with either password field or quick unlock password field as it should be. However the keyboard does not automatically open to allow entering the password. I first have to click the password field, only then the keyboard is shown and I can enter the password.

I am not really sure whether it started with that beta version or was like that already before. It would anyhow be more efficient if the password field is active directly when starting the app without the need to click on it.

**Comment by nift4** [comment]
For me on LineageOS 17.1 with latest stable (1.07b-r0) it works, so it is either an bug or an removed feature (what would be annoying).

**Comment by Lineflyer** [comment]
@nift4 Maybe you could try current beta 1.08-pre3 to check if the problem comes up with this version?

**Comment by nift4** [comment]
Beta does not focus.

**Comment by nift4** [comment]
Probably bug

**Comment by nift4** [comment]
BTW Using Beta to enable Fingerprint and then going back to Stable via Titanium Backup kilked my db. Hooray. Thx for Auto backups - nothing is lost.
