### ISSUE TITLE
Security bug that could raveled database password when unlocking database via fingerprint

### ISSUE THREAD

**Issue by mKoonrad** [PhilippC/keepass2android#1134]
I change unlocking feature of my database from password to fingerprint (option when my password is encrypted by Android build-in cryptographic key). Login screen looks like this:
![login](https://user-images.githubusercontent.com/11725227/73499386-434b1f80-43c0-11ea-904b-a05cac264b53.jpg)
When I first click on eye icon (to show my password), than I touch my fingerprint my database password appears until the database is unlocking. When I accidentally click on eye icon, than touch my fingerprint, people looking at my phone screen may see my password. If I use fingerprint to unlock my database it cannot be possible to see password, for security reasons.

**Comment by nift4** [comment]
That's hard. I forgot my password but with that method I got it back - then I wrote it up. But that's useful if someone forgets his password. What goes first - Security or User's Passwords?

**Comment by mKoonrad** [comment]
@nift4 Security is the most important

**Comment by tisboyo** [comment]
I believe related to this issue, when changing the database password from another source (PC) then attempting to unlock via fingerprint, after the failure for invalid password, Keepass2Android leaves the password in the entry box, allowing it to be viewed.
