### ISSUE TITLE
Harmonize AutoOpen with KeePassXC

### ISSUE THREAD

**Issue by PolyMMA** [PhilippC/keepass2android#1138]
Hi!

Firstly, GREAT APP! Thank you! :)

There seems to be an issue with AutoOpen feature. 

I synchronize my .kdbx across systems and devices using Dropbox. Works well.

In KeePassXC (Win10, but should not matter) I keep a slave database in the same folder as my master. Hence, in the AutoOpen group, in the associated entry, I refer to it in the URL field simply by "slave.kdbx" (relative path).

Subsequently when launching Keepassxc2Android on the phone, it finds a slave database but gives an error saying it cannot open the "/slave.kdbx" path. Notice the added "/"!
Ignoring this I go to Settings > Database > Configure sub. database (translating as I go here...) Here I see the slave.kdbx, I can activate it, I can edit settings, and set where the file location is. 
Choosing "Dropbox (KP2A-folder)" sets the actual URL: dropboxKP2A:///slave.kdbx
Choosing "Dropbox" sets the actual URL: dropbox:///apps/keepass2android/slave.kdbx

Choosing either and going back to KeePassXC (Win10 or Linux) results in the slave.kdbx not opening with master due to the modified URL.

Suggestion: 
If chosen URL conflicts with the already set one, have Keepassxc2Android save the chosen URL in  a custom attribute (along existing **IfDevice**, **Visible**, **Enabled**) like
**KP2A_URL_?**: dropboxKP2A:///slave.kdbx
**KP2A_URL_?**: dropbox:///apps/keepass2android/slave.kdbx
**?**: enumerator, tag or whatever works for you

and leave the original URL unchanged so that the AutoOpen feature can remain functional on the original KeePassXC.

Keepass2Android should then of course primarily check for **KP2A_URL_?** field in entries under AutoOpen, and secondarily for URL entries. 

Similar issues are 
#1040 
#1033 
#360 

Thank you! 

[Edit: 2020-02-04 - 09:07]
Adding the relative path **slave.kdbx** (used in the desktop application) to the "Additional URL's" under "Browser integration", while keeping original URL: **dropboxKP2A:///slave.kdbx** or **dropbox:///apps/keepass2android/slave.kdbx** will not make the entry open the slave database on desktop environment either.
The original KeePassXC manager will not let you enter **dropboxKP2A:///slave.kdbx** or **dropbox:///apps/keepass2android/slave.kdbx** under "Additional URL's" so the reverse method will not work either. 

Current solution:

Currently, the only solution I find is to have one entry for the slave.kdbx with URL: **dropboxKP2A:///slave.kdbx** or **dropbox:///apps/keepass2android/slave.kdbx**
and one clone of the same with URL: slave.kdbx. 
NOTE: Currently it is not possible to use AutoType with referenced password "{REF:P@I:UUID-hash}" since the AutoType {PASSWORD} will forward the actual reference tag instead of the content it is referencing to. So, do a static clone for now.

**Comment by PhilippC** [comment]
if different devices require a different URL, then please use IfDevice. In KP2A, you can very easily set up what you need by going ot settings - database - child databases and then select "Copy for this device". If you want to use relative paths, there is {DB_DIR}/slave.kdbx. 
This concept was developed in cooperation with Dominik Reichl (original author of KeePass) and KeePassXC should be compatible to this.
