### ISSUE TITLE
Add autofill support to Brave Browser

### ISSUE THREAD

**Issue by DeXeDeXeD** [PhilippC/keepass2android#1142]
Keepass autofill system feature doesn't work with Brave Browser (mobile).

**Comment by DaFlowah** [comment]
Having the same issue with version on OxygenOS 9.0.10. Running on beta 1.08-r0 of keepass2android.

**Comment by Small-Ku** [comment]
It is added in a recent commit 9d34dfe.
Please wait for next update.

**Comment by serzhshakur** [comment]
Hi,
when is it going to be released?

**Comment by nikolaikopernik** [comment]
No, it doesn't work for me. Version 1.15.73. android 11
