### ISSUE TITLE
Autofill not available

### ISSUE THREAD

**Issue by Isa76** [PhilippC/keepass2android#1146]
Hi,
i used the offline version bevor, it worked perfekt with autofill on Android.

Now, on the online Version, autofill is not possible to activate.

Do you know why? Thank you!

**Comment by abremora** [comment]
Can you describe your problem in more detail? 
1. Do you have problems with apps and browsers? 
2. Which browser do you use?
3. Which version of Keepass2Android do you use? 
4. Which version of Android do you use? 5. Did you activate the Keepass2Android Autofill service in the system settings?

**Comment by Isa76** [comment]
Thank you, number 5 was the problem. Easy to find, sorry to disturb :-)

**Comment by dasb00ter** [comment]
I should probably open a new issue but keepass2 android is NOT available to be selected as an Android service. I'm using the latest Q version February security update. 1.07b kp version. I've had similar issues before but they were resolved by uninstalling kp2a and deleting all related folders and reinstalling. 
Thanks for now I'm just switching keyboards to kp2a

**Comment by Small-Ku** [comment]
If the problem solved, please close the issue.
