### ISSUE TITLE
WebDAV authentication failure after okhttp update

### ISSUE THREAD

**Issue by drzony** [PhilippC/keepass2android#1149]
It seems that after update to okhttp client WebDAV authentication is broken on PUT requests, GET requests work fine.
According to logs from the WebDAV server PUT requests are not repeated with credentials after receiving 401 code (it works on GET), so the comms look like this
- GET - receive 401 from server
- GET - repeat request with credentials, OK
- PUT - receive 401 from server
- Display error toast with "NO ERROR" error and stream broken message

I've looked through Kepass2Android code and it seems ok, so this is probably a bug in okhttp

**Comment by PhilippC** [comment]
which version of KP2A do you refer to? Do you mean the latest OkHttp librarry update for the 1.08-r0 release?

**Comment by drzony** [comment]
It's hard to pinpoint the exact update since I rarely modify database on my mobile, but it seems that 4.2.2 update was the one that broke things. I'm using the latest beta version from Play Store.

**Comment by PhilippC** [comment]
do you think this could be related to https://github.com/square/okhttp/issues/4964 ? I am still waiting for a bugfix on it.

**Comment by drzony** [comment]
Yes I think this is a similar issue, 401 on the server probably causes stream reset. After disabling HTTP/2 everything works fine.
I think this might be a simpler way to reproduce this error for okhttp developers.
It's just plain nginx config with authentication and HTTP/2. I can provide examples if that would help.

**Comment by drzony** [comment]
Closed as it seems to be a duplicate of #747
