### ISSUE TITLE
Keyboard crashes when hardware keyboard is present and language selected

### ISSUE THREAD

**Issue by stepman0** [PhilippC/keepass2android#115]
I use Keepass2Android on a Samsung Galaxy Tab S3 with a hardware keyboard. 
In the normal keyboard, I can select the language of the external keyboard in settings. 
There is also the possiblity to select the language of the external keyboard when Keepass2Android-Keyboard is used. But when I do this, settings crashes and Keepass2Android gets unresponsive.

Using latest (non-beta) version of Keepass2Android from PlayStore

**Comment by PhilippC** [comment]
can you collect a logcat?

**Comment by stepman0** [comment]
Sure. Can you tell me how? -------- Originalnachricht --------Betreff: Re: [PhilippC/keepass2android] Keyboard crashes when hardware keyboard is present and language selected (#115)Von: PhilippC An: PhilippC/keepass2android Cc: stepman0 ,Author can you collect a logcat?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PhilippC/keepass2android","title":"PhilippC/keepass2android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PhilippC/keepass2android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PhilippC in #115: can you collect a logcat?"}],"action":{"name":"View Issue","url":"https://github.com/PhilippC/keepass2android/issues/115#issuecomment-344643198"}}}
