### ISSUE TITLE
TOTP SHA256 and SHA512 support

### ISSUE THREAD

**Issue by 3Goldjungen** [PhilippC/keepass2android#1155]
Hi, it seems that only SHA1 is currently supported.
I added an otp key with SHA-512 and 8 digits via KeePassXC, but only the entry without the generated TOTP is shown in the Android app.

**Comment by dekked** [comment]
I second this.

I cannot use Keepass2Android because it doesn't support SHA-256, which the desktop app does.

Any chance to add support for the other hash functions? 😇
