### ISSUE TITLE
OneDrive Target account being synchronized

### ISSUE THREAD

**Issue by BrendanHere** [PhilippC/keepass2android#1162]
Elho,

I have a situation where I have multiple OneDrive accounts for various things/environments (work, home, consulting gigs, etc...). I need to know which OneDrive account (associated email address) is being used, with which KP database. 

I've been completely unable to find anywhere in the app that shows me which OneDrive account I am synchronizing/updating - the associated email address.

Can you please let me know where that information is displayed, or if it isn't, can you PLEASE add that info to the application?

LOVE the app btw, really keeps me together on storing the mountains of accounts and passwords that I use throughout the week.

PS: all I see in the app, regarding my DB target is this kind of URL: onedrive:///KP/myKPDatabase.kdbx (I can't determine which email address is associated with that DB. 
Cheers,
Brendan

**Comment by PhilippC** [comment]
please click "Change database" - "Open file" - "OneDrive" and browse to the file again. This will then use the new OneDrive implementation which should show as onedrive2_myfiles://your@account.com/me/...
