### ISSUE TITLE
How to change the dB-file 

### ISSUE THREAD

**Issue by fizzlifax** [PhilippC/keepass2android#1164]
Hi
I have major problems with the use of my dB file from android, Linux and Windows!
especially in the android version there seems to be no possibility to change the dB file!?
why that or how to do it!? At least I would like to get a better dialog! 
thanks a lot in advance!

Fizz

**Comment by lostgit** [comment]
Press back until you see "Change Database"

**Comment by PhilippC** [comment]
Click the lock icon. On the quick unlock page tap "Close database". You should then see a button "Change database".
