### ISSUE TITLE
Referencing 2FA fields via {S:<Field Name>}

### ISSUE THREAD

**Issue by AlexCherrypi** [PhilippC/keepass2android#1165]
I was wondering if you could implement the {S:<Field Name>} reference as described in [the Keepass Placeholder Syntax for KeePass 2.x only](keepass.info/help/base/fieldrefs.html) and elaborated in [Placeholders](keepass.info/help/base/placeholders.html) 

> Custom strings can be referenced using `{S:Name}`. For example, if you have a custom string named "eMail", you can use the placeholder `{S:eMail}`.

and

a generated TOTP token when autofilling :)

With that you would be able to reference the `TOTP` field to make it easier to input 2FA TOTP tokens.
As in you just create a second entry (here `TOTPonly`) only for the TOTP input. In this entry you only have the `TOTP Seed` and `TOTP Settings`, represented as `{REF:`[`<whatever>@<Whoknowswhat>:<idk>`](keepass.info/help/base/fieldrefs.html) `}` references to the original entries. Additionally you use the `Password` field with a `{S:TOTP}` reference. So when autofilling you can just select the `TOTPonly` entry and it autofills the generated TOTP token.

Hope you can implement that or a similar solution :)

**Comment by PhilippC** [comment]
might be related to https://github.com/PhilippC/keepass2android/issues/620

**Comment by linkp** [comment]
I have a need to enter passwords with TOTP MFA appended following a comma. In KeePassXC I am able to use reference fields to synthesize the desired output. `{REF:P@I:UUID-Reference},{TOTP}` works. Upon encountering this issue (#1165), I tested `{REF:P@I:UUID-Reference},{S:TOTP}`. This also worked in KeePassXC, but it still did not work in Keepass2Android.

In the interim I have created an alternate copy of the password that omits the TOTP reference `{REF:P@I:UUID-Reference},` and I am entering the TOTP manually. This process is somewhat encumbered by #1341 as well as Keepass2Android defaulting to automatic TOTP entry into the password field on subsequent usage. The workaround for that is to erase the TOTP and manually enter both the password and the TOTP. I can make that work until improvements can be made. The real usability test will be how a "normal" user reacts to the new workflow.

**Comment by PhilippC** [comment]
unfortunately, the architecture of TOTP handling in KP2A does not allow a reasonable implementation of field references, so I need to close this as "not planned". However, I have pushed several improvements in https://github.com/PhilippC/keepass2android/pull/2502 which should help a lot with dealing with TOTPs.

**Comment by WebworkrNet** [comment]
The resource `https://github.com/PhilippC/keepass2android/issues/keepass.info/help/base/placeholders.html` is not found (404).

**Comment by WebworkrNet** [comment]
@PhilippC 

So I can't reference an entry for single sign-on (SSO) to another entry via user name, password and TOTP? Is there a workaround without having to enter the one-time password manually?

Multifactor authentication will become more widespread, I think. I would therefore consider implementing it again.
