### ISSUE TITLE
Standard version unusable offline

### ISSUE THREAD

**Issue by NTWarrior** [PhilippC/keepass2android#1169]
I'm using the standard version of the app with a database synced with OneDrive. I have database caching and local backups turned on.

With airplane mode turned on, when I launch the app:

Expected behaviour:
The app starts up with a toast warning it can't currently sync with the online version, then lets me unlock and interact with a local copy of the database.

Actual behaviour:
The app loads nothing more than a blank screen, with no loading indicator or error messages.

Version: 1.07b-r0

**Comment by Small-Ku** [comment]
This not happen for me in 1.08-r1(newest beta). Please update to the newest stable 1.07b version for new OneDrive implementation that fixes problems of offline access.

**Comment by PhilippC** [comment]
@NTWarrior in addition to upgrading the app as suggested by @Small-Ku  (see https://play.google.com/apps/testing/keepass2android.keepass2android), please make sure you switch to the new OneDrive implementation by clicking "Change database" - "Open file" - "OneDrive" ...
This should ifx the issue.
