### ISSUE TITLE
Major issue - Deleted DBfile, can't create new DBfile with current content from internal cache

### ISSUE THREAD

**Issue by Eeeeeek1972** [PhilippC/keepass2android#1171]
Hi there,

Some how I deleted my databasefile on my Google Drive and can't restore it too.
I can't sync from my phone from internal chache to the file anymore. 
Now I can work only on internal cache.
How can I create a new file out of the local cache version, with the content?
I dont have a backup file now, so this is important to fix.
I can create only new databases, which are empty from scratch.

Kind Regard,

Ruud Kaufman

**Comment by lordsinclair** [comment]
Setting/Database/Export DB
copy to target location and open from there
