### ISSUE TITLE
Feature Request: Face unlock

### ISSUE THREAD

**Issue by screwyluie** [PhilippC/keepass2android#1172]
Face unlock is becoming more and more popular in flagship phones and in some has replaced the fingerprint reader entirely. It is my understanding that there is a newer biometric security feature for apps that will work with both (and more) and I'm wondering if this can be used instead so whatever biometric feature a phone prefers can be used, but in particular face unlock integration would be nice for the phones that no longer have a fingerprint reader.

**Comment by Small-Ku** [comment]
Already implemented as #795 close, please update to newest beta or wait for next stable version.

**Comment by screwyluie** [comment]
Apparently I suck at searching... Thanks
