### ISSUE TITLE
Support otpauth:// OTP entries

### ISSUE THREAD

**Issue by nja0087** [PhilippC/keepass2android#118]
I'm not talking about unlocking the kbdx via TOTP, but unless I'm mistaken there's no way to use TOTP in 'otp' fields created in other keepass software?

**Comment by PhilippC** [comment]
entries created with (Kee)TrayTotp or KeeOtp are supported. What do you mean exactly?

**Comment by p0087** [comment]
I personally use KeeWeb to do most of my kdbx heavy lifting, and for an entry there's a field 'otp' with value "otpauth://totp/<service>:<username>?secret=<secret>&issuer=<service>". The field presents itself as the 6 digit TOTP which you can copy. Keepass2android just presents the url as it can't interpret it.

Judging by the 2 thumbs up it appears I'm not the only one with the issue which is comforting.

**Comment by lwis** [comment]
This doesn't appear to be working for me on 1.05-pre2, anything special I need to do?

**Comment by PhilippC** [comment]
Did it work previously for you?

>

**Comment by lwis** [comment]
Nope, should have mentioned - stumbled on this when trying to setup OTP from KeeWeb on Keepass2Android.

**Comment by PhilippC** [comment]
you should see a "TOTP" field (below the otp field) which updates regularly?

**Comment by lwis** [comment]
I just took a look at the code, which is expecting 'secret, digits,
period'. However, my otpauth:// entries appear to only have 'secret'.

**Comment by PhilippC** [comment]
you are correct, digits and period are required. Where did you get that string from? How should Keepass2Android know the duration and length of the TOTPs?

**Comment by lwis** [comment]
A very good question indeed, KeeWeb allows me to punch the 4x4 string in to generate the OTP. I'm not sure if KeeWeb stores metadata elsewhere, @antelle any suggestions?

**Comment by antelle** [comment]
@lwis it's stored in entry fields, just not displayed on KeeWeb UI.

**Comment by lwis** [comment]
@antelle https://github.com/keeweb/keeweb/blob/4c4a308f9e19e29c240f54d99f64ad5d31639f25/app/scripts/util/otp.js#L135 leads me to believe it should be accessible?

**Comment by antelle** [comment]
@lwis of course, it's available, stored in entry fields, as I commented above :)

**Comment by lwis** [comment]
@PhilippC is this something that can be adopted?

**Comment by lwis** [comment]
Just noticed that this has works now, big thanks to whoever fixed it!
