### ISSUE TITLE
Google Drive shared files on Android app

### ISSUE THREAD

**Issue by jdunne525** [PhilippC/keepass2android#1180]
I share my keepass database with my wife via Google drive. The android app doesn't seem to support "Files shared with me" in Google Drive. What is the best way to make this work?
I've tried making the file offline on my wife's phone via Google drive, but changes I make don't get updated on my wife's phone.

**Comment by PhilippC** [comment]
this is currently not supported with GDrive. It should work with Dropbox or OneDrive, though. There is already an issue for reimplementing GDrive support, so I am closing this.
