### ISSUE TITLE
why MessageSyncQuestion on save in keepass2android-offline

### ISSUE THREAD

**Issue by tommertje** [PhilippC/keepass2android#1188]
i use "keepass2android offline". every time i save a change, i get the MessageSyncQuestion with possible answers: cancel & no,overwrite & yes,sync. i choose yes,Sync every time.
why keepass asks this question? and what is the difference between no,overwrite & yes,sync? what is the consequence of no,overwrite ?
thanks

**Comment by daiaxis** [comment]
I have recently started getting the same issue, anyone have any answers?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
https://github.com/PhilippC/keepass2android/issues/1273
https://github.com/PhilippC/keepass2android/issues/445

**Comment by PhilippC** [comment]
@tommertje KP2A keeps a cache copy of your file in case your original storage is inaccessible (you might open a file from removable SD card or something like this). It seems like the original file went out of sync with the cache. Is this possible?

**Comment by lost2** [comment]
Using KP2A-offline version 1.07b-r0 on Android 10 phone without any memory card.
From time to time I get this message too. At first, I went to check which KP2A version was installed :) Having DB on main phone storage shouldn't pop any message, right? (cache file, if exists, should sync fast enough)

**Comment by tommertje** [comment]
thanks everyone, for being involved with this issue.
i answered 'no, overwrite' to kp2a's question a while back and the app hasn't asked the question since. also, the answer seems to have done no damage to my data. so, for me, this issue is done/over.
