### ISSUE TITLE
Support for Android 10 BiometricManager API

### ISSUE THREAD

**Issue by weberda** [PhilippC/keepass2android#1189]
Using a Pixel 4 device, I am currently unable to unlock using biometric ID.

Face unlock is only supported with the new API from Android sdk level 29

https://developer.android.com/reference/kotlin/android/hardware/biometrics/BiometricManager

**Comment by GarrySchaffel** [comment]
+1 for this, I too moved to a Pixel 4 and the lack of a bio metric login option is very frustrating, as I used fingerprint a lot.  Please add in facial recognition as an option to unlock the db.

**Comment by Small-Ku** [comment]
Please search before create issue.
Already implemented as #795 close, please update to newest beta or wait for next stable version.
Also related: #1172, #1153, #1148, #1123,  #1156, #1082, #1052,  #1013, #1006.

**Comment by weberda** [comment]
> Please search before create issue.
> Already implemented as #795 close, please update to newest beta or wait for next stable version.
> Also related: #1172, #1153, #1148, #1123, #1156, #1082, #1052, #1013, #1006.

Sorry for that, missed that obviously.
