### ISSUE TITLE
Local changes are lost if remote file changed while closed and offline

### ISSUE THREAD

**Issue by Wuestengecko** [PhilippC/keepass2android#119]
How to reproduce:
1. Open the database from a remote location (like WebDAV, in my case) - that way it gets cached locally.
2. Go offline.
3. In KP2A, add a new entry. As you are offline, you cannot synchronize right now.
4. Close the database. Do not use QuickUnlock. (This can happen e.g. if you go online again and, without getting an opportunity to sync, Google Play decides to auto-update KP2A, closing the app in the process.)
5. In another instance (e.g. on PC), make any change to the remote file. At this point, the local cache file contains changes that need to be synced up, but the remote file also contains changes AND has a newer file timestamp.
6. Go online angain and open KP2A. It will open to the "Unlock Database" screen, asking for the full master key.
7. It will also kick off file-level synchronization. As the remote file has a newer timestamp than the local cache file, the local changes (the new entry from step 3) are lost.

I assume it will be analogous if you reverse the order of local and remote changes. That way, the remote file would be older and thus overwritten with the local file.

**Comment by PhilippC** [comment]
I cannot reproduce this. I tested the steps as described above using WebDav, but I see the intended behavior: During loading of the file it says that both the remote and the local file have changes, loads the local copy and tells the user to use the sync menu to merge (or discard one version). Please check again and feel free to re-open.
