### ISSUE TITLE
Very strange bug, please examine on your installation.

### ISSUE THREAD

**Issue by trancephorm** [PhilippC/keepass2android#1190]
Keepass2 for Android, latest version available on Play: When you start typing "key", on letter "y", app hangs. Lineage OS 16.

**Comment by PhilippC** [comment]
@trancephorm can you please try with https://play.google.com/apps/testing/keepass2android.keepass2android ?

**Comment by trancephorm** [comment]
Already switched to KeePassDX. Sorry.

⁣Sent from BlueMail ​
