### ISSUE TITLE
Feature request: Add support for Android 10 Biometric API

### ISSUE THREAD

**Issue by OliverDiedrich** [PhilippC/keepass2android#1195]
Hi,

the new  Biometric API in Android 10 (API level 29) allows you to not only use a fingerprint reader for authentication, but also face recognition as implemented in the GooglePixel 4 devices. Would be nice to  unlock the Keepass2Android database just by looking at the phone :)

Thanks, Oliver

**Comment by Percy2Live** [comment]
Agree with that. Furthermore it would be great if the new on screen fingerprint sensors would be supported

**Comment by chrisolsch** [comment]
Totally agree would be awesome!

**Comment by PhilippC** [comment]
this is already implemented and in available in the beta channel (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by OliverDiedrich** [comment]
Great, just tried it in the test version. Works perfectly on my Pixel 4.
Thanks!

PhilippC <notifications@github.com> schrieb am Fr., 1. Mai 2020, 19:38:

**Comment by chrisolsch** [comment]
Thank you !! Works great

**Comment by wederer** [comment]
Thanks! Wanted to open an issue for this as well. Thanks for the quick updates, Drink a Oktoberfest-Mass on me (next year hopefully).

**Comment by nialat** [comment]
Hello, I installed the above beta version, but unfortunately, I can't still use the Biometric API function on my SAMSUNG A500 with Android 10. When clicking on (!) Red button, application is crashing.
Thanks in advance flor letting me know if any other settings than default should be applied.
Kind regards, 
Alain

**Comment by nialat** [comment]
Erratum : my mobile is a SAMSUNG A50

**Comment by PhilippC** [comment]
did you try to disable and reenable biometric unlock after upgrading?
