### ISSUE TITLE
Password Entry does not use a monospaced font

### ISSUE THREAD

**Issue by Zhaph** [PhilippC/keepass2android#1196]
When creating or editing an entry, the password field uses a standard entry font, and you are unable to distinguish between `0` and `O` characters - this is especially problematic with auto-generated values.

Once you've saved the entry you can "view" the password in a monospaced font.

Use case where this comes up:

Creating an account on a computer without my personal Keepass database on it, I will create the entry on my phone, manually enter the password on the other device, ensuring that the site/application doesn't truncate or complain about the characters, before saving the entry in my database.

Version: `1.07b-r0`

**Comment by PhilippC** [comment]
merged into https://github.com/PhilippC/keepass2android/issues/81

**Comment by PhilippC** [comment]
this was fixed with https://github.com/PhilippC/keepass2android/commit/4636f5800cc76a2a807109afe14166fadc35b508 a while ago
