### ISSUE TITLE
how to compile this project to a apk file?

### ISSUE THREAD

**Issue by anonymousAdminUser** [PhilippC/keepass2android#1197]
is this project write by the c# ? And what is the IDE?   Visual Studio?
Is there anyone can tell me? I am a new learner,I really don't understand

**Comment by PhilippC** [comment]
see https://github.com/PhilippC/keepass2android. Main language is C# with significant parts in Java and very minor native (C++) parts. I don't recommend working with this code base if you are a beginner - it's difficult to handle unfortunatly.
