### ISSUE TITLE
How to avoid re-entering onedrive account and password？

### ISSUE THREAD

**Issue by liwenbus** [PhilippC/keepass2android#1200]
Hi, I have no idea that how I can avoid having to re-enter my account password after logging into webdav or onedrive? I need to sign in every time when I want to see my base, it is really troublesome.

**Comment by Poulpy21** [comment]
Yes it is the same for me, the default database configuration (last successfully opened I guess) is not saved, and i have to enter the my owncloud webdav each time (which makes it impossible to use). Moreover it does not save the configuration 'pasword + file key' or 'password + file key + physical key'.

I even tried to edit `./data/keepass2android.keepass2android/shared_prefs/keepass2android.keepass2android_preferences.xml` manually as root but I did not find those options.

**Comment by towadroid** [comment]
@PhilippC This may also be related to #1038?

**Comment by PhilippC** [comment]
wow, I wasn't aware there are so many duplicates :-) 
@keckj for other problems please comment on the regarding issues.
