### ISSUE TITLE
How to undo 'disable for <site>' 

### ISSUE THREAD

**Issue by Toudahl** [PhilippC/keepass2android#1201]
I accidentally disabled keepass for one site, and I cannot find a place to re-enable it.

How can I fix my mistage

**Comment by mlinger1** [comment]
I have the same issue and it took awhile to figure out. Assuming you are using keepass as the auto field service: In Keepass app (on Android):
- 3 dots at top right
- Settings
- App Settings
- Password Entry Access
- Autofill Services
- Disabled Autofill Targets
- Uncheck the box next to the one you accidentally disabled

If you are on the desktop, I would assume he uses the same terminology.

**Comment by PhilippC** [comment]
thanks @mlinger1!
