### ISSUE TITLE
Add option to use pattern instead of fingerprint

### ISSUE THREAD

**Issue by skst** [PhilippC/keepass2android#1202]
Sometimes my fingerprint reader doesn't accept my finger and locks me out for awhile. It'd be nice if KeePass provided the option of using my pattern instead. (As an example, Microsoft OneDrive does this.)

**Comment by PhilippC** [comment]
this is not possible without compromising the security of your masterpassword. Android only allows to encrypt the master password based on biometric authentication.

**Comment by skst** [comment]
Interesting. I'm certain that Microsoft wouldn't compromise the security of the phone with their implementation, so I wonder how they provide this feature. Oh well.
