### ISSUE TITLE
Howto install a dictionary

### ISSUE THREAD

**Issue by getwet** [PhilippC/keepass2android#1204]
Hi Folks,

this is not a bug, more a question.
On my tablet I've got a german dictionary under my language settings. On my smartphone I've got only an english dictionary available. How can I add a german dictionary as well?

Thanks in advance

**Comment by PhilippC** [comment]
please see https://github.com/PhilippC/keepass2android/blob/master/docs/Advanced-usage-of-the-Keepass2Android-keyboard.md
