### ISSUE TITLE
How to undo (and remove) "Disable AutoFill for xx"?

### ISSUE THREAD

**Issue by dolphinkite** [PhilippC/keepass2android#1206]
Hi,

Often (but not always??), when I need to enter a password on a web site or an app, Keepass will automatically prompt me with 2 options:
1- Fill with Keepass2Android
2- Disable AutoFill for XX

I have the 4 following questions:
1- Why doesn't this prompt ALWAYS show up? I'm assuming that the app/site need to put a metatag stating that this entry box is a password for keepass2Android to detect that it can autofill? Is there anything I can do to enable it when it doesn't show up?

2- I once mistakenly hit "Disable Autofill" for one entry, and I don't know how to UNDO this? Where is the list of all site/apps that have been disabled?

3- Is there a way to COMPLETELY REMOVE the option to "Disable Autofill" so that I don't hit it by mistake again? I never want to use that option anyway

4- Is there a was that keepass REMEMBERS which password to use with a given site/app? It works well on my computer with the http extension, but for my mobile, is there a way to make it so that I don't have to select the entry each time?

Thank you for your work.

**Comment by knobhead** [comment]
Hi dolphinkite,

tap the ⚙️ icon, select Application / Password Access / AutoFill Service / Disabled AutoFill services.
(Actual wording might differ, retranslated from German localization.)

Mind #1175, however.

**Comment by sam2kb** [comment]
+1 for having an option to "Never show disable button". I click it all the time and it wasn't a trivial task to find the list of sites where it was disabled. There was at least 20 entries :)
