### ISSUE TITLE
Add support for Nextcloud 2FA

### ISSUE THREAD

**Issue by suprovsky** [PhilippC/keepass2android#1207]
Hey, I'm using your app and it's very cool, but seems like it doesn't support Nextcloud's 2FA. I'm using Nextcloud 18.0.3 and while using it I can't sync my database through Nextcloud/WebDAV. I'm getting 401 Unauthorized, because there's no way to pass a token at least in the first connection.
Tested on Samsung Galaxy S7 with Android 8.0 and Samsung A5 2017 with Android 7.0.

**Comment by lizardb0y** [comment]
@suprovsky  You will need to configure an application password for K2A

Settings -> Personal -> Security

Look at the bottom of the section "Devices & sessions"

**Comment by suprovsky** [comment]
That's completely right. Closing it.
