### ISSUE TITLE
Add Microsoft Teams App support

### ISSUE THREAD

**Issue by mawi0803** [PhilippC/keepass2android#1208]
Please add support for Microsoft Teams App on Andoid smartphone. 
I have added an entry for an microsoft online account in keepass.
If I open the app, keepass doesn't ask for an account.
Keepass keyboard just works as workaround now by selecting the account and then enter credentials.
It would be great if you add support for this app. Your app is working great!

**Comment by Karreg** [comment]
Unfortunately (or fortunately for @PhilippC), it's working in the opposite way.
You have to ask Microsoft Teams developpers to use the autofill framework in their application. When it's done, Keepass will be able to autofill the form... There's nothing to be done on KP2A side. :)
