### ISSUE TITLE
how can we change the master password ?

### ISSUE THREAD

**Issue by LesAiles** [PhilippC/keepass2android#1209]
Hi,
In the android interface, in parameters, i have not found where we can change the master password of a database ?
For security reasons, it will be nice to change it regularly.
Thank by advance for your help,
BR,

**Comment by patka817** [comment]
If you go into settings (three vertical dots -> settings, at least on my phone) and then click on the database row you will find a row for changing the master pw.

**Comment by LesAiles** [comment]
Thanks Patka817, i have found this row but i did'nt use it correctly.
Just need to put twice the new master password and it's OK !
BR,
