### ISSUE TITLE
The entire password is shown after copy-paste

### ISSUE THREAD

**Issue by prog-amateur** [PhilippC/keepass2android#121]
Hello, 

When I copy paste a password from keepass2android into a "password" field in my browser, my password appears 2 or 3 seconds before being hidden by the "*******" characters. 

The same issue happens when I use the keepass2android keyboard. 

This is very critical as any screenshot malware can record our passwords during this step. 

Can you reproduce this issue ? 

Thank you very much.

**Comment by RealOrangeOne** [comment]
This sounds more like an issue with the browser / website over keepass2android. Once you've copied the password to the clipboard, it's out of the hands of keepass2android, it's down to the browser / website / OS

**Comment by prog-amateur** [comment]
Thank you very much for your feedback. I am using Firefox 56 Android version, and Lineage OS as a ROM. 
Please, could you tell me if you are using Firefox too ? Then, I would be able to suspect Lineage OS to show the PW. 
Thank you

**Comment by prog-amateur** [comment]
OK you were true, I have found the solution. In Lineage OS, you have to go to : 
Settings > Security > Passwords : click on "show passwords" to DISABLE the option. It is crazy that this option is enabled by default.

**Comment by RealOrangeOne** [comment]
I do use Firefox, and I don't have that setting, which makes me think it is Lineage being a little strange. It's super worrying that's the default setting too! 👎
