### ISSUE TITLE
Feature request: write access when accessing via content provider

### ISSUE THREAD

**Issue by limuc** [PhilippC/keepass2android#1212]
Hello everyone,
i recently tried KeePassDX (another KeePass app for Android, also open source) and discovered that i could just open a KeePass-database in OneDrive with the  content provider (file app) and have write access. KeePassDX uses the Storage Access Framework. 
In "KeePass2Android Offline" i can open it via this but i do not have write-access. So its pretty useless.
I know that i can use OneDrive with KeePass2Android but i would like to not login and use the native android file integration (and the offline version of the app). Would be nice to have this solution, as it seems, that it is possible.

Thanks,
limuc

**Comment by Awaces** [comment]
So is this fixed???
