### ISSUE TITLE
[Bug] Autofill does not work right in Firefox Nightly 

### ISSUE THREAD

**Issue by BeeeWall** [PhilippC/keepass2android#1215]
Using Firefox Nightly (after Preview Nightly got merged into it), autofill doesn't properly get the URL. It tries to fill it for the app instead of the website.

Have not tested it with Firefox Preview or Preview Nightly.

Using KP2A version 1.08-r1, on Android 10.

**Comment by xnaterion** [comment]
Also broke on Firefox stable and Brave browser

KP2A 1.08-r1 on Android 7

**Comment by knowdaledge** [comment]
That's why I love to use the share button instead of autofill.

**Comment by PhilippC** [comment]
I cannot reproduce this. It's still working for me.

**Comment by BeeeWall** [comment]
That's weird, wonder if maybe it's either an Android 10 thing or a Samsung thing?

**Comment by PhilippC** [comment]
tested with Android 10 as well

**Comment by jwsp1** [comment]
Same issue here. 
Using keepass2android 1.07b with auto-fill extension and brave browser 1.8.112 (chromium 81.0)

**Comment by montilo** [comment]
Same issue here with new Firefox Stable:
79.0.5 (Build #2015758619)
AC: 48.0.15, 8755ac0cd
GV: 79.0.1-20200813192915
AS: 61.0.10
On my Android 9 Tablet Huawei SHT-W09 and on my Android 10 Phone Xiaomi Mi 9.
Keepass2Android Version:
Version 1.08b

**Comment by bluezed** [comment]
I have the same problem since Firefox got updated to v79... Used to work fine with the old version.
Also noticed... With the old version I could long press on a field and I would have a "Autofill" option next to "Paste" but that's gone now too.

79.0.5 (Build #2015758619)
AC: 48.0.15, 8755ac0cd
GV: 79.0.1-20200813192915
AS: 61.0.10

Phone is a Xiaomi Mi Note 10 Lite with Android 10.

Keepass2Android Version: 1.08b

**Comment by Alokin-ITA** [comment]
K2A version 1.09c-r0
Both on latest Firefox stable and nightly, autofill only works for the password, the username field does not offer to autofill on the form nor on the keyboard suggestions.

I see that the system does not even offer to paste on the username field, perhaps some new security feature?

**Comment by PhilippC** [comment]
is this still an issue? Autofill has been re-worked quite a bit since the last comment here?

**Comment by PhilippC** [comment]
I'll close the ticket but will re-open if somebody reports issues.
