### ISSUE TITLE
Can't connect to Nextcloud

### ISSUE THREAD

**Issue by arnauldb** [PhilippC/keepass2android#1219]
Hello,

I am running Keepass2android on LineageOS 16 and when I wish to open a database from my Nextcloud server using https webdav I receive this error:

![DKHbdXT](https://user-images.githubusercontent.com/13196747/79472625-9746c700-7ff3-11ea-9c47-704d281f8b89.png)

Thank you for help.

**Comment by derhintze** [comment]
du you have 2 factor authentication in nextcloud activated? if yes, you need to create a programm password to use your data base from nextcloud with keepass2android (I am doing it exactly this way!)

**Comment by species-gh** [comment]
It also doesn't work for me without activated 2-factor in Nextcloud using my user password. However, as @derhintze  pointed out, using an app password for keepass2android should do the trick (at least it does on all devices I set up with K2A and Nextcloud). Using an app password is advised for security and safety reasons anyway: If you lose your phone, you can revoke the app password easily or if you change your user password, you do not break sync of your database in K2A (which could possibly lead to a lock-out situation, supposing you store your Nextcloud password in KeePass).

**Comment by arnauldb** [comment]
> du you have 2 factor authentication in nextcloud activated? if yes, you need to create a programm password to use your data base from nextcloud with keepass2android (I am doing it exactly this way!)

Thank you, it worked perfectly.
