### ISSUE TITLE
Gboard Keyboard

### ISSUE THREAD

**Issue by AlleSchonWeg** [PhilippC/keepass2android#1226]
Hi,
If i open an existing entry and select gboard keyboard, not kp2a keyboard, an empty view is shown.
![Screenshot_Keepass2Android_20200422-201318](https://user-images.githubusercontent.com/6727366/80018052-c4a0e280-84d5-11ea-8434-e812cbdad261.png)
Ist this a bug? 
Thank you

**Comment by PhilippC** [comment]
unfortunately on some devices this screen is needed to make sure the keyboard selection dialog is shown. The window closes as soon as you select the KP2A Keyboard (that's why the keyboard selection is shown).
So I consider this a necessity.
