### ISSUE TITLE
OneDrive Sync Fails with size error message

### ISSUE THREAD

**Issue by MaxRink** [PhilippC/keepass2android#1228]
I have an 8.7mb .kdbx that resides on OneDrive.
I cant Sync this via Keepass2Android, as i get this error message:
Code: BadRequest
The Maximum request lenght supported is 4MB

Im using the Onedrive2_full access, although the other ones behave the same

**Comment by MaxRink** [comment]
i guess thats a limitation of the api used
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online
vs 
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online

**Comment by PhilippC** [comment]
duplicate of https://github.com/PhilippC/keepass2android/issues/1036
