### ISSUE TITLE
App cannot be closed via the notification

### ISSUE THREAD

**Issue by 19eXodus86** [PhilippC/keepass2android#1233]
Hello,

as soon as I have started and unlocked the app, I can leave the app with the home button.

Now in the notifications it appears that the database is unlocked and if I expand the notification, I am offered to close the database when I tap the text.

Typing on the text, however, has no function and if I want to close the database, I have to open the app and manually select "Close database"

I am using KeePass2Android on a Samsung Galaxy S9 + with Android 10, all previously available updates and KeePass2Android in the version 1.07b-r0.
The problem already existed in the last version.
I didn't have this problem with Android 9

**Comment by thetric** [comment]
I can confirm this issue on my OnePlus 6 (Android 10) with the current version (1.07b-r0)

**Comment by gitzila** [comment]
On my OnePlus7T with Android 10 I have a similar issue:
When I unlock then database and leave the app with Home Button (Settings: Lock database when App is closed) there is a notification that says "the database is unlocked" an offers to lock the database. But the database is already locked. If I tap on "lock database" nothing happens. I have to tap on the notification text to open Keepass2Android: The app opens and show "QuickUnlock" screen. Leaving this screen open and opening the notification again, the action "lock database" now works and the notification changes as follows: "database locked" and action "close database". Now tapping on "close database" actually closes the database.

Version: 1.08b-r1

**Comment by PhilippC** [comment]
does this issue still exist with 1.09c? I cannot reproduce it.

**Comment by 19eXodus86** [comment]
Nein, es funktioniert schon lange Zeit wieder. Vielen Dank

PhilippC ***@***.***> schrieb am Mi., 2. Feb. 2022, 04:00:
