### ISSUE TITLE
Permission problem when syncing with Synology Drive

### ISSUE THREAD

**Issue by szeiger** [PhilippC/keepass2android#1243]
I've been using Keepass2Android successfully with Synology Drive but a while ago updating the password file stopped working. I'm not sure which change broke it but I suspect it was the introduction of the new caching and synchonization feature.

I can open a password file (marked as available offline) directly from Drive into Keepass2Android. It gets a `content://com.synology.dsdrive.external/file/...` URI. When I try to synchronize it later I get this error about missing permissions `com.synology.dsdrive.external.READ` and `com.synology.dsdrive.external.WRITE`.

This happens both on a Mi Pro 10 running MIUI 11 (Android 10) and a Galaxy S8+ with OneUI 1.0 (Android 9). Currently using Keepass2Android 1.07b-r0.

Here's the log file of an attempt at synchronizing: [Keepass2Android log.txt](https://github.com/PhilippC/keepass2android/files/4570207/Keepass2Android.log.txt)

**Comment by PhilippC** [comment]
As far as I know, Synology supports WebDav which is the preferred way of accessing files instead of going through a third-party app.

**Comment by szeiger** [comment]
While DSM has WebDAV support, this requires the installation of a separate package, with separate configuration, access conrol, manually setting up dynamic DNS and port mapping for external access. With Synology Drive these things work out of the box and with a single server application for all clients. Being able to integrate with the Drive client would be a much more user-friendly solution. (And it worked perfectly fine in the past)

**Comment by sven43** [comment]
I run into the same problem with the keepass2android and synology drive app. is there any update which makes it work again? I really just dont wanna install webdav and open another port on my router.

**Comment by sven43** [comment]
> While DSM has WebDAV support, this requires the installation of a separate package, with separate configuration, access conrol, manually setting up dynamic DNS and port mapping for external access. With Synology Drive these things work out of the box and with a single server application for all clients. Being able to integrate with the Drive client would be a much more user-friendly solution. (And it worked perfectly fine in the past)

if you still have no solution for it, then try "keepassDX". there is no permission error after saving a new entry in the drive-app path

**Comment by PhilippC** [comment]
can you please try again with 1.09a-pre1 from https://play.google.com/apps/testing/keepass2android.keepass2android? I am not sure if it is fixed there but there is a related change at least.

**Comment by SchiFrank** [comment]
I updated, but I have the same problem. Best solution would be the integration of synology drive in the same way like onedrive etc.

**Comment by matthias-bindernagel** [comment]
Mhm, I'm suffering from that very same problem and I have the same reasons as @szeiger to prefer the outlined method over any webdav tinkering. @PhilippC what's your feeling on this, any chance to get this fixed upstream or should we users investigate alternatives?

**Comment by PhilippC** [comment]
The correct way for Synology to make files accessible to other apps is to implement a Storage Access Framework Provider, this would allow KP2A to access the files through Open file > System file picker. I have no idea if they are planning to do this.

**Comment by matthias-bindernagel** [comment]
@PhilippC thanks for your insight. That way, we might ask for a fix (or at least a prospect) from Synology.
