### ISSUE TITLE
Face Unlock on Pixel 4

### ISSUE THREAD

**Issue by poorandunlucky** [PhilippC/keepass2android#1255]
Pixel 4 uses Face instead of Fingerprint, and so I have to type to open the database...

I think it's just a new pathway to the biometric security platform...

**Comment by PhilippC** [comment]
please see 1.08 on https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by poorandunlucky** [comment]
Ah, lovely…  Wonderful, thank you very much  😊
