### ISSUE TITLE
Fingerprint on Pixel 3a

### ISSUE THREAD

**Issue by benxc** [PhilippC/keepass2android#1256]
I've just swapped from a Moto G5s to Pixel 3a and the fingerprint unlock doesn't work.
Clicking the ! symbol shows a java runtime exception.
Entering the last 3 characters still works.

**Comment by PhilippC** [comment]
can you please try to disable and re-enable fingerprint unlock in settings - database - fingerprint unlock?

**Comment by benxc** [comment]
Yes, that's sorted it.

Thanks for the speedy reply.  Great app by the way!
