### ISSUE TITLE
Cloud sync issues - timestamp as possible cause?

### ISSUE THREAD

**Issue by chrimez** [PhilippC/keepass2android#1258]
Hi. I've been using K2A with cloud-stored kdbx- and otp-files. Since ca. mid 2019 I have issues with OTP keys, and found the cause of the problem: the syncing of otp file between the cloud and desktop copy of KeePass installation.

I noted: K2A seems to never update the "date modofied" timestamp on the otp file it accesses in the cloud. I.e. after opening the kdbx, K2A does increment the counter in the otp-file and saves it back to the cloud location. BUT the modified timestamp remains the original one. 

I'm not sure yet, but this may be a cause for my problems: Is not updating the timestamp "normal" behavior? Did this behavior change last year ?

**Comment by chrimez** [comment]
My software changes before the problem occured / after its first occurence last year:
my Software changes in meantime (afaik):

    Android: major OS 'Pie' update Samsung OTA
    Win10: upgrade to KeePass 2.4.1 (from ca. 2.3.9)
    Win10: upgrade to OtpKeyProv 2.6
    Think no updates available / changes to K2A in the same time....

Android: K2A 1.07-r1, Android 9 on Samsung S8 SM-G950F (on latest official Samsung OTA Android)

**Comment by PhilippC** [comment]
which cloud do you use?

**Comment by chrimez** [comment]
Thanks. I just solved it: SSL certificate problem. update was required. 
Nothing on K2A side.
