### ISSUE TITLE
feature request : faster pwd copy

### ISSUE THREAD

**Issue by PacTrix** [PhilippC/keepass2android#1259]
hello 
1) i did offered you a beer
2) to copy a pwd you need to click once on the pwd and then a 2nd time to copy. Most app allow to copy with only 1 click... which is faster !

**Comment by PhilippC** [comment]
1.) Thanks a lot! :-) 
2.) I really want to discourage people from copying their passwords so I don't think this should be made easier (or happen by accident) - Android Clipboard is highly insecure.
