### ISSUE TITLE
Fingerprint error with Samsung API + Android API

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#126]
with both APIs available, fingerprint fails the first time but works the second:

15.11.2017 07:30:39:160 -- GroupActivity.OnPause
15.11.2017 07:30:39:194 -- Timeout start
15.11.2017 07:30:39:210 -- GroupActivity.OnStop
15.11.2017 07:30:40:363 -- PasswordActivity.OnDestroyTrue
15.11.2017 07:30:40:500 -- GroupActivity.OnDestroyTrue
15.11.2017 07:30:40:638 -- OngoingNotificationsService.OnTaskRemoved: android.intent.action.MAIN
15.11.2017 07:30:40:645 -- QuickLocking database
15.11.2017 07:30:40:667 -- Starting/Updating OngoingNotificationsService. Database QuickLocked
15.11.2017 07:30:41:764 -- KeePass.OnCreate
15.11.2017 07:30:41:765 -- KeePass:apptask=
15.11.2017 07:30:41:767 -- Loaded task keepass2android.NullTask
15.11.2017 07:30:41:767 -- KeePass.OnCreate
15.11.2017 07:30:41:769 -- KeePass.OnStart
15.11.2017 07:30:41:770 -- KeePass.OnStart
15.11.2017 07:30:41:825 -- PasswordActivity.OnCreate
15.11.2017 07:30:41:826 -- PasswordActivity:apptask=
15.11.2017 07:30:41:836 -- Loaded task keepass2android.NullTask
15.11.2017 07:30:42:8 -- PasswordActivity.OnStart
15.11.2017 07:30:42:12 -- PasswordActivity.OnResume
15.11.2017 07:30:42:13 --  DatabaseIsUnlocked=False
15.11.2017 07:30:42:14 -- Timeout cancel
15.11.2017 07:30:42:18 -- starting: True, Finishing: False, _performingLoad: False
15.11.2017 07:30:42:25 -- Starting QuickUnlock
15.11.2017 07:30:42:45 -- PasswordActivity.OnPause
15.11.2017 07:30:42:74 -- QuickUnlock.OnCreate
15.11.2017 07:30:42:75 -- QuickUnlock:apptask=
15.11.2017 07:30:42:134 -- requesting fingerprint permission
15.11.2017 07:30:42:147 -- QuickUnlock.OnStart
15.11.2017 07:30:42:152 -- QuickUnlock.OnResume
15.11.2017 07:30:42:153 --  DatabaseIsUnlocked=False
15.11.2017 07:30:42:160 -- InitFingerprintUnlock
15.11.2017 07:30:42:161 -- trying Samsung Fingerprint API...
15.11.2017 07:30:42:216 -- trying Samsung Fingerprint API...Seems to work!
15.11.2017 07:30:42:220 -- successfully initialized fingerprint.
15.11.2017 07:30:42:620 -- FP: Stop listening
15.11.2017 07:30:42:624 -- QuickUnlock.OnPause
15.11.2017 07:30:42:837 -- OnRequestPermissionsResult TrueTrue
15.11.2017 07:30:42:838 -- _fingerprintPermissionGranted
15.11.2017 07:30:42:839 -- InitFingerprintUnlock
15.11.2017 07:30:42:848 -- fpModule.FingerprintManager.IsHardwareDetected=True
15.11.2017 07:30:42:868 -- FP: Create FingerprintDecryption
15.11.2017 07:30:42:895 -- FP: Init for Dec
15.11.2017 07:30:42:953 -- successfully initialized fingerprint.
15.11.2017 07:30:42:961 -- FP: StartListening
15.11.2017 07:30:42:969 -- QuickUnlock.OnResume
15.11.2017 07:30:42:970 --  DatabaseIsUnlocked=False
15.11.2017 07:30:42:971 -- InitFingerprintUnlock
15.11.2017 07:30:42:972 -- Already listening for fingerprint!
15.11.2017 07:30:43:17 -- FP: OnAuthenticationError: Fingerabdruckvorgang abgebrochen, False
15.11.2017 07:30:43:19 -- fingerprint error: Fingerabdruckvorgang abgebrochen
15.11.2017 07:30:43:270 -- PasswordActivity.OnStop
15.11.2017 07:30:43:272 -- KeePass.OnStop
15.11.2017 07:30:43:273 -- KeePass.OnDestroyTrue
15.11.2017 07:30:43:275 -- KeePass.OnDestroyTrue
15.11.2017 07:30:45:338 -- FP: Stop listening
15.11.2017 07:30:45:340 -- FP: StopListening
15.11.2017 07:30:45:342 -- QuickUnlock.OnPause
15.11.2017 07:30:45:384 -- QuickUnlock.OnStop
15.11.2017 07:30:46:117 -- QuickUnlock.OnStart
15.11.2017 07:30:46:119 -- QuickUnlock.OnResume
15.11.2017 07:30:46:120 --  DatabaseIsUnlocked=False
15.11.2017 07:30:46:122 -- InitFingerprintUnlock
15.11.2017 07:30:46:124 -- fpModule.FingerprintManager.IsHardwareDetected=True
15.11.2017 07:30:46:125 -- FP: Create FingerprintDecryption
15.11.2017 07:30:46:128 -- FP: Init for Dec
15.11.2017 07:30:46:134 -- successfully initialized fingerprint.
15.11.2017 07:30:46:136 -- FP: StartListening
15.11.2017 07:30:47:312 -- FP: OnAuthenticationSucceeded
15.11.2017 07:30:47:313 -- FP: StopListening
15.11.2017 07:30:47:316 -- OnFingerprintAuthSucceeded
15.11.2017 07:30:47:883 -- Starting/Updating OngoingNotificationsService. Database Unlocked
15.11.2017 07:30:47:952 -- FP: Stop listening
15.11.2017 07:30:47:953 -- QuickUnlock.OnPause
15.11.2017 07:30:47:988 -- PasswordActivity.OnStart
15.11.2017 07:30:48:48 -- PasswordActivity.OnActivityResult Canceled/0
15.11.2017 07:30:48:49 -- TryGetFromActivityResult: no data
15.11.2017 07:30:48:53 -- PasswordActivity.OnResume
15.11.2017 07:30:48:54 --  DatabaseIsUnlocked=True
15.11.2017 07:30:48:55 -- Timeout cancel
15.11.2017 07:30:48:58 -- starting: True, Finishing: False, _performingLoad: False
15.11.2017 07:30:48:81 -- PasswordActivity.OnPause
15.11.2017 07:30:48:82 -- Timeout start
15.11.2017 07:30:48:109 -- GroupActivity.OnCreate
15.11.2017 07:30:48:110 -- GroupActivity:apptask=
15.11.2017 07:30:48:113 -- Loaded task keepass2android.NullTask
15.11.2017 07:30:48:146 -- GroupActivity.OnStart
15.11.2017 07:30:48:149 -- GroupActivity.OnResume
15.11.2017 07:30:48:150 --  DatabaseIsUnlocked=True
15.11.2017 07:30:48:151 -- Timeout cancel
15.11.2017 07:30:48:741 -- PasswordActivity.OnStop
15.11.2017 07:30:48:743 -- QuickUnlock.OnStop
15.11.2017 07:30:48:745 -- QuickUnlock.OnDestroyTrue
15.11.2017 07:30:54:806 -- GroupActivity.OnPause
15.11.2017 07:30:54:807 -- Timeout start
15.11.2017 07:30:54:840 -- DatabaseSettingsActivity.OnCreate
15.11.2017 07:30:54:841 -- DatabaseSettingsActivity:apptask=
15.11.2017 07:30:55:6 -- DatabaseSettingsActivity.OnStart
15.11.2017 07:30:55:9 -- DatabaseSettingsActivity.OnResume
15.11.2017 07:30:55:10 --  DatabaseIsUnlocked=True
15.11.2017 07:30:55:11 -- Timeout cancel
15.11.2017 07:30:55:526 -- GroupActivity.OnStop
15.11.2017 07:31:05:271 -- DatabaseSettingsActivity.OnPause
15.11.2017 07:31:05:272 -- Timeout start
15.11.2017 07:31:05:355 -- DatabaseSettingsActivity.OnStop
15.11.2017 07:31:07:86 -- PasswordActivity.OnDestroyTrue
15.11.2017 07:31:07:242 -- GroupActivity.OnDestroyTrue
15.11.2017 07:31:07:421 -- DatabaseSettingsActivity.OnDestroyTrue
15.11.2017 07:31:07:526 -- OngoingNotificationsService.OnTaskRemoved: android.intent.action.MAIN
15.11.2017 07:31:07:527 -- QuickLocking database
15.11.2017 07:31:07:739 -- Starting/Updating OngoingNotificationsService. Database QuickLocked
15.11.2017 07:31:08:404 -- KeePass.OnCreate
15.11.2017 07:31:08:405 -- KeePass:apptask=
15.11.2017 07:31:08:406 -- Loaded task keepass2android.NullTask
15.11.2017 07:31:08:407 -- KeePass.OnCreate
15.11.2017 07:31:08:408 -- KeePass.OnStart
15.11.2017 07:31:08:409 -- KeePass.OnStart
15.11.2017 07:31:08:463 -- PasswordActivity.OnCreate
15.11.2017 07:31:08:464 -- PasswordActivity:apptask=
15.11.2017 07:31:08:468 -- Loaded task keepass2android.NullTask
15.11.2017 07:31:08:657 -- PasswordActivity.OnStart
15.11.2017 07:31:08:661 -- PasswordActivity.OnResume
15.11.2017 07:31:08:662 --  DatabaseIsUnlocked=False
15.11.2017 07:31:08:662 -- Timeout cancel
15.11.2017 07:31:08:667 -- starting: True, Finishing: False, _performingLoad: False
15.11.2017 07:31:08:669 -- Starting QuickUnlock
15.11.2017 07:31:08:689 -- PasswordActivity.OnPause
15.11.2017 07:31:08:711 -- QuickUnlock.OnCreate
15.11.2017 07:31:08:712 -- QuickUnlock:apptask=
15.11.2017 07:31:08:734 -- requesting fingerprint permission
15.11.2017 07:31:08:747 -- QuickUnlock.OnStart
15.11.2017 07:31:08:751 -- QuickUnlock.OnResume
15.11.2017 07:31:08:751 --  DatabaseIsUnlocked=False
15.11.2017 07:31:08:752 -- InitFingerprintUnlock
15.11.2017 07:31:08:753 -- trying Samsung Fingerprint API...
15.11.2017 07:31:08:765 -- trying Samsung Fingerprint API...Seems to work!
15.11.2017 07:31:08:767 -- successfully initialized fingerprint.
15.11.2017 07:31:08:832 -- FP: Stop listening
15.11.2017 07:31:08:834 -- QuickUnlock.OnPause
15.11.2017 07:31:09:4 -- OnRequestPermissionsResult TrueTrue
15.11.2017 07:31:09:5 -- _fingerprintPermissionGranted
15.11.2017 07:31:09:6 -- InitFingerprintUnlock
15.11.2017 07:31:09:10 -- fpModule.FingerprintManager.IsHardwareDetected=True
15.11.2017 07:31:09:11 -- FP: Create FingerprintDecryption
15.11.2017 07:31:09:14 -- FP: Init for Dec
15.11.2017 07:31:09:24 -- successfully initialized fingerprint.
15.11.2017 07:31:09:25 -- FP: StartListening
15.11.2017 07:31:09:28 -- QuickUnlock.OnResume
15.11.2017 07:31:09:28 --  DatabaseIsUnlocked=False
15.11.2017 07:31:09:29 -- InitFingerprintUnlock
15.11.2017 07:31:09:30 -- Already listening for fingerprint!
15.11.2017 07:31:09:150 -- FP: OnAuthenticationError: Fingerabdruckvorgang abgebrochen, False
15.11.2017 07:31:09:151 -- fingerprint error: Fingerabdruckvorgang abgebrochen
15.11.2017 07:31:09:432 -- PasswordActivity.OnStop
15.11.2017 07:31:09:433 -- KeePass.OnStop
15.11.2017 07:31:09:434 -- KeePass.OnDestroyTrue
15.11.2017 07:31:09:436 -- KeePass.OnDestroyTrue
15.11.2017 07:31:10:561 -- FP: Stop listening
15.11.2017 07:31:10:561 -- FP: StopListening
15.11.2017 07:31:10:563 -- QuickUnlock.OnPause
15.11.2017 07:31:10:610 -- QuickUnlock.OnStop
15.11.2017 07:31:11:408 -- QuickUnlock.OnStart
15.11.2017 07:31:11:411 -- QuickUnlock.OnResume
15.11.2017 07:31:11:412 --  DatabaseIsUnlocked=False
15.11.2017 07:31:11:413 -- InitFingerprintUnlock
15.11.2017 07:31:11:415 -- fpModule.FingerprintManager.IsHardwareDetected=True
15.11.2017 07:31:11:417 -- FP: Create FingerprintDecryption
15.11.2017 07:31:11:419 -- FP: Init for Dec
15.11.2017 07:31:11:426 -- successfully initialized fingerprint.
15.11.2017 07:31:11:428 -- FP: StartListening
15.11.2017 07:31:12:528 -- FP: OnAuthenticationSucceeded
15.11.2017 07:31:12:529 -- FP: StopListening
15.11.2017 07:31:12:530 -- OnFingerprintAuthSucceeded
15.11.2017 07:31:13:78 -- Starting/Updating OngoingNotificationsService. Database Unlocked
15.11.2017 07:31:13:155 -- FP: Stop listening
15.11.2017 07:31:13:157 -- QuickUnlock.OnPause
15.11.2017 07:31:13:196 -- PasswordActivity.OnStart
15.11.2017 07:31:13:251 -- PasswordActivity.OnActivityResult Canceled/0
15.11.2017 07:31:13:252 -- TryGetFromActivityResult: no data
15.11.2017 07:31:13:255 -- PasswordActivity.OnResume
15.11.2017 07:31:13:256 --  DatabaseIsUnlocked=True
15.11.2017 07:31:13:257 -- Timeout cancel
15.11.2017 07:31:13:260 -- starting: True, Finishing: False, _performingLoad: False
15.11.2017 07:31:13:283 -- PasswordActivity.OnPause
15.11.2017 07:31:13:284 -- Timeout start
15.11.2017 07:31:13:314 -- GroupActivity.OnCreate
15.11.2017 07:31:13:315 -- GroupActivity:apptask=
15.11.2017 07:31:13:318 -- Loaded task keepass2android.NullTask
15.11.2017 07:31:13:358 -- GroupActivity.OnStart
15.11.2017 07:31:13:361 -- GroupActivity.OnResume
15.11.2017 07:31:13:361 --  DatabaseIsUnlocked=True
15.11.2017 07:31:13:362 -- Timeout cancel
15.11.2017 07:31:13:962 -- PasswordActivity.OnStop
15.11.2017 07:31:13:963 -- QuickUnlock.OnStop
15.11.2017 07:31:13:964 -- QuickUnlock.OnDestroyTrue
15.11.2017 07:31:18:767 -- GroupActivity.OnPause
15.11.2017 07:31:18:768 -- Timeout start
15.11.2017 07:31:18:798 -- DatabaseSettingsActivity.OnCreate
15.11.2017 07:31:18:799 -- DatabaseSettingsActivity:apptask=
15.11.2017 07:31:18:979 -- DatabaseSettingsActivity.OnStart
15.11.2017 07:31:18:985 -- DatabaseSettingsActivity.OnResume
15.11.2017 07:31:18:985 --  DatabaseIsUnlocked=True
15.11.2017 07:31:18:986 -- Timeout cancel
15.11.2017 07:31:19:536 -- GroupActivity.OnStop

**Comment by StevenZezulak** [comment]
I would just like to add that I am having a similar/the same issue, with this appearing in my log as well:
>15.11.2017 07:31:09:29 -- InitFingerprintUnlock
>15.11.2017 07:31:09:30 -- Already listening for fingerprint!

I noticed that it happens when manually locking the database with the lock icon. After the first lock, the fingerprint works, but manually locking the database again shows a red exclamation mark and a "Fingerprint operation cancelled" toast. The app does not respond to any fingerprint attempts until pressing Home and reopening Keepass2Android through either the notification or launcher.

Waiting for the database to time out does not cause the issue like the manual lock.
