### ISSUE TITLE
feature request : faster note copy

### ISSUE THREAD

**Issue by PacTrix** [PhilippC/keepass2android#1260]
hello 
1) i did offered you a beer
2) if you want to copy part of a noté, you need to édit the note. or in notes you most often have information that you use selectively like several crédit cards détail. in many other similar app when you click in a noté you can select and copy only part of the note and you dont need to édit it to do that. this is much faster and more secure

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Cheers! I know what you feel pain from. I used to do this in beginning.But you can use custom fields as many you want for your example credit card 
Field CVV
Field expiry
Field pin
All can be copy fast. And made accessible through keyboard. Kp2a ⌨️ 

If you have more cards use template's entry with custom fields pre defined.

Use notes just as notes. For dump off text info. It's a textfiEld
Not single field.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
dupe #689

**Comment by PhilippC** [comment]
duplicate

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Cheers! I know what you feel pain from. I used to do this in beginning.But you can use custom fields as many you want for your example credit card
Field CVV
Field expiry
Field pin
All can be copy fast. And made accessible through keyboard. Kp2a ⌨️

If you have more cards use template's entry with custom fields pre defined.

Use notes just as notes. For dump off text info. It's a textfiEld
Not single field.
