### ISSUE TITLE
Discord app support

### ISSUE THREAD

**Issue by stefansundin** [PhilippC/keepass2android#1262]
Hi,

I am trying to use this app with [the Discord app](https://play.google.com/store/apps/details?id=com.discord), but am having some issues with autofill. Even if this may be a user error on my side, I hope that by opening this issue we can document it for others, because I am having issues figuring it out on my own.

First of all, on the login screen, when I try to autofill a field, a toast pops up with this text:
> Contents can't be autofilled

I then noticed that there's a link with the text `Use a password manager?`. When I click it, a dialog shows up with the following text:

> ### Password Manager
> If you use a password manager, you'll need to allow it in Accessibility Settings -> Downloaded Services. Don't worry, we can take you there.
> <kbd>Cancel</kbd>   <kbd>Open Settings</kbd>

Clicking on the <kbd>Open Settings</kbd> button does bring me somewhere, but I can't figure out how to allow Keepass2Android. I am guessing that this is not supported at the moment, and if that's the case, is there any plans to add support for it?

Thanks!

**Comment by PhilippC** [comment]
which Android OS version are you running? I tried with Android 10 and it works: After opening the app, I select "Log in" (or whatever the exact translation is). The Autofill prompt is opened but when returning to discord, only the username is filled (probably because the password field is marked as No-Autofill. I can long-tap the password field, select the the three vertical dots and then choose Autofill again which shows "Discord" as first item in the list. If I select it, the password is entered.

**Comment by stefansundin** [comment]
I'm on Android 10 as well (OxygenOS). I get the "Contents can't be autofilled" message for both the username and password field, when attempting to autofill in the way you are describing.

Any idea regarding the "Accessibility Settings -> Downloaded Services" hint that they give?

**Comment by PhilippC** [comment]
accessibility sounds like you are trying to use the accessibility based autofill? I was talking about Android Autofill service (introduce in Android 8). Do you have that enabled for KP2A (see app settings - password access)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
I couldn't remember experience any issue with discord.in Android 9 or 10 automatically filled

**Comment by stefansundin** [comment]
Yep, I have the new autofill thing enabled, that is how I usually fill passwords. Reading [this page](https://philippc.github.io/keepass2android/AccServiceAutoFill.html) makes it clear that the thing that the Discord app is referring to is the old autofill stuff. So I'm guessing Discord has not been updated to support the new autofill service.

Still, a bit strange that our results seem to differ. Anyhow, I'm assuming that the Discord app will eventually be updated and this problem will go away. Feel free to close this issue, thanks for the assistance!

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
I successfully used kp2a auto fill in Discord app Android 10 again. But totp entering via kp2akeyboard to button did not work. I had to copy and paste it manually.
