### ISSUE TITLE
Add a "Copy TOTP" button to the entry notification

### ISSUE THREAD

**Issue by stefansundin** [PhilippC/keepass2android#1263]
I think it would be very convenient to have a <kbd>Copy TOTP</kbd> button in the entry notification. In some cases I now have to:

1. Switch to the Keepass2Android app.
2. Find the TOTP field.
3. Click the dropdown button next to it.
4. Click <kbd>Copy to clipboard</kbd> button.
5. Switch back to the app.
6. Paste TOTP.

It would be possible to eliminate steps 1-5 if there was a way to copy the TOTP via the notification. I think it would be very useful!

Thanks!

**Comment by PhilippC** [comment]
already implemented in https://play.google.com/apps/testing/keepass2android.keepass2android
