### ISSUE TITLE
Set QuickEntry Notification to max priority.

### ISSUE THREAD

**Issue by Mellelmejor** [PhilippC/keepass2android#1265]
Could you add an option or any way to set the quickentry notifications, or just all Keepass2Android notifications for that matter, to be always on top of all other notifications?
When I want to open keepass to fill in my credentials on Brave and other apps that are not supported, I need to go search the notification of kee through a lot of other notifications I have on my phone. Usually Telegram, Google Keep, Whatsapp and SMS notifications go above keepass, and sometimes keepass gets stuck in between those and I have to search through all of them to find the app.
I tried using AutoNotification to set keepass notificaiton priority to urgent, but it keeps getting mixed with other notification no matter the priority I set for Keepass or the other apps.
Can you set Keepass to stay on top of all other apps all the time so that is easily accesible?
I'm using Android 10, Oneplus 7.
I tried changing the priority levels on Android itself but there's no option that achieves keeping keepass above all other apps.

**Comment by PhilippC** [comment]
please see the docs (https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md) for the browser based workflow. I would not recommend to use the notification.
