### ISSUE TITLE
Microsoft account confirmation every open

### ISSUE THREAD

**Issue by branpurn** [PhilippC/keepass2android#1267]
Every time I open my database stored on OneDrive, I get a prompt to confirm the email of my Microsoft account, and to confirm I want to grant KeePass permission.

This didn't use to occur, is this not circumventable?

**Comment by cjk28** [comment]
I've seen that quite often too

**Comment by towadroid** [comment]
Seems like a duplicate of #1038

**Comment by Dark-Noir** [comment]
Similar issue here, it's not every time but very often. Using the beta app from play store.

**Comment by towadroid** [comment]
@PhilippC Suggest to close, as #1038 was closed via https://github.com/PhilippC/keepass2android/commit/15d3492ae37fc18c8fd38994f5f13154de53286d.

**Comment by PhilippC** [comment]
thanks for the hint. closing as duplicate of #1038.
