### ISSUE TITLE
internal cache location

### ISSUE THREAD

**Issue by drewgrif** [PhilippC/keepass2android#1268]
Sorry for asking the question.  I was using software to manage my Google Drive and deleted the keepass database.  I am trying to get it restored but am having little luck thus far.  I noticed that the keepass2android looked to sync but could not because the gdrive location was gone.  It used the internal cache and I could open it up.  Can I export from there or can I find the location of the cached file?

**Comment by PhilippC** [comment]
yes, you can export: unlock the database from cache, then go to settings - database - export - kdbx and select a target location of your choice!

**Comment by drewgrif** [comment]
Thanks!! Donated an Octoberfest Beer to you on paypal.
