### ISSUE TITLE
New entry does not work after latest Android 10 Update

### ISSUE THREAD

**Issue by bitstreamout** [PhilippC/keepass2android#1271]
With no result of a search thre are two possiblities, first to choose an other entry and second to add a new entry ... last point does not work anymore ... AFAICR there was a plus Symbol which seems to be gone and replaced with the text ``EINTRAG FÜR URL ANLEGEN``  ... pressing this highligths a larger area then the text its self and does nothing else

**Comment by PhilippC** [comment]
can anybody confirm this? I cannot reproduce.

**Comment by bitstreamout** [comment]
Meanwhile it works again
