### ISSUE TITLE
Crash when attempting to copy/duplicate entry

### ISSUE THREAD

**Issue by mattok** [PhilippC/keepass2android#1275]
I'm using Keepass2Android 1.07b-r0, without any plugins. When I go to a subfolder, long click an entry and select the copy icon (overlapping rectangles), the app crashes and restarts. It appears that although the app crashes, a duplicate entry is still created.

It doesn't do this for all entries though. There are several entries that it reliably crashes on, and these simply have a name, username and password. It doesn't seem to happen for entries that were created very recently. It seems to happen for entries created pre-2019. Hope this helps!

**Comment by PhilippC** [comment]
fixed in 1.08 (https://play.google.com/apps/testing/keepass2android.keepass2android)
