### ISSUE TITLE
Quick unlock gets lost after some minute or hours

### ISSUE THREAD

**Issue by Seba2323** [PhilippC/keepass2android#1276]
Since I'm using a new phone which is a Huawei P30 Pro quick unlock works only for some minutes. After a while I need to reenter my full password.
Befote I was using a Samsung S9 and there the quick unlock was working until a restart of the phone.
In my understanding I'm using the same KeePass2android settings. 
Is this a bug? Is there any new setting or change?

**Comment by PhilippC** [comment]
this is always related to "battery optimization" - please disable this for the app.
