### ISSUE TITLE
Master-Passwort-Typ und damit auch Pfad zur Schlüsseldatei werden nicht gemerkt

### ISSUE THREAD

**Issue by Tien1602** [PhilippC/keepass2android#1277]
Wenn der Master-Passwort-Typ
"Kennwort + Schlüsseldatei + Challenge Response für KeypassXC" ausgewählt ist merkt sich Keepass2Android diese Einstellung nicht. Trotz entsprechender Einstellung in den Optionen.
Der Gewinn eines kurzen Passworts durch die Verwendung des Yubico Keys geht damit komplett verloren, da man nun bei der Anmeldung deutlich mehr eingeben muss.

Ich hoffe der Bug lässt sich relativ schnell beseitigen.
Oder habe ich etwas übersehen?

**Comment by PhilippC** [comment]
duplicate of #1214
