### ISSUE TITLE
Cannot see files in OneDrive

### ISSUE THREAD

**Issue by lkjasdlfwe** [PhilippC/keepass2android#1279]
Since the last 4 or 5 days, I cannot see any files within OneDrive when accessed from within the Keepass2android OneDrive connector.

To reproduce:

1. Open app and select open existing database
2. Select OneDrive as the connector
3. Follow the sign in prompts.
4. [See that no files are displayed.](https://i.imgur.com/00j7K2V.jpg)

I have tried this with all three options given for OneDrive yet am greeted with the same thing. The files do exist on OneDrive yet I cannot see anything in the root directory. Other apps (Keepassium, Solid explorer, iOS files app) can connect to and see OneDrive files just fine.

**Comment by PhilippC** [comment]
I cannot reproduce. Which version of the app are you using? Can you please enable debug logging and send me the log after trying to crocoapps@gmail.com?

**Comment by lkjasdlfwe** [comment]
> I cannot reproduce. Which version of the app are you using? Can you please enable debug logging and send me the log after trying to crocoapps@gmail.com?

Hi, thanks for responding. Check your inbox for the debug log.

**Comment by lkjasdlfwe** [comment]
It started working again. Thanks for the help!
