### ISSUE TITLE
WordPress login submits form after entering username

### ISSUE THREAD

**Issue by auricgoldfinger** [PhilippC/keepass2android#128]
I'm not sure whether this is a bug or a configuration option, but when I use the"username" button to enter my username in my WordPress installation, the form submits and fails because I didn't enter my password yet. What makes the form submit already?

I tried to disable autofill but it had no effect...

**Comment by Vocylis** [comment]
I've been noticing this lately also. This behavior is exhibited on every login form now as far as I can tell. I can't find a way to disable it either.

**Comment by PhilippC** [comment]
closing as duplicate of #89
