### ISSUE TITLE
security flag on uptodown

### ISSUE THREAD

**Issue by devincowan** [PhilippC/keepass2android#1285]
Just noticed that 1.07-r1 is flagged on UptoDown as a "suspicious" security risk.
https://keepass2android.en.uptodown.com/android

It does look like the shasum might not be the same as your release #892?

![image](https://user-images.githubusercontent.com/17934193/84691045-b503b000-af00-11ea-8da4-7cf7a0457e06.png)

$ shasum -a 256 keepass2android.keepass2android-1.07-r1.apk 
eb6886a38bcd9acaee00902de69696d9248fac80dc90d3e5b1a218be73c2e64d

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
SHA-256
3604ce58cb264c4df333e428e722ac3173abb0e5bf4195d09b5dabd8fdbf3cc4

https://www.virustotal.com/gui/file/3604ce58cb264c4df333e428e722ac3173abb0e5bf4195d09b5dabd8fdbf3cc4/details

This the same I got from linked website of you. 
May upload your apk file to check?

**Comment by devincowan** [comment]
thanks for taking a look @4-FLOSS-Free-Libre-Open-Source-Software.

I think the flagged apk was this one:
https://keepass2android.en.uptodown.com/android/download/1944507

Odd that it shows the Microsoft "Trojan:Script/Foretype.A!ml" warning in UpToDown:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/17934193/84914236-9e806480-b078-11ea-839e-0f7b79550599.png">

But I don't see that in the Virustotal report:
https://www.virustotal.com/gui/file/3604ce58cb264c4df333e428e722ac3173abb0e5bf4195d09b5dabd8fdbf3cc4/detection

Uploaded zipped apk here...
[keepass2android-1-07-r1.apk.zip](https://github.com/PhilippC/keepass2android/files/4793315/keepass2android-1-07-r1.apk.zip)

**Comment by PhilippC** [comment]
Script/A!Ml is some AI saying there's a password related threat. Well, the app is actually asking for all your passwords 🤣 . Don't take this too serious...
