### ISSUE TITLE
Idea about AutoFill for OTP

### ISSUE THREAD

**Issue by schklom** [PhilippC/keepass2android#1286]
I have an idea about the closed issue #1001. I realize it's been not far from a year since the issue opened, but I haven't seen a solution on github.
I'm not an Android developper and I don't know how the Autofill framework works, but I think my idea should be doable.

It looks like KP2A has a way to differentiate between an app's username and password fields.
Therefore, it should be possible to know what field (from an app that requires an input) the user calls KP2A from.
My idea is that if the user wants, he/she can tell KP2A that the field corresponds to TOTP and have it filled directly next time.
Ideally, the user could specify in KP2A to use TOTP or any other field if he/she wants for that specific call to Autofill but it might be harder to implement I think.

For the user, the scenario would be:
_User starts a request with autofill to Keepass for a field like username/password/TOTP
_Keepass either searches for the app name and field name and autofills it if available, or Keepass asks the user to find the keepass entry and field and stores the info for future use
_The app field gets autofilled by default if username/password, or by something the user specifies if he/she wants

What do you think about it ?

PS: big fan of the app, it's really well done and useful :)

**Comment by Small-Ku** [comment]
How a field should be filled seems hinted by the app, not differentiate by KP2A.
TOTP is not officially supported to be hinted. Hints that is officially supported can be find [here](https://developer.android.com/reference/android/view/View#setAutofillHints(java.lang.String...)).
Ref: [Android Developer](https://developer.android.com/guide/topics/text/autofill-optimize#predefined_hint_constants)

**Comment by PhilippC** [comment]
@schklom  can you give examples of login pages/apps which you have in mind

**Comment by schklom** [comment]
@PhilippC I was thinking of when you add a google account with a TOTP through Gmail app for example, or Dropbox app, basically any app where you setup a TOTP.

**Comment by Eifelschaf** [comment]
It would already be nice to pop up the notificationthat lets you easily pick the otp if a login is filled from an alreally opened db. right now this only seems to happen if an entry is picked or the db has just been opened.

**Comment by Indubius** [comment]
> It would already be nice to pop up the notificationthat lets you easily pick the otp if a login is filled from an alreally opened db. right now this only seems to happen if an entry is picked or the db has just been opened.

Apologies, are you referring to the desktop app? At least on android, I never have the possibility to fill in TOTP automatically.
But would support the approach having it on android seriously!

**Comment by GoodSir42** [comment]
It does not fill in automatically, but keepass2android provides a notification with a button to copy the TOTP. I just noticed, that the notification does not seem to pop up if an entry was retrieved from an already opened database.
