### ISSUE TITLE
[BUG] App doesn't even open

### ISSUE THREAD

**Issue by RealGJ** [PhilippC/keepass2android#1288]
Everything was great till last update.

Issue: when tried to open app, it doesn't open. Just return back to launcher. No crash nothing.

Device: Xiaomi Redmi Note 4 Android 7.0

App version: 1.08b-pre1

Thanks.

**Comment by PhilippC** [comment]
sorry. Please see https://github.com/PhilippC/keepass2android/issues/1287 for updates.
