### ISSUE TITLE
Weird and Annoying behaviour 

### ISSUE THREAD

**Issue by mhbr12742** [PhilippC/keepass2android#1289]
So I updated to the latest version yesterday morning and ever since when I load Keepass it flashes the login page but immediately goes to a white page with Keepass at the top in black and I get a dialog box come up asking to select one of my keyboards. If I select 1 it immediately goes back to the login page and switches to the white screen again asking me for a keyboard. The only way I can break the cycle is to keep pressing back quickly till it stays on the login screen. At which point factual recognition works on my Google pixel 4xl.

I am logging on to Onedrive. This experience happens when creating passwords too. It seems as if when it needs a keyboard it gets confused. 

I updated to the Google drive fix version today but have the same issue. 

I was fine on the initial version 8. 

Anyone else seeing this?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
You can disable the switching of Keyboard in options and find out of the problem persists for you. But it should not ask your apparently for keyboard if you select the Apps keyboard kp2a keyboard. Also make sure in Android system settings your Input options at the keyboard is enabled

**Comment by mhbr12742** [comment]
Thanks for this but I would still like to understand why it only started happening since release 8. I have had multiple keyboards for ages on android 10 with no issues

**Comment by PhilippC** [comment]
I don't know why this would be related to the update, but if you have enabled to use the built-in keyboard inside the app then that's expected behavior. Please re-open if this setting is not enabled.

**Comment by mhbr12742** [comment]
HiThis has got so bad I don't think I can continue to use the product. I have checked the keyboard settings and all looks fine and as I say before the 2 recent updates all worked fine. I have added 2 screenshot that might help. As said previously I get the white screen first this does say synchronisation was successful, then get the second screen shot asking me to select the keyboard. When I do it stays on the first screenshot. The way I can get back to the login page is to rapidly press back. If you are too slow it goes to the login page and stra away goes to the white screen wanting to select the keyboard again. I will continue to try and work out what it might be as I use your app several times a day and it would be a bugger to move. Mike Huxleymikehuxley@blueyonder.co.ukTel: 0797 799 1676 On 17 Jun 2020 19:53, PhilippC <notifications@github.com> wrote:
I don't know why this would be related to the update, but if you have enabled to use the built-in keyboard inside the app then that's expected behavior. Please re-open if this setting is not enabled.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
@mhbr12742 you should check the new version. it gives you a screen with keyboard swith and retry button instead of white page. Just FYI

**Comment by mhbr12742** [comment]
Awesome thanks Mike Huxleymikehuxley@blueyonder.co.ukTel: 0797 799 1676 On 22 Jul 2020 18:03, Bernd Eichelberger <notifications@github.com> wrote:
@mhbr12742 you should check the new version. it gives you a screen with keyboard swith and retry button instead of white page. Just FYI
