### ISSUE TITLE
Darkmode support.

### ISSUE THREAD

**Issue by stonerl** [PhilippC/keepass2android#1290]
Android 10 introduced a dark mode.

It would be nice if keepass2android would add support for this.

[Further information](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
https://github.com/PhilippC/keepass2android/issues/966

**Comment by stonerl** [comment]
I wonder why I didn't find that open issue...
