### ISSUE TITLE
Face unlock authentification deadlock

### ISSUE THREAD

**Issue by aotten80** [PhilippC/keepass2android#1291]
affected version: 1.08b-pre2

The face unlock is in general working fine with the beta release. Problem is, when navigating back to the main login screen, that the authentication routine is triggered immediatelly. So if you are watching your phone you will be directly logged in again... and again... and again.

I think the problem is related to the previous fingerprint authentication code. This kind of authentication is possibly triggered only of one finger is touching the sensor. For face unlock this seems to be different.

A solution could be to press this fingerprint icon to trigger the face unlock authentification instead of doing this automatically. But for the first start-up of the app it would be OK to do this automatically.

**Comment by DerekAlfonso** [comment]
Just wanted to add that I was about to request face authentication and saw that it's in the beta, now I'm headed to donate a beer

**Comment by PazzoMas** [comment]
> Just wanted to add that I was about to request face authentication and saw that it's in the beta, now I'm headed to donate a beer

Yep, the same. Waiting for this feature for my Google Pixel 4
