### ISSUE TITLE
App keeps showing a blank screen

### ISSUE THREAD

**Issue by fabkury** [PhilippC/keepass2android#1292]
I wish I could describe it better, but since the last update it keeps sending me to a blank screen. I can escape it if I go back (swipe in from the side) twice quickly in a row. The blank screen looks like the screen where I'd have to log back into my OneDrive account, but it's fully empty.

**Comment by PhilippC** [comment]
do you have the setting enabled that you want to use KP2A's keyboard inside the app? If so, can you try to disable it and see if that changes the behavior?

**Comment by fabkury** [comment]
You're right! It appears to have solved the problem!

Thanks!!!!

Fabrício
