### ISSUE TITLE
Feature suggestion: copy username with a single click and copy password by waving a proximity sensor

### ISSUE THREAD

**Issue by kofaysi** [PhilippC/keepass2android#1295]
Dear Phillip, thank you for the great app.

My suggestion (I learned from a Blackberry password manager app -- can it be patented?) aims to improve username and password copying.

Currently, the most efficient way to fill in username and pwd I see is the following:
* open k2a and find the entry to fill
* switch to the other app (usually a browser) where the entry has to be applied
* pull down the notification area and copy user name
* paste the username into a field
* pull down the notification area and copy the password
* paste the password into a field

The suggestion is:
* open k2a and find the entry to fill
* copy username by one click within k2a (new button required)
switch to the other app (usually a browser) where the entry has to be applied
* paste the username into a field
* wave the hand in front of the proximity sensor of the mobile, password field would be copied into the clipboard
* paste the password into a field

Thank you for reading the suggestion and I hope to be implemented or improved.

**Comment by PhilippC** [comment]
please don't use the clipboard at all, rather try one of the suggested workflows (https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md)
