### ISSUE TITLE
refresh entry activity after modifying tags

### ISSUE THREAD

**Issue by CapitainFlam** [PhilippC/keepass2android#130]
Hi, 
I modified an entry (added tags) as "Android, game "
I saved the entry.
The entry didn't t show my modification. 
But when I get back to it in modification,  it was well recorded. 
Indeed, modification + save should be followed by a refresh of the screen after saving modification. .. to show modified infos.

**Comment by CapitainFlam** [comment]
thanks for taking this in account 👍

**Comment by PhilippC** [comment]
seems to be fixed already, cannot reproduce anymore. please re-open if it does occur again.
