### ISSUE TITLE
Cannot merge two database local files

### ISSUE THREAD

**Issue by noisemaker00** [PhilippC/keepass2android#1304]
I cannot understand how to merge two databases as I can do with KeePass on windows. If I edit my DB on pc then copy the file on my smartphone how can I merge that file with the DB stored on smartphone and used by KP2A?

**Comment by PhilippC** [comment]
KP2A has a different approach. You do not edit two files and then merge them, but you always open the same file from the same location. If another tool has modified the file, then KP2A will allow to merge the changes.
