### ISSUE TITLE
keyfile textfield unusable

### ISSUE THREAD

**Issue by leder11011** [PhilippC/keepass2android#1311]
Hi philipp,

Thank you for kneepass!

Unfortunately I wasn't able to change the master password with keeping the secrets key file!

I Now have master password only with total usage of finger print.

What Do you say?

Ciao
Gerrit

**Comment by PhilippC** [comment]
please use Keepass2 on Windows to change/re-add the key file. This is considered a duplicate of https://github.com/PhilippC/keepass2android/issues/1227
