### ISSUE TITLE
File is Corrupted

### ISSUE THREAD

**Issue by eLIANT-TechnologyServices** [PhilippC/keepass2android#1313]
Third bullet of the error message says, "If you can still open the file on your PC, contact support."  So, here I am.

Two different .kdbx files on my server - one for work, and one for personal.  Both accessible via various PCs and phones over the last few years.  (Love the product.)  Now one of the two is inaccessible from my phone - but only from my phone.  My wife can access it using phone, and I can get to it from my PC.  I can still access the other file, but not this one.  Very strange.

I just this week got a new phone and installed a fresh copy of Keepass2Android.  Same problem.  The kdbx file causing the problem is 1.18Mb, if that matters, and the other is only 42Kb.  I can get to the FTP server via the App and see all the files (kdbx and otherwise),  select the kdbx file in question, put in my Master Password, wait a few seconds, and ---  fail message.

Now what?

**Comment by eLIANT-TechnologyServices** [comment]
Open the problem file on my PC, saved it directly back to the server under a different name, cannot open the new file using phone.

And I don't see any options when saving the file that might let me save under a different method or format (compressed or not.)

**Comment by eLIANT-TechnologyServices** [comment]
Also,  before the "Corrupted" message, I get the little black text box telling me that "Source file and cache are synchronized."  How can that be?

**Comment by PhilippC** [comment]
which version are you trying? If this is not from the beta channel, please try with https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by eLIANT-TechnologyServices** [comment]
I’m running the current version from Google Playstore: v 1.08-r1

 

Just now I…

-removed all local copies of all DBs

- uninstalled

- reinstalled

- attempted to open the problem file – fail

- attempted to open the other (not a problem) file – success

 

I also just now joined the tester group.  How will I know when a beta version get installed?

 

 

Sincerely, 
  
Philip W. Kelly 
eLIANT Technology Services 
  
 <http://www.eliantservices.com/> www.eliantservices.com 
937-974-5521

**Comment by eLIANT-TechnologyServices** [comment]
The beta version fixed the problem.

 

Are there responsibilities of being in the beta tester group?  Should I file an occasional report?

 

 

 

Sincerely, 
  
Philip W. Kelly 
eLIANT Technology Services 
  
 <http://www.eliantservices.com/> www.eliantservices.com 
937-974-5521

**Comment by PhilippC** [comment]
glad to hear that! Being a beta tester just means you should be aware that new updates might not be as well tested as on the production channel. If you find a bug, you're always welcome to report it!
