### ISSUE TITLE
Chrome allowing use of keepass2android

### ISSUE THREAD

**Issue by nicholseric** [PhilippC/keepass2android#1320]
I do not use the accessibility plugin feature so chrome never prompts for or allows use of keepass2android. But, today, after opening a link from YouTube, there it was! Opening the same link in chrome manually results in different behaviour. What's going on here? I couldn't repeat it the next day.

![Screenshot_20200714-100456](https://user-images.githubusercontent.com/9997910/87455223-f9df3d00-c5b9-11ea-8066-b1833467f021.png)
I am on  keepass2android Version 1.08b-r0
Google Chrome | 83.0.4103.106 (Official Build) (32-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Android 11; Pixel 3a XL Build/RPB2.200611.009

**Comment by PhilippC** [comment]
are you sure this is Chrome? Maybe it's a webview inside the youtube app?

**Comment by nicholseric** [comment]
I can open the chrome app and a few tabs to different sites. Then in theYouTube app, I click on that link and it takes me to a new chrome tab with the others I opened earlier. In this screenshot I have GitHub opened in one tab and the aeroponics calculator open from YouTube. Doesn't this suggest that it isn't webview inside the YouTube app? I like the behaviour and would like all chrome tabs to work this way without enabling the keepass accessibility plugin.
![Screenshot_20200723-144110](https://user-images.githubusercontent.com/9997910/88341559-9f00c080-ccf2-11ea-9d91-15aaca9c04b7.png)

**Comment by nicholseric** [comment]
I'm reading that the YouTube app uses Chrome Custom Tabs https://developer.chrome.com/multidevice/android/customtabs and not WebView.

**Comment by nicholseric** [comment]
I have been able to reproduce the prompt for keepass2android in chrome 84 and 86dev without using YouTube. I created a bookmark to https://aeroponicscalculator.com/ and then in both browsers, by visiting that bookmark, I get promoted to use keepass2android. I am not using the accessibility KP2A Autofill plugun. I'm pretty sure this is not a feature and it hasn't been working historically but I hope the behaviour becomes standard. I see that most people using 3rd party password managers wish for this behaviour and resort to using accessibility plugins which add to the risk of password exposure. Maybe someone else has the time to dig into some debug logs to see how and why this is working.

**Comment by nicholseric** [comment]
I found another way to reliably get chrome to prompt for keepass2android. Get to a page that has your password field. Force stop chrome. Reopen chrome and it will prompt. It's inconvenient but if you have chrome set to reopen tabs, it's easier than making bookmarks.
![Screenshot_20200801-075433](https://user-images.githubusercontent.com/9997910/89104220-73ee2f00-d3cc-11ea-977e-091b3802b87d.png)

**Comment by cjk28** [comment]
Whats the deal with support for chrome, it seems to be fully working for me right now, autofill API filling in passwords with a single click, but I thought it wasn't meant to be working in chrome

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
![IMG_20201202_125949](https://user-images.githubusercontent.com/46166740/100870222-90939400-349e-11eb-9a48-1e258e59b3ae.jpg)
![IMG_20201202_125916](https://user-images.githubusercontent.com/46166740/100870230-94271b00-349e-11eb-94b3-84e70d5fa2c9.jpg)

**Comment by svenschn** [comment]
Is this still working for you? It also started working all of a sudden last year but yesterday after my phone was updated to Android 11 (Galaxy S10), it no longer works.

**Comment by PhilippC** [comment]
@svenschn are you in the beta channel? I uploaded a new version this morning with changes to autofill (which should improve the situation, not make it worse, of course, but anyway...?)

**Comment by svenschn** [comment]
@PhilippC No, I am not. But of course, I can try the beta. I have requested to join the beta channel now.

**Comment by svenschn** [comment]
@PhilippC Thanks a lot, it looks like its working in the beta!

**Comment by svenschn** [comment]
@PhilippC I have just updated to 1.08d-r5 and now it does not work again. It works if I open a page in the Gmail app e.g., though.

**Comment by PhilippC** [comment]
which version did you run before?!

**Comment by svenschn** [comment]
Unfortunately, I am not 100% sure which version it was exactly (there is no way to check, is there?). It was the version from the beta channel I installed on January 8th.

**Comment by PhilippC** [comment]
this should be fixed in 1.09a-pre1 (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by nicholseric** [comment]
Donation on the way!

**Comment by Offerel** [comment]
Can someone please tell me, how I can get this work with chromium browsers? At least Autofill is working fine with Firefox and most apps on a Samsung Galaxy S20FE. I only rarely used Chromium browsers before, but today I installed Chrome stable. If I go to login site, like the one of a Fritzbox Router or GitHub there is no Kp2A prompt.

I have no Kp2A plugins installed.

**Comment by PhilippC** [comment]
@Offerel I don't recommend the autofill plugin, I'd rather suggest to switch to the beta channel  (https://play.google.com/apps/testing/keepass2android.keepass2android) and see if 1.09a-pre1 works.

**Comment by Offerel** [comment]
I'm since ages on the beta channel and 1.09a-pre1 is installed. So at least for me on a Samsung Galaxy S20 FE with standard german VDF ROM, Samsung Internet 13.2.2.4 isn't working. It's no big issue for me, since my standard browser is still Firefox, but from time to time, i have to use Samsung Internet. 

If you want, we can try to dig a little bit deeper here. You can't have every combination of app and phone for testing and if i can do something for you, please let me know.
