### ISSUE TITLE
Unable to modify database - Database modified externally

### ISSUE THREAD

**Issue by billie80** [PhilippC/keepass2android#1321]
Every time I try to modify an entry of a database I get the message "Database modified externally".

I tried deleting the recently opened databases, the App cache and also killed the App.

This is with Keepass2Andoid Offline 1.07b on Android 10.

**Comment by billie80** [comment]
Below is the content of the debug log until the message popped up. I am happy to provide more information if required.


15.07.2020 22:50:41:108 -- DatabaseSettingsActivity.OnPause 15.07.2020 22:50:41:112 -- Timeout start 15.07.2020 22:50:41:136 -- GroupActivity.OnStart 15.07.2020 22:50:41:137 -- GroupActivity.OnResume 15.07.2020 22:50:41:138 -- DatabaseIsUnlocked=True 15.07.2020 22:50:41:138 -- Timeout cancel 15.07.2020 22:50:41:158 -- File flags: 326 15.07.2020 22:50:41:624 -- DatabaseSettingsActivity.OnStop 15.07.2020 22:50:41:627 -- DatabaseSettingsActivity.OnDestroyTrue 15.07.2020 22:50:45:196 -- GroupActivity.OnPause 15.07.2020 22:50:45:197 -- Timeout start 15.07.2020 22:50:45:555 -- GroupActivity.OnStop 15.07.2020 22:50:46:620 -- GroupActivity.OnDestroyTrue 15.07.2020 22:50:46:666 -- OngoingNotificationsService.OnTaskRemoved: android.intent.action.MAIN 15.07.2020 22:50:46:666 -- QuickLocking database 15.07.2020 22:50:46:679 -- Starting/Updating OngoingNotificationsService. Database QuickLocked 15.07.2020 22:50:46:698 -- Stopping clipboard service due to database lock 15.07.2020 22:50:46:699 -- Stopping clipboard service due to database lock 15.07.2020 22:50:46:699 -- CopyToClipboardService.OnDestroy 15.07.2020 22:50:46:699 -- Destroyed Show-Notification-Receiver. 15.07.2020 22:50:47:534 -- OngoingNotificationsService.OnTaskRemoved: 15.07.2020 22:50:47:535 -- Database already QuickLocked 15.07.2020 22:50:47:540 -- Starting/Updating OngoingNotificationsService. Database QuickLocked 15.07.2020 22:50:50:78 -- KeePass.OnCreate 15.07.2020 22:50:50:79 -- KeePass:apptask= 15.07.2020 22:50:50:80 -- Loaded task keepass2android.NullTask 15.07.2020 22:50:50:80 -- KeePass.OnCreate 15.07.2020 22:50:50:85 -- KeePass.OnStart 15.07.2020 22:50:50:85 -- KeePass.OnStart 15.07.2020 22:50:50:109 -- Loaded task keepass2android.NullTask 15.07.2020 22:50:50:113 -- Starting QuickUnlock 15.07.2020 22:50:50:127 -- QuickUnlock.OnCreate 15.07.2020 22:50:50:128 -- QuickUnlock:apptask= 15.07.2020 22:50:50:149 -- requesting fingerprint permission 15.07.2020 22:50:50:154 -- QuickUnlock.OnStart 15.07.2020 22:50:50:155 -- QuickUnlock.OnResume 15.07.2020 22:50:50:155 -- DatabaseIsUnlocked=False 15.07.2020 22:50:50:155 -- InitFingerprintUnlock 15.07.2020 22:50:50:159 -- KeePass.OnStop 15.07.2020 22:50:50:159 -- KeePass.OnDestroyTrue 15.07.2020 22:50:50:160 -- KeePass.OnDestroyTrue 15.07.2020 22:50:50:160 -- QuickUnlock.OnPause 15.07.2020 22:50:50:197 -- OnRequestPermissionsResult TrueTrue 15.07.2020 22:50:50:197 -- _fingerprintPermissionGranted 15.07.2020 22:50:50:198 -- InitFingerprintUnlock 15.07.2020 22:50:50:198 -- QuickUnlock.OnResume 15.07.2020 22:50:50:198 -- DatabaseIsUnlocked=False 15.07.2020 22:50:50:199 -- InitFingerprintUnlock 15.07.2020 22:50:58:175 -- QuickUnlock successful! 15.07.2020 22:50:58:241 -- Starting/Updating OngoingNotificationsService. Database Unlocked 15.07.2020 22:50:58:263 -- QuickUnlock.OnPause 15.07.2020 22:50:58:275 -- StackBaseActivity.OnActivityResult Canceled/0 15.07.2020 22:50:58:275 -- TryGetFromActivityResult: no data 15.07.2020 22:50:58:301 -- GroupActivity.OnCreate 15.07.2020 22:50:58:301 -- GroupActivity:apptask= 15.07.2020 22:50:58:302 -- Loaded task keepass2android.NullTask 15.07.2020 22:50:58:321 -- GroupActivity.OnStart 15.07.2020 22:50:58:322 -- GroupActivity.OnResume 15.07.2020 22:50:58:322 -- DatabaseIsUnlocked=True 15.07.2020 22:50:58:322 -- Timeout cancel 15.07.2020 22:50:58:328 -- File flags: 326 15.07.2020 22:50:58:800 -- QuickUnlock.OnStop 15.07.2020 22:50:58:802 -- QuickUnlock.OnDestroyTrue 15.07.2020 22:51:00:750 -- GroupActivity.OnPause 15.07.2020 22:51:00:750 -- Timeout start 15.07.2020 22:51:00:767 -- GroupActivity.OnCreate 15.07.2020 22:51:00:768 -- GroupActivity:apptask= 15.07.2020 22:51:00:770 -- Loaded task keepass2android.NullTask 15.07.2020 22:51:00:791 -- GroupActivity.OnStart 15.07.2020 22:51:00:792 -- GroupActivity.OnResume 15.07.2020 22:51:00:792 -- DatabaseIsUnlocked=True 15.07.2020 22:51:00:792 -- Timeout cancel 15.07.2020 22:51:00:799 -- File flags: 326 15.07.2020 22:51:01:279 -- GroupActivity.OnStop 15.07.2020 22:51:02:798 -- GroupActivity.OnPause 15.07.2020 22:51:02:799 -- Timeout start 15.07.2020 22:51:02:814 -- EntryActivity.OnCreate 15.07.2020 22:51:02:815 -- EntryActivity:apptask= 15.07.2020 22:51:02:842 -- Loaded task keepass2android.NullTask 15.07.2020 22:51:02:851 -- EntryActivity.OnStart 15.07.2020 22:51:02:851 -- EntryActivity.OnResume 15.07.2020 22:51:02:852 -- DatabaseIsUnlocked=True 15.07.2020 22:51:02:852 -- Timeout cancel 15.07.2020 22:51:02:876 -- Received intent to provide access to entry 15.07.2020 22:51:03:298 -- GroupActivity.OnStop 15.07.2020 22:51:05:271 -- EntryActivity.OnPause 15.07.2020 22:51:05:271 -- Timeout start 15.07.2020 22:51:05:286 -- EntryEditActivity.OnCreate 15.07.2020 22:51:05:287 -- EntryEditActivity:apptask= 15.07.2020 22:51:05:288 -- Loaded task keepass2android.NullTask 15.07.2020 22:51:05:321 -- EntryEditActivity.OnStart 15.07.2020 22:51:05:322 -- EntryEditActivity.OnResume 15.07.2020 22:51:05:322 -- DatabaseIsUnlocked=True 15.07.2020 22:51:05:322 -- Timeout cancel 15.07.2020 22:51:05:354 -- Received intent to provide access to entry 15.07.2020 22:51:05:786 -- EntryActivity.OnStop 15.07.2020 22:51:10:643 -- status message: Initializing... 15.07.2020 22:51:10:644 -- status submessage: 15.07.2020 22:51:10:671 -- status message: Speichere Datenbank… 15.07.2020 22:51:10:674 -- status submessage: Prüfe ob Zieldatei geändert wurde… 15.07.2020 22:51:16:626 -- EntryEditActivity.OnPause 15.07.2020 22:51:16:627 -- Timeout start 15.07.2020 22:51:16:649 -- LockingActivity: OnActivityResult 15.07.2020 22:51:16:649 -- TryGetFromActivityResult: no data 15.07.2020 22:51:16:655 -- EntryActivity.OnStart 15.07.2020 22:51:16:657 -- EntryActivity.OnResume 15.07.2020 22:51:16:657 -- DatabaseIsUnlocked=True 15.07.2020 22:51:16:658 -- Timeout cancel 15.07.2020 22:51:16:693 -- EntryActivity.OnPause 15.07.2020 22:51:16:694 -- Timeout start 15.07.2020 22:51:16:699 -- EntryActivity.OnStop 15.07.2020 22:51:16:705 -- EntryActivity.OnDestroyFalse 15.07.2020 22:51:16:771 -- EntryActivity.OnCreate 15.07.2020 22:51:16:771 -- EntryActivity:apptask= 15.07.2020 22:51:16:793 -- Loaded task keepass2android.NullTask 15.07.2020 22:51:16:806 -- EntryActivity.OnStart 15.07.2020 22:51:16:807 -- EntryActivity.OnResume 15.07.2020 22:51:16:807 -- DatabaseIsUnlocked=True 15.07.2020 22:51:16:807 -- Timeout cancel 15.07.2020 22:51:16:854 -- Received intent to provide access to entry 15.07.2020 22:51:17:113 -- EntryEditActivity.OnStop 15.07.2020 22:51:17:115 -- EntryEditActivity.OnDestroyTrue 15.07.2020 22:51:17:381 -- EntryActivity.OnPause 15.07.2020 22:51:17:382 -- Timeout start 15.07.2020 22:51:17:395 -- LockingActivity: OnActivityResult 15.07.2020 22:51:17:395 -- TryGetFromActivityResult: no data 15.07.2020 22:51:17:398 -- GroupActivity.OnStart 15.07.2020 22:51:17:400 -- GroupActivity.OnResume 15.07.2020 22:51:17:400 -- DatabaseIsUnlocked=True 15.07.2020 22:51:17:400 -- Timeout cancel 15.07.2020 22:51:17:413 -- File flags: 326 15.07.2020 22:51:17:739 -- GroupActivity.OnPause 15.07.2020 22:51:17:740 -- Timeout start 15.07.2020 22:51:17:755 -- LockingActivity: OnActivityResult 15.07.2020 22:51:17:756 -- AppTask keepass2android.NullTask in OnActivityResult 15.07.2020 22:51:17:764 -- GroupActivity.OnStart 15.07.2020 22:51:17:765 -- GroupActivity.OnResume 15.07.2020 22:51:17:765 -- DatabaseIsUnlocked=True 15.07.2020 22:51:17:766 -- Timeout cancel 15.07.2020 22:51:17:779 -- File flags: 326 15.07.2020 22:51:18:262 -- GroupActivity.OnStop 15.07.2020 22:51:18:265 -- GroupActivity.OnDestroyTrue 15.07.2020 22:51:18:318 -- EntryActivity.OnStop 15.07.2020 22:51:18:321 -- EntryActivity.OnDestroyTrue 15.07.2020 22:51:24:862 -- GroupActivity.OnPause 15.07.2020 22:51:24:863 -- Timeout start 15.07.2020 22:51:24:880 -- DatabaseSettingsActivity.OnCreate 15.07.2020 22:51:24:881 -- DatabaseSettingsActivity:apptask= 15.07.2020 22:51:24:913 -- DatabaseSettingsActivity.OnStart 15.07.2020 22:51:24:914 -- DatabaseSettingsActivity.OnResume 15.07.2020 22:51:24:914 -- DatabaseIsUnlocked=True 15.07.2020 22:51:24:914 -- Timeout cancel 15.07.2020 22:51:25:347 -- GroupActivity.OnStop

**Comment by PhilippC** [comment]
does this happen with 1.08b-r0 as well? https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by billie80** [comment]
Will test with this version later!
One thing I forgot two mention. It works for one change but all subsequent changes fail. For other reasons I did a factory reset on my device and  again it worked for one change and afterwards I was unable to modify the database. Even force closed the App and cleared the cache.

**Comment by billie80** [comment]
There is no testing version for Keepass2Andoid Offline?

**Comment by billie80** [comment]
I tested with the Standard version (no offline) 1.08b-r0 from GitHub!
Had the same issue!
Basically all I did was install, open a local database file + keyfile, tried modifying it and immediately got the message.

**Comment by PhilippC** [comment]
hmm. can you please try to create a new database and see if it happens with that as well?

**Comment by billie80** [comment]
Could not reproduce with a new database! So you think the one I am using is somehow messed up?
I will try to recreate it from a plaintext export and check if this fixes things!

**Comment by billie80** [comment]
Okay, I have to revert the previous comment. I created a new database. It contained three folders. I deleted the templates and then I tried to delete the next folder but got the same message!

**Comment by billie80** [comment]
Sorry for being late here. Just wanted to report that with 1.08c-r1 I do not experience this issue anymore.
