### ISSUE TITLE
BUG: Searching for matching entries causes extra KP2A window to pop up on Chromebook

### ISSUE THREAD

**Issue by NumbGnat** [PhilippC/keepass2android#1323]
Steps to Reproduce:
1. Open an app that requires a login.
2. Use the Autofill function to fill the field using KP2A
3. Select "SELECT ANOTHER ENTRY" or click the spyglass search icon.
3. Type in your search criteria an hit the [enter] key.

Expected Behavior:  List of matching entries should be shown

Experienced Behavior: List of matching entries is displayed AND an additional KP2A window is created and displayed over the top.

**Comment by PhilippC** [comment]
I cannot reproduce this. what does this additional window look like?

**Comment by PhilippC** [comment]
BTW can you maybe also try to upgrade to 1.08b-r0? https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by NumbGnat** [comment]
I encountered this bug when setting up a new Chromebook for my parents. Unfortunately, I have already delivered it to them, so I can't test any further.

The window was just a copy of whatever was shown prior to hitting [Enter] on the search.

I tried doing a recording of the session, but the KP2A window doesn't allow recordings of course... 

The search result was displaying, but it the results were in another window, that was at a lower Z-order. 

If you can't reproduce it, then it may have been fixed.
