### ISSUE TITLE
Fingerprint unlock not working in 1.08

### ISSUE THREAD

**Issue by yetanothernickname** [PhilippC/keepass2android#1324]
After updating to latest version, app can't detect the fingerprint sensor.
Redmi Note 3 Pro (Android 6.0.1)
No errors in log

**Comment by tigretondigi** [comment]
I have the same issue.
Xiaomi A1 Android 9.

**Comment by edarsaut** [comment]
Same issue here.
Redmi Note 3 pro.
Toast notification says fingerprint sensor is not present in device

**Comment by yetanothernickname** [comment]
Fixed in 1.08b-r1
