### ISSUE TITLE
Show and sort via URL, not by usernames

### ISSUE THREAD

**Issue by FoHlined** [PhilippC/keepass2android#1325]
I don't need a sort of usernames. I want to sort websites where i have accounts for. In this moment i need to open every entry to find the right entry, because usernames are my emailadress, it's not helpful. 
I need a change of vision/show from usernames to URL. I'm using kdbx files.

Thanks!

**Comment by PhilippC** [comment]
You mean in the search results? It should always show the title of the entry and entries with different URLs should have different titles. The idea of showing username is to allow to distinguish between entries for users of the same website.

**Comment by FoHlined** [comment]
Not Search results. When i open the app and click on the folder "Internet", i only see all the entries with the same email adress. On KeePass 2 on my Desktop PC i sort for Websites, not for accountnames, because all my account names are the same (my email adress). So in your app i need to check every entry to find the right website to get my password. So it would be very usefull, that i can change the entry display from "username" to "URL".

**Comment by PhilippC** [comment]
you mean the smaller text below the title? Can you post a screenshot if I still don't get it?

**Comment by WebworkrNet** [comment]
I think it is not a good idea to choose the same username everywhere. Like the password, this should consist of a random string of characters. If I remember correctly, this is also a recommendation of the Chaos Computer Club (CCC).

Admittedly, not every service allows this.

**Comment by WebworkrNet** [comment]
Why don't you just assign an appropriate and unique title / name for each record, as Philipp wrote?
