### ISSUE TITLE
Using "{PASSWORD}" in Notes-Field translates to password in plain text

### ISSUE THREAD

**Issue by CSchlipp** [PhilippC/keepass2android#1326]
When using "{PASSWORD}" in the notes-field of an entry, it always ans immediately shows the password stored in this entry in plain text.

It should better be triggered by the "reveal" button if sensitive data is actually displayed or escaped.

Seen in V1. 08b-r0.

Happy to provide additional data is required!

**Comment by PhilippC** [comment]
the notes field is by definition not sensitive. Please use custom fields for this and mark them protected.
