### ISSUE TITLE
References are typed as literal strings rather than referencing the original entry

### ISSUE THREAD

**Issue by tunbridgep** [PhilippC/keepass2android#1327]
I found this today while trying to log into a website on my phone.

repro:
1. Make an entry that [references](https://keepass.info/help/base/fieldrefs.html) another entry (such as a username reference)
2. Use the Keepass2Android Keyboard to auto-type into a website or another relevant login field
3. Watch it fail to login because it typed out the literal reference text, rather than the username/password/etc from the original field.

Expected Behaviour:
It uses the login details from the original entry that the reference points to.

**Comment by fakuivan** [comment]
References seem to resolve for fields once you open the entry, but this doesn't cover auto fill titles or entry names. This however works just fine on the desktop app.

**Comment by LuisAPI** [comment]
+1 on this. This would be most helpful since many web services have multiple domains (for example: live, office and microsoft365 -.com domains for MS 365).
