### ISSUE TITLE
Does KP2A remember db location and master password after phone restart?

### ISSUE THREAD

**Issue by gio-vanni** [PhilippC/keepass2android#1329]
I'm new to KP2A, but use the desktop version. My database is in Dropbox. It seems each time after database is closed or the phone restarts, I need to do the same steps again in order to Open the database: Select Dropbox, enter Dropbox credentials in the browser, navigate to the database file location, enter master password, etc. Is there an easier way? I don't use the dedicated Dropbox/Apps/Keepass2Android/ folder method yet. Would it make a difference if I do? Do I need to install Dropbox app?

**Comment by PhilippC** [comment]
this sounds a lot like your phone is resetting the app settings on restart. Maybe it's low on memory?

**Comment by gio-vanni** [comment]
Actually I have disabled "remember database" in the security settings, while playing around after installing the app. Now I enabled "remember database" and everything works as expected. However, I did not know which option needs to change, so tried to find how to reset all settings to defaults. It seems there is no such option, so I ended up uninstalling and reinstalling the app. However, after reinstall the settings remain the same. Is there way to revert all settings to default as I don't remember what I've changed?

**Comment by Zoron-germany** [comment]
Sorry to jump in here, but I have the problem that I also have the feature enabled, but cannot understand where KP2A is pulling the DB from - I had deleted it already. It references the location with content://android.externalstorage, which means the URI to my SD-card, but the file isn´t there...??

Is it saving the DB in its own cache? And if so, can I clear that cache?
Thanks! Peter

**Comment by PhilippC** [comment]
@gio-vanni I think you should be able to clear cache & data in the OS's app settings dialog. That should clear all settings (and all data, so make sure it's all synchronized!)
@Zoron-germany yes, there is an internal cache copy. If you go to "Change database", click the three vertical dots next to the filename and select Delete, it will be removed.

**Comment by Zoron-germany** [comment]
thanks man!

**Comment by Zoron-germany** [comment]
PS: just for anyone reading this thread at a later point: in order to see the dots @PhilippC  is referencing, you need to activate "show local backups" at the bottom of the screen.
