### ISSUE TITLE
Database force-closes on unexpected TOTP Settings field

### ISSUE THREAD

**Issue by Wuestengecko** [PhilippC/keepass2android#133]
When opening an entry with unexpected / unsupported TOTP Settings, the App closes the database without showing an error message. The entry in question is Steam, which uses the following TOTP settings string:

    30;S;https://store.steampowered.com

Notice the S in the field for the number of digits (normally 6 or 8); this option is added by the KeeTrayTOTP fork to support Steam's custom algorithm.

Supporting the algorithm directly is not high priority (at least for me), as this phone also acts as Steam Mobile Authenticator, but this issue makes it impossible to re-login to the Steam App in case it gets logged out.

**Comment by PhilippC** [comment]
please upgrade to the beta channel (https://play.google.com/apps/testing/keepass2android.keepass2android) to get a version which has this fixed already (see #34)
