### ISSUE TITLE
Keepass2Android 2.x Version 1.08-r1 - unable to move keys into folders

### ISSUE THREAD

**Issue by oceangirl613** [PhilippC/keepass2android#1331]
Keepass2Android 2.x Version 1.08-r1.

I have created folders (ie recipe sites) and am unable to move the keys (ie Martha Stewart ) into the folders.

I cannot find this option.

Help!

**Comment by PhilippC** [comment]
long press an item - select the Cut (scissors icon) menu option, go to the target folder and select the "Insert here" button.
