### ISSUE TITLE
Database not found on cloud through Webdav (Koofr) 

### ISSUE THREAD

**Issue by olsos** [PhilippC/keepass2android#1332]
Hello,

First of all, I'm happy to be part of a beta testing of a really helpful project. 

I'm trying to keep my keys database on a cloud (Koofr) and sync it with K2A with WebDAV.
The error is always the same "file not found" even when I'm misspelling the WebDAV password.
I correctly chose the https (WebDAV) option in K2A. 
I tried to access the WebDAV with a android file explorer and it find the file without any issue.
Any idea?

Thanks

**Comment by PhilippC** [comment]
can you please try with the 1.08b-r0 from https://play.google.com/apps/testing/keepass2android.keepass2android? I cannot promise it helps, but at least I did change a few things for WebDav there.

**Comment by olsos** [comment]
Thanks for your answer.
I already installed the 1.08b-r0 version since I already had the issue with the previous version.
Do you think the issue is with the cloud or just with the Webdav?
If you need any manipulation from me, don't hesitate to ask. Does the app generates logs you'd be interested in?

**Comment by PhilippC** [comment]
can you try to enter the path without the filename and see if that changes the behavior? It should show a file browser then.

**Comment by olsos** [comment]
I tried the following things without success :  
- if I put the URL of the folder containing the file and the correct login/pwd, I get "Did not find initial path" or "Impossible to connect to file provider null" 
 - if I put the URL or the folder containing the file and an incorrect login/pwd, I get "error 401 Unauthorized "
Results are the same if I point to the root folder.

**Comment by PhilippC** [comment]
hard to say what's going on. Do you have any other WebDav server you can test with?

**Comment by olsos** [comment]
I'll try that soon.

**Comment by olsos** [comment]
Hello again, 
After retrying, I managed to connect to my key file.
I have no idea what I did differently, but the main point is that it works perfectly.
I must have made a typo in one of my inputs.

Sorry for wasting some of your time and thanks for your answers and your application.
