### ISSUE TITLE
Keepass2android tries to open .flo files by default

### ISSUE THREAD

**Issue by terrytw** [PhilippC/keepass2android#1336]
First of all, thank you for the hard work to make this project so awesome!

I have recently started using automate [https://play.google.com/store/apps/details?id=com.llamalab.automate](url)
This app can backup its automated scripts into .flo files.

When I tap on these flo files, Keepass2android pops up trying to open it. 
I think it is because of keepass2android is associating itself with it.

**Comment by PhilippC** [comment]
can you please try if this is fixed in 1.08b-r0 (https://play.google.com/apps/testing/keepass2android.keepass2android)?

**Comment by terrytw** [comment]
Unfortunately it does not solve the issue. 
In fact I got 1.08b-r0 update a couple of days ago, and saw that you mentioned "change file associations of the app to avoid some unnecessary association" in the latest changelog, and tested, just to found that the .flo problem still exists, before opening this issue.

**Comment by PhilippC** [comment]
which app do you use to tap the .flo files?

**Comment by terrytw** [comment]
It is total commander. 
Now that you mentioned it, I tried to open it in the default "file" app, an option popped up prompting me to choose with which app I want to open this file, and automate and keepass2android are the two options available.
