### ISSUE TITLE
interface of keepass2android 1.08b-r0 can not use l10n language correctly

### ISSUE THREAD

**Issue by flowercow** [PhilippC/keepass2android#1338]
Now the interface laguage of 1.08b-r0 is English, how make it to use native language instead of English?
Waiting for official L10n version?

**Comment by Small-Ku** [comment]
Currently, Keepass2Android has full/partial translation of languages below:
```
Arabic
Azerbaijani
Basque
Bulgarian
Catalan
Chinese Simplified
Chinese Traditional
Croatian
Czech
Danish
Dutch
Finnish
French
Galician
German
Greek
Hebrew
Hungarian
Indonesian
Italian
Japanese
Korean
Norwegian Bokmal
Norwegian Nynorsk
Persian
Polish
Portuguese
Portuguese, Brazilian
Romanian
Russian
Serbian (Cyrillic)
Slovak
Slovenian
Spanish
Swedish
Turkish
Ukrainian
Vietnamese
```
While your native language is not included in this list or not fully translated, your interface would use English instead.
Please consider contribution to [the Crowdin project](http://crowdin.net/project/keepass2android) for new language.

**Comment by flowercow** [comment]
> Currently, Keepass2Android has full/partial translation of languages below:
> 
> ```
> Arabic
> Azerbaijani
> Basque
> Bulgarian
> Catalan
> Chinese Simplified
> Chinese Traditional
> Croatian
> Czech
> Danish
> Dutch
> Finnish
> French
> Galician
> German
> Greek
> Hebrew
> Hungarian
> Indonesian
> Italian
> Japanese
> Korean
> Norwegian Bokmal
> Norwegian Nynorsk
> Persian
> Polish
> Portuguese
> Portuguese, Brazilian
> Romanian
> Russian
> Serbian (Cyrillic)
> Slovak
> Slovenian
> Spanish
> Swedish
> Turkish
> Ukrainian
> Vietnamese
> ```
> 
> While your native language is not included in this list or not fully translated, your interface would use English instead.
> Please consider contribution to [the Crowdin project](http://crowdin.net/project/keepass2android) for new language.
is that mean if the translation is not go to 100%, even 90%, the interface would still use English ?

**Comment by Small-Ku** [comment]
> > Currently, Keepass2Android has full/partial translation of languages below:
> > ```
> > Arabic
> > Azerbaijani
> > Basque
> > Bulgarian
> > Catalan
> > Chinese Simplified
> > Chinese Traditional
> > Croatian
> > Czech
> > Danish
> > Dutch
> > Finnish
> > French
> > Galician
> > German
> > Greek
> > Hebrew
> > Hungarian
> > Indonesian
> > Italian
> > Japanese
> > Korean
> > Norwegian Bokmal
> > Norwegian Nynorsk
> > Persian
> > Polish
> > Portuguese
> > Portuguese, Brazilian
> > Romanian
> > Russian
> > Serbian (Cyrillic)
> > Slovak
> > Slovenian
> > Spanish
> > Swedish
> > Turkish
> > Ukrainian
> > Vietnamese
> > ```
> > 
> > 
> > While your native language is not included in this list or not fully translated, your interface would use English instead.
> > Please consider contribution to [the Crowdin project](http://crowdin.net/project/keepass2android) for new language.
> > is that mean if the translation is not go to 100%, even 90%, the interface would still use English ?

Sorry for my words. No, but the words/sentences that not translated would be displayed as English.

**Comment by flowercow** [comment]
Is the l10n files have been released in the current version 1.08-r0? 
i install it from google play, but the interface is still in english.

**Comment by Small-Ku** [comment]
Which language are desired for you? Most of the languages are included in 1.08-r0.
You can find them [here](https://github.com/PhilippC/keepass2android/tree/02073c01b643eba8cca9fa1008bc850dc446623c/src/keepass2android/Resources). They are folders named as value-{language code}.

**Comment by flowercow** [comment]
I want to use Chinese Simplified.
If i change android system language to Chinese Traditional, the language that interface used changes also.  if I change to Chinese Simplified, the interface use English, not zh_CN.
it is weried.

EMUI based on android 10 on Mate 10.

**Comment by PhilippC** [comment]
I think this is an issue with the crodwin integration. I'll try to tackle this in the next build.

**Comment by flowercow** [comment]
> I think this is an issue with the crodwin integration. I'll try to tackle this in the next build.

when will the next build released?

**Comment by flowercow** [comment]
> google paly 1.08b-r1,Chinese simplified still not repaired 😭
> Hope it can be fixed soon, thanks

 i have upgrade to r1 version, this bug has not fixed yet.
