### ISSUE TITLE
[Feature Request] Move "TOTP" field to earlier in the list on keyboard.

### ISSUE THREAD

**Issue by Corey-Keller** [PhilippC/keepass2android#1341]
Currently the "TOTP" entry (the one containing the actual code i.e. 476232 is placed alphabetically in the single line keyboard. This can result in having to tap the ">" button SEVERAL times if an entry has many other string fields (for example I have one for each security question (field name) and answer (field value)). Since the TOTP field is generated (and not an actual string field Name/Value pair in the actual entry itself) it should be possible to place it earlier in the list (I suggest next to "Password" and before "URL") instead of mixed in with the advanced fields.

**Comment by XtraLarge** [comment]
Perhaps an other idea were a method to disable some fields from the one-row-keyboard. Like a special Field with a list for disabled fields ;)

**Comment by Corey-Keller** [comment]
> 
> 
> Perhaps an other idea were a method to disable or priority some fields from the one-row-keyboard. Like a special Field with a list for it :)

@XtraLarge that is also a good separate idea (that you should make a separate request for. I'd thumbs up it), but it still should be moved earlier by default, as one problem is that every TOTP site has one-time recovery codes (which I have in the DB as "One Time Backup Code ##" and do want available in case they are needed) and thus have to scroll past 5+ of them, and then the "TOTP Seed" and "TOTP Settings" fields as well. @PhilippC I feel like having it next to the username and password fields would be a significant quality of life improvement for the app.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
I do never need the otp:key= field button before totp button in mini keyboards
