### ISSUE TITLE
Vault does not auto-lock after the timeout selected in settings

### ISSUE THREAD

**Issue by NeatNit** [PhilippC/keepass2android#1346]
Title.

I can kind of understand that this might happen because of battery optimizations pausing the app in the background, but when I tap the notification to open the app, the vault remains open and I can see passwords. I would expect, at worst, that the app would lock the vault immediately when it wakes up.

OnePlus 6, OxygenOS 10.3.4, Android 10, KP2A 1.07b-r0.

Let me know if you need any more info.

**Comment by PhilippC** [comment]
does locking work at all? E.g. can you enable to lock when screen is off and turn screen off and on? Which settings exactly did you set to which values?

**Comment by lefth** [comment]
I am also experiencing this problem. "Lock when screen is off" works, but "App settings -> Security -> App timeout" does not. Following [these instructions](https://dontkillmyapp.com/) to prevent apps being killed in the background is effective and does make it work, but I had to kill and reopen the app before it took effect.

It seems like locking is accomplished by an alarm, but it would be more secure to use an alarm to clear the clipboard but using more traditional programming to lock the app's main screen and not let the keyboard access the database-- I mean, check the timeout when the screen is resumed or when the keyboard tries to access the database. Do you need a file log that shows the problem?
