### ISSUE TITLE
Bad Font

### ISSUE THREAD

**Issue by markdmac** [PhilippC/keepass2android#1348]
Please change the font that shows passwords to make it clearer between a zero and upper case letter O.

**Comment by PhilippC** [comment]
please post a screenshot to make clear which screen/field you mean and how it looks like.

**Comment by BobVooInformed** [comment]
For password management, I also see the importance of have fonts that is clear and character is clearly differentiable.  
[Slashed Zero](https://seniortechgroup.com/sb/font-with-slashed-zero/#:~:text=A%20solution%20is%20to%20simply,and%20Share%20Tech%20Mono%20fonts.)

**Comment by PhilippC** [comment]
without having a screenshot, I am closing this.
