### ISSUE TITLE
Error: file signature invalid

### ISSUE THREAD

**Issue by bethany85** [PhilippC/keepass2android#1350]
Hi, I'm having an issue logging into KeePass. When I attempt to log in I get the following error code:
An error occurred: the file signature is invalid. Either the file signature isn't a KeePass database file at all or it is corrupted.

**Comment by PhilippC** [comment]
sounds like your database file got corrupted. On which storage is it located? Can you try to open the local backup? (Change database - Enable "Show local backups)?

**Comment by bethany85** [comment]
Thank you! I'd tried changing the database before, without success. But today it worked! Thank you very much.
