### ISSUE TITLE
SSL session reuse on vsftpd server

### ISSUE THREAD

**Issue by drwulsen** [PhilippC/keepass2android#1356]
Hi Philipp,

when hosting the database file on a vsftpd server, it is apparently required to disable the SSL session reuse requirement. (*require_ssl_session_reuse=NO* in vsftpd.conf).
Otherwise it would always fail with **"The file header is corrupted. Less data than expected could be read from the file."**

[kp2a.log](https://github.com/PhilippC/keepass2android/files/5034972/kp2a.log)
[server.log](https://github.com/PhilippC/keepass2android/files/5034973/server.log)

Attached is the server log (which is the exact same in working and failing condition, except for some random
**522 SSL connection failed; session reuse required** messages.

Disabling session reuse made it work, however, it would be nice to have - I'm pretty on the edge of my ftp-foo here, so I can definitely test, but don't have any other clue to offer you.

Thank you for this great app, it works like a charm!

**Comment by PhilippC** [comment]
Is this on 1.07b or 1.08b? If 1.07b, could you please test again with https://play.google.com/apps/testing/keepass2android.keepass2android where I have upgraded the FTP library (I don't know if this has an effect, but it could)

**Comment by drwulsen** [comment]
Hi Philipp,
I've tested with 1.08b-r1; the issue remains the same. I have to disable SSL_SESSION_REUSE on vsftpd to make it work.

**Comment by drwulsen** [comment]
.... I guess, I just found the relevant issue in FluentFTP: [https://github.com/robinrodricks/FluentFTP/issues/347](url)
and it seems that the issue is not on your side.
Whatcha think?

**Comment by PhilippC** [comment]
yes, that seems to be the reason. Looks like we have to close this here as well.
