### ISSUE TITLE
I have a problem with automatically fill out from keepass in a app 

### ISSUE THREAD

**Issue by lynyrd2** [PhilippC/keepass2android#1358]
Hello, I hope that somebody can help me:
Since a longer time I have the problem that any password will not fill out automatically from KeepassAndroid in the corresponding app. After I klick "fill out with Keepass" I get only an empty window from Keepass and have to klick on the button "choose an other entry" and there I can see all my entries in the passwort database.
The automatic function is gone out of use with this problem.

I tried already to delete all entries and all rests of KeepassAndroid and installed it again but the problem is again and again
the same.

Many thanks in advance for any help.

**Comment by PhilippC** [comment]
does it show which app it is looking for? in the title bar there should be something like "No search results for XYZ" - what's XYZ for you?

**Comment by lynyrd2** [comment]
Sorry fot the delay!

No, it shows NO APP .....only a blank window in KeypassAndroid with on top "searchresults ("...  "
and on the bottom "Choose another entry" and "Create entry for URL".

KeypassAndroid cannot find my database...
I MUST klick "Choose another entry" and then it shows all directories in my database! Strange...

**Comment by PhilippC** [comment]
no the delay is mine :-) 

>  "searchresults ("... "
what's that "..."?

**Comment by lynyrd2** [comment]
Hi Philipp,
if I click in an app with a login you have to click "fill out with keepass". Then Keepass appears but it's a window from Keepass 
with NO entries from my database (no directories, simply a blank window inside Keepass). As I said I can only click in that window on the bottom "choose an other entry" and then I can see all my directories in the Keepass database.
Then I must copy the password and have to switch manually to the app with the login-data and must paste it inside.
"searchresults" appears on top inside from Keepass but the window shows no dirs from my database. I think that Keepass cannot find the dir to my database.

Hope you understand the declaration.

**Comment by PhilippC** [comment]
in order to troubleshoot this I would like to know what the title bar of that window looks like. Earlier you mentioned it says "Search results (...)" and I would like to know what exactly ... means. depending on that I might be able to help.

**Comment by lynyrd2** [comment]
A screenshot from Keepass in the corresponding window is not possible...I think Keepass forbid it...
O.k. I will again try to declare that window after I try to let fill out the password from Keepass automatically  in an app:

On the top with GREEN background appears "Searchresults ("... " (incl. ("... )
Below that with WHITE background (normally there are the dirs!) appears "No searchresults"
On the bottom in BLUE color appears "Choose another entry" AND "Create an entry for URL"

Thats it! And I have to klick "Choose another entry" and then my dirs are visible!
Normally Keepass show me directly the dirs if it don't know with PW it should fill out
or it fills out automatically the PW in the app which needs a PW (in this case Keepass stays in background
and is not visible)

I hope you can understand what I will say.

**Comment by PhilippC** [comment]
I'm closing this as autofill has been reworked since the issue has been created. Please reopen if it still exists in recent versions.
