### ISSUE TITLE
Keepass specific folder in OneDrive Business

### ISSUE THREAD

**Issue by nerd2400** [PhilippC/keepass2android#1359]
I'd like KP2A to access only the application specific folder in OneDrive for Business. This was also addressed before in issue #1053 ,
but not really answered (added to 1.08 milestone, but for me still not working in Kp2A 1.08: Still getting "Cannot get path item without share").

Version used: 1.08b-r1

Steps to reproduce:
- create new database
- change location
- choose oneDrive
- choose 3rd option (KP2A app folder)

For my personal OneDrive, it worked like a charm (folder and db created).

For my company's OneDrive for Business, it failed with above mentioned toast
(after choosing account and granting Keepass2Android the "save as" screen did not show any folder (like it had for my personal onedrive)).

Is this intended behaviour (because this option generally does not work at all for OneDrive Business),
or should it work and is either a misconfiguration of my company or I am doing anything wrong here?

(I don't like to open the complete OneDrive Business for the app ...)

Thanks for a feedback and guidance on how to use that option with OneDrive Business.

**Comment by pjaeger16** [comment]
Same Question from me. Giving Full permission is Not an option in Business Environment

**Comment by wederer** [comment]
Can second this issue. I also get the "Cannot get path item without share" error.

**Comment by PhilippC** [comment]
this is not possible: 

> Note, Business OneDrive accounts do not currently support the Files.ReadWrite.AppFolder permission.

from https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/special-folders-appfolder?view=odsp-graph-online
