### ISSUE TITLE
Keepass2Android + Challenge Response + ykDroid only works one time

### ISSUE THREAD

**Issue by Londran** [PhilippC/keepass2android#1360]
When using the YubiKey5C, PW + CHallenge Response can be used only once.

Possible reason:
In the auxilliary file, the lase </data> tag is duplicated, thus it is not reusable.

Steps to reproduce:
Move *kdbx and *xml to device
Open Database with credentials and yubikey via "Password + Challenge Response"
Close Database
Retry to open

**Comment by PhilippC** [comment]
this should be fixed in 1.08 (https://play.google.com/apps/testing/keepass2android.keepass2android) can you please test?

**Comment by Londran** [comment]
Works properly now. Thanks.
