### ISSUE TITLE
QuickUnlock no longer automatically pops up keyboard

### ISSUE THREAD

**Issue by shortattentionspan** [PhilippC/keepass2android#1362]
Using 1.08b-r0, when opening the app after it has either automatically or manually been locked, the text entry field has not been chosen, so no keyboard pops up until one manually chooses the text field. Previously, it was a minor feature, but still nice to have.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
+1
i have the same problem.
