### ISSUE TITLE
Add ability to unlock DB with iris scanner

### ISSUE THREAD

**Issue by ShmuelLevine** [PhilippC/keepass2android#1365]
Currently, the only biometrics supported for unlocking the DB is the fingerprint reader.  I would like to have the ability to use the iris scanning available on my Samsung S9+.  

Firstly, is there a technical reason for this feature to not be available?  

If not, I am happy to work on it, if someone can give me a bit of a hand in navigating the codebase and figuring out how/where to make the necessary changes.

Thanks

**Comment by solarelf** [comment]
I vote this up! Samsung Galaxy Tab S4. Please also make sure it work with DeX (Iris scanner is not supported in DeX officially, but still can be accessed via API and there are apps actually using it, like Samsung Pass etc.).

**Comment by solarelf** [comment]
> Currently, the only biometrics supported for unlocking the DB is the fingerprint reader. I would like to have the ability to use the iris scanning available on my Samsung S9+.
> 
> Firstly, is there a technical reason for this feature to not be available?
> 
> If not, I am happy to work on it, if someone can give me a bit of a hand in navigating the codebase and figuring out how/where to make the necessary changes.
> 
> Thanks

Regarding a technical limitation... Android 10 now has unified BiometricsAPI so maybe...just maybe, it will change the general picture of why it is still not delivered yet...

**Comment by PhilippC** [comment]
the latest version (1.08b-r1) has support for Unified Biometric Auth dialog. However, I think, Google does not support Iris as it's not considered safe enough. So from my side I cannot do anything about this. I need Google to support the biometric method so I can use the secure storage.
