### ISSUE TITLE
Wo ist das entsperren per Fingerabdruck geblieben?

### ISSUE THREAD

**Issue by xandyx12** [PhilippC/keepass2android#1366]
War eine sinnvolle Sache und wäre schade wenn es fehlt das dieses die Nutzung attraktiver macht.

**Comment by PhilippC** [comment]
Einstellungen - Datenbank - Biometrisches Entperren

**Comment by christianhaessler** [comment]
Kann nach dem Update auf Version '1.08b-r1' auch auf meinem Device nicht mehr genutzt werden.

Device: Samsung Galaxy A8 (2018)
Modell: SM-A530F
Android 9

Ist vermutlich ein "duplicate" von: https://github.com/PhilippC/keepass2android/issues/1377

**Comment by JumpOverWires** [comment]
Bei meinem Smartphone (Redmi Note 7, crDroid 6.8/Android 10), lässt sich das Entsperren über den Fingerprint-Sensor noch aktivieren (Keepass 1.08b). Wenn ich aber anschließend die geöffnete Datenbank wieder schließen will, werde ich jedes Mal aufgefordert, den Fingerprint-Sensor zu berühren und muss das dann jedes Mal abbrechen, um am Ende die Datenbank schließen zu können. Das ist reichlich nervig.

**Comment by PhilippC** [comment]
closing this as Fingerprint unlock is still there.
@JumpOverWires I think your point is a duplicate of https://github.com/PhilippC/keepass2android/issues/1373

**Comment by christianhaessler** [comment]
Schade, dass dies nicht mehr funktioniert. War ein echtes Highlight. Sollte Interesse daran bestehen mehr darüber zu erfahren warum es nicht mehr geht bin ich wie schon oft geschrieben gerne bereit irgendwelche Logs oder ähnliches zu liefern.
