### ISSUE TITLE
Could not save to source file: Not a whole file.

### ISSUE THREAD

**Issue by SdoggaMan** [PhilippC/keepass2android#1371]
Heyo!

As above, I'm having a save issue with a KeePass 2 database stored in OneDrive, accessed from several Windows machines and an Android phone running A 10. the database doesn't sync changes made to the database on the phone or other devices with this error, but will sometimes say "Database synchronized successfully!" instead of "Not a whole file" in the android pop-up bubble. It doesn't sync, however. 

Let me know if there's more I should give you to help suss things out!

**Comment by PhilippC** [comment]
which version are you running? Please make sure it's 1.08b-r1?

**Comment by SdoggaMan** [comment]
> 
> 
> which version are you running? Please make sure it's 1.08b-r1?

Correct, it is. I did the update a little while ago (wasn't pushed out by Play but noticed it myself.) 1.08b-r1, ver code 160.

**Comment by PhilippC** [comment]
what's the size of the file?

**Comment by SdoggaMan** [comment]
> 
> 
> what's the size of the file?

Looking in OneDrive on the desktop, the database is 37 KB.

**Comment by PhilippC** [comment]
I searched around regarding this and found https://github.com/PhilippC/keepass2android/issues/763. Are you using the OneDrive app instead of the built-in OneDrive support? Then that would explain it.

**Comment by SdoggaMan** [comment]
> 
> 
> I searched around regarding this and found #763. Are you using the OneDrive app instead of the built-in OneDrive support? Then that would explain it.

Yep, using the OneDrive app. I didn't think there would be any other way to access files in my OneDrive apart from it.

I've gone through and re-opened it, this time from the internal menu in the KP2A app (which didn't show up the first time). It synchronised a test folder right away, without needing even to hit save. I suspect the reason why was that when I first set this up, I grabbed both KP2A and OneDrive and logged into both and must have opened the KPDB from OneDrive, selecting the relevant app to open with - rather than using the app to open the file. 

That, or it's properly authenticated to edit my OneDrive now that i've logged in through the app rather than just through OneDrive itself. Confusing yet it does make sense!

Thank you for your help - I hope i was able to provide some info as well. I'll see how I go from here and leave a good review where I can if all continues to go well!

**Comment by Gerardsc** [comment]
I have the same issue (Not a whole file error on my android phone)
When i check the Google play store there's nothing to update for keepass2android 

ANybody any idea's how could fix this on my phone and the phone's of my familie (we share keepass database on multiplatform through onedrive)
Regards
Gerardsc

**Comment by mardovar** [comment]
Same issue with file in OneDrive. I use the OneDrive app.

**Comment by PhilippC** [comment]
the OneDrive app doesn't seem to provide a proper way to allow writing data back. Please make sure you are on 1.09a (https://play.google.com/apps/testing/keepass2android.keepass2android) and use the built-in OneDrive support (Open file - OneDrive).
