### ISSUE TITLE
Fingerprint reader pops up when closing a database

### ISSUE THREAD

**Issue by PBRow** [PhilippC/keepass2android#1373]
With last update, fingerprint it's enabled and now keeps asking for print whenever filler is closed.

**Comment by JumpOverWires** [comment]
Same problem with my phone (Redmi Note 7, crDroid 6.8/Android 10): When closing database in Keepass 1.08b by clicking on lock-symbol, I'm asked for touching fingerprint sensor. To prevent from re-opening, I have to choose "Cancel". After this, the "Quick unlock"-page opens and once more I'm asked to touch fingerprint-sensor. So I have to choose "Cancel" again to finally close the database. Rather annoying.
