### ISSUE TITLE
[Feature Request] Support Keyboard autofill integration.

### ISSUE THREAD

**Issue by Ich5003** [PhilippC/keepass2android#1374]
Hello,

Android 11 introduces the possibility to integrate autofill in the keyboard suggestions. (As sensitive data, without showing the password etc.)
More information here: https://developer.android.com/preview/features/ime-autofill

I would love to see this feature added, as it would hugely increase the user experience.

**Comment by Ich5003** [comment]
Is help wanted here? And if yes, will it be it be included in an earlier milestone?
I also have some android development experience and may try to implement this.

**Comment by svenschn** [comment]
@PhilippC Do you have a plan when this will be available? This is particularly useful for Chrome, see #1320.
