### ISSUE TITLE
Synchronisation not working (timeout) with Google Drive

### ISSUE THREAD

**Issue by Jazzydad** [PhilippC/keepass2android#1375]
Hi,

I've got an issue (version 1.08b-r1) the synchronisation falls in timeout while trying to save the file.

Could you please help?

David.

**Comment by PhilippC** [comment]
you mean when you make a change or when you trigger sync through the menu? Do you have special Google Drive security settings? Can you try to re-open the file through Change database - Open file - Google Drive?

**Comment by Jazzydad** [comment]
It worked back again yesterday evening. Probably linked with the Google big problems.
Thanks
