### ISSUE TITLE
Clipboard does not get cleared automatically

### ISSUE THREAD

**Issue by csteinle92** [PhilippC/keepass2android#1378]
When copying a password to the clipboard via tapping on the notification it does not get cleared from the clipboard automatically after the defined time span. This seems to happen only, when I'm not inside the Keepass2Android app. When I'm in the app at the time the clipboard should get cleared, it works as expected.

Some details about my hardware:

Device: OnePlus 6 (A6003)
Android version: 10
OxygenOS Version: 10.3.5

**Comment by PhilippC** [comment]
clipboard is inherently unsafe on Android (and behaves differently on many devices). I don't think it's possible to safely support clearing the clipboard. Please use the built-in keyboard (or Autofill) as the docs recommend.
