### ISSUE TITLE
Sync with Google drive error

### ISSUE THREAD

**Issue by obayati** [PhilippC/keepass2android#1385]
Hi there!

I'm using Keepass2Android on my Phone and KeepassXC on my linuxMint PC. so, the database opened flawlessly with no issue adding, removing and editing entries and syncing with google drive without any problem. **but**, whenever I edit the database from PC like delete, edit, adding an entry, adding folder or any changes I got error syncing and trashing message when trying to open the database again on K2A.
I've been trying to fix this for 2 days with no avail. deleting cache, reinstall the app, changing database name, database extension, rename the folder in google drive, putting the database in root folder still not working.

P.S. Error pic attached.
![IMG_0261](https://user-images.githubusercontent.com/24440985/91056834-753e0080-e5f4-11ea-9448-4b7504c7c1cd.jpg)

**Comment by PhilippC** [comment]
this is caused by fuse, but there is a config option to fix: https://github.com/astrada/google-drive-ocamlfuse/issues/494
