### ISSUE TITLE
Kann datenbank nicht öffnen

### ISSUE THREAD

**Issue by leachim2205** [PhilippC/keepass2android#1391]
Seit gestern kann KeyPass die aktuelle Datenbank nicht mehr aus der Dropbox öffnen. 
Die Signatur sei ungültig oder sowas ähnliches. Das lokale Backup ist dummerweise total veraltet. Sowas habe ich immer befürchtet... 
Gibt's irgendeine Hilfe?! 
Vielen Dank 
Michael

**Comment by Ich5003** [comment]
I'm gonna translate this into english:

Since yesterday KeePass isn't able to open my current database from Dropbox anymore.
Error is something like: invalid signature
Unfortunately the local backup is outdated, which is what I always feared.
Any help?
Thanks
Michael

**Comment by leachim2205** [comment]
Problem solved! 
Michael 

Gesendet mit meinem HTC

----- Nachricht beantworten -----
Von: "Lucas" <notifications@github.com>
An: "PhilippC/keepass2android" <keepass2android@noreply.github.com>
Cc: "leachim2205" <leachim2205@gmail.com>, "Author" <author@noreply.github.com>
Betreff: [PhilippC/keepass2android] Kann datenbank nicht öffnen (#1391)
Datum: Mi., Sep. 9, 2020 22:19

I'm gonna translate this into english:
Since yesterday KeePass isn't able to open my current database from Dropbox anymore.

Error is something like: invalid signature

Unfortunately the local backup is outdated, which is what I always feared.

Any help?

Thanks

Michael

&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
