### ISSUE TITLE
Syncing a database produces an exception

### ISSUE THREAD

**Issue by undecomposed** [PhilippC/keepass2android#1395]
I am using KeePass2Android with pCloud. I am using the Android file picker. This _used_ to work well previously. Right now, when I am trying to synchronize the database, I get a message:
`Could not save to source file. Exception of type Java.Lang.UnsupportedOperationException`

I have tried re-opening the database, but this does not seem to work.

Anything I can do to troubleshoot it? Maybe export the cache for now somehow, since I have got some edits on both sides I'd love to sync?

**Comment by PhilippC** [comment]
did you open through the pCloud app or used the built-in pCloud support (which seems to be somewhat broken recently)?

**Comment by undecomposed** [comment]
@PhilippC I used the file pickers to get a file out of pCloud. The built-in pCloud support had not worked for me for about a year, I believe. Opening the file through the file picker seemed to work fine for quite a while.

**Comment by ukysys** [comment]
@PhilippC, there is a log for this issue:
> 2021-03-02 9:20:39 AM:171 -- DatabaseSettingsActivity.OnPause
> 2021-03-02 9:20:39 AM:177 -- Timeout start
> 2021-03-02 9:20:39 AM:185 -- GroupActivity.OnStart
> 2021-03-02 9:20:39 AM:186 -- GroupActivity.OnResume
> 2021-03-02 9:20:39 AM:186 --  DatabaseIsUnlocked=True
> 2021-03-02 9:20:39 AM:186 -- Timeout cancel
> 2021-03-02 9:20:39 AM:196 -- File flags: 3526
> 2021-03-02 9:20:39 AM:667 -- DatabaseSettingsActivity.OnStop
> 2021-03-02 9:20:39 AM:669 -- DatabaseSettingsActivity.OnDestroyTrue
> 2021-03-02 9:20:45 AM:124 -- GroupActivity.OnPause
> 2021-03-02 9:20:45 AM:124 -- Timeout start
> 2021-03-02 9:20:45 AM:133 -- EntryEditActivity.OnCreate
> 2021-03-02 9:20:45 AM:134 -- EntryEditActivity:apptask=
> 2021-03-02 9:20:45 AM:136 -- Loaded task keepass2android.NullTask
> 2021-03-02 9:20:45 AM:169 -- EntryEditActivity.OnStart
> 2021-03-02 9:20:45 AM:170 -- EntryEditActivity.OnResume
> 2021-03-02 9:20:45 AM:170 --  DatabaseIsUnlocked=True
> 2021-03-02 9:20:45 AM:170 -- Timeout cancel
> 2021-03-02 9:20:45 AM:629 -- GroupActivity.OnStop
> 2021-03-02 9:20:48 AM:494 -- status message: Initializing...
> 2021-03-02 9:20:48 AM:495 -- status submessage: 
> 2021-03-02 9:20:48 AM:521 -- status message: Adding entry…
> 2021-03-02 9:20:48 AM:525 -- status message: Saving database…
> 2021-03-02 9:20:48 AM:527 -- status submessage: Checking target file for changes…
> 2021-03-02 9:20:50 AM:233 -- status submessage: Merging changes…
> 2021-03-02 9:20:50 AM:402 -- ReadXmlStreamed: 124ms
> 2021-03-02 9:20:50 AM:466 -- status submessage: 
> 2021-03-02 9:20:50 AM:600 -- Xml WriteDocument: 97ms
> 2021-03-02 9:20:50 AM:613 -- Java.Lang.UnsupportedOperationException: Exception of type 'Java.Lang.UnsupportedOperationException' was thrown.
>   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <26e465c64ed7444bac03a4b6fbfd2566>:0 
>   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <26e465c64ed7444bac03a4b6fbfd2566>:0 
>   at Android.Content.ContentResolver.OpenFileDescriptor (Android.Net.Uri uri, System.String mode) [0x0004b] in <815f7614919c4df287d2c94409477d7f>:0 
>   at keepass2android.Io.AndroidContentWriteTransaction.CommitWrite () [0x00016] in <5709dc0f70364da4a82c13028d822c27>:0 
>   at keepass2android.Database.SaveData () [0x00040] in <5709dc0f70364da4a82c13028d822c27>:0 
>   at keepass2android.SaveDb.PerformSaveWithoutCheck (keepass2android.Io.IFileStorage fileStorage, KeePassLib.Serialization.IOConnectionInfo ioc) [0x00010] in <5709dc0f70364da4a82c13028d822c27>:0 
>   at keepass2android.SaveDb+<>c__DisplayClass13_0.<Run>b__3 () [0x00017] in <5709dc0f70364da4a82c13028d822c27>:0 
>   at keepass2android.SaveDb+<>c__DisplayClass14_0.<RunInWorkerThread>b__0 () [0x00000] in <5709dc0f70364da4a82c13028d822c27>:0 
>   --- End of managed Java.Lang.UnsupportedOperationException stack trace ---
> java.lang.UnsupportedOperationException
>  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:174)
>  at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
>  at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
>  at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1818)
>  at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1633)
>  at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1580)
>  at mono.java.lang.RunnableImplementor.n_run(Native Method)
>  at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
>  at java.lang.Thread.run(Thread.java:923)
> 
> 2021-03-02 9:20:50 AM:614 -- Error in worker thread of SaveDb: Java.Lang.UnsupportedOperationException: Exception of type 'Java.Lang.UnsupportedOperationException' was thrown.
>   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <26e465c64ed7444bac03a4b6fbfd2566>:0 
>   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <26e465c64ed7444bac03a4b6fbfd2566>:0 
>   at Android.Content.ContentResolver.OpenFileDescriptor (Android.Net.Uri uri, System.String mode) [0x0004b] in <815f7614919c4df287d2c94409477d7f>:0 
>   at keepass2android.Io.AndroidContentWriteTransaction.CommitWrite () [0x00016] in <5709dc0f70364da4a82c13028d822c27>:0 
>   at keepass2android.Database.SaveData () [0x00040] in <5709dc0f70364da4a82c13028d822c27>:0 
>   at keepass2android.SaveDb.PerformSaveWithoutCheck (keepass2android.Io.IFileStorage fileStorage, KeePassLib.Serialization.IOConnectionInfo ioc) [0x00010] in <5709dc0f70364da4a82c13028d822c27>:0 
>   at keepass2android.SaveDb+<>c__DisplayClass13_0.<Run>b__3 () [0x00017] in <5709dc0f70364da4a82c13028d822c27>:0 
>   at keepass2android.SaveDb+<>c__DisplayClass14_0.<RunInWorkerThread>b__0 () [0x00000] in <5709dc0f70364da4a82c13028d822c27>:0 
>   --- End of managed Java.Lang.UnsupportedOperationException stack trace ---
> java.lang.UnsupportedOperationException
>  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:174)
>  at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
>  at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
>  at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1818)
>  at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1633)
>  at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1580)
>  at mono.java.lang.RunnableImplementor.n_run(Native Method)
>  at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
>  at java.lang.Thread.run(Thread.java:923)
> 
> 2021-03-02 9:20:50 AM:615 -- OnFinish message: Exception of type 'Java.Lang.UnsupportedOperationException' was thrown.
> 2021-03-02 9:20:54 AM:671 -- EntryEditActivity.OnPause
> 2021-03-02 9:20:54 AM:672 -- Timeout start
> 2021-03-02 9:20:54 AM:683 -- LockingActivity: OnActivityResult 
> 2021-03-02 9:20:54 AM:683 -- TryGetFromActivityResult: no data
> 2021-03-02 9:20:54 AM:687 -- GroupActivity.OnStart
> 2021-03-02 9:20:54 AM:687 -- GroupActivity.OnResume
> 2021-03-02 9:20:54 AM:688 --  DatabaseIsUnlocked=True
> 2021-03-02 9:20:54 AM:688 -- Timeout cancel
> 2021-03-02 9:20:54 AM:694 -- File flags: 3526
> 2021-03-02 9:20:55 AM:161 -- EntryEditActivity.OnStop
> 2021-03-02 9:20:55 AM:163 -- EntryEditActivity.OnDestroyTrue
> 2021-03-02 9:21:01 AM:293 -- GroupActivity.OnPause
> 2021-03-02 9:21:01 AM:293 -- Timeout start
> 2021-03-02 9:21:01 AM:304 -- DatabaseSettingsActivity.OnCreate
> 2021-03-02 9:21:01 AM:305 -- DatabaseSettingsActivity:apptask=
> 2021-03-02 9:21:01 AM:335 -- DatabaseSettingsActivity.OnStart
> 2021-03-02 9:21:01 AM:335 -- DatabaseSettingsActivity.OnResume
> 2021-03-02 9:21:01 AM:336 --  DatabaseIsUnlocked=True
> 2021-03-02 9:21:01 AM:336 -- Timeout cancel
> 2021-03-02 9:21:01 AM:785 -- GroupActivity.OnStop

For now, not the file-syncing nor the built-in pCloud syncing are working.
If you need additional info please feel free to ask for any info you need.

**Comment by PhilippC** [comment]
my interpretation is that the file you get from the file picker is not meant to write to. BTW pCloud support has been fixed.
