### ISSUE TITLE
Feature Request: Generate QR Code

### ISSUE THREAD

**Issue by rafny** [PhilippC/keepass2android#1405]
Very often I use the Android app to login on sites when on a desktop/other device.

It would be helpful to have the option to copy entries to the clipboard, but to also generate QR codes that I can scan on the other device.

Right now, I copy the password, and paste it into a QR code generator, and then scan that code. So if the app can generate the QR, that can save a step in the process.

**Comment by PhilippC** [comment]
please use https://play.google.com/store/apps/details?id=keepass2android.plugin.qr&hl=en

**Comment by Steltek** [comment]
The referenced plug-in cannot be installed on my device. Play Store says "This app is not available for any of your devices".
