### ISSUE TITLE
Unlock stays on screen "working offline" and does nothing

### ISSUE THREAD

**Issue by avinash311** [PhilippC/keepass2android#1407]
I read some messages on this, but not clear what the problem is.
Things were working fine until recently (possibly an recent update on the phone?).

I tried using both system file picker and third party app, to load .kdbx and ,key file.
I enter password, click on "Unlock" and it pops up "Working offline" and stays on the login screen.
No db is unlocked.

Does that error message mean something else? I don't really care if it is working offline, I never use the phone to modify entries in KeePass anyway. But I can no longer see the database entries.
Update: I unchecked "work on internal cache only", and then it loaded the files. So all good for now, but looks like there is scope to print a better error message here? Looks like cache really did not have anything, and so maybe that is why it was not loading the db.

About shows version 1.07b-r0

Another problem is it keeps forgetting that the unlock screen should stay on "password + key file" and remember the location of the key file (setting set to do that), but it does not, Have to select key file again each time. This is only an issue when "work on internal cache only" is checked and it does not load any db (but also does not report any error).

**Comment by PhilippC** [comment]
Can you try to disable "Work on internal cache only" checkbox on the password screen?

**Comment by avinash311** [comment]
Yes, that fix my problem. 
From the first post:
"Update: I unchecked "work on internal cache only", and then it loaded the files. So all good for now, but looks like there is scope to print a better error message here? Looks like cache really did not have anything, and so maybe that is why it was not loading the db.
"

So this is not a big issue, just UI seemed confusing, but was able to move ahead and load the DB.
