### ISSUE TITLE
File access denied 

### ISSUE THREAD

**Issue by tklemmer** [PhilippC/keepass2android#1408]
Samsung Galaxy s10. Android version: 10. Kernel: 4.14.117-18725736. Long time paying customer, use Keepass on all PCs and phones.

Suddenly when trying to open my keepass file I'm getting the following error: "The file you selected is read-only for keepass2android due to restrictions on android 4.4+ ....". I tried copying it around on the phone to both an internal location and to my SD card but then I get "Access denied error: Keepass cannot open file".

I tried uninstalling and reinstalling Keepass but no difference. Tried looking through these issues and googling the error message and again nothing.

Help!

**Comment by PhilippC** [comment]
if you are using Keepass on several devices, how do you sync? Do you use Open database - Android filebrowser? Or third party?

**Comment by tklemmer** [comment]
I do a couple of things. Typically copy the file over to phone or re-download from shared drive when passwords change. Almost always d/l to Download folder on phone. I either keep file in Download folder or create a keepass folder on internal drive or SD card. It depends on whichever one works.

**Comment by PhilippC** [comment]
Maybe it's worth considering to use a sync setup with a shared storage (e.g. Webdav server etc.)? That would simplify things a lot.

If you want to go with local files: Do you use Open database - Android filebrowser? Or third party?

**Comment by tklemmer** [comment]
Open Database Android file browser, File Manager, Samsung files. I've used them all with success until the other day. Never an issue until the other day.

**Comment by sarat13** [comment]
Having the same issue. KeePassXC 2.6.1 on computer and Keepass2Android (Beta) 1.08b-r1 on phone. I've tried putting the DB file on both internal phone storage as well as SD card. Same error

**Comment by tklemmer** [comment]
Philipp, any thoughts on what's causing this behavior?

**Comment by flesti** [comment]
Same issue, trying to open a KeePassXC database from desktop pc on android 10 tablet with 1.08b-r1 but I get this same error.

**Comment by PhilippC** [comment]
@tklemmer Maybe something changed in the way your "Samsung files" passes the files to KP2A? I wouldn't select that app, can't you simply use Android's file browsing? Or, if you want to use a third party app like "Samsung files" select "Open database" - "Third party app"?

**Comment by tklemmer** [comment]
@flesti Thank you!!! That worked like a charm. @PhilippC not sure what's going on but placing the file anywhere else returned the "The file you selected is read-only for keepass2android due to restrictions on android 4.4+ ....". error. Placing it where @flesti suggested worked. Very weird. It's almost as if Keepass is not recognizing that I have read/write access to my drives.

**Comment by flesti** [comment]
I did however used not the default android file picker, but MiXplorer from xda developers. That could have been the problem, because the moment I tried with the default one, it picked the file from whatever folder without error.
