### ISSUE TITLE
BQ Aquaris X Pro automatically closes keepass2android after a few hours

### ISSUE THREAD

**Issue by dominicdesu** [PhilippC/keepass2android#141]
Hi,
I am running Keepass2Android on a BQ Aquaris X Pro (Android 7). If I unlock the database, it keeps open a few hours in the notification bar/background but after that, it disappears and I cannot use quick unlock anymore. When I then open Keepass2Android again, I need to insert the complete password.

I have already disabled the battery optimization for the app in the android settings, without success.
On my old Nexus 4 and on my Asus ZenPad 3S, the notification bar entry is available even after days and it is seems to be never closed automatically. 

On the other side, apps like Tasker also remain active in the notification bar/background for days, so it seems to be the specific combination of Keepass2android and the BQ Aquaris which triggers this strange behaviour.

Any ideas what I could change or try to find the cause of this issue?

**Comment by freelon** [comment]
Hey,
I have the same problem on EMUI 5.1 (based on Android 7.0), just that it is killed after couple of minutes already. I'm playing with some settings now (e.g. show the notification also on lock screen) to see if then problem doesn't occur.

For sake of completion, what Android version where you running on your old devices?
Until yesterday I was using xiaomi mi 4 with Android 7.1, no issues there as well.

**Comment by dominicdesu** [comment]
After the last BQ firmware update Keepass2Android is keep running much longer. Currently it is active since 10 days, even though I didn't use it. I'll continue to monitor the situation, but for me the issue seems to be gone.

The BQ Aquaris is running 7.1.1, the Asus ZenPad 7.0.0 and the Nexus 4 was running the latest available Android version for the Nexus 4.

**Comment by PhilippC** [comment]
closing this. KP2A is doing its best to keep alive as long as possible, but it's not possible on Android to avoid getting killed completely.
