### ISSUE TITLE
Gdrive will Not Login

### ISSUE THREAD

**Issue by leder11011** [PhilippC/keepass2android#1411]
Hi Philipp,

I Switched phones and cannot open the shared kdbx on gdrive anymore!

Error is attached.

Ciao
Gerrit
![Screenshot_20200918-121859](https://user-images.githubusercontent.com/3330116/93587624-79b6c880-f9aa-11ea-8789-abda740ff4aa.jpg)

**Comment by nightlyone** [comment]
I can confirm that this happens.

**Comment by PhilippC** [comment]
please see https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254
