### ISSUE TITLE
Cannot find file content://keepass.kdbx in file explorer

### ISSUE THREAD

**Issue by leder11011** [PhilippC/keepass2android#1418]
I have tried search in
/Android/Data/

No success!

Where is my data located?

**Comment by PhilippC** [comment]
this URL means that you have used Android file browser to locate it. Keepass2Android only receives a filename but no real folder location, so the URL doesn.t tell where it is unfortunately. I propose you use file search to find it?

**Comment by leder11011** [comment]
Yes: I use file search.

How can I locate the file other than that?

I urgently need to backup my kdbx file!

Thanks in advance
Gerrit

**Comment by leder11011** [comment]
Got it: I exported the kdbx through k4a settings!

Now I can backup the kdbx file!

Please leave this issue as resolved.
