### ISSUE TITLE
Fingerprint unlock feature cannot unlock same kdbx after reboot

### ISSUE THREAD

**Issue by Knysliux001** [PhilippC/keepass2android#142]
Might be an issue with specific implementation of fingerprint feature on Vernee Thor.
After reboot fingerprint icon becomes red next to password field and does not work. Password is always accepted. Happens after every reboot on this phone.

**Comment by PhilippC** [comment]
maybe you can collect a logcat (or an app log if logcat is not possible) to see what the exact reason is. Make sure you don't add/remove fingerprints while testing. You might also try different phone login methods.

**Comment by Knysliux001** [comment]
I do not have root access for logcat.

- Enabled fingerprint unlock for database.
- Closed database, closed application
- Tried to open application again - next to password field there is a fingerprint icon
- Unlocked with a fingerprint
- Turned off the phone

application log while working fine:
[before shutdown.log](https://github.com/PhilippC/keepass2android/files/1544750/before.shutdown.log)

- Turned on the phone
- Provided passcode to unlock the phone
- Locked screen
- Unlocked with fingerprint
- Started Keepass2android
- Next to the eye icon instead of fingerprint icon - exclamation mark in a red circle
- Trying to use fingerprint to unlock - nothing
- Pressed on the icon:
Fingerprint unlock
Fingerprint Unlock failed. Decryption key was invalidated by Android OS. This usually happens if a new fingerprint was enrolled or a security settings were changed. Please unlock with your password and then re-enabled Fingerprint Unlock in the database settings.
- OK
- Unlocked with a password

Attaching full app log:
[keepass2android.log](https://github.com/PhilippC/keepass2android/files/1544767/keepass2android.log)

Phone itself accepts fingerprint unlock fine, Google Play store did not have any issues with fingerprint unlock also.

**Comment by PhilippC** [comment]
The exception which KP2A receives has the following documentation:

> This only occurs for keys which are authorized to be used only if the user has been authenticated. Such keys are permanently and irreversibly invalidated once the secure lock screen is disabled (i.e., reconfigured to None, Swipe or other mode which does not authenticate the user) or when the secure lock screen is forcibly reset (e.g., by Device Admin). Additionally, keys configured to require user authentication to take place for every of the keys, are also permanently invalidated once a new fingerprint is enrolled or once no more fingerprints are enrolled. 

I don't think there is anything I can do about that. Please check if any special launcher or settings might cause this. If not, maybe the device manufacturer's support can comment on the behavior?
