### ISSUE TITLE
Unable to build JavaFileStorageBindings

### ISSUE THREAD

**Issue by penguin359** [PhilippC/keepass2android#1422]
I am unable to build Keepass2Android in Visual Studio due to a build error in the JavaFileStorageBindings subproject. I am not terribly familiar with using Xamarin for Android projects so this may be due to a misconfiguration or component mismatch. I am working from Visual Studio 2019 Community. The build error is:

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(431,5): error XACLR7024: Xamarin.Tools.Zip.ZipIOException: File ..\java\JavaFileStorage\app\build\outputs\aar\JavaFileStorage-debug.aar does not exist and file creation wasn't requested
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(431,5): error XACLR7024:    at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options) in /Users/runner/runners/2.165.0/work/1/s/ZipArchive.cs:line 273
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(431,5): error XACLR7024:    at Xamarin.Android.Tasks.CreateLibraryResourceArchive.RunTask()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(431,5): error XACLR7024:    at Xamarin.Android.Tasks.AndroidTask.Execute()

**Comment by PhilippC** [comment]
you need to build the java libraries first. See src\build-scripts\build-java.bat

**Comment by haiqindao** [comment]
I ran the build-java.bat first and then ran build-xamarin.bat on windows 10, still get the similar error like this:
Project "e:\gitrepos\keepass2android\src\KeePassLib2Android\KeePassLib2Android.csproj" (5:2) is building "e:\gitrepos\k
eepass2android\src\KP2AKdbLibraryBinding\KP2AKdbLibraryBinding.csproj" (7:3) on node 1 (default targets).
D:\Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.EmbeddedResource.targets(145,5): error XACLR70
24: Xamarin.Tools.Zip.ZipIOException: Error occured while reading ..\java\KP2AKdbLibrary\app\build\outputs\aar\app-debu
g.aar [e:\gitrepos\keepass2android\src\KP2AKdbLibraryBinding\KP2AKdbLibraryBinding.csproj]
D:\Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.EmbeddedResource.targets(145,5): error XACLR70
24:    at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictCons
istencyChecks, IPlatformOptions options) in /Users/runner/work/1/s/ZipArchive.cs:line 200 [e:\gitrepos\keepass2android\
src\KP2AKdbLibraryBinding\KP2AKdbLibraryBinding.csproj]
D:\Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.EmbeddedResource.targets(145,5): error XACLR70
24:    at Xamarin.Android.Tasks.CreateLibraryResourceArchive.RunTask() [e:\gitrepos\keepass2android\src\KP2AKdbLibraryB
inding\KP2AKdbLibraryBinding.csproj]
D:\Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.EmbeddedResource.targets(145,5): error XACLR70
24:    at Xamarin.Android.Tasks.AndroidTask.Execute() [e:\gitrepos\keepass2android\src\KP2AKdbLibraryBinding\KP2AKdbLib
raryBinding.csproj]
Done Building Project "e:\gitrepos\keepass2android\src\KP2AKdbLibraryBinding\KP2AKdbLibraryBinding.csproj" (default tar
gets) -- FAILED.

Done Building Project "e:\gitrepos\keepass2android\src\KeePassLib2Android\KeePassLib2Android.csproj" (default targets)
-- FAILED.

**Comment by PhilippC** [comment]
> Error occured while reading ..\java\KP2AKdbLibrary\app\build\outputs\aar\app-debu
g.aar [e:\gitrepos\keepass2android\src\KP2AKdbLibraryBinding\KP2AKdbLibraryBinding.csproj]

did you check if this file exists?
