### ISSUE TITLE
Unable to change WebDAV password

### ISSUE THREAD

**Issue by bertbert72** [PhilippC/keepass2android#1425]
Apologies if this is obvious, but I've spent ages trying to find where I can change the connection settings for a WebDAV connection.  My password on the server has changed meaning that the app no longer can sync with it.

I found this issue: https://github.com/PhilippC/keepass2android/issues/27 which apparently has been resolved.  So looks like I should be able to change the connection settings.  If I only knew where to look...

**Comment by PhilippC** [comment]
if you are on the password screen, select Change database to come back to the start screen where you see the list of recent files. There, tap the three vertical dots next to the WebDav URL and select Edit. An alternative option would be to simply select "Open database" and enter the credentials again.

**Comment by bertbert72** [comment]
Thanks Philipp
