### ISSUE TITLE
[BUG? FEATURE?] to know regular from trashbin entries in searchbar

### ISSUE THREAD

**Issue by yasuoiwakura** [PhilippC/keepass2android#1432]
I use keepass2android wich a regular kdb file (KeePass portable for Windows, NOT XC)

When deleting or changing an Entry in KeePass, a backup copy is being placed in the trashing area.

Now, when searching in Keepass2Android I will get ALL the results (even the trashed ones) and there is NO WAY to distinguish them.
 there is no "trash" mark and you cannot see the modification date.

I suggest:
 * mark trashbin items
* sort same-named entries by modification date
* maybe show modification date along with search results

And Btw: great work!!

**Comment by PhilippC** [comment]
to my understanding the kdb format does not support marking a group as recyclebin (and the name of that group can be different depending on the language) so I don't think this can be implemented. It works if you upgrade to use kdbx.

**Comment by yasuoiwakura** [comment]
![grafik](https://user-images.githubusercontent.com/8234100/95661132-265d1380-0b2d-11eb-9e1e-b39621cd1c3f.png)
hi there,
keepass for windows has this checkbox. Keepass would store a copy of the old Entry if you modify it.

PS: switching to kdbx now
