### ISSUE TITLE
Fingerprint quickunlock on FP3

### ISSUE THREAD

**Issue by kramerwolf** [PhilippC/keepass2android#1439]
The fingerprint sensor on the Fairphone FP3 is not working for quickunlock. 
Not being able to make a Screenshot Here just the first failing call of the log.
Error inalizing fingerprint unlock:
Java.Lang.runtimeexeption:
Exception of type... Biometricdecryption.ini () in [000d0] <d88b9a7d74f7461c9e9cc57e36dbc807>:0

The Symptom is that there is simply no reaction if the sensor is used.

**Comment by klic** [comment]
What ROM are you using? With LOS16 it works fine for me

**Comment by kramerwolf** [comment]
I'm not sure what you are referring to with ROM and LOS16.
I'm using:
Android 10
Build 8901.3.A.0045.20200905
keepass2android 1.08b-r1

**Comment by klic** [comment]
Exactly that. So you're on the new Android 10 version. I heard they had problems with the fingerprint sensor with that version at the moment. Unlocking and other apps work fine?

**Comment by kramerwolf** [comment]
Hi, yes. At least two other apps work, as well as the phone unlock itself. At the moment Keepass2android is the only app using the sensor not working that I know of.

**Comment by PhilippC** [comment]
Fingerprint unlock can have different forms - KP2A requires to use secure storage (encrypting the master password and saving it with biometric auth) which other apps might not. Can you please try to test with Keepassdroid or KeepassDX?

**Comment by kramerwolf** [comment]
Keepassdroid works for the biometric unlocking.

**Comment by kramerwolf** [comment]
I believe I manages to identify some important detail and a simple fix. Once disabling the biometric quick unlock and re-enabeling it fixed the matter. Previously I was only checking for the correct setting. Biometric quickunlock was enabled before mirgrating from Android 9 to Android 10. So I guess the biometric data needed refreshing after OS upgrade.
Thanks to all of you for the support.
Thomas

**Comment by PhilippC** [comment]
thanks for the update!
