### ISSUE TITLE
Can't open new SFTP database on OVH SFTP server

### ISSUE THREAD

**Issue by Cromagnon31** [PhilippC/keepass2android#1444]
Hi Phillip,

With resent version of Keepass2droid, i'm unable to open new database on an OVH shared FTP server using SFTP.
Open procedure connects to server but database list is empty.

My keepass2droid version is 1.08b-r1. 

Using FTP only it's all clear.
Opening already SFTP referenced database is working.

If you need test access to OVH FTP server, tell me how to transmit them in a private way.

Olivier

**Comment by PhilippC** [comment]
can you please enable debug logging and see if the log shows any useful hint?
You can also send it to me at crocoapps@gmail.com. If the log does not help, you can also send testing credentials there.

**Comment by PhilippC** [comment]
thanks for providing the credentials (and helping me to use them properly on Windows :-) ).
I think the problem is that KP2A requires you to specify the start directory, which should be `/home/[username]` and then it works with your server.
