### ISSUE TITLE
Exported file as unencrypted xml - how to import it again

### ISSUE THREAD

**Issue by jetguat** [PhilippC/keepass2android#1450]
In mid Septemer 2020 i created an unexcrypted xml -- export of my password DB.   (its saved in a secure location).
I had to swap out my phone.  I have been unable to import the data from that file, I was only able to import and earlier saved, which sadly is out of data.

Is there a different way to import the xml file?  Any recommendations on how to sync up the content from that recently saved unencrypted version into the current db?

Hoping from some guidance on this.  

- From Unlock database screen, i select the xml file
- the masterkey type is set to password only
- i enter the password
- punch the unlock button

An error occured:  The file signature is invalid.  Either the file isnt's a KeePass database file at all or its corrupted.

**Comment by PhilippC** [comment]
the app is acually missing this feature at the moment. If you want to open the file right now, I suggest you use Keepass2 on a PC to import the xml to a kdbx. I also just implemented this in the app, but it might take 1-2 weeks until it's in beta.

**Comment by jetguat** [comment]
Its took me a few attempts to figure out how to import the xml file.  The synchronization option on the PC app did not work as I expected.  But in the end, it works.  many thanks!
