### ISSUE TITLE
Icedrive Synch

### ISSUE THREAD

**Issue by Tomi19** [PhilippC/keepass2android#1451]
Hi,
Please provide the option to synchronise the database file with IceDrive.
Thanks in advance.

**Comment by PhilippC** [comment]
I don't see any API documentation on their site.

**Comment by Tomi19** [comment]
Thanks for looking into this. I opened a ticket with them, hopefully they will provide an API documentation. Do you know if synchronising is possible using the website of Icedrive? I know I can also use the cloud via browser.

**Comment by PhilippC** [comment]
I just see they support WebDav, so Keepass2Android should be able to access it: https://icedrive.net/help/account/does-icedrive-support-webdav
