### ISSUE TITLE
Exclude homoglyphs from password generation

### ISSUE THREAD

**Issue by elected** [PhilippC/keepass2android#1456]
I think it would be helpful if you could add a option to exclude homoglyphs from the password generation.
The font helps for the most characters but for example 0 (zero) an O (upper o) are very close to each other. In the case that only one of them is in the password and you can not compare them to each other, confusion is possible.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
allow the creation of passwords with Exclude homoglyphs drops entropy.
also the kp2a font used in password fields clearly shows difference from 0!=0 by using dotted zeroes.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> homoglyphs from the password generation.
> The font helps for the most characters but for example 0 (zero) an O (upper o) 

The password field don't but generator See: #1510

**Comment by PhilippC** [comment]
merged into https://github.com/PhilippC/keepass2android/issues/81
