### ISSUE TITLE
Access to path "/storage/0/Download..." is denied

### ISSUE THREAD

**Issue by inanedirk** [PhilippC/keepass2android#1468]
Getting an Access denied error when trying to open a file.
Also got EBADF (bad file descriptor) when trying to merge / overwrite earlier.

Worked before the November Update of Android 11. Works properly on other phone that's on October Update.

Not sure if any of this is relevant:
I'm using Resilio Sync to keep the file synchronised between phones and computers.
Using Total Commander On Android 11, October Update shows file permissions as -rw-rw----, UID 0 root, GID 9997 everybody.
Android 11, November Update has the same file as -rw-------, UID 10251 Media Storage, GID 10251 Media Storage.

**Comment by Gremlin69** [comment]
I have the same issue with my Samsung Galaxy Tab A 2018, while it works on my Samsung Galaxy S10. It used to work on the tablet as well. The key file is stored in separate folder on the internal storage. I get access with other apps such as MIX Explorer to the folder.
Given the denied access, I am noit able to use the app.

MEssage is: Acesss to path:"/storage/emulated//0/Keypass/Filename.key" is denied.

**Comment by PhilippC** [comment]
@inanedirk what happens if you re-select the file? @Gremlin69 can you try to open the file through another method (e.g. Android file explorer)?

**Comment by inanedirk** [comment]
"An error occured: [...] Access denied" or EBADF (bad file descriptor) depending on how I try to open it (Change database -> System file picker / "open with" menu in Total Commander).
Btw I also removed and re-created the file and the folder it's in, still same error.

Thanks for looking into this, I appreciate it!

**Comment by PhilippC** [comment]
There is a change in Android 11 which I was not aware of regarding file permissions. I guess this is causing the trouble. See https://developer.android.com/about/versions/11/privacy/storage for details. You might try to see if it helps to re-grant the app permissions regarding storage/files, but it might also not be possible to access those files on Android 11 at the moment.

**Comment by inanedirk** [comment]
Regranting permissions doesn't solve the issue unfortunately

**Comment by Gremlin69** [comment]
I can confirm that opening the path works perfectly with Android Bowser and other browser.
How can I assist / be of help? What is needef to locate the problem?
I use Android 10, SEPF_SM-T590_10_0021, Buildnumber QP1A.190711.020.T590XXU3CTI4.

**Comment by Gremlin69** [comment]
KP2A Version used is 1.08-r1

**Comment by innertruth** [comment]
We also got this problem with my son's Xiaomi Poco X3, this is Android 10, QKQ1.200512.002, MIUI Global 12.0.7 Stable 12.0.7.0(QJGEUXM)

I do **not** have the problem with my Xiaomi Redmi Note 8 Pro, this is also Android 10, QP1A.190711.020, MIUI Global 12.0.2 Stable 12.0.2.0(QGGEUXM). Wonder what happens if I get an update to the same MIUI version as my sons phone, if I get that update...

**Comment by GregAlexandre01** [comment]
Hi,
On Samsung with Android 11, I have the access denied problem with the key file.
Is there a workaround: 
- granting permission with adb (I am doubtful reading https://developer.android.com/about/versions/11/privacy/storage ) ?
- Moving the keyfile to the app storage file (but how)?
Hope this helps.

**Comment by nathaniel-mahieu** [comment]
I would like to confirm this issue on 1.08d-r5 and android 11 4.14.199-gaf03eef7d4c3-ab7185840
#1 Fri Mar 5 04:26:05 UTC 2021

Prevents saving passwords and search texts so is somewhat impactful.

Workarounds that did not work: moving file location between downloads and other locations, uninstalling and reinstalling the app.

**Comment by GregAlexandre01** [comment]
@Gremlin69 & @inanedirk : I agree with inanedirk. The problem is with the kdbx file.

**Comment by inanedirk** [comment]
In case anyone is getting notifications for this thread: As of right now, Keepass2Android can once again write to a resilio folder. Current versions of resilio, Keepass2Android and Android 12 Build SQ3A.220705.003.A1 (July 5, 2022 security update, June 1, 2022 Play system update).
