### ISSUE TITLE
Hide top bar icon

### ISSUE THREAD

**Issue by carlogarro** [PhilippC/keepass2android#1471]
Hello, could it be possible to hide the notification bar icon it while the database is blocked?
Only show it maybe when it is unlocked, or to be able to choose it.

Thank you!

**Comment by PhilippC** [comment]
you mean the icon or the whole notification?

**Comment by carlogarro** [comment]
The icon, and the notification that appears when I slide down the window. (if it is called notification). Let me post a picture of it.

**Comment by PhilippC** [comment]
Thanks for the clarification! QuickUnlock requires a service to run, and a service must be visible to the user. So the only option is to disable QuickUnlock.
