### ISSUE TITLE
Duplicate changelog Version  Version 1.08c-r1 1.08b 

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [PhilippC/keepass2android#1474]
Version 1.08b 

![IMG_20201120_220543](https://user-images.githubusercontent.com/46166740/99849924-b48cd680-2b7c-11eb-9043-48debc7d85cb.jpg)

**Comment by PhilippC** [comment]
fixed in 24b690d19be5c76514e1f6d6a8ac7353d81d94b5
