### ISSUE TITLE
Multiple Database?

### ISSUE THREAD

**Issue by clock33** [PhilippC/keepass2android#1476]
My deleted keepass database file showed up in keepass2android system picker, even though I deleted it from my phone. Meanwhile on my xiaomi android 9 device, I need to pick my database again if I delete it. 
My device is Samsung A50 Android 10. Is this the intended behavior for Android 10?

**Comment by PhilippC** [comment]
which file browser do you mean? The list of recent files? Or anything you see after selecting Open file?

**Comment by clock33** [comment]
the list of recent files

**Comment by PhilippC** [comment]
you can remove it from there as well by tapping the three vertical dots on the right of it.
