### ISSUE TITLE
The file you selected is read-only for Keepass2Android due to restrictions on Android 4.4+

### ISSUE THREAD

**Issue by dwhite4245** [PhilippC/keepass2android#1489]
I am using QNAP's Qsync on my Android 10 phone to synchronise a folder on my NAS with various devices. My Keepass2 database is contained in this folder and so whenever it is modified it is synch'd to the other devices.
When I open Keepass2Android on my phone and try to open my keepass2 database it gives the following "The file you selected is read-only for Keepass2Android due to restrictions on Android 4.4+. To edit it, you must copy the file to another location."
The sync folder is on my SD card but I've also tried it in phone storage but always get this message.
Copying it to another location will defeat the point of synchronisation so can anyone suggest what the problem is here?
Thanks in advance, Dave.

**Comment by PhilippC** [comment]
how did you open the database? Through Android file browser or a third party app? THis should have an effect on how file access behaves.

**Comment by dwhite4245** [comment]
Yes, you're right. Using theSystem File Picker seems to work whereas with a third-party one it does not. Thanks.
