### ISSUE TITLE
Notification Actions do not work on Oreo

### ISSUE THREAD

**Issue by thermatk** [PhilippC/keepass2android#149]
Hi!
With the upgrade to Android 8.0 Oreo notification actions such as Close Database stopped working for me. I would expect [this can be fixed like that](https://stackoverflow.com/a/47032464), could you please look into that? I think it goes somewhere here, but I don't know C#:
https://github.com/PhilippC/keepass2android/blob/d40656b69afce3dff3ef4328731e69a97b78d11a/src/keepass2android/services/OngoingNotificationsService.cs#L165

**Comment by PhilippC** [comment]
see also https://stackoverflow.com/questions/46549109/pendingintent-is-not-working-on-android-o

**Comment by PhilippC** [comment]
if you encountered this error with version 1.04b or earlier, can you please check if this is fixed in 1.05-pre1?

**Comment by inn0kenty** [comment]
I can confirm that 1.05-pre1 fix this issue.
Nexus 5x, Android 8.1.0

**Comment by PhilippC** [comment]
a user is reporting this is still not working on his Android 7 device. Can anybody reproduce?

**Comment by romanomauro** [comment]
@PhilippC , Android 7, Huawei P10 Lite, doens't works yet. :(
For your information, the app KeePassDroid works.

**Comment by romanomauro** [comment]
Hi @PhilippC, I confirm that the version 1.05-pre1 fix this issue for Android 7, Huawei P10 Lite. Thank you.
