### ISSUE TITLE
build error on windows for build-xamarin.bat for Kp2aKeyboardBinding.csproj

### ISSUE THREAD

**Issue by haiqindao** [PhilippC/keepass2android#1493]
I ran the build-java.bat first and then ran build-xamarin.bat on windows 10, still get the similar error like the following, any idea what might be wrong? thank you!

my visual studio is latest visual studio 2019 16.8.2

Project "e:\gitrepos\keepass2android\src\KeePassLib2Android\KeePassLib2Android.csproj" (5:2) is building "e:\gitrepos\k
eepass2android\src\KP2AKdbLibraryBinding\KP2AKdbLibraryBinding.csproj" (7:3) on node 1 (default targets).
D:\Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.EmbeddedResource.targets(145,5): error XACLR70
24: Xamarin.Tools.Zip.ZipIOException: Error occured while reading ..\java\KP2AKdbLibrary\app\build\outputs\aar\app-debu
g.aar [e:\gitrepos\keepass2android\src\KP2AKdbLibraryBinding\KP2AKdbLibraryBinding.csproj]
D:\Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.EmbeddedResource.targets(145,5): error XACLR70
24: at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictCons
istencyChecks, IPlatformOptions options) in /Users/runner/work/1/s/ZipArchive.cs:line 200 [e:\gitrepos\keepass2android
src\KP2AKdbLibraryBinding\KP2AKdbLibraryBinding.csproj]
D:\Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.EmbeddedResource.targets(145,5): error XACLR70
24: at Xamarin.Android.Tasks.CreateLibraryResourceArchive.RunTask() [e:\gitrepos\keepass2android\src\KP2AKdbLibraryB
inding\KP2AKdbLibraryBinding.csproj]
D:\Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.EmbeddedResource.targets(145,5): error XACLR70
24: at Xamarin.Android.Tasks.AndroidTask.Execute() [e:\gitrepos\keepass2android\src\KP2AKdbLibraryBinding\KP2AKdbLib
raryBinding.csproj]
Done Building Project "e:\gitrepos\keepass2android\src\KP2AKdbLibraryBinding\KP2AKdbLibraryBinding.csproj" (default tar
gets) -- FAILED.

Done Building Project "e:\gitrepos\keepass2android\src\KeePassLib2Android\KeePassLib2Android.csproj" (default targets)
-- FAILED.

**Comment by PhilippC** [comment]
seems like you need to run build-java.bat first, the aar could not be found
