### ISSUE TITLE
Let's Encrypt Certificates wont be validated

### ISSUE THREAD

**Issue by superwinni2** [PhilippC/keepass2android#1496]
Hi

I've got my database in selfhosted Nextcloud which is available via HTTPS with an TLS Certificate from Let's Encrypt.
The app won't recognize the certificate. 
The Certificate Issuer is "CN=R3, organizationName = Let's Encrypt, countryName = US"

**Comment by PhilippC** [comment]
this is probably system specific. Is it an old Android version? Can you try to add it as user certificate?

**Comment by superwinni2** [comment]
Im using an OnePlus 8T with Android 11... The certificate is going to be accepted everywhere like Browsers, Nextcloud App, DAVx5, Emby, Gotify.

The message is: 
"Warnung: Server-Zertifikat konnte nicht validiert werden: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. Installiere ein passendes Root-Zertifikat auf deinem Gerät oder siehe Einstellungen." 
(Sorry for German / English. Thats What the Error message in German says.)
In full english:
"Warning: Server-Certificate can't be validated:  java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. Install a suitable root certificate on your device or see settings."

Installing the R3 as a user CA works but it's not a nice workaround in my oppinion.
__________________________________________________________________________________________________

I also updated the ACME.sh Script and now it seems that it's working correctly... Strange...
I will keep an eye on this...
