### ISSUE TITLE
[Feature Request] Password Generator on open/quick unlock

### ISSUE THREAD

**Issue by LaffinToo** [PhilippC/keepass2android#1497]
Many times when I'm registering for a site, I have to open/unlock the database, create a new entry, just to get to the password generator. Would be nice to have access to the password generator on open/unlock screens would be helpful on creation of new entry that last password generated this way would be auto filled...

**Comment by Suncatcher** [comment]
Support this, I also did this many times. It would be good to make password generation a separate function from database

**Comment by PhilippC** [comment]
but you need to save the new entry anyway - why not just create it and then fill the password from the saved entry?
