### ISSUE TITLE
[Feature Request] Add new key to locale database and sync to database in internet network

### ISSUE THREAD

**Issue by tomasmueller** [PhilippC/keepass2android#1498]
Hi,

i don't want to save the database online, its saved on my raspberry pi. When i'm in my home wifi access to the database works fine but not when i'm not at home. Using a vpn is possible but laborious. There is a notification that database is synced to locale storage. there should be a copy on my device. when i'm not at home an want to add a new key: is it possible to add the new key to the locally saved database and sync it with the database on my pi when i'm back at home? Only the new key should be added to the database on the pi.

I know i can sync the database file between raspi and smartphone. but i use K2A on 3 android devices. when i add a new key to the database on my smartphone and a new key to the database on my tablet both will sync there databases with the raspberry pi. So at the end i will have a new database but not with two new keys. There will be only one new key depending what devices synced at least.

**Comment by PhilippC** [comment]
If you can access the database on the pi using one of KP2A's built in methods (e.g. WebDav or SFTP), this should work out of the box: KP2A has a local cache copy, and before synchronizing changes to the server, it will check for changes and then offer to merge (you see a dialog where you confirm that you want to merge).

**Comment by tomasmueller** [comment]
Lets say i'm at home and K2P syncs the database to the local cache. Now that database on the smartphone and on the pi is the same. I go to work and don't have access to my home wifi and to the database file on the pi. Now i add a new key to the local database on the smartphone. Now the database on my phone is different from the database on the pi. when i'm back at home K2P syncs both files automatically or when i open the database the next time?

a few days ago i wanted to pay something using paypal and could not login because K2P could not open the database. I thought this was because K2P could not access to the database on the pi. i'll test this again.

**Comment by PhilippC** [comment]
It syncs either when you open the file (complete fresh open, not QuickUnlock) or when you select "Synchronize database" from the menu in the group view.
