### ISSUE TITLE
Update Google Play information

### ISSUE THREAD

**Issue by ckesc** [PhilippC/keepass2android#150]
Information at [Google Play listening](https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=en) is obsolete: it still refers to http://keepass2android.codeplex.com/
I have checked both [russian](https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=ru) and [english](https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=en) version.

Maybe update the link? :)

**Comment by PhilippC** [comment]
thanks for the hint. link updated.
