### ISSUE TITLE
Keyboard change request after closing database

### ISSUE THREAD

**Issue by ee0s** [PhilippC/keepass2android#1502]
Hi.
There is quirk with the option  "Use built-in keyboard inside K2A". When that option is on, closing database causes an unnecessary keyboard change request, which cannot be easily bypassed.

Steps to reproduce:
- use quickunlock
- Select "Use built-in keyboard inside K2A" in Settings - App - Security
- open database
- change keyboard back to your normal kayboard (not K2A)
- lock database (K2A hides to background)
- switch back to K2A, now on QuickUnlock screen
- tap "close database"

What happens:
- K2A stays on foreground and switches to unlock database screen. This triggers the "please activate K2A keyboard" dialog. Tapping cancel or back button just retriggers the dialog. To get rid of it, you have to use app switcher or switch to K2A keyboard.

What is expected to happen:
- K2A should just disappear / drop to background. 

When I'm tapping "close database", I do that because I no longer want to use K2A at the moment. Also closing database triggers sync and leaving K2A running in the background causes sync annoyances while using KeePass elsewhere.

K2A version 1.08c-r1 (this has existed for a while in previous versions too)

Thanks for your amazing work, I appreciate it a lot.

**Comment by PhilippC** [comment]
it's difficult to predict what people really want to do if they come to the password screen: are they about to close the app or are they planning to change to another database? I suggest you use the notification bar pull-down to click close database there instead of opening KP2A again if you want to close the database.
