### ISSUE TITLE
The clipboard is not cleared

### ISSUE THREAD

**Issue by McAri4** [PhilippC/keepass2android#1506]
Hello! On my honor v30 pro device with android 10, the clipboard is not cleared by timeout, so I suggest that you force the clipboard to be cleaned when the application is locked and the button for its forced cleanup is also like the "stop application" button.

**Comment by PhilippC** [comment]
the documentation clearly states that clearing the clipboard is unrealiable on many devices, and the clipboard itself is unsafe at all. Please don't use it for sensitive data.
