### ISSUE TITLE
Keyboard "Vibrate on key-press" stopped working

### ISSUE THREAD

**Issue by PetrVladimirov** [PhilippC/keepass2android#1507]
Recently, seems after one of the updates keepass2android built-in keyboard stopped vibrating on key-press. Uncheking/Checking the relative option in the settings doesn't help.

As vibration is very useful to avoid mistakes, it would be great to get this defect fixed. Thank you

Version 1.08c-r1
OS: Android 10
Phone: Samsung A-41

**Comment by PhilippC** [comment]
it's still working for me. Is it possible that you changed something in your device settings. Can you please also check the app permissions if you denied something there?

**Comment by PetrVladimirov** [comment]
Thanks for the quick reply. I don't remember to change anything.. It is just stopped working one day. But Android gets regular updates, that could change something.. And truly keyboard vibration shouldn't be dependent on Contacts and Storage access that the app requests... Other keyboards can still vibrate.

Reboots and reinstalling the app didn't help. What else can I check?

**Comment by PetrVladimirov** [comment]
@PhilippC  - after phone firmware update the issue was gone, so it seems that the issue was somehow related to the Samsung firmware. I would suggest to close the issue. Thanks.
