### ISSUE TITLE
Zero and capital O indistinguishable in password generator

### ISSUE THREAD

**Issue by alinuxexpert** [PhilippC/keepass2android#1510]
I don't know if this is specific to my phone, but I was just using the password generator and could not figure out if the password contained 0 (zero) or O (capital character O). In fact, they look EXACTLY the same on my phone. No difference in shape at all.

Expected behaviour: Zeros and character o can be easily distinguished, e.g., using a special font that displays a dot within the zero.

Actual behaviour: Zeroes and capital character O look exactly the same.

Version: 1.08c-r1

**Comment by svenssonaxel** [comment]
The font used for password fields is already different from other fields, so that all characters can be easily distinguished. It'd be good if this font can be used for the password generator field as well.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Yes, would make sense to use same font for same text between generation and field for readability

**Comment by PhilippC** [comment]
merged into https://github.com/PhilippC/keepass2android/issues/81

**Comment by PhilippC** [comment]
this was closed in https://github.com/PhilippC/keepass2android/commit/4636f5800cc76a2a807109afe14166fadc35b508 a while ago
