### ISSUE TITLE
App stuck when put in background while saving database 

### ISSUE THREAD

**Issue by Lineflyer** [PhilippC/keepass2android#1512]
K2A version: 1.08d-r0
Device: Samsung S20, Android 11

Today I managed to get the app stuck while saving the database as follows:

- Database is stored on a ftp (so it might take a while to load/save)
- Opened K2A and added a new entry
- Selected to store the entry 
- While storing still in progress I changed to my browser app
- After a while I changed back to K2A and see the following window:

![PXL_20201223_120543526](https://user-images.githubusercontent.com/949669/102995033-7cccd200-4520-11eb-8877-d79888bef873.jpg)

- I waited for approx. one minute but nothing changes
- I cannot answer the merge dialog as it is shown below the progress dialog

- I ended K2A and started it again
- The progress dialog is still shown, the merge dialog is no longer shown
- I waited again for approx. one minute but nothing changes

I had to reboot my device to get out of this situation.
Luckily it seems the database is still OK, the new entry has not been saved.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Looks similar like #1541 ?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
>  If I switch away, when I switch back then I'm blocked from making a selection by a foreground window indicating a merge in process. 
> 

Thats same experienced: 

-  #1662



> Closing the app isn't enough, if I do, when I reopen the app its still stuck waiting for input, I have to reboot the device.

This shouldn't be necessary, try force close the keepass2android app through android app info. There where you find next to delete app data button
