### ISSUE TITLE
FTPs Lets Encrypt certificate not valid. Even though it is.

### ISSUE THREAD

**Issue by Napsterbater** [PhilippC/keepass2android#1523]
I think this is similar to this. https://github.com/PhilippC/keepass2android/issues/1496

So I have a Lets Encrypts on my Filezilla FTPs (Implicit), it is the same exact certificate I use for my Webserver.

It is a wildcard cert that covers the subdomain in question. Said cert work for the same FQDN in every browser on the device that keepass2android is running and SSLLabs, and Filezilla on another PC.

Yet in the app I keep getting the warning:
![CertERROR](https://user-images.githubusercontent.com/18711451/103599728-d09dca80-4ed3-11eb-8a32-4b4c55ec7688.png)

Forgot to note: This is on a Google Pixel 3a XL Running Android 11 (all updates as of this report)

**Comment by PhilippC** [comment]
can you please do the checks suggested in https://stackoverflow.com/a/16302527/292233

**Comment by Napsterbater** [comment]
I didn't read though much of that, but it set off a light bulb just as I started to.

I updated filezilla to use the "full chain" cert, message is now gone. So Likely it was complaining of the missing intermediate.
