### ISSUE TITLE
When using parent-db and "Unlock with fingerprint" gets lost, prefs are ambiguous

### ISSUE THREAD

**Issue by nursoda** [PhilippC/keepass2android#1524]
When one cancels biometric authentication, it is deactivated in the app. OK so far, but it would be nice to get some warning/explanations in such case. What I seem to have encountered is that I opened my db with my fingerprint, missed it and used the three-dot-menu in the upper right to navigate to database settings. I re-enabled it there but next time I opened the app it did not work. I think I just found out why: I use a local db to open two cloud-based child databases.

My expectation was that when I open that local DB and head to the three-dot-menu, I edit its prefs. Turns out I don't! Instead, the prefs of one of the child databases was modified. I had to tap the  local DB first – and then even get asked that there is a biometric device available (not quite the info I meant in the first paragraph though). Now, setting fingerprint auth THERE solves it.

Lessons learned: The special case "empty parent DB to just load two or more databases" should receive some more UX care ;)

I'm on Play beta w/net on OnePlus 6T.

**Comment by PhilippC** [comment]
You can try to enable debug logging in the app settings and after this occurs again, send me the log (or look into it). Maybe there is a hint what exactly happened. Note that this is expected to happen if you enroll a new fingerprint in the device's biometric settings.

**Comment by nursoda** [comment]
OK, I enabled debugging in app settings and will reopen this bug if it happens again. I did not register or delete prints nor did anything else (like system firmware or play service updates) change on my phone (except for normal app updates). Thanks.
