### ISSUE TITLE
Black Theme

### ISSUE THREAD

**Issue by Adrenokrome82** [PhilippC/keepass2android#1525]
A black theme will make the application more aesthetic and design.

**Comment by PhilippC** [comment]
please see settings - app - display - design

**Comment by Adrenokrome82** [comment]
In the French app, "design" is a "conception" that does not clearly represent the design. "Thème" is more appropriate in French.

Thank for return

________________________________
De : PhilippC <notifications@github.com>
Envoyé : samedi 9 janvier 2021 12:11
À : PhilippC/keepass2android <keepass2android@noreply.github.com>
Cc : CAPARROS Kevin <kevin.caparros@ynov.com>; Author <author@noreply.github.com>
Objet : Re: [PhilippC/keepass2android] Black Theme (#1525)


please see settings - app - display - design

**Comment by PhilippC** [comment]
have changed this on crowdin, thanks for the hint
