### ISSUE TITLE
Keepass2Android is showing mixed translations, while strings already have a proper translation in Crowdin

### ISSUE THREAD

**Issue by Northguy** [PhilippC/keepass2android#1526]
My latest KeePass2Android version (1.08c-r1) is showing mixed translations. Some are translated into my own language while others are still in English. I fully support your statement at  https://github.com/PhilippC/keepass2android/issues/201#issuecomment-529168742 and did check the Crowdin site, but all translations are already there for 2yrs. So what else needs to be done to get proper translations in the app?

**Comment by PhilippC** [comment]
can you please give me an example of a missing string? Can you find the crowdin link to it and let me know the exact language? Maybe there is something wrong with the build settings?

**Comment by Northguy** [comment]
Hi Philipp, it is not one string, it is a complete mix of Dutch vs English. I have taken a few screenshots and highlighted where Keepass2Android is showing English instead of Dutch. Please note that it is still not an extensive list of all screens that are available, but it should be enough to give you an impression of what is going on.

![Screenshot_20210112-170409_Keepass2Android](https://user-images.githubusercontent.com/1189058/104342053-b9299780-54fa-11eb-8966-48cf6afd2bc0.jpg)
![Screenshot_20210112-170325_Keepass2Android](https://user-images.githubusercontent.com/1189058/104342057-b9c22e00-54fa-11eb-913a-bf82091c8b52.jpg)
![Screenshot_20210112-170253_Keepass2Android](https://user-images.githubusercontent.com/1189058/104342058-ba5ac480-54fa-11eb-83a5-088f6bf4067d.jpg)
![Screenshot_20210112-170232_Keepass2Android](https://user-images.githubusercontent.com/1189058/104342059-ba5ac480-54fa-11eb-97d7-2d1db92443fb.jpg)
![Screenshot_20210112-170118_Keepass2Android](https://user-images.githubusercontent.com/1189058/104342060-baf35b00-54fa-11eb-8b29-98bb5b30e444.jpg)
![Screenshot_20210112-170146_Keepass2Android](https://user-images.githubusercontent.com/1189058/104342063-bb8bf180-54fa-11eb-8895-bbd4df3c7473.jpg)
