### ISSUE TITLE
Autofill is accessing locked database

### ISSUE THREAD

**Issue by p477y** [PhilippC/keepass2android#1527]
Even though the database is locked the Autofill Plugin is able to access the database without unlock. 
Keepass2Android Version 1.08d-r1
Android 10

**Comment by Murgeye** [comment]
Noticed the same on 1.08d-r1 and Android 10. Using a Yubikey for full unlock and fingerprint for quick unlocking. Captured the video below to demonstrate the issue:

![20210109_223709](https://user-images.githubusercontent.com/16648242/104109197-d2003600-52cb-11eb-89fc-71e67182a5ce.gif)

**Comment by PhilippC** [comment]
sorry, this was obviously unintended. Fixed in 1.08d-r2 on https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by Offerel** [comment]
Can you please explain a little bit more if the issue occurred only with some circumstances? 

I have always set complete unlock and not only quick unlock (never used this) with Fingerprint and couldn't not reproduce the issue...

**Comment by Murgeye** [comment]
I think it was a quick unlock only issue. When fully locked I could not Auto fill fields in the last version (as expected).

I am not sure how quick unlock works, but from this issue, I assume it holds the database master key in memory and allows access via the quick unlock? Before, I always assumed that the master key in memory is encrypted using a key derived from the quick unlock method.

**Comment by PhilippC** [comment]
yes, it was quick-unlock only (when the database is not fully locked/not loaded, the app definitely cannot access the contents). There is no encryption - the quick unlock code is very weak for encryption. The lock is "UI only" (i.e. there is no way to access the UI to access the data) - security comes from allowing exactly one attempt.
