### ISSUE TITLE
[Feature request] use Keepass 2.47+ native fieldnames for OTP settings

### ISSUE THREAD

**Issue by thomazz-nl** [PhilippC/keepass2android#1533]
KeePass 2.47 now has a native implementation for OTP and uses it's own set of fieldnames ([specs](https://keepass.info/help/base/placeholders.html#otp)) (e.g. TimeOtp-Secret-Base32, TimeOtp-Length, TimeOtp-Period). It would be good to see keepass2android follow this setup.

Risk: a sudden change of the referred-to fieldnames might confront existing users with broken OTP output. Possible solution: only use the KeePass native fieldnames when the kp2a settings [TrayTotp_SeedField_key and TrayTotp_SettingsField_key](https://github.com/PhilippC/keepass2android/blob/35c69fcb3a036e03556641781606f69b5bcd5a6d/src/keepass2android/Totp/TrayTotpPluginAdapter.cs#L24) are empty.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Thanks for hint for official support now finally! I vote for support of this new standardized feature.
Well as totp user, can one change all entries to new format with desktop app? Mess with export & import back is no option. Can the fields be changed in batch search replace? Possibly by help of kpscript somehow? So we do not need two incompatible implementations in mobile app. Of course the current totp works very well for 99%
For staying in sync with new desktop versions, the new Fields support would be great.
_Backwards compatibility is nice 2 have, but better to adopt official specification first instead trying to support more diversity issues._

**Comment by PhilippC** [comment]
this is already supported in 1.08d-r3 (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by gpion** [comment]
> this is already supported in 1.08d-r3 (https://play.google.com/apps/testing/keepass2android.keepass2android)

How does it work ? 
I've been unable to find any documentation
