### ISSUE TITLE
Offer . apk in this website. 

### ISSUE THREAD

**Issue by fckwan** [PhilippC/keepass2android#1538]
I would like to suggest keepass2android offer the . apk in this website. To remove reliance on google play store.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Open your eyes, Enjoy & See:

https://github.com/PhilippC/keepass2android/releases[https://github.com/PhilippC/keepass2android/releases](https://github.com/PhilippC/keepass2android/releases)

**Comment by fckwan** [comment]
Thanks for pointing me to find the .apk file.
