### ISSUE TITLE
Enhancement - make switch hide/show password permanent

### ISSUE THREAD

**Issue by pyhedgehog** [PhilippC/keepass2android#154]
Eye-shaped button that hides password is very helpful when you are in some open space where someone can look ahead your shoulder. But it's onetime only. It returns to opened state when you change entry. I'd prefer to make this switch permanent and enabled by default.

**Comment by 872191** [comment]
I recently discovered KeePass while searching for a password keeper, especially one that works with Dolphin browser for Android. So far I am happy with KeePass and how it works and works great logging into apps.

By default all passwords are hidden for the app on my phone, LG V30+. Maybe you unchecked the "Hide" box without realizing it. Learning this app and all the features is very intense but well worth it for easy password organization. If you haven't already discovered the solution, here are the steps to permanently show or hide all passwords with Keepass2Android.

Login to the app > Tap the 3 dot menu at the top right of the app> Settings > Application settings > Display > Mark password, hide passwords by default is the second option from the top of the screen on my phone.

Check to hide all, uncheck to show all. After checking or unchecking the box go back and look at your passwords to make sure the option you want is applied.

**Comment by pyhedgehog** [comment]
Good to know it's already implemented.
