### ISSUE TITLE
[Bug] v1.08d-r3 button hides behind dialog

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [PhilippC/keepass2android#1541]
Started editing an entry and tried saving it then while the synchronization process was downloading long time I switched the foreground app back and forth to finally confirm the merging question of the database but when I got back I got stuck at this screen when I switch back:
![IMG_20210116_025753](https://user-images.githubusercontent.com/46166740/104794415-c4551f80-57a7-11eb-8cff-4c69d6952113.jpg)

there is no way to cancel it or escape from the screen needed to end the app and lose my changes.
 coffee added for privacy

No debug logs are available sorry.

**Comment by PhilippC** [comment]
did this happen just once or can you reproduce it?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Not only once, did happen again. every time the synchronization process detects a remotely change since last synchronization.



Steps that trigger it:
1. Unlock a remote database from kp2a device 1

2. Make a change to database and sync upload changes to remote from device 2 (to trigger the dialogue with the question"Datenbank wurde von außerhalb geändert möchten sie die Änderungen zusammenführen?"

Back to kp2a device 1:
3. Make a change to database and let kp2a try to sync  changes to remote 
4. While it shows "prüfe ob sie Datei geändert wurde..." Switch kp2a to background until the download is finished. just wait for it for you the usual needed sync Time or find Download traffic  reduced.
5. Result:

![IMG_20210118_210023.jpg](https://user-images.githubusercontent.com/46166740/104958511-74a56c80-59d0-11eb-8d7d-189db2337f30.jpg)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Not only once, did happen again. every time the synchronization process detects a remotely change since last synchronization.



Steps that trigger it:
1. Unlock a remote database from kp2a device 1

2. Make a change to database and sync upload changes to remote from device 2 (to trigger the dialogue with the question"Datenbank wurde von außerhalb geändert möchten sie die Änderungen zusammenführen?"

Back to kp2a device 1:
3. Make a change to database and let kp2a try to sync  changes to remote 
4. While it shows "prüfe ob sie Datei geändert wurde..." Switch kp2a to background until the download is finished. just wait for it for you the usual needed sync Time or find Download traffic  reduced.
5. Result:

![IMG_20210118_210023](https://user-images.githubusercontent.com/46166740/104959498-9c95cf80-59d2-11eb-8a30-36336a2b26c9.jpg)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Looks like #1512

**Comment by PhilippC** [comment]
I agree, duplicate

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Unfortunately the problem occurred again in the current version **1.90a-r3**.

Merge sync button hides behind the loading cycle, after switching app focus to launcher and back to kp2a once transfer finished.

No logs available.

![Screenrecord.gif](https://user-images.githubusercontent.com/46166740/137657174-d140e4bc-66ed-46b3-b8be-4e74b16be3fc.gif)
