### ISSUE TITLE
SFTP open/create database issue

### ISSUE THREAD

**Issue by pohmeloid** [PhilippC/keepass2android#1547]
Could not create new / open saved database using sftp(ssh) connection - "Error occurred:Permission denied".
My workflow: Change database - create/open - sftp(ssh) - enter url (without sftp:// prefix), port, user name, password, directory (opening saved database). Then new window opens for database password - entering password - Permission denied.
All works fine using same sftp credentials on pc keepass and filezilla client on different devices with different IPs.
Also i am able to open saved database using ftp connection in K2A.
Version 1.08c. Android 10.
![photo_2021-01-20_14-26-50](https://user-images.githubusercontent.com/63154584/105168762-a121cb80-5b2b-11eb-8bbd-60dac7e219c6.jpg)

**Comment by PhilippC** [comment]
what did you enter in directory. can you try /home/[username]?

**Comment by pohmeloid** [comment]
I entered path like that "/documents/base.kdbx". It works fine using ftp connection.
Tried to enter "/home/[username]" and got an error about java or something.
But just for a last try i copied path from filezilla client (it was something like that sftp://user@userurl:userport/tmp/mnt/2fa2d705-41f2-d611-00a3-d30541f2b601/documents/base.kdbx) and it worked!
Thanx anyway! =)
