### ISSUE TITLE
Invalid Composite Key - New v2.0 .keyx File Not Supported Yet?

### ISSUE THREAD

**Issue by kahrbomb** [PhilippC/keepass2android#1550]
I just cycled my password and key for my Keepass DB. I went to update the key and open the database on my Android phone with Keepass2Android 1.08c-r1 and I receive this message: "Invalid composite key!"

I triple checked everything and the only conclusion I can come to is that this is the first time I have tried to use a 2.0 key file and it may not be suppoted by the app.

![image](https://user-images.githubusercontent.com/29842199/105643268-d6e0f000-5e5c-11eb-9a1a-64a3163aa394.png)

**EDIT: I have confirmed that returning to a v1.0 KEY file resolves this issue in the app. It appears that my version is not compatible with v2.0 KEY files.**

**Comment by PhilippC** [comment]
this is implemented in 1.08d: https://play.google.com/apps/testing/keepass2android.keepass2android
