### ISSUE TITLE
Invalid Composite Key

### ISSUE THREAD

**Issue by LeRoyB657** [PhilippC/keepass2android#1551]
I'm using KeePass 2 on a PC and share my file via Dropbox with my Android phone using LinageOS 17.1 on a Google Pixel XL. I'm not using a Keyfile at the moment. This morning I could not open my database and received an error Invalid Composite Key. I created a new database with Keepass2android to Dropbox and the file is unreadable to KeepPass 2. KeepPassDX seem to have the same issue.

**Comment by PhilippC** [comment]
I have two thoughts: 
1.) can you try to open the local backup (select "Change database" on the password screen, then enable "Show local backups")
2.) how do you transfer the files between mobile device and PC?

**Comment by LeRoyB657** [comment]
Hi, tried that it still doesn't work. I have the database on Dropbox. All of my devices log into my Dropbox account since I'm only using it on one device at a time, I don't worry about sharing conflicts.
 
FYI, I also tried to open the file with her tablet, which is running OEM Android. I have the same problem also. So, I don't think it's problem with LineageOS.

On January 25, 2021 7:45:50 AM EST, PhilippC <notifications@github.com> wrote:
>I have two thoughts: 
>1.) can you try to open the local backup (select "Change database" on
>the password screen, then enable "Show local backups")
>2.) how do you transfer the files between mobile device and PC?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PhilippC/keepass2android/issues/1551#issuecomment-766791413

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PhilippC** [comment]
hard to say what's going on. Does KeePass on Windows also say Invalid key for the db created on the phone? Does the password contain any special characters (e.g. I just got reminded that μ e.g. has two different Unicode representations)?

**Comment by LeRoyB657** [comment]
Yes I created a database using my phone, and I get an invalid key trying to
open it. No I'm not using any special characters just alpha numeric.

**Comment by PhilippC** [comment]
sorry I'm basically stumped. It might be something trivial like Caps lock on the PC or something like this. But if it's the same for KP2A and keepassDX on the phone the DB is ok. Dropbox seems like a reliable method to transfer the data.

**Comment by LeRoyB657** [comment]
Thanks for trying anyway, I'm not sure why it just suddenly stopped working. I updated the OS to the latest patch. I thought the problem might be using a De-Googled phone, but my wife's Nook tablet is experiencing the same behavior.

 

On January 26, 2021 3:31:20 PM EST, PhilippC <notifications@github.com> wrote:
>sorry I'm basically stumped. It might be something trivial like Caps
>lock on the PC or something like this. But if it's the same for KP2A
>and keepassDX on the phone the DB is ok. Dropbox seems like a reliable
>method to transfer the data.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PhilippC/keepass2android/issues/1551#issuecomment-767809238

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LeRoyB657** [comment]
Hi, So, an interesting thing happened. Since it seems that an impasse occurred on resolving the problem, I decided to tryout Bitwarden with a free account, until this could be resolved. I opened my database to create an export file to load into Bitwarden, and it started giving me a Master Key error. Which is crazy because I could open the file yesterday. Fortunately I had created an export CSV file when the problems had started with Keepass2andriod. I created a new database in KeePass 2 and then exported that into a XML file that Bitwarden specifies as the import format a KeePass database.  The interesting thing is that the newly created database will now open in Keepass2andriod. So, perhaps there was some sort of file corruption involved. Although it seem strange that it seemed to fail so slowly. I would have thought that a corrupted file would not have been readable by any version of KeePass. I’m  not sure what that means, but I thought you might find it useful. At least you can mark the issue closed on your bug log. Sent from Mail for Windows 10 From: PhilippCSent: Tuesday, January 26, 2021 3:31 PMTo: PhilippC/keepass2androidCc: LeRoy Bainbridge; AuthorSubject: Re: [PhilippC/keepass2android] Invalid Composite Key (#1551) sorry I'm basically stumped. It might be something trivial like Caps lock on the PC or something like this. But if it's the same for KP2A and keepassDX on the phone the DB is ok. Dropbox seems like a reliable method to transfer the data.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by PhilippC** [comment]
ok, thanks for the update!
