### ISSUE TITLE
Develop Turkish Keyboard character set

### ISSUE THREAD

**Issue by utaru** [PhilippC/keepass2android#1552]
Please add "c, ç, i, ı, ş, s, g, ğ, u, ü, ö, o" character in default Turkish keyboard. (Good sample : swiftkey microsoft)

In default  Turkish keyboard is same as English keyboard. But as we type in Turkish, we need that  "ç, ı, ş, ğ, ü, ö" charter frequently. Now we type slow.

If it could be specialise as i said, it would be better.

**Comment by PhilippC** [comment]
Sorry, I decided not to develop the keyboard any further. It is not meant as a replacement for any "real" keyboard, it should only provide the "Username" and "Password" buttons. The querty is there for cases where you want to quickly type a URL or so without changing keyboards, but should usually not be required.
