### ISSUE TITLE
[Bug] pCloud connection hangs

### ISSUE THREAD

**Issue by Musiphilos** [PhilippC/keepass2android#1553]
On The latest version, I'm able to login to GDrive but not pCloud. The rotating loader stays there forever. No error message is displayed.

**Comment by cbouyer** [comment]
+1

**Comment by PhilippC** [comment]
please switch to https://play.google.com/apps/testing/keepass2android.keepass2android, it's fixed there

**Comment by Musiphilos** [comment]
![Screenshot_2021-01-27-00-11-21-588_keepass2android keepass2android](https://user-images.githubusercontent.com/5774905/105923460-4b21bc00-6034-11eb-8f99-de1c849d3777.jpg)

Thank you. After login I cannot navigate folders, and there is something funny about the design there (image above)
