### ISSUE TITLE
TOTPs and Application Names

### ISSUE THREAD

**Issue by Silun** [PhilippC/keepass2android#1554]
Hi, I am a new user of KP2A and have a couple questions/suggestions.

1. When searching for credentials from within an app, KP2A will look for something like `com.AppName.android.apps.adm` which never finds the entry for `AppName`, unless one adds the AndroidApp1 field to specifically tie the entry to that app. Would it be possible to make KP2A just regex the `AppName` part out of the longer name and look for that _if_ the long version doesn't get any hits?
2. Password and TOTP fields always ask whether I want to copy the TOTP or toggle its visibility. 100% of the time, I want to copy this TOTP. There are 3 dots to the right of every field, and sure enough the menu contains the very same options. This is quite redundant, is there a way to make KP2A always copy a password I touch, and have everything else be in the dot menu?
3. When I autofill some credentials, most services ask for TOTP after the account and password have been submitted. Could KP2A automatically copy the TOTP (if it exists) to the clipboard after credentials have been autofilled? As it stands right now, I need to enter KP2A again, find the entry, hit the password, hit copy, and switch back to the app. A lot of time could potentially be saved!
4. For those people who use the notification to copy login and password, would it be possible to add a TOTP field so that we can copy that as well without opening KP2A again and copying the TOTP manually?

Thank you for your work!

Edit: I see that for some accounts, the TOTP already shows up in the notification (4.), but it does not show up for other accounts. Weird. Is there a way to force it to show up?

Edit2: Another slight improvement idea - maybe there could be an option to have KP2A open the search bar when it is opened manually, because 99% of the time somebody is going to want to search anyway. And if not, they can just press on the group they want to look at. Just something small that came to mind :)

**Comment by PhilippC** [comment]
there are a couple of good suggestions here, but I need different issues here to keep track of all of this. So I'm closing this and kindly ask you to open new issues for the individual points.

However for 1.) I don't think there is a reliable way of getting an entry name from a package name. Not every package name follows the schema you describe.

2./3. please search for existing issues, there might be something related.

4. + Edit: If you can provide a reproducible test case (e.g. a test database) that would be awesome.

Edit 2: You can enable this in the app settings already.
