### ISSUE TITLE
PCloud storage type is not working

### ISSUE THREAD

**Issue by nicogress** [PhilippC/keepass2android#1555]
PCloud account login does not work using PCloud option when opening a new database.
However, it is possible to connect to the PCloud account with the HTTPS Webdav option using the following URL: "ewebdav.pcloud.com" ("e" means "Europe"). This option does not work if two-factor authentication is active on PCloud.

**Comment by PhilippC** [comment]
it should work with https://play.google.com/apps/testing/keepass2android.keepass2android
