### ISSUE TITLE
Allow to change created timestamp of entries

### ISSUE THREAD

**Issue by soybeansrabbitowl** [PhilippC/keepass2android#1557]
## Summary
The new feature is to change the timestamps of entries.

- Created

## Examples

Here is an example how it could look like.

There is a plugin for KeePass (Windows).
https://github.com/JanisEst/KeePassTimestampChanger

KeePassTimestampChanger

![68747470733a2f2f61626c6f61642e64652f696d672f6b3135737369352e6a7067](https://user-images.githubusercontent.com/78264930/106358342-fa4be500-630b-11eb-8cc2-cda2241a4199.jpg)
![68747470733a2f2f61626c6f61642e64652f696d672f6b3230717362732e6a7067](https://user-images.githubusercontent.com/78264930/106358343-fc15a880-630b-11eb-862b-492429e7cb51.jpg)

## Context
I have created over 300 logins but the timestamps are wrong and I want to change it.

It could work like this tap in an entry on "Created" then select what you want to change e.g. date then Android Date picker appears.
![Screenshot_2021-01-30-16-30-07-713_com mixplorer_1](https://user-images.githubusercontent.com/78264930/106360499-012d2480-6319-11eb-9bfa-06453c3bfe75.jpg)

If time then Android Time picker appears.
![IMG_20210130_163041](https://user-images.githubusercontent.com/78264930/106360511-0a1df600-6319-11eb-8a23-26e7a2e7bcd7.jpg)

**Comment by PhilippC** [comment]
In my understanding this is a very rarely used feature. As I'm trying to keep the app "simple" (it already has lots of features) I am not going to implement this unless it receives more attention or you add information why this is important on a regular basis. For rarely used features, please use the PC version.
