### ISSUE TITLE
Copy to clipboard not working in KeyPass android 

### ISSUE THREAD

**Issue by MaggieHolmes** [PhilippC/keepass2android#1558]
Copy to clipboard has stopped working in KeyPass2 android..any help sorting this would be appreciated..it was ok yesterday..

**Comment by PhilippC** [comment]
the app hasn.t changed, but maybe your OS has or you installed something to your devices?

**Comment by MaggieHolmes** [comment]
Thanks Philipp..I've tried to copy to clipboard today and it's working now..I don't think I've changed anything, the wonders of technology!!
Many thanks for your assistance. Kindest regards Margaret.
