### ISSUE TITLE
Drive instead of DS Cloud

### ISSUE THREAD

**Issue by robertzuber** [PhilippC/keepass2android#1559]
Synology ds cloud will outdate on Android with next DSM 7.0. There will be only "Drive" left. At the time KeePass can not synchronize with it. To open this possibility would be important for a million Synology users. Thanks a lot in advance! 
Robert

**Comment by PhilippC** [comment]
do you have a link to this "drive" feature and how it could be accessed?

**Comment by robertzuber** [comment]
Dear PhilippC

Thanks a lot for reply! "Synology Drive" works together with Synology NAS. It's an android app where you can remote view your team folders and instantly download/open what you need.
Meanwhile I found a solution. It's possible to mark some files as "offline", e.g. the *.kdbx for example and the fitting masterkey. Synology Drive - Apps bei Google Play<https://play.google.com/store/apps/details?id=com.synology.dsdrive&hl=de_CH&gl=US>
And it brings it back properly to the server after changing and saving the database. It's a little bit tricky the first time (what to open first, database or masterkey), but it syncs back correctly.

So thanks for all your works and kind regards,
Robert

Von: PhilippC <notifications@github.com>
Gesendet: Montag, 1. Februar 2021 20:39
An: PhilippC/keepass2android <keepass2android@noreply.github.com>
Cc: robertzuber <rozu@live.com>; Author <author@noreply.github.com>
Betreff: Re: [PhilippC/keepass2android] Drive instead of DS Cloud (#1559)


do you have a link to this "drive" feature and how it could be accessed?

-

**Comment by vepman** [comment]
Maybe you can use Webdav.
So i use it and it works nice.

**Comment by PhilippC** [comment]
I agree that using Webdav is the best option. In addition to that, KP2A can open local files - the cloud apps should provide an option to sync a file to local (if they don't, maybe FolderSync can help). KP2A cannot work with each indvidual cloud app :-(
