### ISSUE TITLE
Unable to choose local files on Android 11

### ISSUE THREAD

**Issue by wehrich** [PhilippC/keepass2android#1561]
Since my Samsung tablet upgraded to Android 11, I seem to be unable to pick a local database or key file. When I select either "System file picker" or "Get from third party app", it appears that the app attempts to launch the file picker which immediately crashes. After 3 attempts I get the message that "Files" keeps crashing. I'm on 1.08d.

Having looked through issues already reported here, I take it that there isn't a general incompatibility with Android 11 and that it works fine for other users?

Let me know, if I can provide additional information.

**Comment by PhilippC** [comment]
This sounds like a more general issue with your device. Can you try to use another app and report if file picking works there, e.g. KeepassDX?

**Comment by wehrich** [comment]
Hi Philipp

 

Thanks for picking this up.

 

I had tried KeepassDX as well when I submitted the issue and it didn’t work either.

However, for some reason, now the file picker seems to be working OK again (in Keepass2Android as well as DX). Perhaps the issue was on the side of the Files app, which may have received an update in the meantime.

 

Christian
