### ISSUE TITLE
Android自动填充密码的时候希望能设置填充用户名或者密码，自动提交希望可以增加开关，有一部分APP无法使用自动填充，希望能选择将密码在悬浮窗显示。方便抄写。

### ISSUE THREAD

**Issue by SJJ-dot** [PhilippC/keepass2android#1563]
Android自动填充密码的时候希望能设置填充用户名或者密码，自动提交希望可以增加开关，有一部分APP无法使用自动填充，希望能选择将密码在悬浮窗显示。方便抄写。

**Comment by PhilippC** [comment]
please re-create in English.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Android自动填充密码的时候希望能设置填充用户名或者密码，自动提交希望可以增加开关，有一部分APP无法使用自动填充，希望能选择将密码在悬浮窗显示。方便抄写。

_Auto-fill password hope to be able to set the fill username or password, auto-submit hope to be able to add a switch, there is a part of the APP can not use auto-fill, hope to be able to choose to display the password in the hover window. Convenient for copying.._
