### ISSUE TITLE
When auto-filling the password, I hope to be able to set the user name or password to be filled. The automatic submission hopes to add a switch. Some APPs cannot use auto-filling. I hope that the password can be displayed in the floating window.  Easy to copy.  

### ISSUE THREAD

**Issue by SJJ-dot** [PhilippC/keepass2android#1564]
When auto-filling the password, I hope to be able to set the user name or password to be filled. The automatic submission hopes to add a switch. Some APPs cannot use auto-filling. I hope that the password can be displayed in the floating window.  Easy to copy.

**Comment by PhilippC** [comment]
As far as I understand, this is not possible in Android. Please use the built-in keyboard for cases where Autofill does not work.
