### ISSUE TITLE
Android 10: Cannot save Database in Nextcloud??

### ISSUE THREAD

**Issue by kangaroo72** [PhilippC/keepass2android#1565]
Added a new entry in Keepass2android

Error-Message:

`Quelldatei konnte nicht gespeichert werden: Permission Denial:opening provider androidx.core.content.FileProvider from ProcessRecord{384e3e19854:keepass2android.keepass2android/u0a278} (pid=9854,uid=10278) that is not exported from UID 10461.Erneut speichern oder verwenden Sie das Menü "Synchronisieren", sobald die Datei wieder verfügbar ist`

**Comment by PhilippC** [comment]
please do not use the Nextcloud app (or any other local file storage thing), use the built-in Nextcloud support (File open - Nextcloud)

**Comment by kangaroo72** [comment]
Thx @PhilippC
