### ISSUE TITLE
Some software has their own built-in keyboard, and there is no way to use the keepass keyboard, hoping to display the password on the floating window

### ISSUE THREAD

**Issue by SJJ-dot** [PhilippC/keepass2android#1566]
Some software has their own built-in keyboard, and there is no way to use the keepass keyboard, hoping to display the password on the floating window

**Comment by PhilippC** [comment]
what do you mean with "floating window"? Autofill prompt? Notification entry?

**Comment by SJJ-dot** [comment]
![IMG_20210218_214937](https://user-images.githubusercontent.com/15243969/108366393-487d4580-7233-11eb-8314-29fbb3f24e87.jpg)
like this.
This is the floating window displayed when Baidu Map is running in the background。

![IMG_20210218_215257](https://user-images.githubusercontent.com/15243969/108366758-b0cc2700-7233-11eb-9e9b-4e56c4e167d1.jpg)

Android permissions

**Comment by 3Goldjungen** [comment]
@SJJ-dot What happens if you longclick on the space key on your keyboard? On my phone I will get a dialog to choose another keyboard.

**Comment by SJJ-dot** [comment]
This is an input panel inside the APP. It has nothing to do with the system input method and cannot use auto-fill or paste. At this time, you need to display the password stored in the keepass in the floating window...
![IMG_20210310_130525](https://user-images.githubusercontent.com/15243969/110582619-6b9e7380-81a7-11eb-8f90-bf44ad6b0dbf.jpg)

**Comment by PhilippC** [comment]
please report this as in issue in the target apps instead.
