### ISSUE TITLE
Autofill

### ISSUE THREAD

**Issue by FuzzyBear69** [PhilippC/keepass2android#1567]
I'm getting the Autofill prompt, a good thing,  except now I dont have to sign in. It no longer asks for your site or long password before being able to put your username and password on the site or app.

**Comment by PhilippC** [comment]
can you please report which version exactly you are using (Settings - About) and send a screenshot to explain what you mean?

**Comment by FuzzyBear69** [comment]
1.08d-r1

**Comment by FuzzyBear69** [comment]
As soon as I open my Chase bank app, it already has keepass2android entry for Chae available without me having to log into the keepass2android database.

**Comment by PhilippC** [comment]
1.08d-r1 is not very recent. Please try with 1.09a-pre1 (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by PhilippC** [comment]
assuming this is fixed

**Comment by FuzzyBear69** [comment]
Yes. Fixed
