### ISSUE TITLE
Where does one go to "reset" the "Autofill" settings? 

### ISSUE THREAD

**Issue by JeffSchre** [PhilippC/keepass2android#1568]
I was on a site that I have a database entry for, instead of hitting the "Fill with Keepass2Android" option I inadvertently hit the "Disable autofill for: "....where are these selections stored and how does one clear them?

**Comment by pascallj** [comment]
Happened to me as well some time ago: Keepass2Android settings -> App Settings -> Password Entry Access -> Autofill service -> Disabled Autofill targets.
