### ISSUE TITLE
File association issue

### ISSUE THREAD

**Issue by pjc123** [PhilippC/keepass2android#157]
I have been using the program for a couple months without any issues, but starting yesterday I began having a problem where I would click on various things like a libreoffice doc file, or a url link to Amazon in an email for instance, and doing so brings up the keepass2android app instead of the appropriate app.  It doesn't even ask me what app I would like to use.  However this is an intermittent problem as sometimes everything works OK.

Keepass2android version = 1.03
Android version = 7.1.2 (Lineage 14.1-20171124-NIGHTLY-osprey)

**Comment by PhilippC** [comment]
usually you can edit the "defaults" for an app in Android's app settings. If you clear them for KP2A, you should at least be prompted which app to use.
The problem here is that Keepass databases don't have their mime type which makes it difficult to create a precise filter.

**Comment by pjc123** [comment]
There is an "Open by default" settings option for KP2A, but nothing is set, so all options are grayed out.  Oh well, it is what it is I guess.
