### ISSUE TITLE
"Invalid Composite Key" on databases with keyfiles created with KeePassXC 2.6.4 [1.08d-r5]

### ISSUE THREAD

**Issue by rfilmyer** [PhilippC/keepass2android#1570]
It appears that some change in KPXC 2.6.4 may have broke compatibility with KP2A 1.08d-r5. I noticed my database (which uses a keyfile) wasn't able to be unlocked, and testing it again with a new database + keyfile pair also didn't work.

However, a database without a keyfile seems to work as expected.

I am attaching a test database with a keyfile that I was unable to open with the app (but opens fine with KPXC). The password to the database is `test123`.

[test kpxc 2.6.4 - pw test123.zip](https://github.com/PhilippC/keepass2android/files/5967842/test.kpxc.2.6.4.-.pw.test123.zip)

**Comment by PhilippC** [comment]
Can you please double check that you are running 1.08d-r5 using settings - about? I can open the file just fine with that version (but cannot in previous versions).

**Comment by rfilmyer** [comment]
Well, I can't screenshot it, but I can confirm that I am on 1.08d-r5.

I'd need to set up Android Studio on this computer but I can try and get a logcat or something if that helps.

**Comment by PhilippC** [comment]
you can enable debug logging inside of the app but I doubt this will give so much information. The issue can also appear if you don't transfer the files correctly to the mobile device. How did you get them there? Can you save your test database and keyfile on Dropbox and try to open from there?

**Comment by rfilmyer** [comment]
I transfered via MTP, I will try on Dropbox. (FWIW I was first experiencing the issue on Google Drive)

**Comment by rfilmyer** [comment]
Confirming that I am unable to load the test database with key using Dropbox sync as well

**Comment by rfilmyer** [comment]
Upon further testing, I too am able to open that test file no problem when transfered over MTP or synced from Dropbox (and I honestly wonder what my issue was from before)

As a final test, I will check if I am able to open this file using the exact same workflow I use for my normal DB (synced over Google Drive, locally stored key)

**Comment by rfilmyer** [comment]
That works as well. I will inspect the debug log to see if there are any clues for the issues on my personal keepass DB, and if I don't find any hints I will close.
