### ISSUE TITLE
Autofill on Firefox

### ISSUE THREAD

**Issue by Ufinator** [PhilippC/keepass2android#1572]
Hello! I'm using Firefox Nightly and if i want to login with the Autofill function, it will not work. On some website it works, but on most websites it doesn't will fill the informations. Is there already a Solution or is this bug already known?

**Comment by PhilippC** [comment]
can you please give examples of websites where it does not work? And can you please specify what exactly happens or what not?

**Comment by PhilippC** [comment]
and please indicate exactly which app version you are working on. BTW Firefox Autofill is buggy and bug reports should probably go to their tracker.

**Comment by Ufinator** [comment]
I'm using Firefox Nightly 210214 17:02 (Build #2015793291)

(I'm using this, because the autofill is on the normal version too not working and i want to see, if future updates of Firefox will fix that.)

And this is the Bug:
The KeePass App want to autofill it (with the Window). I choose the correct Login Data and click it. Keepass2Android is closing the App but don't fill anything... No fields are filled.

But there are a little few sites, where the Autofill is working. But mostly, it doesn't work. For example: I can't use autofill on cloudflare or my own cloud.

**Comment by PhilippC** [comment]
please answer 
> and please indicate exactly which app version

**Comment by Ufinator** [comment]
oh, nvm! I got an Update where the Autofill has been fixed. Everything is fine now! Sorry for that issue, it's working now ^^
