### ISSUE TITLE
Allow "Import Database to Internal Folder" for Content URIs

### ISSUE THREAD

**Issue by AlexaaGit** [PhilippC/keepass2android#158]
Great app implementation and UI... I would have thought that any local database could be Imported to local folder, which is what I would really like to do. I was able to get a newly created database to import, but that is it. But that doesn't help me unless I want to manually retype info from existing database to the newly created database. Something I would rather not do. I would like to take any database which is already created and import it to secure local folder. I even tried to trick app by naming database same name as newly created database and located in same folder as where newly created database was created but didn't work. Hopefully this is something that can easily be debugged and fixed.  Thanks in advance.

**Comment by PhilippC** [comment]
If you can have a third party app that returns a file path instead of a content URI, the feature will work. I have assigned this issue for the 1.05 version to be fixed.

**Comment by AlexaaGit** [comment]
Appreciate the quick response. Yes, using a third party file picker I had instead of the internal system file picker worked to allow importing the database to internal folder. Great job! Hope you enjoyed the beer donated under different id. Keep up the good work... Thanks.
