### ISSUE TITLE
pCloud sync strange behaviour

### ISSUE THREAD

**Issue by Musiphilos** [PhilippC/keepass2android#1580]
Using version 1.08d-r5.
After successfully login in into my pCloud via Keepass2android I get to the attached screen with strange appearance and no content
![Screenshot_2021-02-20-10-48-24-475_keepass2android keepass2android](https://user-images.githubusercontent.com/5774905/108593037-300f4700-7369-11eb-9d64-679162d23390.jpg)

There is no scroll content. Just what is displayed on that image.

**Comment by PhilippC** [comment]
Looks a lot like you didn't read the message popping up after selecting pCloud? KP2A only gets access to the folder Applications/Keepass2Android, so you need to put your file there.
