### ISSUE TITLE
Autofill issues in Android 11+

### ISSUE THREAD

**Issue by magarto** [PhilippC/keepass2android#1582]
I use a samsung galaxy S10+ and since I upgrade to Android 11, autofill plugin is not working properly.
After several time I have to unselect and select again the Keepass2android Autofill plugin service in the autofill system setting, otherwise there is no pop up to select the password in Chrome.
I tried changing several battery optimizations to let Keepass2android runs without limitations.

**Comment by PhilippC** [comment]
IMO this is an issue with Chrome, it.s reported for other password managers as well, e.g. https://github.com/bitwarden/mobile/issues/1276

**Comment by magarto** [comment]
Ok, thanks
