### ISSUE TITLE
Forget master password

### ISSUE THREAD

**Issue by mazzo86** [PhilippC/keepass2android#1591]
Hi, I use your app to save all my password.
I am able to enter by biometric recognition (by my fingerprint), but I can't enter by digit the password cause I can't Remember It. 
Is there a possibility to reset It using the biometric recognition or what can I do? 
If I loose or broke my phone I'm scared to loose all the passowrds.
Thanks

**Comment by pzoupis** [comment]
If you go to Settings/Database there is an option "Change master key" that doesn't require the current master password.

**Comment by mazzo86** [comment]
thanks to your advice I was able to fix the problem.
:)

________________________________
Da: Pantelis Zoupis <notifications@github.com>
Inviato: domenica 28 febbraio 2021, 17:44
A: PhilippC/keepass2android
Cc: mazzo86; Author
Oggetto: Re: [PhilippC/keepass2android] Forget master password (#1591)


If you go to Settings/Database there is an option "Change master key" that doesn't require the current master password.
