### ISSUE TITLE
Unable to link to pCloud ("Session expired, please login")

### ISSUE THREAD

**Issue by TBG-FR** [PhilippC/keepass2android#1593]
Same issue as @Darkilen in #1257

Description: when I try to open a kdbx file on pCloud, the pCloud "linking" screen appears, but after entering my credentials and hitting the "Login" button, it loops infinitely and a red banner displays "Session expired, please login".

Phone: RealMe 7 Pro
Android version: 10
K2A: **1.08d-r5** (also tried with **1.09a-pre1**)
pCloud version: **3.2.0** (USA ?)

Many thanks in advance for your help!

**Comment by PhilippC** [comment]
is this still the case? For me it is working?

**Comment by Darkilen** [comment]
It's working for me with `pcloud` integration.
I don't remember when I migrate from `ewebdav` to `pcloud` integration.
