### ISSUE TITLE
keepass2android doesn't appear to work correctly with the database on an SMB mount

### ISSUE THREAD

**Issue by robertwhitton** [PhilippC/keepass2android#1596]
I share my keepass database via SMB - using a VPN connection when operating remotely.

Hardware: GalaxyS9. SMB share is mounted/made visible via the "My Files" app as "Network Storage"

Latest version of keepass2android as available on the play store.

Whilst I can open the database with keepass2android it throws out some sort of file access error (very long, not on the screen for long and unable to screen grab - lack of permissions). Subsequently I find that the app doesn't appear to work correctly - as a minimum it doesn't appear to save settings. The app has write permissions to the SMB share, so that's not the issue.

**Comment by PhilippC** [comment]
can you please try with 1.09a-pre1 from https://play.google.com/apps/testing/keepass2android.keepass2android?

**Comment by PhilippC** [comment]
closing as no response
