### ISSUE TITLE
Steam TOTP stopped working

### ISSUE THREAD

**Issue by dwoffinden** [PhilippC/keepass2android#1597]
I use KeeTrayTOTP-style fields, and I see the "TOTP Seed" and "TOTP Settings" (30;S) fields, but no longer the TOTP.

Glancing at the code, it looks like TrayTotpPluginAdapter.GetTotpData should, if Settings[1] == "S", set res.Encoder to TotpData.EncoderSteam here, instead of interpreting it as Length:
https://github.com/PhilippC/keepass2android/blob/7df048263bfc4ff2dd6c12985a47de6aa5bb290e/src/keepass2android/Totp/TrayTotpPluginAdapter.cs#L119

I think this was broken in https://github.com/PhilippC/keepass2android/commit/7df048263bfc4ff2dd6c12985a47de6aa5bb290e, it worked before. Prior to that, TOTPProvider just took the Settings from TotpData, so the above didn't matter, but now it takes TotpData itself the Encoder field needs setting:
https://github.com/PhilippC/keepass2android/commit/7df048263bfc4ff2dd6c12985a47de6aa5bb290e#diff-4f2e6a5d12500fa6d9d2a23fa331b39d9e401b7487fca7e5525821bd29df8fbbL117

Sadly it looks like getting this app building myself might take a while :sweat_smile:
Thanks for the app!

(note to self: it looks like https://github.com/PhilippC/keepass2android/blob/6cc007e47e2902f90ac698385618ba3cfc12d757/src/keepass2android/Totp/KeeWebOtpPluginAdapter.cs ought to work in the meantime)

**Comment by PhilippC** [comment]
thanks for the hint, will be fixed with 1.09a-pre2 (https://play.google.com/apps/testing/keepass2android.keepass2android), I hope I find time to release it this week

**Comment by dwoffinden** [comment]
Thanks a lot!
