### ISSUE TITLE
Location of the key file

### ISSUE THREAD

**Issue by mboltz** [PhilippC/keepass2android#1598]
Hi,

When I select to NOT store name and path of my key file, the one to unlock my password safe (in combination with the password), I still see the path of the location of the previously used key when I choose Android file browser. That seems not very wise, especially when for example my correct key file is the only file in that directory. I know I can put other files in there as well in order to misguide a hostile adversary. But still, this is a risk in my opinion. I'd say the whole option of not storing the file's name and path is getting a bit useless this way.

Don't know if there is means to not start browsing inside the previously used directory when opening the system's own file browser... But maybe it's worth a thought.

Regards,
Mac

**Comment by PhilippC** [comment]
KP2A cannot prevent the Android file browser to remember which folder you have opened recently from KP2A.
