### ISSUE TITLE
Enhancement: easier way to add notes

### ISSUE THREAD

**Issue by Safari77** [PhilippC/keepass2android#160]
Now when pressing the ➕ , you have choice of adding user/password or group.
I use k2a also to add notes.  So the new feature could be icon 🗒 when pressing ➕, and with these features:

- does not ask or display username/password/url, override url
- doesn't say "entry available through kp2a keyboard" for the notes

**Comment by PhilippC** [comment]
there is already a template "Secure note" available. It does not show username etc. It does make the entry available to the keyboard, however, because that can be useful.

**Comment by Safari77** [comment]
Oh well. I had deleted the templates some time ago 😄
I don't know how to add a new template, so I did ```Add templates to database``` and edited one of them... now I have a Note template.  But instead of ```Standard entry``` / ```Note``` selection, it would be nice to have direct entries when I press ➕ since I have only three: Group, Note, Standard entry.
