### ISSUE TITLE
Locked out of my other NON-Yubikey database

### ISSUE THREAD

**Issue by pmcl77** [PhilippC/keepass2android#1605]
I have setup a new keepass database for testing it with yubikey, so far everything worked. However, I can now no longer access my original (untouched, this db should still be password only) database anymore. Even thoug I unselect the keyfile option it tells me the composed key is not valid.

**Comment by PhilippC** [comment]
can you try to open the local backup of the old database?

**Comment by pmcl77** [comment]
Hi Philipp

Is there a local backup on android?

I ended up having to restore a backup from my NAS. Strange enough, recent backups also failed even though those backups were created before I even tried the yubikey with keepass, which makes absolutely no sense. I had to recover a backup from mid january. 

I did get the feeling that when switching from a "PW + CR" database back to a "PW only" database, keepass2android would still tell me the composite key is wrong and that was maybe, what corrupted my original pw only database.* Doesn't explain though why even Keepass on my desktop had the same issues with the more recent backups of my database.

**Comment by PhilippC** [comment]
there is a local backup, but if your restored backup was put in the same place as the original file, it's now overwritten with the restored data. Select "Change database" and enable "Show local backups" to see those. Closing this as it seems ok now.
