### ISSUE TITLE
Unable to access local keyfile on Android 11

### ISSUE THREAD

**Issue by ejeffrey** [PhilippC/keepass2android#1607]
I just got a new phone that shipped with Android 11.  I have my database stored on dropbox and keep the keyfile locally.  In the past I have installed the keyfile by copying it from my desktop over USB and then selecting the file with a file browser.  When I tried that this time, I get a permission denied, presumably due to the new android file permissions.  I couldn't find a location to install the file (other than a completely public area like downloads) that was accessible both to the file browser and keepass2android.

I fell back to using SFTP, however while there is a cached key file it is trying to fetch over SFTP every time.  I deleted the file from the target location and while it still works from the local copy it displays an error message on every unlock.

I'm not sure what the best way to handle this is.  Are the app-private storage arenas accessible via USB?  Is there a way to browse them to select a key?  Or an option to download a key once and then use it locally?  I would even be happy to manually enter the key in hex when setting up the phone.  

It would be good to have some better and clearer options here, or even just some documentation on how to use the keyfile better.

**Comment by PhilippC** [comment]
can you 
*  please test if this works better with 1.09a-pre1 (https://play.google.com/apps/testing/keepass2android.keepass2android)
*  import the keyfile to app local storage through the app settings after loading it via SFTP?

**Comment by gn4711** [comment]
Had same issue. But only when I select with external app. When using Android Filebrowser it is working

**Comment by PhilippC** [comment]
closing as no reply
