### ISSUE TITLE
How to force login via Fingerprint? 

### ISSUE THREAD

**Issue by Svenny2** [PhilippC/keepass2android#1611]
Friends, my daughter is using Keepass 1.08c on her Android phone and used to open the database by fingerprint. All of a sudden it asks for the password - obviously she doesn't remember her password anymore :-( Is there a way to force opening by fingerprint (again)? It stopped after the last Android update.
Many thanks in advance,
Sven

**Comment by devlern** [comment]
You can enable the biometric unlock under database options, when you login to the app hit the three dots button on top right and choose Settings, then Database settings, then hit Biometric unlock

**Comment by Svenny2** [comment]
Thanks for your reply. Unfortunately there is no three dots button on the top right, only the one on the top left is available. In this menu, she can click on settings but then database settings is greyed out because she cannot open that database.

We're searching for a way to force biometric unlock in general, maybe she needs to downgrade or re-install an older version of this app?

Thanks again, Sven

**Comment by ei-ke** [comment]
Hello Sven,
have you tried opening older versions of the DB? Maybe some local backups that K2A creates (can be found on the bottom of the switch database page)?
I don't know the exact mechanism, but the biometry option can only be enabled on an unlocked DB. Never used this feature, but I'd assume that it would derive some kind of keyfile from the biometry system of the Android device that will be placed into the DB encryption settings as an alternative to using a plain password. So my guess would be that a) the DB file has been corrupted or b) something changed the way the biometric system of the device works (though I think this would only happen when replacing the device with another one - so I'd never use a biometry only protection (not sure if this is even possible)) or c) one of the recent updates broke the function.
In case c) you can install [older releases](https://github.com/PhilippC/keepass2android/releases) (you nee to enable installing apps from unknown sources. Please disable "installing apps from unknown sources" after you are done trying the older versions!)

I sincerely hope that you regularly created backups of the DB.

Cheers,
Eike

**Comment by kugeekpotet** [comment]
Hello Sven,

Unfortunately, to enable biometric unlock you need to unlock the database first (which isn't possible if you are locked out).

However, if you regain access: Once you're inside the database, tap on the three dots menu on the top right, then choose Settings > Database > Biometric unlock > Enable full Biometric Unlock. This option will store an encrypted version of the master password on the device, which is protected using biometric authentication - this makes it possible to unlock everytime using your fingerprint sensor.

Regards,
Hao

**Comment by PhilippC** [comment]
Unfortunately, as stated in the docs and also explained inside the app when you have enabled biometric unlock, you need to remember the master password. Biometric unlock can be disabled by the OS, there is nothing KP2A can do about it.
https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md

**Comment by Svenny2** [comment]
> Hello Sven,
> have you tried opening older versions of the DB? Maybe some local backups that K2A creates (can be found on the bottom of the switch database page)?
> I don't know the exact mechanism, but the biometry option can only be enabled on an unlocked DB. Never used this feature, but I'd assume that it would derive some kind of key from the biometry/security system of the Android device that will be placed into the DB encryption settings as an alternative to using a plain password. So my guess would be that a) the DB file has been corrupted or b) something changed the way the biometric/security system of the device works (though I think this would only happen when replacing the device with another one - so I'd never every use a biometry only protection (not sure if this is even possible)) or c) one of the recent updates broke the function.
> In case c) you can install [older releases](https://github.com/PhilippC/keepass2android/releases) (you nee to enable installing apps from unknown sources. Please disable "installing apps from unknown sources" after you are done trying the older versions!). In case a) and b) I sincerely hope that you have backups of the DB.
> 
> Cheers,
> Eike

Thank you Eike. We tried all your tips but without success. The local backups also request the password to be entered and do not allow biometric unlock. Then we installed both an old version and the newest version of KPA but no change, therefore I assume it's actually the OS (like PhilippC has stated before) that disabled biometric unlock after installing the latest updates. 
My daughter decided to start a new database and renew all her passwords. I'm sure that she will learn from this incident.
Thanks anyway for all your replies, much appreciated!
Sven

**Comment by ei-ke** [comment]
@Svenny2 I personally prefer using biometrics only for quick unlock. Thus you are also typing the master password regularly which trains the muscle memory. Takes a few dozen times and you'll type it without thinking about it :)
