### ISSUE TITLE
Unable to sync DB with pCloud

### ISSUE THREAD

**Issue by Ip3rFra** [PhilippC/keepass2android#1614]
Hi,

I'm trying to use pCloud to sync the KeePass database with multiple devices. When I try to do this on KP2A I get a generic "Authentication failed" error and it won't let me proceed.

I've tried deleting the app data and moved the DB to the given path.

**Comment by PhilippC** [comment]
which version of the app are you using exactly? Can you please try to update to 1.09a-pre1 (https://play.google.com/apps/testing/keepass2android.keepass2android) and try again. If you see the toast message again, please try it one more time.

**Comment by PhilippC** [comment]
thanks for the feedback and the hint. I have fixed it on https://crowdin.com/translate/keepass2android/33588/en-it?filter=basic&value=0#q=Applications
