### ISSUE TITLE
White text on light background

### ISSUE THREAD

**Issue by dtwitkowski** [PhilippC/keepass2android#1616]
A recent update causes white text to appear on a light background.  This breaks search, and I've also seen an issue where Dark theme causes white text on the pull down menu.

![Screenshot_20210321-092520_Keepass2Android](https://user-images.githubusercontent.com/59034880/111912655-d82b3500-8a27-11eb-9d09-4b38ee8e4c39.jpg)

**Comment by PhilippC** [comment]
is this a Samsung device?

**Comment by PhilippC** [comment]
if you think this is caused by an app update, can you check with an older version from https://github.com/PhilippC/keepass2android/releases?

**Comment by dtwitkowski** [comment]
> is this a Samsung device?

Yes, it's a Samsung Note 20 Ultra running OneUI 3.1.  Is there a known issue with Samsung devices?

...dtw

**Comment by wiscor** [comment]
I had this issues after transferring data and apps from Google Pixel to a Samsung S21.  I opened the Keepass2Android App properties and cleared cache and storage and then reopened database and everything works fine.

**Comment by jsoberg** [comment]
I've also observed this issue on my Samsung Galaxy S20 FE (SM-G781U1/DS). I'm using version 1.08d-r5 of the app, off of Google Play.

**Comment by M4xZ** [comment]
Same for me. Both Samsumg S20 and S21.
It wasn't like that at the beginning when I installed the app.
Reinstalled the app and it was solved.  Waiting to see whether it comes back again.

**Comment by PhilippC** [comment]
just realized this is a duplicate of https://github.com/PhilippC/keepass2android/issues/1435
