### ISSUE TITLE
Autofill for website logins works only with Firefox

### ISSUE THREAD

**Issue by bege10** [PhilippC/keepass2android#1620]
I tried Firefox, Privacy Browser (from F-Droid repo), Brave and Ungoogled Chromium.
K2A is Android autofill service.
System is e/OS based on LineageOS for microG Android 10.
Only in Firefox the autofill popup shows up. If I tap on the K2A button on the K2A keyboard K2A looks for the package name, not for the URL.
Is this something that can be enabled in K2A or must this be done in these browsers?

**Comment by PhilippC** [comment]
these browsers need to implement support for Autofill. To use the keyboard, you should choose "Share URL" from the browser's menu and then select KP2A. See https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md
