### ISSUE TITLE
Cannot synchronize (merge changes) database to KP2A app folder in Onedrive

### ISSUE THREAD

**Issue by ultimateboarder** [PhilippC/keepass2android#1621]
I'm getting an error message saying that the changes cannot be merged. I am unable to screenshot this as the app prevents screenshots. The situation is that I make a change to the database on my PC, then if open the KP2A android app and update/change anything and try to save it asks if I want to merge changes or overwrite. Of course, I don't want to overwrite, so I try to merge, but then get this error. When checking the database from the PC, the android app updates do not show. It seems there is something going on, perhaps with permissions? I am using a Oneplus 6 on Android 10, with the current version of the KP2A app.

**Comment by PhilippC** [comment]
can you please check the file path to the file if you select "Change database" on the password/unlock screen? Does it start with "content://", "onedrive://" or "onedrive2://"?

**Comment by PhilippC** [comment]
Can you please check if the behavior is different in 1.09a-pre from https://play.google.com/apps/testing/keepass2android.keepass2android?

**Comment by ultimateboarder** [comment]
Okay, I downloaded the preview and on initial tests, it does seem to have resolved the issue :)
