### ISSUE TITLE
Incorrect auto filling of login+pass on bank site

### ISSUE THREAD

**Issue by stalingraddd** [PhilippC/keepass2android#1625]
I'm using latest 1.09a-pre1 version on Android 10 (Samsung S20, no root)

When I press the auto fill button to enter my login/pass on this site https://wb.micb.md/way4u-wb/ ,
both login and password fields are filled with my login (expected behavior - login field gets filled with my login, password field with my password)

So every time i have to manually switch to keepass keyboard and manually press the login/pass buttons to correctly enter the data.

![Screenshot_20210326-160648_Chrome](https://user-images.githubusercontent.com/18533380/112643743-5b47f300-8e4d-11eb-9d41-a6c7175122af.png)

**Comment by PhilippC** [comment]
it seems like this webpage is doing a few things to prevent autofill from working. Please report the issue there.

![grafik](https://user-images.githubusercontent.com/5421734/112811744-a6941880-907c-11eb-9859-1d507a3ad76a.png)
