### ISSUE TITLE
Can't access database after transferring data from old phone to new phone

### ISSUE THREAD

**Issue by Almenon** [PhilippC/keepass2android#1626]
I transferred my files from my pixel 2 to my new pixel 4a5g using the standard Google transfer mechanism for a first time setup of a new phone (just connecting the two phones together via USB)

Now when I try to access the database at content://com.android.externalstorage.documents/document/primary%3Akeepass.kdbx I get keepass2android.io.documentaccessrevokedexception. same thing with the local backups.

Fortunately I still have my old phone so I'll try re-copying my keepass file to the new one.

**Comment by PhilippC** [comment]
the app data is not backed up to Google servers for privacy reasons. You need to transfer the database files manually to the new phone.

**Comment by Almenon** [comment]
I did transfer the database manually. That's how you do it with pixel phones, you transfer the data via the usb cable.

**Comment by Almenon** [comment]
I worked around the issue by transferring the specific file manually instead of using googles transfer mechanism.
