### ISSUE TITLE
Recover master password

### ISSUE THREAD

**Issue by wjp99** [PhilippC/keepass2android#1627]
I've been using fingerprint access on pixel 2 for a long time, and now realize I no longer remember the master password.  I want to upgrade my phone, but will need the password.   Since i can open the database with my finger print, is there any way to see the master password??
You're help would be appreciated.  I have visions of having to go through and write them all down.

**Comment by kugeekpotet** [comment]
If you still have access to your database through biometric unlock, you can change your master password by going into Settings > Database > Change master password.

**Comment by wjp99** [comment]
FABULOUS!!!

Thank you so much!

I was losing sleep over losing access.

Wayne
