### ISSUE TITLE
Steam TOTP broken

### ISSUE THREAD

**Issue by gab** [PhilippC/keepass2android#1628]
Not sure when it happened, but my Steam TOTP set up with KeeTrayTOTP doesn't work anymore in KP2A. I used to have a TOTP field available in the KP2A keyboard when this entry was selected - not anymore. And I tried every other field.

I haven't changed this database entry in ages, either. The TOTP still works with KeeTrayTOTP.

**Comment by PhilippC** [comment]
will be fixed in next release on https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by gab** [comment]
Thanks!

> will be fixed in next release on https://play.google.com/apps/testing/keepass2android.keepass2android

Do you mean I have to get the unstable version if I want the fix now? I'd rather stay on stable to avoid running into other problems, do you have an ETA for the official Play Store release of the fix?
