### ISSUE TITLE
TOTP broken? 

### ISSUE THREAD

**Issue by Offerel** [PhilippC/keepass2android#1634]
I'm using 1.09-pre1 currently. If I search an entry with TOTP field's before this version, i had a TOTP button in the notification. But with this version, the button is not available.

The entry has working TOTP field's saved.

**Comment by mendhak** [comment]
This may or may not be related but you could try it.  
I had a similar issue - some of my phones had the 'Copy TOTP' button in notification, and some didn't.  

My display size, in the OS app settings, was set to smallest.  I set it back to normal, and the button appeared.  So this could be related to DPI/display size/density.

**Comment by PhilippC** [comment]
I'm closing this due to the explanation of mendhak. Please re-open if it is still present
