### ISSUE TITLE
When storing more than one database on the same Dropbox account you can use single quick unlock to unlock all the databases

### ISSUE THREAD

**Issue by twdziki** [PhilippC/keepass2android#1635]
Sorry if the names of functionalities don't match exactly, I'm not using English version of the app.

Repro steps:

1. Have more than one database stored on a single Dropbox account
2. Have quick unlock active
2. Open all of your databases
3. Lock the app, e.g. through notification screen on your phone
4. Open the app and enter the quick unlock code for the most recent database

Result: All the databases that you've opened previously are open again.

App version: 1.08d-r5
I have a Samsung phone with Android 11.

**Comment by PhilippC** [comment]
this is intended behavior. QuickUnlock is a "UI lock" and having each database in a different locked/quick-locked/open state would make things difficult both for users and developers.
