### ISSUE TITLE
New Android 11 Device Keeps Locking Database

### ISSUE THREAD

**Issue by CaptainPackers** [PhilippC/keepass2android#1636]
Since I am working from home and never go anywhere, I have my database set to never lock. However, on my new Samsung S21 running Android 11 the database is locked nearly every time I try using Keepass2Android. I am never prompted for the Quick Unlock, even though I have this enabled. This is particularly troublesome because I use a rather lengthy password, because I sync with desktop Keepass, and I hate typing on my miniature phone keyboard.

**Comment by PhilippC** [comment]
there is another setting "lock database on screen off" which you might check. Another reason might be aggressive "battery optimization" settings (from which you should exempt KP2A). It's not an issue with Android 11 in general.

**Comment by CaptainPackers** [comment]
Thanks for the quick reply. Seems to be working as expected now
