### ISSUE TITLE
Improvement creation of personnal data

### ISSUE THREAD

**Issue by michael5428p** [PhilippC/keepass2android#1640]
It Will be fine to have thé possibilité to create an entry in keepass for personnal data and thé do an automatique fullfill field for personal data like :
Name
Firstname
Adress
Zip code
Country
Téléphone 
Mail

**Comment by PhilippC** [comment]
please use this plugin on the PC to setup a template for such data:
https://github.com/mitchcapper/KPEntryTemplates

KP2A is compatible with these templates.

**Comment by michael5428p** [comment]
Hello,

Thank you for tourisme Amsterdam.
Is there a similar plugin for Android ?
We manage the keepass via our mobile.

Thanks
Michael

**Comment by PhilippC** [comment]
KP2A works when you have such templates as part of your database, but doesn't have a feature to setup such templates, sorry.
