### ISSUE TITLE
FRITZ!NAS and kbdx file

### ISSUE THREAD

**Issue by RasputinBerry** [PhilippC/keepass2android#1648]
I would like to use the kbdx file on a USB stick on the Fritz Box. The SmartPhone is connected to the WLAN home network. The file can be seen in the Windows file manager but not in the KeePass2 path FRITZ! NAS. What's wrong ?

**Comment by PhilippC** [comment]
KP2A does not support SMB (https://github.com/PhilippC/keepass2android/issues/82, Windows file shares), but it supports FTP which is also available on your Fritz.box.
