### ISSUE TITLE
Authentication to Nextcloud fails if Password contains special characters

### ISSUE THREAD

**Issue by ClaraCalumna** [PhilippC/keepass2android#1649]
If i try to open a database from nextcloud (20.0.9) using a password that contains ß the connection to nextcloud fails. (401) 
If i remove ß from the password the same connection works.
Connecting to nextcloud directly via Webdav works if the password contains ß so it is a Bug in keepass2android.
This may also affect other special characters from german language like ß,ä,ö,ü

**Comment by PhilippC** [comment]
duplicate of https://github.com/PhilippC/keepass2android/issues/478
