### ISSUE TITLE
Google Drive Synchronization with a Trashed file appears like nothing is wrong.

### ISSUE THREAD

**Issue by NumbGnat** [PhilippC/keepass2android#165]
This is sort-of an odd situation.

When I load Keepass on my PC, it's configured to open a kbdx file in the local file structure created by Google Drive Sync.  Sometimes when I attempt to close Keepass on my PC, it tells me that the .tmp file is locked and won't let me save the database.

In those cases, I have always just saved as a different file and cleaned up manually.

I had one of those occurrences happen last week and evidently, I was in a hurry and didn't rename the saved kbdx back to the original name.  However, I had deleted the original file, so it was in the Trash folder in Google Drive.

I realized this today because I had edited a few entries from KP2A and they weren't showing up on the desktop.  I examined the desktop to see that it was still using the temporary name I had saved it as.  I checked KP2A and it was still referring to the original name.  I had made several changes this week from KP2A, so I was trying to figure out where it was updating to, as that file didn't exist in Google Drive.  It never gave me an error, so I assumed everything was fine.

So I exported from KP2A and synchronized with the PC file, making sure not to lose any entries, and proceeded to debug.

What I eventually found was that the old file I had deleted, was still in the Google Drive Trash.  Even so, KP2A was reporting that the file opened properly, synchronized properly, and saved properly when changes were made.

I think because KP2A kept updating this file, it simply remained in the trash because it wasn't getting older.  Either that, or I caught it before it was permanently removed.

I emptied my Google Drive Trash and attempted to reopen the file from KP2A.  This time it gave me the "unable to open file" error.  Until then, KP2A gave me no notice that I was making new entries in and synchronizing with a file that was actually deleted according to Google Drive.

I'm not sure if you can detect the file's state of being in the trash folder, but you might want to add a notice to that effect, before some other poor user gets bitten by this and doesn't have a backup of changes that were made while the file was sitting in Google Drive's Trash...

**Comment by paradoxon82** [comment]
I think I have a similar issue. 
My keepass2 file is saved to a Google Drive account
A new entry that I created on my phone did not show up on the desktop, even when google drive says everything is synched.
On the phone:
Selecting "Synchronize Database" shows that everything is in synch.
Then I closed the Database, and selected it anew in google drive.
Now I see that it does not have the new entry.
When I look at the list of databases, I seem to have a duplicate entry
They are indistinguishable on first look, but one is the real file in google drive, without the new entry.
And one is some "ghost" file that contains the new entry.
