### ISSUE TITLE
Question: how KP2A store password in phone when fingerprint option is enabled?

### ISSUE THREAD

**Issue by rustforfuture** [PhilippC/keepass2android#1658]
May you please write about this in documents of repo?

How much ut is secure? (Apart from the fact that some laws let biometric passwords forced to get but can't do it with normal ones or physical access and such)

I want to know if hashed password will get saved in phone or plain text of it?

And howuch this feature is secure in different versions of android? (6+ , 7+, 8+, 9+, 10+ and newer versions?

Also how much vendors are forced to do standard hardware based storage (cpu based)?

I mean how much google pressure them to do store biometric info in standard secure way provided by phone SoC? And from what version they are forced to do so? (If they are forced)

Thank you very much and sorry for asking question in issues.

Best regards.

**Comment by PhilippC** [comment]
KP2A uses Android's KeyStore to encrypte and save the master password itself. This is required for biometric unlock to work. It is not storing the masterpassword if you only use it for QuickUnlock.
