### ISSUE TITLE
Something wrong with Keepass2droid stable and onedrive

### ISSUE THREAD

**Issue by aasutossh** [PhilippC/keepass2android#1660]
It wanted me to authenticate everytime I wanted to open a closed database that was stores in onedrive.

Installed beta, worked flawlessly. Would you look into it? I will be using beta for a while now.

**Comment by PhilippC** [comment]
this is fixed in beta, so I don't see a reason for this to be an issue here :-)

**Comment by aasutossh** [comment]
Thank you for your work. Cheers.
