### ISSUE TITLE
Sync spinner not cancelable

### ISSUE THREAD

**Issue by djechelon** [PhilippC/keepass2android#1662]
Today I had an issue related to network connectivity. I'll speak about the video in the end.

# How to reproduce

1. Set up Keepass2Android to "know" a remote SFTP password file. I used biometric authentication but it doesn't really matter. Step 1 makes sure that K2A has a cache of the file
2. Mock network to be **particularly slow/unresponsive**. I was under 4G in an area where you can't watch SD live TV. Some kind of a "fake" 4G or just too much traffic
3. Now open K2A and log in to the password file, e.g. by typing password
4. K2A will open a modal spinner to tell that it is loading the remote file to ensure the cached copy is consistent
5. **Try to "back", it won't work**

I couldn't go "back" and I had to kill the application from drawer in order to regain control.

Device and OS: Pixel 5 with AOSP 11.

On my second attempt I made a video by screen recording, but that time the network resumed operation so while you **could** see that you can't "back" from that spinner, it took a few seconds to sync.

I am not sure about the timeout of the operation. I had quickly looked at the source code but I can't find the name of the "main" activity. I would love to post a video, but I'd really prefer to amend several _useless_ personal information being displayed (including the SFTP urls of known files)

**Comment by freedayko** [comment]
![Screenshot_20210913-162329370](https://user-images.githubusercontent.com/488760/133092524-31b57c82-6be9-4ad0-8f61-8f3a9b1ec97c.jpg)
I have a similar problem too
When I unlock my device while it syncing it viewed as in screen... No option to cancel. Just I lost my changes...

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
- #1512

![Screenrecord.gif](https://user-images.githubusercontent.com/46166740/137657174-d140e4bc-66ed-46b3-b8be-4e74b16be3fc.gif)

**Comment by HolgerJeromin** [comment]
I had the same when using a hotel wifi which did not allow connection to my ssh file.
Using the cached version only would be very ok for me.

**Comment by PhilippC** [comment]
resolved in https://github.com/PhilippC/keepass2android/releases/tag/v1.10-pre
