### ISSUE TITLE
AutoFill not working

### ISSUE THREAD

**Issue by azfar** [PhilippC/keepass2android#1664]
I am on Android 10 (MIUI 12) and I installed "Keepass2Android Offline" and enabled Keepass2Android as AutoFill Service, disabbled "Battery Optimization" for the app.

I tried with Chrome and Firefox but only onetime it was able to fill the credentials but all of the time it only showing the "Fill with Keepass2Android" popup but don't providing and matching credentials (which is in the db (unlocked)). Funny thing is the entry which worked earlier is also not working anymore. Further If I choose "Disable Autofil for site" it is also not adding it to the list and "Disabled AutoFill targets" is always empty.

<a href="https://ibb.co/6BNYwDY"><img src="https://i.ibb.co/6BNYwDY/Whats-App-Image-2021-05-05-at-7-54-47-PM.jpg" alt="Whats-App-Image-2021-05-05-at-7-54-47-PM" border="0"></a>

**Comment by devmaster-st** [comment]
In Settings - Additional settings - Accessibility - Downloaded apps.
![IMG_20220118_181318](https://user-images.githubusercontent.com/20471970/149964297-7430f8a0-4266-44a8-93df-22e1c8603d91.jpg)

**Comment by PhilippC** [comment]
Autofill is improved a lot in the non-offline version. I'm currently struggling with building the offline variant. As soon as this is fixed, the improved autofill implementation will be available there as well.
