### ISSUE TITLE
connect keepass2android database with Windows Keepass2 through Google Drive

### ISSUE THREAD

**Issue by mathib** [PhilippC/keepass2android#1665]
Hi Philipp,

Thanks for this awesome app. It works flawless when syncing a Keepass database, using Google Drive, between two Android phones, but now I want to connect it with Keepass on a Windows desktop computer. I noticed that using Google Drive, the database is only accessible for keepass2android and it cannot be downloaded as a regular file ([Google Drive Application folder](https://developers.google.com/drive/api/v3/appdata)).

Do you happen to know how my Keepass desktop version (v2) for Windows can connect to Google Drive for the database made by keepass2android? Is there a specific URL that I can supply? (I noticed that my keepass2android mentions `gdrive://drive-username/keepas-android.kdbx` but that's not a valid URL according to the desktop Keepass version.)

**Comment by Gnarfoz** [comment]
You probably want this: https://www.kpsync.org/

**Comment by treee111** [comment]
in my opinion you only need th Google Drive desktop application to sync all your files in Google Drive to your desktop PC.
Then, you can edit or show the .kdbx file with Keepass, KeepassXC etc. on Windows, macOS etc.

**Comment by PhilippC** [comment]
the database is not stored in an app folder. You can sync it with 
Google's "Backup and Sync" or use KPSync.
