### ISSUE TITLE
White Background with white Font

### ISSUE THREAD

**Issue by muellela** [PhilippC/keepass2android#1669]
Hello,

I have a serious issue.  In the searchfield are previews "White on white"? See Photo attached. 

![20210511_185124](https://user-images.githubusercontent.com/84036289/117856162-91b9c000-b28b-11eb-8a3c-87fc6aad0720.jpg)

**Comment by PhilippC** [comment]
duplicate of #1616

**Comment by muellela** [comment]
Deleting Cache and Data fine, thanks a lot. FYI, Device was a Samsung S20 with OneUI 3.1
