### ISSUE TITLE
Keyboard "user" button auto-submits

### ISSUE THREAD

**Issue by HairyDude** [PhilippC/keepass2android#167]
When I press the "User" button in the mini keyboard, the login form appears to auto-submit even though the password field is blank. Currently this means I am unable to log in to forums.factorio.com using the mini keyboard because phpBB clears the username field on a failed login. The same issue happened just now on Github (which doesn't clear the username field). This is with Chrome 62.

**Comment by PhilippC** [comment]
duplicate of #89
