### ISSUE TITLE
Support for KDBX 4.1?

### ISSUE THREAD

**Issue by TonyGravagno** [PhilippC/keepass2android#1670]
KeePass v2.48 introduces an update to the KDBX format. I understand KeePass itself will not save in this format until [conditions](https://keepass.info/help/kb/kdbx_4.1.html) indicate we want to use the features. I just want to be sure that when KDBX files are in the new format that k2a will be able to read/write without issue. THANKS!!!

**Comment by goldfish1974** [comment]
I second that.

**Comment by muellela** [comment]
Same here :-)

**Comment by PhilippC** [comment]
should be available from https://play.google.com/apps/testing/keepass2android.keepass2android shortly. Please let me know what you think!
