### ISSUE TITLE
Password will not open app

### ISSUE THREAD

**Issue by Tdean777** [PhilippC/keepass2android#1672]
I'm getting an error when I try to open app. I did recently update my android phone software. I was not having issues prior that I knew about. Thanks.

**Comment by PhilippC** [comment]
what error do you get?

**Comment by Tdean777** [comment]
It actually started working again.  A different file popped up and was able to get in.

I can't remember the error it went away quickly and the app wouldn't let me take a screen shot.

But thanks for getting back to me.

Tony

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
