### ISSUE TITLE
{DB_DIR} shows nextcloud credentials in URL

### ISSUE THREAD

**Issue by simonkurka** [PhilippC/keepass2android#1674]
When using {DB_DIR} in a Nextcloud database the credentials are shown in the URL field unencrypted and even unmasked.
Maybe other connectors are affected aswell.

It's the same configuring a child database saved in Nextcloud.

Is this intended?

**Comment by PhilippC** [comment]
this placeholder is resolved with all information required to open a file so you can use it to specify relative paths, e.g. in AutoOpen. If this is not what you intend to do, either move the URL to a hidden extra field or enter the path explicitly?
