### ISSUE TITLE
Improvement Suggestions

### ISSUE THREAD

**Issue by Frazzle1** [PhilippC/keepass2android#1682]
Using my fingerprint to unlock your app is clunky. With all my other apps the field entry boxes automatically recognize my fingerprint when I touch my phone. With your app there is this extra step where I have to tell keepass I'm going to use my fingerprint to enter my credentials. Older versions didn't have this extra step which I find annoying. Also sometimes I need to reset my fingerprint recognition in my phones settings. After doing this Keepass will no longer recognize my fingerprint and I have to use my text password to open your app and reset your app to recognize my password again. My other apps that use my fingerprint don't do this. Also why is there not a button to simply close the database from within the opened app, why can I only lock it and then only get to a close option by reopening the program or going to the locked notification?

**Comment by PhilippC** [comment]
this is too many things at once. KP2A needs to encrypt the master key with biometrics, that's different from a pure unlock. KP2A should show the biometric prompt immediately, but as you reported in another issue, you are also using a Yubikey where it's assumed you first present this. If you always want to close instead of lock, disable QuickUnlock.

**Comment by Frazzle1** [comment]
Ok it's still a bit cumbersome but if it improves the biometric security then it's something I can live with. Thanks for the tip about QuickUnlock but it would still be nice if there was an option to close the database completely from within the program with QuickUnlock enabled. The database would only get locked if the program was exited without selecting the option to completely close the database.

⁣Sent from BlueMail ​
