### ISSUE TITLE
Unable to access the database (Error - Operation is not supported on this platform)

### ISSUE THREAD

**Issue by Akhilesh-T** [PhilippC/keepass2android#1685]
Hi,

I updated to the latest beta version **1.09a-r0**, but now I'm unable to open the database.

Check out this image: 

<img width="318" alt="R6TRyJF6TV" src="https://user-images.githubusercontent.com/80357467/118620570-3fc0ef00-b7e3-11eb-9fd8-baf979576278.png">

**Comment by derflasher** [comment]
Same problem here!

**Comment by roedel1** [comment]
duplicate of #1679

**Comment by mannvomdeich** [comment]
Duplicate of #

Thanks for your help!

**Comment by PhilippC** [comment]
closing as duplicate of #1679
