### ISSUE TITLE
Very slow store/sync operation

### ISSUE THREAD

**Issue by guiyou65** [PhilippC/keepass2android#1686]
Hello,
I'm a Keepass2android user for long. My database is stored on GDrive and shared with other devices including linux PC. For a few month the synchronisation and save operations take a very long time. It is quite the same with an ownCloud storage.

**Comment by PhilippC** [comment]
how large is the kdbx file?

**Comment by guiyou65** [comment]
Yes the file got very big, almost 9 MO when it usually was between 2 an 3 MO ! 
I found a history parameter in KeepassXC/Linux that was 6MO for history !
I decreased it to 3 and now my database is 2.8MO again.
Much more quicker to open and synchronise, but I still feel it long in comparaison with what I recall.
But I may be wrong in my appreciation..

**Comment by PhilippC** [comment]
it's still a large file. I consider this the reason for slowness.
