### ISSUE TITLE
Cannot connect to Cloudamo's Nextcloud WebDAV service

### ISSUE THREAD

**Issue by dshanks01** [PhilippC/keepass2android#1690]
keepass2android 1.08d-r5 on Android 11

I'd like to store my keepass database on a free Nextcloud service provided by Cloudamo. I am not self hosting this server, so have very limited ability to change the server configuration.

When I attempt to open a database stored in my Cloudamo Nextcloud I get this error message: 

> Cannot connect to file provider service 
Received unexpected response: 
Response{protocol=h2, code=401, message=, url=https://us.cloudamo.com/remote.php/webdav

I believe the URL is correct because when I use it in a web browser I get the following response:

> This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.

That response leads me to believe that URL is Cloudamo's NextCloud WebDAV interface.

To recreate the problem:

- Set up a free Nextcloud account at us.cloudamo.com (this isn't actually necessary - see below)
- In keepass2android select Open another database...
- Tap on Open file...
- Tap on Nextcloud
- Enter the Nextcloud login data:
** Nextcloud URL is us.cloudamo.com
** username is your Cloudamo username (or a dummy username - see below)
** password is your Cloudamo password (or a dummy password - see below)
- Tap on OK
- See the error message shown above.

In fact, you can see the same error message using a dummy username and password. It appears that the error occurs before authentication.

Has anyone run across similar problems? I have been able to use Nextcloud to store my keepass database when I was self hosting, but my internet connection is far too flakey to rely on for access to my passwords.

EDIT: I've discovered the Cloudamo's WebDAV URL (which is not configurable) for these accounts is `https://us.cloudamo.com/remote.php/dav/files/<username>/`. Unfortunately, the keepass2android Nextcloud WebDAV URL also appears not to be configurable. It is always `<User entered URL>/remote.php/webdav`.

It would be nice if keepass2android allowed for the entry of the entire WebDAV URL instead of assuming that the WebDAV URL is the URL the user enters + "/remote.php/webdav."

**Comment by PhilippC** [comment]
can you access this webdav share with any other webdav client?

**Comment by dshanks01** [comment]
Good guess. When I try to connect to it with ANY webdav client (from my phone, at least), the connection fails. I will close this issue.

**Comment by dshanks01** [comment]
Appears to be an issue either with Cloudamo's server or with my phone. The problem occurs when I attempt to use any WebDAV client on my phone to connect to Cloudamo's Nextcloud service.
