### ISSUE TITLE
Linking a password object to many auth entries

### ISSUE THREAD

**Issue by cabbagemaan** [PhilippC/keepass2android#1692]
It would be useful if you could create a password item/object that could then be linked to many authentication  entries. Example many usernames are used for the same account password (federated auth & local):
mcabbage@some.federated.domain.com
localdomain\mcabbage
Cabbage.Maan@vegetable.garden.nearby.org

Password: sauerkraut6969

This way changing your password would only ever really need to occur once.

**Comment by WebworkrNet** [comment]
Using the same password several times, even with different user names, makes little sense in my opinion from a security point of view.

**Comment by PhilippC** [comment]
this is possible with references (https://keepass.info/help/base/fieldrefs.html), but please note that this is currently prevented by https://github.com/PhilippC/keepass2android/issues/1327
