### ISSUE TITLE
Error with version 1.09a-r0

### ISSUE THREAD

**Issue by FranziPoldy** [PhilippC/keepass2android#1693]
I have keepass2android version 1.09a-r0 on my mobile (LG K30 model: LM-X320ZMW).  I think this is the first time I;ve used it because it gave  the version history.  On trying to open my kdbx database, I get the message: "An error occured. Operation is not supported on this platform".  Previous versions worked on this mobile.  The kdbx is in Dropbox.  Keepass on my laptop accesses this file and is working OK.

**Comment by andreasbaum123** [comment]
Update to version 1.09a-r1.

**Comment by FranziPoldy** [comment]
Thank you.  That fixed it.
