### ISSUE TITLE
Autofill no longer working under Nougat

### ISSUE THREAD

**Issue by SanguiniusWept** [PhilippC/keepass2android#17]
I have Autofill selected in the KP2A app, KP2A On in Accessibility Settings, and as far as I can tell the keyboard is turned on in the system (since I can use it), but I get no Autofill prompts after updating to 7.0. Actually, I don't seem to get any sort of notification prompts, either for the Autofill or for the "Password is available for..." that I got under 6.0. Is there an additional step that must be completed before I can get these to work the way that they worked in 6.0?

**Comment by PhilippC** [comment]
can you please check if this is solved in the beta? https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by jeroen7s** [comment]
for me i can get them in nougat, however about half a second after i pull down the notification tray they disappear, and when i push the notification tray back up, the notification comes back, like the notification tray is blocking keepass2android from detecting the login form

**Comment by PhilippC** [comment]
@jeroen7s  I just analyzed a logcat of another user with the same behavior. On his system, the notification drawer was in the package com.android.launcher3 instead of com.android.systemui. Do you know if you have the same thing installed or running? If you can collect a logcat, I can see if it is launcher3 or something different. Can you please check?

**Comment by jeroen7s** [comment]
weirdly enough, the problem disappeared, it seems to come back sporadically sometimes.
I'll try to do a logcat when it pops up again, but when i try to do a logcat now (now that it works again) the notification channel seems to be com.android.systemui

**Comment by jeroen7s** [comment]
just noticed something else, when i type a key on my keyboard (swiftkey in my example), regardless of key, including backspace and then slide down the notification tray with the autfill notification, it disappears, untill i leave the app i'm trying to login to and then open it again, then the autofill notification appears again

**Comment by PhilippC** [comment]
@SanguiniusWept did you get a chance to test this with the current beta? If it does not work, can you please collect a logcat?

**Comment by PhilippC** [comment]
please re-open if you're still having issues.
