### ISSUE TITLE
When opening file: third-party app not showing in app picker

### ISSUE THREAD

**Issue by Yemono** [PhilippC/keepass2android#171]
I am trying to access a database file which is hosted on my Synology NAS, to which I have access through the "DS file" app. After selecting Open file > Get from third-party app, the app picker dialog only shows a narrow selection of apps like Gallery, Audio Recorder, Google Drive, and not the app I want to use for accessing the database file. 

K2A app version: 1.03
Phone used: Xiaomi Redmi 4A, MIUI Global 5 Stable 8.5.5.0
DS file app version: 4.10.5

Theoretically, I could open access to the NAS through other protocols (WebDAV, FTP), but I would prefer not having to open it up just for the db file, especially when access through "DS file" is secure and works flawlessly.

**Comment by PhilippC** [comment]
I don't think there is anything wrong with the intent I am firing:

```
Intent i = new Intent(Action.GetContent);
i.SetType("*/*");
i.AddCategory(Intent.CategoryOpenable);
```

please reach out to the Synology support on this.
