### ISSUE TITLE
KeePass2Android erfordert YubiKey - hab ich nicht

### ISSUE THREAD

**Issue by Atzler** [PhilippC/keepass2android#1718]
hi, Philiipp,

seit längerem nutze ich KeePass, auf PC und Android. Habe auch schon Biere überwiesen. Android nutzte ich dank Corona seit längerem nicht mehr, jetzt verlangt das nach erkanntem Passwort einen YubiKey.
Ich habe keinen.
Muss aber unterwegs an meine Passwörter kommen.
Wie kann ich vorgehen?

Liebe Grüße aus Karlsruhe
Diethard Atzler

**Comment by PhilippC** [comment]
wenn du nur ein Passwort ohne Yubikey für die Datenbank verwendest, solltest du auf dem Passwort-Bildschirm die Option "Nur Passwort" auswählen, dann sollte auch nicht nach Yubikey gefragt werden!

**Comment by Atzler** [comment]
so einfach - stimmt.

 

Danke!
 

Mit freundlichen Grüßen

Diethard Atzler
____________________________________

 

 
 

Gesendet: Samstag, 03. Juli 2021 um 12:15 Uhr
Von: "PhilippC" ***@***.***>
An: "PhilippC/keepass2android" ***@***.***>
Cc: "Atzler" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [PhilippC/keepass2android] KeePass2Android erfordert YubiKey - hab ich nicht (#1718)


 

wenn du nur ein Passwort ohne Yubikey für die Datenbank verwendest, solltest du auf dem Passwort-Bildschirm die Option "Nur Passwort" auswählen, dann sollte auch nicht nach Yubikey gefragt werden!
