### ISSUE TITLE
Can I push the values-zh-rCN localization file directly？

### ISSUE THREAD

**Issue by x-Ai** [PhilippC/keepass2android#172]
I have been constantly modifying and translating zh-rCN localization files，and I have used it for myself until recently  but I want to share it now。Because Crowdin translation is a long process, I hope you can use my translation which is named zh-rCN strings.xml directly,and be beneficial to everyone！

**Comment by PhilippC** [comment]
I think you should be able to upload the xml file to crowdin. Unfortunately pushing to the repo directly won't work as I will overwrite the file next time from crowdin.
