### ISSUE TITLE
Cannot open database via sftp: Permission denied

### ISSUE THREAD

**Issue by Firedragonweb** [PhilippC/keepass2android#1721]
When trying to connect to a database via sftp, I get a toast stating the file provider could not be connected (afc_msg_cannot_connect_to_file_provider_service) with "Permission denied" as detail. In similiar issues, the workaround is to repeat navigating to the file, but this is not possible here, since the file is remote.
What can I do?

**Comment by PhilippC** [comment]
Permission denied is what it says: I think you entered wrong credentials or used the wrong authentication method
