### ISSUE TITLE
Volume slider visible for about 20 seconds with enabled KP2A AutoFillPlugin

### ISSUE THREAD

**Issue by derandiunddasbo** [PhilippC/keepass2android#173]
Hello,

the new external KP2A accesibility service plugin seems to bring back an old issue with AutoFill, as discussed here:

http://keepass2android.codeplex.com/workitem/553

I never experienced the volume controls being visible for so long with old KP2A versions with builtin AutoFill. 

But now, with the external plugin, I can confirm the issue. When disabling the AutoFill plugin in accessibility settings, the volume slider again disappears after about 2 seconds as expected.

I'm using a OnePlus 3t, Android 7.1.1.

Best regards
Andreas

**Comment by JeGr** [comment]
Same on 7.1.1 with an OP5t - hadn't realized that it is the plug-in until after reading here.

**Comment by derandiunddasbo** [comment]
Thank you for the fast update. Version 1.02 seems to fix the issue, at least in my case. :-)
