### ISSUE TITLE
Luckycloud: Synchronization via WebDAV temporarily not possible

### ISSUE THREAD

**Issue by WebworkrNet** [PhilippC/keepass2android#1733]
According to the provider, the requests do not even arrive in these cases.

**Comment by WebworkrNet** [comment]
**Device**:
Samsung Galaxy XCover 4s, Android 10

**Comment by WebworkrNet** [comment]
Keepass2Android
Version 1.08d-r5

**Comment by WebworkrNet** [comment]
Due to #1487, I cannot provide an error log. If I can get the log otherwise, please let me know how.

I can optionally provide screenshots later.

**Comment by WebworkrNet** [comment]
As a result, the merging of the external and local Keepass DB has failed in the last few weeks, so that I then have to choose the "overwrite" option as an alternative. If the merge does work, it usually leads to a damaged file.

As long as I only have 1 device in use, overwriting is not a problem. On the other hand, there would be a problem if I were to integrate further devices in the future, which also have different processing statuses.

Sounds like #1703.

**Comment by WebworkrNet** [comment]
Could be related to #1029.

**Comment by PhilippC** [comment]
what do you do and what error do you get? Does the title of this issue mean that there is currently/temporarily an issue at the Luckycloud side?

**Comment by WebworkrNet** [comment]
**Update:** 
Since version 1.09a-r3 I have observed that merging no longer causes any problems. Since I tried merging for the first time a few days ago and have been testing since then, it may be too early for a final assessment.

**Comment by WebworkrNet** [comment]
> what do you do and what error do you get? 

I am making a change to a record, which results in synchronization. So far, I have not been able to determine whether it only affects certain changes. But I think it's more of a general problem.

**Comment by WebworkrNet** [comment]
> what do you do and what error do you get? Does the title of this issue mean that there is currently/temporarily an issue at the Luckycloud side? 

![20210812_101346](https://user-images.githubusercontent.com/43509007/129165122-70537fc4-c651-4d89-86c8-f3c3d523017c.jpg)
![20210812_102913](https://user-images.githubusercontent.com/43509007/129165137-6c03be97-14d3-492f-b956-3559a8ac01b5.jpg)

I shortened the error message because the URL contains confidential parts.

**Comment by WebworkrNet** [comment]
> Does the title of this issue mean that there is currently/temporarily an issue at the Luckycloud side?

When asked, Luckycloud support informed me that they could not find any failed contact attempts via WebDAV. In my opinion, this rather indicates that the problem is already with the connection being established by the app and not with the provider.

**Comment by PhilippC** [comment]
is the latest screenshot from 1.09-r3 (meaning it still occurs)?

**Comment by WebworkrNet** [comment]
1.09-r3 did _not_ fix the problem.

**Comment by WebworkrNet** [comment]
The synchronisation problem has not occurred for weeks "in favour" of bug #1762. Therefore, I am closing this ticket for the time being.

**Comment by WebworkrNet** [comment]
The issue is not over yet. As it turned out, the XCover 4S that stopped operating the day before yesterday only synchronized the last changes locally for months without me noticing. I now hope that the local kdbx files can still be restored as part of a professional data rescue so that I can import them onto the new device again.

(I also sent you an email about this.)

Can you recommend a cloud provider where, in your experience, synchronization runs smoothly? It is probably faster and more practical to change the cloud provider in this case. If I understood that correctly, the encryption of the kdbx file basically means that any cloud storage is suitable.

**Comment by WebworkrNet** [comment]
With the current synchronization (Samsung Galaxy A13 5G, Android 12) there are always connection problems with Luckycloud. The backup can then only be accessed locally again. If you then export the local backup with changes, the target file is (often) damaged. The new target file can then again not be read.

**Comment by WebworkrNet** [comment]
Since time was of the essence, I tested some other cloud providers without any feedback (no reproach!). The setup did not work with Google and Onedrive, I will not go into details at this point. Now I've landed on Dropbox and the synchronization is running smoothly so far.

**Comment by WebworkrNet** [comment]
@PhilippC I would still be interested in your opinion/experience. 🙂
