### ISSUE TITLE
The entire password is shown after copy-paste

### ISSUE THREAD

**Issue by WebworkrNet** [PhilippC/keepass2android#1734]
The phenomenon described under #121 also occurs under Android 10 on Samsung.

It is worth considering whether it would not make sense to highlight this fact in the setup process after the installation.

As long as you keep typing letter by letter, the problem may not be that serious. If, however, in the case of Keepass2Android, the entire password is briefly displayed, then the potential danger is to be assessed much higher.

**Comment by WebworkrNet** [comment]
**Device**:
Samsung Galaxy XCover 4s, Android 10

**Comment by WebworkrNet** [comment]
![20210714_094938](https://user-images.githubusercontent.com/43509007/125584398-6878140e-6ac3-4399-811c-32031799affc.jpg)
![20210714_095040](https://user-images.githubusercontent.com/43509007/125584407-addf0453-5bd2-42aa-b1d9-9d6561cb130e.jpg)

**Comment by PhilippC** [comment]
if I understand correctly, there is a system setting to control this, and it seems more of a behavior of the target app.

**Comment by WebworkrNet** [comment]
You understood that correctly.

But I'm not sure whether you understood my request correctly.

My point is that KP2A should point out these system settings, for example during installation. It may be manufacturer-specific only for Samsung. However, devices from this manufacturer are widespread.

**Device**: Samsung Galaxy A13 5G (SM-A136B/DSN)
**Operating System**: Android 14, UI-Version 6.0

![Screenshot_20240130_224806_Settings Suggestions](https://github.com/PhilippC/keepass2android/assets/43509007/c31e22de-e062-430e-b2e7-49a1dfd0552c)

![Screenshot_20240130_224832_Settings](https://github.com/PhilippC/keepass2android/assets/43509007/d5a0d884-252b-497f-8d00-1e9950554ed2)
