### ISSUE TITLE
App freezes temporarily after database update

### ISSUE THREAD

**Issue by WebworkrNet** [PhilippC/keepass2android#1735]
Either the update finally works or the app has to be forced to close via the operating system settings.

So far, I have not been able to identify a cause why it freezes.

**Comment by WebworkrNet** [comment]
**Device:**
Samsung Galaxy XCover 4s, Android 10

**Comment by WebworkrNet** [comment]
Keepass2Android
Version 1.08d-r5

**Comment by WebworkrNet** [comment]
Due to #1487, I cannot provide an error log. If I can get the log otherwise, please let me know how.

**Comment by PhilippC** [comment]
which storage type? Can you give step-by-step instructions what exactly you are doing?

**Comment by WebworkrNet** [comment]
Same with KP2A: 1.09a-r3.

**Comment by WebworkrNet** [comment]
I am making a change to a record, which results in synchronization. So far, I have not been able to determine whether it only affects certain changes.

**Comment by PhilippC** [comment]
can you collect a log (see app settings) and provide it after this occured?

**Comment by WebworkrNet** [comment]
> Due to #1487, I cannot provide an error log. If I can get the log otherwise, please let me know how.

**Comment by WebworkrNet** [comment]
Since the error has not occurred for weeks, I am closing this issue until further notice.
