### ISSUE TITLE
Keepass2Android auf Chromebook (Lenovo) - Fingerabdruck-Sensor nicht erkannt

### ISSUE THREAD

**Issue by RKausS** [PhilippC/keepass2android#1736]
Hallo Phillipp

Keepass2Android ist ne coole Sache.
Neu habe ich mir ein Chromebook (Lenovo C13 Yoga) zuagelegt - und war verblüfft, dass Keepass2Android dessen Fingerabdruck-Sensor leider nicht erkennt. Schade.

Chromebooks sind inzwischen eine ganz gute Alternative zu Tablets oder Windows. Wäre toll wenn du dessen Fingerabdruck-Senser in künftigen Versionen von Keepass2Android implementieren könntest?

Viele Grüsse
Roman 
Schweiz

**Comment by PhilippC** [comment]
if this is not supported by AndroidX Biometric library, there is nothing I can currently do here.
