### ISSUE TITLE
java.io.filenotfoundexception was thrown

### ISSUE THREAD

**Issue by sperical** [PhilippC/keepass2android#1737]
Hi, thanks for creating this app. It is indispensable for me. I can't synchronise Keepass2 for Android with its backup file in Google Drive. I had been having a syncing problem for months previously, which I eventually found out was because the Drive app on my phone wasn't logged in. Once I logged in, that sync problem went away. About a week ago I started receiving a new sync failure message as per the title of this message.  I can't recall what the previous error message was. 

I have checked that I am logged into Drive both on the app on my phone and online. 

I have a Samsung Galaxy S20 FE 5G. Running Android 11.

Any suggestions on how to sync again?

**Comment by PhilippC** [comment]
please use the built-in Google Drive support. Re-open the file by locking & closing it, then select "Change database" - "Open file" - Google Drive and browse to the file.

**Comment by sperical** [comment]
Hi Philipp,Happy new year. 
Since the updates, I can't unlock the database using my correct password and password type combo.
I keep getting an error message stating "Invalid composite key please try again"
There was a longer message as well that I can't recall.
Before I could even get to the password stage I was instructed to fix a Google drive problem, which I did using the instructions provided (see attached)

I am using Android Galaxy S20 FE 5G.Any suggestions?
Kind regards Alison

Sent from Yahoo Mail on Android 
 
  On Mon, 19 Jul 2021 at 5:43 pm, ***@***.***> wrote:   


please use the built-in Google Drive support. Re-open the file by locking & closing it, then select "Change database" - "Open file" - Google Drive and browse to the file.

**Comment by sperical** [comment]
Hello again. An update to my email below. Now the access is revoked. At least before I was able to restore sync.
See error message. I tred to access internal cache but still won't accept my password.
I have version 1.09b-r1


Kind regards,Alison 

Sent from Yahoo Mail on Android 
 
  On Fri, 7 Jan 2022 at 11:48 am, alison ***@***.***> wrote:   Hi Philipp,Happy new year. 
Since the updates, I can't unlock the database using my correct password and password type combo.
I keep getting an error message stating "Invalid composite key please try again"
There was a longer message as well that I can't recall.
Before I could even get to the password stage I was instructed to fix a Google drive problem, which I did using the instructions provided (see attached)

I am using Android Galaxy S20 FE 5G.Any suggestions?
Kind regards Alison

Sent from Yahoo Mail on Android 
 
  On Mon, 19 Jul 2021 at 5:43 pm, ***@***.***> wrote:   


please use the built-in Google Drive support. Re-open the file by locking & closing it, then select "Change database" - "Open file" - Google Drive and browse to the file.

**Comment by sperical** [comment]
Hi, I've now submitted this request for help via your forum site. 
Kind regards,Alison 

Sent from Yahoo Mail on Android 
 
  On Fri, 7 Jan 2022 at 11:59 am, alison ***@***.***> wrote:   Hello again. An update to my email below. Now the access is revoked. At least before I was able to restore sync.
See error message. I tred to access internal cache but still won't accept my password.
I have version 1.09b-r1


Kind regards,Alison 

Sent from Yahoo Mail on Android 
 
  On Fri, 7 Jan 2022 at 11:48 am, alison ***@***.***> wrote:   Hi Philipp,Happy new year. 
Since the updates, I can't unlock the database using my correct password and password type combo.
I keep getting an error message stating "Invalid composite key please try again"
There was a longer message as well that I can't recall.
Before I could even get to the password stage I was instructed to fix a Google drive problem, which I did using the instructions provided (see attached)

I am using Android Galaxy S20 FE 5G.Any suggestions?
Kind regards Alison

Sent from Yahoo Mail on Android 
 
  On Mon, 19 Jul 2021 at 5:43 pm, ***@***.***> wrote:   


please use the built-in Google Drive support. Re-open the file by locking & closing it, then select "Change database" - "Open file" - Google Drive and browse to the file.
