### ISSUE TITLE
No merging possible

### ISSUE THREAD

**Issue by HorNet505** [PhilippC/keepass2android#1738]
I am no longer able to merge the online database with my local one. 
it says it's unavailable online which is strange because I reopened it from onedrive.
I have to deactivate local caching to use the most current database on my galaxy S20

**Comment by PhilippC** [comment]
did you use the built-in OneDrive support (File > Open > OneDrive) or did you go through the OneDrive app? Can you give more detailed step-by-step instructions to reproduce?

**Comment by WebworkrNet** [comment]
Could be related to #1733.

**Comment by HorNet505** [comment]
correct. Same issue.
Thanks for pointing out


Am Di., 10. Aug. 2021 um 11:29 Uhr schrieb Denis Müller <
***@***.***>:
