### ISSUE TITLE
Virtual keyboard not present after reinstall.

### ISSUE THREAD

**Issue by ArtlessAptyrex** [PhilippC/keepass2android#1739]
I was trying to fix a synchronization issue so I uninstalled then reinstalled "keepass2android". However, the keepass2android virtual keyboard no longer appears in the list of keyboards at the bottom of the screen.

Phone: Pixel 3 XL
Android version:  11

Keep2android version: 1.08d

**Comment by PhilippC** [comment]
I guess you need to enable it in the system settings first.
