### ISSUE TITLE
Feature request: on clipboard timeout, copy a blank string to the clipboard X number of times

### ISSUE THREAD

**Issue by thegiddylights** [PhilippC/keepass2android#1740]
Starting with version 89, Chrome OS includes a Clipboard Manager that keeps track of the last five items copied to the clipboard — _and cannot be disabled._ KP2A's own keyboard cannot be used on a Chromebook while a physical keyboard is connected to it (and cannot be used on a Chromebook running in tablet mode, which of course is a completely different issue), so perhaps the easiest remedy for this situation would be to enhance the existing clipboard timeout mechanism with an option to copy a blank string to the clipboard X number of times, thus making Clipboard Manager's presence less of a threat.

This is how Clipboard Manager's window looks after a clipboard timeout:

![Screenshot 2021-07-20 16 40 58](https://user-images.githubusercontent.com/51476859/126343920-8de47e2c-6b36-4ecb-82e6-fe7b824fb116.png)

**Comment by PhilippC** [comment]
using the Clipboard is inherently insecure. This is why the documentation recommends not to use it for sensitive information. I stopped trying to find workarounds for such scenarios as they simply don't work well enough.
