### ISSUE TITLE
Templates not showing

### ISSUE THREAD

**Issue by dekiesel** [PhilippC/keepass2android#1742]
Apologies in advance, because this must be a stupid question, but: I can't get templates to show on one of my databases.

I have a database A which has a child database B. Templates are shown when I click the add button (plus) in database B, but not when I click the add button in database A. Database A does have a "Templates" group which contains Credit Card/email/idcard/membership secure note/wifi, so I an not sure why I am not being presented with a choice when clicking add.

Any help is appreciated!

**Comment by PhilippC** [comment]
can you provide a reduced version of your databases (without sensitive information) which show this behavior? In my test wtih two databases, it was working fine.

**Comment by dekiesel** [comment]
Thanks for the reply but I don't have that DB anymore. I exported and imported to a new dB due to this issue. Thanks for your help!
