### ISSUE TITLE
No fingerprint since OS Update

### ISSUE THREAD

**Issue by n3zkwik** [PhilippC/keepass2android#1743]
Since the last update (Huawei SNE-LX1, EMUI version 10.0.0.285, Android 10) for the existing kdbx-Database is unlocking via fingerprint not possible anymore. The fingerprint sign beside the password field has disappeared.
I tried to login with my password but I have the feeling that the activation of the fingerprint changed my password. 
Is it possible to reactivate unlocking via fingerprint again without knowing the password?

**Comment by PhilippC** [comment]
The password doesn't change by activating fingerprint. Unfortunately - as the docs and the app clearly state - you do need the full password to unlock.
