### ISSUE TITLE
Please delete (remove, wipe) my kdbx file in the cloud.

### ISSUE THREAD

**Issue by CKD4XXH** [PhilippC/keepass2android#1744]
Please **do warn** the user when first sending the user's kdbx file to "the coud".
(When I realized that my data was sent to "the cloud", it was late already.)

Please delete (remove, wipe, clean) old and unused kdbx files, residing in the cloud. (I have switched to keepass2android_offline, but my data remained in the "cloud".) Additionally, delete kdbx files when the user asks it explicitely. (And give a button to do this asking. For example "wipe all my kdbx files from the cloud", or "keep this file but wipe my all other files from the cloud".)

Exactly where is/was sent my data? (What is meant "the cloud"?)

**Comment by PhilippC** [comment]
KP2A does not send data to the cloud unless you explicitly select a location in a cloud storage provider like GDrive or Dropbox, ranting the app access to that provider explicitly. I don't know why you think the app "sent" the kdbx to the cloud without you knowing about it.
