### ISSUE TITLE
TOTP secret stored by KeeWeb is not compatible with Keepass2Android

### ISSUE THREAD

**Issue by synchrone** [PhilippC/keepass2android#1745]
**Describe the bug**
When I set up a TOTP entry using KeeWeb the secret is not readable by Keepass2Android 1.09a-r3. Instead it just shows the stored 32-character secret.

**To Reproduce**

1. Create a new record with TOTP, e.g for Google 2FA
1. Store the 32-character 2FA secret
1. Save the DB
1. Open the DB with Keepass2Android
1. TOTP codes are not generated, instead the user can just see the 32-character secret

**Expected behavior**
I would expect the 2FA secrets in KDBX to be compatible with KP2A

**Reasons**
Keepass2Android expects TOTP secret value to be formatted like so
otpauth://totp/Google:<email>?secret=<32-char-secret>&issuer=Google

According to an answer in https://github.com/keeweb/keeweb/issues/1863, where I originally reported it, there's no agreed-upon way of storing 2FA keys in KDBX, but it would be nice if the apps interoperated on this.

**Comment by PhilippC** [comment]
does this format work in KeepassXC?

**Comment by synchrone** [comment]
@PhilippC KeepassXC does the URL
`otpauth://totp/default?secret=<32-char-secret>&period=<seconds>&digits=[6,8]`

**Comment by PhilippC** [comment]
I tried to understand the logic behind parsing otp fields in KeepassXC but don't see where such a key is parsed there:

https://github.com/keepassxreboot/keepassxc/blob/9b2b861a2af451eb160c3771db6453deb90cf792/src/totp/totp.cpp

**Comment by synchrone** [comment]
There're 3 modes:

1. `otpauth://` URL stored under entry attribute called `otp`. This is what KeeWeb uses.
2. Not a URL but a query string, stored under `otp`. I'm assuming this is used by [KeeOtp](https://github.com/tiuub/KeeOtp2)
3. A pair of attributes named `TOTP Seed` and `TOTP Settings` formatted like a raw value and "30;6" respectively. So-called "legacy" format. This is the one that KeePassXC 2.3.1 stores entries in.

**Comment by synchrone** [comment]
I think I found the culprit: In my testing KeeWeb inconsistently saves raw secret under `otp` attribute, depending on whether or not the user clicks away from the editing field, or presses enter to finalize manual OTP secret input. (duh)

Following the code you linked - this inconsistent behavior would store TOTP unreadable by KeepassXC 2.4.0+. However, [KeepassXC 2.3.1](https://github.com/keepassxreboot/keepassxc/blob/2.3.1/src/totp/totp.cpp#L97) (which is what I am testing against, because that's what is packaged in Ubuntu 18.04) reads it okay.

All in all, looks to me that it would be better to fix KeeWeb UI, and not KeepassXC or keepass2android.
