### ISSUE TITLE
How is default sorting defined?

### ISSUE THREAD

**Issue by WebworkrNet** [PhilippC/keepass2android#1746]
In the "Sort by... " menu, the term "default sort" is used. However, this is not defined in more detail.

**Comment by WebworkrNet** [comment]
It would be nice if the labeling was more precise.

**Comment by WebworkrNet** [comment]
![20210805_173901](https://user-images.githubusercontent.com/43509007/128379424-35a2ed42-917b-4d33-96ec-932fcb7422c2.jpg)
![20210805_173817](https://user-images.githubusercontent.com/43509007/128379433-a620019b-2e85-4037-97d8-bf6eb5f83c15.jpg)

**Comment by WebworkrNet** [comment]
Version 1.09a-r3

**Comment by PhilippC** [comment]
it's the order as it is in the file. This order can be edited in tools like KeePass2 (but not KP2A)

**Comment by WebworkrNet** [comment]
> It would be nice if the labeling was more precise.

My attention was on the inscription.
It is not clear at the moment.

Suggested text:
<code>Sort by storage order of the kbx file (default).</code>
