### ISSUE TITLE
Autofill wieder aktivieren

### ISSUE THREAD

**Issue by elias170105** [PhilippC/keepass2android#1748]
Hallo,

ich nutze das Programm Keepass2andriod seit heute und bin relativ zufrieden.

Leider habe ich ein Problem, ich habe bei einer App das Autofill deaktiviert und weiß nicht wie ich es wieder aktivieren kann, kann mir dabei einer helfen?
vielen dank.

**Comment by Rookiestyle** [comment]
Einstellungen -> Anwendung -> Passwort-Zugriff -> AutoFill-Dienst  -> Deaktivierte AutoFill-Ziele

Du siehst dann alle Apps und Seiten, bei denen AutoFill deaktiviert ist.
Entferne den Haken hinter der App, damit wird AutoFill wieder aktiviert.

**Comment by elias170105** [comment]
Vielen Dank für die Schnelle Hilfe.

**Comment by WebworkrNet** [comment]
@elias170105 Zwecks einer besseren Übersicht könntest Du bitte das Ticket schließen? Wenn ich das richtig sehe, ist Dein Anliegen ja geklärt. Vielen Dank :-)
