### ISSUE TITLE
Bug: Keepass2Android Offline attempts online

### ISSUE THREAD

**Issue by cpengr** [PhilippC/keepass2android#175]
I'm using Version 1.03 of Keepass2Android Offline on Android 7.1.2 (LineageOS 14.1-20171128-NIGHTLY-h811). When I open the app, this message appears for a few seconds, then fades away:

> Could not open from remote: Working offline.. Loaded file from local cache. You can still make changes in the database and synchronize them later.

Also, it has a "Work offline" checkbox on the "Unlock database" screen.

This is the *offline* version of the app. There should be no online/offline option, much less any attempts to connect to any remote.

**Comment by PhilippC** [comment]
please see https://github.com/PhilippC/keepass2android/issues/86 for a discussion on this.
To summarize: KP2A Offline caches files as well, and "remote" means "original file" (even if it's local).
