### ISSUE TITLE
[UX] Long entries create line breaks

### ISSUE THREAD

**Issue by WebworkrNet** [PhilippC/keepass2android#1750]
Long field entries sometimes create unsightly line breaks within a record.

A possible approach would be a new arrangement of the icons. Instead of on the left side, they could be arranged as headings.

Whether this would solve the problem completely, I don't know. At least it would alleviate the problem.

**Comment by WebworkrNet** [comment]
This screenshot is intended to illustrate the icons mentioned. I may also add a screenshot of the line break.

![20210809_190002](https://user-images.githubusercontent.com/43509007/128746771-1aaa14ce-6a8d-4cc5-8f58-b18d9f38575f.jpg)

**Comment by PhilippC** [comment]
I don't consider this an issue

**Comment by WebworkrNet** [comment]
Now here is an example of the line break.
![20210812_145514](https://user-images.githubusercontent.com/43509007/129200654-065af194-7f5a-4883-9c61-4410aed02882.jpg)
