### ISSUE TITLE
Cannot figure out how to use with a Syncthing-backed kdbx on Android 11

### ISSUE THREAD

**Issue by delroth** [PhilippC/keepass2android#1752]
(I could not find a better medium for support, hopefully using issues for this is ok. I also didn't find an exact duplicate of this, though there are variants around with other issues relating to Android 11.)

I synchronize my kdbx between devices using [Syncthing](https://syncthing.net) (and more specifically, on Android, [this app](https://play.google.com/store/apps/details?id=com.nutomic.syncthingandroid&hl=en&gl=US)). In keepass2android, I opened the file using the system file picker, navigating to the right directory and opening the kdbx. This all works great in read mode, but whenever I try to write to the database from the keepass2android app, the following error occurs:

> Permission Denial: opening provider com.google.android.libraries.storage.storagelib.FileProvider from ProcessRecord{...keepass2android...} (pid=..., uid=X) that is not exported from UID Y

As a user of these two apps, I could not find a documented way to get around this and be able to write to my database from both Syncthing and keepass2droid. Could you help me figure out whether:

- There is a usable workaround for this problem that I haven't found (maybe it's worth adding in the docs?)
- Something in keepass2android needs to be changed for this use case to work
- Something in Syncthing Android needs to be changed for this use case to work (in which case I'll move the bug over there)

Thank you!

**Comment by PhilippC** [comment]
I think the best way to solve this was if the Syncthing app could provide access through the Storage Access Framework which is ANdroid's recommended way of accessing files across apps.
