### ISSUE TITLE
[UX] label KP2A_URL_x

### ISSUE THREAD

**Issue by WebworkrNet** [PhilippC/keepass2android#1760]
I find the prefix of the label `KP2A_URL_x` somewhat unfortunate. The regular field is only called `URL`. From the user's point of view, it would make sense to have a uniform name. This would also be advantageous for any future sorting function(s). The standard field could be named URL1, for example. Further entries would then simply be incremented.

Related to #772, #1755

**Comment by PhilippC** [comment]
KP2A is using the kdbx format which defines URL as a default, I cannot change that without breaking compatibility. Actually a standard compliant way would be to duplicate the entry using references and change the URL. I think none of these solutions is great, but as long as KeePass/kdbx do not define a standard way of a "list type", there is no really good solution to this.

**Comment by WebworkrNet** [comment]
I had already suspected something like that.
