### ISSUE TITLE
QuickUnlock funktioniert nicht mehr unter Android 11

### ISSUE THREAD

**Issue by simonschaufi** [PhilippC/keepass2android#1761]
Ich habe lange Zeit die App unter Android 10 laufen gehabt und vor kurzem dann auf Android 11 upgedatet. Seitdem funktioniert der QuickUnlock nicht mehr und ich muss jedes mal mein ganzes Pw eingeben. Ich habe noch kein issue dazu gefunden. Ist das Problem bekannt oder muss ich eine andere Systemeinstellung vornehmen? Ich habe den Eindruck, dass mit dem Update nicht alles sauber migriert wurde und doch vieles anders ist als mit Android 10.

Samsung Galaxy A10
Keepass 1.09a-r3

**Comment by PhilippC** [comment]
This is known to happen when you have very aggressive "battery optimization" settings - can you check if those changed with the Android update? Can you exempt the app from it?

**Comment by simonschaufi** [comment]
I did that and it works again! Thanx!
