### ISSUE TITLE
"keepass2android offline" not really offline?

### ISSUE THREAD

**Issue by unclecircuschris** [PhilippC/keepass2android#177]
This is supposed to be an offline app (as indicated by the title), so why is there an option for "work offline/online"?  And why does it keep trying to save to remote ("unable to save to remote. Working offline")? And why is there a synchronise option?  And where does it synchronise to? Is this app truly offline or not?

Thanks,
Chris.

**Comment by PhilippC** [comment]
please see #86 for a discussion on this.
To summarize: KP2A Offline caches files as well, and "remote" means "original file" (even if it's local).
