### ISSUE TITLE
Hide donation option stays disabled

### ISSUE THREAD

**Issue by cengizIO** [PhilippC/keepass2android#1771]
Hello!

I have been using KP2A for at least two years now, and I remember installing a Donation app for sending you beers and stuff. I did donate quite a while ago, with that app and donation options are hidden on my phone. 

I recently installed it on my tablet too, and donated a second time. Because why not? 

However on my tablet "Hide donation option" is disabled despite the fact that at least 4 days have passed.

The version in question is 1.09a-r3

What am I missing

Thank you! @PhilippC

**Comment by WebworkrNet** [comment]
https://philipp.crocoll.net/donate.php?lang=en&app=keepass2android.keepass2android

**Comment by PhilippC** [comment]
@cengizIO First: thanks for your support! :-) 
This option should disappear after opening the entry view for 50 times on that device. If you don't wait so long, send a message to crocoapps@gmail.com and I'll give a hint how to disable it immediately.
