### ISSUE TITLE
New Google Drive not accessible

### ISSUE THREAD

**Issue by engeeaitch** [PhilippC/keepass2android#1772]
Hi - I have just upgraded from Google Backup and Sync to the new Google Drive.   On my desktop I am syncing my keepass file by syncing "My Computer" and adding the folder containing my database.  The new Google Drive app on my phone has a "My Drive" section and a "Computers" section.  Under this folder I can see my computer and then under that, the folder containing my keepass database.

From keepass2Android, having selected Google Drive, I can only see the files under "My Drive".  I don't want to add my database to this folder, because if for any reason Google Drive was not working on my desktop, I would have no access to my database.

Is there any way to access "My Computer" please?

Thanks.

**Comment by PhilippC** [comment]
does it work if you select "Open File" and then choose Android file browser (where you can select Google Drive)?

**Comment by engeeaitch** [comment]
No - unfortunately not.
I went to "Open File" and then chose "System File picker" (I don't have an option called "Android file browser").
From there I can choose "Drive".  But I can then only see what is held in "My Drive" with no option to see "Computers" and "My Computer".

**Comment by meubanks64** [comment]
If you 'star' the file in Gdrive, you should be able to choose it from the the app using "system file picker', and then the Gdrive selection, then starred files. Took about 30s for it to appear for me.

**Comment by PhilippC** [comment]
sounds like a good solution! Thanks @meubanks64 !

**Comment by engeeaitch** [comment]
Thanks - that works for me.
