### ISSUE TITLE
Added auto-type target-window removed when merging databases in Keepass2Android

### ISSUE THREAD

**Issue by Unispezi** [PhilippC/keepass2android#1776]
- Yesterday I've edited a password entry "PE" in my Windows Keepass, adding a new auto-type target window.
- Today I needed PE in a new android app, so I activated K2A autofill
- As K2A did not know the app, I had to chose PE manually
- K2A then asked me whether to remember the new app for PE, I confirmed
- Then "Merge local database changes into changes coming from server?" dialog popped up. I chose "merge database". This apparently merged the two changes to PE.
- Now the added auto-type target window is gone again. In PE's history I can see the version where I've added it, but the version created by K2A removed it again.

Expected behavior: Merging databases in K2A does not revert changes coming in from server.

Informations:
- Keepass2Android 1.09a-r3
- Android 10 on Fairphone
- Windows Keepass 2.48.1
- Databases are synced via Onedrive

**Comment by PhilippC** [comment]
if I understand correctly, the problem appeared when you made changes to the same entry without synchronizing in between. There was a long discussion with the KeePass author whether such changes should be merged or not, but it was decided that it is safer to always take the latest version of an entry, but not merging changes to the same entry. Even though in this case this would have been the better solution, there are other cases where this wouldn't make sense and give you inconsistent data. Please copy the autofill-target from the history to the current entry to fix this.
