### ISSUE TITLE
Introduction of the "Name" field

### ISSUE THREAD

**Issue by WebworkrNet** [PhilippC/keepass2android#1778]
The field `Title` has been replaced by the new field `Name`. `Name` contains the value of the `Title` field as long as this value is not overwritten. The field `Title` still exists.

I think this was introduced with version _1.09a-r3_. What is the background of this change?

**Comment by WebworkrNet** [comment]
Is it just a renaming? I have only discovered the phenomenon of duplicate fields in one record.
![20210828_212255](https://user-images.githubusercontent.com/43509007/131228798-1fa783d7-d8f6-4bc9-bccc-77a545c78148.jpg)
![20210828_211357](https://user-images.githubusercontent.com/43509007/131228799-bdf05ef9-052b-44dd-8e9a-b37c21e90b0e.jpg)

_The field contents have been made unrecognisable._

**Comment by PhilippC** [comment]
It only shows "Name", where as "Titel" seems to be an additional (custom) string in your screenshot.

**Comment by WebworkrNet** [comment]
But the app has already renamed the field names from `title` to `name`? I don't think I created the `title field` manually. That's why I noticed it.
