### ISSUE TITLE
Cannot access file on NAS Drive via http on Port other then 80

### ISSUE THREAD

**Issue by awsmahesh9999** [PhilippC/keepass2android#1779]
Cannot access NAS Drive using http it defaults to port 80 for connection. When I use configured port it gives error Method Not Allowed. Buffalo NAS Drive

**Comment by PhilippC** [comment]
can you access this drive using WebDav e.g. with FolderSync?

**Comment by awsmahesh9999** [comment]
Hi Phillip, Please close the issue. I was able to access it via ftp
