### ISSUE TITLE
Notification priority and settings don't work on Oreo

### ISSUE THREAD

**Issue by ingenium13** [PhilippC/keepass2android#178]
On Oreo (and perhaps older), the notification shows with a normal priority, so it has an icon always displaying when the database is locked or unlocked. Disabling "notification icon while unlocked" has no effect, the icon flashes briefly and then continues to remain. There's now no longer any way to remove the notification icon.

Previously, the notification icon only was present while unlocked. Once the database was locked it became a low priority notification so that it was at the bottom when you swiped down, but it didn't have a persistent icon. Now it does.

It worked fine in Oreo about a month ago, but one of the recent updates broke it.

**Comment by Madis0** [comment]
I believe you're talking about [this "feature" that was added in 8.1](https://issuetracker.google.com/issues/69842394). Unfortunately, it seems like the developer has nothing else to do other than properly implement notification channels and guide users on how to hide the icon manually.

**Comment by PhilippC** [comment]
@Madis0 while trying to implement notification channels, it seems to me that users can only hide the entire notification or keep it including the icon. Do you know if there is the chance of only hiding the icon?

**Comment by PhilippC** [comment]
@Madis0 sorry, I found it. Need to click the notification channel and then can set the importance to low. Now I only need to find if there is a way to set the default importance, because currently it's always medium.

**Comment by PhilippC** [comment]
fixed with https://github.com/PhilippC/keepass2android/commit/6fc4741c9a699e21d61080c6f77574e1b68cf148
