### ISSUE TITLE
Unable to use the "ô" caracter in master password

### ISSUE THREAD

**Issue by Calireel** [PhilippC/keepass2android#1780]
Hi !
I guess this started with the last update,because i didnt had the issue before :

on my android phone (android 11)  using Keepas2android version 1.09a-r3
when typing my master password the ô caracter is not recognized. Therefore my master password is not valid :-) And i am unable to acces my database on the phone typing the password (i have a problem with my fingerprint scanner).

I tried my master password on the  computer and it works fine.
i tried on my android tablet android 11, id dosent work any more.

the others o caracters works fine ö oe , ó  ... etc

thanks for your work :+1:

**Comment by PhilippC** [comment]
Do you know if there is a look-alike character with a different Unicode value? I know for example that the Greek character μ has two Unicode values (depending whether it is part of a unit like μm or part of a a Greek word). Could this cause this behavior here as well?

**Comment by Calireel** [comment]
Hi Phillip, thanks for the reply.

Hmm i dont know how to check that
I did some searches in internet but it dosent seem : 

Symbol ;   ô  Unicode number | U+00F4
The look alike are : https://gist.github.com/StevenACoffman/a5f6f682d94e38ed804182dc2693ed4b

**Comment by PhilippC** [comment]
Hard to tell what the problem is. Did you try different keyboards?

**Comment by Calireel** [comment]
Hi thanks for the suggestion, I tried another keyboard, and you were right.

The problem is with the Samsung keyboard. 
With Microsoft switftkey it is OK

What do you recommend me to do? 
Contact Samsung? 

Thanks for all your work

**Comment by PhilippC** [comment]
Maybe you can check the Unicode characters again to see if they type different codes. You can try to contact Samsung, choose a different password or switch to Swiftkey (at least for typing the password).
