### ISSUE TITLE
Selecting Placeholders for Keyboard 

### ISSUE THREAD

**Issue by OrihalconDE** [PhilippC/keepass2android#1781]
Sometimes I've to type in TOTP into some login forms and when this happens I need to Tab through all available entries to get to the requiered option.
I would like to have the possibility to choose which fields I want to be active and which are not requiered.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Since closed, how you solved it?

> Sometimes I've to type in TOTP into some login forms and when this happens I need to Tab through all available entries to get to the requiered option.

Yes

> I would like to have the possibility to choose which fields I want to be active and which are not requiered. 

I like to hide "otp" button.
And other new native time otp fields

but always like to see "TOTP" Reachable instead.
