### ISSUE TITLE
Login on WiFi when Roaming not available

### ISSUE THREAD

**Issue by andyfrei** [PhilippC/keepass2android#1789]
Hi
Discovered on Holidays: was unable to login into KeePass while on Roaming, all tough WiFi was available with reasonable speed.
Regards
Andy

**Comment by PhilippC** [comment]
can you please provide more information: which error/behavior did you get? Where is your database stored?

**Comment by PhilippC** [comment]
ok thanks. This should be fixed by https://github.com/PhilippC/keepass2android/issues/1500
