### ISSUE TITLE
Fingerprint option not available

### ISSUE THREAD

**Issue by Gilbert54** [PhilippC/keepass2android#1790]
I've been using KeePass like forever on my PC and on my droid phone. At some point - I can't remember when - the option to open keepass2android using my fingerprint sensor disappeared. I don't see the option to re-enable it.

Phone: Xiaomi MI-8 Lite
OS: Android 10 QKQ1.190910.002
Keepass2android version: 1.09a-r3

**Comment by kwaio** [comment]
Same here. Been like 2weeks on a OnePlus 9 Pro.
I have a red ⚠️ signal. Clocking it displays a stack trace I can't copy or screenshots.
Seems mainly an UnrecoverableKeyException

**Comment by PhilippC** [comment]
in order to re-enable it, please go to settings - database - biometric unlock.

**Comment by Gilbert54** [comment]
Thanks. That works. Had to open the app first using the password in order to get access to the DB Settings. Makes sense.
