### ISSUE TITLE
BUG: App doesn't check key, if it's moved from Google drive

### ISSUE THREAD

**Issue by dnim** [PhilippC/keepass2android#1796]
1) attached key, saved in Google drive
2) login
3) remove key from Google drive
4) logout
5) login 

Result 
- error shown that app can't find a key 
- still was logged-in in the app

Expected result
- user shouldn't be allowed to login in this case

Possible solution 
- improve check and logic. Add tests for this case
- remove key file caching

Model: Huawei p20 pro, 
os: version 10, native.

**Comment by PhilippC** [comment]
I don't consider this a bug. If you want to enforce checking that the file still exists on the cloud, there is no need to enable file caching. So simply disable that and it should do what you want to achieve. Note that, of course, you can't open the database anymore when you don't have internet connection.
