### ISSUE TITLE
BUG: SFTP App won't allow me to select publickey only send public key

### ISSUE THREAD

**Issue by Srax** [PhilippC/keepass2android#1797]
**Device:** OnePlus 8T  
**App Version:** 1.09a (latest)  
**Android Version:** 11, Oxygen OS 11.0.10.10.KB05BA  

**Issue:** Whenever I attempt to select my private key file for a SFTP connection a **share** prompt is opened instead of a **select** one.  
It works on my friends 3 year old huawei p10 chink phone running android eumi 9.1.  

**EDIT:** So it seems like I have to send the app's auto-generated private key to myself and then add it to authorized keys on my server... Why can't I choose my own key. The auto generated one doesn't seem to allow me to add a password to it.

![keepass2androidsftpbug](https://user-images.githubusercontent.com/26537568/134825780-53d4893e-4214-403f-be1e-7d6b50e1aa01.gif)

**Comment by PhilippC** [comment]
this is intended behavior. Loading a private key is very difficult without giving other apps access to it (at least temporarily). Instead. KP2A creates a new key pair and allows you to export (share) the public key (which you need to register on your server).

**Comment by Srax** [comment]
I see, my bad then. Odd how on my friend's phone in able to "share" to a file system and pick the actual file
