### ISSUE TITLE
offline version shows online and can't locate my kdbx file

### ISSUE THREAD

**Issue by kevin789900** [PhilippC/keepass2android#18]
Since I copied my kdbx file over to new phone last November I had been getting notification about something like "cannot save remote, working offline" I am using the offline only app version.  So I finally tried to straighten this but I cannot locate my kdbx file to back it up,  App shows it is here:
"content://com.scavengers.apps.filemanager.externalstorage.document/primary%3aKeePass"

This is a file manager app I tried a while back that is no longer in the Play store but I found an apk and reinstalled it.  This path is not getting recreated however.

I can still access the database and add to it.  When I try to export it, it creates a file but it is empty 0KB.

Any other ideas???

Thanks!!!

**Comment by PhilippC** [comment]
the current versions cannot export when working offline. This should be fixed with the next update.

**Comment by realmain** [comment]
Our r
