### ISSUE TITLE
feature request: Importing all-in-one SSL certificate file

### ISSUE THREAD

**Issue by cptechnik** [PhilippC/keepass2android#1804]
I using plesk on my rented server with letsencrypt plugin.
There's a possibility to export all needed certs (CRT, PK, CA.CERT, CERT) in one file for easy import.
Maybe it's possible to accept this file on kp2a?

**Comment by PhilippC** [comment]
maybe I'm not understanding correctly what you want to do, but in my understanding you should install the certificate in your OS.
