### ISSUE TITLE
stream was reset: INTERNAL ERROR

### ISSUE THREAD

**Issue by Discostu36** [PhilippC/keepass2android#1814]
I try to open my Keepass file from my Nextcloud, so I go to "Open Database" --> Nextcloud and add my credentials. I select the file from webdav. Now I am prompted to enter the password. But after I have done so I get the error message "stream was reset: INTERNAL ERROR"

**Comment by PhilippC** [comment]
for testing: can you rename (or copy) the database on Nextcloud and try to open from that "new" location?
