### ISSUE TITLE
[Feature Request] KeePassOTP in a separate database

### ISSUE THREAD

**Issue by gabriele-v** [PhilippC/keepass2android#1815]
Hello,
what about integrate KeePassOTP plugin separate database support?
https://github.com/Rookiestyle/KeePassOTP/wiki/KeePassOTP-storage-approaches#otp-storage-in-a-separate-database

I think having the OTP with the password it's not a real 2FA, I could create two different databases obviously, but having an OTP DB inside the other, like KeePassOTP it's doing I think it's a pretty smart way to manage it.

Thanks

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Kp2a Supports the Special `autoopen` group for loading additional database. You can add the otp to it. 
provided you save the OTP entries in a separate entry in the separate database

**Comment by WebworkrNet** [comment]
I just read a commentary on a German YouTube video. The author writes that he doesn't see any problem with passwords and OTP being in the same programme, but he also recommends separating the databases. @gabriele-v 's train of thought is therefore understandable.

`Gehackt trotz 2-Faktor-Authentifizierung: Wie ihr euch dagegen schützt | c’t uplink 48.2c
https://invidious.snopyta.org/watch?v=PfYwMvRmwLA&local=true`

@4-FLOSS-Free-Libre-Open-Source-Software Is there any documentation or tutorial on this?

**Comment by kud** [comment]
I'm currently thinking about my password strategy and yes, @PhilippC , it's not about finding secure or not KeePass, it's about keeping everything in the same database for passwords and OTP.

I'm considering having a dedicated database for OTP only to be honest.
