### ISSUE TITLE
Autofill pop-up stopped showing up in most apps

### ISSUE THREAD

**Issue by anLizard** [PhilippC/keepass2android#1817]
I've noticed that the autofill popup only rarely shows up anymore.
The issue seems to be mostly on more modern apps, e.g. the latest versions of Firefox, Samsung Internet and Bromite (Chromium fork).

Older apps have no issues displaying the autofill popup.
Very often I have to manually open Keepass2Android, pick the account I want to log in with and copy the password into the clipboard.

Is there an estimate for when Android 11's in-line keyboard autofil will be supported? There is an open issue regarding this here: https://github.com/PhilippC/keepass2android/issues/1534

I believe it would serve as a solution for this issue. Other password managers I've tested work on most login fields using this feature.

**Comment by gbil** [comment]
I can vote for this one, seems like it is broken in general, tried all the main browsers, but I'm pretty sure that it worked a few weeks ago

**Comment by PhilippC** [comment]
please test again with 1.09b-pre1 from https://play.google.com/apps/testing/keepass2android.keepass2android. Should be fixed there.

**Comment by gbil** [comment]
sorry should had mentioned that I'm participating in the beta and have already 1.09b-pre1 installed from 2-3 hours ago with the same result

**Comment by PhilippC** [comment]
@gbil please see my comment to the merge request regarding brave beta: https://github.com/PhilippC/keepass2android/pull/1793#issuecomment-967385424
