### ISSUE TITLE
Some OTP included Doesn't Have "copy OTP" button

### ISSUE THREAD

**Issue by mmtech2012** [PhilippC/keepass2android#1823]
When create an entry in KeepassXC windows which include OTP setup
and sync on android device
when entry appear in notification bar
doesn't show "copy OTP" button.

**Comment by Rick0313** [comment]
Hi Philipp,

I encountered this same problem today and have attached a sample file that should illustrate the problem.  I created the file using the standard KeePass client (installed from KeePass-2.53-Setup.exe) on Windows 10 Home (64bit).  I am using one plugin called **LockAssist** but I would not expect that to have any bearing on this issue.

My personal .kdbx file contains about 15 records with OTP values and they all work fine in the desktop client.  This morning, I copied the file to my phone via USB and imported to **Keepass2android Offline**.  All of the OTP entries work fine except for 2.  The base value is there, but there is no TOTP line, so I can see and copy the base value, but there is no generated value.

I have attached **Sample.kdbx** containing **Sample Entry** and **Sample Entry #2** both of which contain real OTP codes that were assigned to me.  Again, the codes work fine in the desktop client, but do not work in Keepass2android Offline.  The password is _Sample#1823_.  I would appreciate your taking a look to see if you can identify the problem.

Please let me know if you have any questions.  Thank you, and have a great day.
[Sample.zip](https://github.com/PhilippC/keepass2android/files/10669483/Sample.zip)

**Comment by PhilippC** [comment]
this was fixed by https://github.com/PhilippC/keepass2android/pull/2498
