### ISSUE TITLE
Fingerprint Unlock Error Pixel 6

### ISSUE THREAD

**Issue by nostrom0o** [PhilippC/keepass2android#1828]
I get the following error message when I try to use the fingerprint:

![IMG_20211030_022936.jpg](https://user-images.githubusercontent.com/87041362/139513759-1fc93eb0-64d0-4ae5-aaf0-70cab648b187.jpg)

Many thanks for the help

**Comment by PhilippC** [comment]
@nostrom0o can you explain why you closed this? Did you find a way to solve this?

**Comment by nostrom0o** [comment]
@PhilippC 

Yes, I disabled biometric unlocking in the database settings and then enabled it again and that solved the Problem.

**Comment by PhilippC** [comment]
good to hear, thanks for the information!
