### ISSUE TITLE
Issues with biometric unlocking on Pixel 6 Pro (Android 12)

### ISSUE THREAD

**Issue by mynttt** [PhilippC/keepass2android#1829]
Hi! I'm experiencing issues with the biometric unlocking on the Pixel 6 Pro. 

App version: 1.09a-r3 (from Playstore)
OS: 12 + October 2021 Patch

On all other apps the biometric interface works fine. Maybe this has something to do with an outdated API?

I've attached two screenshots of the issue. Biometric authentication is enabled in the settings. 

![Screenshot_20211101-195457](https://user-images.githubusercontent.com/22261092/139726529-e568e524-a2e6-4846-882f-8a73dbff5c88.png)

![Screenshot_20211101-195430](https://user-images.githubusercontent.com/22261092/139726552-2272bd73-3245-4396-bb90-2dc343aae010.png)

**Comment by PhilippC** [comment]
does it help to disable biometric unlock and re-enable (see https://github.com/PhilippC/keepass2android/issues/1828)?

**Comment by mynttt** [comment]
@PhilippC Worked perfectly! I'm pretty sure this issue has to do with copying all the apps and app data from my old Pixel 2! Great this solves it =)
