### ISSUE TITLE
UI regularly glitches out on Android 12

### ISSUE THREAD

**Issue by douglasg14b** [PhilippC/keepass2android#1834]
The UI seems to bug out and constantly load, try and minimize, and load more flashing during the process on Android 12.

I'm unsure why.

Video: https://photos.app.goo.gl/ntePspDwu8Gy9gKt7

**Comment by PhilippC** [comment]
please see https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254 for how to solve this.,

**Comment by douglasg14b** [comment]
That comment is referring to the google drive error, this issue is not about that. It just so happens that the UI glichyness ALSO happens when that error occurs, but not exclusively.

**Comment by PhilippC** [comment]
I have only seen this in combination with the GDrive error. Did you try to resolve that error first? If the other problem is still present, can you post another video please?
