### ISSUE TITLE
Add setting to disable this popup 

### ISSUE THREAD

**Issue by Edfgdz** [PhilippC/keepass2android#1835]
When using keepass in apps not used before,this windows would popup to let user to make sure this app is safe. 

![Screenshot_2021-11-07-13-36-52-982_keepass2android keepass2android](https://user-images.githubusercontent.com/26460124/141271892-91bdb9dc-130b-4a0f-8a00-8987ec8c4cad.jpg)

So is it possible to add setting to make this popup not appear when using keepass in new installed apps?

**Comment by PhilippC** [comment]
there are cases when apps might try to retrieve login information for websites which they are not connected to. If you are aware of this risk, you can disable DAL verification in settings - app - password entry access - Autofill service - No DAL verification.
