### ISSUE TITLE
1.09b-pre0 breaks ykDroid / YubiKey challenge response

### ISSUE THREAD

**Issue by ei-ke** [PhilippC/keepass2android#1841]
I installed the latest beta today and the yk challenge response is broken. K2A just says "install ykDroid" from Google Play and a short notification that the challenge failed (though not actual challenge was initialized) Reinstalling ykDroid doesn't solve this.
Android 11 Galaxy M51

**Comment by PhilippC** [comment]
This was fixed in pre1, uploaded 1 hour ago
