### ISSUE TITLE
Keyboard based workflow: search entry doesn't have url

### ISSUE THREAD

**Issue by tenzap** [PhilippC/keepass2android#1848]
Maybe this is not an issue or has already been reported but I didn't find anything.

When using the keyboard based workflow, I click on the "kp2a" icon of the kp2a keyboard.
It shows a list where there is:
- Choose an entry
- Search an entry with "org.mozilla.focus" (or whatever the app_id of the app/browser)

Selecting the 2nd entry doesn't find anything for the website on which I am. This may be expected since it searches for the app_id.

I excepted the list to contain an item as below (which would be more useful).
- Search an entry with "https://example.url.tld"

Technical info:
*    Keepass2Android: 1.08c-r1-nonet
*    Browser: DuckDuckGo but also Firefox, Firefox focus.
*    Xiaomi Redmi Note 9S: Android 11

**Comment by PhilippC** [comment]
this only works inside apps, but not for browsers. In the browser, select Share URL > Keepass2Android. This will bring up the keyboard for that entry.
