### ISSUE TITLE
biometric fingerprint: set up is impossible

### ISSUE THREAD

**Issue by Sandra11-dev** [PhilippC/keepass2android#1849]
When I want to set up the biometric fingerprint, the following screen first shows the error message "too many incorrect entries". Then the message disappears and a picture appears with a white fingerprint on a grey background. However, the picture is not a button and does not react to pressure. Only the "Cancel" button reacts in the screen. Please fix it. 
One+ 7 with Android 11. Thank you.

**Comment by PhilippC** [comment]
when the fingerprint appears, can you touch the fingerprint sensor?

**Comment by PhilippC** [comment]
closing - no reaction.
