### ISSUE TITLE
SFTP "Auth fail"

### ISSUE THREAD

**Issue by metafarion** [PhilippC/keepass2android#185]
I'm not able to log in to an SFTP server, receiving an "Auth fail" error, but I have verified that the credentials are correct and login is possible with other clients.  The server logs the following error on each attempt:

error: Received disconnect from 172.220.8.65 port 55420:3: com.jcraft.jsch.JSchException: Auth fail [preauth]

I've tried this using the stable and beta (1.04 at this time) versions of Keepass2Android
Server is running OpenSSH 7.5p1

**Comment by PhilippC** [comment]
do you have any public key auth? On https://stackoverflow.com/questions/17148948/com-jcraft-jsch-jschexception-auth-fail-with-working-passwords, it sounds like this message is related to public keys?

**Comment by metafarion** [comment]
The server does accept key authentication, but I'm not using it for this interaction, at least not intentionally.  I'm looking in the SFTP dialog for selecting a database now and I'm actually not seeing where you'd pick a key file.  Where is this done?

**Comment by PhilippC** [comment]
KP2A does not support public keys at the moment. there is another issue for this.

**Comment by mstarks01** [comment]
I'm receiving this as well. I know that the credentials are correct and the server does not require public key authentication.

**Comment by mstarks01** [comment]
In my case, this appears to be a conflict with the Google Authenticator PAM module. "ChallengeResponseAuthentication yes" is required for Authenticator, which works fine for a TTY, but not when using K2A. But even if it was set to "no," which does allow authentication to succeed, and even if the IP has been whitelisted, there is then the issue of "keyboard-interactive" the authentication method. To wit:
Jan 21 14:27:54 host sshd[8718]: Authentication methods list "keyboard-interactive" contains disabled method, skipping

**Comment by rogalian** [comment]
In my case (FreeBSD server) I had to explicitly enable PasswordAuthentication in /etc/sshd_config

**Comment by snIP3r23** [comment]
same problem here using keepass 1.06f and openssh server 7.7p1...
any progress here?

**Comment by PhilippC** [comment]
@snIP3r23 any @metafarion  which auth method does your server support?

**Comment by snIP3r23** [comment]
in my case:  publickey,keyboard-interactive

**Comment by PhilippC** [comment]
@snIP3r23 publickey is supported in 1.07, you can switch to beta (https://play.google.com/apps/testing/keepass2android.keepass2android).

**Comment by snIP3r23** [comment]
same problem also with 1.07 beta:

`Jan 21 19:45:58 area52 sshd[4538]: error: Received disconnect from 192.168.0.50 port 39794:3: com.jcraft.jsch.JSchException: Auth fail [preauth]
Jan 21 19:45:58 area52 sshd[4538]: Disconnected from authenticating user XXXX 192.168.0.50 port 39794 [preauth]` 
plus a 
`Cannot create new folder here` in the app
i am using the absolute path to my home directory in the app ( /home/$USER/ ), thats also where the .kdbx file exists...

**Comment by snIP3r23** [comment]
ok, after adding publickey authentication to my ssh server i managed to get it working *g*

**Comment by PhilippC** [comment]
it seems to me like this is not an issue with KP2A but with server configuration. @metafarion  if you cannot solve the problem by enabling password authentication or public key with 1.07-pre, please reopen.

**Comment by lapo-luchini** [comment]
Still happens in current 1.08, but using public key is a good work-around.
(ad even a better choice anyways)
