### ISSUE TITLE
OneDrive losing connection

### ISSUE THREAD

**Issue by elskewe** [PhilippC/keepass2android#1854]
![image](https://user-images.githubusercontent.com/19361925/143685629-07bf73fe-b97c-42f1-bf62-407e7838246d.png)

I have my KeePass file on OneDrive. When I try to synchronize it, I get the error message above. The problem seems to be with the OneDrive connection itself. When I try to open another database I get the error message "authentication not successful" before I can see any of my files in OneDrive after I click "continue" on the prompt from OneDrive whether I'm trying to log in to Keepass2Android.

I had the same problem a few weeks back. Deleting the app data solved the issue for me temporarily, but now it seems to be back. Before that, it was working without problems.

I'm using Keepass 1.09b-r0 on Android 10. Please let me know if you need any additional information, I am happy to help.

**Comment by PhilippC** [comment]
did you open the file through Open file > OneDrive or did you go through the OneDrive app?

**Comment by elskewe** [comment]
The former. Weirdly enough, I just tried it again and now everything works fine. No idea what is going on.
