### ISSUE TITLE
What's the difference between the blue and green Android versions?

### ISSUE THREAD

**Issue by sir-farfan** [PhilippC/keepass2android#1858]
Sorry for the dumb question but I don't understand why are there 2 versions of the app liking to the same github page.

What's the difference?
Which one should I pick?
Is it just a skin change?

I just want to see/edit my passwords in Linux and Android and backup in Dropbox or something as I did with UPM when it worked in Android...

https://play.google.com/store/apps/details?id=keepass2android.keepass2android_nonet
https://play.google.com/store/apps/details?id=keepass2android.keepass2android

**Comment by PhilippC** [comment]
green: full feature set, requires internet permission
blue: reduced feature set (everything that does not require internet permission)

https://github.com/PhilippC/keepass2android/blob/master/docs/Comparison-of-Keepass-apps-for-Android.md
