### ISSUE TITLE
Database not syncing

### ISSUE THREAD

**Issue by ciupol** [PhilippC/keepass2android#1859]
After upgrading my phone to Pixel 6 I run into a problem as described in 
https://github.com/PhilippC/keepass2android/issues/1833
I used the solution provided there and used a system file picker and selected google drive. The problem now is that the database in not syncing.
I added an entry on my phone and the database saved. The entry shows on my phone. When selecting Synchronize database from KP2A menu it says files are in sync.
Now I go to my PC and download my database from Google Drive to my desktop. I open the database and the new entry is not there.
I open the database directly from Google Drive using KeeAnywhere plug in and the entry is not there.
I go to my phone, unlock the database and the entry is there. I click Synchronize database and it still tells me that the files are in sync.
On my phone I go to Google Drive app and download my database to my phone local storage.  In KP2A I click to change database and select the file I downloaded. The database opens and the entry is not there.
Again in KP2A I select change database, I select system file picker, go to Google Drive and select my database file. It opens and the entry is there.
What is going on?

**Comment by PhilippC** [comment]
can you try to open the file through KeePassDX just for comparison?

**Comment by ciupol** [comment]
Using KeePassDX gives the same results. Local downloaded copy - no entry. Copy from google drive - entry exist.

**Comment by PhilippC** [comment]
that sounds like it is not an implementation issue in the app, then. Can you record a video of how you access both versions, if possible with showing "last modified" dates?

**Comment by Daem0ver** [comment]
Hi
I have encountered exact same issue. I also use Google Drive and have to use file picker. While application shows information that "Files are in sync" copy in the cloud is unchanged. Date of modification is also different.
