### ISSUE TITLE
Feature Request -> integration from other application a import passwords.

### ISSUE THREAD

**Issue by johnmelodyme** [PhilippC/keepass2android#1866]
I would like to propose the feature request for the following: -

1.  Integration within applications. For example in my application, suggests user store the password in `keepass2android`.  Like a prompt `Do you want to save the password in keepass2android ?`
2.  Application able to import existing passwords from `Lockwise` or `Google Password Manager`.

**Comment by GraphiteWingedBird** [comment]
I'm pretty sure I've seen #1, but I am not sure when that was added. It isn't always consistent.

Your second request though, is there a reason you would need that in this mobile app vs. just using KeePass on a computer? I've always considered the mobile version to be a bit of a light version, that is super handy. Sure you can create new databases with it, but for heavy lifting of imports and exports, why not tackle that on a desktop?

**Comment by PhilippC** [comment]
as @GraphiteWingedBird wrote, 1.) is implemented (if you enable Autofill and the client app supports save requests)

2.) is not intended as KeePass2 has great support for this already.
