### ISSUE TITLE
Make keepass2android Samsung DeX compatible

### ISSUE THREAD

**Issue by zwibak** [PhilippC/keepass2android#1867]
When trying to launch keepass2android in Samsung DeX, DeX throws the error message that keepass can't be opened by DeX. Could keepass2android made be DeX compatible?

**Comment by PhilippC** [comment]
please see https://github.com/PhilippC/keepass2android/issues/625#issuecomment-593074355 for a solution

**Comment by zwibak** [comment]
I can't get working K2A with Dex with and  of the solutions discussed. There seems even not to be a clear solution but rather some trial-and-error suggestions. This is not very satisfying. What is the causing K2A to deny starting in Dex mode? And why can't K2A be made to get working with Dex?

**Comment by PhilippC** [comment]
@zwibak as far as I understand you need to enable the DEX developer options. It seems like Dex does not allow apps which have a built-in keyboard. I won't remove the keyboard for this reason. Please contact Samsung if you don't like that policy.

**Comment by zwibak** [comment]
Hello Philipp¨
Thank you for caring about my problems with Dex. Unfortunately there is no
Developer Mode in the inbuilt Dex on my Samsung Galaxy Tab S7 (or I
couldn't find it).
Kind regards,
Stephan.

PhilippC ***@***.***> schrieb am Mi., 29. Dez. 2021, 12:35:

**Comment by PhilippC** [comment]
does this help? https://www.youtube.com/watch?v=DYGgs-b6IGA
