### ISSUE TITLE
App don't ask fingerprint

### ISSUE THREAD

**Issue by andreaprs** [PhilippC/keepass2android#187]
Hi, I have a problem with Keepas2Android app. 
I always unlocked the password's db with fingerprint, but today the app don't ask me the fingerprint and I don't remember original password.

Why app didn't ask me the fingerprint? Can you help me? Can you abilitate this featurse for me?

I hope you can help me, it is very very important for me.

Thanks,
Andrea

**Comment by andreaprs** [comment]
this problem appeared after I added a fingerprint.

I have another question; If the application saves the password in a local database that is only unlocked with the correct fingerprint, is it possible to recover the password?

**Comment by PhilippC** [comment]
the Android Fingerprint API invalidates stored fingerprint data after adding new fingerprints. Sorry but there is nothing to do about this. The master password is required to unlock.

**Comment by andreaprs** [comment]
Sorry Philipp, but other applications I use have not asked me to re-enter my password and have accepted my fingerprint

**Comment by PhilippC** [comment]
they are probably not encrypting data protected with a fingerprint.
