### ISSUE TITLE
Feature Request: Time out for KP2A keyboard 

### ISSUE THREAD

**Issue by JanWaldhorn** [PhilippC/keepass2android#1870]
I like to use the KP2A keyboard and have installed and correctly configured the plugin to automatically change the input method. In the settings you can define different ways to switch back to the normal keyboard, but they rarely work for me. For me a TimeOut of the KP2A would help, which I imagine in such a way that if you are not inside KP2A and x time (~ 30 s) has passed since the change, the original input method is used again. 

Thanks for the great app!

**Comment by PhilippC** [comment]
if you used KeyboardSwap to change *to* the keyboard, it should also switch back automatically when the database gets locked (which you can enable to happen after X minutes), unless you disabled that option?

**Comment by JanWaldhorn** [comment]
cool, that works for me. Thanks
