### ISSUE TITLE
Option to enable one tap copy to clipboard on tap of username, password, otp etc

### ISSUE THREAD

**Issue by gwtp** [PhilippC/keepass2android#1872]
Add option to enable one tap copy to clipboard e.g. if i tap the username field it instantly copies to clipboard instead of drop down menu where I tap "copy to clipboard".

**Comment by PhilippC** [comment]
I don't want to encourage usage of the clipboard further, it has many downsides and there are better alternatives (keyboard, autofill), so I am not going to implement this.
