### ISSUE TITLE
keepass2android uninstall fails

### ISSUE THREAD

**Issue by 3rdRockGuy** [PhilippC/keepass2android#1877]
Any suggestions for how I can fix uninstalling keepass2android on my android phone?
It just hangs for ages with the timer circle rotatiing, so not exactly frozen but fails.
Have tried various ways = drag icon on to "uninstall" +click uninstall in Google Play Store +from file manager apps list

Delete phone keepass2android apps folder from computer with phone usb-connected?

**Comment by PhilippC** [comment]
did you try this after rebooting the phone? I don't think this is an issue with KP2A but rather your OS/device, because the app is not involved in this process.
