### ISSUE TITLE
Lost access to files stored on google drive

### ISSUE THREAD

**Issue by tmoson** [PhilippC/keepass2android#1879]
I've lost access to files stored on google drive from the app. Whenever I go to open google drive, I get an error saying that google has blocked the app. I'm not sure why, but I can see that it has been removed from the third-party apps with access. While the removal of it from there seems like an issue on google's side (it looks like access was removed when I removed the device I initially set the app up on from my account), I can't request access from the app again. I've tried a fresh install of the app, but I get stuck with a repeated loading screen when I first try to open the app, and and then eventually the same loading screen and an on-screen error saying something along the lines of `attribute name cannot be null`. 

I'm not sure if any of these details may help, but here's some information about my phone/the android version I'm running:
Phone Model: Pixel 6 Pro - Verizon model/sim
Android version: 12
Android security update release: November 5, 2021
Google Play system update release: September 1, 2021
Android Build number: SD1A.210817.037.A1
Kernel Version: 5.10.43-android12-9-00001-g3b35c4eea2da-ab7739787

And I'm experiencing this issue on keepass2android version 1.09a-r3

**Comment by PhilippC** [comment]
you might try https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254, but the app's access to GDrive through the API is blocked, which is why I suggest to switch to the way through the file picker (Change database > Open file > System file picker > GDrive).

**Comment by tmoson** [comment]
Thanks, this works perfectly! Turns out I misread these instructions in that comment initially and thought I had already tried that. Appreciate all your hard work on the app!
