### ISSUE TITLE
Option to auto-synchronize file when Quick Unlocking

### ISSUE THREAD

**Issue by metafarion** [PhilippC/keepass2android#188]
It looks to me as though when you open a remote database cold, KeePass compares your cached copy and fetches an updated one if necessary, but this doesn't seem to happen when using Quick Unlock.  I have to manually go to the menu and say Synchronize and then tell it to Yes, update the local copy.  I would like the option to auto-sync/fetch the database whenever the user opens it (quick or otherwise) to make sure they are up-to-date with the master copy.  Without a prompt if possible.

Actually, it might be a better idea to do the auto-sync when the database is closed/locked.  I'll leave that up to you.

**Comment by heapifyman** [comment]
Another option could be to add possibility to swipe down to sync database?

Or allow defining a sync interval in the settings, like "sync every X minutes"?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
if using Quick Unlock i see it does not sync, but after accessing again while still open it asks to reload.

**Comment by Taijian** [comment]
Just bumping this, because it would really be a useful feature, IMHO.

**Comment by mordowiciel** [comment]
Bumping up, would love to see this feature.

**Comment by natereinert** [comment]
I know this is an old issue, and I see that it was implemented, but I was wondering if it was implemented to autosync whenever opened with QuickUnlock, or is it only if the database is fully closed? Mine doesn't sync after QuickUnlock, and I wanted to know if that is intended behaviour
