### ISSUE TITLE
Error message on opening too fast to read

### ISSUE THREAD

**Issue by Polibon** [PhilippC/keepass2android#1881]
I get an error message every time I open the app, but it is long and I can't read it fast enough. So I can't fix the problem. This needs a way to freeze the message in screen, or have it stay until acknowledgement. It is very annoying, and concerns me as I use the app a lot.

**Comment by PhilippC** [comment]
can you tell how the message starts?

**Comment by Polibon** [comment]
It begins:
Could not access source file: Built in Google....
Then I lose it.

I can't do a screenshot as the phone tells me it won't allow that for
security reasons.

My whole life revolves around this database, so it does worry me.
Thanks for your help.
I will buy you several beers if you can solve this problem. This is the
most useful app I have on my phone.
best wishes,
Paul

**Comment by PhilippC** [comment]
I guess this is saying that the built-in Google Drive access is no longer working (app is blocked by Google, even though I requested verification).

please use Change database > Open file > System file picker > Google Drive to solve this.

**Comment by Polibon** [comment]
Many thanks,
It worked! But could I suggest that if you create long error messages that
you leave them on screen for longer or have them saved to a place where
they can be read?
Great software & support!

Happy New Year.

Paul Bonnett
Oxfordshire, England

**Comment by PhilippC** [comment]
sorry, forgot to mention this: you can enable logging in the app settings to see the messages
