### ISSUE TITLE
Version 1.09b-r1 Not Loading DB on Chromebook - Used to work

### ISSUE THREAD

**Issue by waaweech** [PhilippC/keepass2android#1884]
I’ve been happily using keepass2android on Chromebooks with no issue at all. After updating to 1.09b-r1 today, and using the System File Picker, the DB does not load anymore. The popup message keeps saying “Working, Loading database … (Parsing database ...)”. 

- This behavior is the same whether the DB is local or on Google Drive. 

- The Keepass2Android Offline version 1.08d-r5 works with no issue.

- The same database (located on Google Drive) loads fine with no issue on a Google Pixel 3 XL phone running android 12 phone using the System File Picker.

**Comment by FR1701** [comment]
Exactly the same situation for me. The new version is working fine with Android, but stucking in loading the database on my Chromebook. Apart of waaweech I'm using an https WebDav connection to the source database. But even downloading the database to the local storage doesn't make any difference. I reverted back to 1.08d-r5 and everything works fine again. As a workaround I will stay on this older version and deactivated auto update for the apps.

**Comment by waaweech** [comment]
@FR1701 - Thanks for the similar feedback. Actually, 95% of my KP2A usage is on my Chromebook. 

How did you successfully sideload 1.08d-r5 since it would be an app from sources other than Play Store? Would you provide your steps?

Thanks.

**Comment by FR1701** [comment]
@waaweech To be honest, I'm always not feeling well, when using another source than Play Store to retrieve an apk :-( But in those special cases (OneNote was long time a similar one), there is no other solution. Usually I drive good with apkpure. Here you can find older versions at the end of the current version of an app. For keepass2android it is 
https://m.apkpure.com/de/keepass2android-password-safe/keepass2android.keepass2android
I'm only using this store with a browser, not the app. And after installing I let Play Store check my device.

**Comment by waaweech** [comment]
@FR1701 - I've similar concern on grabbing stuff outside of Play Store due to the security issues. But, I have downloaded the older KP2A from the KP2A Github page itself (the previous releases are all there, so that's not the issue). My question was how to get that installed on Chromebook.

**Comment by FR1701** [comment]
@waaweech sorry for the delay. I just found your reply in my spam folder. :-( Good idea to download older versions from github direclty. I'm not very familar wih github and haven't found 1.08d-r05 but that is surely my fault. Installing an apk on my chromebook is for me as simple as on my smartphone. Downloading and starting from the files folder will show a confirmation dialogue that the source is from outside google play store and then you can install it. But it is necessary to stop google from updating it automatically. So, evertime new updates - even for other apps - are available google recommends also to update KP2A. I need to skip it every time. But I will try the next new version from play store once again.

**Comment by waaweech** [comment]
@FR1701 - Unfortunately, installing an apk sourced from out of Google Play Store is not possible on my Chromebook. My Pixelbook (a Google product) seems to have stricter security than yours. It requires enabling the Developer mode and ADB which requires resetting (power-washing) my Chromebook. But, it doesn't matter anymore since the developer has come up with a fix which is in beta right now (https://github.com/PhilippC/keepass2android/issues/1833#issuecomment-1010724364) and should be generally available in the Google Play Store soon. Once available for the general public, I’ll try the new fixed version on my Chromebook and hopefully it will work as the older version did.

Nice chatting with you.

**Comment by waaweech** [comment]
Update:
Installed 1.09c-r0 (the version that fixes the Google Drive block issue). 

Problem 1:
- After the DB location is selected and when the window to enter the password is displayed, the Chromebook "Languages and Inputs" Settings also pops up. Not sure why! (I dismiss it every time to proceed).

Problem 2:
- Once Google Drive location of DB is selected, and the password is entered, the same message reported in post#1 of this thread pops up saying “Working, Loading database … (Parsing database ...)”. The DB never opens, BUT (see below),
- If I MINIMIZE and then MAXIMIZE the KP2A window, the DB shows up immediately in the open state. Currently, minimizing/maximizing the app is the only workaround for me to have the KP2A open the DB successfully. 

Worth to repeat that everything with KP2A on my Pixelbook Chromebook, which is my primary device to use the KP2A app, was working fine prior to 1.09b-r1.

**Comment by waaweech** [comment]
> Update: Installed 1.09c-r0 (the version that fixes the Google Drive block issue) on my Chromebook.
> 
> Problem 1:
> 
> * Once Google Drive location of DB is selected, and the password is entered, the same message reported in post#1 of this thread pops up saying “Working, Loading database … (Parsing database ...)”. The DB never opens, BUT (see below),
> * If I MINIMIZE and then MAXIMIZE the KP2A window, the DB shows up immediately in the open state. Currently, minimizing/maximizing the app is the only workaround for me to have the KP2A open the DB successfully or at least displayed as open.
> 
> Problem 2:
> 
> * When saving an entry after edit mode, it keeps showing "Saving database ...", BUT, (see below),
> * If I MINIMIZE and then MAXIMIZE the KP2A window, the DB shows as saved. Currently, minimizing/maximizing the app is the only workaround for me to have the KP2A save my changes successfully, or at least shown as saved.
> 
> Worth to repeat that everything with KP2A on my Chromebook, which is my primary device to use the KP2A app, was working fine prior to 1.09b-r1.

@FR1701 - Do you also encounter the same behavior I've described in my previous ^^^ post and use the same workaround?

**Comment by FR1701** [comment]
@waaweech I'm still on 1.08d-r5 :-) This is working fine for me. By the way, my chromebook is a Lenovo Flex 3. As I was happy to get it working with the older version again, I intend to stay on this version until a major new one has been released.

**Comment by waaweech** [comment]
@FR1701 - My other Chromebook is also a Lenovo and it also has the same issue with the KP2A. All of my Chromebooks run the latest Chrome OS (Version 97.0.4692.91) have this issue. With this latest Chrome OS version, I’m noticing that for some Android apps, including KP2A, there is now a drop-down menu on the app's top ribbon where it gives you a choice on how to run the app. The choices are: Phone, Tablet, or Resizable. It doesn't matter which mode I select, I still have to do the window Minimize/Maximize for the KP2A in order to see the DB content displayed. I wonder if the issue has something to do with the proper app sizing of KP2A under any of these modes! I run many Android apps on my Chromebooks and only KP2A is exhibiting this behavior. The rest of my apps are just fine to run in Phone or Tablet mode. May be @PhilippC can comment.

**Comment by PhilippC** [comment]
does this behavior depend on the setting "Protect Database Display" in settings - app - display"?

**Comment by waaweech** [comment]
> does this behavior depend on the setting "Protect Database Display" in settings - app - display"?

Hi @PhilippC - No it does not. The behavior is the same with "Protect Database Display" being checked or unchecked. I just tested.

Are you clear on what the problem exactly is that I'm describing? Please ask me anything to help you out since almost my entire usage of the KP2A is on my Chromebooks. It used to work without any issue until 1.09b-r1 and the same issue now with the new 1.09c-r0.

**Comment by PhilippC** [comment]
is it possible to collect a logcat on CHromebook? If not, maybe you can post a log of the built-in logging (see settings)?

**Comment by waaweech** [comment]
> is it possible to collect a logcat on CHromebook? If not, maybe you can post a log of the built-in logging (see settings)?

I'm not sure how to do logcat on Chromebook. I can see the KP2A built-in log contains my personal information, which I don't want to post here. Any section of the log with no such a information are you interested in?

**Comment by SebSchuette** [comment]
I experience a similar behaviour on my Chromebook. However, I am not shure if the max/min does the trick. I think it just takes a very long time: 
A small DB opens as usual.
My regular DB (31MB) takes a minute or two. However, I tried the min/max thingie.

**Comment by waaweech** [comment]
Thanks @SebSchuette - My DB is 277 minutes. I just waited over 5 minutes but it still won't open, had to do the min/max trick which opened it immediately. 

The thing is right after when I see the "Working… Loading database… (Parsing database…)" message, I just need to do the min/max and the DB opens immediately and I do not have to wait any longer. From what I see, it almost looks like the DB is indeed opened already and the system is waiting to the "Working… Loading database… (Parsing database…)" timeout or disappear to show the DB content. From what I see min/max actions cancels out the "Working… Loading database… (Parsing database…)"  message so the content of DB can be viewed. Looks like this popup message is camouflaging the next window, which is the normal DB in open state view.

**Comment by waaweech** [comment]
> Please find a 2nd logfile. It just took 5 minutes! to open the DB. However eventually it opened. It was not necessary to min/max the window. [logfile2.txt](https://github.com/PhilippC/keepass2android/files/7907999/logfile2.txt)

When you see the "Working… Loading database… (Parsing database…)"  message displayed can you do the min/max trick to see if it opens immediately without waiting 5 minutes in your case? Would you confirm this?

Thanks.

**Comment by SebSchuette** [comment]
You are right. Just had to wait until the pop up changes from "Lade Datenbank" to "Lade Datenbank (Lese ein)" , then min/max.

**Comment by SebSchuette** [comment]
Another question: Should I be concerned about this:
Java.Lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
It shows up a few times in the log file.

**Comment by waaweech** [comment]
Just waited over 15 minutes !!! for the the DB to show open. Still wouldn't. So, in my case it seems it's an indefinite wait, unless I do the min/max trick of course which would show the DB open immediately at any time right after the message appears first.

**Comment by SebSchuette** [comment]
When I open the file via FTP from my private NAS, it takes about 7 minutes, before the message changes state. Also, a different exception occurs.
[logfile3.txt](https://github.com/PhilippC/keepass2android/files/7908225/logfile3.txt)

**Comment by waaweech** [comment]
> When I open the file via FTP from my private NAS, it takes about 7 minutes, before the message changes state. Also, a different exception occurs. [logfile3.txt](https://github.com/PhilippC/keepass2android/files/7908225/logfile3.txt)

Hope the your logs shed some lights for @PhilippC to fix the issue :-)

**Comment by SebSchuette** [comment]
I am in some kind of log file frenzy right now ;-)
Opening the same KDBX file via FTP from said NAS on my shiny Android 12 phone is
- fast
- does not show the strange exceptions
[logfile4.txt](https://github.com/PhilippC/keepass2android/files/7908331/logfile4.txt)

The comparison might help you to understand, how the AndroidOnChrome and regular Android differ.

**Comment by waaweech** [comment]
> I am in some kind of log file frenzy right now ;-) Opening the same KDBX file via FTP from said NAS on my shiny Android 12 phone is
> 
> * fast
> * does not show the strange exceptions
>   [logfile4.txt](https://github.com/PhilippC/keepass2android/files/7908331/logfile4.txt)
> 
> The comparison might help you to understand, how the AndroidOnChrome and regular Android differ.

Absolutely. My not_so_shiny Android 12 phone also works flawlessly. I think the KP2A needs to be optimized for running on Chromebooks as many other apps are these days. The thing is KP2A ran with none of these issues till the last two updates :-(

**Comment by waaweech** [comment]
Also to add: the "Quick unlock" does not seem to present this issue. It's only with the initial DB open.

**Comment by waaweech** [comment]
@PhilippC - Attached is a redacted snippet of the log right before/after I minimize/maximize window:

[Snippet.txt](https://github.com/PhilippC/keepass2android/files/7914885/Snippet.txt)

Also to note:
- The DB that I currently have the loading/parsing issue with, the one I must use the min/max window trick to display its content, has the size of 277 KB. 

- I went ahead and created a new DB with the size of 3 KB and the KP2A on Chromebook opens it immediately with no issue.

Both DB’s are on GD.

Does this help?

**Comment by waaweech** [comment]
Also to mention that updating the DB on GD the "Working ..." spin forever. However, min/maxing the window eliminates the spin issue and shows the changes successfully saved.

**Comment by waaweech** [comment]
@PhilippC - Any chance this issue will be resolved in the next next release? 

Thanks.

**Comment by waaweech** [comment]
@PhilippC - 
Good news: I can confirm that after my Pixelbook Chromebook is updated to the latest (version 99, released March 1, 2022), the issue seems to be fixed. Looks like the problem was with the previous Chrome OS version rolled out earlier this year all along and not with the KP2A. The DB now loads and opens for me as expected using the KP2A Android app on my Pixelbook Chromebook. 

Below is the detail of my Chrome OS build:

Google Chrome: Version 99.0.4844.57 (Official Build)  (64-bit)
Platform: 14469.41.0 (Official Build) stable-channel eve
Channel: stable-channel
Firmware Version: Google_Eve.9584.230.0
ARC Enabled: true
ARC: 8205225
Enterprise Enrolled: false
Developer Mode: false

**Comment by FR1701** [comment]
Hi guys,

really good news. I can also confirm that with Google Chrome 99.0.4844.57 and KP2A 1.09c-r0 loading is working as expected again. Many thanks to all of you for your intensive testing and support.

**Comment by waaweech** [comment]
Closing since this issue was related to an apparent Chromebook Android apps bug, which has been fixed since the release of Google Chrome: Version 99.0.4844.57. The issue was unrelated to KP2A.

**Comment by numericOverflow** [comment]
@PhilippC I've had this issue for quite some time too, but just can't across this thread.

I am on the latest Chrome OS (104.0.5112.105) and tried both the most recent KP2A on Play (1.09c-r0) as well as the latest release here in Github (1.09d-r0)

I can't get passed the loading message without doing the min/max trick described above several times.

Was there a permanent fix intended, or was this just waiting for a fix in ChromeOS?

**Comment by waaweech** [comment]
@numericOverflow - As the original poster, I've not had any issues since Chrome OS version 99. For me, the issue was related to Chrome OS support of Android apps at that time which was affecting other Android apps as well. Is your DB size too large?

**Comment by numericOverflow** [comment]
@waaweech - my DB is under 3 MB, so I don't *think* that's the issue. I might try completely uninstalling/reinstalling the apk later tonight too see if that does anything.

**Comment by waaweech** [comment]
@numericOverflow - Mine is below 300 KB.

**Comment by waaweech** [comment]
> @waaweech - my DB is under 3 MB, so I don't _think_ that's the issue. I might try completely uninstalling/reinstalling the apk later tonight too see if that does anything.

Any progress?
