### ISSUE TITLE
No plugins with 1.09b-r1 version

### ISSUE THREAD

**Issue by Dr-Roger-Bro** [PhilippC/keepass2android#1886]
After updating from Google Play to the 1.09b-r1 version, the Keepass2Android app no longer supports plugins, such as KP2A Inpustick. I cannot type passwords anymore through the KP2A Inpustick plugin, while this works great with version 1.09a-r3.

**Comment by PhilippC** [comment]
fixed in 1.09b-r2

**Comment by Dr-Roger-Bro** [comment]
Hi Philipp, thank you for fixing it.I've just sent you a small donation of 20 euros to thank you.All the best ;-)Il 15 gen 2022 14:44, PhilippC ***@***.***> ha scritto:
fixed in 1.09b-r2
