### ISSUE TITLE
How to shiw the fingerprint mode

### ISSUE THREAD

**Issue by aileon85** [PhilippC/keepass2android#1889]
Hello!
First of all, happy good year!

I hace a problem, since I forgot the master password but ever I have entered through my fingerprint, but now the app no longer ask me for it, so how can I request in the app config to enter with my fingerprint again?

My ver: 1.08c-r1

Thanks in advance!

**Comment by PhilippC** [comment]
unfortunately this is not possible: it can happen that Android revokes the fingerprint access at some times - this is shown as a warning in the app and also stated in the docs. I hope you will remember the master password, that's the main way to access the database.

**Comment by gmotor82** [comment]
I have the same problem. 
What can i do now..?
I don't now my master password.
Br
