### ISSUE TITLE
Root certificate chain error

### ISSUE THREAD

**Issue by terrytw** [PhilippC/keepass2android#1891]
Hi dear Dev,

I have encountered a problem:

When connecting to my explicit FTPS server, a toast pops up saying "RootCertificateChainError" was encountered, although I am able to connect to the database without problem. 

I guess it has something to do with the fact that my certificate is issued by LetsEncrypt. It was fine several months ago, and it poped up in recent months. 

My phone is Oneplus 5T with Oxygen OS 10.0.2, Android 10. I have tried other phones with Android 9 and 8.1, and the same message pops up.

**Comment by PhilippC** [comment]
if the certificate can not be validated, you might need to install a certificate in your device settings. Does not sound like an app issue to me? Re-open if you disagree.

**Comment by terrytw** [comment]
My bad, there are couple of things that I did not clarify.

I can connect to the same database using windows desktop KeePass client without problem. The same certificate can be validated when accessed using web browser. It is only when using KeePass2android did I get the notification.

**Comment by PhilippC** [comment]
is this related? https://community.letsencrypt.org/t/lets-encrypt-certificate-is-reported-expired-on-android-10-private-dns-feature/161281

**Comment by terrytw** [comment]
Thank you, but it is not the same problem. I have already done what he did: change to ISRG root cert. 

I can access my FTPS server using winscp, the status shows that certificate is valid. 

My guess is that maybe keepass2android's FTPS implementation is not updated for ISRG certificate.

**Comment by terrytw** [comment]
My apologies, I thought I switched to ISRG, but my command was ignored by openwrt.
Apparently when openwrt-acme find unrecognized command it just ignores it, and --preferred-chain "ISRG" is not supported by openwrt-acme.
