### ISSUE TITLE
feature request: option to hide 'disable autofill for XYZ' menuitem 

### ISSUE THREAD

**Issue by Eddict** [PhilippC/keepass2android#1894]
hi. could you please add a setting to allow me to hide the 'disable autofill for XYZ' menuitem. i accidentally click it way too often and then it's quite a hassle to undo that. i love the autofill, except that annoyance. thanks!

**Comment by Indubius** [comment]
Guess it's there, as long as it's not only in the beta I'm participating... 😉

**Comment by PhilippC** [comment]
closed in 2c93fd15422d03f98c39f16297518e1ff031b8ea, duplicate of #1843

**Comment by PhilippC** [comment]
this is available in beta (1.09d)

**Comment by Eddict** [comment]
> this is available in beta (1.09d)

awesome, thanks!
