### ISSUE TITLE
I want the software to be able to generate a random passcode when signing up for a new account.  Want the button to be easy

### ISSUE THREAD

**Issue by Ngchpr** [PhilippC/keepass2android#1895]
Tôi nghĩ nó cần thiết

**Comment by PhilippC** [comment]
which change exactly do you suggest?

**Comment by Ngchpr** [comment]
Right now I don't know where to generate random password
Vào Thứ Hai, 3 tháng 1, 2022, PhilippC ***@***.***> đã viết:

**Comment by PhilippC** [comment]
if you edit an entry, click the "+"-button next to the password field.
