### ISSUE TITLE
Correct Password & Combo type repeatedly rejected

### ISSUE THREAD

**Issue by sperical** [PhilippC/keepass2android#1900]
Since the updates, I can't unlock the database using my correct password and password type combo.

I keep getting an error message stating "Invalid composite key please try again"

There was a longer message as well that I can't recall.

Before I could even get to the password stage I was instructed to fix a Google drive problem, which I did using the instructions provided (see attached)
![IMG-20220107-WA0000](https://user-images.githubusercontent.com/87528312/148475942-a4900db5-717b-473c-8409-9257a03d14b2.jpg)

Sync was established but access not provided.

I am using Android Galaxy S20 FE 5G
Update version 1.09b-r1

An update to above - Now the access to the database is revoked. 

See error message. I tred to access internal cache but still won't accept my password.

![IMG-20220107-WA0001](https://user-images.githubusercontent.com/87528312/148476164-235e94c2-e6ba-4c8f-8586-53febf3b9803.jpg)

Any ideas how to gain access to database again?

**Comment by PhilippC** [comment]
let's first start with testing the password: Please select Change database, then enable "Show local backups" and try to open one of the local backups. Does this work?

**Comment by sperical** [comment]
Thanks Phil. Yes that worked. I can access the local backup with my password.

**Comment by PhilippC** [comment]
please export the backup to a location of your choice (settings - database - export - kdbx). Can you then open the newly exported file?

**Comment by sperical** [comment]
Hi Phil, I successfully exported to One Drive but couldn't open the file. Message said it is corrupted.

I can't export to Google Drive I just get a blank screen in Keepass2 when I try.

What's next?

**Comment by PhilippC** [comment]
hmm, very weird. Can you export to a local file (using System file picker)?

**Comment by sperical** [comment]
Hi Phil. Yes that worked. It saved to my Google drive and I was able to open it in Keeppass from there.  Each time I use the app, I am prompted to select which database I want to use as there is the one I exported today and an older one.  Shpuld I just keep selecting the relevant database each time? Is it safe to delete the old database in Google Drive? 

I tried a test addition of a password. When I lock the database and reopen, I am prompted to open the database from Google drive and the new entry appears there. I don't get the message that the database s synchronized with the source file.  Is that because I am now working from the source file?

Is this arrangement OK to continue with or is there a risky downside?

**Comment by PhilippC** [comment]
you can safely remove the old file from the list of recent files in KP2A by selecting the small three vertical dots right to the filename, and of course you can also remove no-longer-needed data from GDrive itself. You can use a PC with KeePass2 to check if the latest data is stored correctly on GDrive, then everything is proven to work.

**Comment by sperical** [comment]
Hi Phil, me again. Hope you're well.  I posted a coupe of other problems- last was #1900. I started getting the following error message from June 16 2022 that I  have been ignoring but its not going away. 
"Could not save to source file:No content provider..."
I can't see the rest of the error message. I'm using Samsang Galaxy F20 FE 5G
I seem to be having constant trouble.  I sync to Google drive. 
I can't import to internal folder - or do anything else with the database. I get the same error. 
Version on my phone is 1.09c-r0.
Please help. Should I change the sync destination to something else? If so what would you suggest for someone who is at the basic end of semi tech literate?
Kind regards,Alison


Sent from Yahoo Mail on Android 
 
  On Sun, 23 Jan 2022 at 4:14 am, ***@***.***> wrote:   


you can safely remove the old file from the list of recent files in KP2A by selecting the small three vertical dots right to the filename, and of course you can also remove no-longer-needed data from GDrive itself. You can use a PC with KeePass2 to check if the latest data is stored correctly on GDrive, then everything is proven to work.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
