### ISSUE TITLE
Cannot add or edit any entries anymore - app practically unusable

### ISSUE THREAD

**Issue by t-dome** [PhilippC/keepass2android#1901]
Hello,

as of the latest version (1.09b-r1, updated on december 31 2021), I cannot add or edit any entries anymore.

The following error popup appears after tapping the save button:
_Access to the path "/storage/emulated/0/keepass/Database.kdbx. ... .tmp" is denied._

I didn't have this error before december 31 2021, because that was the last time I updated the app. Using Android 11.

The existing DB can be read without problems from the same directory, and I also exported the DB from within the application, and the file appeared in that directory without issue. So it doesn't seem to be a general Android permission issue. 

Thank you

**Comment by AmygdalaCryptoTeamZero** [comment]
same here. i 
Unfortunately I can not make a screenshot of the error message :/

**Comment by PhilippC** [comment]
can you try to disable file transactions in the app settings? (Note: this might cause data loss when saving gets interrupted, so make sure you have a backup process in place)

**Comment by t-dome** [comment]
Yes, disabling file transactions solved the issue, thank you. But it would be nice to have a safe fix; now I'm feeling like a DB admin who lowered the transaction isolation level just for the program to work somehow.

**Comment by PhilippC** [comment]
Android is getting more and more restrictive regarding accessing files. It seems like the app has access to `/storage/emulated/0/keepass/Database.kdbx` but not to `/storage/emulated/0/keepass/Database.kdbx....tmp`. Not sure why this is the case.

Regarding data security: KP2A will always keep the last successfully opened database as the local backup, so danger of data loss is quite limited.

**Comment by t-dome** [comment]
I don't understand. I have:
keepass/Database.kdbx
Which is the last opened database and which the backup?

**Comment by PhilippC** [comment]
keepass/Database.kdbx is the database file on the local storgae. If you use file transactions, KP2A will temporarily write to a .tmp file (and rename the .tmp to .kdbx when writing is complete). The local backup is stored in app internal storage .

**Comment by PhilippC** [comment]
I think the correct solution to this is to switch to using Storage Access Framework. To do this, please select Change database > Open file > System file picker and select your file again. This should give you a URL of type `content://...`.
