### ISSUE TITLE
autofill doesn't seem to be working at all

### ISSUE THREAD

**Issue by cindyc-il** [PhilippC/keepass2android#1905]
I'm using Keeppass2 Android.  The autofill kind of worked but now doesn't work at all.
Can someone direct me to where I can find instructions specific for ANdroid.  I'm not looking for custom solution, just for the autofill to work when I go to log into a website or app.

Thank you
Cindy

**Comment by PhilippC** [comment]
in the app, go to settings - app - password entry access - autofill service and make sure this is enabled

**Comment by cindyc-il** [comment]
Yes, it was enabled.  I tried turning it off and then back on.  Still
nothing.

Thanks
Cindy

**Comment by cindyc-il** [comment]
What's the most current version?  It looks like I'm on 1.09b-r1

**Comment by PhilippC** [comment]
which browser are you using? which website?
