### ISSUE TITLE
Reload DB in top level folder leads to logout

### ISSUE THREAD

**Issue by muxo771** [PhilippC/keepass2android#1909]
Pixel 6 Pro
v 1.09c-r0
quickunlock active yes.

A reload/resync (nextcloud/webdave) from the top folder leads to an logout. Database is synced, but required new login.
If I navigate into a folder/category one level down, and then start the reload/resync I will stay logged in.

**Comment by PhilippC** [comment]
I cannot reproduce. I open a database, select from the menu "Synchronize database", then I get the toast message "Remote file and local file are in sync" (or whatever the text translates to in English) and everything is fine. Did you make changes to the remote file?

**Comment by muxo771** [comment]
Have the same situation on my backup phone (Oneplus 9 Pro) Android 12 with the same database.

For testing I made new local database on the device and logged in. 

- Created new database with keepass2android. Quickunlock active.
- Changed to keepass2android-offline, open the database and add an entry under email.
- Switched to keepass2android, quickunlocked the database, reload (Datenbank synchronisieren) on the top level -> Logged out

- Relogged into the test db via keepass2android, quickunlock active again. 
- Added a further entry via keepass2android-offline to the test db.
- Quickunlocked the test db with keepass2android and dived into a sublevel (email). 
- Reload the db (Datenbank synchronisieren) on the sublevel and the db stayed open.

Made the same test with reverse setup with different result. 
Keepass2android-offline stayed open with reload on the top level.

**Comment by stefanschwall** [comment]
Got the same issue with 1.09b-r2. when the db is in sync everything is fine. The problem is when the remote db has changed.
