### ISSUE TITLE
Fingerprint Unlock Broken on Pixel 2

### ISSUE THREAD

**Issue by thatcort** [PhilippC/keepass2android#191]
The fingerprint reader doesn't work for unlocking my Pixel 2 phone. A red circle with an exclamation mark appears at the password prompt. Tapping the dot brings up an exception stack trace. I can't copy it or screenshot it, but here's the first few lines:

Error initializing Fingerprint Unlock:
Java.Lang.RuntimeException thrown at
keepass2android.FingerprintDecryption.Init()
...at keepass2android.PasswordActivity.InitFingerprintUnlock()
--- End of managed
Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher at md5f0702f46....PasswordActivity.n_onResume(Native Method) at...

I hope that's helpful. I'd love to see the fingerprint unlock feature working again!

**Comment by adamdehaven** [comment]
I had that issue on my Pixel 2 as well after installing the Beta version of the app. Long story short, disable fingerprint unlock in the app's settings, then re-check the box, then scan your finger when prompted. Fixed for me.
