### ISSUE TITLE
KP2A doesn't work for two-page logins

### ISSUE THREAD

**Issue by LaneLester** [PhilippC/keepass2android#1911]
I'm trying KP2A again to see how it's working. It seems I need the autofill plugin for my Android 9 Samsung Galaxy Tab S3. KP2A works fine for sites where both user and password fields are on the same page. But for sites like Amazon with user on one page and password on a second page, the app will not provide the password.

**Comment by PhilippC** [comment]
I suggest to either use Autofill plugin if your browser supports it or use the browser based workflow as described on https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md. Both support two-page logins.

**Comment by LaneLester** [comment]
Thank you, Philipp. I have the KP2A Autofill plugin installed, and it is not doing the job in the SmartCookieWeb browser I'm using right now. Later I'll check with some other browsers.

The workflow approach did work, although I had to work out a few details. I use the Hacker's Keyboard when I'm not using a physical keyboard. Here are the steps that worked for me (I'm saving them for future reference):
User page: KP2A should present the saved item.
Password page: If KP2A keyboard not active: Share / Find Password / Enable KP2A keyboard.
On KP2A keyboard, click Password button / Log in.

Lane

**Comment by LaneLester** [comment]
Nothing is easy. I needed a convenient way to switch between the Hacker's Keyboard and the KP2A keyboard. I installed the Keyboard Switcher app from APKpure, which does the trick... except that my setting for the one-line keyboard is ignored. The full KP2A keyboard doesn't have the User and Password buttons. Is there a way to access the Password function from the full keyboard?

Lane
