### ISSUE TITLE
KP2A doesn't respond to bank apps

### ISSUE THREAD

**Issue by LaneLester** [PhilippC/keepass2android#1913]
I have three bank apps. For Citibank, I created a KP2A record for the bank's URL. When I opened the app and clicked the User field, KP2A offered me the opportunity to find a record. I selected the one I had creaated and was offered the opportunity to associate the app with that record, which I did.
Unfortunately, the other two bank apps do not cause KP2A to do anything when I click in the User field. Are some apps programmed so they are not compatible with KP2A?

**Comment by PhilippC** [comment]
sometimes you need to long tap a field and select Autofill. If that doesn't work, please paste the Play store links on https://github.com/PhilippC/keepass2android/issues/1892

**Comment by LaneLester** [comment]
Long taps just bring up the copy/paste thing.
https://play.google.com/store/apps/details?id=com.usbank.mobilebanking
https://play.google.com/store/apps/details?id=com.pinnaclebank.mobile
