### ISSUE TITLE
Cannot open database anymore

### ISSUE THREAD

**Issue by schusterro** [PhilippC/keepass2android#1919]
I have the issue in https://github.com/PhilippC/keepass2android/issues/1901
I tried your comment: "I think the correct solution to this is to switch to using Storage Access Framework. To do this, please select Change database > Open file > System file picker and select your file again. This should give you a URL of type content://...."

That didn't solve the issue at all, the error is the same.

Moreover, after several closings + restarts of the application it doesn't ask for my fingerprint anymore. And I don't know the master password anymore, so now I completety lost all my passwords added in all these years! Either that, or something else broke in the application that it doesn't accept the master password.

Can I somehow bring the fingerprint checking back so that I can access the database for a last time?

**Comment by PhilippC** [comment]
sorry to say, but the master password is very important (the app and the docs warn not to forget it when you enable fingerprint). Android may sometimes revoke biometrics and the app cannot do anything about it.

I'm closing this as I don't think I can do anything here. Feel free to respond or re-open if you think.

**Comment by schusterro** [comment]
I remembered the correct master password in the meantime and it works now, includind the fix from [1901](https://github.com/PhilippC/keepass2android/issues/1901) with file transactions enabled.
I don't know why it took 10 app closings + restarts to take the database with the new "content://" format. I tried also with copies of the file but nothing... anyway, good that it works now.

**Comment by PhilippC** [comment]
glad to hear that!
