### ISSUE TITLE
Access to KDBX via WebDAV stopped working

### ISSUE THREAD

**Issue by georgekue** [PhilippC/keepass2android#1923]
Hi, 

presumably as of latest update (Jan 18, 2022), access to my KDBX file via WebDAV stopped working.

I keep getting 401 errors. Details: "Ein Fehler ist aufgetreten. Received unexpected response: Response{protocol=http/1.1, code=401, message=, url=https://webdav.mc.gmx.net/...}"

Verified my credentials twice, and also used another WebDAV client (RCX) on my phone: credentials are OK, access via RCX works.

Same problem on my corporate mobile.

Any hint?

Best regards,
georgekue

**Comment by aengel73** [comment]
Hello, 
the same with me here. I receive the same error message as georgekue. This started several days ago on all of my android devices. The webdav connection is to url https://sd2dav.1und1.de/....  

There are no issues when connecting to that webdav adress from my windows pc or when connecting from other android apps such as "solid explorer".  I'm on keepass2android version 1.09c-r0.
And yes - I have verified credentials several times ;-)

Any help highly appreciated.

**Comment by merlin694** [comment]
Hello!
Same issue with my account at gmx. But not with other webdav providers (tested vodafonemail). Deeper testing showed wedbav to gmx does not work when  kdbx open and sync is requested from menue. 
But, after 
- closing database and 
- changing something in kdbx from PC
- saving it to webdav resource and 
- opening again from handy a change was of source kdbx was detected
- a sync was offered and performed successful. 

My conclusion - gmx (this same provider for web.de, 1und1) has changed something on their side which interferes with specific sync operations when kdbx is open.

**Comment by aengel73** [comment]
Hello merlin694,
well I don't know if that is really the same issue that georgekue and I do have. Doesn't matter if I save the kdbx file from my PC on the webdav location or not in any case it will just throw the error message described above "Ein Fehler ist aufgetreten. Received unexpected response: Response{protocol=http/1.1, code=401, message=, url=https://...."  and I cannot sync the DB even not manually. I only can open the legacy local copy by choosing it from the list of "Lokale Backups anzeigen"

If you think that might be related to the provider, how can we figure out what might have changed ???
All other tools/apps and devices connected via webdav to the provider do work without any issue.

I can offer to provide some troubleshoot information - but do need some assistance on what to check or where to look.

Thanks and best regards.

**Comment by merlin694** [comment]
Hello @aengel73 
I had to rewrite my post a bit. Today it does not work in any way, also my specific "workaround" failed. I tested it with a different webdav provider vodafone and this worked flawless. I did this because web.de, gmx.de, 1und1 are all brands of  same provider.
I have not clue how to figure out what happened at gmx. My hope is that here somebody could help and advise (or hopefully fix it). If this cannot be fixed this week I will switch to a different webdav provider as my personal workaround. 
Keepass on my PC and other tools (like Totalcommander on PC and Android) have no issues.
In meantime I will also try to find out if there is a way to contact support at gmx (but I do not expect fast result).

**Comment by georgekue** [comment]
Just created a debug log. The respective passage reads (replaces user ID and password):

01.02.2022 14:23:27:7 -- SelectCurrentDbActivity.OnStop 7
01.02.2022 14:23:27:407 -- GroupActivity.OnStop 8
01.02.2022 14:23:27:410 -- GroupActivity.OnDestroyTrue 8
01.02.2022 14:23:29:75 -- https://:@webdav.mc.gmx.net/... isCached = False
01.02.2022 14:23:29:108 -- FileSelect.OnPause
01.02.2022 14:23:29:124 -- PasswordActivity.OnCreate 9
01.02.2022 14:23:29:124 -- PasswordActivity:apptask= 9
01.02.2022 14:23:29:213 -- GetIocFromLaunchIntent()
01.02.2022 14:23:29:214 -- no keyprovider specified
01.02.2022 14:23:29:216 -- Reset keyfile
01.02.2022 14:23:29:227 -- PasswordActivity.OnStart 9
01.02.2022 14:23:29:229 -- PasswordActivity.OnResume 9
01.02.2022 14:23:29:229 -- DatabaseIsUnlocked=True 9
01.02.2022 14:23:29:230 -- Timeout cancel
01.02.2022 14:23:29:233 -- starting: True, Finishing: False, _performingLoad: False
01.02.2022 14:23:29:234 -- https://:@webdav.mc.gmx.net/... isCached = False
01.02.2022 14:23:29:236 -- Pre-loading database file starting
01.02.2022 14:23:29:237 -- https://:@webdav.mc.gmx.net/... isCached = False
01.02.2022 14:23:29:237 -- CFS: OpenWhenNoLocalChanges
01.02.2022 14:23:29:292 -- PasswordModeSpinner item selected: 0
01.02.2022 14:23:29:385 -- found 80 in 81
01.02.2022 14:23:29:386 -- cannot autofill
01.02.2022 14:23:29:420 -- Received unexpected response: Response{protocol=http/1.1, code=401, message=, url=https://webdav.mc.gmx.net/...}
01.02.2022 14:23:29:422 -- https://:@webdav.mc.gmx.net/... isCached = False
01.02.2022 14:23:29:724 -- FileSelect.OnStop
01.02.2022 14:23:29:784 -- FileSelect.OnDestroyTrue
01.02.2022 14:23:33:182 -- PasswordModeSpinner item selected: 1
01.02.2022 14:23:33:182 -- key file length before:
01.02.2022 14:23:33:183 -- key file length after: 0
01.02.2022 14:23:41:666 -- PasswordActivity.OnPause 9
01.02.2022 14:23:41:667 -- Timeout start

**Comment by merlin694** [comment]
I talked to gmx hotline. They declined to have changed anything and no errors regarding webdav are known to them. 

I did a test with my other favorit tool Totalcmd for android with their webdav plugin. This plugin was changed lately and now you can select two different webdav-clients implementations "OkHttpClient" or "ApacheClient". With "OkHttpClient" I cannot login into gmx via webdav, although my password is provided in the settings I got asked several times for my password before connection is refused. With "ApacheClient" it worked flawlessly.

My concern is now that also keepass2android is using the implementation "OkHttpClient" which seems to have issues with gmx's implementation of webdav.

**Comment by Huebeni** [comment]
I can confirm the same issue using 1und1 sd2dav.

**Comment by Huebeni** [comment]
> I can confirm the same issue using 1und1 sd2dav.

Since yesterday the problem disappeared. Syncing my kdbx with 1und1 works fine again.
Also Total Commander is working again with OkHttpClient. 
Neither KeePass2 nor Total Commander was updated on my phone.

Can anyone confirm this?

**Comment by aengel73** [comment]
Hello all,
yes - I can confirm that since yesterday the access to my kdbx file with 1&1 is working again with keepass2android.
No clue what changed in between. The keepass2android version is still the same nor webdav settings on my devices have changed

**Comment by georgekue** [comment]
Good news! Yes; i can confirm this, too. Works again for whatever reason, obviously not a Keepass2Android issue. Thanks to all. Closing this now.

**Comment by merlin694** [comment]
can also confirm. working again with gmx.
