### ISSUE TITLE
Feature Request: Copy username/password/etc with single tap

### ISSUE THREAD

**Issue by JetPil0t** [PhilippC/keepass2android#1925]
In the iOS app Strongbox, there is a great feature where you can copy the password, username and some other fields (I don’t use them do not sure exactly which) to the clipboard by single tapping on them once the database is unlocked and entry is selected.

This is a very good usability feature.  Currently in KP2A it is necessary to use 2 taps to copy the password to the clipboard.

Many thanks for considering this.

**Comment by Tonny52** [comment]
If possible make the little pictures (person for username and key for password and others) active for copying.

**Comment by PhilippC** [comment]
I do not want to encourage using the clipboard. It should only be used very rarely for very insensitive data. It is insecure.
