### ISSUE TITLE
Hängt in "Prüfe, ob Zieldatei geändert wurde"

### ISSUE THREAD

**Issue by Pebberman** [PhilippC/keepass2android#1929]
Hallo, 
die Datei war auf dem ftp-Ort geändert worden. Lokal auf dem Android ebenfalls. 
Es kommt die Abfrage "... Zusammenführen?". In dem Augenblick schaltete sich irgendwine andere App im Handy vor den Dialog. 
Als ich zu keepass2android zurückkehrte, kam ich nicht mehr an den Dialog "Zusammenführen?, da der Prüfvorgang erneut startete. Dort bleibt die App hangen:
"in Bearbeitung... 
Speichere Datenbank...
(Prüfe ob Zieldateigeändert wurde)"

App abgeschossen, neu gestartet, bleibt wieder im der Anzeige hängen "in Bearbeitung ..."

App abgeschossen, neu gestartet, bleibt wieder im der Anzeige hängen "in Bearbeitung ..."

App abgeschossen, Flugmodus, neu gestartet, bleibt wieder im der Anzeige hängen "in Bearbeitung ..."

Deadlocked?

Viele Grüße
Pebberman

--english
Hello,
the file had been changed on the ftp location. Locally on the android as well.
It comes the query "... Merge?". At that moment, some other app in the phone switched in front of the dialog.
When I went back to keepass2android, I couldn't get to the "Merge?" dialog, because the check process started again. That's where the app gets stuck:
"in progress...
Saving database...
(check if destination file has been changed)"

App kicked out, restarted, stuck again in the display "in process..."

App kicked out, restarted, stuck again in the display "in progress ..."

App kicked out, flight mode, restarted, gets stuck again in the display "in progress ..."

Deadlocked?

**Comment by PhilippC** [comment]
duplicate of https://github.com/PhilippC/keepass2android/issues/996 (at least my comment https://github.com/PhilippC/keepass2android/issues/996#issuecomment-566854677)
