### ISSUE TITLE
Specific Folder on OneDrive - Make folder name changeable

### ISSUE THREAD

**Issue by swtrse** [PhilippC/keepass2android#1935]
There should be a way to Customize the Folder Name.
KeePass2Android is fine if you use only Android devices.
But for me using the same KeePass Database located at OneDrive on Android, Windows Phone, PC and IOs devices the folder name does make no sense at all.

**Comment by PhilippC** [comment]
as far as I understand, the folder name is the app name which is configured in the Azure Active Directory and which is e.g. used to display to the user which app has which access scopes to your OneDrive. For that reason, it is not possible to rename this to something more generic.
