### ISSUE TITLE
Donation cannot be done

### ISSUE THREAD

**Issue by Suncatcher** [PhilippC/keepass2android#1939]
I cannot open your page for making a donation

![photo_2022-02-23_11-52-27](https://user-images.githubusercontent.com/6388034/155296093-f4153273-287f-4d58-814b-0b6c56bd7b3e.jpg)

all my browsers and firewalls block such connections and prevent me from getting to your page. 
You'd better move to HTTPS, because your site looks phishy for many security guards

**Comment by GrantMoyer** [comment]
The donation page loads for me over https. You might be getting [MITM] attacked.

For example, it's common on corporate networks, where the re-encrypt the traffic using their own root certificate authority. Normally, they install the root CA on any device they own, but if you're using a personal device it won't (and probably shouldn't) have their CA, so it would reject the connection.

Does this issue occur on your home network?

[MITM]: https://en.wikipedia.org/wiki/Man-in-the-middle_attack

**Comment by PhilippC** [comment]
I agree that this seems to be an issue with your connection. the certificate is ok.
