### ISSUE TITLE
""Notification icon while unlocked" option does not remove notification. 

### ISSUE THREAD

**Issue by adamdehaven** [PhilippC/keepass2android#194]
Unchecking the "Notification icon while unlocked" option in Settings on Android 8.1 does not get rid of the non-dismissible (red) notification.

**Comment by PhilippC** [comment]
duplicate of #178

**Comment by adamdehaven** [comment]
I saw that issue but couldn't determine if it was the same root cause. :+1:

**Comment by renyhp** [comment]
I am still experiencing this issue, on Huawei P9 Lite, Android 7.0, KP2A v1.06f. It's not a real problem for me because I have disabled KP2A's notifications system-wide as a workaround. It might be a problem for someone else, though.
