### ISSUE TITLE
Biometrics unlock doesn't work on Samsung SM-A530F

### ISSUE THREAD

**Issue by massotn** [PhilippC/keepass2android#1943]
Dear Support,

I cannot enable the fingerprint unlock on my phone.

In the Setting > Database > Biometrics Unlock page, when I select one of the below 2 options:
 * Enable Biometrics Unlock for QuickUnlock
 * Enable full Biometrics Unlock
k2a displayes 'Please authenticate to continue' but putting my fingerprint has no effect...

Not sure if this issue is a duplicate of 1377...

Phone: Samsung SM-A530F (Galaxy A8 2018)
Firmware: A530FXXULCUK6/A530FOXMLCUK6/A530FXXULCUK6
Android: Version 9
Keepass2Android: version 1.09c-r0

Kind regards,
Nicolas

**Comment by massotn** [comment]
Dear Support,

The problem is that my preferred biometric authentication on my phoine is face recognition and not fingerprints recognition.
When I switch to fingerprints recognition, it is working fine...

Kind regards,
Nicolas

**Comment by PhilippC** [comment]
this is due to a decision from Google. they treat face recognition in some Samsung phones as too insecure for using it with Android's secure storage. Sorry, I don't think I can do anything about this.
