### ISSUE TITLE
Avoid search in backup

### ISSUE THREAD

**Issue by Thierryy1712** [PhilippC/keepass2android#1947]
When searching any word, he also search in "bachup" or in "sauvegarde" (if file has been created with a french version of keepass). A good option could be.. Group where i do not want to examine when searching. Because name could change depending of the language whre file has been created.. Thx !

**Comment by PhilippC** [comment]
are you using kdbx or kdb files? In kdbx, you can exclude groups from search. This is not possible to set in the app but in KeePass2 on PC. KP2A will respect the settings then. For kdb, this will not be supported.
