### ISSUE TITLE
Access to keepass db in shared pCloud folder

### ISSUE THREAD

**Issue by CrfzdPQM6** [PhilippC/keepass2android#1949]
It seems that Keepass2Android can only access a database in pCloud if:
1) it is in the path /Applications/Keepass2Android, AND
2) that Keepass2Android folder is owned by the pCloud account on the device

(2) effectively blocks sharing a folder between two pCloud users as far as Keepass2Android functionality is concerned.

Have I misunderstood? When I try to setup access to the folder with Keepass2Android on the second account, Kp2A just creates a new folder in /Applications/, ignoring the existing one called "Keepass2Android" but owned by someone else. Is sharing possible?

**Comment by PhilippC** [comment]
I'm not sure if this is possible with the Java SDK of pCloud. I created https://github.com/pCloud/pcloud-sdk-java/issues/33 to clarify this.

**Comment by CrfzdPQM6** [comment]
Thanks, @PhilippC , let's see if they reply (I see the reply-time is a couple of weeks sometimes). If not, I guess that excludes keepass db sharing on android devices, using pCloud. Would be happy not to have to revert to google... :(

**Comment by CrfzdPQM6** [comment]
Sounds like they fixed it! Fast work!

**Comment by PhilippC** [comment]
currently blocked by https://github.com/pCloud/pcloud-sdk-java/issues/34

**Comment by CrfzdPQM6** [comment]
Yes, I see. Thanks for trying the implementation so fast :)

**Comment by CrfzdPQM6** [comment]
Any luck with getting a release out that implements this? 

Thanks for all your work on this so far.

**Comment by user-elly** [comment]
I can also confirm this problem when trying to work with a keepass file that is shared by another account. (My workaround is currently to create a copy into the right folder by a script running in my PC. Just to have any old copy readable in case of emergency....)

But i would like to add another aspect if this functionality will be improved: **Please allow to use any pathname to configure**. On other platforms i use a more hidden place that obfuscates the purpose of the database file. The file itself appears in my case also as any harmless office document. I like it to give no hint to any intruders where to look for my secrets. The hard coded root folder in pCloud indicates directly where to search for relevant files. The encryption is already strong. But hiding is additional safety.

**Comment by user-elly** [comment]
> Any luck with getting a release out that implements this?
> 

Here was no repsonse posted. So i tried myself the latest beta channel version (1.09d-r0). 
Apparently it still does not work with a shared applications folder. I do get in parallel a new empty "Applications (2)" folder. And this is no longer shared on pCloud as it was meant to be. I mean.... use it back and forth synchronized.

Is there any release planned with this feature? Would be relly helpful when somone is working in pCloud environments.

**Comment by user-elly** [comment]
Using version 1.10:
- It is possible to access now any folder in pCloud. Thats very helpful. Thanks for that!
- but when i try to access any folder that has **another pCloud user shared with me** then it does not work. The shared folder is shown as empty. No files and no subfolders are displayed when i try to open/select an existing database there.

**Comment by PhilippC** [comment]
@user-elly I updated pCloud SDK last weeks which fixes this, but there is no release with that feature yet

**Comment by xgoisern** [comment]
It tried this feature but it doesn't seem to work! Did I miss something?

**Comment by user-elly** [comment]
> It tried this feature but it doesn't seem to work! Did I miss something?

Perhaps you could give more details on that what happens. I shared a folder on pcloud and the other person works seemless with the database there in the shared folder area. Are you are using the new method for access? See my screenshot.

![keepass-pcloud](https://github.com/user-attachments/assets/ea016d78-0b7f-4aea-ad2d-381174f07076)

**Comment by xgoisern** [comment]
Sorry, my fault! The last release of Keepass2Android was not installed! Now I can access the shared folder without any issue. Thanks for your help and providing us with this really amazing app!
