### ISSUE TITLE
Load on startup and don't unload

### ISSUE THREAD

**Issue by PaulGuijt** [PhilippC/keepass2android#1950]
Hi,

What is the easiest / best way to
1. load Keepass2Android at startup automatically and quietly?
2. prevent Keepass2Android from unloading until I close Android altogether? 
I can use Tasker, but that is perhaps not optimal.

Paul

**Comment by PhilippC** [comment]
I think tools like Tasker are well suited for this kind of automation. To prevent "unloading", please check if you have exempted the app from battery optimization, it should then not be closed while in the background.
