### ISSUE TITLE
feature req: save entry by default

### ISSUE THREAD

**Issue by nutpantz** [PhilippC/keepass2android#1953]
There are some times when I'm putting a new entry into my phone while I'm making it ona webpage on the desktop, and I'll be focusing on the desktop and the phone app will time out and close, losing everything i typed in so far into the phone keepass app.  
Which can be frustrating
It would be nice if any info entered into the app as a new entry was automatically saved on close switch and not most

**Comment by NumbGnat** [comment]
I opened the following issue back in 2018, that speaks to the same problem... 🤔 

[Issue #320](https://github.com/PhilippC/keepass2android/issues/320#issue-309794786)

**Comment by PhilippC** [comment]
closing as duplicate
