### ISSUE TITLE
Re-entering password after database sync is supposed to be so?

### ISSUE THREAD

**Issue by CodeJP97** [PhilippC/keepass2android#1956]
Hi,
after a recent update (can't tell exactly which), when syncing the database with a webdav folder, the program closes the database and one has to enter the master key again. Before the update this was not the behavior. Is this intended?
Kind regards
JP

**Comment by Eyion** [comment]
In addition, the password cannot be entered in Chinese. Is this a KeePass problem or an input method problem? As a result, the password can only be copied from other locations to the KeePass for pasting.
It's not easy to operate and it's a safety hazard, right?
