### ISSUE TITLE
Initial Notices Conflicting with Keyboard

### ISSUE THREAD

**Issue by NumbGnat** [PhilippC/keepass2android#1957]
I recently started having issues with the "initial notices" conflicting with the keyboard.

1. Notice of domain mismatch.
2. Question whether to save search result for future.

Rather than try to explain the steps to reproduce, I recorded the following video, showing what is happening in case 1 above.

https://youtu.be/9WICim9v-DY

Case 2 is the same result, but with the dialog you are presented, after searching for an item, when it asks if the user wants to remember that association for future searches.

**Comment by PhilippC** [comment]
I experienced this as well - I don't know a good solution yet (but usually got rid of the issue by switching back and forth a few times)

**Comment by NumbGnat** [comment]
Okay. Hopefully we can find a resolution.

This makes it impossible to associate new entries to applications. After minimizing the keyboard, the dialog is missing, but KP2A is sitting there, as if it's still waiting for the response...

**Comment by NumbGnat** [comment]
I just had this happen with the dialog that asks you if you want to remember the association from a search result.

Steps to reproduce:

- Open the login page for a web site that you don't have any associations for.
- Use the [Fill with KeePass2Android] button on the key board's autocomplete bar.
- Search for an entry in your database.
- Select an entry from the search results.

>>> KeePass2Android prompts with a dialog box asking if you want to remember that entry the next time. The dialog box is hidden behind the keyboard.

- Tap the 🔽 button on the Android navigation menu

>>> The keyboard minimizes, but the dialog box disappears.

**Comment by jason-phillips** [comment]
I am also experiencing this issue, specifically with the confirmation window after a search. 

How I've been getting around it is I select add new entry even if I really want an existing entry, copying the text for the app one custom field that it would have written into the entry that I want, Going to the entry that I want, and making that custom field. Then when I close it down and reopen it again, it's now associated with the entry that I want and it auto-populates. Definitely a pain in the butt. 

I didn't have this issue before, so I'm wondering if it's something in the OS that updated that broke it or an update in keypass. 

Pixel 5, Android 12.
Build SP2A.220405.003
