### ISSUE TITLE
A very easy one

### ISSUE THREAD

**Issue by EricOuellet2** [PhilippC/keepass2android#1968]
When you display database, please ensure you display the full path of the database, mainly when on google drive.

**Comment by PhilippC** [comment]
I don't see why this is necessary. If you have several databases, KP2A will show the path on the QuickUnlock screen, in the database selection screen, in the recent file lists and it also shows the database name/root group name in the title of the root group.

Please re-open with a good reason :-)

**Comment by EricOuellet2** [comment]
I currently have the primary copy of the database and a backup in another folder but with the same name, into google drive. 
If I'm not wrong, I don't see the full path when the database is in a folder of google drive. I would be required in order to distinguish which database you open when presented to the user.
It could also be usefull to be able to have a status (which database is currently open with the full path) in order to ensure we work on the proper database.
For the moment I will modify the name of the database to ensure I'm on the good one.
Your product is very nice!!! Thanks!!!
