### ISSUE TITLE
On samsung Galaxy S21 FE, I can't use my finger print while it was working on Xiaomi Redmi Note 10 pro

### ISSUE THREAD

**Issue by EricOuellet2** [PhilippC/keepass2android#1969]
On samsung Galaxy S21 FE, I can't use my finger print while it was working on Xiaomi Redmi Note 10 pro

**Comment by mak163** [comment]
I have S21+, but there were no problems with the fingerprint scanner

**Comment by PhilippC** [comment]
@EricOuellet2 what exactly do you try and do you get? Did you go to settings - database - biometric unlock?

**Comment by SimonsPure** [comment]
Also have the same issue. I believe it to be an issue with the latests Google update. I've had a bunch of biometrics apps not work, buit some (and my lockscreen) still do.

**Comment by EricOuellet2** [comment]
My bad, sorry. it was not in full biometric.
