### ISSUE TITLE
Cannot access kdbx file on Google Drive: "the name must not be empty: null"

### ISSUE THREAD

**Issue by anta40** [PhilippC/keepass2android#1984]
On Pixel 3 (running stock Android 12), accessing kdbx files on Google Drive works fine.
But on Pocophone F1 (running Android 10), there's an issue: "the name must not be empty: null"

I already authorized the app to access my Google Drive, though.

![kpx_gdrive_f1](https://user-images.githubusercontent.com/16976/165922084-4d830782-5ec4-4515-985e-188290528c22.jpeg)

**Comment by Liturgist** [comment]
I have this same problem on Samsung Galaxy A53 5G. It is working well on Samsung Galaxy S7 Edge.
Android version 12

**Comment by PhilippC** [comment]
please see https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254
