### ISSUE TITLE
how to remove obsolete entries from the "select database" menu?

### ISSUE THREAD

**Issue by gpion** [PhilippC/keepass2android#1991]
Hello,
I've recently moved my main database to another location.
But It still appears in the _"select database"_ menu
How can I clean up entries I'm not using anymore there?

BTW I just noticed that I've also duplicates entries here, I would like to be able to get rid of those too.

**Comment by gpion** [comment]
Clearing app cache didn't succeed.
But after having restarted device it seems OK now

**Comment by PhilippC** [comment]
you can remove entries from the list of recent files by tapping the three vertical dots next to the filename.

**Comment by gpion** [comment]
Il not referring to the recently opened databases list but to the currently opened databases.
No vertical dots there :
![iMarkup_20220514_100352](https://user-images.githubusercontent.com/2971216/168417094-21e0ebdc-edc8-4c10-a592-174980b69618.png)

In my case one is a test database would like to get rid of.
There is no "close database" menu option.
And everytime I launch KeePass I've to make a selection on that "select database" menu.

**Comment by PhilippC** [comment]
you need to lock and the select "Close database" on the quick unlock screen
