### ISSUE TITLE
Autofill erweitern, damit es auch bei der App "Ladeverbund+" funktioniert

### ISSUE THREAD

**Issue by mattuschek** [PhilippC/keepass2android#1994]
Hallo,

da Du noch nicht auf meine Frage in meiner Rezension hier
https://play.google.com/store/apps/details?id=keepass2android.keepass2android_nonet
reagiert hast, melde ich mich nun auf GitHub.

Ist es möglich, Autofill zu erweitern, damit es auch bei der App "Ladeverbund+" funktioniert?
https://play.google.com/store/apps/details?id=de.chargecloud.solid

**Comment by PhilippC** [comment]
added to the list on https://github.com/PhilippC/keepass2android/issues/1892
