### ISSUE TITLE
How can I export the database backup from /data/user/0... to another place?

### ISSUE THREAD

**Issue by aquarius222** [PhilippC/keepass2android#1995]
Obviously it's not possible to export the local database backup at /data/user/0/keepass2android_nonet/no_backup/content... directly in Keepass2Android. This would be an enormous benefit, when the normal database is corrupt?

**Comment by PhilippC** [comment]
you can open the backup file from KP2A (select Change database - enable "Show local backups"), then select Settings - Database - Export - kdbx.
