### ISSUE TITLE
ReadMe.md on front page doesn't work - 404's

### ISSUE THREAD

**Issue by incIined** [PhilippC/keepass2android#2]

**Comment by PhilippC** [comment]
Do you mean the file itself or any link in it? The readme is displayed for me on the front page of https://github.com/PhilippC/keepass2android or also https://github.com/PhilippC/keepass2android/blob/master/docs/README.md

**Comment by incIined** [comment]
For me, clicking on "view all of readme.md" on https://github.com/PhilippC/keepass2android links me to a 404.

**Comment by PhilippC** [comment]
hmm, I don't see such a link. can you post a screenshot?

**Comment by dliuzzi** [comment]
I'm also seeing this and I agree; seems a bug on GitHub's part. I couldn't find where to post an issue about this, so I've [hit them up on Twitter](https://twitter.com/danielliuzzi/status/912295162088476672). Hopefully they'll fix this shortly.

**Comment by PhilippC** [comment]
closing this as this is a confirmed bug at Github.
