### ISSUE TITLE
"Offline" version does not save kdbx file.

### ISSUE THREAD

**Issue by unclecircuschris** [PhilippC/keepass2android#200]
The offline version does not seem to automatically save the database back to the kdbx file, and I cannot find a save button.  Am I missing something?
Thanks :)

**Comment by PhilippC** [comment]
how did you open the file? Through a third party app? Which one?

**Comment by unclecircuschris** [comment]
I tried opening the file in keepassdroid, and I also tried copying the file (via usb) back to my pc and opening it in keepass2 on the pc. I have added extra entries on my phone and want to copy it back to my pc so I can use it on both.

**Comment by PhilippC** [comment]
I mean when you opened the kdbx file (the one you are editing) in Keepass2Android, what did you select after "Open database"?

**Comment by unclecircuschris** [comment]
Ah, I think I've figured this one out...  It appears to be related to the other issue I raised...
"keepass2android offline" not really offline? #177

Sorry for my ignorance, but I didn't actually understand your explanations on that issue (or on the other issue you referenced: #86), but from what I understand now, "Work Offline" actually means "don't save back to file" (I had this option checked).

To be honest, I don't really understand why this option exists (why would you not want to save the file?) or why it's named this way (it's not about working online/offline; it's about saving to a local file) and as a dumb user, "working online" in an "offline" application still fills me with dread, but at least I now understand.

(FYI, if you're still interested, I opened the file through "System File Picker").

(And by the way, apart from this one confusing option, I love the app, and really appreciate the hard work you've put into it, so Thanks!!!!)
