### ISSUE TITLE
KP2A shows OTP secret and TOTP when only wanting to show TOTP

### ISSUE THREAD

**Issue by SkyKwas** [PhilippC/keepass2android#2008]
When I want to see the TOTP code in my database for two-factor authentication, KP2A exposes that and the OTP secret.

Oddly enough, the OTP and TOTP sections have their own "show password" button (the three dots on the right side). But, when I only want to view the TOTP (the 6-digit code) by selecting "show password" under TOTP, the OTP (the secret string that is used to create the TOTP generated codes) also gets exposed.

I find this sightly annoying because the TOTP gets pushed down due to the long string of the OTP.

I also find this to be a security concern as there is no reason to show the OTP secret except to make a copy/backup. It is also possible to accidentally copy the OTP secret instead of the TOTP.

Can there be a fix for this by showing the OTP and TOTP independently?

**Comment by PhilippC** [comment]
this is fixed in 1.09d-r0 (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by SkyKwas** [comment]
I assumed the problem was fixed when you closed it (and it probably is for the regular version), but I forgot to mention that I'm using the offline version of the app.

When I check my codes in "Keepass2Android Offline", the secret still pops up.
