### ISSUE TITLE
Add a way to specify my own SSH key with SFTP

### ISSUE THREAD

**Issue by john01dav** [PhilippC/keepass2android#2009]
This is a great app, but in my use case it's better if I can provide a private SSH key (e.g. by opening the file browser and selecting a id_rsa or id_ed25519 file) rather than having to use the one that keepass2android generates. I tried poking around in the settings to see if I can override which key it is using and provide my own, but I could not find any way to do so.

**Comment by Zerowalker** [comment]
Does keepaas2android have any ssh key support, i can't find anything?
So not sure what you are talking about here, i have just used ssh with KeePass2XC to load into the ssh-agent,
which seems to be what you mean here but on android.

Just asking out of interest as i am fan of using SSH keys when possible;p

**Comment by john01dav** [comment]
> Does keepaas2android have any ssh key support, i can't find anything? So not sure what you are talking about here, i have just used ssh with KeePass2XC to load into the ssh-agent, which seems to be what you mean here but on android.
> 
> Just asking out of interest as i am fan of using SSH keys when possible;p

It does. When you open a file, you can select "SFTP (SSH File Transfer)" at which point it will give you a public key to add. Presumably it randomly generates this on the app, but I see no reason that we can't just enter a private key here instead, hence the feature request.

**Comment by SkA4kOv** [comment]
I totally agree! It would be much better if I could import my private key. Or give a choice, generate the program itself or specify it yourself. I myself already wanted to make a similar proposal, but since it already exists here, and not one, then I'll just sign it here.

**Comment by dmiraj** [comment]
Yeah, it would be a nice feature

**Comment by PhilippC** [comment]
resolved in https://github.com/PhilippC/keepass2android/releases/tag/v1.10-pre
