### ISSUE TITLE
[Feature Request] Allow user to select the app language

### ISSUE THREAD

**Issue by LeonelF** [PhilippC/keepass2android#201]
Allow the user to select the prefered language in settings so the app doesn't use the native OS language.

**Comment by vdenisov** [comment]
+1 to that

**Comment by aXe1** [comment]
👍 
Where the translation is not ideal - language setting would come in place :)
Unfortunately, there are no system settings for such changes on per-app basis. Even in LineageOS.
So, it would be great to have in-app choice…

**Comment by aXe1** [comment]
AFAIK it's doable, but not straightforward at all. See the [article](https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758).

**Comment by LeonelF** [comment]
I wasn't aware of technical stuff behind it. Well I will still help with a good translation into my native language when needed :P

**Comment by CoooolRaoul** [comment]
The referenced article is about changing system default language on the fly.
The request is about being able to permanently set app language independently of global Android default. 
Since there are number of apps wich include such option in I guess it shouldn't be difficult to do.

**Comment by gpion** [comment]
The referenced article is about changing system default language on the fly.
The request is about being able to permanently set app language independently of global Android default. 
Since there are number of apps wich include such option in I guess it shouldn't be difficult to do.

**Comment by PhilippC** [comment]
my preferred solution to this is to improve bad translations: https://crowdin.com/project/keepass2android

**Comment by gpion** [comment]
> my preferred solution to this is to improve bad translations: 
Hope you won't mind I not agree with that (and I guess many others users will too)
To take my personal case, my native language is French and that's the default global setting I'm using on my phone since it's most suitable for general usage apps (like news, calendar, weather, social, etc ...)
Anyway, for "technical" applications (and your's definitively falls is in this category), I always prefer using English when available. I find it especially essential when looking for help online since most users use that language: googling for French translations of error message and app settings items is most of the time useless.

**Comment by aXe1** [comment]
My usage scenario is the same as @gpion said, except my native language is Russian. Also strings in Russian are typically much longer. So, as I have no problem reading in English, I definitely want to use English for many apps.
Also, I understand that this is not the only valid case, and good translation would be the most welcomed variant for many other people.

**Comment by PhilippC** [comment]
I understand. It.s explained in https://stackoverflow.com/a/2900144/292233 how to do it.

**Comment by gpion** [comment]
> It.s explained in https://stackoverflow.com/a/2900144/292233 how to do it.

Just seen this. Unfortunately I'm not an Android développer and so really unable to build a wrapper app around yours (is it even feasible?) to run it in a different locale context.

**Comment by gpion** [comment]
> my preferred solution to this is to improve bad translations: https://crowdin.com/project/keepass2android

Just tried your "prefedred solution" (not mine BTW) to check if I help to fix some truncated message texts.
Sample: 
![screenshot](https://i.imgur.com/GnXUzEV.png)

But I'm not sure if I'm able to manage this without breaking things.

Still no hope to have language selection available in the app in the future?

**Comment by PhilippC** [comment]
> Still no hope to have language selection available built in in the app in the future?
I added this feature to a future milestone, so don't let your hope die. Unfortunately I haven't found a lot of time to work on the app in the last months, I wish I could improve it faster...

**Comment by PhilippC** [comment]
for reference: this is available through settings - app - display - app language

**Comment by gpion** [comment]
> this is available through settings - app - display - app language

But not yet available on the official released version 1.09a-r3. 
(Since I use Keepass for my professional data too, I prefer staying on the safe side and not switch to beta)
