### ISSUE TITLE
[Feature Request] Make use of Trashcan 'Recycle bin'

### ISSUE THREAD

**Issue by ShapeShifter499** [PhilippC/keepass2android#2010]
Today I deleted an entry without realizing why I had it only to remember what it was for later. I couldn't easily restore it without resorting to my file backups. On my desktop I make use of KeePassXC which has a 'trashcan' feature. It has an option to store deleted entries into a 'Recycle Bin' which you can then permanently have removed later. Unless I'm missing something, Keepass2Android doesn't do this. Is it possible to include such a feature?

**Comment by waaweech** [comment]
The "Recycle Bin" is already implemented. All my deleted entries end up in that folder by default.

**Comment by ShapeShifter499** [comment]
It did not seem to work here and I don't see any feature in the settings to turn on

**Comment by waaweech** [comment]
I would make sure to save a copy of my database somewhere safe and outside of the KP2A folder on the device, uninstall and reinstall the app to see if the "Recycle Bin" shows up. As I mentioned I've always had it. In fact when I want to delete any entry, it always asks me if I want to delete it permanently or to send it to the "Recycle Bin". The screenshot of the message is attached here:
![Screenshot 2022-06-10 10 19 20 AM](https://user-images.githubusercontent.com/55951150/173090062-bbed1317-8f42-4c66-a5fd-d04cd38f1c42.png)
.

**Comment by ShapeShifter499** [comment]
I'm going to close this. This was a PEBCAK error on my behalf. I'm sorry.

**Comment by ShapeShifter499** [comment]
For posterity, must have been tired and clicked through prompts. 

Testing on my end shows it works fine. Even so this is why you should keep backups.
