### ISSUE TITLE
Can I make keepass2a make sync in the background to my local backup automatically? 

### ISSUE THREAD

**Issue by slendermon** [PhilippC/keepass2android#2017]
Hello, I'm wondering if it is possible to autosync, because I just recently reset my laptop and backed it up. And I forgot to sync my changes in the database. Sorry, this is my fault. 

I've seen quick unlock automatic sync feature, somewhere else as an issue in here. Does it prevent this from happening?

**Comment by PhilippC** [comment]
if you store your database on a remote location and open it from there, KP2A will write all changes to the remote location immediately. Is this what you are looking for?

**Comment by slendermon** [comment]
Yes, thanks, maybe I'll try putting it on usb flash drive or cloud storage
