### ISSUE TITLE
ⴰⵣⵓⵍ

### ISSUE THREAD

**Issue by BoFFire** [PhilippC/keepass2android#202]
ⴰⵣⵓⵍ,
Is the application capable technically to generate passwords other then in latin ASCII to add more entropy ?
Example mixture of Tifinagh and Arabic :

ⵣⵇ3_ⵝتⴷ@%ⵇqWⵛⵙظلⵟ

Best regards,

**Comment by PhilippC** [comment]
Currently this is not supported and I don't think it's much better than simply increasing password length.

**Comment by BoFFire** [comment]
Ok, closed.
