### ISSUE TITLE
Feature Request: Hide otp field if TOTP field is enabled

### ISSUE THREAD

**Issue by Rookiestyle** [PhilippC/keepass2android#2033]
After having selected an entry to fill in e. g. form fields, all the entry's attributes are shown and one can navigate back and forth to pick the required one.

If an otp value has been calculated, the TOTP field/button is added.

Can you please give this button higher priority and show it right after the password button and/or can you hide the otp  button?

I don't think the otp button is required in this case. At least I can't imagine a use case where I need to input the otpauth string anywhere.

**Comment by PhilippC** [comment]
I understand that this is referring to keyboard only, not the entry activity, right?

**Comment by Rookiestyle** [comment]
Yes
