### ISSUE TITLE
Closing the database requires at least 4 clicks

### ISSUE THREAD

**Issue by mcaay** [PhilippC/keepass2android#2036]
1) swipe from top
2) click arrow
3) click "LOCK DATABASE"
4) click arrow
5) click "CLOSE DATABASE"

This is annoying when done 20 times a day.
Is it possible to just close the db with no more than 2 clicks?
Perhaps a setting like "automatically close the db after locking".
I never need the intermediate step that exists between locking and closing.

The experience is great except for this.

**Comment by UmBottesWillen** [comment]
You can disable QuickUnlock in the settings. When opening your databasee again, it should lock as soon as the app is closed.

**Comment by mcaay** [comment]
That works 100% as I had hoped! Thanks a lot!
