### ISSUE TITLE
[Feature Request] Adaptive Icon

### ISSUE THREAD

**Issue by rodrigoswz** [PhilippC/keepass2android#204]
Adaptive Icons is a feature of Android Oreo that is gradually being adopted by all Android applications. It is an icon that adapts according to the native shape of the system, making all the icons of that device combine with each other.

Fortunately, the KP2A icon is perfect for this feature, since it is a white icon with a shadow and a shape. Then it will not need any creativity or work for a new icon. I would recommend using the colors used in the icons I made last year (shown below). 👍

![image](https://user-images.githubusercontent.com/14058427/34834665-b87a89ca-f6d9-11e7-8782-f5c8d742368d.png)
Source: https://plus.google.com/+rodrigosowza/posts/Gxt2eZVuzyP

### More info: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by PhilippC** [comment]
nice work, @rodrigoswz . BTW do you have the vector graphics for the logo?

**Comment by rodrigoswz** [comment]
@PhilippC unfortunately I do not have these files anymore. I did this a long time ago, I could do it again but my computer is under maintenance at the moment. Sorry :disappointed:

**Comment by gregorydk** [comment]
I remade the icons from scratch.

![icon_keepass2android_online_gh](https://user-images.githubusercontent.com/7804464/36267644-b545bffc-1274-11e8-8f4b-f6add2553937.png)

![icon_keepass2android_offline-gh](https://user-images.githubusercontent.com/7804464/36267643-b525d296-1274-11e8-845d-096164e9dfec.png)

**Comment by PhilippC** [comment]
thanks @gregorydk , but I was able to create the graphics as vector drawables.
