### ISSUE TITLE
Play Store description has broken link to ITS (codeplex)

### ISSUE THREAD

**Issue by Chealer** [PhilippC/keepass2android#2050]
As reported in tickets #75 and #150, the description on Google Play contains a link to an ITS no longer accessible on Codeplex, http://keepass2android.codeplex.com/

> Rapports de bug et suggestions : http://keepass2android.codeplex.com/

**Comment by gpion** [comment]
Still not fixed

**Comment by PhilippC** [comment]
I don't see this:
![image](https://github.com/PhilippC/keepass2android/assets/5421734/2e591ca4-bd04-481d-916f-36a7a54dd715)

Can you please provide a URL and a screenshot? Maybe also the language you are using?

**Comment by ikanakova** [comment]
> I don't see this: ![image](https://private-user-images.githubusercontent.com/5421734/293709016-2e591ca4-bd04-481d-916f-36a7a54dd715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDUyMDksIm5iZiI6MTcwNDIwNDkwOSwicGF0aCI6Ii81NDIxNzM0LzI5MzcwOTAxNi0yZTU5MWNhNC1iZDA0LTQ4MWQtOTE2Zi0zNmE3YTU0ZGQ3MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMTQxNTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI0MjZiNDNhYmI2MDdmNzNlM2U1YzUyNGM0NmE3ZjE3MGI4ZWE5M2FiM2VhZDI5NDRkZDNjNzExMTg2ZWJjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X7HhBQ6o-Z5EcZVKXUDqKl07iWtd1XpY605rdIuTXx4)
> 
> Can you please provide a URL and a screenshot? Maybe also the language you are using?

French:
https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=fr
Czech:
https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=cs

**Comment by PhilippC** [comment]
you are right. I only checked a few others...

I fixed it (might take  a few hours to appear on Google play)

**Comment by Chealer** [comment]
Aha, I missed that. Thanks @ikanakova and @PhilippC it's indeed fixed for at least French and Czech.
