### ISSUE TITLE
Unwanted OTP secret shown fix to be applied in offline version

### ISSUE THREAD

**Issue by SkyKwas** [PhilippC/keepass2android#2054]
Hi, I opened a previous issue where the OPT secret codes are shown when wanting to view the TOTP codes.

The issue is "KP2A shows OTP secret and TOTP when only wanting to show TOTP #2008"

This has been fixed and closed, but this fix seems to only apply to the regular version, not the offline version (which is what I use).

**Comment by 121tech** [comment]
-Bump-

Using KeePass2Android v1.09c-r0 (green icon)

While viewing an entry then either long-pressing or using the  ⋮  (menu option) on any hidden field entry to select options, the first option of "Copy to clipboard" works as expected, copying ONLY the viewed field entry of the field selected to the android clipboard ...but the second option of "Show password" doesn't work as expected and converts all hidden field entries (Password, otp, TOTP, etc.) to be revealed, where I expect only the TOTP, and maybe a visual countdown timer, to be revealed when interacting with the TOTP field.

I have been using the cloud-based AUTHY (Twilio) app, but as cloud-based LastPass recently had their client vaults stolen I thought I'd be be better off not relying on cloud-based services but using my KeePass2 vault for TOTP as well. 

There are times when it's quicker to visually see the TOTP info from my android phone to be entered into a second device keyboard, so I'm used to seeing in seeing a large display of the calculated Time-based One Time Password next to a time-remaining token expire countdown timer (pie clock or reducing line) to aid me.

Thanks for listening.

**Comment by PhilippC** [comment]
this has been fixed in the meantime
