### ISSUE TITLE
[Android 13] Clipboard data needs to be marked as sensitive

### ISSUE THREAD

**Issue by metronidazole** [PhilippC/keepass2android#2058]
With Android 13, anything added to the clipboard is previewed on screen. As per the docs, anything sensitive such as passwords should be flagged with "android.content.extra.IS_SENSITIVE" so that the OS does not display them: 

See 
https://developer.android.com/about/versions/13/behavior-changes-all
https://developer.android.com/guide/topics/text/copy-paste

**Comment by garpunkal** [comment]
Is this why I'm getting "contents can't be autofilled" on certain password dialogs now?

**Comment by joshjama** [comment]
#bug can not connect to next Cloud
I get the following error if I wanted to connect to my nextcloud instance. 
Fehler
Kann nicht zum Datei-Dienst verbinden.  Received unexpected response: Response{protocol=h2, code=401, message=, url=https://220823v5iaqrstmqgm4.nextcloud.hosting.zone/remote.php# /webdav}
