### ISSUE TITLE
TOTP: Individual input fields for each digit (example Paypal)

### ISSUE THREAD

**Issue by WebworkrNet** [PhilippC/keepass2android#2064]
**KP2A**: Version 1.09d-r0
**Device**: Samsung Galaxy XCover 4s (SM-G398FN)
**Operating System**: Android 11

Some websites and apps have set up the TOTP entry in such a way that there is a separate input field for each individual digit of the OTP. Paypal recently switched to this variant.

I currently see no way to transfer the one-time password to the app or website via the KP2A keyboard.

In this case, I guess I have no choice but to manually transfer the code from KP2A.

Would it be possible to adapt the direct and more comfortable insertion via keyboard?

Thanks

**Comment by WebworkrNet** [comment]
![Screenshot_20220828-155807_Fennec](https://user-images.githubusercontent.com/43509007/187078392-a5bfed3b-60a8-4607-a3ae-7baadbff9adb.jpg)

**Comment by WebworkrNet** [comment]
In the specific case of Paypal, direct input via the keyboard now works (Android app & web). Since Keepass2Android has not been updated in the meantime, but PayPal has updated the app at least once since the opening of this case, I assume that the payment service provider will also have adapted its website accordingly or that its Android app will fall back on changes made to the website.

**Comment by jonuns** [comment]
An other example of a still not working website with individual otp fields is epicgames.com the first field is filled the second stays empty(space?) The third one contains a character again. The cursor ends in the fourth field.

**Comment by PhilippC** [comment]
while I understand that it is helpful for users manually inputting TOTPs to make the display large, I consider it a bug in the target app/website if they use multiple fields for entering one value (i.e. the TOTP code), that's semantically not correct. While it may be possible to find workarounds to deal with this, they should fix their input fields (as paypal did).
