### ISSUE TITLE
[Feature Request] link app.url with existing database entry

### ISSUE THREAD

**Issue by dehein** [PhilippC/keepass2android#207]
I want to link or even save an additional app.url into the password database.
So i can just save my genericwebsite.com password and use the same password inside the  genericwebsite-app. Which should look something like: com.genericwebsite.app 

Maybe after using the fill out password feature and using the search you may be asked to link this entry with the app?

**Comment by PhilippC** [comment]
If you use "Share URL" from the browser, KP2A will search for a matching entry. If there is none, you click "Select other entry" and navigate to the entry. KP2A will then ask if you want to remember the search. 
The same thing happens if you search for an entry through the KP2A keyboard or when using Oreo Autofill.

**Comment by dehein** [comment]
Would probably be a good idea to promote this more. Show it in a tutorial, or change the text, because for me it was not obvious that "select other entry" would lead me to link it with the app.url.
But thanks for the working implementation.

**Comment by RT483b** [comment]
I just now learned this. Question if in KP2A and you click URL which then takes you to site and then from the browser click menu and the "Share URL",  is this process done using the android clipboard or is part of KP2A alone. In other words is this safer like with AutoFill or is it just the standard clipboard?

**Comment by PhilippC** [comment]
both Share URL and Autofill do not use the clipboard and can be considered safe.
