### ISSUE TITLE
Hide clipboard preview on Android 13

### ISSUE THREAD

**Issue by gerdablum** [PhilippC/keepass2android#2071]
Hi!

I recently updated my phone to Android 13, and now copied passwords are shown in the new clipboard preview as clear text.
There is a way to obscure sensitive content in the new preview: https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent

**Comment by AriehSchneier** [comment]
Duplicate of #2058

**Comment by PhilippC** [comment]
marking as duplicate
