### ISSUE TITLE
Development stalled?

### ISSUE THREAD

**Issue by Offerel** [PhilippC/keepass2android#2074]
Since there is no new commit since February, i ant to ask if this project is still alive?

**Comment by garpunkal** [comment]
Same, would be good to know either way.

**Comment by bkev** [comment]
I hope not as this is one of the most important apps I've got. But it would be good to know too.

**Comment by tortuosit** [comment]
Also interested. Maybe Dr. Crocoll is simply more busy in his regular job. Happens.

**Comment by PhilippC** [comment]
The company I have been working for was aquired earlier this year by a large German automotive company and we are now being integrated into that company. As a group leader, I'm quite a bit involved in this process.

Apart from that, there are some challenges and changes regarding family and personal life keeping me busy after work. 

I definitely didn't decide to give up work on KP2A but right now I don't have the resources to do development work. Even answering all support emails is difficult. Sorry about that, hope I'll find time again soon.

**Comment by Offerel** [comment]
Many thx for the statement. Good to know this wonderful app is not dead. I can fully understand your point since I was in the same boat some years ago.

Take your time. Family and job is much more important and good luck with the new company.
