### ISSUE TITLE
[Feature Request] Setting to auto-forget recently opened databases

### ISSUE THREAD

**Issue by Sanaki** [PhilippC/keepass2android#208]
While being able to select recent databases is obviously useful, that also provides a clean list of every database and keyfile to anyone who has access to the device. It would be helpful to be able to enable a setting to never remember opened databases, or even just to not append the history while the setting is enabled (with the option of clearing it if so).

**Comment by PhilippC** [comment]
app settings -> security -> remember database file

**Comment by Sanaki** [comment]
Ah. My mistake. Couldn't get into settings and had no memory of that being there. Thanks.
