### ISSUE TITLE
[Question] How to stay focused on the parent database when opening automatically a child database?

### ISSUE THREAD

**Issue by kud** [PhilippC/keepass2android#2084]
Hey,

I've configured two databases where I've got one main and another one secondary.

When I use Keepass2Android, it focuses on the secondary database. I would like to stay focused on the main database.

Any idea how?

Thank you

**Comment by temaoz** [comment]
Hi,

I think that is not possible yet because KP2A doesn't support focus restoration, see issue [#1845](https://github.com/PhilippC/keepass2android/issues/1845).

**Comment by kud** [comment]
Thank you  @temaoz 😌
