### ISSUE TITLE
[Feature request] Support tall screens

### ISSUE THREAD

**Issue by Madis0** [PhilippC/keepass2android#209]
[This Google blog post explains, how](https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html). Thanks in advance!

**Comment by StevenZezulak** [comment]
I am using a galaxy S8+ and the app fills the screen automatically. Which device are you using? If it is a Galaxy device, you can allow individual apps to run full screen in the settings menu (if you're not prompted to when you first launch the app).

**Comment by Madis0** [comment]
Samsung and many other OEMs stretch apps artificially with software to fit the screen. That doesn't make sure it actually _works_  100% in that height, so it would be much better if the developer implemented the required manifest values and tested it, to make sure.

**Comment by StevenZezulak** [comment]
I definitely agree, but as far as I know Samsung's solution is not stretching, but a sort of on the fly edit of the manifest. Videos get stretched and cropped, as with some games, but all the apps with regular UI components I've used the setting with actually do resize properly and display more content.

I've taken two screenshots of keepass2android in both modes and there is more content shown when Samsung's option to fill the screen is enabled.

**Comment by Madis0** [comment]
Fixed in 1.05-pre1.
