### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by KATalyzt75** [PhilippC/keepass2android#2090]
Hi there. Since KeePass2Android has more options in its templates, I can't import them all into KeePassXC (On Windows) and I can't display them correctly, or I can't give Android new PC values. Is there any way (or extension) to fix this?

**Comment by NumbGnat** [comment]
There are features of KeePass2Android that are not currently supported by KeePassXC. You should probably bring this up in the KeePassXC Github...

https://github.com/keepassxreboot/keepassxc

**Comment by PhilippC** [comment]
the template system of KP2A is compatible with KpEntryTemplate plugin for KeePass2 on Windows. As @NumbGnat said, you can request compatibility of KeePassXC with that as well. I don't consider this an issue of KP2A.
