### ISSUE TITLE
Android 13? Password not entered in screen, clipboard copy exposes password for several seconds

### ISSUE THREAD

**Issue by cto-mike** [PhilippC/keepass2android#2102]
Noticed this change since Android 13, some apps have split user / password where only user is entered by keepass2android keyboard while password remains blank.   Mostly notice this in banking / credit apps, since no auto-login, even when both user and password are on the same screen.  

There are other cases like Amazon app where user is correctly entered in user field, then the next screen the password has to be entered but there is no option to auto-fill with the app.

Workaround to both is to switch to keepass2android, find the entry, copy to clipboard, then go back to app then paste.  In this case Android 13 shows the password for at least 5 seconds with share icon in lower left (clipboard overlay / editor) which is alarming in a public setting.  Now having to remember to **cover the screen with hand**, which is less than ideal.

**Update:** a bit of googling shows this https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#java

_Add sensitive content to the clipboard
If your app allows users to copy sensitive content, such as passwords or credit card information, to the clipboard, you must add a flag to ClipData’s ClipDescription before calling ClipboardManager#setPrimaryClip(). Adding this flag prevents sensitive content from appearing in any content preview show in the copy visual confirmation in Android 13 and up._

**Update 2:** must have been blind or search keywords not good, did not see the other similar issues opened until going through them one at a time:

[1]
Failing to enter password for Chase Credit Card App #2079
Contents can't be auto-filled #2059

[2]
[Android 13] Clipboard data needs to be marked as sensitive #2058
Hide clipboard preview on Android 13 #2071

**Update 3**  unfortunately no option to turn off Clipboard overlay editor.  Seems to be a common problem for password managers.  https://support.google.com/pixelphone/thread/181160916?hl=en
_You can send feedback from Settings->About phone->Send feedback about this device to let the development team know_  to other readers, please send feedback that Clipboard overlay editor needs a disable option for privacy until apps catch up.

**Comment by PhilippC** [comment]
IMO these issues have all been addressed in the meantime
