### ISSUE TITLE
Keepass2Android Old Icon Set: Support for 64-bit

### ISSUE THREAD

**Issue by ghost** [PhilippC/keepass2android#2110]
Hey Philipp,

I would like to use the Old Icon Set in my Pixel 7, but the app is currently a 32-bit app and not installable. Would you like to provide a 64-bit variant?

Thanks,
derflasher

**Comment by heuligeuli** [comment]
👍 same problem here (Pixel 7, too).
Usability of the old icon set is much better.

**Comment by kaczorws** [comment]
Bumping thread, I too prefer old icons as they're in line with desktop KeePass and it is no longer possible to install on Pixel 7 Pro. Any chance of recompiling this in 64-bit? Thanks :)

**Comment by Nemonyme** [comment]
I also used the old icon set...
... Until my Pixel 7.

Would be great to have a new 64 bits version.

But anyway, thanks for this great tool.

**Comment by PhilippC** [comment]
I created https://github.com/PhilippC/AncientIconSet and requested an update, currently pending Google's approval.
