### ISSUE TITLE
On Android 13, copied passwords are shown in plaintext 

### ISSUE THREAD

**Issue by daven-que** [PhilippC/keepass2android#2137]
Ref: https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent

See the section "Add sensitive content to the clipboard"

When using the copy to clipboard menu item with a password:
![Screenshot_20221202-163410](https://user-images.githubusercontent.com/12043264/205392847-714ae004-059c-4b70-899e-589c4c9637c7.png)

the password is shown in plaintext:
![Screenshot_20221202-164006](https://user-images.githubusercontent.com/12043264/205394737-71701af6-61c3-49d4-a2cf-454b660b3c82.png)

**Comment by waaweech** [comment]
Yes, I confirm this is an issue with KP2A on Android 13.

**Comment by PhilippC** [comment]
duplicate
