### ISSUE TITLE
TOTP 1-field 'otp' vs. 2-field 'TOTP Seed'/'TOTPS Settings'

### ISSUE THREAD

**Issue by CaptainBalou** [PhilippC/keepass2android#2152]
Hello all together,

I tried to find an answer for this for hours but I wasn't successful with that. I also haven't seen if there is a place like a discord channel or so. So sorry for opening an "issue" here.

I'm using Keepass on Windows with Kee TrayTotp Plugin and Keepass2Android. Both are able to generate TOTP entries but somehow in a different way. Maybe this is by intention, maybe I'm doing something wrong.

On Windows I generate a TOTP entry by clicking on an existing entry and using the TrayTotp menu to add TOTP fields to this entry. After doing so I have two more fields which are TOTP Seed and TOTP Settings. Then I sync the database and Keepass2Android is using them without any problem. I can use TOTP 6-digit numbers on which device I want. Perfect.
But when I go the other way like using my Keepass2Android to generate TOTP fields into an entry it behaves different. If I click on "configure TOTP" just one field named 'otp' is generated. In Keepass2Android it's working fine, but syncing the database over to Windows it doesn't do anything because the needed fields ...Seed and ...Setting are missing.

Is it possible to tell Keepass2Android to generate those two fields instead of the one 'otp'? Otherwise I would end up in two different fields/mechanisms depending on where I've generated them.

Kind regards
Marco

**Comment by PhilippC** [comment]
there is a similar request in https://github.com/PhilippC/keepass2android/issues/2295 but requesting to write yet another format. I decided for the standard Key URI Format. Please ask other app/plugin developers to support this as well or switch to KeepassXC which does.
