### ISSUE TITLE
Autofill Custom Field in Browser

### ISSUE THREAD

**Issue by jstiete** [PhilippC/keepass2android#2154]
Hello,
regarding to my recent issue #2144 I wanted to check, if it is possible to autofill custom fields in the browser.

I found this website which needs a customer ID, username and password: [https://www.cleverreach.com/de-de/login/](https://www.cleverreach.com/de-de/login/) 
But I am not able to create any working keepass entry in my database. 

Can someone please check, if autofill of the customer ID is possible with Keepass2Android (on that website)?
Or can someone send me a working keepass entry/template for any other website that needs additional fields?

**Can Keepass2Android handle/autofill custom fields at all?**

Thanks in advance. Jan

**Comment by NumbGnat** [comment]
This used to be available when using the KP2A keyboard, but that feature stopped working a while back. I've documented that in Issue #1980.
