### ISSUE TITLE
Automatically Open Last Used Database

### ISSUE THREAD

**Issue by Jugoshwa** [PhilippC/keepass2android#216]
Is it possible to add a new option so that KP2A can remember and automatically open last used database on startup instead of selecting a database everything?

**Comment by aeilkema** [comment]
Whould like this too.

(Opened a new topic by accident, didn't see this one)

**Comment by PhilippC** [comment]
This is currently due to the way the Google Drive API is implemented. If you can switch to Dropbox or Onedrive, the issue should be gone. I leave this open to maybe fix this in the future.

**Comment by jkaberg** [comment]
I'm using WebDAV and would also like to see this (remember database URL, username and password for the connection to the KeePass DB)

**Comment by jkaberg** [comment]
@PhilippC so I was reiterating over what you wrote and from what I understand  there's a bug with Google Drive which prevents it from auto opening kdbx files stored on Goolge Drive? Am I correct?

That would mean that it should work on other storages backends like Webdav, sftp etc? It does not in my experience - closeing down Keepass2android or rebooting mean you will need to renter all details regarding last opened database (which is a real pain if you use WebDAV with a long password). IMO this is a real deal breaker for me :-/

**Comment by PhilippC** [comment]
can you please check if you have enabled "remember database" in the security settings?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
its done, issue can be closed

**Comment by gpion** [comment]
> can you please check if you have enabled "remember database" in the security settings?
It's "on" for me but not woarking. Since I've opened a test database, I'm unable  to get rid of the database selector
![image](https://user-images.githubusercontent.com/2971216/97410029-d1781600-18fe-11eb-9eac-77d821618fd5.png)
I'm going to reset app data to fix this but that embarassing

**Comment by PhilippC** [comment]
Looks like you have opened several databases.
can you close (lock, then close) all open databases which you don't want?

**Comment by gpion** [comment]
> Looks like you have opened several databases.
Exactly, to make a test for a demo to a colleague.

> can you close (lock, then close) all open databases which you don't want?
I've only locked using the padlock icon (I'm unable to locate how to "close" )
And the chooser stills appears when launching keepass.
Meanwhile I'me made a full reset of app (erase storage). Obviously it worked but  I was searching for a simple way to do it.

I was looking for a way to have keepass "forget" the 2nd database

Now I've reopened the second database and again facing the issue.

**Comment by PhilippC** [comment]
you can use the KP2A notification: pull down the notification bar of your device. depending on the device, you might also need to "extend" the notification by pulling it also down, so you see the "Lock database" button. (This is the same as the lock button in the app). After tapping it, do the same thing again,but now it is a "Close database" button. After that, KP2A will ask you to fully unlock whatever database you want.

**Comment by gpion** [comment]
> ou can use the KP2A notification: pull down the notification bar of your device

Thanks, that I've done meanwhile and it worked (I thought having replied but probably closed browser without post validation)
Maybe a "close database" item in the dropdown menu (even it it duplicates the notification button) could be more practical.
