### ISSUE TITLE
"Master key type" not remembered if "Password + Key file + Challenge-Response for KeePass XC" is used

### ISSUE THREAD

**Issue by mitohund** [PhilippC/keepass2android#2160]
If I choose to use a password AND a key file AND a YubiKey, then I have to choose the appropriate "master key type" every time I open the app. Additionally, the location of the key file is also not remembered - so that requires a few clicks as well.

Practically speaking, this means I can't use this option. Too many tech-unsavvy users in the family that would not know what to do.

Maybe related to #975?

Phone: OnePlus 7
Android version: 11
KeePass2Android version: 1.09c-r0

**Comment by masterElmar** [comment]
Same problem here would be nice if this could be fixed.
Only the Master-Key-Type, Key file location and the two checkboxes (quickunlock & internel cache) need to be saved.

Phone: Poco F3
Android: 12
KeePass2Android version: 1.09c-r0

**Comment by mitohund** [comment]
Is there a chance that this will be implemented? I've actually switched to KeePassDX because of this, but would totally switch back again.

**Comment by AlexCherrypi** [comment]
fixed it with #2345

**Comment by PhilippC** [comment]
closed in https://github.com/PhilippC/keepass2android/pull/2345
