### ISSUE TITLE
[bugfix] Auto lock should not engage if adding or editing an entry

### ISSUE THREAD

**Issue by aetonsi** [PhilippC/keepass2android#2178]
Hello

At the moment, when adding a new entry, if a timed autolock (eg after 30 seconds) is set, the database is simply locked and the entry is lost forever without a trace. This is pretty annoying...
This happened to me a few times because, for a reason or another, sometimes it takes me a while to fully register to a new website, but the very first thing i do in K2A is generate a password and copy it into the website registration field. But when i complete the registration process, if the autolock engaged, the entry is lost and the password is not even saved in the android keyboard history (as expected).
As in [keepassxc](https://keepassxc.org/), if autolock engages while in edit mode, a small popup window should be presented to the user, asking to discard changes, save changes, or cancel the locking.

---

Have a nice day

**Comment by NumbGnat** [comment]
This is referenced in Issues #320 & #1953.

**Comment by PhilippC** [comment]
closing as duplicate
