### ISSUE TITLE
Username entered in app, but not password

### ISSUE THREAD

**Issue by TimB1023** [PhilippC/keepass2android#2184]
Issue:
Keepass2Android enters the user name in apps (e.g. LinkedIn), but does not enter the password. Keepass2Android is set as the default Autofill service. If I tap in the password box, an Autofil tooltip appears, but nothing is entered when I tap on it. There is a password for the app stored in the kp database.

Configuration etc:
V 1.09c-r0
Galaxy S22 Ultra, latest software (Android 13, One UI 5.0)
kp DB stored in dropbox
Gboard keyboard (Keepass2Android icon offered for user name, but not password)
Keepass2Android had worked previously on this phone, but stopped working after a factory reset required for a screen repair.

Happy to supply any further information as needed.

**Comment by BiuZero** [comment]
I also encountered this problem, I think it may be that this software has not been adapted to Android 13, because I use another software to automatically fill, https://github.com/AriaLyy/KeepassA
My configuration:
V 1.09d-r0
K60PRO, Android 13, MIUI14

**Comment by Kusi-Schweiz** [comment]
Ich habe dasselbe Problem seit Android 13.
Getestet auf OnePlus 8, Oppo Find X3 Pro und Google Pixel 7 Pro.

**Comment by Theangelo2** [comment]
Same Problem here, with Android 13 the autocomplete system not working.

Hope the developer can fix this problem as soon as possible, thanks

**Comment by ikanakova** [comment]
I have the same problem in Samsung Galaxy A53, Android 13.

**Comment by JMW882** [comment]
I have the same problem. Samsung Galaxy S23+.

**Comment by dwhitman3** [comment]
Same problem.  Pixel 6 Pro.

**Comment by Offerel** [comment]
Same behavior here with Galaxy S20FE, A53, A52, S23, S23+. All with Android 13. The problem does not occur on a Huawei Phone with Android 11. KeePassDX is working fine for the same procedure. The issue does not occur with every app.

**Comment by TimB1023** [comment]
Excellent - thank you Philipp! I look forward to the update.

**Comment by TimB1023** [comment]
I've just updated from an S22 Ultra to an S24 Ultra (SM-S928B/DS, running One UI 6.1, 6..1.25 Kernel) and the problem has returned. Keepass2Android (ver 1.1-pre) is set as the preferred autofill service. It provides the user name, but not the password

**Comment by PhilippC** [comment]
@TimB1023 can you share an app where this behavior occurs for you?
