### ISSUE TITLE
Suppress "Entry is available" notifications on wearable devices

### ISSUE THREAD

**Issue by proski** [PhilippC/keepass2android#2185]
When I open an entry in Keepass2Android, a notification appears both on the Android device and the connected smartwatch. The notification text is "Entry is available through KP2A Keyboard" and the options on the watch are "copy user", "copy password" and "copy TOTP".

I believe that notification should not be bridged to wearable devices for two reasons:

- The notification should always appear as a result of user actions on the Android device. Bridging the notification to wearable devices distracts the user from the current action.
- The results of the selection (e.g. "copy password") remain only on the Android device (in the clipboard). There is no such scenario that the user opens an entry on Android, sees something on the watch and uses it elsewhere (e.g. on a PC), as no secrets are shown on the watch (which is the right thing to do).

I believe the notification should be marked as local-only, as described at https://developer.android.com/training/wearables/notifications/bridger

My setup:
Motorola Moto G Power (2021)
Android 11
Garmin vivoactive 3
Keepass2Android 1.09d-r0

**Comment by AriehSchneier** [comment]
You could just turn off notifications for Keepass2Android for your Garmin? [see here](https://support.garmin.com/en-AU/?faq=TLeDN92ZU0AgN4df6HakwA)

**Comment by proski** [comment]
Yes, I can. My point is that good apps do the right thing without having to be configured, let alone blocked from sending notifications. I was pleasantly surprised that I'm only getting notifications on the smartwatch that make sense on the smartwatch. For instance, I get notified about upcoming alarms, but not of the fact that I'm using a navigation app.

The notification from Keepass2Android is an exception, it's distracting me from what I'm doing on my phone, that's why I have reported it.
