### ISSUE TITLE
keepass2 no third party App

### ISSUE THREAD

**Issue by captain8836** [PhilippC/keepass2android#2202]
Keepass2 tried ver 1.09c and 1.09d when selecting Open File there is now no option to select "third party App" to open the .kdbx file. I Installed 1.09d hoping it would have "third party app" but it was not there it did have the new options PCloud and MEGA. Had to go all the way back to keepass2 ver 1.09a-r3 before finding a ver that has the "third party App" option.
Phone Samsung S21 FE Android 13
I read looking for a solution but could not find one and thought I would ask here if anyone knows how to resolve my issue.

Thank You

Screen shot from keepass 1.09c
![Screenshot_20230125_131203_Keepass2Android](https://user-images.githubusercontent.com/123596748/214692031-968df4c6-7979-4f82-8090-f97c2184e10e.jpg)

Screenshot from ver 1.09d
![Screenshot_20230126_015751_Keepass2Android](https://user-images.githubusercontent.com/123596748/214808375-8763eee9-3e9c-4a50-8927-abd8f5110a77.jpg)

Screenshot ver 1.09a-r3
![Screenshot_20230127_124852_Keepass2Android](https://user-images.githubusercontent.com/123596748/215198384-e9b20303-69bf-4852-8cf6-e8997ee4f311.jpg)

**Comment by PhilippC** [comment]
third party app access is causing more and more trouble on recent Android versions which is why this was removed. Use "System file picker" instead.
