### ISSUE TITLE
Hide copied text in clipboard floating window in Android 13

### ISSUE THREAD

**Issue by kolbasky** [PhilippC/keepass2android#2206]
I have an  issue with new android 13 feature: floating window of clipboard. idk how it is actually named, but the thing is - when you copy text, it is immediately displayed in a small floating window on your screen.
So when i copy some password from keepass - it is shown on my screen in plain text. Which is not good :-)

I have searched through all the settings in keepass2android and in android itself, but haven't found anything useful.
The phone is Asus Zenfone 9 - if that matters.

**Comment by PhilippC** [comment]
fixed in 1.09e (currently in beta channel: https://play.google.com/apps/testing/keepass2android.keepass2android)
