### ISSUE TITLE
Notifications disappeared in latest beta version 

### ISSUE THREAD

**Issue by zan2828** [PhilippC/keepass2android#2208]
Notifications disappeared in latest beta version in Android 13. Therefore selected entry as well as option to lock database from notification tray is gone.

In app notification settings the slider is set to off and cannot be re-enabled. I have attached a screenshot.
![Screenshot_20230131-105735](https://user-images.githubusercontent.com/10559230/215856387-6299be63-2f30-4457-9ed3-4f0eab140056.png)

**Comment by PhilippC** [comment]
fixed in 1.09e-r1
