### ISSUE TITLE
Support for Yubikey Neo's static password mode

### ISSUE THREAD

**Issue by mydexterid** [PhilippC/keepass2android#221]
Hi!

It seems that the app does not support yubikey's static password mode. Whenever I swipe the neo on the nfc reader it opens the web browser instead of inserting the static password in the password field.

According to this: https://developer.android.com/guide/topics/connectivity/nfc/nfc.html
an app has to request permission to use NFC (android.permission.NFC), but grepping through the code (even though it is mainly not in java) I couldn't find anything related to requesting the NFC permission.

Maybe this is one of the issues leading to not reading the nfc tag?

**Comment by mydexterid** [comment]
Digging further I found this:
https://keepass2android.codeplex.com/workitem/140
Where you actually implemented this feature in commit: 6b4d31aa44330cac7ebc2ed76d9e56441817251c

But it seems that it stopped working some time ago? https://keepass2android.codeplex.com/workitem/620

**Comment by mydexterid** [comment]
It also could be that it needs a new intent filter, like what yubiclip did in this patch:
https://github.com/Yubico/yubiclip-android/commit/5f566cd291a0f41cdc27b45e8f48df3d69d8b428#diff-a48d6def78e18cbabab3c95ae3c9fc49R61

**Comment by mydexterid** [comment]
So I've managed to build the app (with a lot of ups and downs), added the same intentfilter as yubiclip:
https://github.com/Yubico/yubiclip-android/commit/5f566cd291a0f41cdc27b45e8f48df3d69d8b428#diff-a48d6def78e18cbabab3c95ae3c9fc49R61
without the autoVerify.

The only thing I managed to achieve with this is the passwordactivity displaying "(One or more OTPs already available)" when I touch the yubikey to the NFC reader and the key type is Password + OTP.
When I choose Password or Password + Key file for the type unfortunately nothing happens, no static password is insterted into the password entry.
Also I had to choose 'Open in this app' in Android settings->Apps->App links->Keepass2Android for it to even display in the app chooser dialog when the yubikey is touched to the NFC reader.
Something else needs to be done for this to work, but I can't figure it out yet.

**Comment by mydexterid** [comment]
@PhilippC 
Soo.. I managed to figure out what is going on. I'm not creating a merge request for now mainly because the patch needs to be discussed first.
1. First of all it needs the default handler for the url. So it either needs this:
```
<intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data
                    android:scheme="https"
                    android:host="my.yubico.com"
                    android:pathPrefix="/neo"/>
</intent-filter>
```
for the PasswordActivity or it needs this:
```
[IntentFilter(new [] { Intent.ActionView },
              Categories = new[] { Intent.CategoryBrowsable, Intent.CategoryDefault },
              DataHost = "my.yubico.com",
              DataPathPrefix = "/neo",
              DataScheme = "https")]
```
for the NfcOtpActivity.

The first issue is that according to your comment here: https://github.com/PhilippC/keepass2android/blob/master/src/keepass2android/PasswordActivity.cs#L142 intents go to AndroidManifest.xml but
the `.gitignore` file contains `/src/keepass2android/Properties/AndroidManifest.xml`. Why is that?

2. When you add the default url handler intent, it cannot be set to autoVerfy=true, so the user has to manually set keepass2android to 'Open in this app' in Android settings->Apps->App links->Keepass2Android.

3. This https://github.com/PhilippC/keepass2android/blob/master/src/keepass2android/PasswordActivity.cs#L1776 needs to be moved out of the `if` to right above it, because the `else` also needs it. Without this, when the static password is read from nfc, `onResume` is called and from it `ClearEnteredPassword();` is called (depending on user settings) which immediately clears the password entry.

I'm hoping you can include this in your next release.

**Comment by PhilippC** [comment]
@mydexterid thanks for your work! AndroidManifest.xml is excluded because it is chosen based on the release type from one of the files in https://github.com/PhilippC/keepass2android/tree/master/src/keepass2android/Properties

**Comment by mydexterid** [comment]
@PhilippC I see. Do you need me to create the patches, or you're good to go?
Also keep in mind that setting the `_keepPasswordInOnResume = true;` in step 3 probably only a good solution if the app chooser really appears for the user (so after that onResume is called). If they set k2a as the default handler for the url, the chooser won't appear, and most probably onResume won't be called, so in this case `_keepPasswordInOnResume` will still be true. I don't know if this would introduce other bugs, or it doesn't matter.

**Comment by PhilippC** [comment]
I will try to integrate the changes, but haven't looked at the details yet. Might be nice if you create a pull reqeust, but I can do it without as well.

**Comment by mydexterid** [comment]
Created pull request #270.

**Comment by mydexterid** [comment]
@PhilippC Did you have time to take a look at this?

**Comment by PhilippC** [comment]
merged in

**Comment by cwolters** [comment]
@electrofloat @PhilippC 
While adding the same intent as the YubiClip App, the YubiClip App now stops working if both apps are installed.
It looks as if you should put in a priority for the intent so that yubiclip is winning.

Or - make it configurable so that the NFC tag is not read by default with  keepass2android.
Or - make keepass2android to use the same logic of yubiclip so that there is no need to have two apps installed and the static or otp passwords are placed in the clipboard. 
Currently an error is shown (otp_discarded_because_no_db) - if used anywhere except in the unlock dialog.

**Comment by PhilippC** [comment]
@cwolters can you please open a new issue for this?

**Comment by electrofloat** [comment]
@cwolters The code has already been modified in: https://github.com/PhilippC/keepass2android/issues/564

https://github.com/PhilippC/keepass2android/issues/564#issuecomment-473827651
