### ISSUE TITLE
bank virtual keyboard

### ISSUE THREAD

**Issue by hug956** [PhilippC/keepass2android#2212]
To consult our online accounts, banks often offer a virtual keyboard whose keys change places after each identification phase.
In the Keepass2android application, can you offer, in addition to the "user/password/url/note/name/app" buttons, a button whose name would be the password that would contain the 4 or 6 digits requested by the bank . In this way we will be able to read these numbers and we could type them on the virtual keyboard.

**Comment by PhilippC** [comment]
closing as duplicate of #556
