### ISSUE TITLE
Nonet package broken, doesn't install

### ISSUE THREAD

**Issue by tenzap** [PhilippC/keepass2android#2222]
When trying to open the apk to install nonet it fails and doesn't install it.

v1.09e-r1

Same problem on android emulator:

![image](https://user-images.githubusercontent.com/46226844/217546786-fa366e31-c019-4406-9637-13f627103110.png)

**Comment by PhilippC** [comment]
which apk are you referring to? The one from github releases or Github actions or Google Play?

**Comment by tenzap** [comment]
The one from github releases

**Comment by IzzySoft** [comment]
@PhilippC you forgot to sign the `nonet` APK, my updater complains as well:

    No signing certificates found in repo/keepass2android.keepass2android_nonet_189.apk

Also see [here](https://github.com/PhilippC/keepass2android/issues/38#issuecomment-1426871922) and #2233

**Comment by PhilippC** [comment]
fixed with https://github.com/PhilippC/keepass2android/releases/tag/v1.09e-r3

**Comment by IzzySoft** [comment]
Confirmed thanks! Just wondering why the `nonet` flavor now includes "Google Services for Google Drive" (`com.google.android.gms.drive`)? No network permissions, though, so it mostly just looks confusing.

**Comment by tenzap** [comment]
Thanks! Happy to see the new nonet version with many improvements (compared to the previous nonet version)

**Comment by IzzySoft** [comment]
Thanks for explaining, @PhilippC! Maybe there's a way to exclude that? It's obviously not used (at least not for what its name suggests – as how could it without network access), so removing shouldn't™ break things.
