### ISSUE TITLE
Reset lost password with fingerprint

### ISSUE THREAD

**Issue by Shimon33** [PhilippC/keepass2android#2230]
Hi,

I'm using keepass2 on android as well as on a laptop.
I currently unlock my database using my fingerprint and it works.
So I have access to all my data.

But I forgot my master password.

Is there any mean to reset the master password ? 

Thank you for your help.
Simon.

**Comment by Shimon33** [comment]
Ok guys I found the way to get my database back without the masterkey only with the android app and the fingerprint unlock feature.
Once it's unlocked with the finger print on the android device we have the ability to export the data base without any password. 

Then you can easily set a new password to secure this exported DB.

Hope it will help.

NOTE :  if you don't have the fingerprint unlock feature set properly, and so no access to your vault, I'm afraid you won't be able to recover your data.

**Comment by PhilippC** [comment]
you can also change the master key after unlocking with fingerprint. The app does warn that you shouldn't forget the master key, I don't know what else I could do :-)
