### ISSUE TITLE
keepass2android.keepass2android_nonet-1.09e-r1.apk on page https://github.com/PhilippC/keepass2android/releases is not signed. Can't install or upgrade app

### ISSUE THREAD

**Issue by FranLa** [PhilippC/keepass2android#2233]
As mentioned it seems keepass2android.keepass2android_nonet-1.09e-r1.apk on page https://github.com/PhilippC/keepass2android/releases hasn't been signed. So I can't install it / upgrade the existing version (which is unfortunately since the version on Google play is quite old (1.08d-r5) so I was looking forward to this upgrade of the offline version)
I would be glad if you could sign it if possible. Thanks

**Comment by Boebbele** [comment]
Same here.

**Comment by Boebbele** [comment]
Nonet Version is not installable. also at a new installation

**Comment by PhilippC** [comment]
fixed with https://github.com/PhilippC/keepass2android/releases/tag/v1.09e-r3
