### ISSUE TITLE
Change keyboard behaviour for entries with multiple usernames/ Android autofill

### ISSUE THREAD

**Issue by Indubius** [PhilippC/keepass2android#2235]
Linked to many other issues claiming autofill isn't working properly on Android 13, I'd like to raise the idea to change the keyboard's behaviour. For comparing matters, I have installed keepassdx to find out whether this one does fill out better automatically and really experienced diffenerces. It does find more fields in apps. Not all and it's not a bursting difference, but there must be a way to tweak this.
The keyboard additionally offers descripted entries to choose from for entries with several usernames as an overlay pop-up. That's making it much more user-friendly than the actual keepass2android selection process. Perhaps worth a look, Phillip?

**Comment by PhilippC** [comment]
please see https://github.com/PhilippC/keepass2android/issues/2059#issuecomment-1455921233 and report any app which is not working as expected as described there.
