### ISSUE TITLE
Samsung Galaxy S23 / Adroid 13 - Can't Open Database File On Google Drive

### ISSUE THREAD

**Issue by hughwobrien** [PhilippC/keepass2android#2238]
I just got my new Samsung Galaxy S23 today.  I have run into an issue attempting to use keepass2android offline with google drive.   When I attempt to pick google drive as my file source, I get the following error message: "Can't load content at the moment".

Steps to reproduce:

1. Open the app
2. Choose "Open file..."
3. Choose "System file picker"
4. Use "Hamburger Menu" 
5. Choose my google account
6. Choose "My Drive"
7. Error Message: "Can't load content at the moment"

**Comment by casperklein** [comment]
I am having the same issue. However, I noticed this also with other apps using Google Drive.

**Comment by hughwobrien** [comment]
I followed your steps above and unfortunately, that didn't work for me.  I was never asked to access...I was only asked to allow notifications.  Also, after revoking the access, I tried uninstalling and reinstalling.  Same thing, I was asked to allow notifications but that is all I was asked and it still doesn't work.

**Comment by lisat-hub** [comment]
I have the same problem with KeepassDX. I do not have the access in the Google account settings, so I cannot remove it.
Any suggestion?

**Comment by S23user** [comment]
I'm having a similar issue except,  I am trying to open files directly thru GDrive app. It won't open my GDrive files (pdf). Forever loading with a fuzzy preview of what I need to sew. I got my s23 just a day ago and it's doing this.

**Comment by casperklein** [comment]
The issue is completely gone for me with the release of a new version of the google drive app.
