### ISSUE TITLE
Can't login because OTP property missing

### ISSUE THREAD

**Issue by santo998** [PhilippC/keepass2android#2246]
I only use KeePass 2.53.1 x64 in my desktop to generate TOTPs for my entries.
Then, I use KeePass2Android on my phone to copy TOTPs to login on websites that I access on my phone.
Problem is some TOTPs work, but others don't.

All my TOTPs were generated the same way, by KeePass 2.x TOTP generator menu.
All have the same named default property: "TimeOtp-Secret-Base32" and I didn't modify it.

Concrete examples:
Uber: TimeOtp-Secret-Base32 length = 32 characters, it **HAS** TOTP property defined
Dropbox: TimeOtp-Secret-Base32 length = 26 characters, it **HASN'T** TOTP property defined
Twitch: TimeOtp-Secret-Base32 length = 52 characters, it **HASN'T** TOTP property defined

I dont know if it's related to TOTP seed length, but only my Uber account has the TOTP property.
On the others entries if I enter to edit them, I don't see TOTP properties, but on my Uber entry I do.
Also when auto-type I see defined TOTP property to copy on my Uber entry, but on the others don't.

**Comment by santo998** [comment]
@zsigmi the work you have done is amazing!
Searching all your TOTP seeds as real world examples to confirm what is happening here.
You confirmed something is happening with 26 and 52 characters length TOTP seeds.
This is a pretty much important bug, because it makes TOTP 2FA unusable on some websites.

**Comment by santo998** [comment]
@PhilippC I think this issue is pretty important and needs to be fixed.
If not, then KeePass2Android won't support TOTP 2FA.
Also should be an easy fix

**Comment by inzaghi89** [comment]
Still catching the same issue. For keys with length <32 signs TOTP are showing correctly, but for longer keys it doesn't show TOTP value. Tried on Dropbox and epic account. On KeePass (windows) it's all ok, on keepassdx (Android too).

**Comment by santo998** [comment]
@inzaghi89 not only that. Try with 26 characters TOTP seed.
Just test with random characters...

**Comment by inzaghi89** [comment]
Interesting is that key from Google (32 chars) works without any problem. I'm really not sure why some keys isn't displayed correctly.

**Comment by PhilippC** [comment]
can somebody please provide a demo kdbx file (including master key) here for testing?

**Comment by PhilippC** [comment]
forget my previous comment. https://github.com/PhilippC/keepass2android/issues/2020 includes one.

**Comment by d0verenny** [comment]
The bug persists in the latest version as well ..
