### ISSUE TITLE
Ability to export a synchronized database

### ISSUE THREAD

**Issue by gameraccoon** [PhilippC/keepass2android#225]
I run into very disappointing scenario with a synchronized database.

I use Dropbox for synchronization my keepass database.

1. After one of my phone was lost, I disconnected all the devices from Dropbox.
1. My primary android device was disconnected too and I worked some time without synchronization.
1. After a while I decided to connect it again and synchronize keepass. But I didn't find a way to back up my local database before this synchronization, I could only open it but not save in phone memory or somewhere else.
1. I connected Dropbox and synchronized database. The app ask me what version I want to apply, and I'm sure I've chosen to not override my version from Dropbox, but my local database was overridden from Dropbox.
1. I saw my old database in the list of cached databases and could open it, but again, couldn't resave it
1. After app restart or some my actions this cached version disappeared from the list

I think the main problem here was **lack of ability to save database**. Because even now I can't imagine how in this scenario I could save my database at once, without writing down every single password.

P,S, If you know a way to restore that cached database from a device (android 7, not rooted) I would be very grateful. I have some passwords that I can't restore any other way.

**Comment by PhilippC** [comment]
Did you try settings -> database settings -> export database?

**Comment by gameraccoon** [comment]
No, I didn't find it when searched for an export option. Actually only found it now after you'd pointed it out.
Anyway, thanks for this. Will use this option the next time.

Also, big thanks for the work you did on this app. This is one of the best applications that making people's daily routines easier.
