### ISSUE TITLE
Database cache accessible without database's required keyfile

### ISSUE THREAD

**Issue by JLeemaster** [PhilippC/keepass2android#2256]
I have a database encrypted by a password and key file combination. After deleting/removing the key file, I was still able to open my password database which should not have been possible. 

The message from the app indicates it is using a local backup cache instead of the main file and will synchronize them later when the key file is accessible again.

The cache should have been encrypted with both the password *and* key file, not just the  password.

Removing my key file should have left my database, *and* any internal caches and or backups, inaccessible. By not requiring the key file, those internal backups and caches are not as well protected as the main database.

**Comment by PhilippC** [comment]
Caching is used to allow access to your data even when you're offline. If you don't want this, disable file caching in the app settings.
