### ISSUE TITLE
Almost never works with filling in on sites!?

### ISSUE THREAD

**Issue by vampyren** [PhilippC/keepass2android#2258]
Hi, 
As the titles says, the fill in does not work most of the time....and sometimes it only fills in the email (username) and not the password.
And when i go to the password then it wont even show the keepass2android so i have to keep switching from browser to keepass2android and copy the password and go back to browser! 
Its really a hassle. Why does it work so poorly on Android phone? maybe the blame is the keyboard or even something else but i ask it here since i'm using keepass2android for my main password manager and i really like it beside this.

I am using a S23 Ultra with Samsung original keyboard and their own browser (Internet) but i also have/use Brave. Same thing there.

**Comment by PhilippC** [comment]
please get 1.09e-r3 from

https://play.google.com/apps/testing/keepass2android.keepass2android
https://github.com/PhilippC/keepass2android/releases/tag/v1.09e-r3

and see https://github.com/PhilippC/keepass2android/issues/2059#issuecomment-1455921233
