### ISSUE TITLE
v1.09e-r4 still crashes at saving creds

### ISSUE THREAD

**Issue by Siarhei-Yarkavy** [PhilippC/keepass2android#2269]
zenfone 8, android 13

![__bug1](https://user-images.githubusercontent.com/1478327/224314813-0188bae4-540d-4311-ae9a-e46aa39be200.jpg)
![__bug2](https://user-images.githubusercontent.com/1478327/224314828-ffdf6a81-5040-40fc-9109-7457d4973f4e.jpg)

**Comment by PhilippC** [comment]
can you provide a logcat please?

**Comment by PhilippC** [comment]
ah, sorry, I misinterpreted at first. I will try to reproduce.

**Comment by tome9111991** [comment]
same issue
![Screenshot_20230312-070814_Vivaldi_Browser](https://user-images.githubusercontent.com/57866234/224527593-ee471f35-68e6-4abb-ad6a-694016eb952e.png)

Almost with the numbers only keyboard.
