### ISSUE TITLE
[Feature Request] Multiple URLs via custom attributes

### ISSUE THREAD

**Issue by ckotte** [PhilippC/keepass2android#227]
I have some entries that require multiple URLs. For example, same (Active Directory) user account for multiple web sites. 

The only way to use multiple URLs for one entry is to clone the entry and use references for username and password. There is no common standard to implement multiple URLs via custom attributes with KeePassXC and all those browser add-ons. 

Would it be possible to add multiple URLs via custom attributes like URL1, URL2, etc. and search all entries for matching URLs in those fields?

**Comment by PhilippC** [comment]
I don't see any required action for this. Keepass2Android first searches entries with matching URL field. If it does not find any, it searches other fields as well. It also suggest to create a new field with the URL so the search is successful next time. These fields are called "KP2A_URL" or "KP2A_URL_[counter]" if "KP2A_URL" exists.

**Comment by bengalih** [comment]
> I don't see any required action for this. Keepass2Android first searches entries with matching URL field. If it does not find any, it searches other fields as well. It also suggest to create a new field with the URL so the search is successful next time. These fields are called "KP2A_URL" or "KP2A_URL_[counter]" if "KP2A_URL" exists.

This works for me so that I can use my entries by placing the appropriate androidapp name in these fields.  I actually called mine "KP2A_URL_ANDROID" and "KP2A_URL_ANDROID_2", etc. and it seems to work fine.

I can't find any other reference anywhere to "KP2A_URL" being an actual field, it appears you just made up a random name for a field to store this in?  Do you have any more data on this setting?

**Comment by PhilippC** [comment]
If Keepass2Android doesn't find a matching entry in the URL field, it will search all entries for ANY field that matches the URL. So the name is not important.
If you select an entry manually after search did not find a match, you should be prompted if this should be remembered. If you click yes, an entry like KP2A_URL_[1,2,3] will be created.
