### ISSUE TITLE
Unlock database takes me to Microsoft Sign in

### ISSUE THREAD

**Issue by FranziPoldy** [PhilippC/keepass2android#2272]
I use K2A (1.09e-r4) on my mobile (Pixel 5a 5G; Android 13) and tablet (Galaxy Tab S3 SM-T820; Android 9).  Mobile works fine.  Tablet worked until recently but now, when I enter master password and click UNLOCK, it takes me to a Microsoft Sign in page.  See screenshot.

![Screenshot_20230311-185213_Chrome](https://user-images.githubusercontent.com/39401988/224474790-bfb9e009-7742-4311-a4db-8a88ee72dbf7.jpg)

**Comment by PhilippC** [comment]
are you storing your database (or any child database with AutoOpen) on OneDrive?

**Comment by FranziPoldy** [comment]
Yes, my database is on OneDrive. This works OK on my mobile (Pixel 5a 5g)
but not on my tablet (Galaxy S3). I don't know what AutoOpen is.

**Comment by PhilippC** [comment]
so if you click the account below ("we found an account you can use to log in") everything works?

**Comment by FranziPoldy** [comment]
Yes, it works now, but I don’t understand what is going on.

 

I clicked the account ("we found an account you can use to log in") and there were a couple of iterations of signing in and out of OneDrive and being presented with the Keepass2Android unlock screen.  

 

I am now signed out of OneDrive on my tablet (according to the OneDrive app), but K2A is working.  It says it is using ***@***.***/me/Keepass2Android/franzipasswords.kdbx) which I suppose is local on my tablet, but I can’t find any sign of it when I search (/storage/emulated/0) with Total Commander.

 

And, even though I am signed out of OneDrive on my tablet, if I make a change to the database, it (the change) appears on Keepass on my PC (which syncs with OneDrive).  So, obviously I’m not signed out.  Does K2A have separate access to my OneDrive?

 

Does this make sense to you?

**Comment by PhilippC** [comment]
you have different options to access OneDrive files - I suggest to use the built-in OneDrive access, for which you need to sign in (as you did in our discussion above). After doing so, KP2A has its own access token to OneDrive, this does not depend on third party apps. If you access the file through the OneDrive app, this has its own access token and mechanisms to log in/out. 

I don't think that TotalCommand can access files in app local storage.

I'm closing this as it seems to behave as expected.
