### ISSUE TITLE
Google Drive reverting to internal cache

### ISSUE THREAD

**Issue by robpaolella** [PhilippC/keepass2android#2276]
After a day or two of using the Google Drive integration to access my database, I will get a notice when accessing it that the source file couldn't sync or couldn't be found and it's now working off of internal cache. Thus no changes that I make to my database on other devices are synced with my phone unless I go and re-add the database, which only holds for a day or two at most.

**Comment by robpaolella** [comment]
> I am facing the same issue. Once KeePass clients update the actual DB the actual .kdbx file is deleted and .kdbx. shows up and after that, a new .kdbx is added. Since keepass2android put the DB in the cache locally that would resolve into an outlier of versions on different devices.

I can confirm now that this issue starts after accessing the database from Mac OS X using KeePassXC. I look at the log in the Google Drive desktop client and it is deleting the existing database and replacing it with a new one of the same name. I also use KeePassXC on my Windows 10 desktop machine, but any modifications to the database from Windows don't cause this issue.

**Comment by PhilippC** [comment]
I am pretty sure this is related to https://github.com/PhilippC/keepass2android/issues/882 and I consider this an issue with how KeePassXC is modifying the file (in Google Drive, a file has an idea and cannot be identified by name - multiple files with the same name can exist at the same time).

**Comment by robpaolella** [comment]
For anyone who has this issue in the future, I fixed it by changing my Google Drive desktop client from 'Stream files' to 'Mirror files' on my Mac. Now any changes I make to the database don't delete and recreate it. It simply updates it. Strangely, this isn't an issue on Windows 10, only on Mac.
