### ISSUE TITLE
Enhancement: Add actions for click&hold on entry

### ISSUE THREAD

**Issue by zavjah** [PhilippC/keepass2android#2282]
Hi, I was using password safe for a long time before I switched to keepas2android and in pwsafe one could click&hold on an entry and actions menu for copying name or password would appear. Maybe you could integrate this feature into you app. That'll be awesome.

Thx,
Zavjah

**Comment by Spiralpine** [comment]
+1

**Comment by mywalkb** [comment]
I'm evaluating to develope this feature request, because I have the same issue. 
On password safe was more eaasy copy username and password.

**Comment by PhilippC** [comment]
please note that the clipboard is unsafe on Android. The recommended way to transfer sensitive information into other apps is Autofill (or the built-in keyboard for cases where autofill does not work). This is why I am not going to support clipboard further.
