### ISSUE TITLE
Crash using fingerprint

### ISSUE THREAD

**Issue by sercasbh** [PhilippC/keepass2android#2293]
When I want set unlock with fingerprint, I receive this error.
Lineageos 19.1 - Android 12
Xiaomi Mi A1
![Screenshot_20230328-143613_Trebuchet](https://user-images.githubusercontent.com/33605132/228239434-c8b9d8dd-e734-4668-b081-957956cb22da.png)
Thanks for your great work

**Comment by Spiralpine** [comment]
Is your fingerprint registered on your device?

**Comment by sercasbh** [comment]
Yes
It is working with all other apps

Il 5 aprile 2023 17:16:57 CEST, Spiralpine ***@***.***> ha scritto:

**Comment by Spiralpine** [comment]
> Yes It is working with all other apps Il 5 aprile 2023 17:16:57 CEST, Spiralpine ***@***.***> ha scritto:
> […](#)
> Is your fingerprint registered on your device? -- Reply to this email directly or view it on GitHub: [#2293 (comment)](https://github.com/PhilippC/keepass2android/issues/2293#issuecomment-1497665892) You are receiving this because you authored the thread. Message ID: ***@***.***>

Have you considered clearing the app cache and storage fully and then uninstall/reinstall the app?

**Comment by sercasbh** [comment]
Clear the storage solve the issue.
Thank you

**Comment by sercasbh** [comment]
The issue solved clearing the storage and cache
