### ISSUE TITLE
Generate TimeOtp fields when configuring TOTP

### ISSUE THREAD

**Issue by BobVul** [PhilippC/keepass2android#2295]
It would be nice if Keepass2Android could generate the various [`TimeOtp` fields](https://keepass.info/help/base/placeholders.html#otp) as standardised by Keepass 2.47 / 2.53 when configuring TOTP, e.g. by QR code. Currently only an `otp` field is generated, which does nothing when the database is later used on the desktop application.

**Comment by PhilippC** [comment]
KP2A is read-compatible with KeePass2 style (https://github.com/PhilippC/keepass2android/blob/1248--totp-docs/docs/Generating-TOTPs.md), but only writes Key Uri Format which is supported by many other tools as well (KeePassXC, KeeWeb, Google Authenticator etc.). Please open tickets for any app/plugin which cannot read this.
