### ISSUE TITLE
How to get app updates

### ISSUE THREAD

**Issue by stbxxl** [PhilippC/keepass2android#2296]
What is the recommended way of getting the latest app version? 

I usually install apps through the Google Play Store. However, for Keepass2Android the version in the Play Store is several revisions behind: 1.09c-r0 in the Play Store vs. 1.09e-r5 on Github.

**Comment by PhilippC** [comment]
Google Play (production channel) is considered the current stable release. If you want to use the latest version, please install from Github or switch to https://play.google.com/apps/testing/keepass2android.keepass2android.
