### ISSUE TITLE
Can the app extract text attachments to memory instead of temp storage?

### ISSUE THREAD

**Issue by haititu** [PhilippC/keepass2android#2304]
Can the app extract text attachments to memory instead of temp storage?

For the desktop version of keepass2, **text attachments** are opened using an internal editor which opens the attachment in **RAM**, but I have found that keepass2android does not.  It opens to a temp text file in storage, which to me is a security risk because I store my secrets in attached files and temp files (in storage) containing secrets  can be retrieved in plain text.

Or did I miss something?
If not, can this be a feature request?

(Trivia: On the desktop version, for non-text files, keepass2 opens the files in temp encrypted EFS files, which is "correct")

In case someone thinks I may be using keepass2 "wrongly" this way by attaching text files instead of entering the secrets directly into the app, I use attachments because I have a very long list of secrets (which I had in a text file in an encrypted zip before I discovered keepass2) and would be tedious to retype all of them into keepass, so I just attach the text file. :)

Thanks.

**Comment by PhilippC** [comment]
Text should be stored in the "Notes" field (or probably better in custom fields). using temporary files is a way of making the data available to other apps (which of course should only be done if you trust those) and to access the data if it is proprietary formats or the like. I can't encrypt it for that purpose.
