### ISSUE TITLE
(Feature Request) Add countdown to TOTP Token

### ISSUE THREAD

**Issue by hansgeorgfranke** [PhilippC/keepass2android#2315]
Please add a validity indicator (some sort of a countdown) to the TOTP-field like it is for example in "Google Authenticator" app.

This feature will be very usefull if you have to enter the TOTP Token into an application running on a different device.

**Comment by WebworkrNet** [comment]
I had the same idea a few days ago. Thanks for posting.

**Comment by WebworkrNet** [comment]
This would even be helpful in certain cases on the same device. Not every web form is optimally designed, so that the transmission of the TOTP cannot be conveniently inserted via the KP2A keyboard, but each character must be entered by hand.

**Comment by stefan-muc** [comment]
I like it how it is realized in KeePassOTP plugin for KeePass: The code is displayed as usual. In the five seconds before expiration, the code is displayed as `code (5)`, `code (4)`, ...
That would be enough and doesn't need a separate GUI element/line.
