### ISSUE TITLE
[FEAT]  Make KP2A Online Version Chromebook Compatible 

### ISSUE THREAD

**Issue by Spiralpine** [PhilippC/keepass2android#2316]
Google has removed the Keepass2Android Online version from the Chromebooks Play Store ( see #2314 ) as it is currently incompatible to run in the ARCVM as an Android app.

There is a noticeable community of users who would benefit from this compatibility. 

Thanks.

**Comment by ippocratis** [comment]
Have you tried to install the apk from github releases?

https://github.com/PhilippC/keepass2android/releases/

**Comment by Spiralpine** [comment]
Yes, but that is not a viable option as my Chromebook is not a test machine typically used by app developers. 

In order to sideload an apk on a Chromebook you need to turn on the “Developer Mode” on your Chromebook. Switching to “Developer Mode” will erase my Chromebook and any information stored on it, so I can not afford utilizing this mode in my work/production computer.

**Comment by ippocratis** [comment]
True what you said
There is a workaround I think to Enable Linux Subsystem and then adb so that you can adb  connect and adb sideload the apk
This way you don't compromise any security nor wipe any storage

**Comment by Spiralpine** [comment]
> True what you said There is a workaround I think to Enable Linux Subsystem and then adb so that you can adb connect and adb sideload the apk This way you don't compromise any security nor wipe any storage

I'm aware of that workaround, but as I mentioned above once you enable ADB you would end up to powerwash your chromebook. That method is for app testing and not suitable for a production environment.

https://support.google.com/chromebook/answer/9770692?hl=en

Additionally, the KP2A Online version was available for years on Chromebook Play Store and I was using it even though it had some weirdness. It's been removed recently and only the offline version remains available.

@PhilippC  needs to look into it to see why the app has disappeared from the Chromebook Play Store and I would like the KP2A to once again be officially back as a supported Android app on Chromebooks and downloadable from Chromebook Play Store as it was previously.

**Comment by PhilippC** [comment]
does anybody know where to find information about such requirements?

**Comment by PhilippC** [comment]
I guess I found the reason. Does your Chromebook have a camera? If not, that's causing the trouble probably.

**Comment by Spiralpine** [comment]
> I guess I found the reason. Does your Chromebook have a camera? If not, that's causing the trouble probably.

@PhilippC  - All Chromebooks have cameras, like typical laptops. Lots of Chromebooks also come in 2-in-1 design. They incorporate a 360-degree hinge or detachable keyboard that allows you to use the Chromebook either like a laptop or a touch screen tablet. You can run the supported Android apps and choose the app window either in “Phone” mode, “Tablet” mode, or custom resizable mode. 

Please note that there is a very long list of password manager apps available to install on Chromebook Play Store, including the Keepass3Android Offline. But strangely the KP2A Online version, which seems to be the only app with Google Drive support and that many have been using for years, has been removed. 

Curious question: Does this removal have anything to do with the Google Drive API? Specifically, with the 1.09.e version and the support of Google Drive restricted  scope verification process? The reason I’m asking is the  timing of public release of 1.09e and the KP2A Online version removal from the Chromebook Play Store seem to be overlapping.

**Comment by Spiralpine** [comment]
> does anybody know where to find information about such requirements?

I'm not a developer, but may be this:

https://developer.android.com/topic/arc/manifest

And a Chromebook with i5 or higher, 8GB of RAM or higher, 128GB of storage or higher to be capable of running the native Linux VM.

**Comment by Spiralpine** [comment]
@PhilippC - As the developer of KP2A, are you able to find out why the online version was pulled from the Chromebook Play Store? 

If you can get it back on, we can live with any regular glitches we have seen with the app as we have workarounds for it to use as is. 

Thanks.

**Comment by PhilippC** [comment]
@Spiralpine not all Chromebooks are supporting the `android.hardware.camera` feature. Some only support `android.hardware.camera.front` but not `android.hardware.camera`. Thus, removing this as a required feature will fix this.

**Comment by Spiralpine** [comment]
@PhilippC -  Chromebooks only have the front camera (user-facing camera used for selfies, video calls, etc.). When should we expect your fix to show up on Google Play Store?

Thanks.

**Comment by Spiralpine** [comment]
Ping @PhilippC  again. Any idea when this issue is going to be fixed?

**Comment by Spiralpine** [comment]
> @Spiralpine not all Chromebooks are supporting the `android.hardware.camera` feature. Some only support `android.hardware.camera.front` but not `android.hardware.camera`. Thus, removing this as a required feature will fix this.

When will this removal be implemented?

**Comment by AlexCherrypi** [comment]
> > @Spiralpine not all Chromebooks are supporting the `android.hardware.camera` feature. Some only support `android.hardware.camera.front` but not `android.hardware.camera`. Thus, removing this as a required feature will fix this.
> 
> When will this removal be implemented?

With the next release, I assume.

**Comment by Spiralpine** [comment]
I only hope. It would be just nice if @PhilippC comments  with few words 😉

**Comment by gwillen** [comment]
For what it's worth: I just tested the fix and it seems to work.

I tried sideloading nonet_1.09e-r4 on my Chromebook (with no rear camera), and it installed but crashed on startup (right after clicking through the changelog, as I recall.) I assume sideloading ignores the manifest or something, but then dies trying to actually open the camera.

Then I sideloaded nonet_1.09-r7 and it seems to be working. If I try to scan a TOTP QR code, it successfully previews using the front-facing camera. (The aspect ratio is weird, it squishes the camera image to the shape of the app, but I suspect that's a Chromebook problem with resizeable activities, unrelated to the camera issue, and purely cosmetic.

Thanks very much for fixing this!

**Comment by Spiralpine** [comment]
Thanks @gwillen for testing the unreleased version.  I hope the new release with the fix will again show up on Chromebooks Play Store soon.

**Comment by gpgp00** [comment]
@PhilippC Looking forward to this being in the ChromeOS Play Store again so that we can use it again on a new Chromebook. Thanks much for a great tool!

**Comment by pmarks-net** [comment]
A family member recently replaced his Chromebook, and it seems that the **Offline** version is also unavailable now.  I linked directly to https://play.google.com/store/apps/details?id=keepass2android.keepass2android_nonet and he claims there was no install button.

**Comment by MrSellerie** [comment]
@pmarks-net 
comment from @Spiralpine on april, 24 2023: The Keepass2Android Offline version has also been removed from the Chromebook Play Store.

**Comment by MrSellerie** [comment]
Since a few days is version 1.10-PRE listed in the ChromeOS-Playstore.

**Comment by Spiralpine** [comment]
Correct. And it works fine for me.

**Comment by MrSellerie** [comment]
New problem on Google_Vilboz.13434.576.0 Zork and Android 13 in Chomebook-Playstore. App starts, seems to be running for a few seconds and the app ends without an error message. After deleting cache and/or data you can attach to google drive, but after a few seconds ends the app also without a message.

**Comment by Spiralpine** [comment]
@MrSellerie  - It is recommended to create a new issue for your problem since this one has been closed and was related to the unavailability of KP2A on the Chromebooks Play Store. Include the template to describe your problem and provide debugging logs for the developer's examination. Adding more information about your Chromebook and its OS details such as "About ChromeOS, Additional details, Build details, copy/paste" would also be beneficial.

The online version 1.10-pre of KP2A, which is currently accessible on the Chromebooks Play Store, functions fine on my Chromebook, as stated earlier. Here is my build detail:

Google Chrome: Version 120.0.6099.235 (Official Build)  (64-bit)
Platform: 15662.76.0 (Official Build) stable-channel eve
Channel: stable-channel
Firmware Version: Google_Eve.9584.230.0
ARC Enabled: true
ARC: 11277394
Enterprise Enrolled: false
Developer Mode: false

**Comment by MrSellerie** [comment]
You are right, but the issue #2316 was closed october, 31 2023. All new opened issues with ChromeOS in context were closed by @PhilippC

**Comment by Coasie** [comment]
I have 2 new late 2023 chromebooks one is an Acer Spin 714 with an Intel I5, and sideloaded K2A 1.10-pre works just fine.
The other is an Asus 14' with an AMD Ryzen 3 7320c  and  sideloaded K2A 1.10-pre crashes when opening.

Both run the latest ChroemOS 120, and I have also tried with 118 and 119 when they were the latest version. The Asus/AMD model, K2A always crashes when loading.
