### ISSUE TITLE
[BUG] internal SFTP client / Algorithm negotiation fail

### ISSUE THREAD

**Issue by spel-ux** [PhilippC/keepass2android#2317]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

sftp connection Error:

Kann nicht zum Datei-Dienst 
verbinden. Algorithm negotiation fail:
algorithmName="cipher.c2s" jschProposal
="aes128-ctr,aes192-ctr,aes256-ctr
,aes128-gcm@openssh.com,aes256
-gcm@openssh.com" serverProposal="aes
128-cbc,3des-cbc,aes192-cbc,aes256-cbc"

### Describe what you expected to happen:

Failed to connect via Android via internal SFTP on Synology NAS DS213j (DSM 6.2.3-25426 Update 2).
Match SFTP credential and connection works via PC/Android (Total Commander sftp plugin).

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

11

**Comment by PhilippC** [comment]
can you make config changes to your server? https://stackoverflow.com/questions/6263630/jschexception-algorithm-negotiation-fail
KP2A is using the latest JSCH version.

**Comment by matthias-bindernagel** [comment]
I'm on KP2A 1.09e-r7 and syncing via SFTP with a Synology DS414j with DSM 6.2.4-25556 update 6.

I was suffering from the same problem. As @PhilippC suggested in https://github.com/PhilippC/keepass2android/issues/2317#issuecomment-1517159174, I could on the Synology DS go to *Control panel* / *Terminal & SNMP* / *Terminal* / *Advanced Settings* and there select the ciphers supported by *jsch*.

Works for me now.

**Comment by PhilippC** [comment]
glad this helped for @matthias-bindernagel.
I am now considering this not as a bug. Please re-open if you disagree.
