### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by eilmi** [PhilippC/keepass2android#2318]
I recently upgraded to Keepass2Android 1.09e-r7, which apparently includes a new SFTP implementation.

Unfortunately, I can't find any documentation on how to use it :(

When I try to connect to an SFTP server and switch to public key authentication, I still get the old (and considered insecure) RSA public key.

Please can someone tell me how to use my own key pair

Thank you!

**Comment by PhilippC** [comment]
for using your own key, please wait for https://github.com/PhilippC/keepass2android/pull/2247 to be integrated (in the next release)
