### ISSUE TITLE
[FEAT] Ability to arrange additional strings

### ISSUE THREAD

**Issue by shundred** [PhilippC/keepass2android#2322]
The additional strings shown on kp2a appears to be shown in order it was added.
It will be useful if one can re-arrange these fields.

An excellent option will be like this:
User should be able to rearrange fields.
Then user will decide which fields will appear on kp2a keyboard and which fields will appear in popup view of password entry.

This will also solve one of the significant problems, in which user is given 'otp' option on kp2a keyboard which is never required as only derived TOTP is asked every time and never the otp.

**Comment by PhilippC** [comment]
I have implemented several improvements regarding TOTP handling. A generic rearrangement is not planned but should no longer be required with https://github.com/PhilippC/keepass2android/pull/2502
