### ISSUE TITLE
Keepass2Andoid on Android 13: opening database file failed with access denied

### ISSUE THREAD

**Issue by LittleAlf** [PhilippC/keepass2android#2329]
### Describe the bug you encountered:

After the latest update of K2A to version 1.09e-r7 K2A fails to open my database file, which is in folder `/storage/emulated/0/Documents/Keepass`. Error:  "Access to the path '/storage/emulated/ ... ' denied."

Using "Change database" does not work either: the only choice for selecting a file stored locally on the phone is the Android file browser. This browser does not give access to above folder! And my special file manager is NOT listed!

Automated update via Google Play happened just now. Before it was working fine.

Now I have no way of opening my database file anymore.

Phone: Pixel 6a

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

Android 13

**Comment by iqapps** [comment]
Fixed this by allowing app to access Images, Videos, Music, Sound

**Comment by LittleAlf** [comment]
> Fixed this by allowing app to access Images, Videos, Music, Sound

If I am not mistaken, this means I need to move the database file out of the `/storage/emulated/0/Documents/Keepass` directory?

I am using Syncthing to synchronize my database file between my PC and my mobile. I hope, that this will work with the new directory as well.

**Comment by LittleAlf** [comment]
**I was able to resolve the issue!**

It seems like that Android 13 removed my permissions to access this directory. I tried to regain it by copying the full path as mentioned in my previous post into the file browser: to no avail! I had to manually drill down the correct directory to regain access.

Nevertheless, it works now. So, issue closed.

**Comment by ZelphirKaltstahl** [comment]
To clarify what LittleAlf wrote:

It seems like the app does not ever ask for any permission. This can be seen by looking at app permissions in general and checking which permissions are granted to the app. There it will mention, that no permissions have been asked for by the app. The app simply fails, when it cannot access the database file. This is circumvented by using a file browser to select the file and then "open with" the keepass app.
