### ISSUE TITLE
[FEAT] Synology Drive storage

### ISSUE THREAD

**Issue by ea4k** [PhilippC/keepass2android#2347]
Synology has a software called Synology Drive.

From the user perspective is like Dropbox but files are stored locally, in your Synology NAS.
It allows to sync folders between smartphones (Android, ios) and computers (windows, macOS ...) so it is very convenient. 

When opening a file from the Synology Drive folder in Android, it is not possible to write back to the file system in Android so it is not possible to use keepass2android fully as the user can't add/modify registers.

It would be nice to add a trusted way to open KeePass files with your great software. 

Thank you.

**Comment by PhilippC** [comment]
synology supports WebDav and SFTP. This is the "trusted way" to use!

**Comment by ea4k** [comment]
Using webdav or SFTP does not allows to sync automatically and forces the user to download each time he/she wants to work with the updated version of the file.
It requires also to upload the file if it is modified in the the phone and download again from the computer or other phones using the same file.

The synology drive app, as Dropbox, sync automatically in both ways in a transparent way for the user.
