### ISSUE TITLE
[BUG] v1.09e-r7 - SFTP fails to connect to IPv6 address

### ISSUE THREAD

**Issue by odkr** [PhilippC/keepass2android#2350]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I am using Keepass2Android v1.09e-r7 on an unofficial build of LineageOS v19 (Android v12) for the Fairphone 4. When I try to connect via SFTP to my NAS using its IPv6 address, Keepass2Android responds with the error message 'Cannot connect to file provider service For input string: "[last 7 quartets of the IPv6 address]"'.

I noticed that the first quartet of the IPv6 address is missing, so I conjectured that everything up to the first colon is interpreted as a protocol and prefixed the address with "sftp:". However, this triggers the same error, save for that the IPv6 address is reported in full.

I also tried enterting the IPv6 address in square brackets, but this, too, triggers the same error.

I searched the FAQ, the docs sub-directory, googled "Keepass2Android IPv6", and checked open issues containing "IPv6" or "SFTP", but didn't find any information on how to enter an IPv6 address.

### Describe what you expected to happen:

I expected Keepass2Android to open the password database on my NAS.

### What version of Keepass2Android are you using?

v1.09e-r7

### Which version of Android are you on?

12 (Android) / 19-20220611-UNOFFICIAL-FP4 (LineageOS)

**Comment by odkr** [comment]
I updated to the official LineageOS v20. The bug persists.

**Comment by PhilippC** [comment]
resolved in https://github.com/PhilippC/keepass2android/releases/tag/v1.10-pre

**Comment by odkr** [comment]
Thank you!
