### ISSUE TITLE
Connection to Yandex.Disk via WebDAV: error

### ISSUE THREAD

**Issue by LevYas** [PhilippC/keepass2android#236]
Hi!
I have the last version of keepass2android and the same problem on 2 devices (Android 7 and 8).
I pick "open existing" (or something like this), then "HTTPS WebDAV".
On next window Link "https://webdav.yandex.ru/my.kdbx", also my valid login and pass.
On next step I enter my valid database password, but all what I see is "An error occured:". No more, only these 3 words.
It's not the problem of Yandex.Disk. On WindowsPhone app WinPass works normally with this database.
Downloaded database opened without any problems.

**Comment by PhilippC** [comment]
@LevYas Please try to enter https://webdav.yandex.com/ (including the slash at the end) as server address (maybe also try .ru, but .com worked for me). Then you should see the browsing window on the next side.
@frdmrckr what do you mean with "similar". Can you also try with entering the root folder?

**Comment by LevYas** [comment]
@PhilippC thank you very much for your help! It works. First times I tried entering only server address, but without trailing slash. I see you opened issue "Fix detection of file or folder for WebDav and possibly others #276", so I close this one.

**Comment by AnalitikSamara** [comment]
Greetings to all, Philip low bow! Slash at the end of the server address solved the problem over which I fought for a week (https://sourceforge.net/p/keepass/discussion/329220/thread/ac8fc21d/).

**Comment by J0n1k4** [comment]
Hi PhilippC,
I had the same issue today, and here I found the solution.
Thank you for your work, I just installed the app, trying to migrate from NSWallet.
It looks promissing.
Cheers

**Comment by kLF-OMLx** [comment]
All these years later I still have to spend hours playing a guessing game when attempting to use the WebDAV https picker for a Koofr webdav. 

I have to include the folder name **AND FILENAME** of the .kdbx file in the url otherwise I kept getting a totally unhelpful generic error.
