### ISSUE TITLE
Error cloning netftpandroid submodule

### ISSUE THREAD

**Issue by mydexterid** [PhilippC/keepass2android#237]
Wanted to build this app myself to fix #221 but run into this error:

`Cloning into 'src/netftpandroid'...
fatal: https://git01.codeplex.com/forks/philippc/netftpandroid/info/refs not valid: is this a git repository?
fatal: clone of 'https://git01.codeplex.com/forks/philippc/netftpandroid' into submodule path 'src/netftpandroid' failed`

it seems codeplex just shut down a couple of days ago? Anyways.. can you please just commit it to this repo?

Thanks.

**Comment by PhilippC** [comment]
moved subrepo to github
