### ISSUE TITLE
[BUG] Cannot connect via SFTP

### ISSUE THREAD

**Issue by FEER0** [PhilippC/keepass2android#2374]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I'm sorry if this is due to an error on my part, however I've checked everything and still cant get it to work.
I am using a Synology Disk Station over DDNS with private key authentication.
When I:
`Open file -> SFTP (SSH File Transfer)`
and input the correct credentials then I get the error:
`Cannot connect to file provider service java.net.NoRouteToHostException: Host unreachable`
I can't explain this behavior because the SSH connection over the DDNS works properly on all other Linux and iOS devices.
Does the Android device have to be rooted?

### Describe what you expected to happen:

I expected an connection to the SSH server to occur and the file manager to allow me to chose a file.

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

12

**Comment by hyproman** [comment]
This would seem to be a DNS resolution issue.

A few things to look into:

1. When you try to connect, are you using mobile data or on WiFi? If the latter, is it the same network as the one the server is on? How about the for the devices that can successfully connect? In my experience, the DDNS host name is not usually resolvable from the internal network.
2. If you connect the phone to the same network as the server, and use the IP address of the server, will KP2A connect?
3. Is there any way you can try connecting via an SSH/SFTP client from the phone that's having issues? Termius, JuiceSSH, AndFTP, or similar?

For what it's worth, I'm also using v1.09e-r7, Android 12, and SFTP integration successfully. My phone is rooted, but I don't see how rooting (or not) would be an issue here.

**Comment by FEER0** [comment]
Thank you for your help @hyproman.
The issue was indeed caused by being on the same network as the Server.
This comes as a bit of a surprise to me, because my Linux PC resolves the host name without issue while being connected to the same network.
