### ISSUE TITLE
[FEAT] Keyboard TOTP typing speed

### ISSUE THREAD

**Issue by pmodin** [PhilippC/keepass2android#2380]
While I've seen many feature requests to make the app faster, I'd like to slow things down 😀 

Sometimes websites are creative with TOTP. Here, the cursor jumps to the next input field after every number. Unfortunately the input is too fast so it's not filled correctly.

When it's filled too fast, not all numbers are entered. I think if there was an option to add a delay after each key press (best would be just for the TOTP), it would work fine.

![Screenshot_20230713-103056.png](https://github.com/PhilippC/keepass2android/assets/1815201/d2da47da-b243-444e-a785-0b572d4ed486)

https://github.com/PhilippC/keepass2android/assets/1815201/74c142af-e2e1-4886-a073-ca498b56ff04

**Comment by PhilippC** [comment]
I think this should be considered a bug in the target app, not in KP2A. They should have one semantic field for input of the TOTP. If they misuse several fields for this, it won't work in some cases.
