### ISSUE TITLE
[FEAT] keyboard: only show TOTP button, hide OTP button

### ISSUE THREAD

**Issue by pokanoka** [PhilippC/keepass2android#2394]
When OTP is configured for the entry, keepass Android keyboard shows both OTP and TOTP buttons. It's confusing. Moreover, pressing the OTP  would "disclose" secret which user would not normally want to change or output anywhere.

My proposition is to hide the "OTP" button. The "TOTP" is the one user wants in about 100% cases.

**Comment by PhilippC** [comment]
duplicate of #2033
