### ISSUE TITLE
In-Entry Group Move

### ISSUE THREAD

**Issue by erichiller** [PhilippC/keepass2android#24]
Ability to move entries from one group/category to another from within the entry's dialog (not just the listing of entries).
Ideally in the same Top-Left menu where 'Donate a Beer' is currently located.

**Comment by thetrad9** [comment]
I second that!

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
would easy organisation

**Comment by thomabrown** [comment]
I need this feature! My database has been migrated from other PC-based software and many entries are in undesirable locations. I would rather not have to re-enter all of them into the right place and run the risk of typos on my Android device!

**Comment by stevie86** [comment]
May I suggest the position of the option to be in the top right three dot menu as well?
