### ISSUE TITLE
[QUESTION] Does the "Nonet" version connect to the internet? Virustotal shows 3 HTTP, 11 DNS, 29 IP connections!

### ISSUE THREAD

**Issue by ai2p** [PhilippC/keepass2android#2400]
Why virustotal says that "nonet" version connects to the internet? I checked 
[keepass2android.keepass2android_nonet-1.09e-r7.apk](https://github.com/PhilippC/keepass2android/releases/download/v1.09e-r7/keepass2android.keepass2android_nonet-1.09e-r7.apk), downloaded from github releases.  
Look at [virustotal check](https://www.virustotal.com/gui/file/1eb8dfb161334bc2426632b11c8fb8796c360acd2fd1d75396a7d78786e19f4c/behavior) of that file.

On "**BEHAVIOR**" tab we can see these **Network comms: 3 HTTP 11 DNS 29 IP**. Further is gives more details:
**Network Communication**
**HTTP requests**
```
http://connectivitycheck.gstatic.com/generate_204
http://play.googleapis.com/generate_204
http://www.google.com/gen_204
```

**DNS Resolutions**
```
android.googleapis.com
clientservices.googleapis.com
connectivitycheck.gstatic.com
firebaseinstallations.googleapis.com
gmscompliance-pa.googleapis.com
```

Then goes a long list of **IP Traffic**.

I understand, that all those connections are google standard analytics, telemetry "spying", etc. 

**But why "nonet" version from github makes all that connections at all? Is it safe behaviour for "nonet" app?** Or, maybe, it's a glitch of virustotal, and that app doesn't connect to the internet?

**Comment by FabianMNoss** [comment]
I use https://trackercontrol.org/ on my smartphone (the F-Droid Version) to limit access to the internet of all installed applications.
Keepass2android does not even request internet access at all on my side - I'm using it since years.

**Comment by VA1DER** [comment]
Has nonet been discontinued?

**Comment by PhilippC** [comment]
the nonet version is a variant of the regular build and thus might include some libraries which could potentially access the internet. However, the apk does not have INTERNET permission so AFAIK Android will prevent any such library from making web requests. 

Nonet is not discontinued but is usually released after the regular version.
