### ISSUE TITLE
[BUG] Android 13 biometrics don't work with Fairphone 3

### ISSUE THREAD

**Issue by R-cohn** [PhilippC/keepass2android#2403]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

After I install the Android Version 13 on my Fairphone 3
With this current KeePass App(1.09e-r7) for me it’s not possible to activate the biometric authentication. 
I was happy to use this feature & it was working before the Android Update to 13.
All the other Apps that uses Fingerprint to authentication with still work well.
### To Reproduce my Problem:
I have the Preinstalled Android only with the lasted Version auf Android.
The KeePass file is hosted on a Nextcloud Server in my Local Network. 
I reinstalled the Keepass App.
1. I reboot my device & use a pin to initial login in my Phone.
2. I access the Keepass File via WebDav over https & open the File with my Keepass Password. 
3. After that the App shows a Notification to activate authentication with fingerprint.
4. With a tap on Yes the App show me the options to authentication with fingerprint. But 
every Time if I tap on one of the options to enable. The App shows me the following Error Message.
![grafik](https://github.com/PhilippC/keepass2android/assets/45150338/02851e6c-76d5-4348-b94b-cdc429cf0016)
> Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException'

Logcat Events wenn ich tap on the options:

> 2023-08-17 14:46:10.062 26392-26392 KP2A                    keepass2android.keepass2android      D  FP: Create BiometricEncryption
> 2023-08-17 14:46:10.067 26392-26392 KP2A                    keepass2android.keepass2android      D  FP: CreateKey 
> 2023-08-17 14:46:10.073  1546-9906  BiometricService        system_server                        D  Sensor ID(0), oemStrength: 255, updatedStrength: 255, modality 2, state: 0, cookie: 0, sensorId 0, hasEnrollments: true cannot participate in Keystore operations
> 2023-08-17 14:46:10.322  1546-1546  WindowManager           system_server                        W  removeWindowToken: Attempted to remove non-existing token: android.os.Binder@effaf89
> 2023-08-17 14:46:10.744  1546-9906  CoreBackPreview         system_server                        D  Window{a3c08ee u0 Toast}: Setting back callback null
> 2023-08-17 14:46:10.763  1546-3747  InputManager-JNI        system_server                        W  Input channel object 'a3c08ee Toast (client)' was disposed without first being removed with the input manager!
> 2023-08-17 14:46:10.770  1546-3747  NotificationService     system_server                        W  Toast already killed. pkg=keepass2android.keepass2android token=android.os.BinderProxy@24aa2b4
> 2023-08-17 14:46:10.798  1546-3747  CoreBackPreview         system_server                        D  Window{8411a52 u0 Toast}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@c493620, mPriority=0}
> 2023-08-17 14:46:10.829  1940-2181  OpenGLRenderer          com.android.systemui                 E  Unable to match the desired swap behavior.
> 2023-08-17 14:46:10.841  1940-2181  Parcel                  com.android.systemui                 W  Expecting binder but got null!

Log from Keepass App after a device Reboot:

[KeePass_log.log](https://github.com/PhilippC/keepass2android/files/12370132/KeePass_log.log)

### Describe what you expected to happen:

Like before the Android update that the options to authentication with fingerprint is possibile on my Fairphone 3

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

13 (6.A.018.0)

**Comment by matthewdjb** [comment]
Just spotted this issue myself. 

Some additional information. 

I guess it's tied to this 
https://forum.fairphone.com/t/fairphone-3-and-3-a13-fingerprint-sensor-update/97654

Android 13 changed the way biometrics for apps requiring higher security works. The sensor software hasn't been upgraded on the Fairphone 3, so it no longer works with such apps. Apparently FP are working on it.

**Comment by R-cohn** [comment]
Thanks for your reply. 
I found this app on the list of apps, that require higher security and didn't work because of that Android change..
[https://forum.fairphone.com/t/list-of-apps-and-their-status-of-fingerprint-support-on-fp3-with-android-13/97658](https://forum.fairphone.com/t/list-of-apps-and-their-status-of-fingerprint-support-on-fp3-with-android-13/97658)
The only solution for me is to wait for the sensor upgrade.

**Comment by R-cohn** [comment]
Thanks for your reply. 
I found this app on the list of apps, that require higher security and didn't work because of that Android change..
[https://forum.fairphone.com/t/list-of-apps-and-their-status-of-fingerprint-support-on-fp3-with-android-13/97658](https://forum.fairphone.com/t/list-of-apps-and-their-status-of-fingerprint-support-on-fp3-with-android-13/97658)
The only solution for me is to wait for the sensor upgrade.
