### ISSUE TITLE
Offline version no longer writes back to backing storage

### ISSUE THREAD

**Issue by bsidhom** [PhilippC/keepass2android#241]
I host my keepass file on Google Drive and always access it via the "system" file picker, i.e., the SAF.

When making changes locally, K2A previously wrote back to the backing storage provider after saving. I would refresh my local Drive client to ensure that the timestamp reflected the most recent changes.

Unfortunately, it appears that writes have stopped propagating to Drive. I'm not sure how long it's been happening, but I believe it has been at least a few months based on missing entries.

I have not yet had the chance to check whether this affects other SAF providers. I will test it out with a local storage provider to try and figure out whether this is a wider problem.

**Comment by bsidhom** [comment]
I've just tested it with [Local Storage](https://github.com/ianhanniballake/LocalStorage). I am able to write back database changes successfully.

This means there's either a problem with K2A's interaction with Drive or with the Drive app itself. I wonder if the SAF semantics changed in a way that broke this with Android 8.

**Comment by hackel** [comment]
When was this actually fixed?  I'm running 1.04b that is supposed to include the above commit, and it just erased a folder and password I added earlier today.  I have no idea how long this has been going on, but it's very distressing that I have apparently been losing all new data!  The last time Google Drive shows the file was updated is 7 March.  :-/

**Comment by PhilippC** [comment]
this is part of the 1.05 milestone, you can install https://play.google.com/apps/testing/keepass2android.keepass2android to get the fix.
