### ISSUE TITLE
[QUESTION] - choose which file to sync with

### ISSUE THREAD

**Issue by Davros23** [PhilippC/keepass2android#2416]
Version 1.09e-r7
I am probably being dumb, but how do I select which file I synchronise the database with?
When I hit "Synchronize Database", a message flashes up (it disappears so quickly, I can't read what it says) and the I get a "files are in sync" message.
Which file is it synchronising with? How do I pick a different one?
Thanks,
Davros

**Comment by finsterwalder** [comment]
Did you open a remove file? Then Keepass keeps a local copy that you can sync (usually automatically or manually)
So you always sync with the file that was opened originally.
