### ISSUE TITLE
[QUESTION] Is there a way to autofill on some apps that implemented their own keyboard inside the apps?

### ISSUE THREAD

**Issue by directentis1** [PhilippC/keepass2android#2425]
**What version of Keepass2Android are you using?**
 I'm using the latest version from PlayStore.

 Some applications, like banking apps don't allow me to use system keyboards so I can't switch to Keepass2Android to autofill my password.
 It even doesn't allow copy-paste menu content so I don't know what's a way to input my password instead of writing it over note and retype it, extremely inconvenient, annoying and reveals the password, especially in crowded places, payment counter...

 Is there any way to autofill such apps, even if there is some module for root phones it would be fine.

Thanks for the help!

---
A quick example.
Those apps don't allow users to input/switch to another default keyboards on the android system, so.... If there is a way.
![](https://i.imgur.com/Zskvofr.png)

**Comment by NumbGnat** [comment]
I can't remember what setting it is, but somewhere there's a setting to enable the keyboard switching portion of Android.

I have a little keyboard icon in the lower right, below my keyboard, that allows me to switch keyboards.

![Screenshot_20240107-213058.png](https://github.com/PhilippC/keepass2android/assets/1946849/c3a7fc2e-13ec-4330-9950-08dad59864db)

**Comment by directentis1** [comment]
@NumbGnat Yes, with usual common applications, I can switch keyboards easily like that... but with some applications, there is no keyboard switching icon.

Google Message
![](https://i.imgur.com/k7v7Qn1.png)

And... Wolfram Alpha for example
![](https://i.imgur.com/Rbt3xkx.png)

**Comment by NumbGnat** [comment]
@directentis1 Yes. I see. Funny.. when I am in Google messages, I have the option to switch keyboards. 

It must be the keyboard you're using that's blocking out that spot.

![Screenshot_20240108-082613.png](https://github.com/PhilippC/keepass2android/assets/1946849/fe533a29-45da-40ec-b9da-645ef908e19a)

**Comment by PhilippC** [comment]
please report this for the authors of such apps to fix. If they don't want you to autofill, the should reconsider this.
