### ISSUE TITLE
[BUG] App Language can not be set back to "System" after it was changed 

### ISSUE THREAD

**Issue by finsterwalder** [PhilippC/keepass2android#2426]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I installed the App and the Language was set to "System", so it uses the same language that my Android system is set to.
Then I changed the language to Englisch.
Now when I change the language I can only set a language, but I can't set it back to use the System language.

### Describe what you expected to happen:

An option to use the system language in the list of languages to choose from.

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

13

**Comment by PhilippC** [comment]
fixed in https://github.com/PhilippC/keepass2android/releases/tag/v1.10-pre
