### ISSUE TITLE
Background processing issues?

### ISSUE THREAD

**Issue by Ruud-cb** [PhilippC/keepass2android#243]
My settings: 
Clipboard timeout: 1 minute. 
Application timeout: 15min
Quick unlock enabled with fingerprint.
My device: Google Pixel 2, running Android. 8.1

What I encountered:
I open a entry, so the notifications appear.
I use them somewhere and lock my phone.
Didn't open this app in the last 4 hours or so. Only used for navigation, Whatsapp, just usual stuff.
But still, the notifications are present to copy my username and password. When i click on one of them it gives me the error message: Sorry! Keepass2Android was killed by the Android OS. For security reasons...etc.

I figured it might be because of Google's battery optimization, turning that off didn't really help.

Sometimes it does sometimes it doesn't work.
While I am typing this I am testing it again and now I notice that I can still copy my password after 1min or 15min. Database still unlocked.

**Comment by PhilippC** [comment]
With the app timeout of 15 minutes, the database should be locked 15 minutes after using KP2A for the last time (where "using" may mean to have it open). When the DB is locked, the notifications to copy data should disappear.
Clipboard timeout is the time between copying something to clipboard and the attempt to remove that from the clipboard.
If the app is killed, it cannot remove its notifications which is not good but hard to change. If you find anything in addition, please re-open this.
