### ISSUE TITLE
[BUG] No Access to Keepass2Android in Georgia via Google Play Store

### ISSUE THREAD

**Issue by GeorgeLubaretsi** [PhilippC/keepass2android#2431]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

The app is unavailable in Georgia, restricting access to a valuable tool, without a valid reason. As changing Google Play Store country is not a trivial feat, this forces users to either set up a different Google account, or download the APK from questionable sources, potentially exposing them to malware.

Please update the app distribution settings to include Georgia in the list of accessible countries.

Steps to reproduce:
1. Open Play Store with Google account's country set to Georgia
2. Search for keepass2android
3. Observe that app is not listed in the search results and banner appears on top, stating: "This app is not available on Google Play Store in your region".

![screenshot](https://github.com/PhilippC/keepass2android/assets/2069680/4bfea4fe-d769-4a1b-bd0d-77b7f3f47b36)

### Describe what you expected to happen:

App should be listed and installable for users with Georgian Google Play Store account.

### What version of Keepass2Android are you using?

N/A

### Which version of Android are you on?

N/A

**Comment by grapexy** [comment]
It's been several months since this issue was raised and got no attention, it just takes one click to enable it and there's no reason it should be disabled.

**Comment by GeorgeLubaretsi** [comment]
@PhilippC I wish I could assist directly by creating a PR, but this change requires your direct intervention. If there's any other way I can support to resolve this, please let me know.

**Comment by PhilippC** [comment]
I changed the play store settings

**Comment by GeorgeLubaretsi** [comment]
@PhilippC I don't think these changes have been applied. It is still unavailable in Georgia as of 2024-04-28
![image](https://github.com/PhilippC/keepass2android/assets/2069680/23d6054e-2076-4981-ba08-fc8efdc5d330)

**Comment by PhilippC** [comment]
I think this will only take effect when I release 1.11. Unfortunately I didn't have any time in the last weeks to check how the test is going and thus didn't do so ye..
