### ISSUE TITLE
[BUG] Error when importing .key file via nextcloud - "Schlüsseldatei existiert nicht"

### ISSUE THREAD

**Issue by Meigl89** [PhilippC/keepass2android#2438]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I switched my nextcloud and wanted to add my keepass files there. Adding the database via nextcloud no problem, but when I add the key, I can choose it and as I enter my password I get the message "Schlüsseldatei existiert nicht".

I didn't do anything different then before.

Maybe a bug or own stupidity?!

### Describe what you expected to happen:

Load the key without error message

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

Android 14

**Comment by Meigl89** [comment]
Ah super stupid nextcloud error.. sorry.

**Comment by PhilippC** [comment]
sounds like this is no longer relevant?
