### ISSUE TITLE
Keepass 2.55 reports "key transformation settings of the database are weak."

### ISSUE THREAD

**Issue by mhschloss** [PhilippC/keepass2android#2440]
I have updated my PC with the latest version of KeePass (2.55) and I am now greeted by the following message upon startup:

        The key transformation settings of the database are weak.

        Do you want to set them to the current default values (recommended)?

My question/concern is that if I change this, will I encounter any problems with KeePass2Android?

**Comment by yanncharlou** [comment]
I just updated keepass to 2.55 and checked Yes on the warning.
Created a new entry as test and synchronized to Keepass2Android.
Everything seems ok.

**Comment by Kuki77** [comment]
And how about other keepass clients, also for iOS, e.g. KeePassium?
Is the adjustment (based on the pop-up) done in KeePass 2.55 OK for the other clients or is it better to wait a bit?

**Comment by Swaddy33** [comment]
I just tried it.
Key derivation AES-KDF with 30’000’000 Iterations. Takes a i7 11gen 0.3 seconds and my S22 3 seconds to open.

**Comment by Kuki77** [comment]
> I just tried it. Key derivation AES-KDF with 30’000’000 Iterations. Takes a i7 11gen 0.3 seconds and my S22 3 seconds to open.

I also tested the recommended setting and opened the DB on iOS with Keepassium. No impact in my eye on DB opening time.

**Comment by ManfredSchenkIOSB** [comment]
> And how about other keepass clients, also for iOS, e.g. KeePassium? Is the adjustment (based on the pop-up) done in KeePass 2.55 OK for the other clients or is it better to wait a bit?

This is the Issue Tracking of keepass2android - you have to ask this question about other clients in the proper place and not here.

**Comment by PhilippC** [comment]
KP2A is still "compatible" with increased parameters so I'm closing this issue
