### ISSUE TITLE
[QUESTION] Can't open the database!! Help

### ISSUE THREAD

**Issue by ElenaCasanovas** [PhilippC/keepass2android#2442]
Hi!
I haven't changed my master sentence to enter my database and it says it is invalid!
Sometimes the app lets me enter with the fingerprint, is quite random, some times asks for the password and other the finger print...
But now that it says my password is invalid (which I think I ok) and doesnt show me the option of the finger print?

What can I do? Can I reset something? is there a way to update the password??

Please any input will help!
Thanks!

Elena

(I'm using 1.09e-r7 version)

**Comment by Schubacka333** [comment]
I have the same problem. I forgot my password and now I can't open the app.. What can I do???

**Comment by PhilippC** [comment]
you can try to open the latest backup in case you think the file got corrupted (select "Change database", enable "Show local backups"). If it still says wrong password, the password is wrong. The app needs the correct password to open the file.
