### ISSUE TITLE
[BUG] Unable to write on Dropbox file

### ISSUE THREAD

**Issue by ReinerBanken** [PhilippC/keepass2android#2444]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I am using KP2A with Dropbox since a few years without any problems. The Dropbox app is installed on my phone (version 348.2.4).

Since a few weeks,  maybe longer, I am getting the message on opening KP2A: unable to write on the source file: in use. Syncing is ok of changes made to the Dropbox file on my PC.

I dissociated and reassociated Dropbox. No change.

I uninstalled and reinstalled KP2A. When opening the Dropbox file for the first time, I did not get any error messages. But it reappeared the next time.

I am getting the error message regardless if KeyPassXC is open on my PC or not.

### Describe what you expected to happen:

In the past, I got an alert when changes were made at the same time to the Drobox file on KP2A and my PC, asking me which changes to keep or to merge changes.

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

13

**Comment by PhilippC** [comment]
if you are using the dropbox app in the process of opening the file, please switch to KP2A's built-in Dropbox support

**Comment by ReinerBanken** [comment]
I placed the .kdbx file in dropbox.com/home/Applications/Keepass2Android and this solved the problem. 

But now I am getting the same message again: _Unable to write on the source file: in use_ even when opening the  .kdbx file in dropbox.com/home/Applications/Keepass2Android

**Comment by PhilippC** [comment]
modifying files on Dropbox works for me. Can you give a step-by-step instruction how to reproduce this error?

**Comment by ReinerBanken** [comment]
1. I am opening my database in the dropboxKP2A folder in dropbox/Applications (see attached screenshot)
![Screenshot_20231113_111806_Keepass2Android](https://github.com/PhilippC/keepass2android/assets/36557835/ae5c2a77-ef65-4bea-aef7-affa5c57d3dc)

2. On  the unlock screen a message appears for 5 seconds _Impossible d'enregistrer sur le fichier source: Utilisation en cours..._  (I am working in French)

I tried to do a screen shot of step 2, but I am getting a message that the security policy does not allow me to do a screenshot.

The problem started to appear a month or two ago.

Is there anything else I can send you?

**Comment by PhilippC** [comment]
Hmm, I cannot reproduce (I also tried on the app folder and with a file with spaces).

Can you 
 * try to create a different file (for testing) and see if you can modify that?
 * try a different Dropbox account
 * enable debug logging and send that to me after the issue occurs?

**Comment by PhilippC** [comment]
I repeatedly see this line: 
`2023-11-14 12:22:54:724 -- keepass2android.Io.OfflineModeException: Working offline.`

after unlocking a database, in the menu there is "Work on internal cache only" to switch to offline mode and "Synchronize cache copy with source". If you see the latter, please select it to switch back to "online mode"
