### ISSUE TITLE
[QUESTION] in App completion

### ISSUE THREAD

**Issue by Stefanqn** [PhilippC/keepass2android#2447]
I lost in Keepass's in app completion, when  changed from my Xiaomi Mi 9 to a Google Pixel 8.

I can't install the [autofill plugin](https://philippc.github.io/keepass2android/AccServiceAutoFill.html). Yet, the functionality was also present at my old Mi 9, with V1.09e-r7 and Android 10.

What am I missing?

Screenshots from my old Mi 9:

![Screenshot_2023-10-23-10-12-08-352_org mozilla firefox](https://github.com/PhilippC/keepass2android/assets/139038/5b024ebb-254f-4840-96de-b137fa05d61a)
![Screenshot_2023-10-23-10-12-19-309_keepass2android keepass2android](https://github.com/PhilippC/keepass2android/assets/139038/5c558a7d-322b-4099-9b8a-e5a7a106f86c)

**Comment by PhilippC** [comment]
you need to enable the KP2A autofill service. go to settings - app - password access

**Comment by Stefanqn** [comment]
it seems that [this is working for bitwarden](https://github.com/bitwarden/mobile/issues/2826)

**Comment by Stefanqn** [comment]
yes, thank you. It works without installing the autofill plugin.
