### ISSUE TITLE
[BUG] Autofill attempts to save system passwords in Android 14

### ISSUE THREAD

**Issue by metronidazole** [PhilippC/keepass2android#2449]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Since updating to Android 14 I've noticed the password autofill service for keepass2android trying to save inappropriate passwords such as the phone's lockscreen password (e.g. when entering fingerprint settings). This didn't use to occur with Android 13.

### Describe what you expected to happen:

The autofill service should not offer to save system passwords

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

14

**Comment by PhilippC** [comment]
can you post a screenshot of the activity where this appears?
