### ISSUE TITLE
KP2A Keyboard external dictionaries does not work

### ISSUE THREAD

**Issue by torkelsson** [PhilippC/keepass2android#245]
The advanced documentation for K2PA keyboard says that it should work with dictionaries from Hacker's keyboard and AnySoftKeyboard. 

I have both Hacker's keyboard as well as AnySoftKeyboard installed with Swedish dictionaries. The dictionaries does not show up in KP2A Keyboard.

Huawei Mate 10 Pro, running Android 8.0.0.

**Comment by robertg042** [comment]
Would be awesome if someone looked into this issue. I have far too small programming experience. That would be a killer feature!

**Comment by tome9111991** [comment]
hi
i install the dictionaries
but not working.
