### ISSUE TITLE
[FEAT] Special request... No feature, keep it secure!

### ISSUE THREAD

**Issue by JGG-Apps** [PhilippC/keepass2android#2453]
I have a special request for your team that is more a security minding like KeepassXC team have decided to follow !

Ilove using KeePass '"solution" where it's an OpenSource project, where it's possible to use many software option... and where this allow you the capability to port this application on Andoid OS 

...the KeePass database is very safe and I hope it will still for a while. But like you probably know it exist some security breachs in KeePass products... and these breachea are basically caused by the capabilities to use interactive plugins... it where a major difference exist between KeePass and KeePassXC. Then, when we talk about KeePass solution for Android, you are the reference and I wish you will still a reference for long time. Then my request is to keep in mind to never add an option in your product (or remove it if it's already there) where it allow to export/sync/stole database content!

**Comment by PhilippC** [comment]
I am well aware that security needs to be taken into account in every line of code I write :-)
