### ISSUE TITLE
broken link in doc

### ISSUE THREAD

**Issue by gerald2545** [PhilippC/keepass2android#2454]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

the link at the bottom of the following doc https://github.com/PhilippC/keepass2android/blob/master/docs/How-to-create-a-plug-in_.md is broken : https://keepass2android.codeplex.com/SourceControl/latest#src/java/PluginA/

### What version of Keepass2Android are you using?

NA

### Which version of Android are you on?

NA

**Comment by PhilippC** [comment]
updated the page
