### ISSUE TITLE
[FEAT] Support token-only otp field?

### ISSUE THREAD

**Issue by 12425** [PhilippC/keepass2android#2458]
If the otp field is a raw token (not otpauth://), the app does not show TOTP code.

This does not work:
`otp` field is `{token}`
This works:
`otp` field is `otpauth://totp/?secret={token}`
That means the issuer and username are optional, and only the token is required, so can we support `{token}` only?

Typically I copy the raw token from the issuer website, save into 'otp' field in Keepass, and don't make it `otpauth://`. Both the Windows KeePass (with KeeTrayTOTP plugin) and KeePassXC support raw token, so I wish keepass2android can support it.
Thanks!

**Comment by PhilippC** [comment]
can you please provide a database with such a field as an example (please use dummy data, of course). I tried to configure an item as you described but KeeTrayTOTP doesn't recognize this if there is only an `otp` field.

**Comment by PhilippC** [comment]
I'm closing this. Please reopen when you have prepared the sample database.

**Comment by 12425** [comment]
[sample-otp.kdbx.zip](https://github.com/PhilippC/keepass2android/files/13813002/sample-otp.kdbx.zip)

Thank you for your reply!
I just uploaded a `sample-otp.kdbx`.
It has 2 entries.
* `otp-full-url`: it has a field `otp` with `otpauth://totp/?secret=base32secret3232`. When I click the entry and it shows an extra field `TOTP` with the 6-digit code.
* `otp-secret-only`: it has a field `otp` with the raw key `base32secret3232`. I wish I could also see the `TOTP` field, as my kdbx has whole bunch of `otp` fields with key only.


Thanks!

**Comment by PhilippC** [comment]
thank you @12425! can you share the master key, please? Did you check that otp-secret-only works with KeeTrayTOTP?

**Comment by 12425** [comment]
Sorry my bad, the master password is `abc`.
Yes it's compatible with KeeTrayTOTP. Select one entry and click Ctrl-t, the 6-digit code will be copied.

**Comment by PhilippC** [comment]
can you give the version of KeePass2 and KeeTrayTotp that you are using? For me (2.55 and 0.180) it doesn't work (for both entries):
![image](https://github.com/PhilippC/keepass2android/assets/5421734/57b96884-45ef-4c5a-9a18-5b80b02ffb92)

**Comment by 12425** [comment]
Version:
KeePass 2.51.1 64-bit (Windows)
KeeTrayTOTP 0.108.0.0

After changing the field name, Ctrl-t works.

![image](https://github.com/PhilippC/keepass2android/assets/1549210/94bce2ab-5b67-45e5-b7b4-7736ac39c530)

**Comment by PhilippC** [comment]
ah, I see. It seems like this is not a good idea to do IMO. If you use this database with KeePassXC, it does output TOTPs, but you get different ones from KeeTrayTOTP. Unfortunately, there are too many TOTP storage options out there in KeePass implementations...

Keepass2Android currently supports these:

* Keepass2 style: used when there are TimeOtp-Secret fields
* KeeOtpPlugin style: used when there is an otp field containing a query string in the form of key=abc&step=X&size=Y (step and size are optional)
* KeeWebOtp/ Key Uri Format style: used when entry contains a URL starting with otpauth://totp/, e.g. otpauth://totp/?secret=abc (https://github.com/google/google-authenticator/wiki/Key-Uri-Format)
* TrayTotp style: 
  * requires a non-empty seed field (default key is "TOTP seed", can be changed in app settings), value is base32 encoded data
  * requires a non-empty settings field (default key is "TOTP Settings", can be changed as well), value is expected to be a csv-separated array with [Duration];Length(;TimeCorrectionURL). Length is either an integer value or "S" to indicate Steam encoding
  
Anyway, it was easy to update the TrayTotp style implementation to make the settings field optional (using the same defaults as KeeTrayTotp). If you set the TOTP Seed field name in KP2A's settings to "otp", your usecase is fulfilled, but I still suggest to use something more explicit (Key Uri Format or at least KeeOtpPlugin style) for better interoperability.

**Comment by 12425** [comment]
Thanks for the explanations!

I was able to make it work by

* In KP2A settings / TrayTotp:
  - Set the seed field name to `otp`
  - Set the setting field name to `otp-setting`
* In the entry `otp-secret-only`:
  - The field `otp` is the raw secret key
  - Add another field `otp-setting` whose value is `30;6`

With latest version, I have to add the `otp-setting` to every entry that has `otp` field, and in the next version, the `otp-setting` field will be optional, am I correct?
