### ISSUE TITLE
Using database from Google Drive: Changes lost

### ISSUE THREAD

**Issue by anoopelias** [PhilippC/keepass2android#246]
For version 1.03 from Play Store.

Steps to reproduce:
1. Open file -> System File Picker -> Choose Google Drive on the left menu and then select a file.
2. Enter password and then make a test entry.
3. Lock and close the database.

Got a toast : "Updated local cache copy of the database file"
Test entry is now lost!

**Comment by PhilippC** [comment]
thanks for reporting, bad bug!

**Comment by PhilippC** [comment]
same as #241: the main problem is that changes are never written to Google Drive.
