### ISSUE TITLE
[BUG] Cannot install on Chromebook v118 

### ISSUE THREAD

**Issue by bubibubi** [PhilippC/keepass2android#2465]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

The error is simply "Application not available for this device"

### What version of Keepass2Android are you using?

n/a

### Which version of Android are you on?

Chromebook 118

**Comment by Spiralpine** [comment]
Search the open and close issues. This has already been addressed.

**Comment by bubibubi** [comment]
I've seen only bugs running Keepass2Android.

just in case:
* I used Keepass2Android with a Lenovo Ideapad Flex 5 updated (I can't remember the version but newer than 110) and it used to work fine
* With 118 I can't install it using app store so I can't check if it works (this ticket)

If I can install it I can check it on HP X360 with v118

**Comment by Spiralpine** [comment]
bubibubi - Look at issue#2316 and 2448 for example. The Keepass2android is not currently available for Chromebooks on the Play Store (read 2316 to find out why). The next version should show up on the Play Store.

Also, this is not a "bug" as you have filed your issue. I recommend you first read 2316 and 2448 and then close your issue to reduce clutter.

**Comment by bubibubi** [comment]
Duplicate of #2316
