### ISSUE TITLE
[BUG] Application Log File can leak internal KBDX Details

### ISSUE THREAD

**Issue by Ray-B** [PhilippC/keepass2android#2466]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Similar to the issues addressed in another PR: https://github.com/PhilippC/keepass2android/pull/2464/files

The application log file also appears to leak other information from inside the KDBX file such as folder names. 

For example:

```
11/22/2023 11:12:09 PM:120 -- Populating group view False Company Passwords Example Folder
11/22/2023 11:12:09 PM:123 -- Populating group view False Personal Passwords Example Folder
11/22/2023 11:12:09 PM:126 -- Populating group view False Recycle Bin Example
11/22/2023 11:12:09 PM:128 -- Populating group view False Banking Example Folder
```

### Describe what you expected to happen:

Log file should not contain any information from inside the KBDX. If iterating accross folder structures is needed, then the log store this information as random GUIDs perhaps.

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

13

**Comment by PhilippC** [comment]
I didn't consider the group name sensitive, but I removed the log output to be more safe
