### ISSUE TITLE
[Feature Request] improvements for other 2fa besides yubikey

### ISSUE THREAD

**Issue by MrSauna** [PhilippC/keepass2android#247]
Sorry for being vague but I just don't understand the technical aspect of 2fa security keys. I just bought Feitian ePass NFC and it's quite painful in practice on android. My goal is to use HOTP. At the moment I use it with an otg cable trough usb, it works but k2a could at least offer auto-tab when filling otp keys to ease use of everything besides Yubikey. From what I understand k2a offers NFC interface for yubikey out of the box but not for Feitian NFC. I couldn't find comprehensive material about Feitian NFC's functionality but I would appreciate if somebody had insight of it. Could filling OTP keys trough NFC be implemented for Feitian NFC? Does Feitian even support HOTP trough NFC or only U2F (from what I gathered nobody has had OTP trough NFC wokring)?

At least the implementation of auto-tab would be considerably helpful.

**Comment by iinuwa** [comment]
I read somewhere that Feitian's NFC key only supports OTP over USB, not NFC. I'll look for the reference.
