### ISSUE TITLE
Keepass2Android: How to change the password used to access a database over sftp?

### ISSUE THREAD

**Issue by dstromberg** [PhilippC/keepass2android#2471]
Hello.

I've been using Keepass2Android  1.09e-r7, and it's been working great.

However, now I want to change the password to the (ssh'able) account Keepass2Android's database is sftp'd to and from - and I'm finding it difficult. Google search isn't much help, because "keepass2android change sftp password" gives thousands of irrelevant hits.

I changed my server's account password using /usr/bin/passwd, but then Keepass2Android hung on open, and my server went inaccessible for a while - I suspect the hosting service saw a bunch of failed ssh attempts and blocked access temporarily. I can ssh to it now, but I couldn't previously. This has happened twice today.

Anyway, how can I change the password that Keepass2Android uses to access my keepass password database over sftp?

Thanks!

**Comment by PhilippC** [comment]
in the list of recent files, tap the three vertical dots and select Edit
