### ISSUE TITLE
[BUG] Feedbacks about 1.10-pre release

### ISSUE THREAD

**Issue by Latruffy** [PhilippC/keepass2android#2474]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Mainly feedbacks about pcloud since it's my present issue.

Context : Let's say I've got a pcloud account as id Alan. I want to host my kdbx file on it, and my son's one, firstname Bob. I create a free pcloud account for him.

Here is the plan :

Alan's account :
/Applications/Keepass2Android/alan/	(physical folder)
`     `alan.kdbx
/Applications/Keepass2Android/bob/	(physical folder, shared to Bob's account (with modify rights))
`     `bob.kdbx

Bob's account :
/Applications/Keepass2Android/	(physical folder)
`     `remotebob/	(mount point of bob folder shared from Alan's account)
`     `local/	(physical folder)

Facts :
- As Alan, I install 1.10-pre apk on my smartphone, select either "pcloud KP2A" or "pcloud complete" mode, and use my Alan's pcloud account credentials, I succeed in opening my db file alan.kdbx.
(the same if I test opening bob.kdbx still with **my** credentials)
- But if on Bob's smartphone, selecting "pcloud KP2A" mode, and using Bob's pcloud account credentials, I browse folders, I can see "local", but not "remotebob".
If in this last case I select "pcloud complete" instead, even "local" doesn't appear.

Some other points :
- On the same smartphone, if I open a pcloud hosted kdbx file, it's impossible to open a second one hosted on another pcloud account. The same credentials (and then account) are used for both opening.
Could you pleas	e allow this ?
- Is there a way, in the app, to manage (delete,...) databases already defined ? For example I needed to delete a database to force pcloud credentials request to open another database (see the point just above) ? I didn't find a way...
- Last point : sometimes, "burger menu" (the 3 vertical dots) at the top right of the screen aren't visible (and then unreachable). Even the top right padlock icon is a little bit nibbled on the right.

Thanks by advance for your upcoming fixes.
Regards

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

Android 10 (LineageOS 17.1)

**Comment by PhilippC** [comment]
I don't know how to implement this. I'm waiting for a reply on https://github.com/pCloud/pcloud-sdk-java/issues/33
