### ISSUE TITLE
[FEAT] customize pcloud folder

### ISSUE THREAD

**Issue by tkuraku** [PhilippC/keepass2android#2475]
Is it possible to allow the user to specify the pcloud folder for the database file?

It isn't a big deal, but would be nice to have.

**Comment by medialwerk** [comment]
I would be interessted in this feature too. I don't like to put my kdbx file in a "Keepass2Android" folder. I sync the file because I want to use it on other devices with different Apps.

**Comment by PhilippC** [comment]
this is implemented in the current beta version 1.10: https://play.google.com/apps/testing/keepass2android.keepass2android or https://github.com/PhilippC/keepass2android/releases

**Comment by medialwerk** [comment]
Oh I didn't see that, I apologize. Thank you very much, I'm very happy about that feature!
