### ISSUE TITLE
[FEAT] Option to Close Database instead of Lock

### ISSUE THREAD

**Issue by BrassStack** [PhilippC/keepass2android#2476]
I've noticed that with a kdbx in Dropbox, I get fewer conflicted copies if I make sure to close the database when I'm done with it on my phone.  Please add an option to always close database instead of lock, when normally the app would lock the database (timeouts, after exiting, etc.).

Even better:  Let us choose for each type of event whether the database will lock or close.

**Comment by PhilippC** [comment]
please disable Quick Unlock in the app's settings to always close the database.
