### ISSUE TITLE
Password problem

### ISSUE THREAD

**Issue by dovmalz** [PhilippC/keepass2android#2479]
[QUESTION] Hi, I'm using keepass android v. 1.09 & am having problems with the password. I had copied my vault to dropbox and attempted opening it with the keepass password I'd created. However the password was invalid. Should I simply create a new vault and password? Thank you

**What version of Keepass2Android are you using?**
Please follow these steps to find your app version:
1. Click the **⁝** icon in the top right corner
2. Sele ct **Settings**
3. Click **About**
4. Find the "Version" information and provide it here:

**Comment by PhilippC** [comment]
where did you copy it from? How did you copy it?

**Comment by dovmalz** [comment]
I copied/pasted direct from the database. I just ended up creating a new file.
Thanks!

Ari Silverman
he/him
