### ISSUE TITLE
File access denied after install Android v14

### ISSUE THREAD

**Issue by 1reese1** [PhilippC/keepass2android#2480]
**What version of Keepass2Android are you using?**
Please follow these steps to find your app version:
1. Click the **⁝** icon in the top right corner
2. Select **Settings**
3. Click **About**
4. Find the "Version" information and provide it here:1.09e-r7
5. Just installed Android v14. Tried to save a new password entry and could not. Error message: Acess to path "/storage/emulated/0/keepass2android/"filename".kdbx.9950DF.tmp" is denied. Keepass2Android v1.09e-r7 Android v14 OneUI v6.0

**Comment by PhilippC** [comment]
if android has revoked permissions for the app to access the file, please open it freshly ("Change database" => "Open database").
