### ISSUE TITLE
[QUESTION]  Don't use K2A for an specific App

### ISSUE THREAD

**Issue by hollysheep** [PhilippC/keepass2android#2481]
**What version of Keepass2Android are you using?**
1.09e-r7

Can i disable K2A for a specific App so that nothing happens when i enter a password in that app?

**Comment by PhilippC** [comment]
do you mean regarding the Autofill question "Do you want to save credentials..."?

**Comment by hollysheep** [comment]
Yes. Can i see the list somewhere and can i add apps manually to that list? That could be interesting when i have a new device or install android completely new. Also an option to export the settings could be useful.

**Comment by PhilippC** [comment]
when you see the option to autofill the fields (either integrated in the keyboard or as an autofill popup), you can choose something like "Disable autofill with KP2A". This will add the current app/website to that blacklist. It should then also suppress the question if you want to save the credentials.

**Comment by tomasmueller** [comment]
Is there a feature to Export the settings to an other instance of k2a so that these settings will work in a New device?
