### ISSUE TITLE
"previous versions" entries crash app

### ISSUE THREAD

**Issue by metaxis** [PhilippC/keepass2android#2484]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Tapping on a previous version (a text button with a date and time) within a record entry immediately crashes the app.  I tried several different entries with version history.  I could not repro with a fresh entry created within the app, so the entries must not conform to current expectations due to older app version or more likely other KeePass2.0 apps the db is shared with.

### Describe what you expected to happen:

Tap on previous version, see screen with older entry and options to restore or delete.

If entry is non-conforming or corrupted, expect a helpful error message and no crash, ideally some sort of record rebuild/ repair option, or extract to text as last resort for recovery.

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

10

**Comment by metaxis** [comment]
Bad search, Duplicate of #2325

**Comment by PhilippC** [comment]
closing as duplicate
