### ISSUE TITLE
show where the opened dB is stored

### ISSUE THREAD

**Issue by m707** [PhilippC/keepass2android#249]
Sorry, if I overlooked the obvious, but I find no way where the app can show me which /xxx/xxx/xxx/mydb.kdbx dB is open at present :(

**Comment by PhilippC** [comment]
when is this important to know?
A simple way to view it is to quick-lock the database, it's shown on the QuickUnlock screen...

**Comment by m707** [comment]
If I wanted to delete the DB from my phon, thought it is in folder A, but it wasn't :(. I tried to find out where this %&! DB is stored, but couldn't find it. QuickUnlock screen is the right hint, THX.
