### ISSUE TITLE
[BUG] clipboard cleaning not working on android 13

### ISSUE THREAD

**Issue by Olifair** [PhilippC/keepass2android#2491]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I have just installed keepass2android on a Android 13 phone (Samsung note). This new version of Android (my phone before was Android 10 ;-) gives the possibility to have a look at the last 6 entries in the clipboard (in any input box, lets say an sms, long press, gives me s pop-up with copy paste possibilitites, but also a clipboard icon). And this list of 6 entries also shows the last passwrods copied from Keepass2Android, in clear letters ! And even setting the auto clean function to 30 seconds does not clean up the clipboards, and the passwords are still there days later. This seems to me to be quite a security probelm. Anybody else has observed this ? I have searched the issues for "clipboard" and not found anything relevant.  

### Describe what you expected to happen:

I expect that the passwords are cleaned out of the clipboard after the number of seconds or minutes defined in the preferences. 

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

Android 13  ONe UI 5.1

**Comment by Olifair** [comment]
finally linked to issue [https://github.com/PhilippC/keepass2android/issues/2102] and others therein, even though not quite the same (because only about the passwords being in clear writing, but not about the auto cleaning.

**Comment by PhilippC** [comment]
android's clipboard should not be used for sensitive content because the app cannot force other apps to clear their data. this is mentioned in the app and in the docs.

**Comment by Olifair** [comment]
OK, but even though, the autoclean feature does not work on Android 13, so either this feature should be disabled to avoid confusion, or this issue is not really solved

**Comment by PhilippC** [comment]
it works on some systems and doesn't work on some. The app outputs a warning to indicate this and the fact is stated in the documentation.
