### ISSUE TITLE
[BUG] android keyboard is shown above keepass2android making it unusable

### ISSUE THREAD

**Issue by soredake** [PhilippC/keepass2android#2507]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

What happened:

https://github.com/PhilippC/keepass2android/assets/5204968/43360014-b9bd-4fb8-92b9-c62b679f2c59

If I rotate the screen, then I can get this popup without keyboard:
![Screenshot_20240112-144027_Keepass2Android](https://github.com/PhilippC/keepass2android/assets/5204968/deaf0b8b-ef46-4318-81c1-8005abeae670)

### Describe what you expected to happen:

A keyboard should not appear and force me to rotate the screen in order to use the app.

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

12L (crdroid rom)

**Comment by PhilippC** [comment]
does this happen with every target app for you and all the time? I wasn't able to reproduce (on an Android 14 device, testing with Feedly as well).
I pushed a change which will hopefully fix this. Please re-open if after the next update this issue remains.
