### ISSUE TITLE
[QUESTION] Are GitHub Releases up to date?

### ISSUE THREAD

**Issue by skwde** [PhilippC/keepass2android#2509]
I am wondering if the github releases are up to date? 
If so, why the date difference when comparing date of the latest release on github and the date on google play store?
If not, can the github releases be kept up to date?

The reason for asking, I would like to use Obtainium to get keepass2android and not rely on the Play store.

**Comment by PhilippC** [comment]
yes, the Github release is the latest available release. I uploaded in the Play Beta Channel when uploading to Github, but Play probably shows the date when I started to roll out in the production channel.
