### ISSUE TITLE
Is dropsync necessary?

### ISSUE THREAD

**Issue by ewgoforth** [PhilippC/keepass2android#2522]
I'm using 1.10 pre on Android 14 on a Galaxy S21+.  

My work has apparently disabled personal OneDrive accounts and so I'm going to have to go back to using DropBox for my keepass files.  I believe that years ago it was necessary to run DropSync in order to synchronize DropBox keepass files.  Do you know if this is still necessary?

Thanks,
Eric

**Comment by stysedo** [comment]
We use keepass2android from the Play Store to sync with DropBox with no additional android software.

**Comment by PhilippC** [comment]
use KP2A's built-in dropbox support, don't use third party tools.
