### ISSUE TITLE
[BUG] No means to exit/back out of keepass

### ISSUE THREAD

**Issue by jddavidm** [PhilippC/keepass2android#2523]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

No option button available when in "Settings"

### What version of Keepass2Android are you using?

Version 1.10-pre

### Which version of Android are you on?

Version 14 on Pixel 7a

**Comment by PhilippC** [comment]
Android always has a "back button". Please reopen if this doesn't work
