### ISSUE TITLE
[BUG] Can't disable notification while database is locked

### ISSUE THREAD

**Issue by eRaz3r** [PhilippC/keepass2android#2526]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

On A14 (Galaxy S24 U) I am not able to disable the notification while the database is locked without affect the functionality of keepass itself. Maybe a layer 8 problem but I cant solve it by my self.

Realy apreciate any help. 

### Describe what you expected to happen:

Disable the Notification while Keepass database is locked and only show it when its unlocked.

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

14

**Comment by PhilippC** [comment]
long press the notification and go to Android's notifications settings. Enable "Database unlocked" and disable "QuickUnock"
