### ISSUE TITLE
[FEAT] export selected entry and/or entire folders

### ISSUE THREAD

**Issue by TruthTeller365** [PhilippC/keepass2android#2528]
Make a new button in the three dots which appear when you select one or multiple entrys or folders. The button should be named something like Export selected and share it password secured.
That button takes you to a configuration menu, which let's you select which Information of the entrys or folders you want to export. For example if you want to share only user and password or if you only want to share the optional text fields. After clicking okay you get taken to the next page. That page let's you set or generate a password with which the file get encrypted. After clicking okay, it save a ****.kpdbexport file to your device. Then the user can send it to someone else who can import it to a selected location. By clicking import, the user gets to input the password earlier set by the other user. If input is correct the password get copied to the database and just work as it were created by the user itself. If the input is wrong, even if it's the first try, then the file should get destroyed by itself.

That would make it possible to share passwords safely without sharing your whole database with for example the master key.

**Comment by PhilippC** [comment]
the app supports multiple databases and copying/moving entries between those. So to do what you want to do
 * create a new database
 * create a copy of the entries you want to transfer
 * move the copy of the entries to the new database
 * remove any information you'd like not to be transferred
 * open the entries and remove old versions (which would still contain the information you don't want to transfer)
 * share the new database 

the other user simply opens the database and moves the entries to the location of his choice in his database.
