### ISSUE TITLE
Datei öffnet nicht mehr[BUG] 

### ISSUE THREAD

**Issue by leachim2205** [PhilippC/keepass2android#2534]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Beim öffnen von keypass wird angezeigt dass die Datei korrupt oder beschädigt ist oder gar keine keypass Datei ist.
Ich habe aber nichts anderes gemacht als sonst auch.

### What version of Keepass2Android are you using?

Die aktuellste App Version und auf Windows die 2.56

### Which version of Android are you on?

12

**Comment by PhilippC** [comment]
can you try to open the local backup (select Change database, then enable "Show local backups" and select the backup for the db)

**Comment by leachim2205** [comment]
I did. And I managed to export it as new database in my Dropbox folder.
The damaged database (don't know any reason) had only about half the size of the "good" one. Just like that...
Maybe due to an update of the app.
Thanks anyway.
Michael

19.02.2024 09:13:26 PhilippC ***@***.***>:
