### ISSUE TITLE
[FEAT] Biometric authentication with multiple fingerprints

### ISSUE THREAD

**Issue by CAFxX** [PhilippC/keepass2android#2547]
I know that Android in general allows to set multiple fingerprints for biometric authentication; what I don't know is if the application requesting biometric authentication can distinguish between which of the allowed fingerprints were used.

If detecting which fingerprint was used is possible, it would be great if keepass2android could require the user to perform authentication either a) with more than one of the allowed fingerprints or b) with a specific sequence of fingerprints. Whether a) or b) is required should depend on user preference.

**Comment by PhilippC** [comment]
the Android APIs don't allow this unfortunately, see e.g. https://stackoverflow.com/questions/51523053/how-to-know-which-finger-is-scanned-for-bio-metric

**Comment by CAFxX** [comment]
Long shot, but filed a request upstream: https://issuetracker.google.com/issues/326639467
