### ISSUE TITLE
Dropbox Auth Error

### ISSUE THREAD

**Issue by G3tHob** [PhilippC/keepass2android#2552]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I'm getting, "authenticating not successful." I uninstall the reinstall and it works for like twice then goes back to the error.

Pix8

### Describe what you expected to happen:

I expected to work flawlessly like it's done for years.

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

14

**Comment by PhilippC** [comment]
If you say "dropbox", how exactly did you open the database? Are you using the built-in dropbox implementation (i.e. you selected Open Database > Dropbox) or are use accessing the file through the system file browser? (In the first case, the displayed filename starts with `dropbox://`)

If you are using the built-in dropbox implementation: do you have the dropbox app installed? This affects the authentication workflow for KP2A?

**Comment by PhilippC** [comment]
I just realized that the error message you mention only can happen if you choose OneDrive. So what are we talking about?

**Comment by G3tHob** [comment]
Do you have any idea why this is happening? Like I said my workaround is
your offline app, but I would rather access Dropbox given all my other
machines (KeepassXC) rely on it. Don't want to continually download each
database to each machine due to changes I make in the database. Hope that
made sense.

Why would it work after uninstalling and reinstalling for only about two
times? Then I have to repeat the uninstall and reinstall in order to make
it work two more times. It's just weird.

**Comment by G3tHob** [comment]
My apologies! I accidentally added your online app to my VPNs split
tunneling. It's simply wasn't connecting. I almost didn't check it given
the fact there was no way I would have done that, but apparently I did.
¯⁠\⁠(⁠°⁠_⁠o⁠)⁠/⁠¯

Thank you for contacting me about this anyway. One of the reasons I like
your apps because you're an active developer that's willing to help.

I will be closing the ticket on GitHub immediately.

Be well
