### ISSUE TITLE
How to automatically sync my mobile database with pc ?

### ISSUE THREAD

**Issue by Shane9248** [PhilippC/keepass2android#2553]
This may sound very noob as i am not very knowledgeable about keepass but whenever i add new entry into a database in Android ..i manually export the database into pc and open the new database in pc again and again so that new entry can also appear in pc ..is keepass solely a offline password manager ? is there no way it can automatically add new entry into pc as well when i enter new entry in mobile... through online mode or something like that ?

**Comment by ikanakova** [comment]
It might help to read the [FAQ](https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md#faq).

**Comment by Shane9248** [comment]
> It might help to read the [FAQ](https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md#faq).

![IMG_20240226_214657999.jpg](https://github.com/PhilippC/keepass2android/assets/83491863/2149d603-ba39-4d35-bb32-399fc3fc7a7c)

i linked my Android database with gmail and i can link gmail with pc by clicking 'Open URL' ? and it shows this ..but what do i enter for url and what is username ?

**Comment by Shane9248** [comment]
nvm thanks to a video on YouTube it helped me....took time to figure it out but did it without url
