### ISSUE TITLE
kdbx Datei im Netzwerk öffnen[FEAT] 

### ISSUE THREAD

**Issue by schmokso** [PhilippC/keepass2android#2557]
Unter "Datei öffnen" - "Speichertyp" existiert keine vorgefertigte Möglichkeit um eine vorhandene kdbx Datei die sich im Netzwerk befindet zu öffnen.
Es gibt zwar den Button "Android-Browser", dieser ist aber so unfähig das man nur lokale Dateien öffnen kann. Hier könnte man ev. einen anderen Datei-Browser auswählen falls dieser auf dem Anfroid Handy installiert ist.
lG schmokso

**Comment by PhilippC** [comment]
duplicate of https://github.com/PhilippC/keepass2android/issues/82
