### ISSUE TITLE
[Feature Request] Add Nextcloud as an alternative to the owncloud option

### ISSUE THREAD

**Issue by SweetDonky** [PhilippC/keepass2android#256]
At this moment there is an integration in the keepass2android app for owncloud.
As more and more people switch from owncloud to nextcloud, would it be an idea to further support nextcloud in the sameway other storage providers such as dropbox and owncloud get supported?

Thanks for listening!

**Comment by PhilippC** [comment]
Technically there is no difference. You can simply select "ownCloud" and enter your URL/user/pass for your nextCloud installation!

**Comment by stefanhoth** [comment]
Can confirm. Switched from Owncloud to Nextcloud and the app works the same.

**Comment by jkaberg** [comment]
Nextcloud/Owncloud provides WebDAV aswell, so there's also that.

**Comment by Lappro** [comment]
I did notice it is required to add "https://" to the nextcloud URL, perhaps it would be nice to add http(s):// automatically if it is omitted.
But the connection indeed is working.

**Comment by jhesketh** [comment]
Yep, it does work, but as a feature request it would still be nice to have nextcloud as a separate option to ensure it is disambiguous to newcomers (even though it could just be a wrapper around the owncloud implementation).

**Comment by ikke-t** [comment]
It kinda works. Ot works fine for me, but when there is conflict, the merge fails to 401 errors. So not reliable, unfortunately. There is another issue for this though. Just FYI.

**Comment by skorokithakis** [comment]
I agree that this would confuse people less if there were either a separate option, or if the existing one were labeled "OwnCloud/NextCloud".

**Comment by tobiasKaminsky** [comment]
Having ownCloud/Nextcloud in one button might look a bit crowded.
May I open up a pull request, which adds Nextcloud as a separate button, with a decent logo?
And I suggest to either group it by "type" or sort all buttons alphabetically (keeping "open with external app" as last one).
