### ISSUE TITLE
[BUG] the app does not work well with power management 

### ISSUE THREAD

**Issue by markjansennl** [PhilippC/keepass2android#2566]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

The app keeps crashing if normal power management is enabled. The app needs to be excluded from all kinds of (normal Android) power management to keep on functioning. Hence, quick open doesnt work unless power management is disabled for the app. Cant this be fixed? It used to work perfectly. Thanks. 

### Describe what you expected to happen:

See before 

### What version of Keepass2Android are you using?

1.10pre

### Which version of Android are you on?

14

**Comment by srdgtr** [comment]
You could try to give it more rights, for battery. Samsung and a few others have a habit of killing many background apps prematurely. 
Open the settings of the app, look for battery settings for app. And select the option unlimited. As the battery use is very low. Also look for updates for your phone might fix this.

**Comment by PhilippC** [comment]
QuickUnlock works by keeping the database open in the background. There is no other secure way AFAIK. If you want to use it, exempt KP2A from "battery optimization". If you don't want to do so, you need to fully unlock (e.g. with biometry).
