### ISSUE TITLE
自动填充自动关闭

### ISSUE THREAD

**Issue by TTDNS** [PhilippC/keepass2android#2571]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

自动填充打开后，过一会设置里的自动填充显示未启用

### Describe what you expected to happen:

我希望自动填充能一直保持打开，不会自动关闭

### What version of Keepass2Android are you using?

1.11

### Which version of Android are you on?

android12

**Comment by Kaligula0** [comment]
please, use English

**Comment by TTDNS** [comment]
Android 12

**Comment by TTDNS** [comment]
keepass2android.keepass2android-1.11-r0

**Comment by TTDNS** [comment]
> 拜托，用英语

When AutoFill is turned on, the AutoFill display in the settings is not enabled after a while

**Comment by TTDNS** [comment]
I want autofill to stay on all the time and not turn off automatically

**Comment by Mikachu2333** [comment]
> I want autofill to stay on all the time and not turn off automatically

啥系统？我这里测试着小米的澎湃没问题，华为鸿蒙偶尔出现，估计与厂商策略有关

Which sys do you use? HramonyOS, HonorUI or HyperOS, etc. Different system has different policy.

**Comment by TTDNS** [comment]
> > I want autofill to stay on all the time and not turn off automatically
> 
> 啥系统？我这里测试着小米的澎湃没问题，华为鸿蒙偶尔出现，估计与厂商策略有关
> 
> Which sys do you use? HramonyOS, HonorUI or HyperOS, etc. Different system has different policy.

Magic UI

**Comment by Mikachu2333** [comment]
问了下其他用荣耀的朋友也会出现这个问题，可以试试把自启动权限开开，后台清理禁止，然后会好一点点……确实是厂商不想让用户使用第三方密码管理器导致的，不是软件本身的问题

I've asked other users who use _Magic UI_ about this issue. Maybe turn on the self-startup permission and avoid cleaning in the background permission would improve the situation... 

Because the manufacturer doesn't want users to use third-party password managers, not because of the software itself.

**Comment by PhilippC** [comment]
thanks @Mikachu2333  for investigating this. I am closing this as it doesn't seemto be an issue with KP2A.

**Comment by TTDNS** [comment]
没事了，我换新手机了
