### ISSUE TITLE
[BUG] Biometric not compatible with New Android OS

### ISSUE THREAD

**Issue by adriosman** [PhilippC/keepass2android#2575]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

The Biometric feature is not compatible with the new Android OS. I have the Galaxy S24+ (Model SM-S926U).

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

REV1.0

**Comment by jo-37** [comment]
Same problem with Android 14 on Xperia 10 V. Though biometric unlock is enabled in settings, it is not offered for quick unlock.

**Comment by jookk** [comment]
samsung a53 and A35 android 14 biometrics quick unlock working fine, but Im on newest v1.11 version.

**Comment by jo-37** [comment]
I can confirm this: The issue is solved in v1.11.

**Comment by adriosman** [comment]
Yes, now working on Samsung Galaxy S24+ (Model SM-S926U) on v1.10-pre.
