### ISSUE TITLE
PCloud new Application folder

### ISSUE THREAD

**Issue by chrisu-mi** [PhilippC/keepass2android#2579]
Version: 1.10-pre

I have a new phone and installed your App...I have my database stored on PCloud, when I connect to pcloud a new application folder [Keepass2Android (Crocoapps)] is created altough there is already a "Keepass2Android" folder from my old phone created.

Why is there a new folder name??

On my old phone the same Keepass2Android App Version is installed.

Regards,
Christian

**Comment by alpenblauwtje** [comment]
@chrisu-mi this is an ordinary bug, see https://github.com/PhilippC/keepass2android/issues/2565

**Comment by alpenblauwtje** [comment]
@chrisu-mi this is an ordinary bug, see https://github.com/PhilippC/keepass2android/issues/2565

**Comment by chrisu-mi** [comment]
@alpenblauwtje Thanks, let's hope it will be resolved in the near future

**Comment by PhilippC** [comment]
closing this as duplicate of https://github.com/PhilippC/keepass2android/issues/2565
