### ISSUE TITLE
[FEAT] Avoid file manager remembering local key file location

### ISSUE THREAD

**Issue by tonyjonespdx** [PhilippC/keepass2android#2584]
Each time I reauth I have to select the keyfile location using system picker.
It seems the system is smart enough to prompt me with the previously used file.
For security reasons I'd prefer it didn't do that and the picker was opened at the FS root with no previous suggestions.

**Comment by scarlion1** [comment]
You can't ask the file manager to launch with `/sdcard` as the root or something?

If this file picker is disabled, it resorts back to some generic file picker which doesn't remember the last location.  However, it also doesn't have the permissions needed to access `/sdcard/Android/data` (I believe, where app storage is and where _Keepass2A_ has a folder where the keyfile is.  I gotta launch something like _X-plore_ first so I can update permissions on `/sdcard/Android/data` with other+read, then this basic file picker can reach the `data` dir and can finally unlock the database.  But, after a few hours the permissions on `/sdcard/Android/data` are reverted and gotta do the whole process again if I need _Keepass2A_ lol 😭
