### ISSUE TITLE
[FEAT] Add support for pronto drive to save key file.

### ISSUE THREAD

**Issue by recoder-lab** [PhilippC/keepass2android#2594]
Would make everything more secure if we can use pronto drive to store the key file.  Is there anything preventing this implementation?   Google and Dropbox are not ideal.

**Comment by PhilippC** [comment]
do you mean Proton or Pronto? I haven't heard of the latter?

**Comment by recoder-lab** [comment]
Yes Proton, sorry for the typoOn May 3, 2024 10:36 PM, PhilippC ***@***.***> wrote:
do you mean Proton or Pronto? I haven't heard of the latter?

**Comment by PhilippC** [comment]
duplicate of https://github.com/PhilippC/keepass2android/issues/2313
