### ISSUE TITLE
[BUG] Copy text from notes field, does not copy TAB correctly

### ISSUE THREAD

**Issue by Offerel** [PhilippC/keepass2android#2596]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

In entry, i have stored some useful information in the notes field with KeePass 2.55. If there is a TAB between 2 words, this tab is not displayed correctly in KP2A. Instead of displaying the TAB, the 2 words seems to be so close together, that it become one word. 

When i now copy this text via clipboard and paste it somewhere else in Android, the pasted string appears again as one word. But in reality there is still a TAB character between the words. This leads to numerous incorrect entries.

### Describe what you expected to happen:

In Wirklichkeit befindet sich aber immer noch ein TAB-Zeichen zwischen den Wörtern. Dies führt zu zahlreichen Fehleingaben.

### What version of Keepass2Android are you using?

1.11-r0

### Which version of Android are you on?

14

**Comment by Offerel** [comment]
Small corrected update: paste the string does sometimes paste the tab characters correctly. I have tried a text editor where the tab character was inserted correctly. Maybe this depends on the field type. 

Anyway,  it would be really helpful to have the string displayed correctly with a monospace font.

**Comment by PhilippC** [comment]
I don't think there is a definition on how "wide" a tab should be. I rely on Android to display it.
