### ISSUE TITLE
[BUG] Database does not open when working with remote disks Google Drive and Dropbox

### ISSUE THREAD

**Issue by f1h0** [PhilippC/keepass2android#2597]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

When trying to open a database located on remote Google Drive or Dropbox disks, the KeePass2Android app is unresponsive and displays "Working offline". The database does not open. Reinstalling the app did not help to solve the problem.

### Describe what you expected to happen:

It was expected that the database located on the remote disk would open correctly after authorization in the corresponding cloud service (Google Drive or Dropbox).

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

MUI 14

**Comment by f1h0** [comment]
addition to the current request currently, when I click on the "add key + file" button, I specify a location in Dropbox, but no action occurs when the "authorize app" window appears, preventing further steps. Perhaps Chrome is making some changes to the app authorization process. Need to check this somehow and fix it for the app to function.

**Comment by PhilippC** [comment]
if it says "Working offline", then you proably enabled this. In the options menu (three vertical dots) you selected "Use internal cache copy only". If you no click these dots again and select "Synchronize cache copy with source", it will go back to "online mode " again.
