### ISSUE TITLE
[FEAT] Support for Passkeys from KeepassXC

### ISSUE THREAD

**Issue by wYhyzByH** [PhilippC/keepass2android#2604]
Hi

I'd really like to use the new support for Passkeys in KeepassXC. But for that I need an Android app to support it as well.
I did not find this to be on the roadmap.

Is anyone working on that, yet?

Thanks for taking this into consideration.

KeepassXC announcement: https://keepassxc.org/blog/2024-03-10-2.7.7-released/

**Comment by Zocker1999NET** [comment]
Passkey support is already discussed in #2099

**Comment by PhilippC** [comment]
closing as duplicate of #2099
