### ISSUE TITLE
[QUESTION] Is the latest beta version compatible with KDBX 4/4.1?

### ISSUE THREAD

**Issue by santo998** [PhilippC/keepass2android#2609]
I'm using latest KeePass2Android beta version (1.11-r0).

However, KeePass 2.57 was released few days ago, and it uses KDBX 4/4.1 file format.

So, is the latest KeePass2Android beta version compatible with KDBX 4/4.1 file format?

**Comment by SoftwUser** [comment]
FWIW KeePass introduced KDBX 4.1 more than 3 years ago (Keepass 2.48).
KDBX 4 had been introduced with KeePass 2.35 in January 2017.

**Comment by santo998** [comment]
@SoftwUser ty so much!

**Comment by santo998** [comment]
@SoftwUser ty so much!
