### ISSUE TITLE
Auto-fill Is Triggered In Google Translate

### ISSUE THREAD

**Issue by gloomy-ghost** [PhilippC/keepass2android#262]
![img_20180221_180908_740](https://user-images.githubusercontent.com/13086421/36464025-56bf9f94-1732-11e8-8492-4bc2b3c2b83b.jpg)
Apparently this is not a place where we want to fill in passwords... How did the text field be detected as a password field?

**Comment by Mysticodex** [comment]
I have the same issue, but in a Reddit app (not web based) called Baconreader.

**Comment by alxkrylov** [comment]
Upvoting. The same issue in my GT.

**Comment by PhilippC** [comment]
fixed, duplicate of #303 (or vice versa)
