### ISSUE TITLE
[FEAT] Import key file to app storage

### ISSUE THREAD

**Issue by kantlivelong** [PhilippC/keepass2android#2628]
Rather than using the selected key file fron the path provided it would be neat if the app could import it into its app storage. On non-rooted systems this would prevent other apps from reading the key.

**Comment by sahriVoraus** [comment]
Isn't Settings > Database > Import key file to internal folder exactly what you are looking for?

**Comment by kantlivelong** [comment]
Well shoot you're right! Not sure how I missed that.
