### ISSUE TITLE
[FEAT] Autofill TOTP or (alternatively) Copy to Clipboard 

### ISSUE THREAD

**Issue by elberfeld** [PhilippC/keepass2android#2631]
Keepass2Android does a good job for AutoFilling Username an Password on logins. 
But if you use TOTP stored in Keepass as additional factor, this usability is broken up because you need to open the Database, search for the correct entry and copy the TOTP code there. 

If Autofill is not possible, an alternative aproch could be to copy the TOTP code to the clipboard after auto filling the login credentials. 
This is the way it is solved in the Bitwarden client. The function is optional and can be activited / deactivated. 
This was also mentioned in an older (closed) Issue: #1072 

One of the solutions would be a good improvement for the usability, especially when using Keepass2Android on a smartphone.

**Comment by sahriVoraus** [comment]
Just switch to the beta channel on google play or directly download the newest version https://github.com/PhilippC/keepass2android/releases/tag/v1.11-r0

**Comment by elberfeld** [comment]
I can confirm that this works with the v1.11-r0 version just as expected 🙂
