### ISSUE TITLE
app closes when you click  send debug log

### ISSUE THREAD

**Issue by papppyo** [PhilippC/keepass2android#264]
#### EXPECTED BEHAVIOR

I was thinking i could send debug log 

#### ACTUAL BEHAVIOR
Whenever i click to send Debug log app crashes immediately 

#### HOW TO REPRODUCE 

1.create new database 

2.input password or generate password by clicking those three horizontal dots under the MASTER  PASSWORD tab 

3.create new database 

4.click the the three vertical dots 

5.Goto settings 

6.Application settings

7.log-file for debugging 

8.Tick the box  "use log file "

9.finally click send debug log

*Keepass2android version1.04b

*Android 7.0 nougat

#### RECORDING OF BUG

https://youtu.be/zGqTGZpcFks

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@pappy/app-closes-when-click-send-debug-log">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by PhilippC** [comment]
did you click "send feedback"?

**Comment by lindhe** [comment]
Same for me, since the 31 of July. I've pressed "Send feedback".

**Comment by Karreg** [comment]
Confirmed. Activating the logs requires to restart the app before being able to send the feedback, or grab the logs...
