### ISSUE TITLE
Quelldatei und Zwischenspeicher

### ISSUE THREAD

**Issue by rojoma99** [PhilippC/keepass2android#2640]
**What version of Keepass2Android:
1.10-pre

Immer wenn ich Keepass öffne, erscheint kurz dieser unvollständige Satz....(  siehe Foto)
![signal-2024-07-19-13-32-08-212~2](https://github.com/user-attachments/assets/8fd152a2-344d-4055-8094-c3b1e83557e2)

und ich Frage mich, was er bedeuten könnte.

**Comment by WebworkrNet** [comment]
Die unvollständige Darstellung ist [suboptimal](#2587).

Meines Erachtens soll das heißen, dass Quell- und Zieldatei identisch sind (lokal und Cloud)  - also alles in Ordnung.

Sofern es Abweichungen gibt, wird eine Fehlermeldung angezeigt. Es kann beim der Synchronisation mit der Cloud potentiell zu Fehler kommen oder der gleiche Eintrag wurde vor Synchronisation von unterschiedlichen Geräten bearbeitet. Dann kommt es zu Versionskonflikten. Abhängig von den Einstellungen in der App kann damit unterschiedlichen verfahren werden.

**Comment by rojoma99** [comment]
@WebworkrNet Vielen Dank für die Antwort! Mir war nicht bewusst, dass die Datenbank auch in einer Cloud gespeichert wird. Ich sichere die Datei nach Änderungen zusätzlich, indem ich sie vom internen Speicher des Smartphones auf einen Ubuntu-Pc und eine externe Festplatte kopiere.
Inzwischen wird beim Öffnen auch ein anderer Dialog angezeigt: Remote- und Cachedateien sind identisch.
In welcher Cloud wird denn die Datenbank gespeichert? 
ps Danke an alle Experten, die sich hier im Forum beteiligen, eine Spende an den Entwickler ist sowieso schon längst fällig.

**Comment by WebworkrNet** [comment]
Die kbdx-Datenbank wird nur dann in der Cloud gespeichert, wenn Du zuvor ein Cloud-Konto hinterlegt hat. _Remote- und Cachedateien_ entspricht inhaltlich dem aber, was ich zuvor geschrieben habe. Die App hält zwei Versionen der Datenbank immer vor: Neben der Originalversion gibt es noch eine Cache-Version, die man bei Bedarf auch direkt öffnen kann. Der Entwickler bezeichnet diese Cache-Datei aber ausdrücklich <ins>nicht</ins> als Backup. Eine Cache-Datei kann man meiner Erinnerung nach nur lesen. Um sie editieren zu können, müsste man sie die Originaldatei mit der Cache-Version überschreiben.

**Comment by rojoma99** [comment]
Herzlichen Dank für die Erklärung.

**Comment by frech-tech** [comment]
Gib es eine Möglichkeit, dass das PopUp nicht vor der Tastatur erscheint? Oder lässt es sich komplett deaktivieren?
