### ISSUE TITLE
[QUESTION] Keyboard Swap Bug

### ISSUE THREAD

**Issue by inputuserhere** [PhilippC/keepass2android#2653]
Using Keepass2Android version: 1.10-pre

I don't know if this is a bug, but I'm on Android 14 and I installed the Keepass2Android keyboard swap plug-in. After granting permissions via add shell my phone has been acting weird. 

My default keyboard doesn't pop up at all when trying to type in any app, including Keepass2Android. When I try to edit any settings for keyboards, the app says settings are not responding, kill the app or wait.

How do I remove the permission and uninstall any trace of the keyboard swap plug-in.

Via add how can I confirm if I reset the permission for the keyboard plug-in?

**Comment by PhilippC** [comment]
On recent Android versions, it is strongly suggested to use Autofill instead of the built-in keyboard.
