### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by Enduro67** [PhilippC/keepass2android#2656]
**What version of Keepass2Android are you using?**
Please follow these steps to find your app version:
1. Click the **⁝** icon in the top right corner
2. Select **Settings**
3. Click **About**
4. Find the "Version" information and provide it here:1.11 r0

How can I Set the duration of the time quickunlock is possible?

**Comment by PhilippC** [comment]
there is no such setting. QuickUnlock remains active until you disable it or close the database. It is considered safe enough, no matter how long you don't use it.
