### ISSUE TITLE
[QUESTION] source file address moved

### ISSUE THREAD

**Issue by cicebear** [PhilippC/keepass2android#2658]
Version 1.10-pre
The IP-address of my local server has changed. Now Keepass for Android always shows "Quelldatei könnte nicht gespeichert werden: Failed to co...." when I save a changed entry.
How can I tell Keepass the new server (source file) address for my local (mobile) database? 
I must sync them because I also made changes to the source file on the new server via my PC.
Cicebear

**Comment by PhilippC** [comment]
select "Change database" on the password screen to see the list of recently used files, Tap the three vertical dots next to the filename and select "Edit".
