### ISSUE TITLE
[BUG] Time lock for clipboard does not work

### ISSUE THREAD

**Issue by RolandHilber** [PhilippC/keepass2android#2660]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

the copied password is always in the clipboard

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

12

**Comment by PhilippC** [comment]
the app should have warned you that clearing the clipboard doesn't work on all devices and isn't safe anyway. Don't use it for sensitive data.
