### ISSUE TITLE
[FEAT] add support for 2fa when opening a nextcloud-hosted database

### ISSUE THREAD

**Issue by rkenyon3** [PhilippC/keepass2android#2661]
I'm on version 1.10pre

Trying to access a database that is hosted on a remote server that's protected with multi-factor authentication doesn't seem to work. Currently, the app asks for an instance address, username, and password when trying to create the connection initially. 2fa is breaking this flow, since there's no opportunity that I'm aware of to enter a TOTP code.

At the moment the app produces an error message:
![Screenshot_20240908_133242_Keepass2Android](https://github.com/user-attachments/assets/22dc8a8a-d1e6-4757-b2fd-0ecebcac41ad)

If it's possible, it would be nice to have an option to mark the database as needing additional authentication and prompt for it when unlocking.

**Comment by PhilippC** [comment]
please use an app password, see https://github.com/PhilippC/keepass2android/issues/717#issuecomment-2346166083
