### ISSUE TITLE
[Subject: Assistance Needed with Database Access

### ISSUE THREAD

**Issue by Natuzza81** [PhilippC/keepass2android#2662]
*Subject: Assistance Needed with Database Access

Dear KeePass2Android Support Team,

I hope this message finds you well. Unfortunately, my phone was damaged, and I had to reset it to factory settings. I am now in a bit of a predicament as I cannot remember if I saved my database and, if so, where it might be stored.

However, I do remember my password. Is there any way for me to regain access to my password database? I would greatly appreciate any assistance you can provide.

Thank you for your help!

Best regards

Natascia Perla

**Comment by PhilippC** [comment]
you do need to have the database file: if you stored it on Google Drive/Dropbox/any other cloud, you can open it from there again. If it was stored locally, then I don't see an option to recover it. Sorry for not being able to help more.

See https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md for explanations.

**Comment by Natuzza81** [comment]
Hi,

Thanks for your answer.

Greetings

PhilippC ***@***.***> schrieb am Mo., 23. Sept. 2024, 08:46:
