### ISSUE TITLE
Disable "Enable Autofill" prompt

### ISSUE THREAD

**Issue by gandalf013** [PhilippC/keepass2android#267]
I have Android 8 and when I open the app, I get a prompt on the bottom:

Keepass2Android supports Android's Autofill feature but it looks like you haven't enabled it yet.

[ENABLE AUTOFILL] [SHOW AUTOFILL HELP]

I actually have enabled Android's autofill, but I use a different app for autofill feature.  I still want Keepass2Android for password management, so that banner on the bottom is distracting.  It would be nice to get rid of that.

**Comment by PhilippC** [comment]
please enable it once, go back to Kp2a (so that it see it's enabled), then disable it again in the system settings. The notification will not appear again.

**Comment by gandalf013** [comment]
I tried that, and it worked.  Thanks!  It's a little unintuitive, but not a big problem.

**Comment by coryallegory** [comment]
Even if you choose an autofill option, the prompt doesn't disappear. It should dismiss as soon as you select something on it in my opinion, or simply have a dismiss button.

**Comment by davidmaxwaterman** [comment]
IMO, this should be fixed properly. A 'normal' user isn't going to bother searching for this github issue to find the fix...even I've 'put up with it' for quite a while before bothering to look.

**Comment by PhilippC** [comment]
please see https://play.google.com/apps/testing/keepass2android.keepass2android, there's already a "do not show again" button.

**Comment by davidmaxwaterman** [comment]
I still get three passwords being offered when I first try to log into the app, which, along with the keyboard appearing, make it impossible to see the field I'm supposed to be entering the password into - which, to a user, it seems like a security concern. Is that some different problem?
