### ISSUE TITLE
[QUESTION] What data is encrypted?

### ISSUE THREAD

**Issue by Wm-A-Weezl** [PhilippC/keepass2android#2680]
Version 1.10-pre
Of the content I type into KeePass2Android, what is encrypted? Only the passwords, or is everything encrypted? I would prefer everything. I often put PINs or answers to security questions in KP2A's Notes section. I hope they are not stored as plain text.  
If Notes are not encrypted, can you suggest a good way to prevent their disclosure?

**Comment by PhilippC** [comment]
everything is first serialized in XML (in memory) and that stream is then encrypted. So yes, everything is encrypted.
