### ISSUE TITLE
[FEAT] Donate via Google Play

### ISSUE THREAD

**Issue by Suncatcher** [PhilippC/keepass2android#2687]
I frequently have some extra $ on my Google Play balance which I would willingly donate to your wonderful app. However now only debit/credit cards are supported and PayPal.
Please implement paying with Play balance like in-app purchases 
https://developer.android.com/google/play/billing/integrate
This way you will be able to receive a greater share of donates.

**Comment by PhilippC** [comment]
this is possible with https://play.google.com/apps/testing/com.keepass2android.android.donate (it's safe to use even though it's in "beta")

**Comment by Suncatcher** [comment]
how to run it? I don't see anything in menu despite I'm a beta tester. What is the beta version required?

**Comment by PhilippC** [comment]
after joining, you should be able to install and run the app (it is separate from the KP2A app), aren't you?

**Comment by Suncatcher** [comment]
ok, it worked. I successfully donated yesterday.
I propose to make a free form entry, not a small beer/big beer. I often have a fixed amount on GP balance which doesn't fit your beer limits. Flexibility is always better chance of donate.
I hope it will be built-in into the main app, I don't want to have an extra app on my phone, lol
