### ISSUE TITLE
[BUG] Synchronization through gdrive is inconsistent

### ISSUE THREAD

**Issue by kyounes** [PhilippC/keepass2android#2694]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

After making changes to a shared gdrive database on the desktop app, often I have to force close the Android app and re-open it to force it to load the changed database on gdrive. I did check the database file timestamp on Android gdrive to make sure it is the updated version, so this is not a gdrive issue.

Even choosing "Synchronize Database" in the menu doesn't resolve this, unless I close and reload the app. Is there a setting that I am misconfiguring perhaps? I have all file handling options checked in Settings (except "always merge on conflict").

Thank you!

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

14, build AP2A.240905.003 on Pixel 7

**Comment by PhilippC** [comment]
did you open the file through the built-in GDrive support or through the system file picker? You can tell this from the "url" identifier in the filename: does it start with gdrive:// or with content://?

**Comment by kyounes** [comment]
It starts with gdrive. Specifically: gdrive://<my gmail address>/<filename>.kdbx

**Comment by kyounes** [comment]
It looks like it's gdrive://{my gmail address}/{filename}.kdbx

**Comment by kyounes** [comment]
Correction (and more details). My Pixel 7 has the gdrive:// path and the KP2A app seems to work fine there.

My wife's phone uses the content:// type path (because the kdbx file is shared from my account to hers) and her K2PA app does not load the changes consistently.

Thanks again...
