### ISSUE TITLE
[BUG] Yubikey / S24 / Password + Challange Response - "an error has occured. Please unplug your Yubikey"

### ISSUE THREAD

**Issue by danny70437** [PhilippC/keepass2android#2696]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Hi,

i use my old Samsung S9 with keepass2android & ykdroid for a long time.
Now, i updated to an S24 (Android 14) and configured the same setup.

If i try to "Load OTP Auxiliary File",  a dialog "Please attache or swipe your YbiKey now" appears. Fine.
Adding my Yubikey my USB-C opens a new dialog "Allow ykDroid to access Yubikesy OTP+FIDO+CCID?" -> entering "OK". fine.

Now a new dialog "Please press button on your Yubikey" - ok, so I press the button an an error occurs: "An error has occurred. Please unplug your Youbikey". I think the error occurs, because the system does not recognize the pressed button, so it runs in a time out. But not sure.

I tried also Keepass2Android 1.11-r0 - same problem.

The same works on my S9, but not on the new S24. Is there any idea to fix this?

Best regards,
Daniel

BTW - Yubikey Authenticator works fine with S24. Also, i uninstall "Yubikey Authenticator" - but this did not change the behaviour.

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

14

**Comment by aubreyz** [comment]
This is definitely a timing issue (as you suspected) which persists into the most recent version - see https://github.com/PhilippC/keepass2android/issues/3169
