### ISSUE TITLE
Edit Connection When Password Changes

### ISSUE THREAD

**Issue by EsRa13** [PhilippC/keepass2android#27]
I access my kdbx via https (company cloud).
For we have to change our company password from time to time I have to update my connection in keepass2android, too.
I would appreciate a feature to edit an existing connection i.e. change the used
password. For now I have to create a complete new connection - which uses a
very long URL with many occasions for typing errors...

**Comment by Sanaki** [comment]
I'm not sure I understand. It sounds like you're saying you can't edit entries, but there's a button on each entry's page allowing you to edit it.

**Comment by EsRa13** [comment]
I'm not talking about entries, I'm talking about the database itselves. This kdbx file is stored in a cloud. If the password for the cloud changes there is no way to edit the connection. You have to create a totally new connection with the URL and the new password.

**Comment by EsRa13** [comment]
I'm not talking about entries, I'm talking about the database itselves. This kdbx file is stored in a cloud. If the password for the cloud changes there is no way to edit the connection. You have to create a totally new connection with the URL and the new password.

**Comment by dvictori** [comment]
I also have this issue. I have my kdbx file stored in a OwnCloud WebDav server. Unfortunatelly, from time to time, we have to change our OwnCloud password. Thus I have to enter the URL and create a new connection.
