### ISSUE TITLE
[BUG] clipboard purge does not work on a samsung A15

### ISSUE THREAD

**Issue by pelafoin** [PhilippC/keepass2android#2702]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

the clipboard purge does not work on a samsung A15. It worked on my old phone. I am on version 1.11-r0. Whatever purge time I choose it does not work.

### What version of Keepass2Android are you using?

1.11-r0

### Which version of Android are you on?

Android 14

**Comment by PhilippC** [comment]
Android clipboard is insecure and cannot be cleared realiably. The app cannot "force" any clipboard manager to forget something if they don't want to and warns about this. I think that's all I can do.
