### ISSUE TITLE
[BUG] sync does not work (nextcloud)

### ISSUE THREAD

**Issue by kalastaaa** [PhilippC/keepass2android#2707]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

when trying to sync comes this message:
' Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.existsOnDevice()' on a null object reference '

### Describe what you expected to happen:

I expect to sync the database with the one in the cloud (nextcloud on woelkli)

### What version of Keepass2Android are you using?

1.11-r0

### Which version of Android are you on?

13 /e/os 2.4.1

**Comment by kalastaaa** [comment]
checked differences by view, synced by hand, and opened it again from cloud ...  running ...

**Comment by PhilippC** [comment]
with your comment you mean it is now working? 

If not: the message reads a bit like you are opening through the owncloud app, is this correct? I strongly suggest to use the built-in owncloud support (e.g. select Open database - Owncloud).

**Comment by PhilippC** [comment]
I'm closing this because I suspect it's no longer needed. Please reopen if I'm wrong.

**Comment by rostmodern** [comment]
Encountering the same error message with K2A version 1.12 r5.
Android 15.
Nextcloud App Version 3.31.4 (not sure if related: recently updated, used to work for at least a year through various of their app versions )


Any updates or workarounds? 

Thank you so much!

**Comment by PhilippC** [comment]
@rostmodern  please read https://github.com/PhilippC/keepass2android/wiki/Keepass2Android-file-handling and switch to the built-in webdav implementation

**Comment by rostmodern** [comment]
thank you for your quick reply. 
I checked the docu before and refrained from using the WebDav implementation because it states that "transactional write not implemented yet". Is this still the case?
I fear that data might get lost in the process.
