### ISSUE TITLE
Locked out now.

### ISSUE THREAD

**Issue by CdnRookie-Eh** [PhilippC/keepass2android#2715]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I had changed my password and the theme to dark.
I do remember the password,  but the program says it is wrong.
After changing the theme to dark, the fingerprint option no longer works.
I tried reloading the local backup, but I still have the same problem.
I'm stuck.

### Describe what you expected to happen:

I expected the fingerprint option to continue to work.
Need a forgot PW option.

### What version of Keepass2Android are you using?

1.11

### Which version of Android are you on?

14

**Comment by PhilippC** [comment]
can you try to select "Change database" on the password screen, then enable "Show local backups" and try to open the local backup of the database?

**Comment by CdnRookie-Eh** [comment]
I did try that, still no luck.
But what I did try was my old password, and luckly, it worked.
It would still be nice to have a "Forgot PW" option.
Thanks for your time.

**Comment by PhilippC** [comment]
please read [the docs](https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md) to get a rough understanding of how KP2A works and why such an option cannot be implemented (without sacrificing security).
