### ISSUE TITLE
[FEAT] Sort or search option for entries having TOTP in mobile app

### ISSUE THREAD

**Issue by hajimammada** [PhilippC/keepass2android#2724]
Desktop have such sorting feature but there is no sort type for entries having TOTP

**Comment by Yuho1985** [comment]
@hajimammada

**Comment by Yuho1985** [comment]
> @hajimammada

**Comment by sahriVoraus** [comment]
try out the newest release https://github.com/PhilippC/keepass2android/releases/tag/v1.11-r0 or switch to the beta channel on the play store. 
In this version there is a dedicated button to show all TOTP entries

**Comment by PhilippC** [comment]
I agree. 1.11 solves this.
