### ISSUE TITLE
[FEAT] Biometric unlock with face or pin

### ISSUE THREAD

**Issue by SimoneAvogadro** [PhilippC/keepass2android#2726]
I'm using a Samsung S22 Ultra and I've some issues with the fingerprint scanner.
Most apps will allow me to access my data by means of face recognition instead of fingerprint.
I suggest to add an option to select which auth methods to accept (e.g. fingerprint, face etc...)

**Comment by ZeWaka** [comment]
Via Google's biometrics stuff, it treats them as the same. Perhaps this is a Samsung-only issue due to their implementation of facial biometrics?

**Comment by PhilippC** [comment]
Google distinguishes between weak and strong biometrics. KP2A requires strong biometrics because it encrpyts data in safe storage (protected with biometrics). Other apps might not need that and thus can use weak biometrics. I cannot change this.

**Comment by SimoneAvogadro** [comment]
Thanks useful explanation but really scary: there are security apps which allow this (=weak auth!)
Thnaks for the good work
