### ISSUE TITLE
[BUG] When phone is offline databse it not saved to cloud, nor when online again. And Internal viewer dont work

### ISSUE THREAD

**Issue by NolanNolan** [PhilippC/keepass2android#2728]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Hi
when phone is offline and i make changes to the file, the file  is not uploaded to cloud storage, not even when the phone is online again. This may lead to conflitcs of versions. Would you consider to make an upload as soon as the phone is online again or is this a bug? Keepassdx uploads when online again automatically.

It takee very long time to load file, keepassdx loads much faster. Is there something to do about this ?
i have a key incl jpg files but internal viewer does not show anything.

### Describe what you expected to happen:

I would say the database should upload from the phone to the cloud storage as soon as the phone is onine again

Further i expected the internal viewer ro work

### What version of Keepass2Android are you using?

1.11-r0

### Which version of Android are you on?

14

**Comment by PhilippC** [comment]
please separate this into multiple issues.
 * KP2A doesn't watch online state. It syncs when you save or load again or click the Synchronize database menu option
 * Please provide an example file which are faster with KeepassDX and tell where you store them.
 * Please provide an example file regarding internal viewer or provide screenshots or other useful info

**Comment by NolanNolan** [comment]
Hi

I cant send an example file as it contains all my data.


Hilsen Jørn

Fra: PhilippC ***@***.***>
Sendt: 31. december 2024 11:56
Til: PhilippC/keepass2android ***@***.***>
Cc: NolanNolan ***@***.***>; Author ***@***.***>
Emne: Re: [PhilippC/keepass2android] [BUG] When phone is offline databse it not saved to cloud, nor when online again. And Internal viewer dont work (Issue #2728)


please separate this into multiple issues.

  *   KP2A doesn't watch online state. It syncs when you save or load again or click the Synchronize database menu option
  *   Please provide an example file which are faster with KeepassDX and tell where you store them.
  *   Please provide an example file regarding internal viewer or provide screenshots or other useful info

-

**Comment by PhilippC** [comment]
with example file I meant a newly created file without personal data just for demonstration/testing purposes

**Comment by NolanNolan** [comment]
Hi Phillip

Thanks, I have used your app for many years but now just switched to Keepass DX Pro because it´s much faster

Will get back to  your app if it gets more speedy

Thanks

Hilsen Jørn

Fra: PhilippC ***@***.***>
Sendt: 7. januar 2025 07:00
Til: PhilippC/keepass2android ***@***.***>
Cc: NolanNolan ***@***.***>; Author ***@***.***>
Emne: Re: [PhilippC/keepass2android] [BUG] When phone is offline databse it not saved to cloud, nor when online again. And Internal viewer dont work (Issue #2728)


with example file I meant a newly created file without personal data just for demonstration/testing purposes

-
