### ISSUE TITLE
Long password (protected field)doesn't display or wrap, or even allow scrubbing/scrolling to left or right.  Even in landscape.

### ISSUE THREAD

**Issue by xgpt** [PhilippC/keepass2android#275]
This bug is very frustrating. I feel as though it is a very negative UI/UX bug that should be remedied as a priority. It is making me actively discouraged from using longer passwords that j have to occasionally view, or to use the system clipboard, which I believe to be a security risk. 
![screenshot_20180226-164301](https://user-images.githubusercontent.com/1377974/36697223-73d0a41c-1b14-11e8-9db1-2706aa4b194a.png)

**Comment by xgpt** [comment]
This issue has been opened and also closed, I am running the most recent version of the app, despite a link to a commit with a comment of fixed with a description of this issue. Did this commit fixing the issue not make it out into the latest release?

**Comment by PhilippC** [comment]
what is "most recent version"? (settings -> about)

**Comment by xgpt** [comment]
1.04b

**Comment by PhilippC** [comment]
please switch to beta to get a fix for this issue (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by PhilippC** [comment]
duplicate of #230

**Comment by xgpt** [comment]
Thanks!
