### ISSUE TITLE
Scan QR code to (partly) fill in database password for unlocking

### ISSUE THREAD

**Issue by jvandenbroek** [PhilippC/keepass2android#277]
A nice feature would be to allow scanning a QR code from within the app to fill in your password to unlock the DB. Even better if it wouldn't auto submit it, so you could eg. enter the last few chars yourself for added security. This way I no longer need to use my OTG USB and my yubikey every time I need to unlock it (unfortunately the app gets killed regularly by Android, so can't always use quick unlock). Thanks!

**Comment by PhilippC** [comment]
this should be implemented as an external app. Keepass2Android can be started with a pre-filled password already. I won't implement this in the app itself to avoid adding permissions.

**Comment by jvandenbroek** [comment]
Clear, thanks for responding. Pre-filled password seems a reasonable alternative, yet have to find this feature! ;)
