### ISSUE TITLE
If entry isn't "standard", username can't be chosen

### ISSUE THREAD

**Issue by Indubius** [PhilippC/keepass2android#28]
As long as entries are build as a standard entry, the keyboard fills in the username correctly. As soon as another template is chosen to create an entry, there is no username and the keyboard doesn't recognise the email address or whatever.
I'd suggest to allow the keyboard to grab another entry for the predefined button "user" on the small keyboard in this case. Probably the best idea is to set the top entry as a replacement. Another solution would be to allow the keyboard to grab a self-created field called "user" e.g.

**Comment by PhilippC** [comment]
are you aware that you can press the KP2A-symbol-button and then select any
field?

--------------------
:-) :-) :-) you liked my reply? Please consider making a donation at
http://philipp.crocoll.net/donate.php. Thanks! :-) :-) :-)

2017-10-06 9:45 GMT+02:00 Indubius <notifications@github.com>:

**Comment by Indubius** [comment]
Hallo Philipp, 

danke für Deine Antwort!
Es stimmt fast, dass jedes Feld ausgewählt werden kann. Nehmen wir den Mustereintrag "email", welcher für mich auch Stein des Anstoßes war. I.d.R. bezeichnet der Eintrag "Name" hier die Emailadresse. Genau dieser Eintrag kann aber nicht über den keepass Button ausgewählt werden. Darüber hinaus ist die Emailadresse beim login in einem emailclient im Normalfall auch der Benutzer, weshalb sich eine entsprechende Belegung anbieten würde.
Ähnlich verhält es sich mit anderen Vorlagen. 

Ist es denn schwierig das "top-level" - Feld zur die Taste "Benutzer" zu Schlüsseln?

Beste Grüße
Sebastian 

--
Mit freundlichem Gruß
kind regards 

S. Gruber


-------- Original-Nachricht --------
Von: PhilippC <notifications@github.com>
Gesendet: Sat Oct 07 08:24:38 GMT+02:00 2017
An: PhilippC/keepass2android <keepass2android@noreply.github.com>
CC: Indubius <Sebastian_grubaer@web.de>, Author <author@noreply.github.com>
Betreff: Re: [PhilippC/keepass2android] If entry isn't "standard", username can't be chosen (#28)

are you aware that you can press the KP2A-symbol-button and then select any
field?

--------------------
:-) :-) :-) you liked my reply? Please consider making a donation at
http://philipp.crocoll.net/donate.php. Thanks! :-) :-) :-)

2017-10-06 9:45 GMT+02:00 Indubius <notifications@github.com>:

**Comment by PhilippC** [comment]
On my (German) phone the template-field for the mail address is called "E-Mail-Adresse" and pressing the KP2A button next to the password button on the keyboard shows a list including an "E-Mail-Adresse" entry which I can pick to enter the mail address.
You might consider changing the template to use the standard username field instead of a custom field which would let you use the username button on the keyboard. But I don't see a simple way to assign a deliberate field to the username button.

**Comment by Indubius** [comment]
Apologies, I must have overseen the entry "email addresse".

-- 
Mit freundlichem Gruß
kind regards

S. Gruber

PhilippC <notifications@github.com> schrieb am 09.10.2017:
>On my (German) phone the template-field for the mail address is called
>"E-Mail-Adresse" and pressing the KP2A button next to the password
>button on the keyboard shows a list including an "E-Mail-Adresse" entry
>which I can pick to enter the mail address.
>You might consider changing the template to use the standard username
>field instead of a custom field which would let you use the username
>button on the keyboard. But I don't see a simple way to assign a
>deliberate field to the username button.
