### ISSUE TITLE
Keepass2Android and KP2A AutoFillPlugin crashing

### ISSUE THREAD

**Issue by psycholyzern** [PhilippC/keepass2android#281]
Android: Oreo 8.0.0
Phone: OnePlus 5T

Sometimes Keepas2Android keep crashing when I'm trying to autofill a form. I have sent a report, but I'm gonna attach stack trace log anyway.

![](https://i.imgur.com/8TpSW7G.jpg)
![](https://i.imgur.com/Zju6Vwd.jpg)

Also KP2A AutoFillPlugin crashing randomly. When it crashed, there is no another option other than hitting stop the app but sometimes the option was "Open app again". I had to open Accesibility and turn off then turn on the swith to make it runs again. Screenshot below taken when I was readin instant article in Facebook.

![](https://i.imgur.com/DcdPg6B.jpg)

**Comment by kifujin** [comment]
Getting the same thing on my Note 8 all the time. On android 7.1.1

**Comment by mcarver2000** [comment]
I'm seeing this as well. It even happens when there are no username/password fields.Moto G5+ Android 7.0

**Comment by bspans** [comment]
Mine also keeps creasing. Android 8.1. One plus one Onyx

**Comment by bspans** [comment]
Also tested on Sony z3 c with android 7.1. Same problem.

**Comment by psycholyzern** [comment]
Somehow since hours ago, I couldnt fill any login form. Had to use KP2A keyboard. Also I am using latest Chrome Beta if that matterd

**Comment by N1cotin** [comment]
Same problem for me, but it works if I open keepass and login first and then use the autofill.

**Comment by Karreg** [comment]
Not sure if it's related, since I use Oreo autofil and not the AutoFill plugin, but when I use Autofill, the apps crashes too.
It seems to be random, because with the same version I had no issues until yesterday. But yesterday I had it on 2 differents devices with the same behavior.

Tested on 
- OnePlus 3T, Android 8.0, OxygenOS 5.0.1
- Galaxy Tab S2, Android 8.1, LineageOS 15.1

**Comment by kifujin** [comment]
Looks like [this](/PhilippC/kp2a_accservice_autofill/issues/4) is the proper issue for this. Over at the project for the autofill plugin.

**Comment by psycholyzern** [comment]
Right now KP2A autofill is completely unusable on my side. Any form that I tried to fill will crash KP2A after I enter pin/password to unlock the database. Had to use KP2A keyboard. 

Thanks @kifujin. Since PhilippC replied to the other issue thread, I think so too. There is a lot issues and I scrolled some before opening this one. Maybe I missed it.

**Comment by kifujin** [comment]
The autofill plugin has a [separate project](/PhilippC/kp2a_accservice_autofill/) on github, so you'd've had to look there.

**Comment by psycholyzern** [comment]
@kifujin oh I didn't really paying attention to the link, thought it was on the same repo. Since I have crashes on main app, also on the autofill plugin, I decided to open an issue here. I'll close this issue when this problem solved even discussions were on the other issue thread. Thanks

**Comment by mileder** [comment]
+1

**Comment by psycholyzern** [comment]
Seems to be fixed. I'll close this for now.
Thanks.
