### ISSUE TITLE
Why local files remembered by descriptor instead of name?

### ISSUE THREAD

**Issue by shleym2000** [PhilippC/keepass2android#282]
I do not want to make changes to a master copy of my keepass file.

That is why I open local copy of the keepass file with this application and I keep this lical copy current with another cloud synchronizing app.

Every time after local copy gets updated, this app complains that it list access to it and goes for cached context.

Why app can not try to reopen keepass file by its name?
File is there. Same name and same location.

**Comment by PhilippC** [comment]
Android is becoming more and more strict on this, no way to do so.

**Comment by shleym2000** [comment]
I am puzzled by your reply.

How can Android be strict on openning file by its name? It is the basic service by any operational system.

If you keep a file descriptor, trying to access it and fail for any reason ( file was overwritten by another app), 
open file by its name and refresh your descriptor.

If you would fail to open file by name due to lack of permissions, so be it. Then you would indeed throw the error.

But most likely you would succeed to reopen the file.
