### ISSUE TITLE
WebDAV authentication results in 401 error

### ISSUE THREAD

**Issue by ghost** [PhilippC/keepass2android#286]
I'm synching KeePass2 with WebDAV (https) and want to connect keepass2android as well. The app asks once for the database file which results in an 401 error.

Any idea what the problem can be? It's a Caddy WebDAV Server.

**Comment by sebastianbauer** [comment]
I found other apps that use OkHttp which have the same problem. :-( So it's not keepass2android specific. Maybe you still have a hint what could be wrong with the WebDAV server.

**Comment by PhilippC** [comment]
Even though this one was first, it seems to be covered by #478 or #747. Closing this to reduce the number of places to discuss these issues.
