### ISSUE TITLE
Master key and encryption

### ISSUE THREAD

**Issue by mydexterid** [PhilippC/keepass2android#287]
Hi!

This is more or less just a clarifying question.

If I'm getting this right the master key is stored as a ProtectedString:
https://github.com/PhilippC/keepass2android/blob/17cbb754a6d46cc3dfae3399804d796014b3cddf/src/KeePassLib2Android/Keys/KcpPassword.cs#L77
which itself is encrypted, but the key for this encryption is stored in memory as clear text:
https://github.com/PhilippC/keepass2android/blob/master/src/KeePassLib2Android/Security/ProtectedBinary.cs#L278
on Windows there's some protectedmemory handling which I'm not familiar with:
https://github.com/PhilippC/keepass2android/blob/master/src/KeePassLib2Android/Security/ProtectedBinary.cs#L116
but that doesn't apply to Android.
Am I right?

I was looking at this because stumbled upon a keepass plugin which does quickunlock but it actually encrypts the master key with the user provided pin:
https://github.com/JanisEst/KeePassQuickUnlock/commit/2cd9c806e34d6e2995524c0b5296ff0702a7d82b
and the user can also choose between a part of the master password or an entry in the database itself for the quick unlock pw.

**Comment by PhilippC** [comment]
There is no memory encryption on Android, so you need to trust the OS anyway that it protects the app memory from other apps. QuickUnlock is implemented in a way that the whole database is still open (and thus in memory), it's more a "user interface level lock". But as said above, if you ever open your database on Android (i.e. decrypt it to memory), you need to trust this is safe. And if you trust this, QuickUnlock is as safe.
