### ISSUE TITLE
Searching password (Oreo Autofill, KP2A keyboard and URL sharing) is crashing Keepass 1.05-pre1

### ISSUE THREAD

**Issue by Karreg** [PhilippC/keepass2android#289]
Hello,

After commenting #281 I create a new issue since this is not related to autofill plugin, but oreo autofill.

Since 2 days ago (I don't know since when exactly), Keepass is crashing when using autofill, but also URL sharing and KP2A search.

It happens on 2 differents devices: 
* OnePlus 3T, Android 8.0, OxygenOS 5.0.1
* Galaxy Tab S2, Android 8.1, LineageOS 15.1

I tried on Facebook app, and it happens whatever the scenario.
First I go to facebook, and click the Fill with Keepass2Android. Then:
* database is locked, and I quick unlock it with fingerprint
* Keepass2Android is closed and I unlock it with fingerprint
* Keepass2Android is closed by force, and same scenario as previous one
* Keepass2Android is open, database is open, then I try to autofill
Then Keepass2Android crashes. I have sent a comment, not sure it will reach you. I can't get a screenshot either, it's blocked. Either way, it would just show the popup saying the app as crashed.

Is there anything else I can do to help analyzing this issue? I don't have root, so I don't have access to logs. But I can try different scenarii.

The same happens when I search the credentials through KP2A keyboard. 

Also when sharing URL from Brave or Chrome.

The only scenario that works now is:

1.  Open KP2A
2. Select the entry
3. Go to app
4. Fill with keyboard

Maybe the search is broken? It would explain all issues.

Full log reproduced here (from @auanasgheps)

```
03-14 11:04:46.838 D/KP2A    (23825): ShareUrlResults.OnCreate
03-14 11:04:46.839 D/KP2A    (23825): ShareUrlResults:apptask=
03-14 11:04:46.843 D/KP2A    (23825): Creating GBA
03-14 11:04:46.844 D/KP2A    (23825): Loaded task keepass2android.SearchUrlTask
03-14 11:04:46.902 I/MonoDroid(23825): UNHANDLED EXCEPTION:
03-14 11:04:46.930 I/MonoDroid(23825): System.NullReferenceException: Object reference not set to an instance of an object
03-14 11:04:46.930 I/MonoDroid(23825):   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.930 I/MonoDroid(23825):   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.930 I/MonoDroid(23825):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0 
03-14 11:04:46.930 I/MonoDroid(23825):   at (wrapper dynamic-method) System.Object:f71f5726-2419-4fc1-a86e-6bbc29f8b994 (intptr,intptr,intptr)
03-14 11:04:46.935 D/KP2A    (23825): System.NullReferenceException: Object reference not set to an instance of an object
03-14 11:04:46.935 D/KP2A    (23825):   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.935 D/KP2A    (23825):   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.935 D/KP2A    (23825):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0 
03-14 11:04:46.935 D/KP2A    (23825):   at (wrapper dynamic-method) System.Object:f71f5726-2419-4fc1-a86e-6bbc29f8b994 (intptr,intptr,intptr)
03-14 11:04:46.944 W/zygote  (23825): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
03-14 11:04:46.948 D/AndroidRuntime(23825): Shutting down VM
03-14 11:04:46.952 E/AndroidRuntime(23825): FATAL EXCEPTION: main
03-14 11:04:46.952 E/AndroidRuntime(23825): Process: keepass2android.keepass2android, PID: 23825
03-14 11:04:46.952 E/AndroidRuntime(23825): android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
03-14 11:04:46.952 E/AndroidRuntime(23825):   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.952 E/AndroidRuntime(23825):   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.952 E/AndroidRuntime(23825):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0 
03-14 11:04:46.952 E/AndroidRuntime(23825):   at (wrapper dynamic-method) System.Object:f71f5726-2419-4fc1-a86e-6bbc29f8b994 (intptr,intptr,intptr)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at md5f0702f468598c68ce18586502249fb40.ShareUrlResults.n_onCreate(Native Method)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at md5f0702f468598c68ce18586502249fb40.ShareUrlResults.onCreate(ShareUrlResults.java:31)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.Activity.performCreate(Activity.java:6999)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.Activity.performCreate(Activity.java:6990)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.os.Looper.loop(Looper.java:164)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at java.lang.reflect.Method.invoke(Native Method)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-14 11:04:46.959 W/ActivityManager(911):   Force finishing activity keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.ShareUrlResults
03-14 11:04:46.963 W/ActivityManager(911):   Force finishing activity keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.PasswordActivity
03-14 11:04:46.968 I/ActivityManager(911): Showing crash dialog for package keepass2android.keepass2android u0
```

**Comment by mileder** [comment]
+1 same issue android oreo galaxy s8 edge+
PLEASE FIX IT!

**Comment by mcarver2000** [comment]
Experiencing same on Pixel C Android 8.1

If I start the process with autofill, KP2A crashes after I input password. Starting KP2A prior to triggering autofill still causes the app to crash. I suspect it's the search process. If I open KP2A first and select the entry, it doesn't crash. If I try to use autofill again in another app (with KP2A still open and not having selected matching entry), KP2A promptly crashes.

**Comment by mileder** [comment]
i think the problem is while k2a tries to read the calling application name for matching the entry. Because there is no crash if i use "select entry"...
hope that helps to fix it

**Comment by Karreg** [comment]
@mileder try to share an URL and you should see the same issue. Probably related to search in general.. :)

**Comment by mileder** [comment]
here is the complete stack trace of crash:

`D KP2A    : Loaded task keepass2android.SearchUrlTask
I MonoDroid:   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0
I MonoDroid:   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0
D KP2A    : System.NullReferenceException: Object reference not set to an instance of an object
D KP2A    :   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0
D KP2A    :   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0
D KP2A    :   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0
D KP2A    :   at (wrapper dynamic-method) System.Object:d2c26434-ea12-4d25-bb79-acb4245fdb02 (intptr,intptr,intptr)
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: keepass2android.keepass2android, PID: 20238
E AndroidRuntime: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
E AndroidRuntime:   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0
E AndroidRuntime:   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0
E AndroidRuntime:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0
E AndroidRuntime:   at (wrapper dynamic-method) System.Object:d2c26434-ea12-4d25-bb79-acb4245fdb02 (intptr,intptr,intptr)
E AndroidRuntime:        at md5f0702f468598c68ce18586502249fb40.ShareUrlResults.n_onCreate(Native Method)
E AndroidRuntime:        at md5f0702f468598c68ce18586502249fb40.ShareUrlResults.onCreate(ShareUrlResults.java:31)
E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7174)
E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6938)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
`

**Comment by adsduarte** [comment]
Same issue here, only works if open kp2a, select entry and then use kp2a keyboard to fill the password.
If i don't select the entry before use keyboard to autofill, kp2a always crashes

**Comment by Karreg** [comment]
I have the same log for all issues.
I have tested to log in Facebook app.
1st occurrence through Autofill
2nd through KP2A keyboard search
3rd from Brave through URL sharing.

It's the same activity, so it makes sense..


`14/03/2018 14:34:33:644 -- ShareUrlResults.OnCreate
14/03/2018 14:34:33:646 -- ShareUrlResults:apptask=
14/03/2018 14:34:33:651 -- Loaded task keepass2android.SearchUrlTask
14/03/2018 14:34:33:724 -- System.NullReferenceException: Object reference not set to an instance of an object
at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0
at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0
at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0
at (wrapper dynamic-method) System.Object:6669961e-9263-4ea7-9681-20c4a0a3b0b5 (intptr,intptr,intptr)`

`14/03/2018 14:35:00:349 -- ShareUrlResults.OnCreate
14/03/2018 14:35:00:350 -- ShareUrlResults:apptask=
14/03/2018 14:35:00:357 -- Loaded task keepass2android.SearchUrlTask
14/03/2018 14:35:00:466 -- System.NullReferenceException: Object reference not set to an instance of an object
at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0
at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0
at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0
at (wrapper dynamic-method) System.Object:c79fe328-13f1-41af-b3b2-9d8beca4f736 (intptr,intptr,intptr)`

`14/03/2018 14:35:54:496 -- ShareUrlResults.OnCreate
14/03/2018 14:35:54:497 -- ShareUrlResults:apptask=
14/03/2018 14:35:54:504 -- Loaded task keepass2android.SearchUrlTask
14/03/2018 14:35:54:608 -- System.NullReferenceException: Object reference not set to an instance of an object
at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0
at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0
at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0
at (wrapper dynamic-method) System.Object:6b8e8f5d-3892-4e14-a87f-34c8cadc6c41 (intptr,intptr,intptr)`

**Comment by Karreg** [comment]
And a more complete log from @auanasgheps in #300 

```
03-14 11:04:46.838 D/KP2A    (23825): ShareUrlResults.OnCreate
03-14 11:04:46.839 D/KP2A    (23825): ShareUrlResults:apptask=
03-14 11:04:46.843 D/KP2A    (23825): Creating GBA
03-14 11:04:46.844 D/KP2A    (23825): Loaded task keepass2android.SearchUrlTask
03-14 11:04:46.902 I/MonoDroid(23825): UNHANDLED EXCEPTION:
03-14 11:04:46.930 I/MonoDroid(23825): System.NullReferenceException: Object reference not set to an instance of an object
03-14 11:04:46.930 I/MonoDroid(23825):   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.930 I/MonoDroid(23825):   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.930 I/MonoDroid(23825):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0 
03-14 11:04:46.930 I/MonoDroid(23825):   at (wrapper dynamic-method) System.Object:f71f5726-2419-4fc1-a86e-6bbc29f8b994 (intptr,intptr,intptr)
03-14 11:04:46.935 D/KP2A    (23825): System.NullReferenceException: Object reference not set to an instance of an object
03-14 11:04:46.935 D/KP2A    (23825):   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.935 D/KP2A    (23825):   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.935 D/KP2A    (23825):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0 
03-14 11:04:46.935 D/KP2A    (23825):   at (wrapper dynamic-method) System.Object:f71f5726-2419-4fc1-a86e-6bbc29f8b994 (intptr,intptr,intptr)
03-14 11:04:46.944 W/zygote  (23825): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
03-14 11:04:46.948 D/AndroidRuntime(23825): Shutting down VM
03-14 11:04:46.952 E/AndroidRuntime(23825): FATAL EXCEPTION: main
03-14 11:04:46.952 E/AndroidRuntime(23825): Process: keepass2android.keepass2android, PID: 23825
03-14 11:04:46.952 E/AndroidRuntime(23825): android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
03-14 11:04:46.952 E/AndroidRuntime(23825):   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.952 E/AndroidRuntime(23825):   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.952 E/AndroidRuntime(23825):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0 
03-14 11:04:46.952 E/AndroidRuntime(23825):   at (wrapper dynamic-method) System.Object:f71f5726-2419-4fc1-a86e-6bbc29f8b994 (intptr,intptr,intptr)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at md5f0702f468598c68ce18586502249fb40.ShareUrlResults.n_onCreate(Native Method)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at md5f0702f468598c68ce18586502249fb40.ShareUrlResults.onCreate(ShareUrlResults.java:31)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.Activity.performCreate(Activity.java:6999)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.Activity.performCreate(Activity.java:6990)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.os.Looper.loop(Looper.java:164)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at java.lang.reflect.Method.invoke(Native Method)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-14 11:04:46.959 W/ActivityManager(911):   Force finishing activity keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.ShareUrlResults
03-14 11:04:46.963 W/ActivityManager(911):   Force finishing activity keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.PasswordActivity
03-14 11:04:46.968 I/ActivityManager(911): Showing crash dialog for package keepass2android.keepass2android u0
```

**Comment by Karreg** [comment]
Great! Can't wait to test it in next preview :smile:
