### ISSUE TITLE
Text not readable in dark theme

### ISSUE THREAD

**Issue by Indubius** [PhilippC/keepass2android#29]
When creating a new folder and using the dark theme, both background and text are displayed in white, making it pretty hard to read the text. It'd be great if you changed either text or background colour for this issue.

**Comment by rsgosnell** [comment]
Running on a Pixelbook, Chrome OS.  Just updated the Pixelbook to Version 74.0.3726.0 (Official Build) dev (64-bit).  This gives white text on white background almost everywhere.  I did not change any settings, it just started with the update.

**Comment by Indubius** [comment]
Thx for fixing, Philipp!
