### ISSUE TITLE
Enable compatibility mode to support AutoFill on FireFox (Android 9.0)

### ISSUE THREAD

**Issue by ceribik** [PhilippC/keepass2android#290]
See the following link for details on how to do this:

https://developer.android.com/reference/android/service/autofill/AutofillService.html#CompatibilityMode

**Comment by PhilippC** [comment]
this requires Xamarin for Android for Android 9.0 which is not yet in stable channel. Moving this to 1.08 milestone.

**Comment by z3ntu** [comment]
Does this also apply to Chrome?

**Comment by PhilippC** [comment]
@z3ntu yes, it also applies to Chrome, but you should notice https://github.com/PhilippC/keepass2android/issues/1061#issuecomment-573741061
