### ISSUE TITLE
[Feature Request] download instead of caching

### ISSUE THREAD

**Issue by hueneburg** [PhilippC/keepass2android#291]
I don't want to upload my file to Google drive or some other cloud provider. So it would be great if I could just press a button to synchronize the database (uploading and downloading the Delta to my nas). This way, i can use it on all my PCs as well as my phone without giving the internet the possibility to hack it.

In short: add possibility to download database and to sync it.

**Comment by PhilippC** [comment]
If I don't miss anything, this should be easily possible: select "open database" and the choose an option which allow to access your NAS, e.g. WebDav. If you haven't disabled database caching, the database will be "downloaded" (to a local cache file) and "uploaded" when you save next time (unless you selected "work offline" which means only the local cache file is updated).

**Comment by hueneburg** [comment]
Is this also true if I close keepass2Android and try to reconnect to my db? Because it might be that I am not at home where my NAS is when I restart my phone.

**Comment by PhilippC** [comment]
The internal cache copy is placed in the "app folder" of KP2A. Unless Android clears that folder (which might happen if you are very low on memory), the file is there persistently.
