### ISSUE TITLE
Quick Settings buttons can not be pressed

### ISSUE THREAD

**Issue by XarisA** [PhilippC/keepass2android#292]
Hi all

After the last upgrade I can not press the quick setting buttons to lock or to close the database.
I have waited some time in case this was an issue in many devices but as far as I understand it's probably device specific.

My specs are the following:
App Version: 1.04b
Model: Huawei Mate 8
Android 7 
EMUI 5.0.1
Kernel 4.1.18

I attach some screenshots.

![screenshot_20180309-105838](https://user-images.githubusercontent.com/3985557/37200301-0887b0d4-238d-11e8-8f82-6b97e268a1a1.png)
![screenshot_20180309-105934](https://user-images.githubusercontent.com/3985557/37200307-0cc695f2-238d-11e8-9cb9-1828fdc2f9ba.png)

**Comment by PhilippC** [comment]
can you please check if this is gone in 1.05-pre? https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by XarisA** [comment]
Yeap it works like a charm in 1.05-pre !
Thank you!
