### ISSUE TITLE
Fill username doesn't work

### ISSUE THREAD

**Issue by dolphinkite** [PhilippC/keepass2android#296]
Ok, this problem has been going on for quite some time (6-12 months?) and I don't see anybody else raising this issue.

I'm running the latest version of Keepass2Android offilne: 1.03.

Here is the issue: When I try to log on a website using my phone (and I haven't found the equivalent of the chromepass plugin for my phone), I'll switch keyboard to the Keepass2Android offline one and then I'll select the entry for the site I am trying to log into.

Once done, if I position the cursor on the username entry, and choose "User Name", the apps seems to enter the username and then press a "enter", which obviously leads to an error since the password has not been entered. For some reason, I must first enter the password, then go back and enter the username. 

This used to work fine a few months ago (previous versions?). The automatic "enter" should be done after the password is entered, not the username. 

Am I missing something?

**Comment by PhilippC** [comment]
please switch to the beta channel which has the upcoming 1.04 release. The issue should be fixed there, see https://github.com/PhilippC/keepass2android/issues/89.
https://play.google.com/apps/testing/keepass2android.keepass2android_nonet

**Comment by dolphinkite** [comment]
When will this issue be fixed in the stable release? I see on the play store that Keepass2Android Offline was last updated on March 20th 2018, but the version number is still 1.03 and the issue is still present.

Thanks
