### ISSUE TITLE
[Feature request] Working with history

### ISSUE THREAD

**Issue by NEK-RA** [PhilippC/keepass2android#298]
Please add ability to work with history of entries.
It may not look important, but in fact everything is the opposite.
History is very important part of keepass from the moment when keepass made possible to attach the files to entries.
Adding one, second, third and etc. and after some time base become realy big and we will get a very long loading in the unstable network. In this case you load base and delete the files that not important, but the database still has the same size as before. Reason is that deleted file just removed from current entry state, but still exist in the history of entry. In this case you have no another way, but to use a PC version to clean the entry.
Yes, keepass is not a container for file storing, but sometimes it's more easy to attach i.e. some config instead of writing config content or descriptrion in the additional field.
Also the history required to compare changes of one entry: you've changed one password and the record with old password becomes to history. Some sites asking such info as a first (registration) password when you chose option "forgot password". At some sites user have to make a completely new password when changing it(do not use one of previous passwords). In all these cases history is very important part of keepass, and also just easier way to optimise database size.

**Comment by ibygrave** [comment]
Password history is also useful for some password change workflow. After generating a new password I need to see the previous one when completing the password change form.

**Comment by fusion1275** [comment]
@ibygrave I second that!! I use the app extensively and password history is required a lot. So much so I am thinking of moving to another app that has this functionality.

Please please get this useful addition in

**Comment by serebryakov-av** [comment]
+1
