### ISSUE TITLE
Enhancement request - Improve display of passwords

### ISSUE THREAD

**Issue by sbuttrill** [PhilippC/keepass2android#30]
Occasionally I use KeePass2Android to look up a password and the it into another device. My system font can be hard to differentiate between similar looking characters such as 1lO0. I would like to see color coding of numbers and special characters to make it easier to read. For example, I might suggest a special color for numbers and a separate color for special characters.

Thanks for all the good work!

**Comment by DJCrashdummy** [comment]
just my 2 cents:
although color-coding is a nice idea, i guess it is better for security, important for different color-schemes and maybe also easier to implement, to just use an other **easily readable font for displaying passwords** (like KeePassDroid does). and thus you don't have to remember which color is ment for text and which is meant for numbers.
i would suggest _**DejaVu Sans Mono**_ or even _Liberation Mono_ is ok... its a pitty that _Droid Sans Mono_ isn't that clear to distinguish. anyway i would stay with monospace-fonts, so you can also easily estimate the length of the password.

**Comment by PhilippC** [comment]
Keepass2Android uses the font SourceCodePro which has clearly distinguishable characters. If this font is not displayed correctly on your devices, please create a new issues for this.
