### ISSUE TITLE
Argon2 is extremely slow

### ISSUE THREAD

**Issue by Phantop** [PhilippC/keepass2android#306]
Seeing as KeepassXC implemented Argon2, finally, I set my database to use it.

Unfortunately, the implementation of Argon2 in Keepass2Android makes it take 40 seconds to do what my computer does in 1, and what KeepassDroid can do in about 5. Why's that happening if this app is based on KeepassDroid?

This is exclusive to Argon2.

Argon2 settings are 40 transform rounds, 64 MiB, 8 threads.

**Comment by RealOrangeOne** [comment]
The fact Argon2 is slower is actually a feature. It's a more secure algorithm compares to AES-PBKDF2, and so requires _far_ fewer rounds. I too use Keepass2Android, but I have far fewer rounds, so my phone can actually open it. As a phone is far less powerful, the number of rounds should be taken into consideration. See my writeup at https://theorangeone.net/posts/keepassxc-2.3-migration/#kdbx4

These symptoms also existed in AES-PBKDF2. On desktop, my machine could handle around 3m iterations in a second. If I tried that on mobile, yes i'd expect it to take a while. It's all about finding a midpoint youre happy with, fewer iterations so it can be opened in a reasonable time on mobile, yet enough that's it's secure enough for you.

**Comment by mydexterid** [comment]
Read this: https://github.com/PhilippC/keepass2android/issues/283
and this: https://sourceforge.net/p/keepass/discussion/329220/thread/acfd14b1/#711f/7bdc/a9f5

**Comment by akuntsch** [comment]
Is there any progress on this? It's really painful to wait ~30 seconds every time when opening the database (quickunlock is only a workaround when not rebooting the phone), while it takes 1 sec on a PC and a few seconds with other apps like https://github.com/Kunzisoft/KeePassDX (which I believe is a fork of KeepassDroid and uses the native C implementation).

**Comment by nazar-pc** [comment]
What takes 1s on my overclocked i9 9900k takes MINUTES on Nexus 6p.
My settings are 70 rounds, 64MiB memory, 16 threads.

As others said, KeePassDX doesn't have such issue, opens database in few seconds.

Do something about this, please, opening database or making any changes is insanely slow.

**Comment by jahnf** [comment]
I am not a C# developer, nor did I compare C# argon implementations, but if using the native implementation is too much hassle, maybe using another existing C# implementation would be faster? e.g. https://github.com/kmaragon/Konscious.Security.Cryptography#konscioussecuritycryptographyargon2

**Comment by dayvan** [comment]
I tested KeePass DX and on it the DB file is opened pretty fast if Argon2 is used.
It's also open source on github, but still in beta. Maybe you could borrow the Argon2 implementation and apply it to KP2A? :)

**Comment by yan12125** [comment]
I managed to speed up unlocking my Argon2 database by introducing the reference C implementation. The patch is #872 and a debug build can be found at https://dl.chyen.cc/keepass2android.keepass2android_debug-Signed.apk. That package is actually 1.06f + the Argon2 patch as the keyboard does not work for me in 1.07 (https://github.com/PhilippC/keepass2android/issues/871).
