### ISSUE TITLE
Databases on GDrive are not opened by default

### ISSUE THREAD

**Issue by johndoe23786** [PhilippC/keepass2android#308]
If I store my keepass in gdrive it is not opened by default. I mean that I see the "database selection screen" when I open the app instead of the "unlock database screen". When I store the same database in Dropbox it works fine ...

Thanks,
  Stefan

**Comment by Jbenci** [comment]
Same. Would save a couple of presses (and seconds) if this could be bypassed.

**Comment by Redoregon** [comment]
I'll third this one.  Should be a way to define a default database so you don't have to select it every time, no matter where you choose to put it.

**Comment by PhilippC** [comment]
fixed in 1.07
