### ISSUE TITLE
Stops Responding When Searching For Some Terms

### ISSUE THREAD

**Issue by christantoan** [PhilippC/keepass2android#31]
When I'm searching for some terms, after entering some letter, K2A will stop responding. I need to use force stop to make it usable again.
The terms seems random but consistent. Example I have is: "indo" (I want to enter "indosat", but when I enter "s", the app stops responding)

**Comment by PhilippC** [comment]
can you please collect a logcat of this?

**Comment by christantoan** [comment]
Hi, not sure if this will help as I don't see any relevant logcat for the crash. 
[2017-10-09-09-47-27.txt](https://github.com/PhilippC/keepass2android/files/1367787/2017-10-09-09-47-27.txt)

**Comment by PhilippC** [comment]
looks like you filtered to KP2A, so the logcat only contains messages logged by the app. But the app is not able to log anything when it really crashes, so you might want to exclude the filter?

**Comment by christantoan** [comment]
Ok, sure. 
[2017-10-09-10-11-39.txt](https://github.com/PhilippC/keepass2android/files/1367858/2017-10-09-10-11-39.txt)

**Comment by AlexCherrypi** [comment]
Is this still relevant?

I have no way of reproducing this issue, so does this problem still happen from time to time?

**Comment by christantoan** [comment]
> Is this still relevant?
> 
> I have no way of reproducing this issue, so does this problem still happen from time to time?

No, it no longer happens.
Sorry and thanks.
