### ISSUE TITLE
"Couldn't load data from server." – Nextcloud/WebDAV

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [PhilippC/keepass2android#313]
After working fine for a while, everytime I am about to unlock the database on my phone I get this error message:

![screenshot_20180324-214528](https://user-images.githubusercontent.com/36411819/37868844-b0a00c36-2fad-11e8-8e5a-ee768b5375b8.png)

(Last one says: "Data is being loaded from local cache. You can do changes on the database and synchronise them later.")

Android 6.0.1 on a Moto G (3. Generation)

How can I get this to work again?

**Comment by PhilippC** [comment]
if it was working before, this sounds a lot like there was a change on the server side. Can you figure out what that was?

**Comment by BunnyTheLifeguard** [comment]
Sure, but how can I do that? 😬

**Comment by BunnyTheLifeguard** [comment]
Ok I think I found the error: When trying to reconnect, I was still typing "https://" in front of the url and that did not work. Everything seems fine now, when leaving the "https://" away. 😅
