### ISSUE TITLE
SFTP connection does not work

### ISSUE THREAD

**Issue by Skuriles** [PhilippC/keepass2android#315]
Hello,

I'm trying to use this app for SFTP connection. 
The Db is on a server.
But I always get the message:
Can't connect to to file service: For input string: ""(translated from German version: "Kann nicht zum Datei Dienst verbinden")

I've tried several different writings of the server but nothing worked:

- hostname with sftp:// and without
- hostname/keepass folder added
- hostname/keepass/db.kdbx file added
- added optional start folder etc.

But it looks it does not work. With Keepass on Windows it works fine.
Did I miss something? Or does the app needs a special writing of the host?
Host is something like: <username>@servername.hoster.de 

Any ideas?

**Comment by PhilippC** [comment]
maybe related to #48

**Comment by Skuriles** [comment]
Hm,
I'm using latest LineageOs, but how can I replace Java Version of my Android device?

**Comment by PhilippC** [comment]
I'd suggest you wait for the next 1.05-pre release which has an updatetd JSch and works with more servers.

**Comment by Skuriles** [comment]
Still no luck with sftp and 1.05 beta.
Same error message: Can't connect to file service: For input string: ""
No matter if I add a optional folder or not. 
I will maybe move my db to google drive and try it again

**Comment by Skuriles** [comment]
Switched to Google Drive => works.
Maybe it is an issues with my webhoster or some SFTP java issue.

**Comment by gillesgros** [comment]
Using 1.04b. The message Can't connect to file service: For input string: "" appears after entering the second password with an SFTP connection.

Can you provide insight ?

Gilles

**Comment by gillesgros** [comment]
For those who might need an answer :+1: 
ServerName : host.domain.info (without sftp:// )
UserName : yourUserName
PathName : /your path/Yourfile.kdbx

**Comment by networxnet** [comment]
> For those who might need an answer 👍 ServerName : host.domain.info (without sftp:// ) UserName : yourUserName PathName : /your path/Yourfile.kdbx

How to be sure SFTP is used? Port 22 is not working.
