### ISSUE TITLE
[Feature Request] Support for Yubikey 4C

### ISSUE THREAD

**Issue by HarrPerson** [PhilippC/keepass2android#316]
Support for Yubikey 4c (USB C) would be great. At the moment only Yubikey NEO (NFC) is supported.

**Comment by piratenpanda** [comment]
I'd love to see this as well. Any guidance on what would be needed?

**Comment by PhilippC** [comment]
please try the beta 1.06b (https://play.google.com/apps/testing/keepass2android.keepass2android) and install ykDroid (https://play.google.com/store/apps/details?id=net.pp3345.ykdroid&hl=en). I haven't tested but it should work with Yubikey C as well.

**Comment by piratenpanda** [comment]
Sry for not getting back earlier. I am still waiting for a cable so I can set up my 4C otherwise I would have tested this already

**Comment by HarrPerson** [comment]
I had no time to test it for me at the moment. But also, thank you very much from my side! Best support, donation is on the way.
