### ISSUE TITLE
Can't hide Enable Autofill nag message

### ISSUE THREAD

**Issue by budajeff** [PhilippC/keepass2android#318]
The bottom of the app now always shows "Keepass2Android supports Android's Autofill feature but it looks like you haven't enabled it yet."

How do I dismiss this message if I don't wan't to enable it? My only choices are Enable Autofill and Show Autofill Help, neither of which i'm interested in.

This message is always displayed and takes up a lot of screen real estate.

**Comment by PhilippC** [comment]
enable autofill once, return to the app - message is gone. then disable autofill in the system settings if you don't like it.
Or install 1.05-pre2 (https://play.google.com/apps/testing/keepass2android.keepass2android).
