### ISSUE TITLE
Cannot open .kdbx file in Windows KeePass (2.36) after opening in KeePass2Android

### ISSUE THREAD

**Issue by ChiTownHustler** [PhilippC/keepass2android#32]
I need to keep passwords synchronized between my Windows desktop and Android phone. 

I'm using Dropbox to store the password file. I can place the KeePass file on Dropbox, and KeePass2Android successfully opens it. 

But, if I try to open the file again with KeePass, the following message is issued: "File signature is invalid. Either the file isn't a KeePass databse file at all or it is corrupted."

This occurs with even if the file is not stored on DropBox, but is instead moved directly between the desktop and Android device.

Any assistance would be greatly appreciated.

**Comment by PhilippC** [comment]
did you try only copying through MTP or also with Dropbox? Dropbox is more reliable. Can you sill open the file with Keepass2Android? If so, please try to compare the hash of the files on both devices. (You can use the old LoadingInfoUtil from https://keepass2android.codeplex.com/releases/view/120663 to get the hash and additional information on Windows+Android.

**Comment by ChiTownHustler** [comment]
Phillip, I wanted to get back to you on this. 

I think that the problem was the add-in that I was trying to use to sync. the databases. If I access the file directly in DropBox - that is, download / upload the file, it works fine. 

If you have an open issue regarding this, please close it. 

Thanks, 

Jon Juracich 

----- Original Message -----
