### ISSUE TITLE
keepass keyboard on opening app

### ISSUE THREAD

**Issue by basbakker** [PhilippC/keepass2android#321]
Can you make it that when you open the app it will change to the keepass keyboard? So I can enter my password in the 'safe' keyboard?

Atm it only switches when you select a entry.

(I'm using the keyboard swap plugin)

**Comment by basbakker** [comment]
awesome! can't wait for it. great work.

**Comment by DJCrashdummy** [comment]
this sounds like a reasonable feature request, but please just optional!
i use a FOSS keyboard (which i'm pretty sure is safe) on an FOSS AOSP-fork so i hardly need the KP2A-keyboard. beside that i setup KP2A to only use "the small KP2A-keyboard" (which wouldn't make sense in this case) as a fallback.

**Comment by PhilippC** [comment]
duplicate of #67
