### ISSUE TITLE
Add specific character on QuickUnlock keyboard

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [PhilippC/keepass2android#324]
I have some specific characters in my main password (like € £ ¥ ₩ • ...) and I can't type them on QuickUnlock .-. 
So for now I have to copy paste :/

**Comment by PhilippC** [comment]
which version are you running? Should be a duplicate of #161 which is fixed in 1.05-pre.

**Comment by PhilippC** [comment]
no reaction. Closing for now. Please open if you have 1.05 and still have the problem.
