### ISSUE TITLE
App crash when changing orientation while synchronizing

### ISSUE THREAD

**Issue by Sanaki** [PhilippC/keepass2android#33]
Noticed recently that if your device changes between portrait and landscape orientation while synchronizing the database, KP2A will crash. Immediately upon doing so, the synchronizing text will disappear, then generally 2-5 seconds later I get the crash notice. Tested multiple times on Android 7.1.2 when synchronizing with google drive. Let me know if you need any further details.

**Comment by PhilippC** [comment]
I cannot reproduce this. Can you please collect a logcat?

**Comment by Sanaki** [comment]
Sorry for the delay.

`10-11 14:11:00.085 21693 21693 D KP2A    : GroupActivity.OnCreate
10-11 14:11:00.086 21693 21693 D KP2A    : GroupActivity:apptask=
10-11 14:11:00.089 21693 21693 D KP2A    : Creating GBA
10-11 14:11:00.090 21693 21693 D KP2A    : Loaded task keepass2android.NullTask
10-11 14:11:00.134 21693 21693 W Group Activity:: Creating group view
10-11 14:11:00.135 21693 21693 W Group Activity:: Retrieved group
10-11 14:11:00.140 21693 21693 W Group Activity:: Finished creating group
10-11 14:11:00.144 21693 21693 D KP2A    : GroupActivity.OnStart
10-11 14:11:00.159 21693 21693 D KP2A    : GroupActivity.OnResume
10-11 14:11:00.159 21693 21693 D KP2A    :  DatabaseIsUnlocked=True
10-11 14:11:00.160 21693 21693 D KP2A    : Timeout cancel
10-11 14:11:00.277 21693 21693 D KP2A    : Setting activated = False
10-11 14:11:00.291 21693 21693 D KP2A    : Setting activated = False
10-11 14:11:00.308 21693 21693 D KP2A    : Setting activated = False
10-11 14:11:00.326 21693 21693 D KP2A    : Setting activated = False
10-11 14:11:00.335  1089  2170 W ConnectivityExtension: ConnectivityExt jar file not present
10-11 14:11:00.341 21693 21693 D KP2A    : Setting activated = False
10-11 14:11:00.351 21693 21693 D KP2A    : Setting activated = False
10-11 14:11:00.459  1089  1140 I WindowManager: Screen frozen for +885ms due to Window{f772404 u0 keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.GroupActivity}
10-11 14:11:00.478 21693 21693 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
10-11 14:11:00.647   513   621 I ThermalEngine: Monitor:ACTIVE:GPU_MONITOR:gpu=465000000:gpu=45000
10-11 14:11:00.647   513   621 I ThermalEngine: ACTION: GPU - Setting GPU[0] to 465000000
10-11 14:11:01.133  1089  1099 I art     : Background partial concurrent mark sweep GC freed 57442(3MB) AllocSpace objects, 51(3MB) LOS objects, 33% free, 27MB/41MB, paused 1.767ms total 245.417ms
10-11 14:11:01.625  1089  2170 W ConnectivityExtension: ConnectivityExt jar file not present
10-11 14:11:02.063  1089  2149 I CwMcuSensor: processEvent: Reporting mPendingEvent.light = 13.000000
10-11 14:11:02.063  1089  2149 I CwMcuSensor: offset changed, id = 3, offset = 453790327340
10-11 14:11:02.475  1089  1140 I art     : Starting a blocking GC Explicit
10-11 14:11:02.666  1089  1140 I art     : Explicit concurrent mark sweep GC freed 7580(759KB) AllocSpace objects, 11(704KB) LOS objects, 33% free, 26MB/39MB, paused 2.057ms total 190.858ms
--------- beginning of crash
10-11 14:11:02.885 22132 21693 F google-breakpad: Microdump skipped (uninteresting)
10-11 14:11:02.903 21693 21693 W google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
10-11 14:11:02.903 21693 21693 W google-breakpad: Chrome build fingerprint:
10-11 14:11:02.903 21693 21693 W google-breakpad: 1.02-pre4
10-11 14:11:02.903 21693 21693 W google-breakpad: 97
10-11 14:11:02.903 21693 21693 W google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
10-11 14:11:02.912 21693 21693 I MonoDroid: UNHANDLED EXCEPTION:
10-11 14:11:02.915 21693 21693 I MonoDroid: System.NullReferenceException: Object reference not set to an instance of an object
10-11 14:11:02.915 21693 21693 I MonoDroid:   at keepass2android.GroupBaseActivity.get_ListAdapter () [0x00010] in <b09bd240853f48a4ba659a7fd623fb48>:0
10-11 14:11:02.915 21693 21693 I MonoDroid:   at keepass2android.GroupBaseActivity.<Synchronize>b__b (System.Boolean success, System.String message) [0x00015] in <b09bd240853f48a4ba659a7fd623fb48>:0
10-11 14:11:02.915 21693 21693 I MonoDroid:   at keepass2android.ActionOnFinish.Run () [0x0003c] in <96a412f5bc634470b04fb95850e2dcc7>:0
10-11 14:11:02.915 21693 21693 I MonoDroid:   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <f851363d71da44549563ae515a9b1f0c>:0
10-11 14:11:02.915 21693 21693 I MonoDroid:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <f851363d71da44549563ae515a9b1f0c>:0
10-11 14:11:02.915 21693 21693 I MonoDroid:   at (wrapper dynamic-method) System.Object:ab2cb348-b271-487c-8ee6-5ccc7ad7992f (intptr,intptr)
10-11 14:11:02.922 21693 21693 D KP2A    : System.NullReferenceException: Object reference not set to an instance of an object
10-11 14:11:02.922 21693 21693 D KP2A    :   at keepass2android.GroupBaseActivity.get_ListAdapter () [0x00010] in <b09bd240853f48a4ba659a7fd623fb48>:0
10-11 14:11:02.922 21693 21693 D KP2A    :   at keepass2android.GroupBaseActivity.<Synchronize>b__b (System.Boolean success, System.String message) [0x00015] in <b09bd240853f48a4ba659a7fd623fb48>:0
10-11 14:11:02.922 21693 21693 D KP2A    :   at keepass2android.ActionOnFinish.Run () [0x0003c] in <96a412f5bc634470b04fb95850e2dcc7>:0
10-11 14:11:02.922 21693 21693 D KP2A    :   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <f851363d71da44549563ae515a9b1f0c>:0
10-11 14:11:02.922 21693 21693 D KP2A    :   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <f851363d71da44549563ae515a9b1f0c>:0
10-11 14:11:02.922 21693 21693 D KP2A    :   at (wrapper dynamic-method) System.Object:ab2cb348-b271-487c-8ee6-5ccc7ad7992f (intptr,intptr)
10-11 14:11:02.929 21693 21693 W art     : JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
10-11 14:11:02.937 21693 21693 D AndroidRuntime: Shutting down VM
10-11 14:11:02.949 21693 21693 E AndroidRuntime: FATAL EXCEPTION: main
10-11 14:11:02.949 21693 21693 E AndroidRuntime: Process: keepass2android.keepass2android, PID: 21693
10-11 14:11:02.949 21693 21693 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-11 14:11:02.949 21693 21693 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        ... 1 more
10-11 14:11:02.949 21693 21693 E AndroidRuntime: Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
10-11 14:11:02.949 21693 21693 E AndroidRuntime:   at keepass2android.GroupBaseActivity.get_ListAdapter () [0x00010] in <b09bd240853f48a4ba659a7fd623fb48>:0
10-11 14:11:02.949 21693 21693 E AndroidRuntime:   at keepass2android.GroupBaseActivity.<Synchronize>b__b (System.Boolean success, System.String message) [0x00015] in <b09bd240853f48a4ba659a7fd623fb48>:0
10-11 14:11:02.949 21693 21693 E AndroidRuntime:   at keepass2android.ActionOnFinish.Run () [0x0003c] in <96a412f5bc634470b04fb95850e2dcc7>:0
10-11 14:11:02.949 21693 21693 E AndroidRuntime:   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <f851363d71da44549563ae515a9b1f0c>:0
10-11 14:11:02.949 21693 21693 E AndroidRuntime:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <f851363d71da44549563ae515a9b1f0c>:0
10-11 14:11:02.949 21693 21693 E AndroidRuntime:   at (wrapper dynamic-method) System.Object:ab2cb348-b271-487c-8ee6-5ccc7ad7992f (intptr,intptr)
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.n_run(Native Method)
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
10-11 14:11:02.949 21693 21693 E AndroidRuntime:        ... 3 more
10-11 14:11:02.951  1089 31809 W ActivityManager:   Force finishing activity keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.GroupActivity
10-11 14:11:02.979  1089  2562 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.amazon.mShop.android/com.amazon.mcc.crashreporter.android.CrashReportBroadcastReceiver requires android.permission.READ_LOGS due to sender android (uid 1000)
10-11 14:11:03.020  1089 24611 I OpenGLRenderer: Initialized EGL, version 1.4
10-11 14:11:03.020  1089 24611 D OpenGLRenderer: Swap behavior 1
10-11 14:11:03.459  1089  1133 W ActivityManager: Activity pause timeout for ActivityRecord{3f1905f u0 keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.GroupActivity t8638 f}
10-11 14:11:03.557  1089  1133 E Notification: setLatestEventInfo() is deprecated and you should feel deprecated.
10-11 14:11:03.557  1089  1133 E Notification: java.lang.Throwable
10-11 14:11:03.557  1089  1133 E Notification:  at android.app.Notification.setLatestEventInfo(Notification.java:2083)
10-11 14:11:03.557  1089  1133 E Notification:  at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:2363)
10-11 14:11:03.557  1089  1133 E Notification:  at android.os.Handler.dispatchMessage(Handler.java:102)
10-11 14:11:03.557  1089  1133 E Notification:  at android.os.Looper.loop(Looper.java:154)
10-11 14:11:03.557  1089  1133 E Notification:  at android.os.HandlerThread.run(HandlerThread.java:61)
10-11 14:11:03.557  1089  1133 E Notification:  at com.android.server.ServiceThread.run(ServiceThread.java:46)
10-11 14:11:04.731  1089  2149 I CwMcuSensor: offset changed, id = 0, offset = 453841593901`

**Comment by PhilippC** [comment]
was able to reproduce

16.10.2017 12:52:01:799 -- LoadDB OK
16.10.2017 12:52:02:49 -- PasswordActivity.OnPause
16.10.2017 12:52:02:53 -- Timeout start
16.10.2017 12:52:02:112 -- GroupActivity.OnCreate
16.10.2017 12:52:02:113 -- GroupActivity:apptask=
16.10.2017 12:52:02:119 -- Loaded task keepass2android.NullTask
16.10.2017 12:52:02:249 -- GroupActivity.OnStart
16.10.2017 12:52:02:250 -- GroupActivity.OnResume
16.10.2017 12:52:02:251 --  DatabaseIsUnlocked=True
16.10.2017 12:52:02:252 -- Timeout cancel
16.10.2017 12:52:03:59 -- PasswordActivity.OnStop
16.10.2017 12:52:06:462 -- GroupActivity.OnPause
16.10.2017 12:52:06:463 -- Timeout start
16.10.2017 12:52:06:477 -- GroupActivity.OnStop
16.10.2017 12:52:06:482 -- GroupActivity.OnDestroyFalse
16.10.2017 12:52:06:652 -- GroupActivity.OnCreate
16.10.2017 12:52:06:653 -- GroupActivity:apptask=
16.10.2017 12:52:06:656 -- Loaded task keepass2android.NullTask
16.10.2017 12:52:06:688 -- GroupActivity.OnStart
16.10.2017 12:52:06:692 -- GroupActivity.OnResume
16.10.2017 12:52:06:693 --  DatabaseIsUnlocked=True
16.10.2017 12:52:06:693 -- Timeout cancel
16.10.2017 12:52:06:849 -- System.NullReferenceException: Object reference not set to an instance of an object
  at keepass2android.GroupBaseActivity.get_ListAdapter () [0x00011] in <12058ac0f6a14cb2be6dc204e41ebb1b>:0
  at keepass2android.GroupBaseActivity.<Synchronize>b__b (System.Boolean success, System.String message) [0x00019] in <12058ac0f6a14cb2be6dc204e41ebb1b>:0
  at keepass2android.ActionOnFinish.Run () [0x0004e] in <16bada42394d46dc92dc291eab91a7af>:0
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <04980648b38842d791d69b0431686998>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <04980648b38842d791d69b0431686998>:0
  at (wrapper dynamic-method) System.Object:15987156-66d0-4957-ad3a-fe98c8cd213b (intptr,intptr)
