### ISSUE TITLE
Keepass2Android keyboard to include TOTP button if entry has TOTP configured

### ISSUE THREAD

**Issue by layanto** [PhilippC/keepass2android#330]
I use Keepass2Android keyboard as the primary means of entering username and password. For entries with TOTP, I have to go into Keepass2Android and copy the TOTP. Would be great if Keepass2Android keyboard has an extra button for TOTP for entry with TOTP configured.

**Comment by layanto** [comment]
Didn't realise can access TOTP via the lock button next to password.

**Comment by Offerel** [comment]
Yes such a menu entry is available. But i would also find it useful to have it as a third button, additionally to username and password.
