### ISSUE TITLE
[Feature Request] Quickunlock password from the database itself

### ISSUE THREAD

**Issue by electrofloat** [PhilippC/keepass2android#331]
It would be nice to have an option for Quickunlock like what the https://github.com/JanisEst/KeePassQuickUnlock has:

> To enable QuickUnlock for a database you need to create a special entry in a group of the database. The title of this entry must be "QuickUnlock". The password you set in this entry will be the key you need to provide while unlocking the database. Only the title and the password field are mandatory, all other fields are ignored. QuickUnlock will not be available for the database if no entry with the title "QuickUnlock" is found or the password field is empty.

So users who already use this feature on desktop could use it on mobile too.
Of course the master password is encrypted with the Quickunlock password (https://github.com/JanisEst/KeePassQuickUnlock/blob/master/QuickUnlockProvider.cs#L135)

**Comment by umm7yass** [comment]
@PhilippC I second this suggestion. At the very least, making the QuickUnlock password configurable instead of tied to the end of your password. Having it linked to the end of your password forces me to end my password with whatever I have my quick unlock set to if I want any consistency between mobile and desktop.

**Comment by Corey-Keller** [comment]
@PhilippC I would also like to throw in my support for this feature. _If_ I can track down the commits used for how you used information from database entries to implement using KeeAutoExec entry info in auto-opening additional DBs, I'll try and adapt it to pulling the unlock phrase from the 'QuickUnlock' entry at the database root.
