### ISSUE TITLE
Enhancement Request Allow easy switch to previous keyboard

### ISSUE THREAD

**Issue by cverbiest** [PhilippC/keepass2android#333]
keepass2android lets you switch to its own keyboard very easily but AFAIK there is no easy way to return to the previous keyboard.
It would be very nice to have a key that opens keyboard selection dialog allowing users to return to their usual keyboard.

**Comment by PhilippC** [comment]
either you longpress the KP2A-button and select the keyboard symbol to get a keyboard dialog or you press the lock button to switch back to the previous keyboard (if this is enabled in the settings, which it is by default).
