### ISSUE TITLE
cannot deactivate AutoFill

### ISSUE THREAD

**Issue by tessus** [PhilippC/keepass2android#335]
After following the advice in https://github.com/PhilippC/keepass2android/issues/311#issuecomment-376098962 I can't deactivate AutoFill.

The `Application - Password entry access` shows `AutoFill Service` as enabled. There's no way to disable it.
Please note that `Auto-Fill enabled` is NOT checked in `Application - Keyboard`.

Now every time I get a popup in other apps whether or not I want to use Keepass2Android.

**Comment by PhilippC** [comment]
why another issue. see the comment to #311.

**Comment by tessus** [comment]
I opened this issue, because I haven heard back in 7 days. This is technically a separate issue (deactivating AutoFill vs. can't get rid of msg) and many developers do not like to discuss different/several issues in one thread. Thus I opened a new one.

**Comment by tessus** [comment]
Thanks, saw your reply in #311. It works. Cheers.
