### ISSUE TITLE
Timeout when syncing to remote (webdav)

### ISSUE THREAD

**Issue by NowayIndustries** [PhilippC/keepass2android#339]
Hi all,
I've been using the app for a while now, very happily. I recently noticed that my desktop app (keepassX) was missing entries compared to the mobile version and chalked this up to some sort of version / save file format mismatch.

After some digging I found out that keepass2android **has not been succesfully uploading my kdbx file!**

## The setup:
I use a nextcloud server for storing among other things my kdbx, so I only have to care about backing up a single datasource for my most important files.

I am using Nextcloud server "12.0.4.3" php 7.0.28 mysql 10.1.30, this all works very well and has no issues.
I have installed the app via the playstore and am currently using 1.04b with a kdbx file.

**My nextcloud hosted file is linked via the owncloud option when opening a file and this works perfectly fine, the file is cached and remote changes are seen and give the option to merge or overwrite.**

**Exporting the database to another file on the same nextcloud host (and in the same folder) works perfectly fine aswell!** This exported database also contains all the 'missing' entries and those can be shown in the desktop apps for kdbx files perfectly fine.

## The problem
The problem is with updating the existing database, **the actual contents are not changed**. However **it does show up in my nextcloud app's activity log as being changed**! This gives the user a false sense of safety regarding their password vault.

## What I think is happening
Looking at my nextcloud logs I can see the following entries roughly relating to a sync:
```
ip - - [11/Apr/2018:22:05:11 +0200] "GET /nextcloud/remote.php/webdav/Documents/Prive/androiddb.kdbx HTTP/1.1" *401* 426 "-" "okhttp/3.9.0"
ip - **user** [11/Apr/2018:22:05:12 +0200] "GET /nextcloud/remote.php/webdav/Documents/Prive/androiddb.kdbx HTTP/1.1" *200* 3842158 "-" "okhttp/3.9.0"
ip - - [11/Apr/2018:22:05:27 +0200] "PUT /nextcloud/remote.php/webdav/Documents/Prive/androiddb.kdbx HTTP/1.1" *401* 426 "-" "okhttp/3.9.0"
```
We can see the app tries to GET my kdbx, without authentication first. This receives a *401 authorization required*, and the app retries with authentication; and succesfully receives the file.

When it comes time to update the file it only ever tries without authentication, and naturally gets a *401 authorization required*. I can see this pattern repeating throughout my logfile.

There is no second entry a second later _with authentication_, the app just appears to wait untill it hits the timeout error. **This timeout error message (or really anything todo with saving) should cause a giant alert instead of a quickly dissapearing snackbar message!**

I think issue #152 is related, however I am getting an actual 401 error on the server instead of a 500. However that issues owncloud log actually shows: '"HTTP\\\/1.1 401 No 'Authorization: Basic' header found.' which appears to be consistent with my findings.

I did try without file transactions enabled, but found that it made no difference; the root cause appears to be the missing authentication on the PUT request.

## App Log:
This is the log from the app, I have removed the webdav connection details:
```
11/04/2018 22:04:27:40 -- Creating application keepass2android.keepass2android. Version=110
11/04/2018 22:04:28:339 -- GroupActivity.OnCreate
11/04/2018 22:04:28:344 -- GroupActivity:apptask=
11/04/2018 22:04:28:364 -- Loaded task keepass2android.NullTask
11/04/2018 22:04:28:438 -- PasswordActivity.OnCreate
11/04/2018 22:04:28:441 -- PasswordActivity:apptask=
11/04/2018 22:04:28:447 -- Loaded task keepass2android.NullTask
11/04/2018 22:04:29:146 -- PasswordActivity.OnStart
11/04/2018 22:04:29:182 -- PasswordActivity.OnActivityResult Canceled/0
11/04/2018 22:04:29:183 -- TryGetFromActivityResult: no data
11/04/2018 22:04:29:188 -- PasswordActivity.OnResume
11/04/2018 22:04:29:190 --  DatabaseIsUnlocked=False
11/04/2018 22:04:29:192 -- starting: True, Finishing: False, _performingLoad: False
11/04/2018 22:04:29:280 -- PasswordActivity.OnPause
11/04/2018 22:04:29:291 -- Pre-loading database file starting
11/04/2018 22:04:29:310 -- CFS: OpenWhenLocalChanges
11/04/2018 22:04:29:698 -- PasswordActivity.OnResume
11/04/2018 22:04:29:698 --  DatabaseIsUnlocked=False
11/04/2018 22:04:29:700 -- starting: False, Finishing: False, _performingLoad: False
11/04/2018 22:04:29:753 -- GroupActivity.OnDestroyTrue
11/04/2018 22:04:32:481 -- CFS: Files in conflict
11/04/2018 22:04:32:538 -- Pre-loading database file completed
11/04/2018 22:04:45:547 -- PasswordActivity.OnActivityResult 874348/1000
11/04/2018 22:04:45:549 -- No AppTask in OnActivityResult
11/04/2018 22:04:46:36 -- OnFinish message: Invalid composite key! Please try again.
11/04/2018 22:04:51:440 -- PasswordActivity.OnActivityResult 874348/1000
11/04/2018 22:04:51:443 -- No AppTask in OnActivityResult
11/04/2018 22:04:51:496 -- CFS: OpenWhenLocalChanges
11/04/2018 22:04:54:412 -- CFS: Files in conflict
11/04/2018 22:04:56:332 -- ReadXmlStreamed: 1725ms
11/04/2018 22:04:56:392 -- Starting/Updating OngoingNotificationsService. Database Unlocked
11/04/2018 22:04:56:431 -- LoadDB OK
11/04/2018 22:04:56:697 -- PasswordActivity.OnPause
11/04/2018 22:04:56:705 -- Timeout start
11/04/2018 22:04:56:746 -- GroupActivity.OnCreate
11/04/2018 22:04:56:748 -- GroupActivity:apptask=
11/04/2018 22:04:56:761 -- Loaded task keepass2android.NullTask
11/04/2018 22:04:56:999 -- GroupActivity.OnStart
11/04/2018 22:04:57:6 -- GroupActivity.OnResume
11/04/2018 22:04:57:7 --  DatabaseIsUnlocked=True
11/04/2018 22:04:57:10 -- Timeout cancel
11/04/2018 22:04:57:805 -- PasswordActivity.OnStop
11/04/2018 22:05:01:980 -- GroupActivity.OnPause
11/04/2018 22:05:01:981 -- Timeout start
11/04/2018 22:05:02:6 -- DatabaseSettingsActivity.OnCreate
11/04/2018 22:05:02:7 -- DatabaseSettingsActivity:apptask=
11/04/2018 22:05:02:268 -- DatabaseSettingsActivity.OnStart
11/04/2018 22:05:02:271 -- DatabaseSettingsActivity.OnResume
11/04/2018 22:05:02:272 --  DatabaseIsUnlocked=True
11/04/2018 22:05:02:272 -- Timeout cancel
11/04/2018 22:05:02:402 -- GroupActivity.OnStop
11/04/2018 22:05:09:90 -- DatabaseSettingsActivity.OnPause
11/04/2018 22:05:09:91 -- Timeout start
11/04/2018 22:05:09:111 -- GroupActivity.OnStart
11/04/2018 22:05:09:114 -- GroupActivity.OnResume
11/04/2018 22:05:09:115 --  DatabaseIsUnlocked=True
11/04/2018 22:05:09:115 -- Timeout cancel
11/04/2018 22:05:09:244 -- DatabaseSettingsActivity.OnStop
11/04/2018 22:05:09:247 -- DatabaseSettingsActivity.OnDestroyTrue
11/04/2018 22:05:23:978 -- ReadXmlStreamed: 1182ms
11/04/2018 22:05:38:187 -- timeout
11/04/2018 22:05:38:300 -- couldn't save to remote https://username:password@url.tld/nextcloud/remote.php/webdav/Documents/Prive/androiddb.kdbx
11/04/2018 22:05:38:304 -- System.Exception: timeout ---> Java.IO.IOException: timeout ---> Java.IO.IOException: socket is closed
   --- End of inner exception stack trace ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <bbb22c0b9b244b0bb0426ab5577d02e6>:0
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <1ec7b7317dd846a8a314e55115c46f36>:0
  at Android.Runtime.JNIEnv.CallVoidMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <0427915eb8c34e20b227185d2654799f>:0
  at Keepass2android.Javafilestorage.WebDavStorage.UploadFile (System.String p0, System.Byte[] p1, System.Boolean p2) [0x00092] in <0db3ef6c845f41df96dcf3cf2245a5fa>:0
  at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x0001c] in <a0341100aa934751bf6277d21d58c13f>:0
   --- End of inner exception stack trace ---
  at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x00036] in <a0341100aa934751bf6277d21d58c13f>:0
  at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00022] in <a0341100aa934751bf6277d21d58c13f>:0
  at keepass2android.Io.CachingFileStorage.TryUpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00000] in <a0341100aa934751bf6277d21d58c13f>:0
11/04/2018 22:05:38:315 -- Xml WriteDocument: 14114ms
11/04/2018 22:05:59:0 -- GroupActivity.OnPause
11/04/2018 22:05:59:1 -- Timeout start
11/04/2018 22:05:59:28 -- DatabaseSettingsActivity.OnCreate
11/04/2018 22:05:59:28 -- DatabaseSettingsActivity:apptask=
11/04/2018 22:05:59:146 -- DatabaseSettingsActivity.OnStart
11/04/2018 22:05:59:150 -- DatabaseSettingsActivity.OnResume
11/04/2018 22:05:59:150 --  DatabaseIsUnlocked=True
11/04/2018 22:05:59:151 -- Timeout cancel
11/04/2018 22:05:59:246 -- GroupActivity.OnStop
```

Sorry for the giant wall of text :speak_no_evil:

**Comment by ikke-t** [comment]
I see the same when my database would need syncing and merge should be done. My merge always fails similarly, same 401 logs. NextCloud is the latest of 13 series, everything up to date.

**Comment by dnel** [comment]
I might have seen this issue, I did not have logging enabled on kp2a however to verify what happened. I created a new entry on the app and on save it asked to merge changes but I wasn't expecting any changes and the app always confirms the file is in sync when I log in. Afterwards I noticed a lot of entries were missing when using Keepassxc on desktop and found the file size was about half what it should be. I have needed to restore the database from Nextcloud versioning which showed the drop in file size occured when I created the entry in kp2a. I run latest Nextcloud 13 and keep kp2a current.

**Comment by PhilippC** [comment]
referenced the wrong issue in my commit, reopening

**Comment by ikke-t** [comment]
For some reason I get timeout connecting there from app.

**Comment by jhesketh** [comment]
I think I might have seen this problem. I have a nextcloud installed with insufficient hardware which, while it does work, can be quite slow. It appears that the timeout in the keepass2android app is less than the timeout on the server; so even though the request for the webdav file[s] would have (eventually) worked the application stops short. I might be wrong, but perhaps we could increase the timeout or wait for a real response from the server?

**Comment by LuCu11** [comment]
I have the same Issue, running nextcloud 13.7
the timeout occures only when I`m connected over wlan
over mobile it works fine

**Comment by jhesketh** [comment]
One thing to check is whether you have the brute force prevention app installed in nextcloud. This will make nextcloud's API slower for IP's that make lots of failed log in attempts. If you have this enabled, make sure to whitelist your IP.

**Comment by LuCu11** [comment]
no I don´t have installed a app like this

**Comment by jhesketh** [comment]
I think it is a default app, but you may have it disabled already.

**Comment by treuss** [comment]
> I have the same Issue, running nextcloud 13.7 the timeout occures only when I`m connected over wlan over mobile it works fine

Having exactly this behaviour lately. 
Using Nextcloud 23.0.0 and the latest version of Keepass2Android from Google Play (1.09c-r0)

**Comment by KlausHans** [comment]
> > I have the same Issue, running nextcloud 13.7 the timeout occures only when I`m connected over wlan over mobile it works fine
> 
> Having exactly this behaviour lately. Using Nextcloud 23.0.0 and the latest version of Keepass2Android from Google Play (1.09c-r0)

Having the exact same issue. Did you found the issue?

**Comment by jhesketh** [comment]
It's been a while since I've seen this, so I can't entirely recall if it is relevant, but one thing to check is your brute-force detection in Nextcloud. Because the connection between keepass and my nextcloud server was slow, it was timing out and then retrying. These retries caused lots of failed login attempts, and therefore nextcloud started blocking the IP.

Basically it came down to making sure that nextcloud would respond+log you in before keepass2android times out, but you may be able to improve that by whitelisting your IP's/devices etc.
