### ISSUE TITLE
Bad TOTP Seed Error

### ISSUE THREAD

**Issue by KodiakIT** [PhilippC/keepass2android#340]
I seem to be having some issues with Twitter's TOTP settings, the seed produces appropriate output in KeePassXC, but KeePass2Android throws an error when opening the entry and trying to generate it.

**Comment by PhilippC** [comment]
Can you create a sample entry which causes that behavior?

**Comment by conkeating** [comment]
Hi @PhilippC, sorry for the lack of response, I'm not a particularly frequent user of Twitter or Github so this slipped my mind. As I recall, the issue turned out to be that there was a space at the end of the TOTP seed entry which KeepassXC ignored, but caused K2A to throw an error.

**Comment by fcrozat** [comment]
I just found one way to duplicate this: if the TOTP key contains a trailing space.

for instance: "xxx xxx xxx xxx xxx x " isn't creating TOTP code (KeepassXC handles this ok) but  "xxx xxx xxx xxx xxx x" works nicely.

**Comment by telmer6** [comment]
This also seems to occur if there are extra "=" characters at the end of the string. (e.g. Amazon, Dropbox).

**Comment by smaslennikov** [comment]
This has been triggered for me with a leading space or line break as well. KeepassXC doesn't seem to care.
