### ISSUE TITLE
Custom file path option

### ISSUE THREAD

**Issue by danpf** [PhilippC/keepass2android#343]
Instead of using the system file picker, could we have the option to enter our own path?
the (my?) system file picker only has  images videos audio and recent, but I store my databases in a custom folder synced by syncthing.

**Comment by DJJosephJumper** [comment]
I have the app MiXplorer on XDA Labs: https://labs.xda-developers.com/store/app/com.mixplorer and it can become the default file picker. You can use it to navigate to your folder.

**Comment by PhilippC** [comment]
the system file picker usually has a menu item to show external storage which should also include your data folder.

**Comment by danpf** [comment]
My phone must be old garbage (probably true). If that's the case in normal android I will just use MiXplorer instead!
