### ISSUE TITLE
Crash when use "search record with [com.android...] etc"

### ISSUE THREAD

**Issue by m-alice** [PhilippC/keepass2android#344]
Load any application
tap login field
Keepass keyboard appear
tap "keepass sign"
Keepass2Android "choose window" appear
tap "search record with ... "
If keepass app loaded and logined then crash
If keepass app not logined then app prompt password then try to load base and crash

https://youtu.be/RC8XuN0wPbw

[from_app.log](https://github.com/PhilippC/keepass2android/files/1913166/from_app.log)
[from_sys.txt](https://github.com/PhilippC/keepass2android/files/1913170/from_sys.txt)

Xiaomi Redmi 4X
7.1.2 N2G47H
MIUI Global 9.2.4.0 (NAMMIEK)
Keepass2Android 1.05-pre1
Plugins: QR 1.0.1 (enabled), Autofill 1.01 (enabled)

**Comment by m-alice** [comment]
Provided additional information.

**Comment by Karreg** [comment]
It's as I thought. It has been fixed in 1.05-pre2

**Comment by m-alice** [comment]
Sorry for delay. Fix confirm in 1.05-pre2 with MIUI Global 9.5.4.0 NAMMIFA.
