### ISSUE TITLE
Option to disable green icon circle

### ISSUE THREAD

**Issue by ArtskydJ** [PhilippC/keepass2android#345]
[![Screenshot_2018-04-15-21-27-07.png](https://s17.postimg.cc/albdksj8f/Screenshot_2018-04-15-21-27-07.png)](https://postimg.cc/image/9vsl8fior/)

I use a plug-in that lets me download icons from websites. The green circles behind the icons do not look great.

Thanks for making this app!

**Comment by Yorik-Code** [comment]
Get the app "KeePass2Android old icon set" from this Developer. This will fix your issue.
