### ISSUE TITLE
ENH [Autofill]: Reoccuring "Do you want to save this password?" question

### ISSUE THREAD

**Issue by tuxmobil** [PhilippC/keepass2android#347]
I'm using Keepass' Autofill feature with Android 8.1

Currently, every day I log into an app which' password I do *not* want to store in Keepass,
I get asked whether I want to save this password with keepass (the Autofill provider) after
entering the password.

[This is the dialog](https://developer.android.com/images/guide/topics/text/autofill_save.png)

It would be nice if Keepass somehow would remember my answer ("no thanks") for this
particular app so that I won't get asked every time again.

That would however also need a way to reset that decision in case the user would change its mind.

**Comment by PhilippC** [comment]
you can disable this question for all apps in KP2A's settings. You can also disable autofill for selected target apps. I think that's all I can do. Please re-open if you think there could be more.
