### ISSUE TITLE
Import data from "SafeInCloud" 

### ISSUE THREAD

**Issue by sklages** [PhilippC/keepass2android#348]
I have almost 200 records saved in Safeincloud. Is there a feasible way to import such data automatically into keepass2android?
I don't want to do that by hand 😊

**Comment by PhilippC** [comment]
maybe you found it: You should be able to import with Keepass 2 using https://github.com/Alezy80/SIC2KeePass (never tried it, though)

**Comment by sklages** [comment]
yep, that's why I closed this issue. `SIC2KeePass` had some issues importing my database with the linux version of keepass2. But the author of `SIC2KeePass` fixed this very fast :+1: 
Now I am using  `keepass2android` together with `KeePassXC` on Linux :grinning:
