### ISSUE TITLE
Re-formatted external SD card: Now local, cached password database cannot be synced back

### ISSUE THREAD

**Issue by FirestarterHNX** [PhilippC/keepass2android#35]
Dear Philipp,

my password database (located on my external sd card) has been open (online) while I ejected the external sd card. I copied all files from card to my pc, then re-formatted the sd card in my phone and that is where all the trouble begins (I thought the card had issues). K2A keeps a local copy of my database an is not able to sync back to the sd card, because Android 7 mounts external sd cards in a path with some randomly choosen name in between:

Example:
- old path to external sd = /storage/ABCD-EFGH/keepass-database.kdbx
- new path to external sd = /storage/IJKL-MNOP/keepass-database.kdbx

Where is my cached copy of the database located, on the phone?? Can I retrieve this most recent copy of my database?

Thanks in advance
FirestarterHNX

**Comment by PhilippC** [comment]
Can you export the database to a new file and then open that again?

**Comment by basbakker** [comment]
I think it's better to have the database in the phone memory. SD cards fail more than phone memory.

**Comment by FirestarterHNX** [comment]
Was able to export database to new file. This option can be found in preferences. Thanks, Philipp!
