### ISSUE TITLE
Android Auto Backup should be disabled

### ISSUE THREAD

**Issue by MalcolmEvershed** [PhilippC/keepass2android#350]
The [Android SDK docs](https://developer.android.com/guide/topics/data/autobackup.html) explain that Android 6 and newer may automatically backup some app files to the user's Google Drive account. The default is to allow auto backup:

> Apps that target Android 6.0 (API level 23) or higher automatically participate in Auto Backup because the android:allowBackup attribute defaults to true.

It seems like the Offline/nonet version of KeePass2Android should explicitly specify android:allowBackup=false. Maybe the regular version should as well, depending on what app files are put where.

**Comment by caesay** [comment]
Out of curiosity - why in the world would you not want to backup your keepass database?

**Comment by MalcolmEvershed** [comment]
> Out of curiosity - why in the world would you not want to backup your keepass database?

If you're using KeePass2Android _Offline_, you want to be offline, meaning that you don't want your database automatically uploaded online (to Google Drive). You may still want to backup your database, just not _automatically_.

If you're using regular KeePass2Android, maybe you don't want your database automatically uploaded to _specifically Google Drive_ and you want it synchronized with a different provider (and maybe a different location in the online account). Again, you may still want to backup your database, just not to the Android backups portion of Google Drive.

**Comment by wondering639** [comment]
I'd also like to see AutoBackup disabled, at least on the offline version. Data stored in a password safe is highly sensitive and shouldn't be uploaded automatically. How about maybe a offline & noautobackup version?

**Comment by PhilippC** [comment]
files are placed in the "no backup directory" already.

**Comment by wondering639** [comment]
Hi Philipp, how about disabling the backup at all? And can you elaborate, what you mean with "no backup directory"? Thanks!

**Comment by PhilippC** [comment]
I don't think there's anything wrong with backing up user preferences. 
https://developer.android.com/reference/android/content/Context#getNoBackupFilesDir()
