### ISSUE TITLE
Always show OTP key

### ISSUE THREAD

**Issue by feiming** [PhilippC/keepass2android#358]
Can we show OTP key without need to unmask all of the password? It would be better if it not masked. There's also no way to tell if the key is going to expire. Could make OTP fonts slowly fade to transparent, like in keeweb

**Comment by uncon** [comment]
I was about to open a similar issue on this. I am not a fan of having to (visually) reveal both my password and OTP secret key just to show my OTP for a given site.

**Comment by ASBaumgarten** [comment]
2 years later, and this is still not a feature.

**Comment by PhilippC** [comment]
it is implemented since 1.09b: you can enable this behavior in settings - app - display - "Mask TOTP field"

**Comment by ben-thul** [comment]
I'm probably missing something, but I don't see that option. I'm on
1.09c-r0.

--
Ben

**Comment by ben-thul** [comment]
![Screenshot_20220206-100900](https://user-images.githubusercontent.com/13566569/152695334-e6628cd8-aa6b-4aef-9116-2068ede76fd5.png)

**Comment by PhilippC** [comment]
sorry I was wrong, it was introduced in 1.09d-r0 which is available at https://github.com/PhilippC/keepass2android/releases or https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by ben-thul** [comment]
No worries - thanks for the update (and all of your work)!
