### ISSUE TITLE
 crash when opening database with OTP

### ISSUE THREAD

**Issue by int03** [PhilippC/keepass2android#371]
Webdav
Android ver.  8

Debug log
07/05/2018 17:49:20:59 -- PasswordActivity.OnPause
07/05/2018 17:49:21:122 -- FileSelect.OnCreate
07/05/2018 17:49:21:122 -- FileSelect:apptask=NullTask
07/05/2018 17:49:21:123 -- Loaded task keepass2android.NullTask
07/05/2018 17:49:21:151 -- FileSelect.OnStart
07/05/2018 17:49:21:154 -- FileSelect.OnResume
07/05/2018 17:49:21:477 -- PasswordActivity.OnStop
07/05/2018 17:49:21:480 -- PasswordActivity.OnDestroyTrue
07/05/2018 17:49:22:28 -- FileSelect.OnPause
07/05/2018 17:49:22:39 -- SelectStorageLocationActivity.OnCreate
07/05/2018 17:49:22:428 -- FileSelect.OnStop
07/05/2018 17:49:24:564 -- onAR
07/05/2018 17:49:24:565 -- base.onAR
07/05/2018 17:49:35:794 -- No AppTask in OnActivityResult
07/05/2018 17:49:35:822 -- PasswordActivity.OnCreate
07/05/2018 17:49:35:823 -- PasswordActivity:apptask=
07/05/2018 17:49:35:825 -- Loaded task keepass2android.NullTask
07/05/2018 17:49:35:890 -- PasswordActivity.OnStart
07/05/2018 17:49:35:893 -- PasswordActivity.OnResume
07/05/2018 17:49:35:894 --  DatabaseIsUnlocked=False
07/05/2018 17:49:35:895 -- starting: True, Finishing: False, _performingLoad: False
07/05/2018 17:49:35:900 -- Pre-loading database file starting
07/05/2018 17:49:35:908 -- PasswordActivity.OnPause
07/05/2018 17:49:35:916 -- CFS: OpenWhenNoLocalChanges
07/05/2018 17:49:35:917 -- CFS: hashing cached version
07/05/2018 17:49:36:32 -- PasswordActivity.OnResume
07/05/2018 17:49:36:33 --  DatabaseIsUnlocked=False
07/05/2018 17:49:36:35 -- starting: False, Finishing: False, _performingLoad: False
07/05/2018 17:49:36:802 -- FileSelect.OnDestroyTrue
07/05/2018 17:49:37:57 -- CFS: Files in Sync
07/05/2018 17:49:37:67 -- Pre-loading database file completed
07/05/2018 17:50:14:140 -- PasswordActivity.OnPause
07/05/2018 17:50:14:162 -- PasswordActivity.OnStop
07/05/2018 17:50:46:824 -- PasswordActivity.OnStart
07/05/2018 17:50:46:828 -- PasswordActivity.OnResume
07/05/2018 17:50:46:828 --  DatabaseIsUnlocked=False
07/05/2018 17:50:46:831 -- starting: True, Finishing: False, _performingLoad: False
07/05/2018 17:50:52:705 -- PasswordActivity.OnActivityResult 874348/1001
07/05/2018 17:50:52:706 -- No AppTask in OnActivityResult
07/05/2018 17:50:53:885 -- CFS: OpenWhenNoLocalChanges
07/05/2018 17:50:53:886 -- CFS: hashing cached version
07/05/2018 17:50:54:956 -- CFS: Files in Sync
07/05/2018 17:51:06:409 -- PasswordActivity.OnPause
07/05/2018 17:51:06:640 -- PasswordActivity.OnStop
07/05/2018 17:51:13:111 -- PasswordActivity.OnDestroyFalse
07/05/2018 17:51:13:192 -- PasswordActivity.OnCreate
07/05/2018 17:51:13:192 -- PasswordActivity:apptask=
07/05/2018 17:51:13:195 -- Loaded task keepass2android.NullTask
07/05/2018 17:51:13:322 -- PasswordActivity.OnStart
07/05/2018 17:51:13:330 -- PasswordActivity.OnResume
07/05/2018 17:51:13:331 --  DatabaseIsUnlocked=False
07/05/2018 17:51:13:332 -- starting: True, Finishing: False, _performingLoad: False
07/05/2018 17:51:13:336 -- Pre-loading database file starting
07/05/2018 17:51:13:339 -- CFS: OpenWhenNoLocalChanges
07/05/2018 17:51:13:340 -- CFS: hashing cached version
07/05/2018 17:51:13:382 -- PasswordActivity.OnPause
07/05/2018 17:51:13:476 -- PasswordActivity.OnResume
07/05/2018 17:51:13:476 --  DatabaseIsUnlocked=False
07/05/2018 17:51:13:483 -- starting: False, Finishing: False, _performingLoad: False
07/05/2018 17:51:14:536 -- CFS: Files in Sync
07/05/2018 17:51:14:538 -- Pre-loading database file completed
07/05/2018 17:51:29:963 -- PasswordActivity.OnPause
07/05/2018 17:51:30:455 -- PasswordActivity.OnStop
07/05/2018 17:51:34:753 -- PasswordActivity.OnStart
07/05/2018 17:51:34:756 -- PasswordActivity.OnResume
07/05/2018 17:51:34:757 --  DatabaseIsUnlocked=False
07/05/2018 17:51:34:759 -- starting: True, Finishing: False, _performingLoad: False
07/05/2018 17:52:05:930 -- PasswordActivity.OnActivityResult 874348/1000
07/05/2018 17:52:05:933 -- No AppTask in OnActivityResult
07/05/2018 17:52:06:67 -- received 3 otps.
07/05/2018 17:52:08:427 -- System.NullReferenceException: Object reference not set to an instance of an object
  at OtpKeyProv.OathHotpKeyProv.CreateAuxFile (OtpKeyProv.OtpInfo otpInfo, KeePassLib.Keys.KeyProviderQueryContext ctx, KeePassLib.Serialization.IOConnectionInfo auxFileIoc) [0x00030] in <036d7a25cadf4079828e0ccaad444a5c>:0 
  at keepass2android.PasswordActivity+SaveOtpAuxFileAndLoadDb.Run () [0x00020] in <036d7a25cadf4079828e0ccaad444a5c>:0 
07/05/2018 17:52:08:442 -- Java.Lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <57e0a6acef6e4845a0d5ecf0a1c0c092>:0 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <01c559b136574e6da7d54f4d43a3a646>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <01c559b136574e6da7d54f4d43a3a646>:0 
  at Android.Widget.Toast.MakeText (Android.Content.Context context, Java.Lang.ICharSequence text, Android.Widget.ToastLength duration) [0x00061] in <d7be053069994d8e8ea9693faa6a8e96>:0 
  at Android.Widget.Toast.MakeText (Android.Content.Context context, System.String text, Android.Widget.ToastLength duration) [0x0000d] in <d7be053069994d8e8ea9693faa6a8e96>:0 
  at keepass2android.PasswordActivity+SaveOtpAuxFileAndLoadDb.Run () [0x000a8] in <036d7a25cadf4079828e0ccaad444a5c>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d7be053069994d8e8ea9693faa6a8e96>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d7be053069994d8e8ea9693faa6a8e96>:0 
  at (wrapper dynamic-method) System.Object.30642583-467b-4831-aadc-3a4ccce9f0ed(intptr,intptr)
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
	at android.widget.Toast$TN.<init>(Toast.java:394)
	at android.widget.Toast.<init>(Toast.java:114)
	at android.widget.Toast.makeText(Toast.java:277)
	at android.widget.Toast.makeText(Toast.java:267)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at java.lang.Thread.run(Thread.java:764)

07/05/2018 17:52:08:462 -- PasswordActivity.OnPause
07/05/2018 17:52:18:228 -- Creating application keepass2android.keepass2android. Version=112
07/05/2018 17:52:18:372 -- KeePass.OnCreate
07/05/2018 17:52:18:376 -- KeePass:apptask=
07/05/2018 17:52:18:383 -- Loaded task keepass2android.NullTask
07/05/2018 17:52:18:383 -- KeePass.OnCreate
07/05/2018 17:52:18:399 -- KeePass.OnStart
07/05/2018 17:52:18:399 -- KeePass.OnStart
07/05/2018 17:52:18:452 -- FileSelect.OnCreate
07/05/2018 17:52:18:453 -- FileSelect:apptask=NullTask
07/05/2018 17:52:18:456 -- Loaded task keepass2android.NullTask
07/05/2018 17:52:18:577 -- FileSelect.OnStart
07/05/2018 17:52:18:585 -- FileSelect.OnResume
07/05/2018 17:52:18:681 -- KeePass.OnStop
07/05/2018 17:52:18:684 -- KeePass.OnDestroyTrue
07/05/2018 17:52:18:686 -- KeePass.OnDestroyTrue
07/05/2018 17:52:19:511 -- FileSelect.OnPause
07/05/2018 17:52:19:526 -- SelectStorageLocationActivity.OnCreate
07/05/2018 17:52:20:153 -- FileSelect.OnStop
07/05/2018 17:52:20:976 -- onAR
07/05/2018 17:52:20:978 -- base.onAR
07/05/2018 17:52:23:120 -- No AppTask in OnActivityResult
07/05/2018 17:52:23:162 -- PasswordActivity.OnCreate
07/05/2018 17:52:23:162 -- PasswordActivity:apptask=
07/05/2018 17:52:23:169 -- Loaded task keepass2android.NullTask
07/05/2018 17:52:23:473 -- PasswordActivity.OnStart
07/05/2018 17:52:23:485 -- PasswordActivity.OnResume
07/05/2018 17:52:23:486 --  DatabaseIsUnlocked=False
07/05/2018 17:52:23:489 -- starting: True, Finishing: False, _performingLoad: False
07/05/2018 17:52:23:547 -- PasswordActivity.OnPause
07/05/2018 17:52:23:554 -- Pre-loading database file starting
07/05/2018 17:52:23:557 -- CFS: OpenWhenNoLocalChanges
07/05/2018 17:52:23:717 -- PasswordActivity.OnResume
07/05/2018 17:52:23:717 --  DatabaseIsUnlocked=False
07/05/2018 17:52:23:719 -- starting: False, Finishing: False, _performingLoad: False
07/05/2018 17:52:24:41 -- FileSelect.OnDestroyTrue
07/05/2018 17:52:24:267 -- Received unexpected response: Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://xxxxx}
07/05/2018 17:52:25:452 -- PasswordActivity.OnPause
07/05/2018 17:52:25:469 -- AppSettingsActivity.OnCreate
07/05/2018 17:52:25:469 -- AppSettingsActivity:apptask=
07/05/2018 17:52:25:608 -- AppSettingsActivity.OnStart
07/05/2018 17:52:25:611 -- AppSettingsActivity.OnResume
07/05/2018 17:52:25:612 --  DatabaseIsUnlocked=False
07/05/2018 17:52:26:18 -- PasswordActivity.OnStop
07/05/2018 17:52:26:692 -- AppSettingsActivity.OnPause
07/05/2018 17:52:27:78 -- AppSettingsActivity.OnStop
07/05/2018 17:52:27:363 -- AppSettingsActivity.OnStart
07/05/2018 17:52:27:365 -- AppSettingsActivity.OnResume
07/05/2018 17:52:27:365 --  DatabaseIsUnlocked=False
07/05/2018 17:52:29:707 -- AppSettingsActivity.OnPause
07/05/2018 17:52:37:935 -- AppSettingsActivity.OnResume
07/05/2018 17:52:37:936 --  DatabaseIsUnlocked=False

**Comment by Crankle437** [comment]
I've the same problem. Is there any workaround to use otp?

**Comment by int03** [comment]
> I've the same problem. Is there any workaround to use otp?

Error occurs when i use android split window feature. Don't use :)
