### ISSUE TITLE
Add popup appears after startup

### ISSUE THREAD

**Issue by Mession77** [PhilippC/keepass2android#378]
Just now when starting Keepass2android, an add popup screen appeared, something about a 10 year birthday and if I wanted to send an e-mail. Is this a know issue? Unfortunately I didn't make a screenshot; will try when it appears again.

**Comment by PhilippC** [comment]
this is a popup asking for a donation. It appears in May (in the week of my birthday) and during Oktoberfest. You can turn it off in the app settings (settings > app > hide donation option and never ask for donations)

**Comment by SavantasNL** [comment]
Just donated, but I can't seem to get past the oktoberfest screen. I can't only open the download page or close the app if I click the second button. How do I get to my passwords now?
