### ISSUE TITLE
OneDrive issue in Beta

### ISSUE THREAD

**Issue by erichiller** [PhilippC/keepass2android#379]
I've just switched to the beta branch and of the two database opens 1 has failed and of the 3 or 4  database saves 1 has failed. 
Description of failure: the app locked up and I had to force close. In the example of the save, my changes were lost upon reopening the app. The message _"Local cache and Remote are synchronized"_ (or something to that effect, was displayed as the app opened my DB.

This is a DB in OneDrive, and these issues only began since updating to the beta channel , which Play store tells me occurred 20 hours ago.

Let me know what further information I can provide.

**Comment by PhilippC** [comment]
I have implemented a this completely new. Please switch to beta and install 1.07b-pre2 (just published to beta, see https://play.google.com/apps/testing/keepass2android.keepass2android). Please click "Change database" (on the password screen), then "Open database", "One Drive", "All files and shared files" (or something else if appropriate) and browse to your file again. This will then use the new implementation. (If you don't re-open the database like this, the old implementation will be used).
Please re-open (or comment) if the issue persists for some reason.
