### ISSUE TITLE
Tab hovers over sign-in screen

### ISSUE THREAD

**Issue by FranziPoldy** [PhilippC/keepass2android#380]
When I open Keepass2Android a rectangular tab hovers over the screen.  The tab has the green lock icon at the left followed by the words “Password for xxx” where xxx is the username for one of the entries in my data base.  If I tap on the tab, it puts the password for xxx in the space for entering the database password.  How can I make this tab go away?

**Comment by PhilippC** [comment]
can you please check if this is still present in 1.05 (https://play.google.com/apps/testing/keepass2android.keepass2android)?

**Comment by FranziPoldy** [comment]
Hi PhilippC,

The tab is still there in version 1.05.  I attach a screen shot.

Franzi

**Comment by FranziPoldy** [comment]
Further to my last email with the screenshot (tab is still present in 1.05), I also have Keepass2Android (v 1.04b) on my Samsung Galaxy Tablet S3 SM-T820.  This accesses the same database as my Nexus 5X mobile.  The hovering tab is NOT present on the tablet.

**Comment by PhilippC** [comment]
I don't see an image, can you please post on github?

**Comment by FranziPoldy** [comment]
![screenshot_20180518-185930](https://user-images.githubusercontent.com/39401988/40469075-b68770d6-5f72-11e8-8d54-4aaf6b00137c.png)
Not sure how this site works.  My screenshot is on Preview.

**Comment by FranziPoldy** [comment]
![screenshot_20180518-185930](https://user-images.githubusercontent.com/39401988/40469373-aa31376c-5f73-11e8-976f-da49f54c6964.png)

**Comment by FranziPoldy** [comment]
The screenshot was attached to my email.  Here it is again, embedded.  I think I’ve also posted it on github, but I’m not sure how that works.

**Comment by PhilippC** [comment]
please update to 1.05 and see if the issue is gone (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by FranziPoldy** [comment]
Just updated to version 1.05-pre2. Tab is still there.

**Comment by FranziPoldy** [comment]
No, I don’t think so.  I did also have “Donate to Keepass2Android” installed.  I have just uninstalled everything to do with Keypass2Andriod (i.e. KP2A v1.05-pre2 and Donate to Keepass2Android) and reinstalled Keepass2Android v. 1.05-pre2.  

 

The tab is still there.

**Comment by FranziPoldy** [comment]
The following may be relevant (v. 1.05-pre2).
The tab hovering over the sign-in screen, just above the keyboard, is there as soon as the app opens.  Pressing the mobile back key makes the tab and the keyboard disappear.  Tapping Password (to make an entry) brings back the keyboard and the tab.  Pressing the mobile back key makes the tab and the keyboard disappear (again).  Then, tapping either of the (i) spots (Enable QuickUnlock or Work offline) brings up an information window.  Tapping OK makes the window disappear and the tab (but not the keyboard) reappears.  Tapping the mobile back key takes me back to the home screen - i.e. it doesn't just make the tab disappear as when the keyboard is visible.
Incidentally, there used to be a special KP2A secure keyboard (on an earlier version?).  I don't have that now.

**Comment by FranziPoldy** [comment]
Is there any progress with this "floating tab" issue?

**Comment by PhilippC** [comment]
what do you have enabled as autofill service in the Android settings? Can you set to "None" please?

**Comment by FranziPoldy** [comment]
That was it.  It was set to Google.  I’ve set it to none and the tab has disappeared.  Thank you.

 

I note that Keepass2Android is an option on the Autofill option list.  Does it work?

**Comment by PhilippC** [comment]
yes.
