### ISSUE TITLE
Fingerprint doesn't work on Sony XZ2 Compact

### ISSUE THREAD

**Issue by dsent** [PhilippC/keepass2android#387]
Red exclamation mark is displayed next to the quick unlock field. Some kind of Java runtime exception, I can't copy the error message and can't make a screenshot (it's not allowed by the application).

**Comment by PhilippC** [comment]
you can disable screen protection in the settings. 
Please try to disable and re-enable fingerprint

**Comment by Yorik-Code** [comment]
I had something similar on a Samsung A5 (work phone) and I just tapped the exclamation mark, acknowledged the pop up and rescanned fingerprint, it seemed to work (maybe the fingerprint scanner takes too long to start). Give it a go.

**Comment by PhilippC** [comment]
tested on a XZ2 Compact, fingerprint does work.
