### ISSUE TITLE
Keepass2android beta Fingerprint problem

### ISSUE THREAD

**Issue by sonho666** [PhilippC/keepass2android#388]
I jumped to the new keepass2android beta as it supported Oreo Notification channel. The only problem is that if I disable the "database unlocked" channel my fingerprint no longer work and I have to write my long password every time.

If I leave this notification alone, I have a permanent icon on my android.

Is there a way to get rid of this icon and still be able to user the fingerprint?

Thank you!

**Comment by PhilippC** [comment]
No idea how this should interfere with the fingerprint...
Can you please set the importance of the notification to minimum instead of disabling it?
