### ISSUE TITLE
[feature] Show username in search results

### ISSUE THREAD

**Issue by Birch-san** [PhilippC/keepass2android#390]
<img width="270" alt="repro" src="https://user-images.githubusercontent.com/6141784/40778490-3ca7f8f6-64c9-11e8-87a1-57d38de7feae.png">

Could you please expose username in the search bar?

The search bar shows only the _title_ of the record.  
The username is really important for multi-account situations.

**Comment by PhilippC** [comment]
the search results also show the username if the username matches the query. I'd suggest to give meaningful titles for this usecase.
