### ISSUE TITLE
Keepass defaults to local keepass-database

### ISSUE THREAD

**Issue by madjo80** [PhilippC/keepass2android#391]
Ever since the most recent update, keepass doesn't open my offsite stored database by default, instead it defaults to its locally stored copy. 

It doesn't even attempt to open the one stored on my WebDAV stored database.

**Comment by canojim** [comment]
Ya, it didn't default to dropbox copy any more after update. It will default to local cache copy with read-only.

**Comment by otaconix** [comment]
As a workaround, you can disable the making of local backups (Settings -> Application -> File handing -> Local backups).

Also, it should be noted that I can't unlock local backups using my fingerprint, making this issue doubly annoying.

**Comment by Egokrieger** [comment]
Same here. Since the Oreo-Update together with the latest Keepass-Beta it always opens with the local copy as default, not my cloud-database. Kind of annoying, tbh. Hope this will be fixed soon, I'll promise you a big beer for it! ;-)

**Comment by PhilippC** [comment]
this is fixed since 1.05a.
