### ISSUE TITLE
"the name must not be empty: null" when trying to access the .kdbx on Google Drive

### ISSUE THREAD

**Issue by safeforschool** [PhilippC/keepass2android#398]
When choosing my Google account to access the Google Drive where my .kdbx is on, it gives me the mentioned error. This happened since changing to the beta version.

KP2A: 1.05a
Android: 8.0.0

**Comment by PhilippC** [comment]
did you grant the required permissions (contact & storage)?

**Comment by safeforschool** [comment]
It was working before, I don't recall to got asked again for permissions and didn't intentionally switched off anything.

Checked again and now it magically works again. Guess the issue is solved for now.

**Comment by Barleyman** [comment]
Same problem here. Yes, permissions granted. Tried clearing app data and reinstalling bujt no joy.  Was working fine for a long time previously.

**Comment by schorsch262** [comment]
Same problem (Android 8). For me it worked after a reboot.
