### ISSUE TITLE
App crashes in the settings (error is described in German)

### ISSUE THREAD

**Issue by Anagastes** [PhilippC/keepass2android#40]
Wie per Mail besprochen stürzt die App ab in den Einstellungen.

Entweder direkt oder kurz danach. Habe ein logcat dazu erstellt. Passwort schicke ich über andere Wege. Bin da etwas paranoid.

[logcat-crash-issue.zip](https://github.com/PhilippC/keepass2android/files/1369378/logcat-crash-issue.zip)

**Comment by PhilippC** [comment]
hmm, I am not really able to track this down from the logcat. It looks more like an ANR than a crash. Does this occur for locked and unlocked databases or only in one case? (unlocked databases have more settings). Can you please report your device & OS version. Do you have any special things installed?

**Comment by Anagastes** [comment]
The error occurs in both cases. Unlocked and locked database.

Devices: Xiaomi Redmi Note 4 Snpadragon

OS: LineageOS
https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/rom-unofficial-lineageos-13-t3607847

Extension: Xposed

Root?: Yes

**Comment by PhilippC** [comment]
can you disable Xposed for testing? There are a few lines which look weird to me:

10-09 19:19:36.818 W/ResourceType(8858): No package identifier when getting value for resource number 0x00000000

These might be the cause for the ANR and might be caused by Xposed. (But I might be totally wrong on this...)

**Comment by Anagastes** [comment]
Same result. Xposed completely disabled and started without.

**Comment by Anagastes** [comment]
I'm now on LOS 14.1 and Xposed 88.1

Now everything works fine... wierd. 

Many many thanks for you! :)
