### ISSUE TITLE
Permission Denial accessing database

### ISSUE THREAD

**Issue by sbraaa** [PhilippC/keepass2android#402]
Today keepass2android didn't find the database! After putting my pwd an alert told me 
"Permission deniala: opening provider com.android.providers.downloads.DownLoadStorageProvider from ...... requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs".
This occours on a LG G6 with Oreo, 2 days ago it runs well, today I found this error and I don't know what to do!
The app was configured to keep local cache of database but I didn't find the right directory... any suggets please?

**Comment by PhilippC** [comment]
Did you create the database on this device or did you open an existing database? Can you re-select the file by clicking Change database?

**Comment by sbraaa** [comment]
I created the database on my device. I've tried re-select the file by clicking Change database but I didn't find the place were the file was supposed to be.
Could you give me some hints to find the right path? which is the file default extension? kbdx? No files on my device with that extension :-(

**Comment by PhilippC** [comment]
you can see the default path if you create another new database

**Comment by sbraaa** [comment]
that path doesn't exists on my device!
How could this is possibile?
Recently I made a clean-up of system and apps cache, could this be the problem?
And if the answer is yes, why? I guess that file should be considered as app data (which obviously I didn't remove) and not as app cache

**Comment by PhilippC** [comment]
are you sure you created the database in that default directory? Because in your message "com.android.providers.downloads.DownLoadStorageProvider " sounds like you used another app to open the file, and that would also make more sense in that a file from a "download storage provider" might be considered cache?

**Comment by sbraaa** [comment]
Sincerely I don't remenber. when I first install the app I used default settings so I guess the database should be created in default directory.
I'm sure not have used other app. I dindn't found any database, not in my device, nor in any cloud connected.
Fortunately I found a backup manually made so my data are restored. I put my backup file on gdrive and It seems all is running well.
Thank you for your support.

**Comment by sbraaa** [comment]
Little update (I don't know if it is related to the original problem).
After create a new database and put it on my gdrive account it seems that all runs well.
Today trying to access the database the app gave me an error ("the name must not be empty") and told me that a local copy will be used.
Any try to use the database selecting from gdrive account gave me the same error : "the name must not be empty".
Accessing my gdrive account using official gdrive app solve the problem.
It seems related to Google Drive API not to keepass2 but it's very strange behaviour...

**Comment by PhilippC** [comment]
please see 
https://github.com/PhilippC/keepass2android/issues/417#issuecomment-398194855
