### ISSUE TITLE
[Enhancement] Consistent use of password font.

### ISSUE THREAD

**Issue by wikholm** [PhilippC/keepass2android#404]
As of 1.04b, the password font (DejaVu Sans Mono) is used when viewing stored passwords, but when editing, creating or generating passwords, KP2A falls back to some default UI font, in which I, l, 0, O etc. are much harder to tell apart. Consistent use of DejaVu Mono, whenever a password is shown, would, I think, make certain user errors less likely, such as, for example, misreading a newly generated password and thus sign up somewhere with a different password than what actually gets stored in the KP2A database.

Personally, I'd be ok with the entire UI using DejaVu, but that might break certain style guides.

**Comment by rmgr** [comment]
I've also run in to this issue.

**Comment by daevidvincent** [comment]
Just came to post this bug! Please fix to font that is clear what each letter/number is.
![Screenshot_20191117-123116_Keepass2Android](https://user-images.githubusercontent.com/20825058/69013599-c0750580-0936-11ea-8f7b-dc04ccbdf946.jpg)
![Screenshot_20191117-123028_Keepass2Android](https://user-images.githubusercontent.com/20825058/69013602-c7037d00-0936-11ea-9968-c811b4be1786.jpg)

**Comment by Zhaph** [comment]
Personally I'm still finding it hard to distinguish between zero 0 and capital oh O in the displayed password

**Comment by vk5880** [comment]
Please update font
