### ISSUE TITLE
timeout quick unlock

### ISSUE THREAD

**Issue by illionas** [PhilippC/keepass2android#405]
When activating quick unlock, we are basically lowering security for the sake of convenience. Too me it seems that this should only be temporarily.

I guess it should be:
- open for less than 5 minutes (to reduce hassle with copying/creating/editing passwords.
- in quick unlock mode for between an hour and 3 hours maybe. Don't want to type in 20 letter passphrase multiple times a day. Use a short password (probably stillshould be more than just 3 letters default), btw I like the idea of storing a quick unlock password in the database. It simply use fingerprints.
- still, you wouldn't want to have your database left easily breakable with only a three letters password for eternity. I don't know if the only one try rule makes this any better (can this be bypassed if the phone is connected to a computer?). Additionally, in the fingerprint for quick unlock scenario time is not an issue for an intruder.

**Comment by Small-Ku** [comment]
Would first 2 item duplicated with #53 and #331?
Although I didn't get what you mean in third point, you can change the length of QuickUnlock code in setting now.

**Comment by Karreg** [comment]
Also, security issue is mitigated by the fact that only one failure will require to input the full password... Meaning the only way to break through quickunlock is to know the 3 (or more because it's configurable) characters first...

**Comment by PhilippC** [comment]
closing as duplicate of #53. please reopen if you have a certain point uncovered by the referenced issues.
