### ISSUE TITLE
long passwords not visible

### ISSUE THREAD

**Issue by illionas** [PhilippC/keepass2android#406]
A problem I often encounter is that too view long passwords you need to choose to "edit" them and then scroll around the text field.

Maybe there could be a way to change the text girls to a multiline text area of the password exceeds the line (or a predefined number of letters).

One big advantage of using passphrases instead of passwords is that you can easily type them into other machines. A few words can be easily remembered for a few minutes. But first, you need to be able to read them off your database of course.

**Comment by PhilippC** [comment]
fixed in 1.05 (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by illionas** [comment]
Perfect! Thanks
