### ISSUE TITLE
HEEEEEELLLLLLPPPPPP

### ISSUE THREAD

**Issue by alberto-cado** [PhilippC/keepass2android#408]
I really need help over here, sorry about the long subject. This morning I signed into the app with my fingerprint just fine, I could navigate  just fine through my password database but the app showed me a message saying that the amount of time I've used the fingerprint has expired and that I must reenter the main password. Somehow I've lost the password and I cannot get my passwords back. Please tell me there's a way I can trick the app to use my fingerprint or that I can somehow relate my fingerprint with the master password.

**Comment by PhilippC** [comment]
Are you sure you understood the message correctly? Maybe it was

> Note that you will not be able to open your database without the master key. There is no way to "reset" the master password. Also note that fingerprint unlock works by storing your master key in Android's secure storage. This storage may be deleted by Android at any time, e.g. if you add a new fingerprint in the system settings. So don't rely on your fingerprint but remember your master password, please!

? 
Can you just try to use the fingerprint again? If that works you might either be able to quickly press the eye-icon on the password screen to show the password or after unlocking you can export to unencrypted xml, which can be re-imported into a new database on Windows using Keepass 2.

If you cannot open with fingerprint AND you don't remember the master password, there is not a lot I can do to help, unfortunately.

**Comment by alberto-cado** [comment]
I can't use my fingerprint anymore and I forgot the master password. Thanks anyway
