### ISSUE TITLE
Keepass Keyboard showing entire password

### ISSUE THREAD

**Issue by TheCodeFiend** [PhilippC/keepass2android#41]
I've been using the app for quite a while, and I have noticied new behavior recently on all my devices.  When I use the Keepass keyboard to enter my password, the entire password becomes visible in the password box for a short period.  I would like to turn this feature off.  I do not need to see my entire password.  I like to use the Keepass keyboard to avoid that.  I've looked through settings, and I can't find a way to do it.

**Comment by PhilippC** [comment]
this is rather a behavior of the controls you're inputting to. The Keyboard emits the password as a whole (not as single key strokes) which can lead to the effect you see. The keyboard hasn't changed for a while.
