### ISSUE TITLE
Traytotp

### ISSUE THREAD

**Issue by xgpt** [PhilippC/keepass2android#411]
I see settings for traytotp plugin. But I can't see where the plug in is available for download? I have at least one entry in my database with a seed and seed setting...but I can't seem to figure out how to get the keepass2android app loaded with a traytotp  otp generation capability

**Comment by xgpt** [comment]
I should add that I'm using the beta tester

**Comment by xgpt** [comment]
It "just works" with the kp2a keyboard!! I had spaces in the seed though and the software didn't parse them out. Perhaps it can be fixed so that the spaces these otp processed providers give out don't break the function?

**Comment by PhilippC** [comment]
looking at the code I see that spaces are removed already.
