### ISSUE TITLE
Missing add/edit entry icon

### ISSUE THREAD

**Issue by andypl** [PhilippC/keepass2android#413]
Hello,

Yesterday I have updated Keepass2Android to the newest beta version (1.05d) and now I can't add or edit entry from K2A because icon is missing.

Smartphone: LG G4 supercharged by LineageOS 14.1

**Comment by maart84** [comment]
Check the solution in #400

**Comment by chandramoulipathanjali** [comment]
I still have this problem even after choosing the database from Change Database

**Comment by chandramoulipathanjali** [comment]
[https://www.youtube.com/watch?v=nuYpoqkbxSs](url)

**Comment by andypl** [comment]
@maart84 changing database fix this problem for me, thanks.

**Comment by PhilippC** [comment]
@chandramoulipathanjali can you swipe down in the password screen to see the full database path? What is it?

**Comment by vcurl** [comment]
In version 1.05e, I do not have the add/edit icons, there is no database path on the password screen, and I have no option to 'change database' under settings/database.
