### ISSUE TITLE
SSL problem since 1.05d: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by markusd112** [PhilippC/keepass2android#419]
Since upgrade to version 1.05d yesterday I get an error message when keepass2android tries to sync my keepass file stored on my qnap nas via https (webdav): "Warning: Cannot validate server certificate: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. Install a root certificate on your device or see settings" (Warnung: Server-Zertifikat konnte nicht validiert warden: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. Installiere ein passendes Root-Zertifikat auf deinem Gerät oder s. Einstellungen.)

And nevertheless the sync seems to work, even though the error/warning message: several seconds after the error message the "sync completed message" appears....

I am using a self generated SSL certificate signed with my own CA. I have installed to root certificate on my devices.

Before the update everything worked fine... 

Maybe this could be a reason (I had the same error message a year ago with Banking4A when the developer has changed the API level in the IDE/compiler. After he has changed the following setting in the manifest, it worked again):

"... apps targeting Android 6.0 (API level 23) and lower also trust the user-added CA store by default."

https://developer.android.com/training/articles/security-config.html

Mit der folgenden Option im Manifest/XML-Config-File kann man scheinbar
 steuern, ob User-eigene CAs akzeptiert werden, vielleicht liegt ja hier
 das Problem:

```
     <certificatessrc=["system"| "user"| "/raw resource/"]               overridePins=["true"| "false"] />

 |src|
     The source of CA certificates. Each certificate can be one of the
     following:

       * a raw resource ID pointing to a file containing X.509
         certificates. Certificates must be encoded in DER or PEM format.
         In the case of PEM certificates, the file /must not/ contain
         extra non-PEM data such as comments.
       * |"system"| for the pre-installed system CA certificates
       * *|"user"|**for user-added CA certificates*
```

**Comment by ibressler** [comment]
I am affected as well (v1.05e), it refuses to sync with the server. But in my case, I use a certificate from cacert.org with the root cert being already installed system-wide.

**Comment by wwebers** [comment]
I experience the very same problem with a Comodo certificate.

**Comment by PhilippC** [comment]
closed in commit https://github.com/PhilippC/keepass2android/commit/ee63946be2c9cde0fdf912569db5a2f9dbd274b1 (referenced the wrong issue)

**Comment by dennisboeck** [comment]
I experience the very same problem with a Sectigo certificate (used by https://dennisboeck.de/test.html). Obviously Comodo is now Sectigo. How was the issue resolved?
