### ISSUE TITLE
SFTP: Failed resolution of: Lorg/ietf/jgss/Oid

### ISSUE THREAD

**Issue by adrianf0** [PhilippC/keepass2android#420]
In version 1.05d I get a new error when try to access my database over sftp:

![screenshot_20180620-092955](https://user-images.githubusercontent.com/8123045/41649128-131b61be-747b-11e8-8563-cbfee0b12bdf.png)

**Comment by PhilippC** [comment]
I found that there is an issue in JSch with servers supporting gssapi-with-mic. If you can disable this for your server, your might be good. I have incorporated a workaround which you should get with the next beta .

**Comment by adrianf0** [comment]
@PhilippC thanks for your reply.
Unfortunately, I don't have access to server's configuration.

**Comment by jac423** [comment]
I encountered this same issue in the 1.05d release.  I wanted to report that the above suggestion worked for me.  After disabling Kerberos auth in Bitvise SSH server, I was once again able to connect.  Thank you for this.
