### ISSUE TITLE
Bug v1.05d

### ISSUE THREAD

**Issue by zediiiii** [PhilippC/keepass2android#421]
Attempting to connect to Google drive after in place update yeilds error: null name must not be empty. Clear data fixes the issue, though reinstall did not.

**Comment by Acters** [comment]
I cleared the cache and "force stop"ed it. fixed it for me.

**Comment by Danixu** [comment]
Same problem here... The phone was formatted so i don't think that force stop and clear cache will help...

**Comment by PhilippC** [comment]
please see
https://github.com/PhilippC/keepass2android/issues/417#issuecomment-398194855
if you still have the issue.

**Comment by zediiiii** [comment]
Thanks @PhilippC. My apologies for creating a separate ticket.
