### ISSUE TITLE
Excessive battery usage

### ISSUE THREAD

**Issue by gogainda** [PhilippC/keepass2android#423]
On Samsung 7 with Oreo update system complains about battery usage until I force stop it

**Comment by Sanaki** [comment]
I assume you mean the Android System notification that says "1 app is consuming battery" or something of that nature? If so, that notification will apply to any app that runs in the background, especially those that maintain a notification while doing so. I constantly have 5-6 apps listed there, but it isn't actually an indication of battery consumption.

**Comment by Sanaki** [comment]
Does that one have a persistent notification that can't be swiped away? If not, that's probably why.

**Comment by phocean** [comment]
Same issue here. 
I wonder how other password managers do (I did not have such an alert with enpass, for instance).

**Comment by Sanaki** [comment]
Just to be clear, have either of you actually noticed any abnormal battery consumption from the app, or are you -only- talking about the notification?

**Comment by phocean** [comment]
The notificaiton only appears for this app all the time, and another one from time to time.
So I believe this is for a good reason, but I am going to measure the battery consumption from now to make sure.

**Comment by Sanaki** [comment]
I have Override DNS, Tasker, OpenVPN, Orbot, TermBot, and Keepass2Android in that list at all times. None of those consume more than around 2-3% battery at most in a full charge generally. [The notification itself used to be labeled as apps running in the background.](https://www.androidheadlines.com/2017/10/android-8-1-shows-persistent-apps-consuming-battery-alert.html) It depends on -how- it's running in the background, but it doesn't explicitly mean the app is actually consuming battery.

**Comment by PhilippC** [comment]
Keepass2Android uses an ongoing notification for its QuickUnlock implementation. There is an Android service running in the background to make sure the app is not killed by the OS. This allows to keep the database in memory without persisting unencrypted database contents or master key. The service does not do any work and thus does not consume battery power.

**Comment by cherio** [comment]
Mine uses relatively a lot of battery in **foreground**, though none in background, likely because I configured it to self destruct after a minute. I could be browsing in chrome for a hour and open keypass a few times to fill in passwords but its battery consumption shows as more than from chrome app. I love hearing that it doesn't use battery but the battery keeps telling me otherwise.
