### ISSUE TITLE
Crashes when entering certain phrases into search

### ISSUE THREAD

**Issue by BradleyDS2** [PhilippC/keepass2android#429]
When entering certain phrases into the search, the app crashes, resulting in a white page then a couple of seconds later displaying the login screen.

Two examples are "ca" and "re". I noticed this issue as one of my entries is Cashrewards and so to search for it I typed ca, which crashed it, so I tried re, which crashed it as well. I've come across other 2 letter things that crash it as well, but can't remember them at the moment. 

As soon as ca or re are typed into the search, it crashes without allowing you to type any more or press enter.

Interestingly, having a letter before the ca or re, such as hca or hre doesn't cause a crash.

Running on a Oneplus 3 on Android 8.0.0.

Thanks for the fantastic app, I use it on a daily basis and love it!

**Comment by BradleyDS2** [comment]
I activated logging, searched for ca, searched for re, searched for hre, accidentally tapped an entry, backed out of the app accidentally, disabled logging and copied the log below:


27/06/2018 4:26:55 PM:914 -- Creating application keepass2android.keepass2android. Version=119
27/06/2018 4:26:56 PM:143 -- PasswordActivity.OnCreate
27/06/2018 4:26:56 PM:149 -- PasswordActivity:apptask=
27/06/2018 4:26:56 PM:173 -- Loaded task keepass2android.NullTask
27/06/2018 4:26:56 PM:946 -- PasswordActivity.OnStart
27/06/2018 4:26:56 PM:974 -- PasswordActivity.OnActivityResult Canceled/0
27/06/2018 4:26:56 PM:975 -- TryGetFromActivityResult: no data
27/06/2018 4:26:56 PM:981 -- PasswordActivity.OnResume
27/06/2018 4:26:56 PM:983 --  DatabaseIsUnlocked=False
27/06/2018 4:26:56 PM:987 -- starting: True, Finishing: False, _performingLoad: False
27/06/2018 4:26:57 PM:51 -- Pre-loading database file starting
27/06/2018 4:26:57 PM:60 -- PasswordActivity.OnPause
27/06/2018 4:26:57 PM:70 -- CFS: OpenWhenNoLocalChanges
27/06/2018 4:26:57 PM:72 -- CFS: hashing cached version
27/06/2018 4:26:57 PM:323 -- PasswordActivity.OnResume
27/06/2018 4:26:57 PM:324 --  DatabaseIsUnlocked=False
27/06/2018 4:26:57 PM:327 -- starting: False, Finishing: False, _performingLoad: False
27/06/2018 4:26:57 PM:354 -- FP: Create FingerprintDecryption
27/06/2018 4:26:57 PM:370 -- FP: Init for Dec
27/06/2018 4:26:57 PM:419 -- FP: StartListening 
27/06/2018 4:26:58 PM:295 -- CFS: Files in Sync
27/06/2018 4:26:58 PM:307 -- Pre-loading database file completed
27/06/2018 4:26:58 PM:350 -- FP: OnAuthenticationSucceeded 
27/06/2018 4:26:58 PM:351 -- FP: StopListening 
27/06/2018 4:26:58 PM:357 -- FP: Decrypting 
27/06/2018 4:26:58 PM:904 -- PasswordActivity.OnActivityResult 874348/1000
27/06/2018 4:26:58 PM:905 -- No AppTask in OnActivityResult
27/06/2018 4:26:59 PM:834 -- ReadXmlStreamed: 517ms
27/06/2018 4:26:59 PM:965 -- LoadDB OK
27/06/2018 4:26:59 PM:973 -- Starting/Updating OngoingNotificationsService. Database Unlocked
27/06/2018 4:27:00 PM:252 -- PasswordActivity.OnPause
27/06/2018 4:27:00 PM:255 -- Timeout start
27/06/2018 4:27:00 PM:299 -- GroupActivity.OnCreate
27/06/2018 4:27:00 PM:299 -- GroupActivity:apptask=
27/06/2018 4:27:00 PM:305 -- Loaded task keepass2android.NullTask
27/06/2018 4:27:00 PM:443 -- GroupActivity.OnStart
27/06/2018 4:27:00 PM:448 -- GroupActivity.OnResume
27/06/2018 4:27:00 PM:449 --  DatabaseIsUnlocked=True
27/06/2018 4:27:00 PM:450 -- Timeout cancel
27/06/2018 4:27:01 PM:119 -- PasswordActivity.OnStop
27/06/2018 4:27:05 PM:205 -- Creating application keepass2android.keepass2android. Version=119
27/06/2018 4:27:05 PM:406 -- PasswordActivity.OnCreate
27/06/2018 4:27:05 PM:412 -- PasswordActivity:apptask=
27/06/2018 4:27:05 PM:432 -- Loaded task keepass2android.NullTask
27/06/2018 4:27:06 PM:131 -- PasswordActivity.OnStart
27/06/2018 4:27:06 PM:157 -- PasswordActivity.OnActivityResult Canceled/0
27/06/2018 4:27:06 PM:159 -- TryGetFromActivityResult: no data
27/06/2018 4:27:06 PM:164 -- PasswordActivity.OnResume
27/06/2018 4:27:06 PM:165 --  DatabaseIsUnlocked=False
27/06/2018 4:27:06 PM:169 -- starting: True, Finishing: False, _performingLoad: False
27/06/2018 4:27:06 PM:239 -- PasswordActivity.OnPause
27/06/2018 4:27:06 PM:240 -- Pre-loading database file starting
27/06/2018 4:27:06 PM:257 -- CFS: OpenWhenNoLocalChanges
27/06/2018 4:27:06 PM:259 -- CFS: hashing cached version
27/06/2018 4:27:06 PM:415 -- PasswordActivity.OnResume
27/06/2018 4:27:06 PM:416 --  DatabaseIsUnlocked=False
27/06/2018 4:27:06 PM:417 -- starting: False, Finishing: False, _performingLoad: False
27/06/2018 4:27:06 PM:439 -- FP: Create FingerprintDecryption
27/06/2018 4:27:06 PM:455 -- FP: Init for Dec
27/06/2018 4:27:06 PM:498 -- FP: StartListening 
27/06/2018 4:27:07 PM:500 -- CFS: Files in Sync
27/06/2018 4:27:07 PM:510 -- Pre-loading database file completed
27/06/2018 4:27:07 PM:546 -- FP: OnAuthenticationSucceeded 
27/06/2018 4:27:07 PM:547 -- FP: StopListening 
27/06/2018 4:27:07 PM:552 -- FP: Decrypting 
27/06/2018 4:27:08 PM:111 -- PasswordActivity.OnActivityResult 874348/1000
27/06/2018 4:27:08 PM:112 -- No AppTask in OnActivityResult
27/06/2018 4:27:09 PM:43 -- ReadXmlStreamed: 531ms
27/06/2018 4:27:09 PM:158 -- LoadDB OK
27/06/2018 4:27:09 PM:167 -- Starting/Updating OngoingNotificationsService. Database Unlocked
27/06/2018 4:27:09 PM:442 -- PasswordActivity.OnPause
27/06/2018 4:27:09 PM:446 -- Timeout start
27/06/2018 4:27:09 PM:490 -- GroupActivity.OnCreate
27/06/2018 4:27:09 PM:490 -- GroupActivity:apptask=
27/06/2018 4:27:09 PM:497 -- Loaded task keepass2android.NullTask
27/06/2018 4:27:09 PM:634 -- GroupActivity.OnStart
27/06/2018 4:27:09 PM:639 -- GroupActivity.OnResume
27/06/2018 4:27:09 PM:639 --  DatabaseIsUnlocked=True
27/06/2018 4:27:09 PM:641 -- Timeout cancel
27/06/2018 4:27:10 PM:289 -- PasswordActivity.OnStop
27/06/2018 4:27:14 PM:514 -- GroupActivity.OnPause
27/06/2018 4:27:14 PM:515 -- Timeout start
27/06/2018 4:27:14 PM:536 -- GroupActivity.OnCreate
27/06/2018 4:27:14 PM:537 -- GroupActivity:apptask=
27/06/2018 4:27:14 PM:540 -- Loaded task keepass2android.NullTask
27/06/2018 4:27:14 PM:575 -- GroupActivity.OnStart
27/06/2018 4:27:14 PM:577 -- GroupActivity.OnResume
27/06/2018 4:27:14 PM:577 --  DatabaseIsUnlocked=True
27/06/2018 4:27:14 PM:578 -- Timeout cancel
27/06/2018 4:27:15 PM:86 -- GroupActivity.OnStop
27/06/2018 4:27:16 PM:287 -- GroupActivity.OnPause
27/06/2018 4:27:16 PM:289 -- Timeout start
27/06/2018 4:27:16 PM:309 -- AppTask keepass2android.NullTask in OnActivityResult
27/06/2018 4:27:16 PM:312 -- GroupActivity.OnStart
27/06/2018 4:27:16 PM:315 -- GroupActivity.OnResume
27/06/2018 4:27:16 PM:315 --  DatabaseIsUnlocked=True
27/06/2018 4:27:16 PM:316 -- Timeout cancel
27/06/2018 4:27:16 PM:650 -- GroupActivity.OnStop
27/06/2018 4:27:16 PM:658 -- GroupActivity.OnDestroyTrue
27/06/2018 4:27:19 PM:167 -- GroupActivity.OnPause
27/06/2018 4:27:19 PM:170 -- Timeout start
27/06/2018 4:27:19 PM:187 -- PasswordActivity.OnActivityResult FirstUser/0
27/06/2018 4:27:19 PM:188 -- AppTask keepass2android.NullTask in OnActivityResult
27/06/2018 4:27:19 PM:191 -- Locking database
27/06/2018 4:27:19 PM:220 -- OngoingNotificationsService.OnDestroy
27/06/2018 4:27:19 PM:228 -- Finishing md5f0702f468598c68ce18586502249fb40.GroupActivity due to database lock
27/06/2018 4:27:19 PM:668 -- PasswordActivity.OnDestroyTrue
27/06/2018 4:27:19 PM:760 -- GroupActivity.OnStop
27/06/2018 4:27:19 PM:763 -- GroupActivity.OnDestroyTrue
27/06/2018 4:27:20 PM:356 -- KeePass.OnCreate
27/06/2018 4:27:20 PM:357 -- KeePass:apptask=
27/06/2018 4:27:20 PM:359 -- Loaded task keepass2android.NullTask
27/06/2018 4:27:20 PM:360 -- KeePass.OnCreate
27/06/2018 4:27:20 PM:373 -- KeePass.OnStart
27/06/2018 4:27:20 PM:374 -- KeePass.OnStart
27/06/2018 4:27:20 PM:421 -- FileSelect.OnCreate
27/06/2018 4:27:20 PM:421 -- FileSelect:apptask=NullTask
27/06/2018 4:27:20 PM:423 -- Loaded task keepass2android.NullTask
27/06/2018 4:27:20 PM:474 -- FileSelect.OnStart
27/06/2018 4:27:20 PM:512 -- PasswordActivity.OnCreate
27/06/2018 4:27:20 PM:513 -- PasswordActivity:apptask=
27/06/2018 4:27:20 PM:515 -- Loaded task keepass2android.NullTask
27/06/2018 4:27:20 PM:576 -- PasswordActivity.OnStart
27/06/2018 4:27:20 PM:579 -- PasswordActivity.OnResume
27/06/2018 4:27:20 PM:580 --  DatabaseIsUnlocked=False
27/06/2018 4:27:20 PM:581 -- starting: True, Finishing: False, _performingLoad: False
27/06/2018 4:27:20 PM:584 -- Pre-loading database file starting
27/06/2018 4:27:20 PM:586 -- CFS: OpenWhenNoLocalChanges
27/06/2018 4:27:20 PM:586 -- CFS: hashing cached version
27/06/2018 4:27:20 PM:597 -- PasswordActivity.OnPause
27/06/2018 4:27:20 PM:700 -- PasswordActivity.OnResume
27/06/2018 4:27:20 PM:701 --  DatabaseIsUnlocked=False
27/06/2018 4:27:20 PM:702 -- starting: False, Finishing: False, _performingLoad: False
27/06/2018 4:27:20 PM:708 -- FP: Create FingerprintDecryption
27/06/2018 4:27:20 PM:710 -- FP: Init for Dec
27/06/2018 4:27:20 PM:734 -- FP: StartListening 
27/06/2018 4:27:20 PM:792 -- FileSelect.OnStop
27/06/2018 4:27:20 PM:890 -- FileSelect.OnDestroyTrue
27/06/2018 4:27:20 PM:898 -- KeePass.OnStop
27/06/2018 4:27:20 PM:900 -- KeePass.OnDestroyTrue
27/06/2018 4:27:20 PM:901 -- KeePass.OnDestroyTrue
27/06/2018 4:27:22 PM:132 -- CFS: Files in Sync
27/06/2018 4:27:22 PM:134 -- Pre-loading database file completed
27/06/2018 4:27:22 PM:406 -- FP: OnAuthenticationSucceeded 
27/06/2018 4:27:22 PM:407 -- FP: StopListening 
27/06/2018 4:27:22 PM:409 -- FP: Decrypting 
27/06/2018 4:27:22 PM:964 -- PasswordActivity.OnActivityResult 874348/1000
27/06/2018 4:27:22 PM:967 -- No AppTask in OnActivityResult
27/06/2018 4:27:23 PM:303 -- ReadXmlStreamed: 263ms
27/06/2018 4:27:23 PM:333 -- LoadDB OK
27/06/2018 4:27:23 PM:344 -- Starting/Updating OngoingNotificationsService. Database Unlocked
27/06/2018 4:27:23 PM:494 -- PasswordActivity.OnPause
27/06/2018 4:27:23 PM:495 -- Timeout start
27/06/2018 4:27:23 PM:537 -- GroupActivity.OnCreate
27/06/2018 4:27:23 PM:538 -- GroupActivity:apptask=
27/06/2018 4:27:23 PM:542 -- Loaded task keepass2android.NullTask
27/06/2018 4:27:23 PM:581 -- GroupActivity.OnStart
27/06/2018 4:27:23 PM:583 -- GroupActivity.OnResume
27/06/2018 4:27:23 PM:584 --  DatabaseIsUnlocked=True
27/06/2018 4:27:23 PM:585 -- Timeout cancel
27/06/2018 4:27:24 PM:107 -- PasswordActivity.OnStop
27/06/2018 4:27:33 PM:338 -- GroupActivity.OnPause
27/06/2018 4:27:33 PM:339 -- Timeout start
27/06/2018 4:27:33 PM:361 -- DatabaseSettingsActivity.OnCreate
27/06/2018 4:27:33 PM:362 -- DatabaseSettingsActivity:apptask=
27/06/2018 4:27:33 PM:564 -- DatabaseSettingsActivity.OnStart
27/06/2018 4:27:33 PM:566 -- DatabaseSettingsActivity.OnResume
27/06/2018 4:27:33 PM:566 --  DatabaseIsUnlocked=True
27/06/2018 4:27:33 PM:567 -- Timeout cancel
27/06/2018 4:27:34 PM:2 -- GroupActivity.OnStop
27/06/2018 4:27:40 PM:705 -- DatabaseSettingsActivity.OnPause
27/06/2018 4:27:40 PM:707 -- Timeout start


Let me know if you need another log.

**Comment by PhilippC** [comment]
and you mean that crash occurred during logging? I don't see any exception (which I was expecting)?

**Comment by BradleyDS2** [comment]
Yep, crash occurred twice during logging.

Do you want me to do another log?

**Comment by PhilippC** [comment]
maybe you can collect a logcat. It seems like the built-in logging does not capture the crash.

**Comment by BradleyDS2** [comment]
Sorry about the delay. I tried doing as short a logcat as I could (started it just before typing ca and crashing) but it's still very long, I hope it has the information you need though.

[Here's the link to it](https://paste.ee/p/y6mLS#AlS2rtVSZOCO2q4EX3yCfTuTJf1TRW7A), I thought pasting 2000 lines here might not be a good idea.

**Comment by PhilippC** [comment]
seems like the app crashes when copying the entry image for some images. Should be fixed in the next release. Thanks for providing the log!

**Comment by BradleyDS2** [comment]
Awesome, thanks for the great work as always! I wasn't expecting a resolution so swiftly :)
