### ISSUE TITLE
Allow to disable AutoFill Service

### ISSUE THREAD

**Issue by finsterwalder** [PhilippC/keepass2android#430]
I enabled AutoFill on Android 8.
When I check the settings now I see it's enabled. Touching it doesn't do anything.
It would be nice if touching it would take me to the systems settings to disable it.

**Comment by Sinutok** [comment]
push.
Same Problem here (Oreo,K2A 1.05e)

**Comment by Small-Ku** [comment]
Would it duplicated with #253 ?
BTW, it is solved now. Could you close this issue?

**Comment by PhilippC** [comment]
duplicate of #253
