### ISSUE TITLE
Exporting databases has issues with special characters

### ISSUE THREAD

**Issue by tapiov** [PhilippC/keepass2android#437]
App encouraged me to backup my database, so I exported it in xml and csv. XML seems to have issues with (at least) & chars and CSV with commas (ofc). Am I doing this wrong or what's going on? Should the app have export to plain txt as well?

**Comment by tapiov** [comment]
Seems like my XML viewer had issues with &. In Emacs they are rendered as &amp, I guess that's OK. So the database should be able to recreate using the XML

**Comment by PhilippC** [comment]
Both & and , are working with XML and CSV. In CSV, this is handled by quoting each field.
