### ISSUE TITLE
Blocking on xiaomi

### ISSUE THREAD

**Issue by SavostinVladimir** [PhilippC/keepass2android#440]
Hi! Thanks for your project. Could you add blocking the app, when i click home button.
Thone Xiaomi redmi note 3

**Comment by PhilippC** [comment]
what do you mean with "blocking the app"?

**Comment by SavostinVladimir** [comment]
I mean it`s needed to provide password or fingerprint again, when I leave the app through the home button and return to the app then.

**Comment by PhilippC** [comment]
there are also several options in app settings -> security, e.g. lock database on leaving and the app timeout, this should be sufficient.
