### ISSUE TITLE
"work offline" checkbox missing - db cannot be opened anymore

### ISSUE THREAD

**Issue by fichtennadel** [PhilippC/keepass2android#442]
Unfortunately the last update seemed to have removed the "work offline" checkbox and now I can't open the database anymore when I'm out of my home network (db is sftp@privatenas).

Error message: java.net.ConnectException: failed to connect to /<ip> (port 22) ...

Please bring back this option, the current version is unusable for me.

**Comment by fichtennadel** [comment]
I've been checking now being back in the home network and having the sftp host available: database can be opened online.

After closing the db and going offline again, the "work offline" checkbox is now back!

I guess this could be related to the update, seems it requires to have the db file available when opening the app the first time after the update.

**Comment by fichtennadel** [comment]
Happened again, suddenly offline mode wasn't available anymore (no upgrade):
![image](https://user-images.githubusercontent.com/2324670/42435612-6032fa3a-8357-11e8-9c56-9989c350d874.png)

I had to restart KP2A several times being online the get the DB opened again.
Please have look at this, KP2A is currently not usable being offline in a reliable way.

**Comment by PhilippC** [comment]
I guess the simple explanation is this: For some reason, during the update, Android clear the app's cache data and thus also the local cache copy of the database. If no cached copy is available, the option is not displayed. When opening while being "online", the cache was restored and the option was back again. 
BTW with the new "local backup" you are also able to open even if the cache gets cleared, because that Local Backup is stored in a more persistent directory.
Please re-open the issue if the explanation is not sufficient for you.

**Comment by fichtennadel** [comment]
I don't think so:

1. if the app cache data would have been cleared, the filename and all the settings would also have been lost, which wasn't th case
2. the problem ocuurred twice: first after upgrade (my first post) but then today with no upgrade whatsoever (third post)
3. "local backup" is active in settings, still didn't work. Or do I have to use/open the backup DB explicitly? If yes, how to?

(PS: thanks for this app and enjoy your beer)

**Comment by PhilippC** [comment]
1./2.) it is possible for Android to clear the cache directory of an app (without clearing the settings). However I agree that this is not too likely to happen twice. Or do you have any somewhat aggressive memory settings or are low on memory?
3.) To open a local backup, go to the list of recent files (click Change database on the password screen) and then select the local backup.

**Comment by fichtennadel** [comment]
Following your hint on memory settings I think I found the trigger: I have a Samsung S8 and the "device management feature" closes background apps. When I run this intentionally, the "work offline" checkbox in KP2A is removed until I successfully open it from remote again.

But why does closing the app in the background remove the "work offline" functionality?
