### ISSUE TITLE
Initial colon in locked notification

### ISSUE THREAD

**Issue by Michaelkielstra** [PhilippC/keepass2android#446]
The persistent "database locked" notification had a strange initial colon, as seen in the attached screenshot.
![_20180706_081019](https://user-images.githubusercontent.com/4313413/42364868-9cec2204-80f4-11e8-8492-b4503f089c68.JPG)

**Comment by PhilippC** [comment]
in front of the colon, there should be either the database name or the the file name. Can you please send a screenshot of your "recent files" list or the unlock screen which should show the file path?

**Comment by Michaelkielstra** [comment]
![img_20180709_094711](https://user-images.githubusercontent.com/4313413/42440281-32cf03ee-835d-11e8-92a5-54f5e0b35af0.jpg)
I'm using a local file as my database, if that helps.
