### ISSUE TITLE
Synchronization fails when opening keepass sometimes

### ISSUE THREAD

**Issue by josefwells** [PhilippC/keepass2android#45]
When my phone holds keepass in memory, it opens to the 'Unlock database' page, I then get a message that it failed to synchronize the kdbx file (from cloud).

"Could not open from remote: .... looks like XXX not set up...."  something like that.

If I back out and go to the main Keepass2Android page, and select the database from the 'recent' list, it works every time.
"Remote File and Cache are synchronized."

Can this be fixed?  Maybe force to the Keepass2Android page instead of Unlock database?

**Comment by PhilippC** [comment]
Can you please try to collect logging regarding this? You can try to create an empty file /mnt/sdcard/keepass2android.cloud.log (e.g. with ES File Explorer) and see if this gets filled. If it is, that's nice. If not, please collect a logcat. The most relevant tag ist KP2AJ, but you might include KP2A as well. thanks.

**Comment by josefwells** [comment]
Sorry for the delay.  I didn't get anything in the /mnt/sdcard/keepass2android.cloud.log file, it just stayed empty.  I collected a logcat, and redacted my username, is there anything else I should be concerned with there?  There seems to be a hash of some sort after filenames/dirnames via gdrive.. just making sure that isn't some serious Auth key..
gdrive://.U8-<EMAIL>/.U8-<PATH>-<HASH>-<HASH>/<FILE>-<HASH>-<HASH>

**Comment by josefwells** [comment]
Ok, I just REDACTED out the hashes that made me nervous...
[kp2a_logcat.txt](https://github.com/PhilippC/keepass2android/files/1447144/kp2a_logcat.txt)

**Comment by PhilippC** [comment]
@josefwells I just tried to fix this, but I am not totally sure what's happening. The point is that Google Drive needs some initialization process, but that is not triggered. It should be triggered from the "FileSelectActivity" (where you choose the file from the recents list), but according to your log, that activity never was started. Can you tell me how you manage to go to PasswordActivity without going to FileSelect first?

**Comment by josefwells** [comment]
I don't know.  If I pick the gdrive database, then unlock, everything works.  Then if I just hit back, (I have "Lock when leaving app" set), I exit the program, but reopening it takes me straight to the Unlock screen, not database selection.  I'm on Android 8.0 now, same behavior with 7.1  previously.
It is much harder to do now, not sure why.  It did this when I just tried it, but trying no >10 times, I never got it to happen again.

Only by opening the database, hitting the home button, waiting for the database lock timeout to hit, then opening the app again do I get to the Unlock screen, but even then, I get that Remote and Local are synchronized.

I am also less convinced now that there is ever a problem with what happens anyway, I might get the error, but then after unlocking the database, I get the message that they are synchronized.. not sure if this was always the case, but I have seen it a few times now.

I have work-offline enabled as well, maybe there is an interaction in that code and my network has small windows of seeming inaccessibility?

**Comment by PhilippC** [comment]
closing this for now as it seems not reproducible at the moment. Please re-open if you find how to reproduce the issue.
