### ISSUE TITLE
Better place to store key files (enhancement request)

### ISSUE THREAD

**Issue by jbash** [PhilippC/keepass2android#451]
As far as I can tell, at the moment I can store my key file either on some inconvenient and hard-to-secure cloud service... or in a file on the Android "slush" storage that can be accessed by any of roughly ten billion different apps with "storage and media" permission. The "file picker" doesn't let me go anywhere else.

I would like an option for the Keepass2android app to store a key file in its own private filesystem space, where the OS will make at least some attempt to keep other apps from reading it.

**Comment by PhilippC** [comment]
settings -> database settings -> Import key file to internal folder
