### ISSUE TITLE
Keyboard Enhancements

### ISSUE THREAD

**Issue by carstengrimm** [PhilippC/keepass2android#453]
I have been wondering about the keepass2android keyboard.

It shows a dictionary for englisch, but it seems like i can't add a dictionary for all other languages such as german which kinda makes auto complete useless. Is there some way to add other dictionaries?

Also i'd love to see any sort of swiping method to type as i have been used to it and most major keyboard applications have transitioned or added similar features.

Anyhow I'd love to replace keepass2android keyboard as the main keyboard, but i am unable to do so with both "flaws" above. I'd love to hear suggestions if there's anything i can do. Is keepass2android even intended to replace the main keyboard or solely with the swapping purpose of getting passwords and other data into fields?

**Comment by PhilippC** [comment]
No, KP2A's keybord s not intended as a replacement for other keyboards. This would be a whole new development effort. Anyway, you can install other languages in the dictionary (https://github.com/PhilippC/keepass2android/blob/master/docs/Advanced-usage-of-the-Keepass2Android-keyboard.md).
I still suggest to only use it for inputting passwords, mainly using the two special "Username" and "Passwords" buttons.
