### ISSUE TITLE
[Request] Password + Key file + Challenge-Response

### ISSUE THREAD

**Issue by JohnBeres1** [PhilippC/keepass2android#456]
Hello ^_^

I started a conversion from LastPass --> KeepassXC and setup my database with a password, keyfile, and a challenge-response via a YubiKey. When I got Keepass2Android I noticed these options are all there... just not together. 

I commented on the Google Play store and the devloper said it is currently not supported but I could request this feature here.

Can I keep hopes this is an easy/quick implementation? Does adding this suddenly complicate the authentication process ten-fold? I'll keep my fingers crossed! Stay classy :)

Kindly,
Fellow Security Nut

**Comment by vronp** [comment]
Hi,

I am looking for the exact same setup.  I just started converting from LastPass to KeePassXC.  I use a Yubikey Neo and was hoping to be able to use the Neo with keepass2android as well.  I am just now researching the best way to sync the database between KeePassXC and keepass2android and I welcome any suggestions.

Also, my kdbx is at v4 on KeePassXC.  This doesn't seem to be supported on keepass2android.

thanks,
Dave

**Comment by vronp** [comment]
I'm sorry, my mistake.  I misinterpreted something I read on Google Play.

Thank you for the reply.

**Comment by k8oi** [comment]
For those of us who are paranoid, this is a great feature request.

Thank you for considering it!

**Comment by macearl** [comment]
@PhilippC Not sure if i'm doing something wrong but i cant select the option to use a password + keyfile + challenge response.

I only see the first 7 options, the 8 option should then be to use all 3? Is there anything i need to setup first for the option to show up.

Im using 1.06f (tried both the normal and the offline version) found under releases here on github
