### ISSUE TITLE
Guide users to regularly create database backups

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#46]
Users should be notified after making some changes to their database that they should ensure they have an up-to-data backup

**Comment by Safari77** [comment]
Are the databases included in Android Device Backup (App data)?
For example ```/storage/emulated/0/Android/data/keepass2android.keepass2android/files/keepass.kdbx```

**Comment by PhilippC** [comment]
@Safari77 no they are not (for privacy reasons)

**Comment by cawoodm** [comment]
So where are the files? Users are told it is their responsibility to back them up but no guidance is given on where to find the files.

**Comment by Safari77** [comment]
I backup like this.
```
alias k2a='adpull /sdcard/Android/data/keepass2android.keepass2android/files/keepass.kdbx ~/Documents/k2a/keepass.$(date +%s).kdbx'
alias adpull='adb -s model:ONEPLUS_A3003 pull'
```

In this example I use adb to transfer files from my Oneplus 3 phone to ```~/Documents/k2a```.

**Comment by PhilippC** [comment]
@cawoodm another option is simply to regular click settings - database settings - "Export database" and choose a location which is either a backup location (e.g. a removable USB device) or from which you can move/copy the exported data to a backup media.

**Comment by GraphiteWingedBird** [comment]
@PhilippC  - I'm not sure if this is the right place to start, but need to start somewhere. Do you have any tips on getting started with creating a Plugin for the app? I'd like to work on a plugin that will automatically create a backup when you open a database or when you close it/synchronize it. I'm working on downloading the right Java/C# 'stuff' and going to give it a go teaching myself, but any advice you have would be helpful. At the end of the day, I'd like to create my own plugin that basically calls into the "Export Database" functionality that exists. Here's a related question/functionality request (I think): [https://github.com/PhilippC/keepass2android/issues/176](https://github.com/PhilippC/keepass2android/issues/176)

**Comment by PhilippC** [comment]
@GraphiteWingedBird I don't think the Plugin API would allow to do that, but feel free to submit a pull request

**Comment by GraphiteWingedBird** [comment]
Honestly - I think I'll have more luck figuring out Java and Mono than I will figuring out how to create a pull request. I'm presuming that if I give creating a pull request the ol' college try, someone can help make sure it is in the correct branch(es)? I'd love to work on this myself, but like I mentioned I don't have any background on apps or plugins so it is slower going getting started
