### ISSUE TITLE
Unable to share database file between two OneDrive accounts

### ISSUE THREAD

**Issue by klzig** [PhilippC/keepass2android#463]
1) user_a creates Passwords directory on OneDrive, adds database file to it

2) user_a shares Passwords directory with user_b, granting edit privilege

3) using the OneDrive app on Android 7.1, user_b "Adds to my OneDrive" the Passwords directory shared to her

4) user_b opens keepass2android for the first time, Open file>OneDrive>navigate to Passwords directory

Expected behavior:  database shows up in pick list
Actual behavior: Passwords directory shows "Empty"

Notes:
* user_b can see the database file in the Passwords directory using the OneDrive app on the phone.
* user_a can successfully connect to the shared database on Android 8.0 phone using the steps outlined above, except without the "Add to my OneDrive" step (user_a is the owner of the folder)

**Comment by dschuesae** [comment]
Mentioned the same a year ago or so, but it isn't available anymore.

**Comment by pddulfer** [comment]
I have exactly the same problem. Hoping there is a solution - I have been a very happy user of this app for some time and recently switched from syncing via Dropbox to use OneDrive instead.

**Comment by dschuesae** [comment]
As a workaround I use dropbox for only this file.

**Comment by pddulfer** [comment]
Thanks for the reply.

That was fine until recently, when Dropbox limited their free version to sync with only 3 devices. Hence my migration to OneDrive as I'm already paying for an Office 365 subscription.

It was all going very well until this little issue trying to use a shared OneDrive folder. I've worked around it by syncing the other person's device to my OneDrive rather than using a shared folder but that's not ideal either.

**Comment by PhilippC** [comment]
This is fixed now. Please switch to beta and install 1.07b-pre2 (just published to beta, see https://play.google.com/apps/testing/keepass2android.keepass2android). Please click "Change database" (on the password screen), then "Open database", "One Drive", "All files and shared files" (or something else if appropriate) and browse to your file again. This will then use the new implementation. (If you don't re-open the database like this, the old implementation will be used).
Please re-open (or comment) if the issue persists for some reason.
