### ISSUE TITLE
App crashes on DB open

### ISSUE THREAD

**Issue by Skuriles** [PhilippC/keepass2android#470]
Hello,
I've updated to Android 8 and now the app crashes when I try to open a Google Drive Database.
I enter the password, DB is loading, then "App stopped working"...
Tried it several times. Didn't work.
Can I create a Dump file or something to provide more information about the crash?
I've downloaded the tombstone and anr folder, but can't find a real hint about the crash.

**Comment by schlimmchen** [comment]
Are you familiar with Android's logcat?

You could also enable writing a log file in the app settings and search that for hints.

**Comment by schlimmchen** [comment]
Do you have a fingerprint sensor on your device? Could your issue be related to #474?

**Comment by Skuriles** [comment]
Seems to be the same error..I have also an OPO with latest LineagOS and no Fingerprint Sensor.
So I will close this issue and subscribe to yours
