### ISSUE TITLE
AppCrash on DB Unlocked on device without fingerprint sensor

### ISSUE THREAD

**Issue by schlimmchen** [PhilippC/keepass2android#474]
I have a OnePlus One (bacon) here running LineageOS 15.1 20180702. After updating through the Market yesterday, the app crashes after unlocking the database.

Logcat strongly hints that this happens because the device has no fingerprint sensor.

[kp2a_logcat.txt](https://github.com/PhilippC/keepass2android/files/2229481/kp2a_logcat.txt)

EDIT: This happens in v1.06a. Reverted to v1.05e via apkmirror.com and did not experience this issue.

**Comment by Skuriles** [comment]
Same here

**Comment by samueltardieu** [comment]
It makes it impossible to open the database on Nexus 7 2013 (Wifi) as well.

**Comment by S-Bartfast** [comment]
Yup, same problem here on a Nokia 3.

Is there any workaround? The app is completely unusable now and I am restricted to only using Keepass on my PC.

**Comment by Skuriles** [comment]
Just leave Beta program and go back to 1.05 version. At least, this works  for em

**Comment by S-Bartfast** [comment]
Are, wonderful.

It actually took a bit more work than expected to resolve as it was actually a different account I have available on this device that had subscribed to the Beta but I got there in the end.

**Comment by Skuriles** [comment]
Yeah: I left Beta Program on a windows desktop browser, but was still there in Android Play Store. But in Play Store near the bottom of the page you can select "leave Beta program" than I could re-install the stable version 1.05
