### ISSUE TITLE
dropbox sync failing

### ISSUE THREAD

**Issue by psternak49** [PhilippC/keepass2android#477]
Had dropbox sync working but after latest update it no longer works. Moto G 6 play android 7, keepass2android 1.05e. 

When I open the dropbox file I am prompted to save it locally. I have tried both internal memory and external sd card locations. The saves are normal. Dialogue says remote and cache are synced. When I make a change to the file and then do a sync I get the message files are in sync. The dropbox location however is not getting the changes, timestamp on the database is unchanged and I have confirmed the changes are not there by opening the dropbox file on other keepass clients.

I have deleted the local file on the phone and re-downloaded a new copy but no change in behavior.

Now for the strange part. On a Nexus 7 tablet running android 6, same ver 1.05e, syncing is working.

There are errors in the debug log but I can't tell what they mean.

[keepass3.log](https://github.com/PhilippC/keepass2android/files/2239232/keepass3.log)

I have "closed" the databases after making changes, reopened and they tried a sync but message is files are in sync and nothing happens. Doesn't appear to be a dropbox permissions issue as syncing from the tablet and windows 10 desktop work. I am ensuring only 1 client is connected when doing a sync.

Suggestions?

Thank you,

**Comment by atroposfate** [comment]
I am having the same issue. I have clicked on dropbox and then log-in and I get the "allow" the API but then shows "Error Cannot cannot connect to file provider service". 
If I use the database link from the history dropbox:///XXXX/XXXX.kdbx I get "An error occurred: Exception of the type 'Java.lang.exception' was thrown"

Annoyingly any changes to the database on my phone is not being sent to the dropbox record so all other systems aren't getting the updates.

**Comment by psternak49** [comment]
Your issue sounds different. I can delete my local copy of the database, point the program to dropbox as a source and download a new copy from dropbox. I am told it has to be stored locally and when I do that I am told the remote and local files are in sync. If I make a change to the local database and then tell it to sync, I am told the files are synced. They aren't, and there are java errors in the debug log.

It is annoying I have to make database changes using a different platform and then redownload a fresh copy of the database to my phone. In my case, the problem is only happening on android 7. An android 6 tablet is working fine.

I have tried deleting the keepass2android cache, restarting the program and grabbing a fresh copy of the database but it hasn't helped.

**Comment by PhilippC** [comment]
Can you try if the same happens with another file?

**Comment by psternak49** [comment]
I have to apologize. I was cleaning up my device and deleted the wrong version of the program so was trying to use the stand alone version. Reloading the correct version solved my problem.

Sorry

**Comment by thopras** [comment]
I have the same problem. I opened the database directly from dropbox then added a new entry with the keepass2 Android app saved it synchronized it. Everything seems to be ok from Androip app but on dropbox there were no changes. 
If I take a look at my changes on the dropbox I see that only changes from PCs are done - no changes from Android. 
If you make any changes on Android it doesn't work if you change it on Windows it is synchronized to the Android app.
