### ISSUE TITLE
Keepass db won't open

### ISSUE THREAD

**Issue by otto426** [PhilippC/keepass2android#483]
Since the update to android 8.0 and Samsung experience 9.0 keepass2android 1.05e won't open the db. I enter my pw but the app has no response.  Everything works fine on the pc with the same shared db.

**Comment by ajbarth815** [comment]
+1.  app does open local readonly backup but that is sort of useless.  have tried the open new DB route and selected Google drive then my account.  from there nothing happens. Keepass on PC has Google sync plugin which appears to be working correctly.

**Comment by PhilippC** [comment]
can you please try if the steps described on https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254 fix the issue?

**Comment by ajbarth815** [comment]
thanks for responding. I got a security update just days after OS upgrade
and that required another phone reboot.  working fine since.

sent from my phone

**Comment by otto426** [comment]
I tried each step listed in thread $432 with no success.  Turns out, there is a check box to work offline at the bottom that checked itself on my and my father’s phones when the system updated and unchecking that allowed the database to open.  Thank you very much for the information and assistance.

Dan Ruegg
856.236.7689
