### ISSUE TITLE
Minor bug: Edit of Group title does not allow saving change

### ISSUE THREAD

**Issue by AlexaaGit** [PhilippC/keepass2android#484]
PhillippC,

Wanted to change the title of group on Offline app after selecting the pencil icon and making change selecting OK --- nothing is changed, nor indication that database has changed.  Not a major item I'm able to work around.  Have verified the behavior on a couple of different devices and OS versions.  Great App... Thanks!

**Comment by browntown52** [comment]
Same behaviors in online mode with samsung galaxy tablet s3.   App Version 1.05e

**Comment by michelepetito** [comment]
Same behaviors with samsung galaxy s8. App Version 1.05e. I have also disabled the cache but the problem persists.

**Comment by PhilippC** [comment]
duplicate of https://github.com/PhilippC/keepass2android/issues/434
