### ISSUE TITLE
Keepass2Android Keyboard does not recognize page in Chrome

### ISSUE THREAD

**Issue by Kroesss** [PhilippC/keepass2android#485]
I am running Keepass2Android, the offline-version. All is good, except that the keyboard does not recognize the url/page in Chrome. Instead, it gives me the option to search for an entry manually, or let it search for "com.android.chrome". Also in other applications I get these kind of predefined search-options, but I don't have to log in as much in those, so there it is not a problem for me..

I don't know if it is intended to work that way, but I would assume it would search for some part of the url, or perhaps title?

**Comment by Karreg** [comment]
This is how it works. If you want to search for your URL, you have to do this:

in Chrome -> menu -> share -> share to keepass -> unlock your database if it's locked.
Then the entry is selected and you're back to your webpage with the credentials...

**Comment by Kroesss** [comment]
@Karreg  Thanks! Taht works like a charm!
