### ISSUE TITLE
Autofill Framework always asks to save passwords

### ISSUE THREAD

**Issue by SciLor** [PhilippC/keepass2android#488]
I have several apps that I open with my fingerprint or where I don't won't to drop the password in KeePass.
But on oreo it always asks to save it after I entered it. Any option to deactivated it?

**Comment by thousandsofthem** [comment]
"never" option for specific app would solve the issue.
Means app could locally store list of app ids with autofill disabled

**Comment by telmer6** [comment]
The "NO THANKS" button should set a persistent flag per application, rather than just dismissing the prompt.

**Comment by SciLor** [comment]
> The "NO THANKS" button should set a persistent flag per application, rather than just dismissing the prompt.

I don't think so. This wouldn't be transparent to the user. There is another button needed for that.

**Comment by telmer6** [comment]
That's reasonable. Maybe change "NO THANKS" to "NOT THIS TIME" and add a "NEVER"? 

My issue is that I expected this functionality to exist, and the "NO THANKS" button seemed to be how it would be accessed.

**Comment by syldub69** [comment]
I would love to have an option which allows Keepass2Android to never ask to save password!!!
The database I use on my smartphone is just a synchronized copy of a master version located in the Cloud, so I never have to update my local Keepass database on my smartphone.
Look at these screenshots taken in Lydia and DS File:
![screenshot_2018-11-13-23-07-19-323_com synology dsfile](https://user-images.githubusercontent.com/16567425/48561679-c8980080-e8f0-11e8-98b8-f6abb27f0947.png)
![screenshot_2018-11-13-20-02-49-750_com lydia](https://user-images.githubusercontent.com/16567425/48561703-d483c280-e8f0-11e8-9894-40f261cb4ab5.png)

**Comment by dasgrischa** [comment]
> 
> 
> The "NO THANKS" button should set a persistent flag per application, rather than just dismissing the prompt.

Where is the "NO THANKS" button. I can't see it anywhere? 

This is how it looks for me and I really need to disable this pop-up :S 
![screenshot_20190307-123821](https://user-images.githubusercontent.com/48331536/53986331-2f4e5d80-411e-11e9-8336-14ada6768590.jpg)

**Comment by dasgrischa** [comment]
> 
> 
> "never" option for specific app would solve the issue.
> Means app could locally store list of app ids with autofill disabled

Where is this "never" option? 

I really want to disable this pop-up.
![screenshot_20190307-123821](https://user-images.githubusercontent.com/48331536/53986451-87855f80-411e-11e9-9874-50c6e26496b3.jpg)

**Comment by telmer6** [comment]
@dasgrischa The "never" option does not exist at this point in time. 

Additionally, this issue pertains to the dialog for saving entered credentials, not the autofill popup seen in your screenshot. I would suggest that you create a separate issue in regards to disabling autofill for specific applications.

**Comment by dasgrischa** [comment]
> 
> 
> @dasgrischa The "never" option does not exist at this point in time.
> 
> Additionally, this issue pertains to the dialog for saving entered credentials, not the autofill popup seen in your screenshot. I would suggest that you create a separate issue in regards to disabling autofill for specific applications.

Alright, thanks. :)
