### ISSUE TITLE
Keyboard input is accepted while unlocking with fingerprint

### ISSUE THREAD

**Issue by BradleyDS2** [PhilippC/keepass2android#493]
Hi, sorry if the title doesn't explain the issue well, I'll try to explain it properly.

When fingerprint unlock is enabled, you can scan your fingerprint, and before it unlocks you can type on the keyboard, causing the password that was entered automatically from scanning your fingerprint to have a letter or two added, making it incorrect and automatically disabling fingerprint login even though the fingerprint was correct.

I have a Oneplus 3, the fingerprint scanner is on the home button and I've accidentally touched the space bar on my keyboard a few times, causing me to need to enter my password manually, go into the settings and reenable fingerprint unlock.

Also, while not completely related, would it be possible to have the number of fingerprint attempts be adjustable in the settings, or if you fail the fingerprint scan and it disables the fingerprint scanning automatically, next time you unlock with your password it either has a message down the bottom asking if you want to reenable fingerprint login with yes/no options, or renables it automatically after a successful unlock without asking (maybe an option in the settings to disable this as well).

If there's anything I said that I need to rephrase, please let me know. 

Thank you for your time, and I appreciate your hard work on this wonderful app.

**Comment by PhilippC** [comment]
trying to reproduce this but I can't: after the password is inserted, I immediately see the "Loading" dialog which prevents keyboard input. Can you be a bit more specific when exactly you can modify the password?

**Comment by BradleyDS2** [comment]
Yep, sorry for the lack of clarity.

It's just after scanning the fingerprint, there's a split second before the loading pop-up appears that disables keyboard input.

I'm using a OP3 so I'm fairly certain it's not due to device lag. I'm using fingerprint for full unlock and loading the password database from Dropbox. I'm running Android Oreo.



Since you said you couldn't reproduce it I just tried reproducing it deliberately and was able to by scanning my fingerprint and before the loading screen popped up typing on the keyboard, it failed to unlock about 75% of the time. After clicking OK on the "Unlocking the database failed" pop-up my password is correctly entered by my fingerprint but also has an extra letter or two from touching the keyboard and is viewable by clicking the show password button.
Removing the extra letter or two leaves my master password entered and able to unlock the database.


If it's easier to explain with a video I'll be happy to record my screen as I reproduce the issue.
