### ISSUE TITLE
What's about "keepass2ios"?

### ISSUE THREAD

**Issue by markusd112** [PhilippC/keepass2android#495]
I love keepass2android on my Android devices: it's a powerful and good working password manager.

There is no alternative like keepass2android on iOS plattform available... Minikeepass is not a really alternative, because it has no WebDAV-sync functionality.

What's about porting "keepass2android" to iOS? ("keepass2ios")

**Comment by PhilippC** [comment]
Keepass2Android is a hobby project and already takes lots of my time. I never did iOS development nor are Apple's Store restrictions compatible with GPLv3. I won't do this, sorry.

**Comment by WebworkrNet** [comment]
KeePassium is often recommended. 

I have not yet tested the open source app myself, as I do not currently use an Apple device.

https://keepassium.com
