### ISSUE TITLE
Search for login not opening in Android Pie

### ISSUE THREAD

**Issue by fantini29** [PhilippC/keepass2android#496]
After you switch to keepass keyboard I normally use the keepass key on the bottom left to open keepass and find the entry for the app. This had stopped working on Android Pie. If I long press the key it opens the keyboard settings or keyboard switch icons

**Comment by scwalla** [comment]
Confirm that I also have this problem on pixel 2 XL running android 9 Pie.

**Comment by PhilippC** [comment]
duplicate of https://github.com/PhilippC/keepass2android/issues/377
