### ISSUE TITLE
Full Fingerprint Option missing / not available on Samsung S5

### ISSUE THREAD

**Issue by TobiasKk** [PhilippC/keepass2android#498]
Hello,

on my wife's Samsung S5 only the option for Quickunlock with fingerprint is available. On my S7 there is also the option to fully unlock the database with the fingerprint and everything works fine. On the S5 it is not just greyed out, it is completly missing.

The S5 is running Android 6.0.1. The S7 is running 8.0.0.

Am I missing something or is this feature just noch available on Andoird 6.0.1?

I tried reinstalling the app, opened the database multiple times with the master passwaord, restarted the phone, disabled and enabled the Quickunlock with fingerprint option.

The scanner works, Quickunlock with fingerprint works, too.

Thanks for any help!

**Comment by PhilippC** [comment]
On the SGS5 the Android 6 Fingerprint API is not implemented. I have such a device as well, it can only use the Samsung Fingerprint API (which is not suitable for full unlock).
