### ISSUE TITLE
Webdav Yandex.disk issue

### ISSUE THREAD

**Issue by x-plood** [PhilippC/keepass2android#506]
I load database from my Yandex disk using webdav and all works fine. But if i add some changes in db and then try sync, kp2a say me a error.

15.08.2018 15:00:26:900 -- Write error: ssl=0xca228a00: I/O error during system call, Broken pipe
15.08.2018 15:00:29:836 -- GroupActivity.OnPause
15.08.2018 15:00:29:837 -- Timeout start
15.08.2018 15:00:29:874 -- DatabaseSettingsActivity.OnCreate
15.08.2018 15:00:29:874 -- DatabaseSettingsActivity:apptask=
15.08.2018 15:00:30:22 -- DatabaseSettingsActivity.OnStart
15.08.2018 15:00:30:27 -- DatabaseSettingsActivity.OnResume
15.08.2018 15:00:30:28 --  DatabaseIsUnlocked=True
15.08.2018 15:00:30:28 -- Timeout cancel
15.08.2018 15:00:30:384 -- GroupActivity.OnStop

How can i fix this problem?

**Comment by x-plood** [comment]
Nope, i tried on my home wi-fi, on my work wi-fi, 4g connection on my phone, unfortunately the result is the same. However, through other apps, the connection and synchronization work fine.

**Comment by kvanderkamp** [comment]
Similar error here using webdav (https) on a different storage provider.

`Write error: ssl=0x94027dc0: I/O error during system call, Broken pipe`

**Comment by Gigses** [comment]
Same problem with webdav (https) and Yandex.Disk.

**Comment by PhilippC** [comment]
is this related to 1.06f?

**Comment by progserega** [comment]
09.02.2019 10:43:53:75 -- Write error: ssl=0x89eabc40: I/O error during system call, Broken pipe
09.02.2019 10:43:59:596 -- GroupActivity.OnPause
09.02.2019 10:43:59:597 -- Timeout start
09.02.2019 10:43:59:635 -- DatabaseSettingsActivity.OnCreate
09.02.2019 10:43:59:636 -- DatabaseSettingsActivity:apptask=
09.02.2019 10:43:59:713 -- DatabaseSettingsActivity.OnStart
09.02.2019 10:43:59:714 -- DatabaseSettingsActivity.OnResume
09.02.2019 10:43:59:714 -- DatabaseIsUnlocked=True
09.02.2019 10:43:59:715 -- Timeout cancel
09.02.2019 10:44:00:239 -- GroupActivity.OnStop

**Comment by progserega** [comment]
Fix is clear app data, add webdav https  url again. And no more change keepass db on phone. :-/

**Comment by jzyken** [comment]
1.07-pre5 issue is still alive =(

**Comment by PhilippC** [comment]
tried to reproduce this but even failed to login with webdav, I get 401 unauthorized. Is there anything to configure in Yandex to make webdav work? can I use the same user/password combination used to login to the yandex site?

**Comment by x-plood** [comment]
> tried to reproduce this but even failed to login with webdav, I get 401 unauthorized. Is there anything to configure in Yandex to make webdav work? can I use the same user/password combination used to login to the yandex site?

I use 2fa and i create separately password for program, also i use a https protocol to authorize. But login the same as the yandex site.

**Comment by PhilippC** [comment]
is https://webdav.yandex.com the right WebDav URL. I cannot connect through Windows Explorer either.

**Comment by Gigses** [comment]
> is https://webdav.yandex.com the right WebDav URL. I cannot connect through Windows Explorer either.

This way:
![image](https://user-images.githubusercontent.com/38125874/84647869-b8049d80-af0c-11ea-9624-74956d3b903d.png)

**Comment by jzyken** [comment]
Unfortunately Yandex is unofficially blocking file uploads using this protocol now.
https://ru.stackoverflow.com/questions/1043523/После-загрузки-файла-на-Яндекс-Диск-по-webdav-происходят-паузы-по-60-секунд-на-к
https://qna.habr.com/q/677787

**Comment by PhilippC** [comment]
sounds like this makes it impossible to support Yandex through webdav at the moment

**Comment by dartraiden** [comment]
It can be supported, but you need OAuth token
https://yandex.ru/dev/disk/doc/en/concepts/quickstart#quickstart__oauth
