### ISSUE TITLE
Unable to open database from online source

### ISSUE THREAD

**Issue by Ziggyshack** [PhilippC/keepass2android#507]
I have my keepass2android set up to use my fingerprint, and it connects to a copy of the database in a Dropbox folder. No issues until today, on my first attempt it didn't recognize my fingerprint, but when I tried my password I received an "Invalid composite key" error. I tried copying the database to Google Drive but get the same error. I can open the local copy on my phone with both the password and fingerprint, but can't add/modify it. I was able to open the database on my computer with the password last night, so the database itself should be good. The only thing that changed on my phone was the latest Sprint security update was installed yesterday afternoon, I don't think I tried accessing it between then and now.

**Comment by Ziggyshack** [comment]
To follow-up, I've tried all the steps in [this post](https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254) but none of them worked.

**Comment by Ziggyshack** [comment]
Found out I couldn't open it on my home computer either, but luckily I was able to pull the one from my backup which worked, and I was able to open it on my phone too. Still not sure what happened in the 5 hours since the backup, though the broken copy was 2 KB larger than the working one.

**Comment by PhilippC** [comment]
maybe you can take a look at the Dropbox history of the file to see which app/program made the "breaking change"?
