### ISSUE TITLE
feature request: support for pcloud

### ISSUE THREAD

**Issue by alpenblauwtje** [PhilippC/keepass2android#512]
Please add support for pcloud. Pcloud is the only cloudspace with proper Linux support after dropbox ditches support for encrpted ext4 fs in November.

**Comment by gilbsgilbs** [comment]
I'm also concerned by Dropbox dropping proper Linux support starting from November. PCloud sounds like a good alternative as their client supports two-ways synchronization on Linux (unlike GDrive, OneDrive and others).

@PhilippC Can you assign this issue to me please? I already have a working PCloud integration running locally. If you don't have anything against incorporating PCloud into Keepass2Android, I can definitely take some time to clean this up and submit a PR. Furthermore, their SDK is [licenced under Apache 2.0](https://github.com/pCloud/pcloud-sdk-java), so there should be no legal concerns. If you agree, may I kindly ask you to review [this PR](https://github.com/PhilippC/keepass2android/pull/522) first? I'd prefer avoiding conflicts.

Thanks.

**Comment by alpenblauwtje** [comment]
@gilbsgilbs Great work, thanks!!

**Comment by alpenblauwtje** [comment]
Only a few weeks left before Dropbox ditches encrypted ext4 support. When is keppass with pcloud support being released?

**Comment by gilbsgilbs** [comment]
@PhilippC, any chance you release 1.07 some days before the 7th of November? It would help us not getting into troubles with Dropbox and even give us some time to adapt our workflows. Thanks :raised_hands:!

**Comment by PhilippC** [comment]
sorry for the delay. I have been working on https://github.com/PhilippC/keepass2android/issues/174 recently and wanted to include this in the first 1.07 preview release. It still needs some testing but I plan to publish a version with pcloud support on beta channel during the next 2 weeks.

**Comment by gilbsgilbs** [comment]
That should do it. Thank you very much :) .

**Comment by alpenblauwtje** [comment]
Just tested the beta KP2A with pcloud support. If you have enabled 2-factor authentication, like I have, you can't login. The login screen shows a red 'Two factor authentication required' error and there is no way to proceed.

**Comment by gilbsgilbs** [comment]
@alpenblauwtje Thanks for testing this out. I can reproduce. I reckon it's PCloud's fault: 2FA tokens should be prompted in the webview during the login process and I don't think I can do anything to make PCloud ask for them. I must get in touch with them for confirmation though.

**Comment by gilbsgilbs** [comment]
@alpenblauwtje Yeah, they just replied to me and unfortunately the SDK (and their whole OAuth2 process I guess) isn't compatible with 2FA at the moment. There's nothing we can do except waiting they implement it, sorry. Your only chance is to disabled 2FA :-1: .

**Comment by jkt628** [comment]
any news on the preview release?  dropbox EOL coming soon.

**Comment by gilbsgilbs** [comment]
@jkt628 it's on the beta channel already.

**Comment by pbosio** [comment]
File chooser is empty (showing 'empty' string in the center of the screen) after I log in with my pcloud account (I don't have 2FA enabled)

**Comment by alpenblauwtje** [comment]
@gilbsgilbs Thanks for your quick response! I managed to get it working by disabling 2FA. Hopefully pCloud will fix this soon.
However I faced some issues while experimenting with a test database: new instances of the database are created every time I save it from Android. Say I have have a _test.kdbx_ database. When I create an entry in Android and save it, a new file called _test.kdbx (2)_ is created. When I save again then there is a _test.kdbx (3)_ file. When I explicitly open this file and save it there will be a _test.kdbx (3) (1)_ file. Could you look into this please?

**Comment by alpenblauwtje** [comment]
Oh one more thing: when opening an existing database (what most users will do that abandon Dropbox), there is no indication in which folder KP2A is looking on pCloud. If you create a new database you can see it is placed in _Applications/Keepass2Android_. It would be helpful if an indication of this folder could be given.

**Comment by gilbsgilbs** [comment]
@alpenblauwtje Apparently, PCloud SDK does not overwrite files when uploading (and it's probably a good idea to avoid corruptions). I have to find a way around this, shouldn't be too hard though. Thanks for the report.

> when opening an existing database (what most users will do that abandon Dropbox), there is no indication in which folder KP2A is looking on pCloud.

I did this on purpose, but you're right, something should be done to make things clearer. @PhilippC any idea how we could be more explicit?

**Comment by gilbsgilbs** [comment]
@alpenblauwtje I just pushed a fix FYI.

**Comment by PhilippC** [comment]
@gilbsgilbs I simple way would be to add a small explanation text, similar to that of "Dropbox (App Folder)": It is displayed when the user clicks the storage type, simply as a message. To add it, I think all we need to do is add a string named filestoragehelp_pclout in strings.xml. Do you think that's ok?

**Comment by gilbsgilbs** [comment]
I indeed think that would be enough. I won't be able to make a PR until I find some time to get the build working again (which may not happen anytime soon unfortunately).
