### ISSUE TITLE
Prompts hidden on Android Pie

### ISSUE THREAD

**Issue by NumbGnat** [PhilippC/keepass2android#516]
I just installed Android Pie the other day and am noticing an odd behavior when showing prompts over chrome. I have attached a screenshot which should illustrate everything you need to know.
![screenshot_20180821-144441](https://user-images.githubusercontent.com/1946849/44422477-48603a00-a551-11e8-88c6-787f35681ca2.png)

**Comment by PhilippC** [comment]
duplicate of #377
