### ISSUE TITLE
Android Pie's task switcher locks up after dismissing popup

### ISSUE THREAD

**Issue by NumbGnat** [PhilippC/keepass2android#517]
I have been able to duplicate this issue twice, so I think it's something that should be looked into. Here are the steps to reproduce...

1. Open KP2A
2. Select an entry
3. Switch to another app (i.e. Chrome)
4. Swipe down from the top to view notifications
5. Swipe right to dismiss the GREEN KP2A notice that says an entry is available for entry. 
6. Try switching apps using the square at the bottom. 

What I encounter:

I cannot switch to any application other than KP2A. When I tap the circle, I go home and can manually start up a previously closed app, but tapping the square puts me right back into KP2A and doesn't present a preview of apps to switch to. 

I tried force stopping KP2A, with no luck. The only way I could recover was to restart the device. I'm using a Google Pixel XL.

I assume that I stumbled on this because Android is allowing me to dismiss that alert, when it wasn't able to be dismissed under previous versions of the operating system. Obviously the workaround is to never dismiss that notification, but I thought you might like to know that this Behavior occurs if somebody happens to dismiss that notification.

**Comment by PhilippC** [comment]
I cannot reproduce on a Google Pixel with Android 9. Anybody else?
