### ISSUE TITLE
Limit onedrive access

### ISSUE THREAD

**Issue by InmarRishi** [PhilippC/keepass2android#518]
Currently when I give access to onedrive, it has access to read/edit my MS account and also read/edit any of my onedrive files. Please restrict the access to only read/edit specific folder in onedrive, not all.

**Comment by PhilippC** [comment]
This is now possible with the new implementation. Please switch to beta and install 1.07b-pre2 (just published to beta, see https://play.google.com/apps/testing/keepass2android.keepass2android). Please click "Change database" (on the password screen), then "Open database", "One Drive", "All files and shared files" (or something else if appropriate) and browse to your file again. This will then use the new implementation. (If you don't re-open the database like this, the old implementation will be used).
Please re-open (or comment) if the issue persists for some reason.
