### ISSUE TITLE
Hide number of characters for Quick Unlock

### ISSUE THREAD

**Issue by Alan-Smith** [PhilippC/keepass2android#52]
In quick unlock screen it says "Enter last N characterd of your password" ... where N is the total chosen by the user in settings.

An option to hide the actual value of "N" would be good.

I know how many things I need to type in, so don't need the hint. But hiding the actual number would help stop someone guessing. 

A simple "Enter your quick unlock code" would be enough.

Or even a more sneaky "Enter last character of your password", regardless of what number is chosen by the user. Any attacker might chance their arm if they thought it was only a single character, immediately locking the database !

**Comment by Opensourcecommunitydevelopment** [comment]
Yes, it is like: please type in the Master Password of length of 8 ! Decreasing number of guesses a lot.
