### ISSUE TITLE
Version 1.05e: No new entries possible

### ISSUE THREAD

**Issue by TheFearlessTinkerer** [PhilippC/keepass2android#520]
On my LG G4 the + symbol for adding new DB entries has disappeared. Restarting the phone does not help. Reinstalling I have not tried. Everything has worked perfectly for 2+ years on this phone

**Comment by Alfanatic1** [comment]
Awesome app.I've begun using out for years now. 
Suddenly can't edit existing passwords. Also can't add outs delete entries.

**Comment by PhilippC** [comment]
Sounds like you have opened the local backup of the database. Please lock close, select Change database and on the recent files list make sure you open the actual database, not the local backup (which is readonly).

**Comment by TheFearlessTinkerer** [comment]
Spot on! That was indeed the issue, thanks. Of course I still don't know how I got there in the first place, but it will probably figure itself out now that I'm aware of it.
Cheers and please keep up the brilliant work. I'll keep spending a beer every once in a while ;-)

**Comment by PhilippC** [comment]
I have also added a switch to show local backups, and that switch is disabled by default (see 1.06 beta).
