### ISSUE TITLE
Show message when file is opened read-only

### ISSUE THREAD

**Issue by Alfanatic1** [PhilippC/keepass2android#521]
Awesome app.I've begun using out for years now.
Suddenly can't edit existing passwords. Also can't add outs delete entries.

**Comment by PhilippC** [comment]
Sounds like you have opened the local backup of the database. Please lock close, select Change database and on the recent files list make sure you open the actual database, not the local backup (which is readonly).

**Comment by philn5d** [comment]
It would be helpful to indicate something in the UI for "readonly"
