### ISSUE TITLE
Can't distinguish zeros and O's when showing passwords

### ISSUE THREAD

**Issue by keeeeymann** [PhilippC/keepass2android#525]
I can't tell zeros (0) and uppercase O's when showing passwords in plain text. Could you change the font? Thanks.

**Comment by Karreg** [comment]
0 have a point inside, O does not. Can't show the result since we can't screenshot the app (obviously).

Granted though: when typing it's harder to tell the difference. However, the important part is reading, not writing right?

**Comment by keeeeymann** [comment]
Well, it seems that my password has no zeros in it, and I'm confusing myself. Thanks for pointing it out.

**Comment by Karreg** [comment]
Sure, I had the same issue a long time ago :smiley:

**Comment by vk5880** [comment]
This is ridiculous. There is no point inside zero. I can't tell difference. Spend a hour before identified the issue. Please fix font. Username is ok, but password is non readable

**Comment by PhilippC** [comment]
maybe we're talking about different views/input fields? If you go to an entry page and click the "Eye" icon to make passwords visible, you definitely should see zeros with a point inside. Where did you look at?

**Comment by vk5880** [comment]
Yes, but there is no dots in zeros!

**Comment by vk5880** [comment]
Sorry, view is when you add new Entry and click eye on password. 
BUT O character in password is almost the same as 0. If you dont remember that 0 has dot inside you can't tell difference. I suggest use same font or change password font O representation
