### ISSUE TITLE
Keeboard-Switching not working on Android P if app is not in foreground

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#530]
this could be solved by starting an activity which brings up the keyboard selection dialog onStart, see also https://stackoverflow.com/questions/52036241/showinputmethodpicker-from-notification-not-working-in-android-9

**Comment by chuim** [comment]
I think I am seeing the problem described by the OP. See screenshot:
![slczhuhweaw](https://user-images.githubusercontent.com/235138/45862898-a8045d80-bd28-11e8-8cd1-85f426e21e5e.png)
