### ISSUE TITLE
Migrate android:// to custom attribute

### ISSUE THREAD

**Issue by hydrian** [PhilippC/keepass2android#531]
One of the aggravations I have with KeePass2Android is the when you save an android application identifier to the entries URL field. Since many services has both an URL and android app, it is common to use a single entry for both the website and the android app. The problem being is that if a user 'updates' the entry to link the android app to the entry with the KeePass2Android keyboard input method, it overwrites the website's URL. Now my browser auto-filler now doesn't work as expected. Many people wouldn't consider an android:// a 'normal' URL. 

**Proposed solution:**
Store the android application URL in a custom keepass entry attribute. 

This is done by other opensource keepass2 android apps (https://github.com/bpellin/keepassdroid). This protects the linking from other applications that may be utilizing the URL field. 

**Migration of existing data:**
On update or creation of android app linking to entry:
If the custom attribute doesn't exist and entry's URL's schema is 'android://' then create the custom  entry key and copy the android:// URL value to the custom attribute.

**Comment by tastyratz** [comment]
I want to stand behind this 1000%. This actually bugs the crap out of me because I sync my desktop database to my phone. I REALLY do NOT want to save an android link in the URL field. It's not a url!

**Comment by hydrian** [comment]
@tastyratz Technically an android://{app java name} is a valid URL. :-) It is just not a browser URL. 

Considering almost all web browser plugins use keepass's URL field, when putting a non-browser URL in there, it breaks a lot.

**Comment by hydrian** [comment]
Personally, I think each platform should work togther and have their own keepass custom attribute: iOS://, macOS:// but that not for this project to work on.

**Comment by tastyratz** [comment]
Honestly, I have a problem with the singular url attribute per entry anyways which instead requires the mess of linked duplicates vs supporting multiple URL attributes, but everyone loses their minds over that so I digress.

 android:// functions as a hyperlink, but it's not a web page and therefore not a URL. That's the important distinction to have here because it both breaks the main use of a database and just plain isn't a URL.

**Comment by thousandsofthem** [comment]
Looks like the appcan use custom attributes like
`KP2A_URL_1` (2,3,...). Can anyone confirm it works correctly, also with multiple entrees per record?

**Comment by hydrian** [comment]
@thousandsofthem,
I don't see any configuration for it in the Google play official version. I don't know if there is a beta program. The only thing I see about attributes is for the TOTP seed attribute.

**Comment by PhilippC** [comment]
to clarify things a bit: When searching for matching items (e.g. when using the built-in keyboard or KP2A's autofill, KP2A will perform several steps to locate them:
* first: search for exact url
* 2nd: if no results, search for host (e.g. "accounts.google.com") (not for androidapp:// queries)
* 3rd: if still no results, search for host, allowing subdomains ("www.google.com" in entry is ok for "accounts.google.com" in search (but not the other way around)), (not for androidapp:// queries)
* 4th if no results returned up to now, try to search through other fields as well
* 5th search for host as text

This means that you can use *any* additional field to store the androidapp:// values.

I see that there can be potential issues if you register for a service inside the android app and later want to use the passwords from a PC which only searches the URL field for the website URL. I didn't expect this to happen often, though.

**Comment by tastyratz** [comment]
Actually, it's frequently an issue here. I have multiple entries for apps I also use on my pc which have a website.
Making the default association another entry, and allowing kp2a to attach to an existing entry especially could be really handy in my use. 

In the meantime, I have to decide which one I use more frequently, the app or the website - but editing the app entry is really cumbersome on the phone vs my pc.

**Comment by hydrian** [comment]
@PhilippC, that search subdomain matching should be a disabled option by default like KeePass 2. That could an used to harvest credentials if the user isn't aware. Think sites that use allow user controlled content in their subdomain. Tumblr is a prefect example of this. I didn't see any control for this behavior in the KP2A. 

Should I open this a separate issue, or just leave it here?

**Comment by hydrian** [comment]
Also, I agree with @tastyratz. This is a pretty common occurrence with me too. 

It is more about the updating of the entry issue KP2A is silently destroying data without warning by overwriting the URL field with the andriod:// schema over top of a https:// without warning. Yes, KP2A asks if you want to add it to the entry,but it doesn't tell you that you are changing existing data. The way it works now would be fine if the URL field was blank.

The way most of my entries are often added are create the entry on a desktop machine with site URL. Then I find out that they have a mobile app. Use KP2A to look up my password, then KP2A asks me if I want associate this app with the entry. I said 'yes' because it makes sense (before I noticed this issue) and it overwrites my website URL.

If I notice while I'm on a desktop, I may make a linked username/password entry. One with the android:// and one with the https:// schema. I don't believe you can make a linked entries with KP2A at this time.

**Comment by PhilippC** [comment]
@hydrian yes, please, create an issue for the changing of entry matching.

Regarding "silently destroying data", I disagree. I just tested this to be sure and it works as I expected:
I have an entry with URL=paypal.com. I go to the paypal app and click the "Autofill with Keepass2Android". The search does not find anything. I select Paypal manually and KP2A asks me if I want to remember this. Keepass2Android does *not* overwrite the URL field but instead create a KP2A_URL_1 additional field with value "androidapp://com.paypal.android.p2pmobile". 

Please give me detailed instructions if you really can overwrite URL data.

**Comment by PhilippC** [comment]
closing this as #657 is more clear about what's demanded.
