### ISSUE TITLE
Does keyboard switching plugin work on my phone?

### ISSUE THREAD

**Issue by xarx00** [PhilippC/keepass2android#532]
LG G6, Android 8, Keepass2Android 1.05e, KeyboardSwap plugin 1.0.3 (enabled via adb and in k2a settings), AutoFill plugin 1.02

It seems to me that this plugin doesn't work on my phone, though I don't know how can I tell that it does.
At least I don't see any change in k2a behaviour with this plugin enabled, and without it.

For testing I use e.g. the Samsung Browser and the Facebook login page. I expect that when I tap into a username or password field on this page, the k2a small keyboard would open. But it doesn't. Perhaps, is this caused by this issue of mine: https://github.com/PhilippC/kp2a_accservice_autofill/issues/9#issuecomment-417837849?

**Comment by PhilippC** [comment]
you need to select the browser menu's Share URL and then select KP2A. Instead of opening the keyboard popup, KP2A should automatically switch to the keyboard now.

**Comment by xarx00** [comment]
Hmm, it does not work exactly this way. This is how this works for me in the Samsung browser:

1. Search google.com for Facebook, click on the m.facebook.com link. The Facebook login page opens. The focus is outside the form fields, so that no keyboard is shown. (You may tap inside the username or password field and the normal keyboard is shown, but the subsequent steps do not change.)
2. Share > with K2A > choose from available credentials. Then the screen blinks, but eventually there is no keyboard shown and no credentials are filled in.
3. Try again point 2. This time the small K2A keyboard is presented. But the chosen credentials are filled in neither in this case.
4. Go back in history to the Google page and click the search field. The small K2A keyboard occurs again, not the normal keyboard.

When I disable the automatic keyboard switching, there is only a small change to the work-flow above:
In point 2 after selection from the credentials, the android keyboard selection dialog is shown. But the rest is the same. So this helps very little.

Because of the Switching plugin description I expected that the K2A keyboard somehow recognises that there's not password field in the web-page, and switches back to to normal keyboard. But the only way how I can switch to my original keyboard from the K2A keyboard is to tap at the padlock sign at the right-hand side, but this also locks the K2A database.

**Comment by xarx00** [comment]
I have installed Chrome just to see what this plugin is supposed to do, and now I understand what it does.
Though Samsung browser is Chromium based as well, the plugin doesn't work correctly with it: Here are some differences:

* When you open the page m.facebook.com, K2A in **Samsung browser** matches on "**m.facebook.com**", while K2A in **Chrome** matches on "**www.facebook.com**".
* The K2A small keyboard in Chrome has a button **Next/Go** on username/password. While in Samsung browser it is only **Go/Go**.

In both browsers, however, the following doesn't work correctly:
1. Tap on a form field in the page to focus it. The normal keyboard is shown.
2. Choose: Share > to K2A, then the screen shortly blinks.
3. Now the form field is still focused (the cursor still blinks in it), but **no keyboard is shown**.
4. When you tap into the field again, the K2A small keyboard is shown.

**Comment by PhilippC** [comment]
@xarx00 You can report the missing "Next" key to Samsung as the browser is responsible for the attributes of the text field. You can also request that the keyboard is shown again at the browser manufactorer's support, both things cannot be solved on my side.

**Comment by xarx00** [comment]
What kind of attributes (apart of those that are part of the HTML page) are you talking about? I don't @PhilippC: I don't understand what you mean as the K2A keyboard correctly recognises the username and password fields, and tab order is part of the HTML page (hence independent on the browser).

And what about the difference in match URL?
