### ISSUE TITLE
Cancel delete problem

### ISSUE THREAD

**Issue by jm009** [PhilippC/keepass2android#533]
When I long tap a key entry, the waste bin symbol appears.
I tap the waste bin symbol. A dialog comes up: "Endgültig löschen" (Really delete).
I tap "NEIN" (no).
The entry disappears (is deleted).

**Comment by PhilippC** [comment]
if you want to cancel the deletion process, you need to tap Cancel (Abbrechen).

**Comment by jm009** [comment]
I reinstalled the app today, and everything seems ok.
Strange, didn't I read the text ("Gewählte Elemente permanent löschen? Nein wählen, um in den Papierkorb zu verschieben." - Delete selected elements permanently? Choose no to move to bin.)?
Or was the text not there when I had the app installed in September...
Sorry for bothering.
