### ISSUE TITLE
[Request] Show username in search results

### ISSUE THREAD

**Issue by jeroeng33** [PhilippC/keepass2android#546]
When using search to pick a value, the popup only shows the entry title and url. Can it be made also the username is visible? I have a lot of entries for login.live.com (also for the family), and would like to distinguish them without manually renaming them.

Edit:  Strange, somehow this already works for some entries. I will try to find why it is not working for some entries.

**Comment by leethax666** [comment]
On mine, it also shows the keepassxc browser settings, it's really annoying when i have multiple accounts for the same site. it should really show the username

**Comment by Small-Ku** [comment]
Would autofill also showing username as #435 mention?

**Comment by haqk** [comment]
It would be great if there was an option to show username below entry titles in search results. While there is already an option to show group name below entry titles, in instances where there maybe multiple usernames for the same group, it turns into a guessing game as to which search entry holds the correct password. It's especially fun finding the right entry when there are > 20 usernames for the same service. Adding this feature would also make the search result entries consistent with how entries are displayed when browsing.
