### ISSUE TITLE
Dropbox sync creates conflict copies

### ISSUE THREAD

**Issue by synk-a-dynka** [PhilippC/keepass2android#547]
Using Dropbox to sync my database between machines.

When opening the .kdbx from dropbox in android  I can edit the database once and it is saved and updated on other devices.
If I edit the still open database a second time Keepass2android does not update the kdbx-file but creates a conflict copy in the dropbox folder next to the original database-file containing the edits. For each edit or addition to the db a new conflict copy is created with an incrementing number.

Have to delete the original db and rename the conflict copy. 

I then have to syncronize db in k2a to get the "new" db-file as it still has the cached file open, even if I choose the new db in dropbox and opens from there.
I can save once before getting conflict copies again.

So there seems to be some kind of issue with syncronizing local cache and original db-file on android.

my db resides in /dropbox/documents/

Keepass2android v1.05e.

[have updated bug report since originally posted as I got more clear with what's going on)

**Comment by PhilippC** [comment]
looks like you have opened the database through the Dropbox app? Please lock and close the database, select "Change database" and "Open database" and then select Dropbox and browse to the database. Retry what you described, this should work now.

**Comment by synk-a-dynka** [comment]
Ah, yeah, that seemed to be the problem...
