### ISSUE TITLE
How are apps matched to autotype entries?

### ISSUE THREAD

**Issue by jjgray** [PhilippC/keepass2android#551]
When my app requests the password from K2A, the search key seems to be backwards.  For example, on the bank's app when I press 'Fill from Keepass2Android' it searches for "com.mybank...", but in my database, which was built on a PC, the URL to match contains "mybank.com".  So there's no match.  Should I be writing my database entries differently to enable a proper match?

**Comment by jjgray** [comment]
Also -- thank you all for your work creating and maintaining this app!  It's a fantastic tool.  I also appreciate that you've made the source public.  Thank you.

**Comment by PhilippC** [comment]
I haven't implemented "inverting" of the package names for the search. I suggest you keep the actual URL in the URL field and add another field for the package name. If you search for the entry the first time and don't get a hit, you select the entry manually. KP2A will then offer to put the app's package name in an additional field. Next time you look it up, it shoud be found.
