### ISSUE TITLE
Interrupted main password entry remains field filled

### ISSUE THREAD

**Issue by jan-gerard** [PhilippC/keepass2android#558]
Difficult to phrase in one brief sentence, but this is what happens :
If I open the app, enter the database password, but don't continue (because for example a phone call is coming in), the the next time I start keepass2android, the password is still filled in, even if it's two days later.
This is not right, I think. Leaving the app for some reason should blank this input field.

**Comment by PhilippC** [comment]
please enable "Clear entered master password" in the security settings.
