### ISSUE TITLE
Allow autofill in browsers on Android Pie

### ISSUE THREAD

**Issue by rodrigoswz** [PhilippC/keepass2android#559]
Android Pie allows autofill passwords in browsers like Chrome without any need for accessibility service.

Some password managers (LastPass, Dashlane...) already provide support for this functionality, it would be great if KP2A did the same.

[An article explaining better about this new feature](https://blog.dashlane.com/android-p-autofill/)

**Comment by PhilippC** [comment]
I guess this is the same as https://github.com/PhilippC/keepass2android/issues/290
