### ISSUE TITLE
Crash after DB unlock (fingerprint and password): System.ObjectDisposedException: Cannot access a disposed object

### ISSUE THREAD

**Issue by EQXTFL** [PhilippC/keepass2android#560]
Crash reports sent, restarting app fixes the problem.

- Android 9, Patchlevel Sept. 5, 2018
- Offline version v1.05d

**Fingerprint:**

09-20 07:29:01.852  8740  8740 D KP2A    : FP: OnAuthenticationSucceeded 
09-20 07:29:01.852  8740  8740 D KP2A    : FP: StopListening 
09-20 07:29:01.888  8740  8740 D KP2A    : System.ObjectDisposedException: Cannot access a disposed object.
09-20 07:29:01.888  8740  8740 D KP2A    : Object name: 'Android.OS.CancellationSignal'.
09-20 07:29:01.888  8740  8740 D KP2A    :   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <17c7fde123ba4702946210f8780e0360>:0 
09-20 07:29:01.888  8740  8740 D KP2A    :   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <17c7fde123ba4702946210f8780e0360>:0 
09-20 07:29:01.888  8740  8740 D KP2A    :   at Android.OS.CancellationSignal.Cancel () [0x0000a] in <c95835bee7fa47fb8c786e2331fc50c3>:0 
09-20 07:29:01.888  8740  8740 D KP2A    :   at keepass2android.FingerprintCrypt.StopListening () [0x00019] in <3748bf3675ff4538b5ba4a23a8fc2c20>:0 
09-20 07:29:01.888  8740  8740 D KP2A    :   at keepass2android.FingerprintCrypt.OnAuthenticationSucceeded (Android.Hardware.Fingerprints.FingerprintManager+AuthenticationResult result) [0x0000a] in <3748bf3675ff4538b5ba4a23a8fc2c20>:0 
09-20 07:29:01.888  8740  8740 D KP2A    :   at Android.Hardware.Fingerprints.FingerprintManager+AuthenticationCallback.n_OnAuthenticationSucceeded_Landroid_hardware_fingerprint_FingerprintManager_AuthenticationResult_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_result) [0x0000f] in <c95835bee7fa47fb8c786e2331fc50c3>:0 
09-20 07:29:01.888  8740  8740 D KP2A    :   at (wrapper dynamic-method) System.Object.d985696e-e2d1-4234-be70-09b62e232e43(intptr,intptr,intptr)
09-20 07:29:08.196  8819  8819 D KP2A_FC_P: onCreate

**Password:**

09-20 07:29:19.378  8819  8866 D KP2A    : LoadDB OK
09-20 07:29:19.381  8819  8819 D KP2A    : Starting/Updating OngoingNotificationsService. Database Unlocked
09-20 07:29:19.556  8819  8819 D KP2A    : FP: StopListening 
09-20 07:29:19.574  8819  8819 D KP2A    : System.ObjectDisposedException: Cannot access a disposed object.
09-20 07:29:19.574  8819  8819 D KP2A    : Object name: 'Android.OS.CancellationSignal'.
09-20 07:29:19.574  8819  8819 D KP2A    :   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <17c7fde123ba4702946210f8780e0360>:0 
09-20 07:29:19.574  8819  8819 D KP2A    :   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <17c7fde123ba4702946210f8780e0360>:0 
09-20 07:29:19.574  8819  8819 D KP2A    :   at Android.OS.CancellationSignal.Cancel () [0x0000a] in <c95835bee7fa47fb8c786e2331fc50c3>:0 
09-20 07:29:19.574  8819  8819 D KP2A    :   at keepass2android.FingerprintCrypt.StopListening () [0x00019] in <3748bf3675ff4538b5ba4a23a8fc2c20>:0 
09-20 07:29:19.574  8819  8819 D KP2A    :   at keepass2android.PasswordActivity.OnPause () [0x00008] in <3748bf3675ff4538b5ba4a23a8fc2c20>:0 
09-20 07:29:19.574  8819  8819 D KP2A    :   at Android.App.Activity.n_OnPause (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <c95835bee7fa47fb8c786e2331fc50c3>:0 
09-20 07:29:19.574  8819  8819 D KP2A    :   at (wrapper dynamic-method) System.Object.fdba0402-4543-4bd2-af6c-68b672fc3629(intptr,intptr)
09-20 07:29:23.296  8890  8890 D KP2A_FC_P: onCreate

**Additional details**

09-20 07:28:11.723  8385  8385 E AndroidRuntime: FATAL EXCEPTION: main
09-20 07:28:11.723  8385  8385 E AndroidRuntime: Process: keepass2android.keepass2android_nonet, PID: 8385
09-20 07:28:11.723  8385  8385 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
09-20 07:28:11.723  8385  8385 E AndroidRuntime: Object name: 'Android.OS.CancellationSignal'.
09-20 07:28:11.723  8385  8385 E AndroidRuntime:   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <17c7fde123ba4702946210f8780e0360>:0
09-20 07:28:11.723  8385  8385 E AndroidRuntime:   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <17c7fde123ba4702946210f8780e0360>:0
09-20 07:28:11.723  8385  8385 E AndroidRuntime:   at Android.OS.CancellationSignal.Cancel () [0x0000a] in <c95835bee7fa47fb8c786e2331fc50c3>:0
09-20 07:28:11.723  8385  8385 E AndroidRuntime:   at keepass2android.FingerprintCrypt.StopListening () [0x00019] in <3748bf3675ff4538b5ba4a23a8fc2c20>:0
09-20 07:28:11.723  8385  8385 E AndroidRuntime:   at keepass2android.FingerprintCrypt.OnAuthenticationSucceeded (Android.Hardware.Fingerprints.FingerprintManager+AuthenticationResult result) [0x0000a] in <3748bf3675ff4538b5ba4a23a8fc2c20>:0
09-20 07:28:11.723  8385  8385 E AndroidRuntime:   at Android.Hardware.Fingerprints.FingerprintManager+AuthenticationCallback.n_OnAuthenticationSucceeded_Landroid_hardware_fingerprint_FingerprintManager_AuthenticationResult_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_result) [0x0000f] in <c95835bee7fa47fb8c786e2331fc50c3>:0
09-20 07:28:11.723  8385  8385 E AndroidRuntime:   at (wrapper dynamic-method) System.Object.eed8f791-fa5e-4ad8-b480-295230cbae31(intptr,intptr,intptr)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at md5f0702f468598c68ce18586502249fb40.FingerprintCrypt.n_onAuthenticationSucceeded(Native Method)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at md5f0702f468598c68ce18586502249fb40.FingerprintCrypt.onAuthenticationSucceeded(FingerprintCrypt.java:56)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at android.hardware.fingerprint.FingerprintManager$AuthenticationCallback.onAuthenticationSucceeded(FingerprintManager.java:257)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at android.hardware.fingerprint.FingerprintManager.sendAuthenticatedSucceeded(FingerprintManager.java:954)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at android.hardware.fingerprint.FingerprintManager.access$600(FingerprintManager.java:67)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:893)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-20 07:28:11.723  8385  8385 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-20 07:28:11.734  1010  5390 W ActivityManager:   Force finishing activity keepass2android.keepass2android_nonet/md5f0702f468598c68ce18586502249fb40.PasswordActivity
09-20 07:28:11.759  8385  8385 I Process : Sending signal. PID: 8385 SIG: 9
09-20 07:28:11.794  1010  3458 I WindowManager: WIN DEATH: Window{8914d64 u0 keepass2android.keepass2android_nonet/md5f0702f468598c68ce18586502249fb40.PasswordActivity}
09-20 07:28:11.795  1010  3408 I ActivityManager: Process keepass2android.keepass2android_nonet (pid 8385) has died: vis  +99TOP

**Comment by PhilippC** [comment]
@EQXTFL can you please test if the pre4 release fixes this?

**Comment by EQXTFL** [comment]
Can't currently reproduce - will reply if I see this again. Many thanks for fixing the issue!!
