### ISSUE TITLE
Firefox autofill

### ISSUE THREAD

**Issue by Jtasiu** [PhilippC/keepass2android#562]
I don't know if you know but firefox 64 now has autofill functionallity! https://bugzilla.mozilla.org/show_bug.cgi?id=1485810

thank you for your great work @PhilippC this is a great app

**Comment by githubomane** [comment]
This actually works for me with 1.07pre-3 - have you checked if it works for you too?

**Comment by Offerel** [comment]
Confirmed working on FF64 Android, Samsung S9, Pie final.

**Comment by kleinarne** [comment]
Doesn't work for me on FF64.0.1 with 1.07-pre3. I'm on OnePlus OxygenOS 9.0.1 based on Android 9.0, and autofill works fine with Webkit (Firefox Focus).
With Firefox, even on 1.07-pre3 I'm still getting the following toast: 
Found multiple web domains: valid=github.com, child=github.com

**Comment by gabrielambuehl** [comment]
Same issue as kleinarne on EMUI 8.0 on a Mate9 (both with FF stable as well as the nightly) and just like for him, it works fine on Firefox Focus.

**Comment by DcR-NL** [comment]
Same issue here on Android 9 with the version 1.06 and 1.07-pre3. Firefox, Firefox Beta and Firefox Nightly all show the following toast and no autofill option:

> Found multiple web domains: valid=accounts.google.com, child=accounts.google.com

Firefox Focus and apps (WebView) work fine.

**Comment by kleinarne** [comment]
As @Small-Ku points out in #675:

>> This issue might be the same issue in #592 ?
>> Maybe the same issue.
>> I am using firefox 64.0.2 not firefox focus.
>>  PhilippC has close issue #592 by this change "e2e7666"
>> I think this should be fixed in the version 1.07, but i have upgraded to the beta version and no effect.

> That fix was committed after 1.07pre3 released.
> 1.07pre3 releasing: 9 Dec, 2018
> Fix: 10 Dec, 2018

**Comment by Nic888** [comment]
> As @Small-Ku points out in #675:
> 
> > > This issue might be the same issue in #592 ?
> > > Maybe the same issue.
> > > I am using firefox 64.0.2 not firefox focus.
> > > PhilippC has close issue #592 by this change "e2e7666"
> > > I think this should be fixed in the version 1.07, but i have upgraded to the beta version and no effect.
> 
> > That fix was committed after 1.07pre3 released.
> > 1.07pre3 releasing: 9 Dec, 2018
> > Fix: 10 Dec, 2018

Can we expect a new release soon? I think this feature would bring value to a lot of users.

**Comment by Small-Ku** [comment]
> 
> 
> > As @Small-Ku points out in #675:
> > > This issue might be the same issue in #592 ?
> > > > Maybe the same issue.
> > > > I am using firefox 64.0.2 not firefox focus.
> > > > PhilippC has close issue #592 by this change "e2e7666"
> > > > I think this should be fixed in the version 1.07, but i have upgraded to the beta version and no effect.
> > 
> > 
> > > That fix was committed after 1.07pre3 released.
> > > 1.07pre3 releasing: 9 Dec, 2018
> > > Fix: 10 Dec, 2018
> 
> Can we expect a new release soon? I think this feature would bring value to a lot of users.

It depends on the decision of PhilippC. Also, if you want to know more about the progress of 1.07, you may go to the [1.07 milestone page](https://github.com/PhilippC/keepass2android/milestone/5)
