### ISSUE TITLE
YubiKey 5 NFC ndef change

### ISSUE THREAD

**Issue by mydexterid** [PhilippC/keepass2android#564]
This is just a reminder that the code needs a little change to support the new YubiKey 5 NFC (they just released) and the old neo.
A helpful example is here: https://github.com/Yubico/yubiclip-android/commit/fa4cd08f1fbbc10ab9711336a7c599c19f1efae8#diff-ab4671c0f97ebc5623c342cc21e1f080

I assume the above only affects NfcOtpActivity.cs. Also the "/neo" pathprefix needs to be removed from all the Properties/AndroidManifest_*.xml files as per change here: https://github.com/Yubico/yubiclip-android/commit/fa4cd08f1fbbc10ab9711336a7c599c19f1efae8#diff-c8cc2dd42271f2bf39c6aa81eb6a5529

**Comment by mydexterid** [comment]
@PhilippC I see your new commit (https://github.com/PhilippC/keepass2android/commit/eb134fd41ad0ac4324c35c225dda112939be1044) but I cannot see the changes needed to work with the new 5 NFC.
Have you tried this with the new one? Does this really work? (I haven't tried 1.7 myself yet, so don't know if it works even with the old NEO)

If not, I suggest reopening this issue, and handling it later when you have time to work on it.

**Comment by rouzbeh** [comment]
I can at least confirm that the latest available version does not work with the Yubikey 5 NFC.

**Comment by mabachel** [comment]
On my Nexus 5X with AOSPExtended (Android Pie) I cannot unlock my KeepassXC database with password and Challenge Response using YubiKey 5 NFC. I used 1.07-pre5.
I uploaded (expires on 2019-03-30.) a log here: [Ubuntu Pastebin](https://paste.ubuntu.com/p/Tm4grgxsSB/)

**Comment by pp3345** [comment]
@mabachel Could you please open a new issue for that over at https://github.com/pp3345/ykDroid/issues?
@rouzbeh Are you talking about Challenge Response (via ykDroid) or OTP?

**Comment by rouzbeh** [comment]
@pp3345 I am trying to use Challenge Response.

**Comment by pp3345** [comment]
@rouzbeh Could you please also comment at https://github.com/pp3345/ykDroid/issues/10 with information about the device and the ROM you use as well as logcat output, if possible?

**Comment by rouzbeh** [comment]
@pp3345 Done!

**Comment by mnpenner** [comment]
So, when I open Keepass2Android, choose "Password + OTP", type my password, click in "OTP 1" text field, and then swipe my [Yubikey 5 NFC](https://www.yubico.com/product/yubikey-5-nfc/), it opens `https://my.yubico.com/neo/%1E%%%1E%20'$` or something like that in a web browser (which fails to load, `ERR_SPDY_PROTOCOL_ERROR` -- I don't think it likes those characters at the end).

I used to YubiKey Personalization Tool to have "NDEF" use Configuration slot 2. I change the URL, or change it to use text, but nothing seems to work with Keepass2Android.

**Comment by PhilippC** [comment]
@mnpenner I suggest you either use the NDEF payload (URI mode) https://my.yubico.com/neo/ and install YubiClip or you use https://keepass2android.crocoll.net/neo and won't have to install YubiClip.

**Comment by PhilippC** [comment]
@mnpenner and please make sure you are running 1.07-pre6 or higher.
