### ISSUE TITLE
Save or open in Drive

### ISSUE THREAD

**Issue by johannbar** [PhilippC/keepass2android#565]
I used to use Drive to save my Database. But at some point it didn't synchronised anymore. 
I try to connect again or to export the local DB to Drive. I can select my Gmail account but after I have a message like entry couldn't be empty.

**Comment by PhilippC** [comment]
please follow https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254 to solve this issue. Re-open if it does not work.
