### ISSUE TITLE
Android P: encoded db path in notifications 

### ISSUE THREAD

**Issue by microcreators** [PhilippC/keepass2android#568]
Hi. It looks like the full db path is now displayed in notifications. At least on OnePlus 6. I'll attach a screen shot as soon as I can add it here on mobile... Thanks. 
![screenshot_20180928-075752 2](https://user-images.githubusercontent.com/12513837/46190740-0a46fa80-c2f5-11e8-8ce3-780989c80423.jpg)

**Comment by serebryakov-av** [comment]
@microcreators It looks like the cached DB has that name. Usually it writes something like: "Dbfilename: Unlocked."

**Comment by microcreators** [comment]
It used to be like that in Oreo. I changed nothing except upgrading to P,
and now I see that name. Not a big deal though. Just cosmetics.

**Comment by Ditti4** [comment]
Actually, I see the same thing in Android 6.0.1. And this only started after the latest update, before that it used to be correct.
