### ISSUE TITLE
Fingerprint sign-in

### ISSUE THREAD

**Issue by mlc73** [PhilippC/keepass2android#572]
Please add the ability to sign in to the mobile android app using fingerprinting.

**Comment by RealOrangeOne** [comment]
This is already possible. If you open the database, and go to 'Database Settings', you can select fingerprint unlock, and configure it from there.

**Comment by mlc73** [comment]
That's great and it works. I just have an idea for improvement. What can I give you more fingerprints?

**Comment by PhilippC** [comment]
if you want to add other fingers, please do so in the Android settings. (Note that this will invalidate previously stored fingerprint data and you have to re-activate fingerprint unlock in KP2A).
