### ISSUE TITLE
Can't manage multiple OneDrive Accounts

### ISSUE THREAD

**Issue by lemonGon** [PhilippC/keepass2android#585]
When a database has been synchronized on Microsoft OneDrive it works well but the problem comes when you try to open another database that dwells on another OneDrive cloud.
These are the steps that I followed:
- I set up a database on my personal Microsoft OneDrive,
- I saved some entries and closed it,
- No problem at all so far: everything works as expected,
- I tried to open another file that dwells on my employer Microsoft OneDrive from the same handset,
- I expected to have the possibility of choosing an account (as it is for Google Drive) but it automatically opened the Microsoft OneDrive cloud previously set, without asking which one, hence it is impossible to choose a database from another Microsoft OneDrive account when you have already one in place.

**Comment by erichiller** [comment]
Second this. In my case it's Google Drive (I want personal, but business is there as well).

For additional info, here are the exact steps, and the error generated:

1. open the Kepass2Android file picker.
![screenshot_20181015-084335_keepass2android](https://user-images.githubusercontent.com/5379325/46962008-e4408a80-d056-11e8-8fbd-8f61d952592a.jpg)


2. Select my personal account
![20181015_084512](https://user-images.githubusercontent.com/5379325/46962012-e4408a80-d056-11e8-83f4-96a6a7ede70e.jpg)

3. Receive error: `The name must not be empty: Null`
![20181015_084424](https://user-images.githubusercontent.com/5379325/46962010-e4408a80-d056-11e8-86d1-bb21b365c4be.jpg)

**Comment by MaceJustice** [comment]
I'd like to add to this.

I have stopped using a particular OneDrive account and have moved my data to another OneDrive account. Unfortunately whenever I select OneDrive at the "Select the storage type screen", it defaults to my old OneDrive account.

I have:

1. Removed app authorisation at my old OneDrive account to try and force a new log-in. It did not force me to log in but simply tried to reauthorise my old OneDrive account.

2. Uninstalled and reinstalled Keepass2Android from the Google Play Store - same behaviour as 1

3. Ensured my new OneDrive account was added to my phone accounts, restarted my phone, selected "System File Picker" - I can select my new OneDrive account but it is treating my .kbdx file as being read-only. This would presumably require a manual workaround to sync if I changed any passwords via Keepass2Android.

**Comment by julmoser** [comment]
@MaceJustice have you tried to delete all the Data and Cache in the settings of the App before uninstalling it? That worked for me

**Comment by PhilippC** [comment]
this issue is fixed in the new OneDrive implementation. Please switch to beta and install 1.07b-pre2 (just published to beta, see https://play.google.com/apps/testing/keepass2android.keepass2android). Please click "Change database" (on the password screen), then "Open database", "One Drive", "All files and shared files" (or something else if appropriate) and browse to your file again. This will then use the new implementation. (If you don't re-open the database like this, the old implementation will be used).
Please re-open (or comment) if the issue persists for some reason.
