### ISSUE TITLE
Limit access to READ ONLY for certain .kdx files?

### ISSUE THREAD

**Issue by andrewkeypass** [PhilippC/keepass2android#586]
This I think is similar to "Limit onedrive access #518" but is generic.  Is there a way one can limit (or you can add the function) to limit access to KeyPass files on a different persons phone/shared media?  Scenario is I have a family keypass file, and would like others in the family to be able to access it, but only in a READ ONLY mode so that I am the only one who can ADD or CHANGE data inside.

If made as part of your application, supposedly would would on ONEDRIVE, DROPBOX, GOOGLE storage, whatever external cloud storage one uses.

**Comment by PhilippC** [comment]
this is something which must be configured on a file system level. E.g. with Webdav, you could create an account for the other users with read-only permissions to the file. I don't see a way to implement this inside the app.
