### ISSUE TITLE
Button to select entry from keyboard no longer works in Android 9 (OxygenOS 9)

### ISSUE THREAD

**Issue by PMKielstra** [PhilippC/keepass2android#587]
I recently updated my OnePlus 6 from Android 8 to 9.  The button on the KeePass keyboard that used to launch the app in order to choose an entry (the one with the KeePass2Android logo) no longer launches anything.  I press it and nothing happens.  It worked on Android 8, so I believe this is an issue with the new version.  The upgrade went seamlessly and I have had no issues with any other apps, so I do not believe it was a problem with the upgrade process.  I have tried uninstalling and reinstalling the app and the problem persists.  Thank you very much for looking into this.

**Comment by PhilippC** [comment]
which app version are you running?

**Comment by Michaelkielstra** [comment]
1.05d offline.

On Oct 10, 2018 21:40, PhilippC <notifications@github.com> wrote:

which app version are you running?

**Comment by hockey6611** [comment]
Anyone else still having this issue? This issue persists on Pixel 3 with Android 10, version 1.07-r1. The fields do have have always worked selecting the ">". But I have some entries with many long field names so this is not very helpful becauase they are cut off on the mini keyboard buttons.

**Comment by zveber** [comment]
I have the same problem on my new Xiaomi Redmi 8T, which runs OS, based on Android 9.

**Comment by hockey6611** [comment]
This appears to have been addressed in 1.08b. Than you to @PhilippC for the hard work on this! However I still seem to be having an issue. The previously missing fields now show up in the list, however, when one is selected, they do not appear to fill into the form. The keyboard simply closes. This is on Android 10.

**Comment by PhilippC** [comment]
@hockey6611 do you know how to collect a logcat?
