### ISSUE TITLE
App is saving database forever (sftp)

### ISSUE THREAD

**Issue by elmicha** [PhilippC/keepass2android#589]
Hi,

keepass2android hangs forever with "In Bearbeitung" - "Speichere Datenbank... (Prüfe ob Zieldatei geändert wurde...)". I'm using sftp, and I had the database opened with KeepassXC. But it would be nice if that dialog could have a cancel button or a timeout.

Best regards...
  Michael

**Comment by RobertHeim** [comment]
Did you find a solution? cannot access any passwords anymore from mobile...

**Comment by elmicha** [comment]
Sorry, it has been working for me for a long time. I also cannot reproduce this hang anymore.
