### ISSUE TITLE
How to sync with ownCloud/Nextcloud after using local keypass file

### ISSUE THREAD

**Issue by 74cmonty** [PhilippC/keepass2android#591]
Hi,
I'm using the online version of k2a.
However I started using the app creating a local keypass file on my device.

Now I want to sync the passwords with my newly installed Nextcloud server.
However I cannot detect any setting to switch to online sync.

Can you please advise how to proceed from here?

THX

**Comment by PhilippC** [comment]
go to settings - database settings - export database and Export the database to your server. Then lock&close the database and select Open database - ownCloud and browse to the exported file.
