### ISSUE TITLE
Oreo autofill broken with Firefox 64/Focus

### ISSUE THREAD

**Issue by artgru** [PhilippC/keepass2android#592]
After last firefox focus update, I can't force keepass2android to show up and fill up my login information, instead there is a weird popup showing up:
https://screenshots.firefox.com/cbdVhaiuTtC0bDCx/null

**Comment by BobVul** [comment]
Focus switched (A/B testing, so currently only some users) from Google WebView to Firefox GeckoView around that time. At the same time, GeckoView/Firefox 63+ fixed some Autofill-related issues (where 62 wasn't triggering Autofill at all).

https://bugzilla.mozilla.org/show_bug.cgi?id=1330257
https://bugzilla.mozilla.org/show_bug.cgi?id=1352011
https://bugzilla.mozilla.org/show_bug.cgi?id=1491989

This toast can be triggered on Firefox Nightly (65) or by forcing Focus to GeckoView via `focus:test`.

Not sure who's responsible for the problems between Firefox and K2A. Evidently either one side is generating invalid data or the other is failing to parse valid data. Or both.

**Comment by PhilippC** [comment]
I just tested again with Firefox Klar 7.0.13 and AutoFill seems to work again in that release. Can you please check?

**Comment by BobVul** [comment]
Does not work on 7.0.13. Same toast is shown. 

@PhilippC, are you sure you're using the new renderer? Check `focus:test`.

**Comment by artgru** [comment]
It works o 7.0.13.
Nightly 65 still shows the same toast.

**Comment by Small-Ku** [comment]
It doesnt work for me, no matter in firefox focus 7.0.13 (geckoview enabled in focus:test) and nightly(66.0a1).
It looks strange when I test with another app but it works.
![result-2018-12-17-17-10-13](https://user-images.githubusercontent.com/16464896/50077596-c4c50a00-021f-11e9-9975-0ce4b8f78478.png)
