### ISSUE TITLE
When I save to Dropbox I get conflicted copies

### ISSUE THREAD

**Issue by abdupattoh** [PhilippC/keepass2android#598]
Hi - 

I leave Keepass 2.39.1 open on my computer and my wife's computer pretty much all the time.

I am running the latest version Keepass2Android on a samsung A8 (2018) Android 8.0.0. 

It seems that whenever I try to update/save a new entry in keeppass2android I end up with a conflicted copy in Dropbox.

Is there some setting I should be aware of?  

The expected behavior was that that editing the database on different devices was transactional (atomic?) by entry, so it would work seemlessly...  

Thanks,

**Comment by PhilippC** [comment]
did you open the database through the built-in Dropbox support in Keepass2Android ("Open database" -> "Dropobx")? Do *not* open it starting in the Dropbox app. Then KP2A will not create conflict copies. If conflict copies are created on the PC, you might have to setup something like https://keepass.info/help/kb/trigger_examples.html#dbsync
