### ISSUE TITLE
Feature request: Add a way to move or export keyfile from internal folder

### ISSUE THREAD

**Issue by spocko** [PhilippC/keepass2android#599]
If the option to "Import key file to internal folder" has been used, then there doesn't seem to be a way to get a copy of the keyfile again (without root).

My use case is that I have the keyfile on my phone, and I have imported it to the internal folder. Now I want to get a copy of the keyfile so I can copy it to another device, but I can't find a way to do that.

A few options off the top of my head:

a) Add an option to export the keyfile, similar to the option to export the database, or
b) Add options to move the database and/or keyfile from internal folders back to normal storage.

Thanks

**Comment by PhilippC** [comment]
Caution! Looks like you might lose access to your data whenever you lose your mobile device!
I suggest you export the database as unencrypted XML and import it into a new database with KeePass 2 (or use the Change password option to save it without key file). You can then add a keyfile again, but make sure you keep a safe copy of it.

**Comment by spocko** [comment]
Thanks, but I think my data is safe. My database is stored in the cloud and sync'd to several devices. I store my keyfile only on those devices, not in the cloud.

I was away from home and wanted to get a copy of the keyfile from my mobile device so I could copy it to a new laptop. I couldn't find a way to do that, so I had to wait until I got back home so I could copy the keyfile from another computer. It would be nice if there was a way to copy, move or export the keyfile from internal storage.

**Comment by Vlad1mir-D** [comment]
I would like to ask for this feature too as I'm using Google Drive to sync and store databases and sometimes I need to open another database with the same which was already imported into "internal folder" (which isn't accessible outside of keepass2android without rooting device) so my only option here is to copy key from safe storage again, open database, import key into an internal folder and remove key from plain storage - this seems to be far from best possible usability experience.
Thanks a lot!

**Comment by Vlad1mir-D** [comment]
@PhilippC Thank you so much! You're awesome!
