### ISSUE TITLE
Unable to read database on Google drive

### ISSUE THREAD

**Issue by hopslink** [PhilippC/keepass2android#600]
After phone update to android 8.1 I am unable to access my password database on Google drive. This looks like a change from Google. 
If I try Open File > Gdrive > Select Account > OK I see an error 'the name must not be empty: null' and connection to Gdrive does not happen.

**Comment by hopslink** [comment]
I can open the database using KeyPass from Gdrive app, but cannot access direct from KeyPass.

**Comment by Trav77** [comment]
I have a similar problem in that my Google drive hosted key file is no longer accessible. I have tried to Change location but when I select my Google account and click OK I get the same error as above. I think this issue may also affect webdav.  I'm on the latest version of keepass2android and android Oreo 8.1 on a moto g5.

**Comment by PhilippC** [comment]
please see https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254

**Comment by Trav77** [comment]
The process in #432 worked, thought I'd tried that before.  This time I revoked permission then forced stop, then changed location of the key file and it worked fine.
