### ISSUE TITLE
Can't authenticate with pCloud when using 2-factor authentication

### ISSUE THREAD

**Issue by MisterY** [PhilippC/keepass2android#605]
Now that the pCloud integration is done (thanks!), I'd like to keep this issue open until resolved. It has been mentioned in #512, but that is now closed as it has been completed successfully.
As noted there, the client library is not (yet) compatible with 2-factor authentication so, I guess, this will be complete when a new library/api is released. Those who want to stay in touch should be able to subscribe to this issue and follow progress.

**Comment by MisterY** [comment]
Some relevant info may be found in the [docs](https://docs.pcloud.com/methods/intro/authentication.html). No mention of the 2FA for the moment.

**Comment by MisterY** [comment]
Unfortunately, their support claims that that it is not on the roadmap.

**Comment by cdyson37** [comment]
Any update on this? I just tried to sign in via kp2a and the blue login button just keeps spinning (does not prompt me for a 2FA number).

**Comment by bobberooni** [comment]
Good news, I think this may be fixed now (at last). I enabled 2FA on my pCloud account (with the auth app option) and so far it has worked with keepass2android

**Comment by MisterY** [comment]
Thank you, I can confirm that it works. Tested with K2A, pCloud mobile app, RCX, and rclone in Termux! 
They have linked the API access to 2FA. 
🚀 🚀 🚀
