### ISSUE TITLE
Unable to unlock KeepassXC DB with Yubikey on 1.07-pre1

### ISSUE THREAD

**Issue by JRussell** [PhilippC/keepass2android#609]
You requested I open a new issue about this. I tested with 1.06f release you linked me to in the other thread and that works as expected with both a local DB and to my nextcloud server(using the owncloud option)

1.07-pre1 throws a toast at the bottom of the screen saying "The challenge response is incorrect." when I try to unlock and then hangs on "working" and I have to manually close the app.

The log below has attempts to unlock both local and nextcloud(using nextcloud option). I'm glad I looked at the log before posting it because it seems that the debug option stores the username and password for my nextcloud in plaintext. I edited my password and server to *s for my own security obviously.

This is on a Pixel 3 running P and I also get the same behavior on my Sony XZ1 Compact running O. Both were using 1.07-pre1 and the latest ykdroid when testing.

[kp2a-debuglog.txt](https://github.com/PhilippC/keepass2android/files/2560296/kp2a-debuglog.txt)

**Comment by PhilippC** [comment]
sorry for the leak of file access credentials. Just fixed this.
I'll have to do some testing on my own, but did you try without checking the "Work on internal cache only" option?

**Comment by JRussell** [comment]
The tests in the debug log had the internal cache box unchecked. When I check that box I see an additional toast in the center that says something along the lines of "Could not access source file using local cache instead" I attached a log with that box checked using a local DB in my downloads folder.

[kp2a-debuglog2.txt](https://github.com/PhilippC/keepass2android/files/2560381/kp2a-debuglog2.txt)

**Comment by PhilippC** [comment]
@pp3345  thanks for your investigation. It looks like I haven't correctly pushed my local repository. The change you refer to is https://github.com/PhilippC/keepass2android/commit/4f3f18a0ad9a62ce801fbf1684ca1a27944fa91b#diff-912c629806a45bf7d95c8f1859b99a79L72
which is no actual "revert". I moved all the manifest stuff from PasswordActivity to another activity and will have to add the configChanges to PasswordActivity again.

**Comment by PhilippC** [comment]
@pp3345 do you think this could also cause https://github.com/PhilippC/keepass2android/issues/596? In that case I would have to add these settings to many more activities?

**Comment by pp3345** [comment]
@PhilippC I think that's possible. Haven't looked at the code, but supposedly KP2A also invokes ykDroid when saving a KPXC challenge-response database? In that case, you'll also need to add `keyboard|keyboardHidden` to the `android:configChanges` attribute of the activity used for saving a database. I'll try and see if I can reproduce the issue with a USB YubiKey later today. Never actually used KP2A for modifying a database before.

**Comment by PhilippC** [comment]
@pp3345 I made further tests and found that this is probably related to the fact that the ykDroid activity is a dialog, please see https://stackoverflow.com/questions/53456335/onactivityresult-not-called-when-starting-a-dialog-activity-and-recreating-activ
