### ISSUE TITLE
Improve K2A's matching for apps

### ISSUE THREAD

**Issue by SinTan1729** [PhilippC/keepass2android#618]
Let's say I have added an amazon.in entry from my pc. Then, in the Amazon app, it doesn't automatically find that an input. I have to manually search for it. It used to work with lastpass for example. Please do something. Maybe loosen the matching criteria or something.

**Comment by Small-Ku** [comment]
you might refer to #551 and #531 instead
Try to create a KP2A_URL_1 additional field with value that links to the app instead
ଘ( ˙꒳​˙ )ଓ

**Comment by PhilippC** [comment]
decided not to implement this, it is recommended to link the app once with an entry explicity for security reasons
