### ISSUE TITLE
Go button not submiting form

### ISSUE THREAD

**Issue by crispyduck00** [PhilippC/keepass2android#621]
The Go button in the small kayboard is not submitting the password form when auto switch back to standard keyboard is enabled.
When auto switch back is not enabled, the Vo button submits the form. When auto switch back is enabled it only swiches back to the standard keyboard and Go has to be pressed again on it.

LineageOS 14.1
Keepass2Android Offline 1.06f
KeyboardSwap Plugin 1.0.3

**Comment by PhilippC** [comment]
what is the target app you are using for testing?

**Comment by crispyduck00** [comment]
Brave and Firefox Klar.

**Comment by crispyduck00** [comment]
Same with Brave 1.0.71 or FirefoxKlar 7.0.13, on Android 8.1.0/Lineage OS 15.1

The Go button always only swaps back to the default keyboard.

Is this a browser related behaviour?

**Comment by PhilippC** [comment]
sorry for not taking care of this so long. Is it possible that this "disappeared"? I cannot reproduce using Firefox Klar, logging in to Paypal and Amazon. Please re-open if you can still reproduce, then add more specific information.
