### ISSUE TITLE
Updates not correctly saved in pCloud

### ISSUE THREAD

**Issue by MisterY** [PhilippC/keepass2android#624]
Just an early warning, hoping that others confirm or deny this behaviour.

I'm using pCloud as the storage provider. Unfortunately, today I experienced that the updates made on the phone do not make it into the cloud. This happened on two different devices. I still do not see the changes on the desktop workstation, in pCloud Drive.

scenario:

- install K2A on a mobile device (tablet)
- open database from pCloud
- make changes

As a side note, during this scenario, when I made a second change, I was warned about the conflicting changes and selected the Merge option.

After these changes, the desktop, using pCloud Drive, does not reflect any changes in the record.

- open database (including refreshing from the cloud) on a different device (phone). Result: no changes visible.
- make the same change (update username field). Result: the change still not visible when re-opening the database on the desktop workstation.

This might be very important.

**Comment by MisterY** [comment]
Reopened the database on the phone, including automatic cache refresh. The change that was made two minutes ago is now completely gone and I see the old username (email address) in the record.

Effectively, any changes made on mobile devices are wiped out! Had this been the password field, I would have now lost access to the account.

**Comment by MisterY** [comment]
- made the change in the desktop app
- reopened the database on the phone, the changes are visible

- editing the record on the phone, saving,
- reopening the database on the desktop, no changes are found.
- reopening the database on the phone, sync happens, changes not found (wiped out)

**Comment by MisterY** [comment]
Some light in the tunnel...

I see five password files in the format "<original name> (n).kdbx" in the app folder. I've merged the changes and I see the test entry which was made on the mobile device.

**Comment by MisterY** [comment]
Every time I save changes on the phone, a new copy of the database file is created in pCloud. 
Could've been that the API has changed and the workaround for the save problem is now the problem itself.

**Comment by PhilippC** [comment]
@MisterY this has already been fixed in the code and should work after the next release.

**Comment by MisterY** [comment]
Thanks a lot. Good to know!
