### ISSUE TITLE
Donation is done

### ISSUE THREAD

**Issue by mkching88** [PhilippC/keepass2android#629]
I donate the app with PayPal but can't get the test account and Donated version of Keepass2android
Transaction ID: 1WN83434YX302880M

**Comment by PhilippC** [comment]
first: thanks for your donation!
second: please note that a donation is not a purchase, i.e. you don't receive anything in return (maybe except a happier developer which will be more willing to continue working on the app...). 
If you mean beta testing, everybody can join https://play.google.com/apps/testing/keepass2android.keepass2android 
There is no "donated version". Everybody can disable the prompt for donations in the app settings.

**Comment by Karreg** [comment]
And I hope you find what you want in developping KP2A (both for money and joy on the task), because what you're doing is quite big!
