### ISSUE TITLE
Entries with otp field aren't  accessible via notification or keyboard

### ISSUE THREAD

**Issue by seanrand** [PhilippC/keepass2android#632]
Version 1.07-pre2 on Android 8.0

When opening an entry with an otp field from within KP2A, neither the KP2A keyboard notification nor the keyboard is shown. Well, as far as I can tell, both the notification and keyboard appear for a split second but disappear again.

When trying to access an entry "manually" via the KP2A keyboard (KP2A icon -> select (another) entry),

- with keyboard switching enabled, it immediately switches back to the default input method  
or
- with all keyboard switching options disabled, after selecting the entry, the KP2A keyboard doesn't acknowledge that in any way. No user/password buttons, nothing in the icon menu except select entry and search for entry.

So, the only way to access the user/pass/totp values of an entry with a otp string set is to manually copy each one to the clipboard.

I'll dig deeper if you can't reproduce this issue, just thought I'd try my luck with a superficial bug report first. 

Edit: nothing relevant in logcat, unfortunately.

**Comment by DDoSolitary** [comment]
I got exactly the same issue on v1.0.7-pre3. And for me, the keyboard buttons for entries without otp aren't displayed properly

![screenshot_firefox_beta_20181213-224020](https://user-images.githubusercontent.com/25856103/49946180-65b67b00-ff29-11e8-99ff-742cb2cf03a9.png)

**Comment by xurimx** [comment]
I have same issue when I open an entry with otp. But it does work if I open the entry from the keyboard(open the keyboard touch any text field). the entry stays until totp is refreshed.

**Comment by saalkom** [comment]
Have same issue with KP2A v1.07-r1 on S8 Plus running Android 7.0.
[keepass2android.log](https://github.com/PhilippC/keepass2android/files/3244952/keepass2android.log)

**Comment by lcrok** [comment]
I'm getting the same issue. No notification and keyboard not selecting entries with otp. Any news on that yet ?

**Comment by PhilippC** [comment]
please follow https://github.com/PhilippC/keepass2android/issues/799 for updates on this.
