### ISSUE TITLE
[Feature] changeable password generator

### ISSUE THREAD

**Issue by 927589452** [PhilippC/keepass2android#633]
It would be nice to provide alternative password generators I a way to easier integrate for example a word based password generator like https://xkpasswd.net/s/

**Comment by lindhe** [comment]
I don't see the use for letting the user change generator, but having a passphrase generator like in KeePassXC (on the desktop) would be swell.

**Comment by dave-kennedy** [comment]
I'd love to be able to generate a passphrase from the app.

**Comment by PhilippC** [comment]
duplicate of https://github.com/PhilippC/keepass2android/issues/284
