### ISSUE TITLE
[BUG] - Modify data with Yubikey Neo Corrupts the Database on PC - Reproducible

### ISSUE THREAD

**Issue by camAtGitHub** [PhilippC/keepass2android#636]
Hi,
I found a bug in my testing on Android and YubikeyNeo NFC support (Challenge Response Mode) (using YkDroid)

Requirements:
- Yubikey NEO (NFC) in Challenge Response Mode Slot 2
- Windows 10 x64 (KeepassXC 2.3.4 x64)
- Android 8 (Keepass2Android v1.06f)

Steps to reproduce bug:

### ON PC:
New DB
- Pass 1234
- Tick Challenge response ( with Yubikey in Challenge Response mode (Slot 2))

Add new entry
- Title: West
- Username: steve
- Password: 1234
- Repeat: 1234
- URL: west.com
- Tick 'Notes'
-- Input: '1'  (without quotes etc)
Save / OK

Click Database > Database Settings > Encryption > Change Key Derivation Function to: 'AES-KDF (KDBX 4)'
Save / OK

Lock Database

### Open Database with Keepass2Android
Unlock with Password + Yubikey with NFC

Select Entry 'West'
Edit Entry
Change Notes '1' to: 'I did a thing'  (without quotes)
Save entry > Provide Yubikey Neo as requested
Lock DB
Close DB

### On PC:
Try to open the 'synced' DB with:
- Pass 1234
- Tick Challenge response ( with Yubikey in Challenge Response mode (Slot 2))

DB fails to open with:

'Unable to open the database
Wrong key or database file is corrupt'

**Comment by camAtGitHub** [comment]
Ok I see this a known issue: https://github.com/keepassxreboot/keepassxc/issues/1060
 and https://keepassxc.org/docs/#faq-platform-mobile 
Feel free to close...

**Comment by joshuous** [comment]
@PhilippC, I'm reporting again that issue #596 is not fixed as highlighted by issue #636.

**Comment by PhilippC** [comment]
@joshuous did you test with 1.07-pre?

**Comment by joshuous** [comment]
@PhilippC, my apologies. I didn't realise that I was on version 1.06. I just updated to the 1.07 version and confirm that the bug is fixed. Thank you!
