### ISSUE TITLE
pCloud intergration

### ISSUE THREAD

**Issue by bugreport0** [PhilippC/keepass2android#64]
I would like to propose pCloud sync for consideration. The app seems mature, they have pretty straight forward [API](https://docs.pcloud.com/) and since they offer 2TB/250EUR lifetime licence user numbers are presumably growing. They offer client-side encryption and as [Swiss company](https://www.pcloud.com/terms_and_conditions.html) heir are arguably more geared towards privacy. On the top of that they are [ISO 27001:2013 and ISO 9001:2008 certified](https://www.pcloud.com/company/certification.html).

I'm not affiliated with the company in any way, I was just reviewing my cloud options and pCloud seem to offer best privacy and space for dollar. I'm currently testing pClound on multiple platforms, so far without a hitch, and since I'm considering premium, I'm also reviewing integrations.

**Not having this 3rd-party plugin is by no means an issue**, I just wanted to get your opinion on this. I'm also sending link to this discussion to their support.

If you haven't tried pCloud, here is [referral link](https://my.pcloud.com/#page=register&invite=WsF6ZkXq8KV) (+1Gb free), or you can register without referral using any link above. Or don't register at all, I'm not your mom.

**Comment by fsantini** [comment]
I would also like to see this enhancement.
