### ISSUE TITLE
Incorrect labels for Keepass2Android keyboard

### ISSUE THREAD

**Issue by me-and** [PhilippC/keepass2android#641]
I'm using 1.07-pre3. On this version, I'm seeing the "username" and "password" fields marked as what appears to be "ABC" and "Credential input search" on the Keepass2Android keyboard; see screenshot below.

I'm seeing this with multiple entries (I've checked two entries in the same folder and with different sets of additional fields). This is with Android 9 on a OnePlus 6T.

![screenshot_20181217-090840](https://user-images.githubusercontent.com/1397507/50077158-7aba3500-01db-11e9-8fed-02d4777828d9.jpg)

**Comment by nicolas-stephens** [comment]
Yup, #377 looks to be back.

**Comment by Offerel** [comment]
I hope there can be a update for this on Android Pie. Bug confirmed for Pie final on Samsung Galaxy S9.

**Comment by solikeumyeah** [comment]
I can confirm I'm experiencing the same as my screenshots in #377, including these menu entries:

- "Search for entry with %$1s".
- "Close the keyboard Press the Back Key."
- "Open the keyboard Touch any text field."

It also seems "Keyboard switch back" often triggers as soon as I select an item, and I'm not given the opportunity to actually perform the password entry. Some other times, the entry fields do not work until I have entered a line feed. I can't seem to get consistent behaviour. It's quite frustrating, so I'm moving back to the stable release.

**Comment by Karreg** [comment]
Confirmed on my side too. Is it for all languages or only French ?

**Comment by me-and** [comment]
@Karreg It's definitely not just French; my screenshot above is English (it'll be en-gb rather than en-us if that's a relevant distinction).

**Comment by charlesmcevoy** [comment]
Just the same here on en-gb (HTCU11 Android 8.0.0)

**Comment by Elias23** [comment]
Just the same here on en-us (HTC10 Android 8 and OnePlus 6T Android 9)

**Comment by Topher2014** [comment]
Same issue here.

**Comment by PhilippC** [comment]
should be fix in 1.07-pre4 (available on https://play.google.com/apps/testing/keepass2android.keepass2android)
