### ISSUE TITLE
turn off notification while quickunlock is active?

### ISSUE THREAD

**Issue by meeotch** [PhilippC/keepass2android#647]
On Oreo 8.0, I'm getting a persistent notification icon when KP2A is in quickunlock mode.  If I try to hide it, I get a persistent notification from android telling me that KP2A is running in the background.  Both of these create icons in the status bar.

What I'm trying to achieve is no icons (and ideally, no notifications), except when the database is actually unlocked.  Is this possible?  (Please excuse my ignorance - just upgraded to an Oreo phone from one that was still on, I think, Gingerbread.  Figuring out how to tame all the new geegaws and flashing trinkets is a bit overwhelming.)  If it matters, I do have the accessibility service enabled.

Bonus question:  is there any difference between the online & offline versions of the app, from a battery/wakelock perspective - assuming that I'm not using on online database?

**Comment by whisdol** [comment]
You can change the priority of the "QuickUnlock"-notification to low in the Android app settings - this will hide the icon from the status bar, but keep the notification itself in the notification drawer. The easiest way to navigate to these settings is by long-pressing the notification and then tapping "All categories". The priority for the "Database unlocked" notification can be adjusted separately.

It's not possible to completely hide the notifications, as Android 8+ requires apps to show them while they are running in the background (which I think K2A is doing to keep the database open).

**Comment by meeotch** [comment]
Thanks for the reply.  In fact, that's what I'd tried - what's described above, only I suppose I'm using the wrong terminology.  I turned off the little slider next to QuickUnlock in the All Categories screen for KP2A, which I take it means "low priority", though it's not labeled as such.  The result is a new, regular priority notification telling me it's running in the background, which also produces an icon, and cannot be dismissed.  I poked around, but it seems like the only way to turn off that notification is to turn it off for all apps.  (Which I'd prefer not to do, since it seems like it would be useful for catching rogue apps.)

In fact, turning off notifications for KP2A altogether from All Categories also produces this system background notification.  Is there some option within the app to disable sending of notifications?  I primarily access KP2A through the keyboard, or by directly clicking on the app.  I'd prefer to just have a "database open" notification & no others, but I'd settle for none at all, and just trust KP2A to close the db as appropriate.

(Weirdly, I don't think I've seen this system background notification for other apps.  Though I pretty sure I've got things running in the background.  I've got an LED manager called "Light Manager" that runs in the background, but that app has options for turning off its notifications, and it produces no "background" notification.)

**Comment by whisdol** [comment]
Turning the notification off is not the same thing as changing the priority - toggling the switch after long pressing just turns it off. You need to actually open the All Category screen, tap on the notification category -> Importance -> Low to change the priority.

**Comment by meeotch** [comment]
Aha - thanks.  That was also not clear from the interface.  Unfortunately, it seems to produce similar results:  a compressed QuickUnlock note at the bottom, and a regular "Keepass2Android is running in the background" note above, with status bar icon.

Setting this background note also to low priority removes the icon, but retains the compressed notification message, as expected.  So total result = no icons, but twice as many permanent notifications.

Is there a way of causing QuickUnlock to time out after a couple hours?  I could probably live with having to enter my full passphrase a 1-2 times a day, in exchange for a notification tray that cleans itself up over time.

**Comment by PhilippC** [comment]
Keepass2Android does what it can do (by using notification channels). I agree with @whisdol  that you should be able to remove the icon but have to keep the notification in the notification drawer. I don't think there should be a "running in the background" notification. If this is caused by your device/OS, maybe https://play.google.com/store/apps/details?id=com.iboalali.sysnotifsnooze will help.
