### ISSUE TITLE
NFC challenge-response prompt does not come up.

### ISSUE THREAD

**Issue by andmib** [PhilippC/keepass2android#65]
I have a database that is protected with a password and challenge-response via my Yubikey NEO. When I click 'load auxillary OTP', I do not get a prompt to install a yubi-challenge app.

Is there something I have to do to bring up the prompt?

**Comment by PhilippC** [comment]
which kind of file storage do you use? Is anything happening? 

Depending on the filestorage, KP2A should automatically find the auxiliary file (.xml) or bring up a file browser to select it.

**Comment by andmib** [comment]
I'm using Google Drive file storage. However, I don't see an auxiliary file in the same folder as where my .kdbx file is.

**Comment by PhilippC** [comment]
did you set up the database with Keechallenge on Windows? You need to do this to get the auxiliary file!

**Comment by andmib** [comment]
I see what the problem is. I use KeepPassXC (a port of KeepPass) which doesn't support plugins but has built-in support for challenge response that doesn't utilize an auxiliary file. 

So it looks like I'll need to switch to KeepPass with plugins to get this to work. Thank you for your help on this.

**Comment by PhilippC** [comment]
Ah ok. Please see #4  for updates.
