### ISSUE TITLE
Passwords do not display in monospace font

### ISSUE THREAD

**Issue by jamesmeastus** [PhilippC/keepass2android#650]
I am using keepass2android on a Sony Xperia XP Premium with Android Pie 9.0, and none of the text is displayed in a monospace font like Source Code Pro etc.  This makes reading stored passwords quite hard, e.g. a lowercase L ('l') looks like an uppercase I.
I am fairly certain the text was monospace at some point, which makes me think it's either a problem to do with th Sony Xperia phone or Android Pie.

**Comment by PhilippC** [comment]
hmm, can you maybe try to reinstall the app? If that doesn't help, can you post a screenshot? It's working on a Google Pixel with Android 9 for example.

**Comment by Small-Ku** [comment]
> 
> 
> Sorry for the delay writing back ! See attached screenshot. I'm using the "Secure Note" entry for storing this password info because I need to keep the previous password around.
> ![sony-xperia-no-monospace-font](https://user-images.githubusercontent.com/46108864/51114848-8bf36300-17d4-11e9-9038-dbad3de6b5da.jpg)

While you using the Secure Note for storing password, using normal fonts instead of monospaced fonts is expected because it is hard for the application to decide which parts of the note would be password that should display with monospaced fonts.'
Otherwise, would it be a feature reqeust?

**Comment by PhilippC** [comment]
as @Small-Ku  pointed out, passwords should go in the password field, so please use the default template (standard entry) and put the password in the password field (or an additional protected field).
