### ISSUE TITLE
Custom field "application"

### ISSUE THREAD

**Issue by darkdragon-001** [PhilippC/keepass2android#657]
Use custom field "application" instead of URL or title to automatically match current app and password entry.

**Comment by Small-Ku** [comment]
Would your idea same with #531 ?
#531 is in the [1.08 milestone](https://github.com/PhilippC/keepass2android/milestone/7).
So, if #531 is what you want.
You might close this duplicated issue and comment in #531 instead.
And then wait for 1.08 release.

**Comment by thousandsofthem** [comment]
There should be more than one "application" attribute to be useful - multiple apps can use the same credentials

**Comment by tastyratz** [comment]
What field is used by https://github.com/bpellin/keepassdroid ?
#531 referenced a field used by another keepass app. If one is just being picked, Should the same one be used for consistency if users switch apps?

**Comment by eLIANT-TechnologyServices** [comment]
I access one bank's login page using multiple ID/PWD credentials:  self, wife, kids, business, etc.  I used KP2A and  agreed to use autofill.  Now KP2A always and only autofills that one ID, even if I want to log in as another user.  Can I manually get around this limitation by adding entries to the KP Advanced tab?  I already have this one Name/Value pair:
KP2A_URL_1 ::  androidapp://com.ifs.banking.fiidNNNN  (N is digits)

If I replicate that pair, I assume Name would end in URL_2, but what would be Value?

**Comment by PhilippC** [comment]
@eLIANT-TechnologyServices you can change this in settings - app - password access - automatically return...
