### ISSUE TITLE
[Feature] ability to trust other CA

### ISSUE THREAD

**Issue by Baptizein** [PhilippC/keepass2android#660]
Hi,
I use Keepass2android via Webdav, and despite the addition of my certificate of certification authority in Android, the app gives me the following message on start:
java.security.cert.cert.CertPathValidatorException: Trust anchor for certification path not found...

However, the certificate is good, it seems especially that it doesn't see the certification authority certificates added by the user (me).

Can you add an option to make this possibility... possible?

(I think I found something to help: https://stackoverflow.com/questions/21306336/android-2-3-x-javax-net-ssl-sslhandshakeexception-java-security-cert-certpathva/46465722#46465722 )

**Comment by PhilippC** [comment]
sounds like a duplicate of https://github.com/PhilippC/keepass2android/issues/419. Please test with the 1.07-pre3 https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by Baptizein** [comment]
Hello

I tested the alpha version, it works perfectly ! 
 

Thank you !

**Comment by incendor** [comment]
I get this exact same error in 1.15-pre0

My setup:

kdbx file hosted on an SSL secured WebDAV share on my NAS which is accessible via nginx reverse proxy.
Accessing the NAS and kdbx file on any other device works perfectly fine, the certificate is recognized and valid.

When I try to unlock the DB on my recently purchased Samsung Galaxy S25 Ultra, after entering the master password, I get the exact error above.

EDIT: my certificate is a Let's encrypt that is being automatically and correctly renewed by my nginx.

Any new ideas on how to resolve this?

**Comment by PhilippC** [comment]
just an idea: Many newer phones no longer trust the old DST Root CA X3 that Let’s Encrypt used to cross-sign.
Maybe your NAS is still sending that expired chain?

echo | openssl s_client -connect example.com:443 -servername example.com -showcerts

Look for "DST Root CA X3" — if present = problem.

**Comment by incendor** [comment]
If I access the WebDAV share through my desktop browser, the cert comes back as valid. (Access https://kp.f-x-a.de/ and click "cancel" to reproduce)

Issued by: Let's Encrypt E8, hierarchy says ISRG Root X1/E8/[my cert]

EDIT: I was just this morning able to fix it. I removed and reconfigured the nginx proxy host pointing to the WebDAV share on my NAS and for some reason it works now.
