### ISSUE TITLE
Fingerprint quick unlock issue

### ISSUE THREAD

**Issue by Suroboro** [PhilippC/keepass2android#663]
After upgrading my Note 9 to Android Pie stable, I am no longer able to unlock my database using the fingerprint and see a long error message starting with "error initializing fingerprint unlock".

**Comment by Wetwhere** [comment]
I had the same issue.  I uninstalled/reinstalled KeePass and now fingerprint unlock works fine

**Comment by Suroboro** [comment]
It was the first thing I tried (once with clearing cache and data before uninstalling) but it hasn't solved the issue..

**Comment by Suroboro** [comment]
Problem solved by itself :) After multiple reinstalls and whatnot, today the fingerprint quick unlock started suddenly working! Hopefully, the issue won't return.

**Comment by Wetwhere** [comment]
I have found that if I change the Android fingerprint settings (add/remove fingerprint, etc.) the red exclamation mark in KP2A returns.  The problem can be solved by disabling and reenabling fingerprints in KP2A.

**Comment by PhilippC** [comment]
@Wetwhere  that's documented and expected behavior.
