### ISSUE TITLE
Configurable Autofill

### ISSUE THREAD

**Issue by kleinarne** [PhilippC/keepass2android#665]
When logging in to websites that require TOTP, I cannot use autofill because I cannot configure KP2A to fill the OTP field with the TOTP value.

Furthermore, some websites may require a combination of a password/PIN and a TOTP, so being able to configure a form field's content would be great - something along the lines of 
_on page **github.com/login**, the form field with the ID **password** is filled with **{PIN}{TOTP}**_

**Comment by PhilippC** [comment]
I don't believe this is possible with the current Android Autofill architecture.
