### ISSUE TITLE
Dialog Selection Displaying Incorrectly

### ISSUE THREAD

**Issue by Topher2014** [PhilippC/keepass2android#667]
I've been having issues when I select Keepass2Android keyboard. When selecting the lock icon, the dialog box no longer shows clear options but instead says:
"Search for entry with %1$s 
Open the keyboard 
 Touch any field" 
or
"Close the keyboard
Press the back key.
Open the keyboard
Touch any text field." 
The former if I haven't chosen an entry, the latter if I have. 
Also, the icons that used to say "username" and "password" after selecting an entry now say "ABCredential input se." 

Essential Phone running updated, stock Android.

**Comment by IronJunkie** [comment]
Duplicate  #641 (return of #377 & others)

& same issue for me

**Comment by PhilippC** [comment]
should be fix in 1.07-pre4 (available on https://play.google.com/apps/testing/keepass2android.keepass2android)
