### ISSUE TITLE
Cannot add new entry or see some menu items in the app

### ISSUE THREAD

**Issue by brafaar** [PhilippC/keepass2android#670]
Since the last update (1.06f) I cannot add new entries to my database (the + icon is missing). I cannot see some items in the menu as well, such as Synchronize database.

I am comparing with another phone I have which has the same app version but 5he system language is English. 

I am using a LG G4, Android Version 6.0, system language Spanish. 

Can it be that some options in this version are lost when the app is in Spanish?

**Comment by PhilippC** [comment]
Sounds like you have opened the local backup of the database. Please select "Change database" on the password screen, then make sure you open the actual database from the recent files list and not its Local backup (which is readonly)!
