### ISSUE TITLE
Quickunlock fails to work on Nokia 5.1-Oreo8.0

### ISSUE THREAD

**Issue by go4tidal** [PhilippC/keepass2android#673]
After setting up my new Nokia 5.1 Christmas present found KP2A no longer works with Quickunlock. Previously worked great on S4 Mini/Kitkat. Tried disabling Battery Optimisation but no luck.

Have to say some widgets are affected too, notably UKWeather and Simple Calendar Widget, which fail to update.

Of course KP2A is more important to me and a great app which I use many times a day.

any ideas out there ?

thanks

**Comment by sdex** [comment]
Try this: https://dontkillmyapp.com/nokia

**Comment by go4tidal** [comment]
Thanks for the link sdex. This looked very promising.
I found Evenwell Battery protect version 8.0020.03 amongst the system apps on my Nokia 5.1

I forced Stop on this app but unfortunately it didn't have any effect on the widget updating or more importantly quickunlock on KP2A. Maybe this would have worked in Pie, which the link article referred to, rather than the Oreo on my Nokia.

However I noticed an advanced setting on battery protect, "modify system settings". When I set this to "no" KP2A now appears to work with quickunlock. The widgets still remain frozen. A mystery ?
Unfortunately when KP2A is running Oreo now places a message in the notifications area. "Keepass2Android is running in the background".

So the search continues for a better solution ?

**Comment by Small-Ku** [comment]
> 
> Unfortunately when KP2A is running Oreo now places a message in the notifications area. "Keepass2Android is running in the background".
> 
The notification is normal on Oreo. There is nothing to do while it is a original Android Oreo feature. (Removed in Pie)

**Comment by PhilippC** [comment]
I think it should be possible to configure the Android notifications properly, but there also is an app which lets you hide this notification: https://play.google.com/store/apps/details?id=com.iboalali.sysnotifsnooze
