### ISSUE TITLE
Keepass doesn't display OneDrive files that are shared from another user

### ISSUE THREAD

**Issue by cmruffin** [PhilippC/keepass2android#679]
If an owner of a keepass database shares a directory with me, and add it to my OneDrive, I can see it in the OneDrive Android app but not the OneDrive file picker in android2keepass.

**Comment by drovosekovanton** [comment]
The same thing, OneDrive shared folder doesn't work.
Steps to reproduce: ask someone to share with you any folder with database in it.
Add shared folder to your OneDrive.
Try to open database inside that added folder from Keepass2android.
Result: although you can see added folder, you can't see any file in it

**Comment by Dave-Lowndes** [comment]
Having just tried to set up such a shared database, I can also confirm this problem.
Has it been officially reproduced/validated so that it will be looked into for a fix?

**Comment by ardusprime** [comment]
Same issue... can see shared file on onedrive app but not through keepass2android app when I try to specify the database file.

**Comment by pddulfer** [comment]
Same issue for me. What needs to be done to request this is looked at?

**Comment by MatthewGy** [comment]
I also need a fix, the problem is discussed in #463 as well. I promise to donate a big beer if this is being fixed.

**Comment by PhilippC** [comment]
I would like to solve this in combination with https://github.com/PhilippC/keepass2android/issues/55 but unfortunately I am blocked at this and didn't find anybody who can help so far.

**Comment by MatthewGy** [comment]
What help do you exactly need? Which information? 

BTW, RClone (https://rclone.org/) works for me without problems.

**Comment by cmruffin** [comment]
PhilippeC, I have an account for you.  Please send me your email address.

**Comment by PhilippC** [comment]
@MatthewGy Basically I would like to see an answer to my question on https://stackoverflow.com/questions/53972480/onedrive-for-business-account-not-working-with-ms-graph-sdk
But thanks for the hint to rclone. This might help, but it looks like they have a completely different implementation for authorization and file access which seems a bit hard to adopt.

**Comment by PhilippC** [comment]
Finally made it. Please switch to beta and install 1.07b-pre2 (just published to beta, see https://play.google.com/apps/testing/keepass2android.keepass2android). Please click "Change database" (on the password screen), then "Open database", "One Drive", "All files and shared files" (or something else if appropriate) and browse to your file again. This will then use the new implementation. (If you don't re-open the database like this, the old implementation will be used).
Please re-open (or comment) if the issue persists for some reason.
