### ISSUE TITLE
Remember last database, Auto reopen

### ISSUE THREAD

**Issue by ctrlbrk42** [PhilippC/keepass2android#680]
Without requiring manual selection, please remember the last used database, and just have the option to reopen it instead of needing to select it.

I realize it shows a list, but this takes an extra step. I want to always reopen the last database I used.

**Comment by Small-Ku** [comment]
Remember it in what situation? If you just lock the database instead of close it, I think the database will be showed up and ask for unlocking when you re-enter KP2A.

**Comment by ctrlbrk42** [comment]
First open after reboot, first open after phone memory management closed it, etc -- every situation where it's not just locked but instead shows the file selection screen.

Mike

Sent from my phone
________________________________

**Comment by Small-Ku** [comment]
Oh, would your idea same with #416?
It is in the 1.07 milestone.
So, just wait for next release. (BTW, author didnt close #416 yet. Therefore, please dont expect beta channel would include this feature)

**Comment by Small-Ku** [comment]
Could you close this issue while it is duplicated with #416 ?

**Comment by PhilippC** [comment]
thanks, @Small-Ku for helping me cleaning the issues a bit :-)
