### ISSUE TITLE
Migration from netftpandroid to FluentFTP

### ISSUE THREAD

**Issue by Px7-941** [PhilippC/keepass2android#681]
Hi Philipp

I plan to help you with your obsolete netftpandroid and migrate it to the new FluentFTP.
Can you fork this repository https://github.com/robinrodricks/FluentFTP?

Then we can use it as a git submodule like the netftpandroid repository.

Why should we migrate to FluentFTP?
FluentFTP is under development and supports the FTPS protocols better.
There are several issues with the keyword FTP/FTPS.

kind regards

**Comment by PhilippC** [comment]
thanks for offering help. If you can provide an implementation using FluentFTP, I'd be happy to include FluentFTP as a submodule.

**Comment by PhilippC** [comment]
this was done for 1.08-per3
