### ISSUE TITLE
What's the actual procedure to autofill on an android phone?

### ISSUE THREAD

**Issue by skyzoomer** [PhilippC/keepass2android#683]
Could some kind soul describe the step-by-step procedure to autofill logins using an android phone?  I have a Samsung S8 phone.  I plan to store the KP2A database on Google Drive.  Browser Firefox.

Does KP2A automatically recognize the website and allow autofilling the username and password with a single tap?

**Comment by skyzoomer** [comment]
Is this the following the easiest procedure for using KP2A's autofill on my S8 android oreo phone?

A. Sometimes this happens:
1. Open login page using Firefox.
2. Tap in the username field.
.... a) KP2A entry bar appears at the bottom of the screen that shows:
....  | ABC | User | Password | > | DroidIcon | <x | Go | grayed out lock icon 
3. I tap username in the bar but it enters the username for the previous forum I visited.
4. I erase the user name using the <x key in the bar.
5. I tap the Droid icon in the bar.
.... I tap "Select another entry".
.... A list of entries displays.
.... I tap the correct entry.
6. The KP2A bar appears at the bottom again.
7. I tap in the "username" field and then tap "User" in the bar.
.... The correct username fills in.
8. I tap the "Password" field and then tap "Password" in the bar.
.... The correct password fills in.
9. I tap "Sign In" button and sign in occurs properly.

Is this what I have to do using KP2A for every login?

**Comment by Small-Ku** [comment]
I am using a Xiaomi A1 with Android Pie (KeyboardSwap installed).
What I do while there is a error while #562 / #592 / #675 exists:

1. Open the login page
2. Open KP2A myself and unlock via QuickUnlock
3. Find the entry and click on it
4. Return to Firefox
5. Tap in the "username" field & tap "User" in the bar
    -Username fills in
6. Tap the "Password" field & tap "Password" in the bar
    -Password fills in
7. Relock the database with notification

BTW, when the fix of error I mentioned above released, procedure in Android Pie would be:
1. Open the login page
2. Autofill dialog popup
    -If database unlocked:
        3. Click the entry name on the dialog
        4. Username & Password filled in
    -If database locked:
        3. Click "Fill with Keepass2Android" on the dialog
        4. KP2A poped up
        5. Unlock the database
        6. Select the entry (Skipped when only one entry matched the link)
        7. Username & Password filled in

For your S8, Android Pie update would be coming soon in few months, if [news](https://www.xda-developers.com/samsung-galaxy-s8-note-8-android-pie-one-ui-update-roadmap/) are true.

**Comment by user23498723452** [comment]
It seems like the current chrome for Android supports this, but I am not seeing any autofill prompts.

Can anyone explain if anything needs to be done for entries to trigger autofill?

**Comment by Small-Ku** [comment]
> 
> 
> It seems like the current chrome for Android supports the Autofill framework, but I am not seeing any autofill prompts. I'm on Android P, Google Pixel.
> 
> Can anyone explain if anything needs to be done for entries to trigger autofill?

Just go to Setting -> System -> Input and Language setting -> Advance -> Autofill and select 'Keepass2Android'.
PS. I am using Android with Chinese. Those name above is translated by myself. Those name would not accurate at all.

**Comment by skyzoomer** [comment]
> 
> I am using a Xiaomi A1 with Android Pie (KeyboardSwap installed).
> What I do while there is a error while #562 / #592 / #675 exists:
> ..... snip .....

Thanks for posting your procedure.  It too is a bit long.  I'm hoping for auto recognition of the login page and autofill both username and password with 1 or 2 clicks.
Anyone able to do that?

**Comment by Small-Ku** [comment]
The [Accessibility service based plugin](https://github.com/PhilippC/kp2a_accservice_autofill) seems to be what you need but it seems like it only support Chrome. Apart from that, Autofill service on Android Pie would be the only solution now.

**Comment by user23498723452** [comment]
@small-ku Supposedly chrome on Android now supports the Autofill framework. but I can find no clear way to configure it.  it was in beta 9 months ago, is what I can find.

**Comment by Small-Ku** [comment]
> 
> 
> @Small-Ku Supposedly chrome on Android now supports the Autofill framework. but I can find no clear way to configure it. it was in beta 9 months ago, is what I can find.

Em... I dont know how to configure it too. You might see [this issue](https://github.com/bitwarden/mobile/issues/320) also.

**Comment by PhilippC** [comment]
@user23498723452 please see https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md for a description of several workflows. I suggest to use the "Browser based workflow" when using Firefox.

**Comment by eyal0** [comment]
Is the accessibility app still needed? Autofill seems to work for me without it.

Is there a screenshot of what the accessibility app does?

**Comment by PhilippC** [comment]
@eyal0 I consider Accessibility deprecated, but some people have Android <8 which doesn't have the Autofill framework.

**Comment by eyal0** [comment]
Thanks for you prompt reply!  This is what I expected was true.  Excellent work.
