### ISSUE TITLE
Buttons to fill password or username not working

### ISSUE THREAD

**Issue by dolphinkite** [PhilippC/keepass2android#685]
Hi,

It seems for the past many months, I'm back with an unusable app. Whenever I try to login a site, and switch keyboard to Keepass2Android Offline then I press on the lock icon and choose "Select entry" (I am not sure what is the use for the other entry: "Search for entry with com.android.chrome" as this has NEVER EVER yielded anything useful). I then select the entry I want but when I am back to the website's login page, it doesn't auto-fill and if I press the lock icon, I used to have the option to "fill username" or "fill password" but neither are there anymore. just "select another entry" and the useless "search for entry" option.

Using Keepass2Android Offline V 1.06f on a Google Pixel running Android  9 build PQ1A.190105.004

Am I missing something of this app isn't working anymore and hasn't been for many months?

Thanks

**Comment by PhilippC** [comment]
you should see a "Username" & "Password" button in the one-line keyboard?

**Comment by dolphinkite** [comment]
I USED to see those two buttons, but that was MONTHS ago. It's been quite a while since I saw them; they are not there anymore.

**Comment by dolphinkite** [comment]
Oh, indeed, I checked that one-line keyboard and it is now visible. But what is the point of this app without that check-box checked..?

@Nikey646 , thanks for the tip.

**Comment by Nikey646** [comment]
Normally a list containing your username, password, and the additional strings available will appear along side the "Select another entry" options after you have selected your entry. Which is what your original issue is, that isn't appearing as intended.

**Comment by dolphinkite** [comment]
Indeed, that's still gone. But I was also not seeing the 1-line keyboard so I couldn't get to anything. Now I have the 1-line keyboard so I am less concerned that the options to "fill password" and "fill username" are gone. But it should indeed be fixed.

**Comment by chuim** [comment]
I'm having exactly the same issue described here. The list that was supposed to list username, password and custom fields (as it used to) now only ever shows 2, the "select another entry" and "search for...". That's even after I have chosen the former, selected the entry I'm interested at in the app, and back to the keyboard.

**Comment by PhilippC** [comment]
can reproduce with 1.06 but not with 1.07.

**Comment by chuim** [comment]
I was able to fix this by clearing all app data and starting from scratch. I don't know what version I was using though.
