### ISSUE TITLE
Using the Google Drive picker results in "file is only temporarily available" message

### ISSUE THREAD

**Issue by karlhorky** [PhilippC/keepass2android#690]
When selecting a file via the Google Drive chooser, an error message appears that the file is only temporarily available and it needs to be copied to another location for use.

Full error message:

> The file is only temporarily available for Keepass2Android. To use it, you must copy it to another location. Click OK to select a location where the file should be copied.

Phone: Xiaomi Mi A2
OS: Android 9 Pie

![whatsapp image 2019-01-21 at 09 12 37](https://user-images.githubusercontent.com/1935696/51463953-d3459a80-1d64-11e9-9fd7-40d2e8314984.jpeg)
![whatsapp image 2019-01-21 at 09 13 16](https://user-images.githubusercontent.com/1935696/51463954-d3459a80-1d64-11e9-9502-93af207b9fc2.jpeg)
![whatsapp image 2019-01-21 at 09 14 04](https://user-images.githubusercontent.com/1935696/51463955-d3459a80-1d64-11e9-9ff2-9c943687c87a.jpeg)

**Comment by PhilippC** [comment]
yes, please!

**Comment by karlhorky** [comment]
Hm, just tried again and I cannot reproduce anymore :(

Closing this issue for now. Will re-open if it happens again.
