### ISSUE TITLE
Omit backup and recycle bin

### ISSUE THREAD

**Issue by bajoodoo** [PhilippC/keepass2android#691]
When searching the app and this repository for a way to omit the recycle bin / trashcan from the search results, I stumbled upon the strings.xml where this topic is mentioned in the translations. However, I cannot find it in the app. Is this feature implemented and if so, where can these results be excluded?

**Comment by PhilippC** [comment]
KP2A relies on the search flags of the group. These cannot be altered with KP2A, but you can do so with Keepass2 on windows (Right click the group, select "Edit group" and then go to the Behavior tab). This is usually only required if you have imported data with a tool that doesnt correctly set these values.

**Comment by bajoodoo** [comment]
Ok, I can confirm the deactivated groups are being hidden from the search results, but they are not hidden from choosing "share to kp2a" in a mobile browser :( Do you plan to integrate this, too? Greetings from Karlsruhe :)

**Comment by ned-martin** [comment]
I think I am having the same issue mentioned here:

When I share to kp2a, it auto-finds anything in the Recycle Bin that matches the URL.

Considering all other forms of search don't find these entries, it took me quite a while to figure out why it kept finding things with the wrong password, when I'd changed the password on the correct entry...

**Comment by githubomane** [comment]
> KP2A relies on the search flags of the group. These cannot be altered with KP2A, but you can do so with Keepass2 on windows (Right click the group, select "Edit group" and then go to the Behavior tab). This is usually only required if you have imported data with a tool that doesnt correctly set these values.

In case anyone else stumbles upon this: the setting you need to change is now "Edit Group" => "Properties" tab => "Searching entries in this group" => "Disabled"
