### ISSUE TITLE
Permission denial: opening provider android.support.v4.content.Fileprovider

### ISSUE THREAD

**Issue by jorgheymans** [PhilippC/keepass2android#701]
Any idea what would be causing this ? Trying to open my database over webdav, this was working before at some point, couple of months ago. Could the fact that I am using the beta channel be the culprit ? [Complete error message](https://imgur.com/a/IKrus74).

**Comment by jorgheymans** [comment]
might it have something to do with my phone getting upgraded to Android 9 ?

**Comment by ximex** [comment]
i have the same problem. could it has something to do with the new kdbx file format 4?

**Comment by PhilippC** [comment]
@jorgheymans This sounds a lot like an issue with accessing a local file. As you say you are opening the database over WebDav, I suspect you have a locally stored key file? If so, please re-select the key file and try again!
@ximex no, this is an error which means KP2A cannot access the file at all. I suggest to click "Change database" and then "Open database" and browse to the file again, this will update the file access permissions for KP2A.

**Comment by PhilippC** [comment]
if my suggestions do not solve the issue, please re-open.

**Comment by jorgheymans** [comment]
Thanks indeed Keepass was pointing to a locally stored cached file which due to phone change no longer existed. Adding the database anew from scratch solved the issue !
