### ISSUE TITLE
Password generator

### ISSUE THREAD

**Issue by michofst** [PhilippC/keepass2android#702]
Would it be possible to add a "at least one" functionality for the generator to match the password guidelines, e.g. at least one number and one special character?

King regards,
Michael

**Comment by nala5081** [comment]
I totally agree. I sometimes might go through many passwords that are just upper and lowercase letters before I see one with a symbol or even a number.

**Comment by amarradi** [comment]
It is possible to use options like the [pwgen](https://linux.die.net/man/1/pwgen)
The -B option is very important to me. This increases the readability/learnability of passwords.

> -B, --ambiguous
> Don't use characters that could be confused by the user when printed, such as 'l' and '1', or '0' or 'O'. This reduces the number of possible passwords significantly, and as such reduces the quality of the passwords. It may be useful for users who have bad vision, but in general use of this option is not recommended.

**Comment by PhilippC** [comment]
merged into https://github.com/PhilippC/keepass2android/issues/81
