### ISSUE TITLE
Keepass2Android Offline no longer in Google Play Store

### ISSUE THREAD

**Issue by mb882** [PhilippC/keepass2android#704]
Keepass2Android Offline has disappeared from the Play Store. Is this intentional or is Google arbitrarily removing apps again?

**Comment by PhilippC** [comment]
Google has removed the app

> Issue: Violation of Deceptive Ads policy
> --
> We don’t allow apps that contain deceptive or disruptive ads. For example, we don’t allow:Ads that aren’t clearly labeled (screenshot included)
![20190402_030147_pst](https://user-images.githubusercontent.com/5421734/52299338-701f4f00-2985-11e9-80bf-9c201ec20bce.png)

I doubt they understood why I am linking to the regular version and I certainly don't agree that this is a deceptive add.

I have sent an appeal message and am waiting for a response which should come during the next 2-3 days.

**Comment by PorygonZRocks** [comment]
Iirc linking to other apps (even for something like this) counts as an ad. Even if it shouldn't really count as an ad, it does.

**Comment by PhilippC** [comment]
I have removed that button as the Google Play team kept their decision. I have uploaded a new apk and am waiting for acceptance.

**Comment by PhilippC** [comment]
it's now back in Play store.
