### ISSUE TITLE
Select entry from search do not show Notification

### ISSUE THREAD

**Issue by Offerel** [PhilippC/keepass2android#708]
Version: 1.07-pre4
Device: Samsung Galaxy S9 / Android Pie

The notification with buttons for username and password, are not displayed, when a entry is found and selected via search.

Howto reproduce:
* Given is that there are multiple entries in the database, for example multiple Firefox Accounts. Now search for example for the phrase "firef". > Multiple entries are found > select one of the entries from the list > the  details for the entry are opened, however no notification is shown.

* Select another entry by only "browsing" through  the entries > select some entry > notification is shown correctly

**Comment by Offerel** [comment]
Maybe it has something to do with #653 directly. It seems that the notification is missing because the keyboard try to switch to the simple keyboard, but can't for some reason. But that's only a assumption from my side, i can be completely wrong.

**Comment by szeiger** [comment]
This notification is also missing for me since the Android 9 upgrade on my Galaxy S8+ but it makes no difference whether I select from a search or from the main list.  The KP2A keyboard works and the "Database unlocked" notification is shown normally.

**Comment by PhilippC** [comment]
could you please test if this is fixed in 1.07-pre6 which I have just published on https://play.google.com/apps/testing/keepass2android.keepass2android?

**Comment by Offerel** [comment]
At least for me, it's fixed now. I can search a entry > select It > KP2A keyboard is switched on > notification is displayed. If expand the notification, i have both buttons for copy username/password.

Thx for the fix.

**Comment by PhilippC** [comment]
closing this for now. If the error re-occurs, please comment/reopen.
