### ISSUE TITLE
[FR] TOTP button in Keyboard

### ISSUE THREAD

**Issue by Offerel** [PhilippC/keepass2android#709]
I know we have problems with the build-in keyboard already, but would like to have a dedicated button for the TOTP field in the "Simple-Keyboard". Specially since Android 9 we cant use the PopUp anymore, the only way to access the TOTP value is by copy the value to the clipboard, since that value isnt available by the button between password- and lock button.

**Comment by PhilippC** [comment]
@Offerel the solution provided by @dbw9580  is the suggested way to do it.
