### ISSUE TITLE
Only unmask single field when showing protected value

### ISSUE THREAD

**Issue by matzedo** [PhilippC/keepass2android#71]
when having a record with multiple secured fields (e.g. default password field and additional customer fields) and you want to display the hidden value of one secured field, all secured fileds will be displayed.
I recorgnized this while using the TOTP plugin and only wanted to have my current token visible, but the app is showing all protected values at once, including the password and the TOTP seed.
I would suggest when selecting to unhide a field, that only this specific field value will become visible and not every value related to the current record. #

**Comment by feiming** [comment]
Since TOTP code valid for a short time, there's no need to mask it. However, it need to show the validity of the code. The simplest implementation is by make the code slowly disappear as it get closer to expiry.

**Comment by squid314** [comment]
I think that this is an extremely valuable feature. I frequently use my phone alongside my desktop and need to read and retype some values. I use protected fields to store answers to security questions as well as other stuff, and it would be nice to be able to display only the 1 or 2 security answers I need out of the 3-5 that are stored.

**Comment by SotongDJ** [comment]
When I try to get TOTP code in public region, showing TOTP secret content make me feel uncomfortable as the CCTV may record the content on my phone's screen.
