### ISSUE TITLE
Firefox autofill now mostly works with some exceptions 

### ISSUE THREAD

**Issue by gabrielambuehl** [PhilippC/keepass2android#711]
Thank you for fixing the Firefox autofill in the latest pre release. 

Sadly, it seems it did not work for all sites. For example, on m.aliexpress.com I still get the toast instead of the autofill pop up. This previously worked with web view based Firefox Focus but it seems like Mozilla finally switched it to gecko as I now see the toast in focus too.

**Comment by Small-Ku** [comment]
In my opinion, it is a expected behavior.
![toast](https://i.ibb.co/r4yx0xM/result-2019-02-07-18-52-24.png)
Maybe KP2A can't deal with multiple domain now.

**Comment by gabrielambuehl** [comment]
I see PhilippC tagged it;

Small-ku: personally I would assume that if multiple domains were submitted, I should be able to pick from any credentials that match one of the domains...

**Comment by whisdol** [comment]
Please also add support for Firefox Nightlyhttps://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora

**Comment by gabrielambuehl** [comment]
Confirming it is fixed, thank you.
