### ISSUE TITLE
Yubikey 5 NFC not working

### ISSUE THREAD

**Issue by Erwyn** [PhilippC/keepass2android#713]
Hi there,

I've seen #564 so it might be related although I'm quite new to these Yubikey things so not sure.

I added my Yubikey 5 NFC for authentication with KeepassXC on Linux ( so password + challenge response).

On Keepass2Android, I select "Password + Challenge response for KeepassXC", and then use my YubiKey through NFC to get the challenge response but it never works. Communication seems fine but always tells me that composite key is invalid.

Any idea on what I'm doing wrong?

**Comment by jorgheymans** [comment]
Yup this would be cool

**Comment by Erwyn** [comment]
Hello @jorgheymans .

Thanks for the pointer to the ykDroid issue. I changed my encryption to Chacha20 and Argon 2, and reset the master password + challenge response and now everything is working like a charm.

Thank you very much!

**Comment by who93** [comment]
Hi,
I have the same issue, a database created in KeePassXC with Yubikey5 challenge is not working on KeePass2Android. How can I change the encryption to Chacha20 and Argon2 in KeepassXC application on linux?
Thanks!

**Comment by nvhaver** [comment]
Hi @who93,
In case you didn't find the feature by now, once you have opened your database in KeePassXC, from the top menu select Database >  Database settings. There you will find the encryption algorithm and key derivation function used in the second tab (Encryption) on the left. There you can also change these properties of the database.

Thanks to this thread I was able to get my setup working, so thanks to everyone, definitely including the awesome teams of KeePass2Android, KeePassXC and Yubico!
