### ISSUE TITLE
Re-enable autofill if disabled by accident

### ISSUE THREAD

**Issue by mmirg** [PhilippC/keepass2android#715]
How do I re-enable autofill for an application if I disable it for an input field by accident? The UI for disabling input is quite confusing and has no verification mechanism and I've tapped it by accident a few times now.

**Comment by gabrielambuehl** [comment]
+1

The GUI is not really very well though out. It's too easy to hit the disable button and I honestly can't figure out how to edit the list

**Comment by PhilippC** [comment]
you can long-press a field which you want to auto-fill and click the AutoFill button, even after you disabled autofill for it. KP2A will then offer to re-enable. What other solution would you suggest?

**Comment by mmirg** [comment]
There are some applications that do not seem to allow or expose the AutoFill button. It would be nice to have some way to access the list of applications for which auto-fill has been disabled and re-enable it from within keepass2android for these corner cases.

**Comment by gabrielambuehl** [comment]
The long press approach works for Firefox but it is not very obvious, so I do second the wish for an editable list in the settings

**Comment by Perlover** [comment]
The AutoFill button doesn't occur in such cases. Just tried it... I see only "Paste" and "Add search engine" or only  "Paste" button. I have Android 10, Note 9, Firefox 68.7.0

**Comment by Perlover** [comment]
OMG! I found option in your program about this! Settings -> Application -> Password access -> AutoFill function ->  Disabled AutoFill targets

I have Russian translated UI so menu texts may be different

**Comment by strongui** [comment]
Why is this closed? I still don't see a way to edit the disabled list.

**Comment by PhilippC** [comment]
see @Perlover 's comment:  Settings -> Application -> Password access -> AutoFill function -> Disabled AutoFill targets

**Comment by cooltronicpl** [comment]
> you can long-press a field which you want to auto-fill and click the AutoFill button, even after you disabled autofill for it. KP2A will then offer to re-enable. What other solution would you suggest?

No
