### ISSUE TITLE
Keepass2Android with Nextcloud and 2FA Enabled

### ISSUE THREAD

**Issue by raffiiii** [PhilippC/keepass2android#717]
Hello,

I was trying to use Nextcloud with 2FA enabled together with Keepass2Android. I created API credentials for keepass2android but still I receive "unsupported auth scheme []" when trying to use an "Owncloud" or "WebDAV" database.

KR

**Comment by starsoccer** [comment]
@raffiiii were you able to solve this? If so can you post how so others including myself can fix the issue.

**Comment by raffiiii** [comment]
No. :(

**Comment by starsoccer** [comment]
😞 thanks anyways.

Can you post your web server config or provide any more details? I am trying to figure out how the cause so I can fix it myself. I have 2 servers one where it occurs and one where it doesnt so trying to see if there is something common between all broken ones.

**Comment by frankmcc** [comment]
Same issue here.  Any hope of a resolution?

**Comment by starsoccer** [comment]
I was able to resolve it by adjusting the url and then using an app password to login

**Comment by infidelus** [comment]
Can you explain what you changed to fix it?  I've just installed Nextcloud and enabled 2FA and even with the app password I get the same unsupported auth scheme.

**Comment by starsoccer** [comment]
Are you selecting nextcloud or webdav. I dont remember which I used, but Id try both. The webdav you need to add the extra ending for webdav specifically as well

**Comment by infidelus** [comment]
Thanks for the reply.  I've tried both Nextcloud and (HTTPS) WebDav.  Nextcloud gives the unsupported auth scheme error, and if I try with WebDav using just the url of the server I get:

https webdav: Cannot connect to file provider service  Received unexpected response: Response{protocol=h2, code=405, message=, url=https://domain url/}

If I try and add the full path to the file (https://domain url/remote.php/Folder/filename.kdbx) it goes back to the unsupported auth scheme error.

**Comment by starsoccer** [comment]
That url for webdav is not correct. It should be `domain/remote.php/webdav/folder/file.kbdx`

**Comment by infidelus** [comment]
Oops, that was just a typo on my part.  I did actually put that in the path when trying to connect ...

**Comment by starsoccer** [comment]
hmm okay then Im not sure what its not working. That is exactly what for my path currently and I am then using an app password

**Comment by infidelus** [comment]
I just had another look in the Nextcloud Files settings and it says the path to use is:
domain/remote.php/dav/files/user/
Unfortunately that doesn't work either.

**Comment by NikuZai** [comment]
I got the WebDev work with 2FA with this solution found here: https://github.com/PhilippC/keepass2android/issues/478#issuecomment-550215625

"I was able to bypass the problem by using an "app-password" generated via nextcloud user menu Settings / Security / Devices&Session / Generate new app password .
These passwords don't contain any unicode chars and you don't have to change the main password for your account." -siegmund42 commented on Nov 6, 2019

**Comment by sjas** [comment]
1. nextcloud web interface: administration settings >> personal: security >> devices & sessions >> create new app password
2. keepass2android: open file >> nextcloud >> 

- nextcloud url: YOUR_DOMAIN/remote.php/dav/files/YOUR_USER/YOUR_FOLDER/YOUR_FILE
- username: from the created app password above
- password: from the created app password above

**Comment by derco0n** [comment]
> 1. nextcloud web interface: administration settings >> personal: security >> devices & sessions >> create new app password
> 2. keepass2android: open file >> nextcloud (not webdav) >>
> 
> * nextcloud url: YOUR_DOMAIN_WITHOUT_PROTOCOL_PREPENDED/remote.php/dav/files/YOUR_USER/YOUR_FOLDER/YOUR_FILE
> * username: from the created app password above
> * password: from the created app password above
> 
> main url part can be found bottom right frame of the webinterface after clicking on 'files settings', there i tells the main path, however mousehovering over the keepassfile in the webinterface gave YOUR_DOMAIN/remote.php/webdav/YOUR_FOLDER/YOUR_FILE

that worked. thanks
