### ISSUE TITLE
[Enhancement] Keyboard Security. Set Keyboard manifest to Incognito 

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [PhilippC/keepass2android#718]
Set Keyboard Securit to Incognito mode. For example you see this in a chrome private tab, the gboard keyboard will stop saving word prediction witch is desired for passwords too. Some banking app do this already.

**Comment by Small-Ku** [comment]
There is a [reference](https://developer.android.com/reference/android/view/inputmethod/EditorInfo.html#IME_FLAG_NO_PERSONALIZED_LEARNING) on Android Developers.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Yes, this is what I was talking about:

IME_FLAG_NO_PERSONALIZED_LEARNING
added in API level 26
public static final int IME_FLAG_NO_PERSONALIZED_LEARNING

Flag of imeOptions: used to request that the IME should not update any personalized data such as typing history and personalized language model based on what the user typed on this text editing object. Typical use cases are:

When the application is in a special mode, where user's activities are expected to be not recorded in the application's history. Some web browsers and chat applications may have this kind of modes.
When storing typing history does not make much sense. Specifying this flag in typing games may help to avoid typing history from being filled up with words that the user is less likely to type in their daily life. Another example is that when the application already knows that the expected input is not a valid word (e.g. a promotion code that is not a valid word in any natural language).
Applications need to be aware that the flag is not a guarantee, and some IMEs may not respect it.

Constant Value: 16777216 (0x01000000)

**Comment by Small-Ku** [comment]
In my opinion, it is not needed to copy the whole text here. It lost its original text format. As a result, it is less readable.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Yes Afterwards I see you linked the anker of this part directly in URL

**Comment by Small-Ku** [comment]
I mean you destroyed it's format. Also, please use the quote format of markdown for quotes. It would be better to separate the original contents and the contents from others.
