### ISSUE TITLE
How to sync between KeePass 2 and KeePass2Android in WLAN automatically?

### ISSUE THREAD

**Issue by thomas-zmo08179** [PhilippC/keepass2android#721]
Hello,

I'm using KeePass 2 on Windows 7 and KeePass2Android on my Android Phone. 
I want to sync automatically the both databases in my WLAN. 
Which possiblity is there without user interaction to sync the both databases?
I don't want to use an online storage like dropbox.

If I want to sync with SFTP, as I see it's needed to install and run a FTP Server/Provider.

Best regards, 
Thomas

**Comment by PhilippC** [comment]
KP2A does not have SMB support (for accessing the file through a Windows share), because this never received lots of attention (https://github.com/PhilippC/keepass2android/issues/82). So either you set up a server (SFTP/WebDav) or you use a third party tool like FolderSync.

**Comment by thomas-zmo08179** [comment]
Thank you Philipp! I've installed and set up a server.
