### ISSUE TITLE
How to sync from Windows to K2A with SFTP

### ISSUE THREAD

**Issue by thomas-zmo08179** [PhilippC/keepass2android#722]
I've installed KeePass on Windows 7 and K2A on my Phone.
I've also installed a SFTP Server on Windows.
At First I created a kdbx database with KeePass on Windows. 
From K2A I'm starting the database on Windows with SFTP if I'm on the same WLAN. 
It is possible to sync from Android --> to Windows, what is done from K2A.
How is it possible to sync automatically KeePass from Windows --> to Android K2A? 

Do I need a SSH Server on my Android phone? Do I need a trigger?

Best reagards,

Thomas

**Comment by PhilippC** [comment]
if you opened the file through KP2A's built-in SFTP option, all changes will be saved to the sftp server immediately if a connection exists (if not, only a local cache copy will be updated and the sync is performed manually or when you save/load when connection exists). Similar the other way round: if your database is changed from Windows, it will be updated when you load/save the DB on Android or when you trigger the Sync from the menu.

**Comment by thomas-zmo08179** [comment]
That is great, it means I just have to set a SFTP server and K2A and KeePass are syncing automatically to each others database. So I don't have to worry about duplicated entries or overwritten new passwort. 

**Android --> Windows**
From K2A to Windows the Synchronisation is done by K2A automatically, because the KeePass database on Windows is the "_master_" database for K2A. 

**Windows --> Android**
But it is not possible over the Sync button on KeePass because I don't have a SFTP provider on my Android phone. As I see, it is not at all necessary: From KeePass to Android the Synchronisation is also done by K2A automatically, because it calls the Kepass database on Windows and gets the new or changed entries to it's own "_slave_" database. 

Thank you very much Philipp :+1:
