### ISSUE TITLE
How to get stored database from Android, if stored on Windows with SFTP synchronisation?

### ISSUE THREAD

**Issue by thomas-zmo08179** [PhilippC/keepass2android#724]
Hello,

I've created a database with KeePass on Windows and opening it with K2A on Android.
If I loose the connection to Windows, because of a reason like lost pc, changed connection, removed database and so on, how can I get a copy of the stored database from Android? 

Is there a possiblity to get the K2A database on Android?

**Comment by PhilippC** [comment]
you mean the internal cache copy? You can select Settings > Database > Export to export it to a location of your choice.

**Comment by thomas-zmo08179** [comment]
Thank you, didn't know it exists :+1:
