### ISSUE TITLE
ADD (+) button gone.

### ISSUE THREAD

**Issue by ilanrab** [PhilippC/keepass2android#725]
BUG?? The app could not load my passwd database from the SD card because the SD card got unmounted mysteriously (happens every 6 months, for some reason.)
After loading the local backup passwd DB, the app let me in. The (+) button was gone. I could not add new entries without this button. 
I restarted the phone, and the SD storage card loaded properly. The (+) button never came back to the app. Ultimately, I had to uninstall the app and reinstall it from the app store. After logging into the app, the (+) button appeared as usual. Anyone else encounter this anomaly?
ir

**Comment by PhilippC** [comment]
the local backup is readonly (to make sure it's never corrupted). Please select settings > database > export and export the file to a new location. Then close and click Change database > Open database and browse to the newly created file.

**Comment by ilanrab** [comment]
What about the MISSING Menu item?????  Please read the message I posted, again!

**Comment by PhilippC** [comment]
the local backup is readonly, so the app does not show menu items for modifying the database.

**Comment by ilanrab** [comment]
I see. Now I understand. In that case, why didn't the ADD button re-appear, after I logged out, forced shut all running apps, then ran the password manager again?  Was the app still using the read-only version?  If so, why does a reinstallation, of the app, allow for read/write access?

**Comment by PhilippC** [comment]
reinstallation removes the local backup, so after that you only have a writable copy. Please note that I have improved selection of the database so this should not happen this way again in 1.07

**Comment by ilanrab** [comment]
Thank you. Sounds good.
