### ISSUE TITLE
Continually crashing after using search or opening a recently saved entry.

### ISSUE THREAD

**Issue by kewlguy2** [PhilippC/keepass2android#727]
How do I get to the toast message that flashes by complaining that my "Gmail account was not initialized correctly" when the front is not permitted for screenshots?

From my computer I have opened & resaved a fresh copy of my database, that works fine, in Google Drive yet on my Fully up to date Samsung Note 9 I am getting repeated crashes.

I tried reordering my Gmail & gsuite accounts I have available for login with no resolution.

Is this a Google Drive issue because I am having issues using the password database stored in my personal gmail Drive folder for my g-suite accounts on both Chrome "Tusk" extension AND now my Android mobile through Keepass2Android 1.06f

**Comment by PhilippC** [comment]
can you please try https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254?

**Comment by kewlguy2** [comment]
The very first suggestion solved the issue on my Samsung Note 9
