### ISSUE TITLE
Password forgot after using fingerprint for awhile. How to reset? 

### ISSUE THREAD

**Issue by Tkam12** [PhilippC/keepass2android#733]
Hi,

I've been using this app for years but recently the app must have updated and didn't allow my fingerprint to unlock. The problem is I must have forgotten my pw cause everything I thought it was isn't working. Is there a way to reset the password? I didn't see that feature. Not sure what to do. Thanks

**Comment by Small-Ku** [comment]
> # What you should know and think about
> If you store important information using Keepass2Android, you should know a little bit about what's going on:
> * Keepass2Android stores your password in an encrypted file. It is *your responsibility* to backup this file regularly and safely.
> * There is no way for anyone, including the app's author, to access the information stored in your password database without 
>   * having the database file
>   * knowing the master password (and additional second factor if you chose one)
>   This means that **if you forget the master password, your database is lost**! So make sure you remember the password and retain any second factor method (if one is used).

Quote from docs of [Keepass2Android](https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md)
You just lose your information in your database.

**Comment by Tkam12** [comment]
Understand that now. I always used to have the master key but I think I had to change like a year ago and that's around when I started using the fingerprint feature evrytime and must have forgotten/new wrote down the new master since I never used it.

I do have multiple achieved files backed up on my Google drive and I know what most of the characters should be just obviously not the exact and I've tried so many combinations... 

Is there a way to get the info from the archived Google drive files? Every time I click on them, they just open right to the KeePass app and ask for the pw. If I could just get the text. I could try creating a new data from that info. 

Let me know. Thank you

**Comment by Small-Ku** [comment]
As I just contribute as a translator, I think the archived files are backups for avoiding lose when the file being destroyed. It might not useful for finding your master password.
As the Keepass 2 official page said,

> If you forget this master password, all your other passwords in the database are lost, too. There isn't any backdoor or a key which can open all databases. There is no way of recovering your passwords.

In my opinion, you might try a brute-force attack on your database to find password. As you remember most of the characters, you might try [mentalist](https://github.com/sc0tfree/mentalist) for generating a list of possible passwords and [mod0keecrack](https://github.com/devio/mod0keecrack) for brute-force attack. BTW, those two software work on personal computers.
I just attach a Windows version of mod0keecrack compiled by myself. And it works for my database.
Reminder: I don't take any responsibility of any lose from using executes inside this zip file.
[mod0keecrack.zip](https://github.com/PhilippC/keepass2android/files/2922908/mod0keecrack.zip)

**Comment by Tkam12** [comment]
Understand. I might try to crack the pw more but I'm not great with computers so not sure if that'll work.

I'll prob just create a new database and start over and try to slowly get all my other pws reset and record them in the new database. I'll write this new master siren in a secure place so this doesn't happen again.

You guys have been very helpful. Thanks for responding!

**Comment by Small-Ku** [comment]
If your problem is solved, please close this issue.
Little reminder: Always set a easy to remember combinationas masterpassword. Like something you like but not a common dictionary word.
