### ISSUE TITLE
Name of share option maybe too long

### ISSUE THREAD

**Issue by Small-Ku** [PhilippC/keepass2android#734]
![result-2019-03-04-09-29-06](https://user-images.githubusercontent.com/16464896/53705531-46f8be00-3e60-11e9-8c18-8fff3c9c2cfc.png)
![result-2019-03-04-09-29-25](https://user-images.githubusercontent.com/16464896/53705532-47915480-3e60-11e9-9de7-426cc7a70480.png)

Two screenshots above show the share menu in Firefox and Chrome in Traditional Chinese.
The share option string (kp2a_findUrl) would be too long. Please remind that Chinese string is shorter than latin languages in most situation. It may be great for shorten it as "KP2A: Find Password". In additon, user-friendly suggestions in #144 are recommended too.

**Comment by Small-Ku** [comment]
Also, condensed font of Chinese and some languages are not pre-loaded with most of Android devices even with Android Pie. In normal Android devices, it would only shown "Keepass2Android: 查找", which means search. As a result, it is not clear enough for users.

**Comment by PhilippC** [comment]
what's your suggestion for Chinese and/or English?

**Comment by Small-Ku** [comment]
In my opinion, it would be better to keep the text in one line. So, keeping it short would be great. Also, the icon would be enough for recognizing the Keepass2Android app. I would suggest “Find Password” and “查找密碼” only. "Get Password from KP2A" would also great but hard to translate in a fluent way for me.

**Comment by Small-Ku** [comment]
Oh, I think get "Get entry/credential" would be nice too.
