### ISSUE TITLE
About translation consistency

### ISSUE THREAD

**Issue by Small-Ku** [PhilippC/keepass2android#735]
If a word has multiple translation and the current translation is not consistent, which tranalation would be more suitable?
These are some example from Traditional Chinese.

- The most used word in the current translation (consistent with most version of the app)
  - Challenge-Response: 質詢-回應
  - AutoFill: 自動填滿
- The official translation from national organization
  - Challenge-Response: 詰問 / 回應 ([NAER from Taiwan](http://terms.naer.edu.tw/detail/2346458/))
- The translation in other Keepass program, like Keepass2, KeepassXC, etc. (consistent with other program and platform)
  - Challenge-Response: 挑戰回應 (KeepassXC)
- The translation from Android (consistent with system)
  - AutoFill: 自動填入 (Oreo+)

**Comment by PhilippC** [comment]
Not sure if I can answer this with authority. It certainly depends on how well each of the options match the original meaning. E.g. I think it's a good thing to be consistent with the system and other Keepass ports - but if other Keepass ports have a bad translation, we shouldn't use it just for consistency! So it's probably a decision which takes everything into account. But obviously it is desirable to have one translation which is then used through the whole KP2A app.

**Comment by Small-Ku** [comment]
Thank you for your reply. ╰(⸝⸝⸝´꒳`⸝⸝⸝)╯
