### ISSUE TITLE
KeePass Pop-Up (disable password pop-up for specifit apps)

### ISSUE THREAD

**Issue by dasgrischa** [PhilippC/keepass2android#738]
Hi there,
I got a question about the pop-up appearing when I open an app (as you can see in the screenshot).
My problem is that I activated app-lock for some of my apps, Facebook as an example. But when I open the app this pop-up (which is useful) hampers me from using my fingerprint to unlock the app.
I always need to tap on my screen first, so the pop-up disappears and then I can use my fingerprint to unlock my app.

So my question is, how can I disable this pop-up in KeePass app? 
It would be nice when I could either disable the pop-up or just deactivate automatic password fill in for specific apps (for the ones which I have fingerprint lock on)

![keepass pop-up](https://user-images.githubusercontent.com/48331536/53980790-813cb680-4111-11e9-94f6-ad624ca31d67.png)

**Comment by Small-Ku** [comment]
In fact, this pop up is from the AutoFill service of Keepass2Android. It seems that this feature is still in a basic stage. Refer to telmer6,

> The "NO THANKS" button should set a persistent flag per application, rather than just dismissing the prompt.

You may also see #488 and #455 for more details.

**Comment by dasgrischa** [comment]
Thanks, gonna write with the guys then, because I can't find the "never" or "NO THANKS" buttons :S

**Comment by Small-Ku** [comment]
Oh, the "No Thanks" button is for saving Password. Sorry for my misunderstanding. BTW, disable AutoFill for specific is what #455 said. Now this feature is in the beta app but it is not yet fully functional. You may wait for next update of Keepass2Android.

**Comment by dasgrischa** [comment]
Alright, thanks @Small-Ku 

I try to get the beta client from the store or wait until the new update. :)

**Comment by dasgrischa** [comment]
Update: 

Enrolled for the Beta app on the Playstore and it works now. I can disable the Autofill option, so the pop-up doesn't appear anymore and my apps are safe from my roommates or colleagues who uses my phone :D

Thanks @Small-Ku

**Comment by Small-Ku** [comment]
While your issue is solved, please close this issue. Also, you might not need to thanks me. You might appreciate the work of developer instead. (人 •͈ᴗ•͈)
