### ISSUE TITLE
Enhancement Request - Improve startup speed

### ISSUE THREAD

**Issue by auanasgheps** [PhilippC/keepass2android#74]
I have noticed that Keepass2Android is always slow to open itself when is not in memory: It takes about 3 seconds to prompt for password.

My database is stored on Google Drive. What happens at startup? Is the database refreshed at this time or after bein authenticated?

I have noticed this problem on both slow and fast smartphones, doesn't make a difference at all. Wiping the app does not help too.

Thanks

**Comment by PhilippC** [comment]
KP2A is a complex and large app, mainly because it's built using Mono for Android (which allows maximum compatibility with Keepass2). I think that this is the main reason, so there's nothing I could do about that. Sorry.
