### ISSUE TITLE
[Question] What is template to put in URL field ?

### ISSUE THREAD

**Issue by the4anoni** [PhilippC/keepass2android#741]
Hello
What is the template for autofilling user + pass in apps ?
I want to put template + Android package name so keepass2android will auto fill password.

Also is there any way to put 2 or more urls for one login and password ?

**Comment by PhilippC** [comment]
If you have enabled the Android autofill service (which was introduced in Android 8), you should see a popup "AutoFill with KP2A". If you select that ,you can search for an entry. After selecting that, KP2A will prompt you to save the app package name in the entry. If there is already a URL, it will add that to a special field, not the URL field. 
When KP2A searches for an entry, it will first look in the URL fields of all entries. If it doesn't find a matching entry, it will look in all other fields, so it doesn't matter what name you give to them.

**Comment by the4anoni** [comment]
@PhilippC but I want to add that info via PC version of Keepass.

I use phone version ONLY for reading password database.

**Comment by Small-Ku** [comment]
> When KP2A searches for an entry, it will first look in the URL fields of all entries. If it doesn't find a matching entry, it will look in all other fields, so it doesn't matter what name you give to them.

Just add a additional field with a name you like and fill the package name in.

**Comment by the4anoni** [comment]
Thanks, this worked :)
