### ISSUE TITLE
Crashes when clicking Search button while on Keepass Keyboard

### ISSUE THREAD

**Issue by kingp0dd** [PhilippC/keepass2android#743]
On latest version as of today on Samsung note 8 Android 9.0.

Steps to recreate
1. Change keyboard to Keepass Keyboard
2. Unlock Keepass2Android
3. Click Search button

**Comment by jschof** [comment]
Same issue on Galaxy S9 Android 9.0. 

"Workaround" is to force stop the app and then launch app again. App does not crash if you don't switch to Keepass Keyboard (I.e. do cut/paste instead)

**Comment by PhilippC** [comment]
please switch to 1.07 beta to get a fix:
https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by jschof** [comment]
Beta seems to have fixed the problem and no other issues found to date.

Thanks!
