### ISSUE TITLE
Pre6 immediately crashes upon trying to open a database 

### ISSUE THREAD

**Issue by gabrielambuehl** [PhilippC/keepass2android#748]
I get immediate crash upon trying to decrypt my database (even before entering passphrase) with the latest pre release

**Comment by gabrielambuehl** [comment]
More accurately, it may not be a proper crash but it immediately bumps me back to the db selection screen

**Comment by PhilippC** [comment]
thanks for the feedback. Unfortunately I cannot reproduce this on any of my devices. Can you collect a logcat? If not, maybe you can revert to 1.06 (regular channel), enable debug logging, then upgrade to beta again and send me the log?

**Comment by PhilippC** [comment]
can you try if this disappears if you disable the KP2A autofill service in the system settings?

**Comment by khampf** [comment]
Unable to start KP2A:
<pre>
03-18 12:00:27.125 24191 24191 E AndroidRuntime: FATAL EXCEPTION: main
03-18 12:00:27.125 24191 24191 E AndroidRuntime: Process: keepass2android.keepass2android, PID: 24191
03-18 12:00:27.125 24191 24191 E AndroidRuntime: java.lang.IllegalArgumentException: need to provide at least one DataSet or >
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at android.service.autofill.FillResponse$Builder.build(FillResponse.j>
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at md5fecc842b695051371a671ed1d12dddd6.AutofillServiceBase.n_onFillRe>
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at md5fecc842b695051371a671ed1d12dddd6.AutofillServiceBase.onFillRequ>
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at android.service.autofill.AutofillService.lambda$-android_service_a>
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at android.service.autofill.-$Lambda$svbjmB3NFhHnuZrn67G14PFSJlY.$m$0>
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at android.service.autofill.-$Lambda$svbjmB3NFhHnuZrn67G14PFSJlY.exec>
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(Hand>
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6590)
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java>
03-18 12:00:27.125 24191 24191 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
</pre>

**Comment by khampf** [comment]
> can you try if this disappears if you disable the KP2A autofill service in the system settings?

Stops crashing immediately, you are right on track

**Comment by Sanaki** [comment]
Same story here, repeated crashing any time I'm interacting with text fields in any app as long as autofill is enabled, including the kp2a app itself.

**Comment by gabrielambuehl** [comment]
Can confirm, turning off autofill fixes the issue. I am traveling so a logcat will be difficult to do for the next few days

**Comment by C-O-D** [comment]
Well, I unsigned from Beta, uninstalled the Beta and reinstalled the regular version, which worked but ALL sttings were gone. Then I enabled debug log, signed to beta again, reinstalled Beta which didn't work again and then I was searching for the logfile about half an hour without success.
The I read the hint about disabling autofill which worked. Since I was able to start the app again I then tried to open my database (which is located on my Fritz NAS) which took another hour since I forgot how I dis this before (certificate and access errors vom Feinsten). Afterwards had to to setup the complete app from scratch which took another half an hour - Cheers
I would really appreciate if you would implement an export function for the settings, what do you think?
Final result: Pre6 is working with autofill disabled...

**Comment by elrac** [comment]
I'm having the same issue on my Moto G6 (Android 8.0.0, Kernel 3.18.71). However I don't know how to disable the autofill service through he system settings.

**Comment by C-O-D** [comment]
Here's my log (finally) 😉

https://paste.ubuntu.com/p/6h3KWqYhT2/

**Comment by PhilippC** [comment]
I have just published 1.07-pre7 to Play store. Could you check if the issue is fixed?

**Comment by Zorks** [comment]
> I have just published 1.07-pre7 to Play store. Could you check if the issue is fixed?

Just received the 1.07-pre7 update, re-enabled autofill, and tested the autofill service. I can confirm that it is now working for me at least (Samsung Note8, android 8.0.0, kernal 4.4.78).

**Comment by Sanaki** [comment]
That fixed it, thanks.

**Comment by C-O-D** [comment]
autofill issue is fixed for me too, thanks!

**Comment by khampf** [comment]
Works perfectly for me
