### ISSUE TITLE
Pre6 immediately crashes

### ISSUE THREAD

**Issue by C-O-D** [PhilippC/keepass2android#749]
Pre6 immediately crashes on start - I can type nothing but restart or close the app.

Android 8.0, HTC U11

**Comment by PhilippC** [comment]
thanks for the feedback. Unfortunately I cannot reproduce this on any of my devices. Can you collect a logcat? If not, maybe you can revert to 1.06 (regular channel), enable debug logging, then upgrade to beta again and send me the log?

**Comment by PhilippC** [comment]
can you try if this disappears if you disable the KP2A autofill service in the system settings?

**Comment by PhilippC** [comment]
please comment on #748. Duplicate.
