### ISSUE TITLE
Crash when trying to send debug logs

### ISSUE THREAD

**Issue by Karreg** [PhilippC/keepass2android#752]
... and since we can't send debug logs, there's nothing much to say... 😢 

version 1.07-pre6 on Android Pie (OnePlus 6T)

**Comment by PhilippC** [comment]
I just fixed a potential crash when sending debug logs in the pre6 release, so can you please double check you're at that version? (settings - about)?
Can you collect a logcat?
In earlier versions, you had to enable Debug logging, then close the app completely (lock&close database, swipe out from history) and after restarting, sending debug logs worked.

**Comment by Karreg** [comment]
Yep, double checked, I got the update just 1 hour ago, before testing...

Your fix seems to work, but only when the option is not already checked.

What I did to fix the issue:

- Disable logging
- Close database
- Force close KP2A
- Load KP2A and DB
- Enable logging
- Close database
- Force close KP2A
- Load KP2A and DB
- Send logs

Following this scenario worked. Maybe there are useless steps, but I could not send logs before disabling and enabling the option again...

I tried a more adapted scenario:

- Disable logging
- Close database
- Force close KP2A
- Load KP2A and DB
- Enable logging
- Send logs

And it works. Of courses logs are empty, but it makes sense...
