### ISSUE TITLE
Support autofill in Firefox Fenix / Firefox Preview

### ISSUE THREAD

**Issue by gabrielambuehl** [PhilippC/keepass2android#758]
Firefox Fenix (basically rewrite of Firefox Android) is starting to come along nicely but sadly, autofill currently does not work. Nightly builds available at https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly/latest

**Comment by PhilippC** [comment]
is there any other app which can autofill into Fenix, i.e. is it supported by the browser itself?

**Comment by einsweniger** [comment]
autofill works for me with the f-droid version. are you certain that it's set up correctly?

**Comment by gabrielambuehl** [comment]
With latest version of Fenix (now Firefox Preview) from the playstore it works when I manually select the sie in keepass2android. When I just press autofill it searches for the browser's package name instead of the site url which obviously does not find anything useful.

k2a is definitely setup correctly, in stable Firefox and other apps it works like a charm with autofill.

**Comment by einsweniger** [comment]
Ah, now I get your problem. Yes, that's true. You're forced to search for the correct entry, since it's only matched against the running app and not the URL. Thank you for the clarification

**Comment by pipip** [comment]
where does this have to be fixed? (receiving package name instead of URL)
I have the same issue with Kiwi browser (chromium)

**Comment by jonalmeida** [comment]
Hello! Here's a similar issue filed for another password manager to whitelist Mozilla browsers: https://github.com/bitwarden/mobile/issues/477

**Comment by gabrielambuehl** [comment]
Strangely on latest Firefox preview from play store I can't even get the Keepass2android drop down to display anymore, not even with long tap on password field..

**Comment by anonymous-user** [comment]
> When I just press autofill it searches for the browser's package name instead of the site url which obviously does not find anything useful.

This is how it behaves with Firefox Nightly for me. Is this something that needs to be updated in K2A?

**Comment by gabrielambuehl** [comment]
According to the discussion linked to regarding bitwarden I would assume so

**Comment by caesar** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/87

**Comment by caesar** [comment]
@PhilippC now that this has been merged (some time ago) any chance of a new release including this? On beta channel at least? Thanks! 🙂

**Comment by PhilippC** [comment]
I had to pause working on KP2A for a while and I'm currently in the process of answering hundreds of support e-mails. After that, I will try to build an update.
