### ISSUE TITLE
KeyboardSwap Plugin - Android 9 warning

### ISSUE THREAD

**Issue by auanasgheps** [PhilippC/keepass2android#760]
Hi,
I have updated my device to Android 9.
**Every time** I use KeyboardSwap Plugin, I get a message from the system telling me this application was made for a previous version of android and could not work properly and I should chck for updates.

Yes, the plugin works fine but the message is annoying.

Actually this app was made to target Jelly Bean API 16. Are you planning to increase it at least to Oreo?

Thanks

**Comment by DeXeDeXeD** [comment]
I have the same annoying issue. Hope the dev will address it 😄

**Comment by DaFlowah** [comment]
I'm facing the same issue on OnePlus 5 on Pie stock rom (OxygenOS).
Not a big deal, but still pretty annoying.

**Comment by PhilippC** [comment]
fixed
