### ISSUE TITLE
Add TOTP from Keepass2android

### ISSUE THREAD

**Issue by emmaliddell** [PhilippC/keepass2android#770]
Right now, it seems like the only way to add a TOTP seed to Keepass2android is to open the database file on a desktop app like keepassxc.

There appears to be no way to set up a TOTP / Google Authenticator OTP directly from Keepass2Android.

**Comment by dragoangel** [comment]
Actually there is a way: create custom protected field with name "otp", and text: "key=your secret key without spaces and in uppercase", and click save.

**Comment by giopas** [comment]
@dragonangel but if I try to do so I still cannot see the codes changing in the app. What am I missing?

**Comment by saudiqbal** [comment]
I would like to see this too, so that I can scan the QR code.

**Comment by kc0bfv** [comment]
I got a suggestion similar to dragoangel's to work.  I created three custom fields, TOTP Seed, TOTP Settings, and TOTP.

The value for seed is the TOTP key, the TOTP settings are usually "30;6", and leave TOTP's value empty.  I copied these from an existing TOTP in my DB that worked.

After saving the entry, the value in TOTP was set and updated correctly.  It would be cool if this process were simpler and supported QR code entry.

**Comment by stefan-muc** [comment]
@dragoangel It's easier: use that custom otp field and paste in full _otpauth://totp/[...]_ string from QR code. Keepass2Android can handle that too and this is even compatible with KeePass Plugin KeePassOTP so you can use that on desktop too.

In case I need it, I can for now scan the QR Code using my barcode scanner app, and copy the string to Keepass2Android.

**Comment by nitrocode** [comment]
@kc0bfv your instructions worked for me on android, thank you. Here's a clear summary for future me.

1. Create additional string `TOTP Seed=<totp-token>` with protected ticked
1. Create additional string `TOTP Settings=30;6` without protected ticked
1. Create additional string `TOTP` without protected ticked

This is less intuitive than mainstream apps and could be simplified. For example, the settings can default to `30;6` without being explicitly set and much like 1password, the totp-token could be shown when editing and turn into the totp-generated-code-every-30 sec when in non-edit mode.

**Comment by dragoangel** [comment]
Hi @nitro I'm stopped using totp in keepass and move to authy :/ far ago. My comment is 2years old man and at time of writing it - it works. Don't know if it works right now and not interested actually.

**Comment by stefan-muc** [comment]
> @stefan-muc I tried your method using `TOTP Seed=otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example` but it didn't work.

@nitrocode What exactly did you do? Where does the string `TOTP Seed` come from?
* create a field `otp`
* put in full `otpauth://totp/[...]` string
* done

(By the way: It's no good idea to edit your post and then mention more people. I'm just replying because I visit this topic out of curiosity. An edit doesn't generate a new notification mail.)

**Comment by frederickjh** [comment]
> I can for now scan the QR Code using my barcode scanner app, and copy the string to Keepass2Android.

It would be nice to be able to scan the QR Code then open it with Keepass2Android so we can select the the DB entry to add it to or start a new entry. Or just scan it with the app or with **QR Plugin for KP2A** to start the same process.

**Comment by becbe** [comment]
> > @stefan-muc I tried your method using `TOTP Seed=otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example` but it didn't work.
> 
> @nitrocode What exactly did you do? Where does the string `TOTP Seed` come from?
> 
> * create a field `otp`
> * put in full `otpauth://totp/[...]` string
> * done
> 
> (By the way: It's no good idea to edit your post and then mention more people. I'm just replying because I visit this topic out of curiosity. An edit doesn't generate a new notification mail.)

@stefan-muc 
Thanks - works perfect - you just need some useful hints from cooperative people to find a simple solution

**Comment by stefan-muc** [comment]
Thank you very much! I'm so excited to see the implementation running!

**Comment by PhilippC** [comment]
should be available from https://play.google.com/apps/testing/keepass2android.keepass2android shortly. Please let me know what you think!

**Comment by saudiqbal** [comment]
There is no option to add the code using the camera for QR code.

**Comment by PhilippC** [comment]
@squabbi correct, this is another issue (#1575 )
