### ISSUE TITLE
Not working with DEX on Samsung Galaxy S9

### ISSUE THREAD

**Issue by bazhub** [PhilippC/keepass2android#779]
keepass2android doesn't start in DEX mode on Samsung Galaxy S9 (Android 9).

**Comment by Small-Ku** [comment]
Would #625 helps?

> just one thing you might try is to disable the "screen protection" in the app settings. Maybe this causes this behavior.

If not, please provide debug log.

**Comment by fcrozat** [comment]
duplicate of #625
