### ISSUE TITLE
Beta tester group

### ISSUE THREAD

**Issue by BobVul** [PhilippC/keepass2android#782]
With the shutdown of Google+, the beta tester group as linked in the Readme and as the feedback link on the App Testing page is no longer available.

Is there an alternative anywhere?

**Comment by PhilippC** [comment]
currently not. Anybody has a good suggestion?

**Comment by BobVul** [comment]
Discourse seems popular for open-source projects, but you'd need a server to host it on (I'd be happy to provide one for at least a few years but you'd be relying on a random guy...). Being open-source there'd always be the option of migrating it across hosts.

Google Groups also seems reasonably popular and is unlikely to disappear anytime soon (then again Google's track record isn't great). It's a bit like Usenet groups/mailing lists?

If a more chatroom-like interface is acceptable, then Gitter might be an option. Being a chat, you don't really get threads the same way as the other two, but I think you do get history search.

**Comment by JohnLGalt** [comment]
I'd point to Redditt, seeing as how The Android ßeta program is using it as a replacement for the G+ Android Beta program community, and it seems to be working well.

However, that comes with its own caveats (as would most other established systems out there).

**Comment by PhilippC** [comment]
this has long been solved by Google Play: https://play.google.com/apps/testing/keepass2android.keepass2android
