### ISSUE TITLE
Unable to open database when keeautoexec references a local PC file

### ISSUE THREAD

**Issue by insanityinside** [PhilippC/keepass2android#787]
After the latest update, it appears there's KeeAutoExec/AutoOpen functionality attempting to load my additional databases, but they're referenced via %USERPROFILE% for loading on my PC, as you can't use paths relative to the file itself. Unfortunately it doesn't fail gracefully on the Keepass2Android app, and fails to load any of the files as it can't load my second database.

Any chance of a graceful failure or the ability to disable the functionality, or a way to override the path for KP2A to, e.g. point at a dropbox relative location?

**Comment by insanityinside** [comment]
Just to confirm, once I closed and reopened the database, it solved the issue by asking me.

**Comment by insanityinside** [comment]
Another update - unfortunately it appears setting the location in KP2A overwrites the location set for the PC. Is it possible to specify the location on KP2A as an override instead of replacing the main URL / file location?

**Comment by Karreg** [comment]
If you want to avoid opening the secondary database on your mobile, you can add the "IfDevice" attribute to your keeautoexec entry.
The documentation for that is in the keeautoexec plugin archive. Works like a charm.

**Comment by insanityinside** [comment]
I managed to disable the auto-open, but what I'm ideally looking for is to specify an alternate (Dropbox in this case) path to the same file on Android, if it's possible.

**Comment by PhilippC** [comment]
If you go to settings - database settings - configure child databases you can
 * select which entries should be opened on the current Android device
 * copy entries which do not work (e.g. local files on a PC) and then change the URL for those
This should close this issue.

**Comment by insanityinside** [comment]
I did this, but it changed the URL on the PC side so they wouldn't open on there anymore. URL field was changed to a dropbox:// URL, which the PC version of keepass didn't recognise.
