### ISSUE TITLE
Dropbox api authorization error when system language is Chinese

### ISSUE THREAD

**Issue by alien41** [PhilippC/keepass2android#793]
When system language is Chinese, the URL opened in the browser is https://www.dropbox.com/1/connect?locale=zh_CN_#Hans&k=ax0268uydp1ya57&n=0&api=1&state=oauth2%3A4e907712d7d87201208dade5816e3228, and return “This app is not valid”.

When system language is English, the URL opened in the browser is https://www.dropbox.com/1/connect?locale=en_US&k=ax0268uydp1ya57&n=0&api=1&state=oauth2%3Ab86db2df6c0f41dc739053401f48324d, and that's no problem.

**Comment by KGMIT** [comment]
I'm not sure how to look into my error specifically, but I suspect that it is the same. It started happening when I switched my system language to Arabic, can no longer open a Dropbox stored database.

**Comment by PhilippC** [comment]
this seems to be a result of https://github.com/dropbox/dropbox-sdk-java/issues/115
