### ISSUE TITLE
pCloud Unterstützung: Root "leer"

### ISSUE THREAD

**Issue by mgkai** [PhilippC/keepass2android#794]
Hallo, hab gesehen, dass pCloud unterstützt wird. In der Verzeichnis- bzw Datei-Auswahl unter "Root" ist alles leer, die App sieht keine Verzeichnisinhalte (sind natürlich jede Menge da). Der Dialog wirkt auch irgendwie nicht responsiv. Also wieder zurück zu Dropbox.

**Comment by codeRetard** [comment]
+1 on this.

Just opened a new thread for this post in English as well just in case the devs might have an issue with German language.

**Comment by PhilippC** [comment]
I'm fine with German but I prefer English as most users can participate in the discussion then. Closing this in favor of #796
