### ISSUE TITLE
Unified biometric authentication dialog

### ISSUE THREAD

**Issue by Rakleed** [PhilippC/keepass2android#795]
Please use Unified biometric authentication dialog.

https://developer.android.com/about/versions/pie/android-9.0#biometric-auth

**Comment by lizardb0y** [comment]
+1 BiometricPrompt supports multiple biometric options. One of my devices is a Samsung Tab S4 which has an iris scanner instead of fingerprint reader. I'm having to use my Mooltipass Mini to unlock the database on this device which is a PITA™.

**Comment by daevidvincent** [comment]
Just found a new competitor named "KeePass DX". You should check it out. It's the only other Android app I've seen in years that gives you a bit of a run for your money. One killer feature that I really love is it will use my Iris biometric on my Samsung Galaxy S8 not just fingerprint!

**Comment by RobBiddle** [comment]
Thanks for the suggestion @daevidvincent .  I don't really want to switch apps, but based on keepass2android milestones, it looks like this feature might take a year or so to make it into production.  As more and more Android phones do away with fingerprint scanners this will greatly affect the usability of keepass2android.  I'll keep checking back in hopes the support is there when I get a new phone.  Wish I was more proficient in C/Java so I could help out with this project.

**Comment by df03438** [comment]
so, will or does  support Google pixel 4 face unlock

**Comment by lparsons** [comment]
Any chance we can get this feature moved to an earlier milestone? I'm willing to support the effort, either with $ or perhaps code.

**Comment by df03438** [comment]
I concur let this great app lead the way ahead of the other password apps. I would support some $, too. I am delaying my Pixel 4 purchase until the spring. Keeping my fingers crossed. I hate loosing the fingerprint feature, but no replacement coming is unpleasant.

**Comment by CarlosLopezES** [comment]
I also want this feature, please. 

I will not change the app because i have using it for years and I like it, I prefer to wait some time

**Comment by schwabe** [comment]
Unless someone else creates a PR for this I think I am going to invest some time in the next two weeks to implement this.

**Comment by PhilippC** [comment]
If you have time to do so, I would gladly receive pull requests. But let's discuss a bit how this should be done. I would like to switch to using biometric prompt using androidx and fully replace fingerprint manager. However, there must be a transition phase where people who have configured fingerprint unlock can still use the old implementation to unlock, but then need to be informed they should upgrade to the new implementation.
Using biometric prompt from Androidx means migrating all uses of support libraries to androidx. I guess this might come with some pain.

**Comment by daevidvincent** [comment]
If this is a simple one-time change to the user, I don't think anyone has any problem reauthing with their print again or whatever. I say make a "breaking change" if it gets the feature out faster. And if it comes with the added bonus that ANY biometric the phone supports (or is actively using) can be used then I'm 100% in support of it! :) A little pain for a lot of gain!

**Comment by df03438** [comment]
I concur with daevidvincent

**Comment by PhilippC** [comment]
This might work for you, but i bet there are thousands of users who don't remember their master password and rely on fingerprint. This sounds insane, but you don't know how many support mails I'm writing every day 😭

**Comment by df03438** [comment]
how can that be?  It is the most important pswd of any... its the master.  my gosh... if they use native Keepass on windows then at some point in time they need their master password.. even on android occasionally master pswd has to be re-entered after a reboot or app update.  I wouldn't let the fools prevent for the masses a technology upgrade into the future .   My opinion.

**Comment by PhilippC** [comment]
don't get me wrong. I consider this issue one of the top priority issues in the next milestone. But doing it right shouldn't take much more time and it makes sure I'm not updating the app for some users at the cost of some others.

**Comment by yelch** [comment]
I think best would be to create a new version 2.0 as a separate app.
In 1.x you inform the users that there is a 2.x and that they need to turn off fingerprint and set a password.
If someone starts 2.x and 1.x is installed, users must enter the password, if they don't know they can switch to 1.x and set it otherwhise 1.x could be prompted for uninstall (if new bio features are set, app just starts).
If someone starts 1.x and 2.x is installed and configured app closes and starts 2.x

**Comment by CarlosLopezES** [comment]
2.0 app has to be a HUGE change... this maybe its small for most of users.

Maybe only the update for Pixel 4 users?

**Comment by RobBiddle** [comment]
Why would there need to be a transition period/re-enrollment?  If the user already has fingerprint unlock enabled in keepass2android, and the device is running Android 9+ then I can't think of any reason it wouldn't be acceptable to switch the API call for authentication from **FingerprintManager** to **BiometricPrompt**  without notifying the user of the change.  Unless I'm completely misunderstanding something it seems like fingerprint unlock would continue to function without interruption (i.e. needing to re-enroll fingerprint unlock / re-enter master password.)

The main problem will likely be supporting older devices running Android <9.  That would require either a keepass2android version split for Android 9+ devices, or maintaining support for both **FingerprintManager** AND **BiometricPrompt**, accepting the increase in keepass2android app size/complexity.

**Comment by schwabe** [comment]
Porting to androidx as part of using BiometricPrompt as my first contribution to the project seem a little to big of a task. Especially I haven't worked with Xanarim before. 

For this discussion did anyone even check if swithing from FingerprintManger to BiometriPrompt does even invaldiate the old authentiation data? Maybe androix just wraps it in a compatible fashion?

**Comment by schwabe** [comment]
So I setup the build environment but not having worked with Xamarin/Visual Studio for Android apps I was completely overwhelmed and did not find out how to setup adding the androix biometrics support library. 

But looking at the source code of the android.xbiometrics it looks like it just wraps the fingerprint cryptoobject: https://github.com/aosp-mirror/platform_frameworks_support/tree/androidx-master-dev/biometric/src/main/java/androidx/biometric

**Comment by PhilippC** [comment]
I'm trying to that, but I don't have too much time this week and the next.

**Comment by Utini2000** [comment]
I don't want to crash this ticket but:  
How does the biometric implementation work anyway?

My .kdbx is locked with a password that only I know and that is not written or stored anywhere else. 
Now I will unlock my .kdbx by using my facial scan. Will the data of my facial scan be like a second master password that gets added to my .kdbx? 
Or will Android "store" my master password somewhere and pass it on to the app once it verfies my facial scan?
Or is there going to be a token that is associated with my facial scan, .kdbx database and hopefully my specific device so no one can steal the token and re-use it on their device?

Thanks! :)

**Comment by PhilippC** [comment]
This is now in beta (https://play.google.com/apps/testing/keepass2android.keepass2android), 1.08-pre2. @ all Pixel 4 users: please test and report whether face unlock works. I didn't have such a device for testing.

@Utini2000 The implementation is the same as with fingerprint: if you enable full unlock with biometric prompt, the app will store the encrypted master password in Android's secure storage (there is an info text about this in the app). It's up to the user to decide whether they want to accept this.

**Comment by psmedley** [comment]
Thanks!!! Tested here with Pixel 4 and works fine. One suggestion, the app states that fingerprint hardware is detected - this should be changed to biometric.

**Comment by Sanyen** [comment]
I can confirm that this works, thanks for all your hard work. Just the wording needs some fixing as mentioned by +psmedley.

**Comment by schwabe** [comment]
Same result here on a Pixel XL. Works fine but wording is still fingerprint. I also had to switch to deactivated and enabled again to make it work.

**Comment by PhilippC** [comment]
thanks for the feedback! I am aware of the wording issue but decided to roll out asap and change the texts later.

**Comment by betasheet** [comment]
Works for me as well (Px 4), though, when unlocking, I see the face unlock prompt appear a second time briefly after acknowledging the first one. It disappears on its own with a "Face operation cancelled" message. This doesn't happen for "quick unlock", only if the DB was "closed" fully.

**Comment by Utini2000** [comment]
@PhilippC Thanks for the beta and the quick explenation. Is there a place I could learn and ask about this Android secure storage? I am worried about what apps could extract data (my master password) from this secure storage and if it gets more risky with a rooted Android device. 
So far my master password has never been stored anywhere else than my had and my RAM. Now that Android secure storage of my P4 is going to be a new permanent storage.

**Comment by wombat01** [comment]
Thank you for the implementation, it works ;-) Would it be possible to open direct after recognition without having to click confirm button?

**Comment by PhilippC** [comment]
@wombat01 which confirm button do you mean? On my devices with fingerprint sensor I don't have to confirm anything. Can you post a screenshot?

**Comment by betasheet** [comment]
I'm pretty sure wombat01 talks about the "Confirm" button shown in Figure 2 here: https://developer.android.com/training/sign-in/biometric-auth#no-explicit-user-action

This page also mentions how you can disable it. Not entirely sure if that's desired here though - without the prompt, you'd automatically unlock just by opening the app and "showing" your face.

**Comment by Sanyen** [comment]
It looks like [this](https://drive.google.com/file/d/15NNQXlBgIQo0NWxXsj7Qd4od4xFqXbiz/view?usp=drivesdk). Sometimes I get prompted a 3rd time if I hit confirm fast enough on the 2nd prompt.

**Comment by PhilippC** [comment]
@Utini2000 see https://developer.android.com/training/articles/keystore

**Comment by wombat01** [comment]
> @wombat01 which confirm button do you mean? On my devices with fingerprint sensor I don't have to confirm anything. Can you post a screenshot?

[https://i.ibb.co/j3qqjDM/x-Screenshot-Nov-6-2019-8-23-38-PM.png](url)

**Comment by PhilippC** [comment]
thanks for all of your feedback! I am currently preparing 1.08-pre3 with
 * no need to "confirm" authentication
 * no longer showing biometric prompt immediately after authentication.

The text are not updated, yet.

**Comment by PhilippC** [comment]
@daevidvincent I don't have a Samsung device with Iris scanner. Did you enable this? https://stackoverflow.com/questions/55145785/android-biometricprompt-shows-iris-scanner-on-samsung-running-android-pie

**Comment by daevidvincent** [comment]
@PhilippC yes, that setting is currently (and has been) set. But what is also curious as per the initial post way up above about KeePassDX is that it "just worked" with my IRIS when I loaded their app. I didn't have to do anything. So perhaps there is another setting in your code that needs to be investigated to respect that default biometric flag or something?

**Comment by PhilippC** [comment]
hmm, I don't see that they do anything special. The main difference I see is that they use an older version of androidx.biometric and use targetSdkVersion=28, whereas I use 29 (=Android 10). https://source.android.com/security/biometric says that in Android 9, only fingerprint is supported, but that seems weird if it works in another app...

**Comment by daevidvincent** [comment]
I AM on Android 9 (pie).... so that could be the reason. Can you lower the value and we can see?

**Comment by PhilippC** [comment]
@daevidvincent please try https://www.dropbox.com/s/z2o2azc6pfilata/keepass2android.keepass2android-1.08-pre3-targetSdk28.apk?dl=0

**Comment by wombat01** [comment]
> thanks for all of your feedback! I am currently preparing 1.08-pre3 with
> 
> * no need to "confirm" authentication
> * no longer showing biometric prompt immediately after authentication.
> 
> The text are not updated, yet.

1.08-pre3 👍👍👍 Perfect, works great. Thank you.

**Comment by daevidvincent** [comment]
> @daevidvincent please try https://www.dropbox.com/s/z2o2azc6pfilata/keepass2android.keepass2android-1.08-pre3-targetSdk28.apk?dl=0

unfortunately that didn't work (I mean, it installed, but it didn't prompt or do anything IRIS/facial, only FP still)

**Comment by Sanyen** [comment]
Hello folks, just tested the new beta release. Thou i get the face unlock prompt, its failing to unlock the database. Just errors out a few secs after the prompt. *Can't verify face*, not sure what the underlying issue is. Any other users with the pixel 4 xl having this issue?

**Comment by Sanyen** [comment]
Great work Phil, everything is working great. A few beers coming your way. Everybody else on this thread, remember to do the same.

**Comment by lparsons** [comment]
Pixel 4 XL working great here. For sure some beers coming. Thanks for such
a quick update.

**Comment by L3Nerd** [comment]
Can confirm: Pixel 4 XL is working. Beer is on the way - Prost!

**Comment by Javier-Giral** [comment]
Work like a charm on my Pixel 4XL. Many thanks and a beer is on its way!

**Comment by PhilippC** [comment]
@daevidvincent I think that according to https://issuetracker.google.com/issues/142150327 the difference between versions of androidx.biometric makes the difference. Google decided not to accept Iris as secure enough. That was changed since early betas of the library.

**Comment by dolphinkite** [comment]
@PhilippC, 

I'm using the offline version of keepass2android (blue icon) and it seems that even though I joined the beta program (link above), I'm not receiving a beta update of the offline version.

Like others, I want to use the face unlock feature on my Pixel 4.

Is there something specific I need to do for this version?

Thanks

**Comment by CarlosLopezES** [comment]
Is there an estimated date for it to be published in the stable version?

Thank you very much.

**Comment by timokl-github** [comment]
> This is now in beta (https://play.google.com/apps/testing/keepass2android.keepass2android), 1.08-pre2. @ all Pixel 4 users: please test and report whether face unlock works. I didn't have such a device for testing.

Unlocking the database worked on the Pixel 4. The UI still mentions "fingerprints" in setup / database, should be renamed to "unlock with biometric information" or similar.

**Comment by fklemm** [comment]
Using a Pixel 4 XL - works just fine, thank you so much!

**Comment by neilpryde1984** [comment]
using a pixel 4, also works well!!!

Thanks a lot

**Comment by pilot23** [comment]
I have installed the 1.08 Pre3 on Pixel 4XL but can't choose in settings to the new faceunlock. Do i have to setup something else? Otherwise there is no question from the app to use camera access.
In setup / database there is also a message in fingerprint setting that there is no hardware (Pixel4xl has no fingerprint hardware).

**Comment by neilpryde1984** [comment]
> I have installed the 1.08 Pre3 on Pixel 4XL but can't choose in settings to the new faceunlock. Do i have to setup something else? Otherwise there is no question from the app to use camera access.
> In setup / database there is also a message in fingerprint setting that there is no hardware (Pixel4xl has no fingerprint hardware).

You have to grant keepass permission to the biometric sensors. I took the easy way and cleared all storage, cache from the app. during the next startup, the app asked for the permissions

**Comment by pilot23** [comment]
> > I have installed the 1.08 Pre3 on Pixel 4XL but can't choose in settings to the new faceunlock. Do i have to setup something else? Otherwise there is no question from the app to use camera access.
> > In setup / database there is also a message in fingerprint setting that there is no hardware (Pixel4xl has no fingerprint hardware).
> 
> You have to grant keepass permission to the biometric sensors. I took the easy way and cleared all storage, cache from the app. during the next startup, the app asked for the permissions

Thank for your assist but it doen't help. I have delete userdata and cache also deinstalled the app itself. There is no question for sensor access, only contacts and storage. I have version 1.08-pre3.

**Comment by daevidvincent** [comment]
Same here on Galaxy S9


Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by christianhaessler** [comment]
I've tried this with a Samsung A50 and it doesn't work. It's Android 10 and i use face unlock right now. If you need more Information just ask.

The error occurs on enabling biometrics for the database.

Debug logs are not showing anything:
```
19.05.2020 20:16:43:405 -- CFS: OpenWhenNoLocalChanges
19.05.2020 20:16:43:406 -- CFS: hashing cached version
19.05.2020 20:16:44:588 -- CFS: Updated Cache
19.05.2020 20:17:15:349 -- status message: Initializing...
19.05.2020 20:17:15:351 -- status submessage: 
19.05.2020 20:17:15:393 -- status message: Lade Datenbank…
19.05.2020 20:17:15:400 -- status submessage: Führe Schlüsseltransformationen durch…
19.05.2020 20:17:15:408 -- status submessage: Entschlüssele Datenbank…
19.05.2020 20:17:15:410 -- status submessage: Entschlüssele Datenbank…
19.05.2020 20:17:15:412 -- status submessage: Lese Datenbank ein…
19.05.2020 20:17:15:438 -- ReadXmlStreamed: 25ms
19.05.2020 20:17:15:440 -- status submessage: 
19.05.2020 20:17:15:442 -- status message: Aktualisiere lokale Sicherungskopie...
19.05.2020 20:17:15:506 -- LoadDB OK
```

The error message onscreen is a java failure. I can't copy it but i did a photo:
![20200519_201903](https://user-images.githubusercontent.com/1273151/82365127-88976980-9a10-11ea-85c4-b2e1ac651c79.jpg)

**Comment by PhilippC** [comment]
I think google doesn't consider face unlock secure enough on some (or all?) Samsung devices. Can you try with fingerprint?

**Comment by christianhaessler** [comment]
sorry for answering this late. On the a50 the fingerprint sensor is on the display and not really working. I've tested this on my samsung a8 (2018). The fingerprint does not work as well. I don't get any failure but the fingerprint is not recognized. I tried the same with my banking app and this is working.

After a few tests i installed the public version of keepass2android (1.07b-r0) and the fingerprint sensor worked as expected.

**Comment by dniku** [comment]
I see conflicting reports here about whether the current beta implementation works. Has anybody tested it on any of the Samsung tablets, and in particular the Tab S6 Lite? I am considering purchasing the latter, and the lack of a fingerprint sensor seems to be the only major blocker.

**Comment by dniku** [comment]
In the app, I get a notification that biometric hardware has been detected and a question whether I want to enable it. When I tap "Yes", I am taken to a screen where I have an option to enable full biometric unlock. When I tap it, I get the following:

![Screenshot_20200918-103046_Chrome](https://user-images.githubusercontent.com/1315874/93569504-4a985b00-f99a-11ea-8be2-2f37445e7bd8.jpg)

(I switched away from KP2A to take a screenshot)

Samsung Tab S6 Lite, face unlock only, no fingerprint reader.

**Comment by PhilippC** [comment]
@dniku sounds like you did not setup a fingerprint in your device biometric settings?

**Comment by dniku** [comment]
@PhilippC this tablet does not have a physical fingerprint reader, only face unlock.

**Comment by PhilippC** [comment]
unfortunately Google doesn't consider face unlock safe on some devices and doesn't allow to use it with secure storage.

**Comment by dniku** [comment]
I guess this is out of scope for this issue report, but can this problem be reported in a more user-friendly way?
