### ISSUE TITLE
pCloud Support - Empty Root folder

### ISSUE THREAD

**Issue by codeRetard** [PhilippC/keepass2android#796]
Hi,

Been a long time user of the app and have been waiting for the pCloud support for some time as I am a Linux user and pCloud is my cloud storage of choice. I happily downloaded and installed the latest update just now and tried it but after logging in to the pCloud account and giving Keeaass2Android access to the pCloud it just shows a blank screen with "root" written on the top.

Needless to say I have numerous directories on the root of my pCloud storage, one of which stores my KeePassXC file but none are displayed for me to choose from.

Any help is much appreciated.

**Comment by PhilippC** [comment]
@gilbsgilbs do you have an idea on what could happen here?

**Comment by gilbsgilbs** [comment]
Thanks for mentioning me.

Yeah, it's (kind of) normal @codeRetard. For obvious security reasons, KP2A doesn't get access to the whole storage but only a specific directory: "Applications/Keepass2Android". Therefore, you only see the content of this specific directory which is empty at the moment.

I do recognize this should be made more intuitive or should be properly documented somewhere at very least.

Feel free to reopen if I happen to be wrong.

**Comment by gilbsgilbs** [comment]
I just saw that another issue has been opened for the exact same reason. If this happens to be a major painpoint for end users, maybe we could open another issue to discuss on how we could make this behavior more clear. I'm not sure what's the proper way to get this solved.

**Comment by PhilippC** [comment]
one simple option was to create an info text (like with the Dropbox-App-Folder storage) which is displayed when clicking the pCloud option?

**Comment by rdwilson** [comment]
Workaround:
In Pcloud, choose the database and set it as an "offline file". Double tap and choose kepass2android as the default. Webdav wouldn't work for me when I tried to sync but the offline file method works fine.

**Comment by dbareis** [comment]
> Workaround:
> In Pcloud, choose the database and set it as an "offline file". Double tap and choose kepass2android as the default. ... but the offline file method works fine.

This works for read only?  I have no idea what any of the text in the following message is telling me:

![PDRIVE-Screenshot_20210521-122254](https://user-images.githubusercontent.com/295230/119072979-cc5fed00-ba2f-11eb-8037-4c9ce11383ed.jpg)

**Comment by PhilippC** [comment]
@dbareis You get this if you go through the pCloud app. why can't you use KP2A's built-in pCloud support (Open file - pCloud)?

**Comment by dbareis** [comment]
Hi,

To me, the attached message wasn't clear enough, and if it was required I don't think clicking OK created the directory.  In any case I recollect creating the directory and adding the keepass file and others into this directory and keepass showing me "root" without any files shown.  I just tried it again and it seems to work.

![KeePassPcloudMessage](https://user-images.githubusercontent.com/295230/119280316-3b2d8800-bc74-11eb-8036-d380d0af97ca.jpg)

**[CURRENTLY]** This storage type will only request access to the Applications/ Keepass2Android folder. If you want to use an existing database from your PCloud account, please make sure the file is placed in this folder.

**[SUGGESTED]**  Using PCLOUD requires the database file to be contained in the **PCLOUD** folder "Applications/Keepass2Android" (or a subfolder of).

_At least add "tree" to the end of the existing message and remove the incorrect space after the slash._

_Other than that I assume it's actually the Keepass app with the requirement, what isn't this dirctrory configurable (for this or similar could services)?_

**Comment by Timbo104** [comment]
Hi,
Long time user of Keepass2Android. Just transferred from DropBox to pCloud and having difficulty understanding how to point to the location of my database. If I click on the PCloud storage type button I receive the warning message that dbareis shows in his note, but I can't understand what I need to do. If I click OK I get the empty Root screen.

At present my database file is sitting in a keepass folder within my documents folder on pCloud.

Can a user that has got this working tell me (in simple language!) what I need to do.

Thanks,
Tim

**Comment by dbareis** [comment]
> @dbareis You get this if you go through the pCloud app. why can't you use KP2A's built-in pCloud support (Open file - pCloud)?

Just to clarify, this was through the keepass2android app.  I don't think it works correctly if you start off with no folder.  I seem to have got it going by manually creating the folder and keepass file in the folder you require.

I also notice that maybe if I had waited long enough maybe the folder wouldn't have been blank, when I tried it on my Samsung tablet which I'd forgotten about up until today, it too ages for the cloud link dialog to come up and during that time it looked empty (no toast progress messages etc).

I'm not real happy that the app decides how my data is structured or that it gives it the name "Keepass2Android" (no configuration for location) for a file that can be accessed by "Keepass2Android" amongst many other apps apps (not "Keepass2Android").

**Comment by Timbo104** [comment]
Hi dbareis,
I was using KP2A's pCloud support and that's when I get the message:
'This storage type will only request access to the Applications/Keepass2Android folder. If you want to use an existing database from your PCloud account, please make sure the file is placed in this folder.' 

I then clicked on OK and I get the Empty Root screen.

Firstly I'm not clear where KP2A wants the Applications/Keepass2Android folder and like PhilippC I'm not happy about having to move my database file to a different folder.

I'm beginning to regret having moved from DropBox to pCloud as I didn't have this (and other) problems.

Tim

**Comment by dbareis** [comment]
@Timbo104 
FYI: You got the names all wrong in your post 

There were a few things that made me wonder whether I'd made a mistake at first but after setup everything has just worked :-)

As I suggested above create the directory yourself and maybe add at least one random file in there so you can expect to see it.

I have added a picture (I have my whole Windows 10 portable directory there and hate that I had to misname it and move it from where it should be):

![github, keepass, pcloud](https://user-images.githubusercontent.com/295230/122840602-cc5c5100-d33d-11eb-84c6-a250b708d245.png)

**Comment by Timbo104** [comment]
Sorry about the names. I was trying to be polite!

Thanks for your reply, particularly the screen shot. That makes it very clear.

I'm debating whether to continue with pCloud (to store my KeePass data) or whether to stick with my free DropBox storage which lets me place my files wherever I want, which is what I prefer.

Tim

**Comment by dbareis** [comment]
I'm not worried about the use of names, but you got the names in the wrong places, you need to swap their positions around to address the intended people correctly (like "PhilippC" I'm ..." ==> like "dbareis" I'm ..." etc)

I have got a fair bit of lifetime storage with drive and really, it seems keepass was the main reason I was using dropbox so I'd like to remove a cloud provider (I'm using google drive for other files).  

I'd like @PhilippC to allow configuration of the path (I'm assuming the restriction is his and not pdrive's), but at least my windows computer is actually better off (as pdrive allows you to map locations which I really like, not sure if that can be done in dropbox now, but I just had a quick look and if it's possible, its not obvious how to do it):

![pdrive sync](https://user-images.githubusercontent.com/295230/123010428-ed867580-d401-11eb-84fb-3d592f5bcf8a.png)
