### ISSUE TITLE
It's impossible to open the single-row keyboard for entrys that have OTP additional string

### ISSUE THREAD

**Issue by roman90sv** [PhilippC/keepass2android#799]
When i delete additional OTP string, the problem disappears. 
since v1.07-r1 (Android 8.1.0)

But, TOTP generation is working properly: https://i.imgur.com/npou3px.jpg

**Comment by dragoangel** [comment]
Vote up, after upgrade keyboard begin working really strange. Previous flow:
when I opened app with login, I switched to Keepass2Android, find needed record and my keyboard aumotically switch to one-line login pass keyboard, I switched to my app with login screen and proceed login.
Now:
After I switched back to my app with login screen the keyboard have NO selected password, and if I choose find one in K2A it not helping ether 😑

**Comment by dragoangel** [comment]
I'm now downgraded to https://github.com/PhilippC/keepass2android/releases/tag/1.06f and all work fine. Will wait for 1.08f version

**Comment by roman90sv** [comment]
**dragoangel**
> I'm now downgraded to https://github.com/PhilippC/keepass2android/releases/tag/1.06f and all work fine. Will wait for 1.08f version with bugfix
Я еще заметил, что на старом андроид 4.4 диалог смены клавиатуры всегда открывается автоматически после успешного поиска записи по url из браузера. Но на 10м MIUI (redmi note 5) диалог почти на всех сайтах не открывается. Приходится вручную вызывать диалог (долгий там по пробелу). Проблему можно решить плагином Keyboardswap, который сам переключает клаву на кипас, но для него требуется через режим отладки присвоить android.permission.WRITE_SECURE_SETTINGS, а для этого в свою очередь требуется зарегистрировать micloud и залогинить смартфон (иначе миюай не позволяет через консоль раздавать права приложениям). Такие вот дела. И еще раздражает, что плагин оставляет свое окошко в интерфейсе недавних приложений.

**Comment by dragoangel** [comment]
@roman90sv
I'm always use KeyboardSwap App so I'm not see any issue 😅. It align my base requirements in configuration.

**Comment by dragoangel** [comment]
Good morning GPlay autoupdated my K2A. This such a pain.

**Comment by JohnLGalt** [comment]
I am experiencing the same behavior as dragoAngel has listed below, and it has been happening with the 1.07 releases, even when I was a ßeta tester, to the point where I left the ßeta program to revert to 1.06 stable version.

Now Google Play store has updated me to version 1.07-r1 and I'm experiencing the same issue again.  Please move 1.07 back to ßeta status until this issue can be resolved.

It is 100% reproducible with 1.07-r1 and never occurs with 1.06f.

> 
> 
> Mi MIX2 (MDE5), Android 8.0 (OPR1.170623.027), MIUI 10.3.1.0 (ODEMIXM)
> Vote up, same issue here after upgrade to 1.07f. **Any** record that have OTP record can't be seleted at K2A keyboard.
> _Previous flow:_
> 
>     1. Opened app/browser with login screen
> 
>     2. Switch to Keepass2Android, open needed record and my keyboard aumotically switch to one-line  keyboard
> 
>     3. Switched back to my app with login screen and proceed login with selected record accesible throu one-line keyboard.
> 
> 
> _After upgrade (apply only for records with OTP keys):_
> 
>     1. Opened app/browser with login screen
> 
>     2. Switch to Keepass2Android, open needed record and my keyboard aumotically switch to one-line  keyboard
> 
>     3. Switched back to my app with login screen and K2A keyboard have no selected record at all
> 
>     4. Use select option button to open K2A
> 
>     5. Select needed record and automatically return to app/browser
> 
>     6. Still K2A keyboard have no selected record at all 😑

**Comment by theolike** [comment]
I reported and commented on this several different times before the Google+ page shutdown. I had to leave the beta program because it kept popping up.  I wouldn't mind coming back. I'm generally tolerant of errors, but this is such a key feature for me I couldn't wait any longer.  Now that it's been pushed to the stable branch I really hope it will get fixed.

**Comment by JohnLGalt** [comment]
Indeed - When I realized it was the ẞeta build of 1.07 I opted out of the ẞeta program as well.

But now 1.07-r1 is being pushed as stable by Google Play.  So, I opted to do as dragoangel mentioned - manually install 1.06f, and then going into Google Play, selecting K2A and disabling automatic updates.

Play store still mentions that the update is available, but it won't automatically update, and you can just skip it when updating other stuff if you need to manually update other apps.

**Comment by torerikk** [comment]
I'm also seeing this problem on my Pixel 3. The problem went away for a few days after wiping the app's storage.

**Comment by tiberius8** [comment]
I'm also experiencing this is. Only affects entries with totp.

**Comment by whitep0wer** [comment]
Subscribing, affects me as well. For me this is related to having TOTP set up in the entry, works fine when the entry has only password configured.

**Comment by JohnLGalt** [comment]
I'll double check - I have several entries that have more than just opt keys as entries in the advanced tab - not sure if it is only otp or anything at all in the advanced fields.

**Comment by chandradeepdey** [comment]
Same issue on

- Redmi Note 4 running Android 8.1 (LineageOS 15.1-20190508)
- ZenFone Max Pro M1 running Android 9.0 (WW-16.2017.1903.050 )

**Comment by DaveSchmid** [comment]
same issue here

**Comment by Hansa064** [comment]
Same here on a Nokia 7 Plus running Android 9.0.

@PhilippC: Can you tell, when you will have time to fix this issue? This prevents us from updating the App

**Comment by numericOverflow** [comment]
I've got the same issue. Running KP2A version 1.07-r1 on Android 6 (Marshmallow). 

Having an OTP on the entry makes entries unusable via keyboard, only via copy/paste which is not very secure.

**Comment by immanuelfodor** [comment]
It indeed helps (re)installing APK version 1.06f from here: 
https://github.com/PhilippC/keepass2android/releases/tag/1.06f

**Comment by marcelmu** [comment]
I recently set my phone up freshly. Since then I also have this issue on Android 7.
The 1.06f works just fine.

From the Debug-Log of 1.07f when selecting an Entry containing a TOTP:
```01.07.2019 22:30:32:748 -- Timeout cancel
01.07.2019 22:30:40:263 -- DatabaseSettingsActivity.OnPause
01.07.2019 22:30:40:265 -- Timeout start
01.07.2019 22:30:40:320 -- DatabaseSettingsActivity.OnStop
01.07.2019 22:30:44:784 -- Received intent to provide access to entry
01.07.2019 22:30:44:788 -- System.Exception: Invalid full id 49EC7A92444F1F338E839B6FD5F8D20A

  at keepass2android.ElementAndDatabaseId..ctor (System.String fullId) [0x00029] in <d9555282dea14061ab4400355adad9e4>:0 
  at keepass2android.CopyToClipboardService.OnStartCommand (Android.Content.Intent intent, Android.App.StartCommandFlags flags, System.Int32 startId) [0x00094] in <42483a0e42cb482da6be36caa63cd922>:0
01.07.2019 22:30:44:790 -- CopyToClipboardService.OnDestroy
01.07.2019 22:30:44:791 -- Destroyed Show-Notification-Receiver.
01.07.2019 22:30:55:173 -- Loaded task keepass2android.NullTask
01.07.2019 22:30:55:233 -- ShareUrlResults.OnCreate
01.07.2019 22:30:55:234 -- ShareUrlResults:apptask=
01.07.2019 22:30:55:240 -- Loaded task keepass2android.SearchUrlTask```

**Comment by lubor-slusny** [comment]
Same issue (after selecting entry and returning to previous app, keyboard doesnt remember open entry at all) here:
- Xiaomi Mi A1, Android 9

It also seem to depend on app that Im switching back to - many apps work fine, some almost never keep entry open and always reset keyboard.
Example where it works fine:
- com.alphainventor.filemanager

Example where I cant get keyboard to keep entry open
- com.teamviewer.teamviewer.market.mobile - login page

**Comment by marcelmu** [comment]
In my case the issue is independant from the app switching. 
Usually there should be a notification when selecting an entry, which works fine in most cases.
As soon as there is a TOTP configured, there is no entry notification.

**Comment by upD8R** [comment]
Can confirm: no entry notification (and therefore no usage of clipboard) in case OTP is populated in this entry.

**Comment by dragoangel** [comment]
4 month after issue appeared with TOTP. I simply moved all my TOTP to Authy app today and updated to 1.07, can't take anymore.

**Comment by Hansa064** [comment]
@dragoangel Yes, it's really strange to me as well, that there is no reaction from @PhilippC for 3 months.. Well, at least, he did merge a pull-request 10 days ago, so he's still active. Hopefully, we will hear from him soon about this issue.

**Comment by JohnLGalt** [comment]
I'm sticking to 1.06 - I don't see anything in 1.07 that I need to have.

**Comment by immanuelfodor** [comment]
Accidentally updated the previously downgraded app to the latest version (1.07-r1), and it doesn't work there either. 

**Quick fix**: Settings -> App -> TrayTotp -> set both TOTP Seed/Settings name to something else, e.g., append a character to the end. The one-row keyboard and the notification start to work again on such entries. Of course, you can't get the TOTP code from this app but if you use another app for 2FA, it's not a big problem, at least you can access your entries here.

**Comment by JohnLGalt** [comment]
Of you just another app for TOTP you don't need it enabled in your keypass
database, so spring it as OTP seed is pointless in the first place.

**Comment by upD8R** [comment]
> Of you just another app for TOTP you don't need it enabled in your keypass database, so spring it as OTP seed is pointless in the first place.
Wrong. Because on the (Windows) desktop I don't use any other tool than Keepass to provide TOTPs as convenient alternative to use my phone.

**Comment by JohnLGalt** [comment]
That is you.  Not everyone.  The whole point of having the TOTP in the KP
database is to avoid having to use multiple programs and have multiple
databases.  You're use case does exactly that - have multiple apps and
multiples databases providing the same functionality.

And this workaround, while it gives you access the items that have the OTP
seed as well as those without equally, forces the user to have an alternate
means too get acres to the TOTP - which is counter-productive to having otp
support in keypass and keypass2Android in the first place.

In effect, you've just said to everyone ” Hi, here is a workaround for otp
use - user another app.”

ESPECIALLY since it works perfectly fine in 1.06f.

**Comment by upD8R** [comment]
Honestly, I don't see your point. 
Let's assume I only use KP for passwords and TOTP. Desktop app and Keepass2Android, same database. 

How is this solving the issue described in this thread?

**Comment by immanuelfodor** [comment]
I think upD8R meant that you can sync the DB across multiple devices, and so you can't remove the TOTP seeds from KeePass entirely. E.g., KeepassXC handles it well.
My workaround is for those who can't live without their entries but can live with using another app.

**Comment by JohnLGalt** [comment]
By reverting to a build that it does work on, 1.06f, as has been repeatedly
mentioned.

**Comment by JohnLGalt** [comment]
Correct.  And by downgrading to 2.06f until the is a true fix for 1.07-r1,
the workaround is actually not needed.

I manually installed 1.06f, then used the Google Play store to set this one
so to not auto update.  Now, when play store has updates, I can select
update all, and it throws up a warning that I have this one app set to not
auto update, and asks is I want to update or skip.

With this, I still have access to *all* my database entries, as will as
full access to TOTP entries, without needing a second app, across all of my
devices, as the problem doesn't occur in either Linux it Windows desktops,
only on the latest build of K2A.

And since you said that it doesn't affect KpXC, either, that is an
alternative for folks who cannot get 1.06f to stay on their devices without
upgrading automatically to 1.07-r1 - use KpXC n Android and OS specific
builds for other OSs.

**Comment by upD8R** [comment]
Not sure if it makes sense to discuss possible workarounds. Personally, I just open the affected entry in K2A and do a manual copy of the needed field. Not too bad.

I guess we all agree that is a bug/regression, which just *should* be fixed.

**Comment by JohnLGalt** [comment]
That works - but is a PITA compared to using the KeyPass native keyboard to fill in entries with a single tap on each 'button' corresponding to each field you need to enter - no app switching required.  Of course, the older way I used to do it, using the notification area to keep a running notification of both username and pw makes it a bit easier - but TOTP is not one of the items that you can throw up in the notification area, only UN / PW.  So, without regressing to 1.06f, you'll need to switch back and forth between apps.

And, obviously, if I don't want to swap back and forth between 2 apps, I most certainly am not in favor of using a third app app and having to swap between 2, then 2 more, apps to get this all done when I can use 1 app, have it select my entry and enter everything into the same app without switching once I start.  Hence my comment about it being pointless if you use another app (which, I'll admit, was from my own PoV, which I did not specifically state).

Having used that same sort of functionality (KeyPass's Autotype) on desktop OSs, it's not only inconvenient but, IMO, a major PITA to swap apps to enter PWs from my database, a regression, if you will, from the previous app I used 15+ years ago.
