### ISSUE TITLE
KDBX file external updates and keepass2android offline behaviour (enhancement) 

### ISSUE THREAD

**Issue by sancho-one** [PhilippC/keepass2android#8]
Dear Philip,

First of all, let me thank you for your great app from all points of view. At the same time, let me offer you two minor enhancement for keepass2android offline which you've already implemented in keepass2android safe:

1. Well, when you re-open db in keepass2android safe version (i.e., with quick lock), it checks for external modifications and offers three options merge, replace or just reload db. As for keepass2android offline, it only checks for changes only when one saves something or through synchronize menu. It would be great if keepass2android offline followed exactly the same pattern as keepass2android safe as for db external modifications check.

2. The second issue is somewhat related to the first one. While keepass2android safe always offers 3 options: merge, reload and ignore, keepass2android offline offers merge option only when you add record and try to save it. When you already have unsaved modifications in keepass2android offline and db file is updated externally, keepass2android offline doesn't offer **merge** option, it only offers reload or ignore. It would be great if keepass2android offline followed keepass2android pattern always offering merge option.

**Comment by PhilippC** [comment]
The behavior depends on the storage type you select and not the KP2A version. This sounds to me like you opened a local file in KP2A (regular) through a third party app as a local file while you opened a file throguh the system file picker with KP2A offline. Is that possible?

**Comment by sancho-one** [comment]
Dear PhilippC,
The scenario was different but you're right, both versions behave the same
way: I specially installed both versions and found it out. :)
