### ISSUE TITLE
KP2A AutoFillplugin keeps stopping 

### ISSUE THREAD

**Issue by GreglLew** [PhilippC/keepass2android#800]
The release notes for the latest Keeppass2Android supported auto login completion for Firefox. Worked great on my Samsung Tablet.  The plugin keeps stopping on my Galaxy Note 5 when I go to a log in page in Firefox.  It doesn't appear to fail into I manually key in the first letter of the UserID (because the autofill didn't happen). I am running Android 7.0 on my Note 5.  I am running Firefox 66.0.2.  I am running 1.02 of the plug in.

**Comment by PhilippC** [comment]
the release notes refer to Android 8 Autofill, not the accessibility service based plugin. I don't think this ever worked for firefox.

**Comment by GreglLew** [comment]
OK I got it.

FYI it works in Firefox on my Samsung Tab A.

___________________________
Greg Lewis

Business Email: greg@zanco-corp.com
Mobile: 312-953-6627
Office: 312-985-6111
Fax: 425-962-9566
