### ISSUE TITLE
Fingerprint error failed to encrypt data

### ISSUE THREAD

**Issue by mtraxiot** [PhilippC/keepass2android#802]
When I enable fingerprint unlock I get an error message:

Failed to encrypt Data. This can happen if you add or remove fingerprints in system settings while Keepas2Android is listening for your fingerprint.

Note I haven't changed my fingerprints and I used to get a crash now it throws the above error.

I'm running on Teclast T10 with Android 7.0 Kernel v3.18.35

**Comment by InvalidCast44** [comment]
Exactly the same on a s7 with Pie

**Comment by littleboxis** [comment]
Having the same problem right now. Using Galaxy S7 with LightROM (v6  / android pie).

**Comment by juso** [comment]
Same problem on xiaomi redme 4x. On previous version is used to crash every time i tried to set fingerprint unlock, now it states 'failed to encrypt data'. The data file is on g-drive. Android 8.1.0, LOS 15.1.20190322-NIGHTLY-santoni. Kernel 3.18.131

Pretty scary message, now I don't know whether my data is encrypted or not - and this is the only function of the application

**Comment by everga** [comment]
Same Problem on Sony Xperia L3 Model I4312 Android 8.1.0. Kernel 4.9.77 from 25.07.2019 21:51:47 Build-Nummer 54.0.A.6.23This is my first try with keepass2android so I have no earlier experiences, but "system unlock" with Fingerprint is working.

**Comment by PhilippC** [comment]
can you please try with Keepassdroid or KeepassDX - they have similar (but different) implementations of fingerprint?

**Comment by mtraxiot** [comment]
Tried keepassdriod and it also crashes

**Comment by everga** [comment]
I tested with Keepass DX (Early Access):
at combining fingerprint  with db password:
(First sensor touch) fingerprint not recognized 
(Second sensor touch)  app crash.

**Comment by PhilippC** [comment]
if you find another open source app where encrypting something with fingerprint protection works, please let me know. I would like to see what they are doing, but my suspicion is that there might be an issue with the fingerprint implementation on some devices (especially Redmis).

**Comment by wmoreland** [comment]
I'm also having this same issue on a Galaxy S7. I had a similar issue with KeePassDroid and with a non-open-source banking app (N26) for what it's worth.

**Comment by wmoreland** [comment]
Interestingly, the ProtonMail app is working with fingerprint! Unfortunately we're still waiting with baited breath for them to release the source code but perhaps there is some hope there @PhilippC?

**Comment by PhilippC** [comment]
ProtonMail does not use key store, but KP2A needs the keystore to protect your master password. This looks like an issue outside KP2A.
