### ISSUE TITLE
[Feature request] TOTP Overview

### ISSUE THREAD

**Issue by andi-blafasl** [PhilippC/keepass2android#803]
I use TOTP for many services. Unfortunately, I find the use in Keepass2Android complicated. You have to search for the entry, open it and then display the passwords. This also shows the secret and the password. There is also no indication how long the TOTP is valid.

It would be a very nice feature if there was an overview page with all the TOTP entries on which the TOTPs would be directly displayed and provided with a timer. Similar to the style of GoogleAuthenticator displays the TOTPs.

**Comment by dragoangel** [comment]
No need to search and "copy/unhine" any fealds from KeePass DB, them can be accesible from Keyboard. So you can use KeePass2Android Keyboard to entry TOTPs. Then no really need to know how much time is left because you ensert it right before press login button.

**Comment by andi-blafasl** [comment]
@dragoangel this would be a solution on my phone. But you always have to switch keyboards then.
But it is no solution if you need the totp on another device 😉

**Comment by dragoangel** [comment]
1. Use KeePass2Android Keyboard Switcher - it works like a charm! No need to root, only read manual.
2. What another device you mean? PC? - Install KeePass OTP plugin then on this PC. Or leave this future to Apps which created only for OTP in mind like Authy.

**Comment by andi-blafasl** [comment]
Yes, I'm using TOTP on PCs. But installing KeePass on them is no option! They are not under my control.

Using another Software for TOTPs is also not an option for me. I like to sync my KeePass DB over serveral devices.

But why are we discussing about this anyway? Is it so complicated to implement a simple overview with all TOTP-Entries????

**Comment by theolike** [comment]
It's more of a conversation of time.  You're requesting a feature and there are bugs related to TOTP.  It's not a feature I'd use so you should be glad there is discussion.  If it gets enough interest, it might actually be implemented.

**Comment by silas229** [comment]
I would also be interested in this feature. I don't want to use the keyboard, but rather have a quick overview of all my TOTP codes.

**Comment by siodor** [comment]
I would also be interested in having TOTP in Keepass2Android, especially for synchronizing across devices because Google Authenticator is always bound to one device.

**Comment by AriesFR** [comment]
I can only add my vote to this feature. The very best would be a KeePass-wide solution common to the PC version of KeePass and this one as I usually sync my DB between multiple devices. Therefor, it would be great if it were compatible with the existing PC plugins

**Comment by silas229** [comment]
I'd prefer just another button (next to the password generator for example). No need to completely rethink the gui just because of a single additional button.
