### ISSUE TITLE
Double EDS containers two seen but only one readable

### ISSUE THREAD

**Issue by HoudayerPierre** [PhilippC/keepass2android#807]
Hello,

My databases are opened with a key-file, these are store in encrypted volume with VeraCrypt, to open it I use EDS. When I want open (the database) two of them simultaneously (previously opened volumes with EDS, vol1 and vol2) I can see two volumes to select but only one can work (it always read the first one) 
exemple for selection :
My Phone
My Drive
...
vol1
vol1

But no "vol2" when you select vol1 (first one or the other) it always open the container vol1.

**Comment by PhilippC** [comment]
as far as I understand this rather seems an issue with VeraCrypt or the Android file browser.
Please re-open if you think there's something wrong with KP2A.
