### ISSUE TITLE
Extend password creation view

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#81]
- [x] add box to use extended character set (e.g. §©®¢°±¹²³¼½×÷«âéïñù¡¿»¦Ø)
- [x] add longer password button (24 or 32)
- [x] passphrases
- [x] use password font in password generator
- [x] "at least one of each group" checkbox
- [x] password profiles
- [x] exclude look-alike characters
- [x] immediately update suggested password when changing settings 
- [x] password quality estimation

(This combines  https://github.com/PhilippC/keepass2android/issues/702, https://github.com/PhilippC/keepass2android/issues/284 and #1196)

**Comment by rocketwidget** [comment]
If this issue is addressed, another good one would be:
* add box to force at least 1 from each chosen set
For example, some websites require at least one Upper-Case, at least one Lower-case, at least one Digit, at least one Special, etc.

**Comment by Riajyuu** [comment]
Is it possible to start this since 10 thumbs up?

**Comment by Riajyuu** [comment]
@PhilippC A great thanking for the planning!

**Comment by Riajyuu** [comment]
another small question here:
is password quality estimation planned?
![image](https://user-images.githubusercontent.com/16912240/64099376-a6c11a80-cd58-11e9-9167-4514a756b340.png)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Also, I would like to have my password generation profiles:
> 
> ![image](https://user-images.githubusercontent.com/16912240/64002296-3b2d4200-caf9-11e9-93a6-5a89aba4cb2f.png)

Yes, I like this and use profiles too. But even if implementation done, they won't be sync to mobile devices. The password template is not saved in database is it?

**Comment by Corey-Keller** [comment]
@PhilippC I'd also suggest that an option to "exclude look-alike characters" like in the desktop version be added. If it's already there and I've just missed it, please let me know
