### ISSUE TITLE
Oreo Autofill and TOTP with prefix Pin is impossible

### ISSUE THREAD

**Issue by XtraLarge** [PhilippC/keepass2android#811]
Hi,
I've tried since two days to configure it. There must be a bug or a missing feature :)

I need an static pin-code followed by an TOTP Token as the password in the Autofill feature since Android Oreo.

If I configure it like Keepass TOTP-Tray Plugin with Pin followed by the {TOTP} Reference Field, Autofill sends that String as Password. There is no substitution.

I saw the entry has an additional field TOTP with the right changing code, but there is no chance to use it for Autofill as password.

please help :)

best regards
Willi

**Comment by theolike** [comment]
I put my static pin a separate field.  It's to taps to insert both parts.  I'm assuming you're trying to set it up so you can also use the desktop auto-type functionality?

**Comment by XtraLarge** [comment]
Perhaps, I did not understand how it works, but if i insert the tags {pin}{otp} they were no resolved in the password field. I've test it by using a password site with a button to show the password in cleartext. So I saw the tags in the field, they were not substituted. 

How do I use the {otp} tag as a password???
