### ISSUE TITLE
Share a password entry

### ISSUE THREAD

**Issue by marlene-gratigny** [PhilippC/keepass2android#813]
A new feature can be to share an entry for example for the internet box of the house I want to share the entry with my husband instead of spelling the login and password

**Comment by dragoangel** [comment]
There is a qr plugin for kp2a witch can generate qr codes from keepass2android entries or scan qr codes to save them in database.
But there is no scan from file option. So you can only real-time capture other phone screen.

**Comment by MichelDiz** [comment]
https://play.google.com/store/apps/details?id=keepass2android.plugin.qr

**Comment by PhilippC** [comment]
another option is to use a child database (see settings - database settings - configure child databases) which you can have on a shared cloud storage (e.g. Dropbox). This child database can be shared between two KP2A databases and thus allows to manage a folder of shared passwords easily.
