### ISSUE TITLE
Background tasks and Android Q

### ISSUE THREAD

**Issue by djpandemic** [PhilippC/keepass2android#814]
I jumped in early on Q and there was a notice regarding background tasks being disabled in future builds. Now that beta 3 and Google I/O have dropped, they have now moved forward with disabling background tasks.  Some/all plug ins (especially inputstick which my life revolves around) now no longer operate.  Good news, the screen shot blocking capability also works, so no attachment.

**Comment by PhilippC** [comment]
I understand this is a problem for **working with** KP2A, but I don't understand how this is an issue **with** KP2A? Please note that input stick is not developed by me. Please re-open if there is something KP2A could do to solve this.
