### ISSUE TITLE
Notification does not appear when a TOTP is set

### ISSUE THREAD

**Issue by madnessmike** [PhilippC/keepass2android#815]
Hello there,
I set up a new field with both a password and a TOTP; every time I'm using it the notification that allows me to enable the KP2A Keyboard does not appear. This issue does not occure with fields that have only a password, it works as expected

I'm using the beta version on Android 9

**Comment by dragoangel** [comment]
Hi, you duplicate https://github.com/PhilippC/keepass2android/issues/799
