### ISSUE TITLE
Keepass keeps hijacking things on my phone

### ISSUE THREAD

**Issue by Gooberpatrol66** [PhilippC/keepass2android#816]
1. I tried to use an app called "markor" to edit a text file on my phone, and keepass popped up, preventing me from doing so
2. Whenever I download a file in chrome and click "open", keepass pops up instead

**Comment by herexf** [comment]
I believed you have selected always open text file with Keepass, you can clear this default setting in app management.

**Comment by dragoangel** [comment]
I think too that you misconfigured app association on your phone. In any case KeePass2Android not do it on it own on any device.

**Comment by Gooberpatrol66** [comment]
It says "no defaults set" in "open by default".

**Comment by dugite-code** [comment]
@Gooberpatrol66 You could try to reset your app preferences `settings -> apps -> (overflow/three dot menu) Reset app preferences`

**Comment by Gooberpatrol66** [comment]
> @Gooberpatrol66 You could try to reset **all** your app preferences `settings -> apps -> (overflow/three dot menu) Reset app preferences`

I tried that, and it's still hijacking things.

**Comment by Hustensirup** [comment]
Maybe k2a autocomplete feature?
I had problems too and disabled it.

**Comment by Gooberpatrol66** [comment]
Autofill service? It's not enabled.
