### ISSUE TITLE
Invalid Composite Key error with regenerated keyfile

### ISSUE THREAD

**Issue by KodiakIT** [PhilippC/keepass2android#818]
So, in updating my Keepass database to work with KeepassXC 2.4.0, I regenerated my key file which I use in addition to a password to unlock the database. While I'm now able to unlock it on more recent versions of KeepassXC, it seems that KP2A won't unlock it with the new Password/Key file combo.

**Comment by KodiakIT** [comment]
Db/key version mismatch, but in the process noticed an undocumented issue with KP2A keyboard TOTP entry/autotype.

**Comment by prashantkhurana** [comment]
Do you remember what the issue was? I had a similar thing. Invalid composite key with k2pa keyboard and valid when entered with swiftkey.

**Comment by KodiakIT** [comment]
Unfortunately not as I’m not using an Android device these days

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 226cenk** [comment]
Trying to use the app with my Yubikey via NFC. It worked fine for a time, now it is displaying a "invalid composite key" error. What could be happening?

Personally use KeepassXC as my password manager, my Yubikey works fine with KeepassXC.
