### ISSUE TITLE
Unable to use KP2A Keyboard to enter TOTP

### ISSUE THREAD

**Issue by KodiakIT** [PhilippC/keepass2android#821]
As stated in title, attempting to switch to KP2A keyboard from AOSP keyboard on LineageOS in multiple apps results in the numpad from the AOSP keyboard simply re-appearing instead of allowing me to cycle through stored fields to input (e.g. name, password, TOTP, other attributes) as I was previously able to on previous LOS versions/stock Oreo(/Pie too I think?)

**Comment by theolike** [comment]
Probably a duplicate of #799.

**Comment by PhilippC** [comment]
closing as duplicate
