### ISSUE TITLE
Support nextcloud app tokens

### ISSUE THREAD

**Issue by Matzz** [PhilippC/keepass2android#822]
It would be cool if Keepass2Android could login to nextcloud using app tokens rather than username/password (user docs here https://docs.nextcloud.com/server/16/user_manual/session_management.html)

As a workaround I created a separate username and shared keepass file with it. However, it's far from ideal solution.

**Comment by Caligatio** [comment]
It already does; using them myself.

**Comment by brOOper** [comment]
> It already does; using them myself.

And how exactly did you do that? Choosing Nextcloud storage type I only get URL, username and password (and entering the app token as password does not work).

**Comment by PhilippC** [comment]
As far as I know you just enter the app token as password.

**Comment by brOOper** [comment]
That's what I tried. Unfortunately, it does not! 😉

**Comment by brOOper** [comment]
It's weird. When I use `curl` to access the very same URL / user / token it works. But in the app I get this error:
![image](https://user-images.githubusercontent.com/7403075/70892231-092ce680-1fe9-11ea-86de-d5653b72d3a8.png)
