### ISSUE TITLE
Quick unlock no longer working

### ISSUE THREAD

**Issue by Lovett99** [PhilippC/keepass2android#823]
Quick unlock no longer working since updated to Android 9
Samsung S8
Android 9

**Comment by dnessl** [comment]
Same happened to me when I loaded a system backup from a phone running Android 8.1 onto my new Pixel 3a running Android 9.  

Solved by going into Keepass2Android settings, disable fingerprint unlock, then re-enable fingerprint unlock.

**Comment by Lovett99** [comment]
Fixed. I had stopped Keepass using notifications but that is required for quick unlock to work.
Thanks for your suggestion. It didn't work for me but now I use fingerprint login which I never tried before

**Comment by D000DM000R** [comment]
Quick unlock has not been working for me for quite some time. I always have to enter my long (20 character) password now. Not sure if this happened when my phone (T-Mobile Samsung Galaxy S9+) was updated to Android 9 or if it started after the April update to KeePass2Android. Since I don't use fingerprint unlock I didn't try the suggestion to disable/reenable fingerprint unlock. I do have notifications turned on for KeePass2Android.

**Comment by D000DM000R** [comment]
I see this thread has been closed. Can it be reopened, or do I need to start a new thread?

**Comment by PhilippC** [comment]
@D000DM000R I'm pretty sure it's related to your system settings. Please make sure you see the "Enable QuickUnlock" checkbox when you open your database. If this is checked and you unlock the DB, what happens if you click the lock icon in KP2A's menu? Do you see the QuickUnlock notification?

**Comment by D000DM000R** [comment]
Yes, I do see the QuickUnlock notification page.

**Comment by PhilippC** [comment]
If you click the notification, you should see the QuickUnlock screen where you can enter the last three digits (by default) of your password to unlock quickly. Is this working, too? If yes, what is NOT working?

**Comment by D000DM000R** [comment]
Yes, that works fine.

The problem occurs when the app is inactive, automatically times out (app
timeout currently set to 5 minutes), and then locks the database. To unlock
the database after the database has auto-locked I need to use my full
master password rather than quick unlock.

**Comment by PhilippC** [comment]
this very much sounds like it's a battery optimiztaion setting or something similar on your device, because QuickUnlock is enabled correctly, but Android kills the app while it's in background.

**Comment by Lovett99** [comment]
That will be the answer.  I found this was the issue on my Samsung S8. Check power settings/battery/keypass app. Something like 'put to sleep when not in use'
Also I wasn't sure how/when quick unlock should be available so wasn't sure if it was working properly but understand now.

**Comment by D000DM000R** [comment]
I did a bit of poking around and found that 'put to sleep when not in use'
was turned on for KeePass2Android (not sure how or why that option was
turned on). I've turned  'put to sleep when not in use' off and am testing
now.

**Comment by D000DM000R** [comment]
tuning the option 'put to sleep when not in use' did fix the problem. Thanks for the help.
