### ISSUE TITLE
Search filter doesn't remove non matching folders

### ISSUE THREAD

**Issue by dbareis** [PhilippC/keepass2android#827]
Just as entries are removed as you type so should folders. Can be simple match or matching folder is one that matches text or contains something that does (option should be nice)

**Comment by PhilippC** [comment]
I don't get what you mean. In the quick search, no folders are displayed. Can you post a screenshot?

**Comment by dbareis** [comment]
Sorry I've been on holidays and have now tried to reproduce this and failed.  It's possible I got confused with the black dialog on top of black screen as it's not always obvious what I'm looking at.

If I see it again I'll report again, close this thanks.  Feel free to make the search results more obviously something that is on top of the background...
