### ISSUE TITLE
Store cached files in app internal directory (and not in cache directory)

### ISSUE THREAD

**Issue by ghanjiboy** [PhilippC/keepass2android#83]
Hi there, this combination use to work - if i was offline for whatever reason, I will still able to access the cached database.  In the last few releases this has gone away.  

Is this something that can be corrected or is there a workaround?

Thanks!

**Comment by nandhp** [comment]
I am also having this problem. Keepass2Android is configured to access the database via Dropbox. Sometimes (perhaps after a period of time without using the app) I am not able to open my password database without a network connection. When I open Keepass2Android I receive an error message (no address associated with hostname `content.dropboxapi.com`), and I am not able to unlock the database.

If I subsequently open the database when a network connection is available there is no problem. I can then close the database and quit KeePassX (swiping it out of recents and also verifying there are no running services), and if I subsequently reopen the database while in flight mode there is no issue. Although I did not often use Keepass2Android offline, this used to work as far as I know. I first noticed this problem in late September/early October.

Keepass2Android seems to behave as if its locally cached copy of the database expires. In my opinion, this behavior is incorrect -- the app should always be able to open the last seen copy of the database. This is particularly important if the account password for your internet service provider is stored in your password database. Can you please fix this?

Thanks.
