### ISSUE TITLE
Keyboard button to select entry button unresponsive

### ISSUE THREAD

**Issue by louisch** [PhilippC/keepass2android#832]
I'm using a MI 8 Lite, with MIUI 10.3.
The button for selecting entry (to enter username/password) in the keyboard is unresponsive.
Not too sure what else I can report, though I will note the keyboard is working fine on my other phone (an Honor 9)

Uninstalling and reinstalling doesn't seem to fix the problem.

The version I'm using on both phones appears to be the same (1.07-r1)

**Comment by test01wrk** [comment]
Same problem here，MI8 lite MIUI 10.3.

**Comment by PhilippC** [comment]
what exactly do you mean with "unresponsive"? Nothing happens?

**Comment by louisch** [comment]
Yes, nothing happened. But it's been 2 months since then and I don't use keepass anymore. However, I just redownloaded the app on MIUI 10.3.3 and the button now seems to work correctly.
