### ISSUE TITLE
Unable to download .kdbx via sftp on new Samsung Galax Tab A

### ISSUE THREAD

**Issue by jdege** [PhilippC/keepass2android#837]
I've been using KeePass2Android on a number of different devices with great success, for a number of years.

I bought a new tablet, today, a Samsung SM-T510, and I cannot get KP2A to login via sftp to download the .kdbx file.

I'm working with KP2A version 1.07, on Android Version 9, Kernel version 4.4.111-15563421

I'm trying to connect to OpenSSH_6.6.1p1, running on Linux Mint 17.3 Rosa

The process I'm seeing is:

- I uninstall the existing installation of KeePass2Android, just make sure nothing is left behind.
- I install a fresh installation of KP2A.
- I click on "Open File".
- I click on SFTP.
- I enter the bare IP address of the machine I want to access into the "host" field, with no extraneous decorators (no http://, no myusername@, no URL path, just "192.168.123.456", except it's a real IP address, assigned me by my ISP.
- I enter the non-standard port number I have my router allowing through into the "port" field.
- I enter a username into the "username" field (there are two on this machine, neither works.)
- I set the "Authentication mode" dropdown to "Password".
- I leave the "Initial Directory" field set to "/".
- I click OK.
- I see a dialog: "The authenticity of host "1292.168.123.456" can't be established. The RSA key fingerprint is... Are you sure you want to continue connection?"
- I click Yes.
- I see another dialog: "/data/user/.../knownhosts does not exist. Are you sure you want to create it?"
- I click Yes.
- I get an error dialog: "Cannot connect to provider service: SSH_MSG_DISCONNECT:2 Too many authentication failures for username".

That I'm getting the RSA key dialogs convinces me that I'm getting to the right port on the right machine. Googling the error indicates this is a common problem when clients have too many public keys configured, but you shouldn't be trying public keys, you should be trying a password login, yet you never show  me a password dialog.

Now here's the confusing bit - my older android devices, that first connected using passwords months or years ago, can connect just fine.

And, I have AndFTP installed on both the old devices and the new one, and I can make a successful sftp connection using that IP address, port, and username.

That is - I can make an sftp connection using the specified connection information, using AndFTP on my new SM-T510, and I cannot using K2PA's sftp storage type.

This convinces me that there's something wrong with K2PA's sftp authentication negotiation.

**Comment by jdege** [comment]
Ok, it was a least astonishment error.

The authentication mode dropdown isn't a dropdown, it's a switchable area that can contain either a password field or a send private key button.

The last app I used that configured an ssh correction did not request a password during configuration, but instead popped up a dialogue to ask for one, if it were necessary. With the look of the new UI to support both password and public key, I was expecting the same.

If I enter a password, it works fine.

**Comment by m-iwe** [comment]
Hello, 

I am here some years later - with the "authentication failures" issue with an sftp-file. I have selected password +keyfile - and maybe have tried four times or so. Both parameters are there - but I don't know how to overcome this denial of access. 

The problem came up after having changed to a new smartphone (both from Samsung) with the help of "Smart Switch"-app. 

I have updated to the newest version of keepass2android (1.09a-r3).

On the old phone it works, on desktop computer as well.

Could you please help?

**Comment by PhilippC** [comment]
did you re-select the files? Select Change database on the password screen - Open file and then browse to the kdbx file again?
