### ISSUE TITLE
Keepass2Android blocks yubico authenticator

### ISSUE THREAD

**Issue by dodtsair** [PhilippC/keepass2android#839]
I like that keepass2android has integrated with Yubico, I might decide to use it at some point.  But for now I use the Yubico Authenticator android app as a MFA TOTP platform.  I tap my yubikey against the back of my phone, the yubico authenticator comes up and shows me my otp for all my services.

Recently, I think due to an update in keepass2android, that has stopped.  Now keepass2android gets the event for the yubikey and since it is not configured to work with a yubikey it gives me a little warning, "Please select a database first, otp has been discarded for security reasons".

Is there a way I can disable keepass2android reading the yubikey, so that yubikey authenticator will resume getting the events?

**Comment by tehshane** [comment]
Similar issue here. When I'm in Chrome and tap my key as part of a WebAuthN login on an unrelated site, Keepass2Android instead opens and tries to unlock my database, interrupting the flow.

**Comment by markchalloner** [comment]
A workaround for this (on Android 9.0):

1. Open Keepass2Android _Open by default_ settings (_Settings_ > _Apps_ > _See all  ... apps_ > _Keepass2Android_ > _Advanced_ > _Open by default_).
2. Set _Open supported links_ to _Ask every time_.

**Comment by PhilippC** [comment]
unfortunately I don't know of a way to make this configurable because it's part of the App manifest. So I suggest to use the workaround suggested by @markchalloner
