### ISSUE TITLE
SFTP to synology - failed to send channel request

### ISSUE THREAD

**Issue by LMSSonos** [PhilippC/keepass2android#842]
I try to connect with SFTP to my synology. I have tested with password and with private key. I always get the same error: "Cannot connect to file provider service failed to send channel request". I can connect with WinSCP to the synology with the same private key. 

Synology DSM Version: DSM 6.2.2-24922 
Android Version: 9 / Pixel2

**Comment by PhilippC** [comment]
I am surprised about the last sentence: KP2A generates its own private key which you cannot even extract, so you cannot test this from anohter device. Are you sure you correctly installed the public key from KP2A on the server?

**Comment by LMSSonos** [comment]
Sorry for the type, same public key.

**Comment by PhilippC** [comment]
according to https://stackoverflow.com/questions/14769164/jsch-error-failed-to-send-channel-request this might be an issue with the server configuration. can you please check?

**Comment by f-ben** [comment]
@PhilippC Fixed my issue I wrote you by mail yesterday.
For some strange reason on my synology I had to disable SFTP access and reenable it again. I also denied FTP access for my user and allowed it immediately after that. Don´t know what caused this issue but this fixed it.

@LMSSonos I too was able to connect via WinSCP but couldn´t open the file with Keepass2Android.

**Comment by PhilippC** [comment]
I'm closing this as I suspect an issue with server configuration. @LMSSonos please re-open if you disagree.

**Comment by LMSSonos** [comment]
@PhilippC thanks for your help. I tried to add the subsystem into the sshd_config like described here. https://gist.github.com/johnantoni/2727718#file-sftp-synology-txt-L11 not sure if `internal-sftp` is the issue or not

@f-ben are you using synology as well, if so, can you tell me which subssystem you have configured?

**Comment by f-ben** [comment]
@LMSSonos yes I use a synology DS718+

Subsystem       sftp    internal-sftp -f DAEMON -u 000

**Comment by LMSSonos** [comment]
@f-ben thank you ... this helped, in the end the issue on my side was, that SSH runs on a different port and SFTP was running on port 22 (according synology UI). So in that combination WinSCP still worked, but for making it work on Android I had to change the SFTP port to the same as SSH.
