### ISSUE TITLE
Support "Autotype selected entry"

### ISSUE THREAD

**Issue by koppor** [PhilippC/keepass2android#845]
OS: ChromeOS (refs https://github.com/PhilippC/keepass2android/issues/272)

On KeePass2, I am used to "autotype selected entry". Is this also possible on ChromeOS? Like, if I type the shortcut for autotype, KeePass2Android does the autotype (similar to the Windows KeePass2 version)?

**Comment by PhilippC** [comment]
ChromeOS is not Windows. AFAIK, this is not possible.
