### ISSUE TITLE
Please kindly consider to update Keepass2android Offline version on Play store to 1.07-r1

### ISSUE THREAD

**Issue by bungabunga** [PhilippC/keepass2android#848]
Online version of Keepass2android works great on Firefox for Android and I'd really appreciate if you'd enable the same bahaviour to offline version on Play store. Thank you!

**Comment by dionorgua** [comment]
I kindly ask +1 for this.

**Comment by willat8** [comment]
This appears to be available now (at least for beta programme members).

**Comment by bungabunga** [comment]
I still se 1.06g on Play store as a beta programme mambe for Keepass2android Offline.

**Comment by chilliger** [comment]
@PhilippC Do you plan on updating the offline version or should one just switch to the normal one?

**Comment by PhilippC** [comment]
I'll update after my vacation, planned for September

**Comment by SoftwUser** [comment]
@PhilippC Any news on the update?

**Comment by PhilippC** [comment]
so sorry 🙈 
I just uploaded 1.08c-r1 to the beta channel of the offline version: https://play.google.com/apps/testing/keepass2android.keepass2android_nonet
