### ISSUE TITLE
generating key or master password from fingerprint authentication

### ISSUE THREAD

**Issue by joao-matos** [PhilippC/keepass2android#849]
Situation: I want to open on Linux a database created on Android. That database on Android was protected with a Master password and a fingerprint.

Issue. Master password forgot, fingerprint not available on Linux device.

Cant generate a key or change the password using fingerprint authentication.

I know i can see and manually generate a new database and manually recreate the contents.
Any other possible solution?

Should the option exist? as in, if 1 authentication option allows to setup other should any other also allow setup the others? example: if master password allows setup fingerprint, fingerprint should allow setup master password.

Tks!

**Comment by Small-Ku** [comment]
In my understanding, the app don't get any data about your fingerprint, and use system API to verify your fingerprint. 
In fact, your database is protected by a master password only. And your master password is stored in Android Keystore with fingerprint. The fingerprint is not related to the encryption of database.

**Comment by dragoangel** [comment]
Your case even doesn't related to this app. Why you created such ticket? Close it and go te forums. In bonus your doubt about database protection wrong at root. So if you have access to keepass database on phone with fingerprint:
SIMPLY GO TO SETTINGS AND CHANGE MASTER PASSWORD TO NEW ONE

**Comment by PhilippC** [comment]
@joao-matos If changing the password as @dragoangel suggests doesn't work for you, you can also consider to export the database in an unencrypted format (XML) and import this in a new database with Keepass2.
