### ISSUE TITLE
Possible to delete local backup database?

### ISSUE THREAD

**Issue by dromani** [PhilippC/keepass2android#859]
Launch Keepass2Android, select Change Database, select Show Local Backups.
Cluck 3-dot menu beside "Local backup of...", system displays "Remove".
If I click "Remove" will doing so delete the actual local backup database copy? Or will it only remove that line from the displayed list of recently opened databases?
If the latter, is there any way to remove the actual local backup database copy?
Thank you.

**Comment by PhilippC** [comment]
it's deleted from the filesystem: https://github.com/PhilippC/keepass2android/blob/master/src/keepass2android/fileselect/FileSelectActivity.cs#L270
You may want to turn on debug loggin in the app settings to make sure there is no error (because that wouldn't be displayed but only logged)
