### ISSUE TITLE
Possible to change name displayed in menu bar at top?

### ISSUE THREAD

**Issue by dromani** [PhilippC/keepass2android#860]
I originalky created a database file with name ABC.kdbx.
I have  now changed the name of my database file from ABC.kdbx to DEF.kdbx.
When I open DEF.kdbx, the name displayed in menu bar is still showing as  ABC.kdbx.
Is there  any way to change the name displayed in the menu bar?
Thank you.

**Comment by Lineflyer** [comment]
That is an interesting question.
I have recently recognized that for me the menu bar shows the file name (without file extension) but not the name I gave this database in the database settings.
I would prefer to see the name instead.

**Comment by Wilker-a** [comment]
the database name (found in the database settings) is separated from the file name.

i think that a good suggestion would be to add a checkbox "also rename database file” while renaming the database itself.

**Comment by xorbital** [comment]
The name displayed at the top bar is actually the name of the root folder.
Open your database in a compatible application like KeePassXC and rename the root folder.

**Comment by dromani** [comment]
Thank you!
Regards,
Dario R.

________________________________
