### ISSUE TITLE
URL are replaced by ANDROIDAPP

### ISSUE THREAD

**Issue by chrisbiomed** [PhilippC/keepass2android#861]
Hello, in keepass2andrdoid the field "URL" is completed by ANDROIDAPP://toto.com instead of "http://toto.com" which is unusable on a personnel computer under Linux or Windows.
Is it possible to use another field to stock this information instead of URL field ?

thanks

**Comment by temoto** [comment]
Duplicate of https://github.com/PhilippC/keepass2android/issues/531
