### ISSUE TITLE
Opening a database containing child entries fails if that is unavailable

### ISSUE THREAD

**Issue by datenimperator** [PhilippC/keepass2android#862]
**Describe the bug**
My KeePass 2.x database contains an AutoExec entry which opens one or more secondary databases on my main Windows system. Opening the DB online via Keepass2Android however fails, because the path is unavailable.

**Background**
If you use more than one database at the same time, one might wish to automatically open databases after a primary DB has been opened. There is a plugin called [KeeAutoExec](https://keepass.info/plugins.html#keeautoexec) which implements the defacto standard. It's supported in KeePassXC, too. See https://github.com/keepassxreboot/keepassxc/issues/477

**To Reproduce**
1. Create a DB which contains one or more not expired entries in a group named "AutoOpen". Please see [Database.zip](https://github.com/PhilippC/keepass2android/files/3363147/Database.zip) as a 
sample. Master password is `keeweb`. There is an AutoOpen entry pointing at `C:\TEMP\other.kdbx`
2. Open that DB in Keepass2Android, entering the master password. Tap unlock.
3. See error "Could not find file: C:\TEMP\other.kdbx"
4. No entry from the orimary DB is visible, although unlocking was successful.

**Expected behavior**
The app should either gracefully fail to open the child DB, or provide an option to disable opening child DBs altogether. If opening a child DB fails, the primary DB and its entries should still be accessible.

**Comment by PhilippC** [comment]
sorry for the late reply. 
I tried to reproduce the issue but wasn't able to do so. If I create an AutoOpen exec entry with "Skip if not exists"=False, KP2A will fail to load the entry and show the password screen *for the not existing database*. You can click back button to return to the (successfully opened) database. If you can't please post more information about your AutoExec entry.
After opening the database, please configure the parent db to disable the entry for the Android device.

**Comment by datenimperator** [comment]
> sorry for the late reply.

No worries I was on vacation anyways.

I wasn't aware about the "Skip if not exists" entry. I created such a field, **and now it works**. But even now I can't seem to find any docs about this feature. I'm closing this issue now, but would appreciate if you'd share a link to the docs if you had one.

**Comment by PhilippC** [comment]
docs regarding KeeAutoExec can be found in https://keepass.info/extensions/v2/keeautoexec/KeeAutoExec-2.4.zip
