### ISSUE TITLE
enhance the keepass2android keyboard to make it a real replacement for stock keyboards

### ISSUE THREAD

**Issue by gitterman** [PhilippC/keepass2android#864]
I would like to replace the stock gboard with another keyboard if I only could find any that allows decent editing.
Most keyboards have auto-completion, auto-capitalization and other features which may be nice but are not essential and often even counter productive.
Please consider the following ergonomics on the keypass2Android keyboard to make it super useful.
1. Swipe left on any character deletes left the last character
2. Swipe left on backspace deletes the last word
3. Swipe right on any character inserts a blank
4. Swipe up on any character creates the "Shift+character" function.
5. Swipe down on any character enters the special character for that key which is denoted in the lower right corner. These characters should cover the most common special characters and not omit the '/' like gboard or the '+' like the legacy touchpal shown in my attachment.
6. have an extra keyboard layout for cursor positioning. It should also have keys for cut, copy, paste, erase, space and punctuation. This allows much easier text editing e. g. in the keypass notes field which currently is a total nag.

With these simple rules it would become super easy to enter and edit even complex text.
For example I like to add a lot of notes, extra PIN and SuperPIN information, addresses etc to password fields. Editing these is really cumbersome with most keyboards.
And auto-XXX features are not nearly as useful here as the above given points.
I have attached 2 screenshots of a legacy touchpal keyboard which has implemented the points 2,4,5 and 6 but it is not available anymore.

![keyb1](https://user-images.githubusercontent.com/10762929/60772390-f20ed200-a0f5-11e9-9d97-499f498434ec.jpg)
![keyb2](https://user-images.githubusercontent.com/10762929/60772391-f509c280-a0f5-11e9-8303-5f21c484c8ca.jpg)

**Comment by PhilippC** [comment]
sorry, but this is not planned. The keyboard is mainly for inserting username and password and has a simple keyboard for simple things, but is not meant as a replacement of real keyboards.
