### ISSUE TITLE
Error: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks

### ISSUE THREAD

**Issue by Ana06** [PhilippC/keepass2android#868]
I get the following error when trying to import a database (generated with Keepassxc) with `Password + Key file`:

```
Error: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks
Parameter name: ticks
```

If the password is wrong it complains about that instead of giving this error.

Keepass2Android version: 1.07-r1
Phone: POCOPHONE F1
Android version: 9PKQ1.180729.001

**Comment by all-the-good-ones-are-gone** [comment]
Same here.
K2A 1.07-r1
Samsung Galaxy S9+
Android reported as version 9

When I connect to Nextcloud via Nextcloud or OwnCloud or webdav options, or download locally, the above message is provided when entering password only.

**Comment by all-the-good-ones-are-gone** [comment]
Just tried creating a new file from keepassxd using default settings, and that worked.

I guess I chose too complex settings?

Is there any documentation listing what the min and max seconds to unlock we can pick to be compatible with this app?

**Comment by PhilippC** [comment]
sorry for the late reply. 
I am pretty sure there is something wrong with the file. Can you try to open with Keepass2? If so, you might want to export it is a XML (unencrypted) and see if there are any weird dates?

**Comment by all-the-good-ones-are-gone** [comment]
I've been using it with keepassxc, and through that, the FF plugin.

I tried exporting the database, creating a new instance with keepassxc,
importing into that, and *that* works with the k2a app.

**Comment by Ana06** [comment]
@PhilippC

> sorry for the late reply.
I am pretty sure there is something wrong with the file. Can you try to open with Keepass2? If so, you might want to export it is a XML (unencrypted) and see if there are any weird dates?

Thanks for your answer. It seems there is an entry with a weird date. I haven't tried that correcting it, prevent the error to happen again, as I in the meanwhile I decided to use a different app. But I guess it does. It may be a good idea to have a more user friendly error in this case though.

**Comment by lonelymaw** [comment]
I'm having similar issues trying to import my database, sourced from KeePassXC. Maybe after authentication the app could direct the user to the entry(-ies) with a weird date so they can be fixed?

**Comment by PhilippC** [comment]
This exception seems to come from deep in the loading of the file which might make this a bit difficult. I am interested in finding out what causes these bad date fields. Can you try to export to XML and spot the reason? And can you try to open with Keepass2 ?

**Comment by wet-rainkoot** [comment]
Wooooo!!! Found,, and almost lost, this thread after having this happen to me. 
+1 for having to fix bad dates. 

My cause: 
-exported to CSV from safeincloud, imported into XC
-forced export of old cached browser passwords to CSV, imported into XC

Noticed that some of my date entries were "from" the year 59 all the way to 85. Desktop app treated these as post 2000 dates. My quick fix for these entries was just to clone them and delete the old entry.

**Comment by PhilippC** [comment]
can you post the headure of the CSV and one of the lines with such an invalid date (of course with sensitive data being removed/changed)? Or maybe even a kdbx file which Keepass2Android cannot open? I would like to have a file to reproduce this.

**Comment by Bug-Ninja** [comment]
I experienced the same issue. Along with some other issues U decided to abandon XC. I exported the database to CSV, imported it in Keepass 2 for windows and now kp2a understands it. Initally Keepass 2 gave me the exact error you had in Kp2a. So it is definitely something about the way XC saves the database.

**Comment by llucax** [comment]
I've been hit by this too, and it took quite a bit to *debug*. My problem was some import process that got the create/update dates of some records wrong. The DB was still perfectly valid. I think keepass2android should be a bit more permissive here, and maybe just **warn** the user about some fishy dates in the future, not allowing the users open perfectly valid databases just because one date is messed up seems a bit too restrictive.

**Comment by PhilippC** [comment]
@llucax can you produce a sample file which has this issue which you can share with me for testing?

**Comment by llucax** [comment]
Hi @PhilippC , sorry for the late reply. Unfortunately I have very little time in my hands at the moment but IIRC I think it should be enough to build a custom cvs and put a date that's way in the future (big timestamp), then import it using keepassxc.

**Comment by wet-rainkoot** [comment]
@PhilippC 
[wet-rainkoot-borked-timestamps.zip](https://github.com/PhilippC/keepass2android/files/3886788/wet-rainkoot-borked-timestamps.zip)
Well... a file after 2 months is better than nothing?
PW for kbdx is a

**Comment by AblingerOscar** [comment]
Sorry for the necro, but the exact same bug just appeared for me. I, too used KeepassXC and have recently imported some data from an svc (from firefox, where the dates seem a bit off anyways).
Should I file a new Ticket or do you want to re-open?

Currently don't have access to my KeepassXC instance until in ~8h, so I sadly can't check which numbers are actually off or provide a file.

Keepass2Android Offline
Version: 1.07b-r0
Android: OxygenOS version 10.3.8

**Comment by PhilippC** [comment]
@AblingerOscar please try again if the problem persists with https://github.com/PhilippC/keepass2android/releases/tag/1.08c-r1-nonet

**Comment by AblingerOscar** [comment]
@PhilippC it does not, thank you :)
