### ISSUE TITLE
Is using battery on Oreo

### ISSUE THREAD

**Issue by jetadams** [PhilippC/keepass2android#87]
On Android Oreo, when the DB is locked the system gives the notification "Keepass2 is using battery."

**Comment by ucwhatic** [comment]
I am running android Oreo and havd seen this same behavior (after closing app) on Keepass2 Openkeychain and a few others. 

For me it went away when i went into settings and did a manual force close. im sure theres a better way though. Seems like the apps that have less support for Oreo permission editing are more susceptible

**Comment by blsz** [comment]
A Nexus 5x running Android Oreo 8.0.0 shows a persistent Android System notification "Keepas2Android is running in the background. Tap for details on battery and data usage".  It is not possible to swipe this notification away.

**Comment by StefanSchoof** [comment]
I had this message also. With the 1.0.3 and Android 8.1.0 I do have this message any longer. I had the problem on Android 8.0, but I do not know which version of keepass. So I can not say which updated fixed this.

**Comment by PhilippC** [comment]
Keepass2Android is not using battery. It simply needs to stay in the background to remember the QuickUnlock code securely. To hide this notification, you can use https://play.google.com/store/apps/details?id=com.iboalali.sysnotifsnooze

**Comment by l-Marty-l** [comment]
Letting the app stay in background just for this feature seems over-kill for me. It should not reserve RAM for this kind of thing. If you, dear reader, use the fingerprint, I recommend to disable the QuickUnlock as it seems redundant in any case. The fingerprint feature will be your new quick unlocking feature that won't be disabled when you disable QuickUnlock.
