### ISSUE TITLE
Auto-save password not working under Android 9

### ISSUE THREAD

**Issue by Teetoow** [PhilippC/keepass2android#878]
Hi, 

I am very interested in auto-saving passwords entered into websites (through google chrome). However even if the "auto-save" option is checked there is nothing which ask me to save the password (except the chrome wallet).
It's the same under Firefox.
I'm on android 9

**Comment by PhilippC** [comment]
This requires that you enable the Android AutoFill service. Unfortunately it's not supported from Chrome, but should work with Firefox.
