### ISSUE TITLE
Keepass2android and Autofill plugin automatically removed from running process after a while under android 9

### ISSUE THREAD

**Issue by Teetoow** [PhilippC/keepass2android#879]
Hi, 

Like many other processes, keepass2android and it's plugin "autofill" are removed from running processes after some time even if "no battery optimization" is set for them.
Whereas it is easy to restart keepass2android, I can't have the autofill plugin restarting. I need to reboot the phone in order to get it working again..
My android is a stock 9 android.
It's the latest keepass2android and autofill plugin.
Thanks.

**Comment by PhilippC** [comment]
KP2A is doing whatever is possible (at least what I know) to prevent being killed. This behavior also sounds pretty device specific, as it is not observed by most users (including me). Maybe you can find other aggressive "battery optimization" settings or apps?
