### ISSUE TITLE
Child database opening always results in error: "String 'path' does not match pattern"

### ISSUE THREAD

**Issue by marcelser** [PhilippC/keepass2android#880]
I'm using KeeAutoExec on PC (where it works fine) and in KeePass which also created some IfDevice entries it seems for my different phones in there (at least it shows them when I look in the configuration dialog for child databases in KeePass2Android). However although on PC opening the database works fine on KeePass2AutoExec when it tries to open the database (which lies on dropbox) it always shows the error "String 'path' does not match pattern". After this error it's shows me the "unlock database" error. When I now enter the correct password (which is stored in the child database settings) it correctly opens the database which lies on dropbox. But why does the AutoOpen always fail with this error?

**Comment by Karreg** [comment]
I'm not sure this is related, but I'm using google drive, and to avoid issues with autoexec, I had to create 2 entries: 1 for desktop (IfDevice preventing to open it on mobile) and 1 for mobile (created by keepass2android, with IfDevice preventing to open it on desktop). Have you tried this?

**Comment by PhilippC** [comment]
I guess this should be solvable ith the hints from @Karreg . Please re-open if the issue persists.
