### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by alsophee** [PhilippC/keepass2android#881]
I have an application for example lastpass where the passwords and username and username I want from the application to transfer all the passwords from lastpass to keepass2android I hope to add this feature 
And thank you all.

**Comment by Lineflyer** [comment]
There are AFAIK some tools to convert or transfer between different password storage formats.
You could also do this transfer with other Keepass compatible applications (like on your PC) instead of keepass2android.

**Comment by alsophee** [comment]
What does AFAIK mean and where do I find this thing?

الحصول على Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Karreg** [comment]
Let me Google it for you:

https://www.guidingtech.com/11787/transfer-passwords-lastpass-to-keepass-right-way/
