### ISSUE TITLE
Fingerprint Quick Unlock Error (!)

### ISSUE THREAD

**Issue by Zhaph** [PhilippC/keepass2android#884]
After enabling Fingerprint quick unlock on my phone the UI shows an error icon next to the quick unlock field.

Tapping that shows a stack trace that I can't copy or screenshot starting with:

> Error initializing fingerprint unlock:
> Java.Lang.RuntimeException: Exception of type `Java.Lang.RuntimeException` was thrown.  
> at `keepass2android.FingerprintDecryption.Init()`

The primary failure seems to be:

> Failed to init Cipher.

In `QuickUnlock.onResume()`

App Version: 1.07-r1
Phone: One+ 7
OS: Oxygen OS 9.5.6

**Comment by zer212112** [comment]
i have same problem

xiaomi redmi 5 plus/note 5 india (vince)
android 9.0 aosp extended
app - 1.07-r1

**Comment by ladams00** [comment]
I get the same error icon and stack trace at the quick unlock screen (with finger print unlock enabled).

App Version: 1.06g (Offline version from Google Play store)
Phone: Google Pixel 3 XL
OS: Android 9

**Comment by fgie** [comment]
Disable quick unlock with fingerprint in the database settings.
Close and open the database.
Enable quick unlock with fingerprint again.
You should be asked to save your fingerprint.
Worked for me!

**Comment by ladams00** [comment]
> Disable quick unlock with fingerprint in the database settings.
> Close and open the database.
> Enable quick unlock with fingerprint again.
> You should be asked to save your fingerprint.
> Worked for me!

fgie, thank you for the suggestion!  It worked perfectly :-)  I hope Zhaph gives it a try.

**Comment by Zhaph** [comment]
@fgie indeed, that seems to have worked, thanks.
