### ISSUE TITLE
Using K2A keyboard, User button also submits web forms

### ISSUE THREAD

**Issue by Kingwad** [PhilippC/keepass2android#89]
Situation: Using the K2A keyboard to enter the username and password in any web form.

Expected behavior: The User button types out the username, and the Password button types out the password.

Observed behavior: The User button types the username and attempts to submit the form on the webpage. The Password button types out the password without submitting the form.

Whenever I press the User button to fill out a username field on a website, the website then complains that the password field is blank, which means that if the username is name, the K2A User button is entering \<n\> \<a\> \<m\> \<e\> \<some other input that attempts to submit the form\> which has become quite annoying, and I have started filling out password fields before username fields, as the Password button does not input whatever the User button is inputting after it is finished with all the expected characters.

Device: Moto Z, Android 7.1.1, K2A 1.02 from the Google Play Store

**Comment by ottinho** [comment]
I can confirm this behavior.

Device: Samsung Galaxy S7, Android 7.0, K2A 1.02 from the Google Play Store

**Comment by PhilippC** [comment]
this does not happen for me. Can you please describe on which browser and which website you experienced this?

**Comment by ottinho** [comment]
This happens on every website.

But as I noticed now it seems only to behave like this with Chrome. In Firefox the keyboard works as expected.

**Comment by PhilippC** [comment]
hmm, still can't reproduce, but I currently only have Android 6 devices for testing here.

**Comment by Kingwad** [comment]
I'm using the Chromium from https://f-droid.org/packages/com.dosse.chromiumautoupdater/. On every website I see this behaviour. Auto-fill is disabled.

**Comment by Kingwad** [comment]
Sorry for the frame rate, but this is a gif of the behaviour:

![GIF](https://user-images.githubusercontent.com/439829/32806664-587414e8-c95b-11e7-8807-f8bb1202d184.gif)

**Comment by arana-krypteia** [comment]
I can confirm that this issue occurs for me when using a chrome based browser (e.g. Chrome, Brave, etc).  Doesn't occur when filling password forms in another browser (e.g. Firefox) or android app.  

Android 7.1.2 with Brave 1.037 (based on Chromium 62.0.3202.84)

**Comment by gpion** [comment]
> Doesn't occur when filling password forms in another browser (e.g. Firefox) or android app

Just faced that issue when login from Amazon Appstore app.

**Comment by tsneiva** [comment]
I too am having this issue. In all sites with chrome browser. Works well on Firefox.
Using BQ Aquaris E5 with "pure" lollipop 5.0

**Comment by dbrand666** [comment]
I'm seeing this on brave on both marshmallow and nougat now.

**Comment by dtmichel** [comment]
Same issue here. Also happens with login forms in Apps, not only in Chrome. Setting the password first seems to be a workaround.

**Comment by PhilippC** [comment]
@dtmichel please switch to the beta channel or wait a few days until you get the 1.04b version
