### ISSUE TITLE
Solve a problem

### ISSUE THREAD

**Issue by alsophee** [PhilippC/keepass2android#890]
I want from the application which is when I add a picture for example I want to add a large number of pictures at once not to add every time I add one picture only this is very hard

**Comment by Karreg** [comment]
Large number of pictures. In a password database file. Even though you [already have database size issue](https://github.com/PhilippC/keepass2android/issues/883)?
What in the world are you trying to achieve? I'm really wondering! 😲

**Comment by alsophee** [comment]
I don't understand you clearly. If you You're clearly clear.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BSG2000** [comment]
Maybe you should use the Google Translator and describe your problem again?

**Comment by PhilippC** [comment]
@alsophee  it looks like encrypted file systems like http://sovworks.com/eds/ better suit your needs.

**Comment by alsophee** [comment]
I want to tell you that the application keeppass2 android password manager is very nice and I thank you for this beautiful application

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
