### ISSUE TITLE
Is this app avalible outside of google play

### ISSUE THREAD

**Issue by DiyaaAlkanakre** [PhilippC/keepass2android#894]
Hello there.
I am just wondering if you have this app in places other than Google play like f-droid for example because I don't use Google products at all and I would love to have this app on my android phone.

**Comment by Karreg** [comment]
Hello,

You can get them here: https://github.com/PhilippC/keepass2android/releases
For F-Droid, see #38

**Comment by DiyaaAlkanakre** [comment]
Thank you sir
