### ISSUE TITLE
Connecting to SSH give error com.jcraft.jsch.JSchException

### ISSUE THREAD

**Issue by reetp** [PhilippC/keepass2android#899]
Just trying to set this up on a Samsung S9

I am trying to use SSH keys with my server which does not have password login normally enabled.

The settings all appear correct, public key is added to .ssh/authorized_keys but when I try to login it just throws this error:

```
Error Cannot connect to file provider service
Auth fail
```

My server logs this:

`Received disconnect from 1.2.3.4: 3: com.jcraft.jsch.JSchException: Auth fail`

Config is:

```
Host: 1.2.3.4
Port 2222
Authentication mode: Private/Public key
Initial directory: /somedir/keepass

```

To test I blew my brains out and enabled password authentication on the server.

That worked perfectly first time.

Key authentication works perfectly Connectbot on the phone.

**Comment by PhilippC** [comment]
And you are sure you added the key generated by Kp2a correctly? Or is it another public key?

**Comment by reetp** [comment]
Ironically it was correct, but hadn't pasted correctly - my phone editor pasted it to the end of the previous line rather than as a new line.

I'd just checked the END of the line as the starts are all "ssh-rsa" and the first few letters all being pretty similar and it's hard to see much more on a phone screen.

A desktop screen sorted that stupidity out.

Doh...
