### ISSUE TITLE
Redmi4 prime fingerprint crash

### ISSUE THREAD

**Issue by maxmax20** [PhilippC/keepass2android#90]
Hi,

I have a Redmi4 prime device, running android 6.0.1. 
When I create a new database and want to use the fingerprint as unlock method, the application crashes as soon as the fingerprint got recognized. 

I have tried this multiple of times. 
Best regards,
Mark

**Comment by PhilippC** [comment]
Can you please collect a logcat and post this on #37 ?

**Comment by maxmax20** [comment]
How can I create a logcat file? I am on an unrooted device.

**Comment by PhilippC** [comment]
https://live.paloaltonetworks.com/t5/Learning-Articles/How-to-Collect-Logs-logcat-from-an-Android-Phone/ta-p/57918
