### ISSUE TITLE
Could not access source file: sharing violation

### ISSUE THREAD

**Issue by Justlanz** [PhilippC/keepass2android#900]
I get this error whether I load the database file from Google drive or Pcloud. So far all is well when I load the file local after I download to my phone. I would like to keep it backed up to the cloud to avoid the hassle.

**Comment by PhilippC** [comment]
Can you please collect a log of this? Either with logcat or, if that's not possible, with the app logging system, see app settings?

**Comment by PhilippC** [comment]
closing as no reaction.
