### ISSUE TITLE
A new feature.

### ISSUE THREAD

**Issue by alsophee** [PhilippC/keepass2android#901]
I want the application to support google chrome browser in automatic filling of the username and password I hope to add this feature and you thank you for this wonderful application

**Comment by JohnLGalt** [comment]
It is supposedly already there - I cannot verify if it works or not because I haven't actually tried it.

https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md

**Comment by PhilippC** [comment]
Kp2a offers the "Share URL" approach with the build-in keyboard which works with Chrome, but Chrome does not support Android Autofill at present.
