### ISSUE TITLE
sftp allow to change key strength

### ISSUE THREAD

**Issue by solarflair** [PhilippC/keepass2android#915]
The PKI option for SFTP seems to work fine, but there are two things that don't seem to be possible that I'd like to see added:

1. An option to modify the key size of the key generated by Keepass2Android. I can't tell if it's a 2048- or 4096-bit key or what, and I'd like an option to specify that myself in the settings.

2. An option to load a key from my device's storage instead of the app-generated one. I like to keep one key per device and not clutter up my server's authorized_keys unnecessarily, and so would like to be able to use the key I keep for my phone instead of the one created by the app.

Thank you!

(I tried to label this as a feature request or enhancement, but I don't see a way to do it here

**Comment by PhilippC** [comment]
per 1.) it's currently 2048 (https://github.com/PhilippC/keepass2android/blob/master/src/java/JavaFileStorage/app/src/main/java/keepass2android/javafilestorage/SftpStorage.java#L379)

regarding 2.) this is also requested in https://github.com/PhilippC/keepass2android/issues/929. I will track this second part of the issue in #929 to have one item per issue only.

**Comment by PhilippC** [comment]
you can now import keys in https://github.com/PhilippC/keepass2android/releases/tag/v1.10-pre
