### ISSUE TITLE
Crash upon copying a standard entry

### ISSUE THREAD

**Issue by merrimanmerlin** [PhilippC/keepass2android#920]
App crashed immediately after clicking the copy icon in menu bar when a standard entry is selected.

**Comment by PhilippC** [comment]
which version? Can you collect a logcat (or try the internal logging)?

**Comment by bg777** [comment]
App crashes since version 1.07-r1, in the latest beta 1.07b-pre1 as well.
I downgraded back to 1.05e and it works again without crashes.
I don't know, whether it worked in v. 1.06, because I skipped this version.

**Comment by bg777** [comment]
If I activated internal logging and the database still  unlocked, then the coping works fine.
I needed to lock the db and unlock again to provoke the crash upon coping an entry.
Also, it didn't crash at all if copying a simple entry (without custom fields).

**Comment by PhilippC** [comment]
@bg777  please email to crocoapps@gmail.com. Thanks!
