### ISSUE TITLE
Are databases stored in the cloud cached on the local file system?

### ISSUE THREAD

**Issue by anno1985** [PhilippC/keepass2android#921]
Does Keepass2Android create a local copy when retrieving a database stored on cloud storage? (I.e. is it safe to keep the database in the cloud and a key file locally?)

**Comment by PhilippC** [comment]
you can configure this in settings - app - file handling. By default: yes, a cache copy is created. 
I don't understand how this is related to the second question, however. Please re-open or comment if there's something to clarify.
