### ISSUE TITLE
Keepass2Android on Galaxy S10+ and fingerprint protection

### ISSUE THREAD

**Issue by chmodplusx** [PhilippC/keepass2android#923]
When I enable full fingerprint protection in the database setting and close/reopen the app, it prompts for the finger to unlock the database.  However, there is a cancel button just above the fingerprint icon.  I can just hit the cancel button and go right to entering password.  What's the point of protecting the database with the fingerprint if I can easily hit the cancel button to unlock the database.  

Is this a bug in the app?  I want to remove the "Cancel" button in the fingerprint prompt screen.  There should only be the fingerprint icon and shouldn't be able to get past it without successfully verifying fingerprints.

**Comment by PhilippC** [comment]
Keepass databases are always protected with your master password and the  master password is always sufficient to unlock the database (if someone has access to the database). Fingerprint can be used as a convenience feature to store your master password using the device's secure storage. It's not a feature to increase security but to reduce typing.
