### ISSUE TITLE
sftp to open database use existing key

### ISSUE THREAD

**Issue by pcause** [PhilippC/keepass2android#925]
I want to use sftp to open a remote database.  I fill in the fields and then select public/private key.  This then seems to create a key, but I am using an existing account that has a key and actually the key is in my keepass database.

Am I misunderstanding something?  Is there a way to use an existing key either from thje file system or the database

**Comment by PhilippC** [comment]
this sounds like a chicken/egg problem: how do you want to download the database if the key is inside the database??
KP2A's way of doing this is to generate a key pair specifically for KP2A and put the public key in the server config. That's the best way of keeping the private key secret.

**Comment by pcause** [comment]
No it isn't.  I download the key from a my nextcloud where i put it and then delete it.  I also can transfer by a USB.  I'd like the option to use a local ssh key and not have to have a new key I have to manage.
