### ISSUE TITLE
Untrapped exception when attempting to use fingerprint QuickUnlock on Galaxy Note 10+

### ISSUE THREAD

**Issue by BoarGules** [PhilippC/keepass2android#928]
I just swapped my Galaxy Note 9 for a Galaxy Note 10+ running Android 9, kernel version 4.14.113-16618471.

Instead of a fiingerprint next to _Enter last 3 characters of your password_ there is a ! in a red circle. If I touch that, I get an untrapped exception Java.Lang.RuntimeExeption at keepass2android.FingerprintDecrpytionInit() [0x000d0]
--End of managed Java.Lang.RuntimeException stack trace

I'm sorry I can't send you a proper stack trace but I can't copy and paste the message text. Even a screenshot would be better than nothing but of course that is disabled too.

**Comment by PhilippC** [comment]
can you please try to disable and re-enable fingerprint unlock in the database settings?

**Comment by BoarGules** [comment]
Thank you. That did it. 

Regards

-- 
Paul Keating
The Hague

2019-08-29 09:39

can you please try to disable and re-enable fingerprint unlock in the database settings?
