### ISSUE TITLE
Note 10+ in screen Fingerprint sensor not working

### ISSUE THREAD

**Issue by gschot** [PhilippC/keepass2android#931]
The app did recognize the fingerprint sensor on the back of my old Note 8 but is unable to initialize the in screen fingerprint sensor. I noticed another issue regarding N10+ but mine does not throw an exception. It only mentions that the Fingerprint sensor cannot be initialized

**Comment by gschot** [comment]
Apologies, duplicate, issue was already logged

**Comment by imran** [comment]
App also recognised the back fingerprint sensor on Note 9 but had problems with the 10+

I did this to get it work on my Note 10+

Go in to settings > database settings > fingerprint unlock

Toggle between disable fingerprint / unlock / full unlock

That gave it the jump start it needed and it's working now.

**Comment by gschot** [comment]
Wow, that did the trick indeed! Thanks for the feedback!
