### ISSUE TITLE
pCloud not working

### ISSUE THREAD

**Issue by bernisim** [PhilippC/keepass2android#932]
I'm using ver. 1.07-r1 on Android 7.0.

When I try to choose a file from pCloud, after request of autentication, I receive a page  with a top line containing two little left/right arrows and a label "Principale" ("main" or "root" translated from italian) and below "vuoto" ("empty").
I tried tu unistall & reinstall, but same result.

![Schermata_2019-08-28-00-03-10-007](https://user-images.githubusercontent.com/54603770/63811378-91e32200-c927-11e9-9cc2-49f7e67ddd3c.jpeg)

I attach the log file in which I see a line:
"java.lang.SecurityException: Permission Denial: opening provider com.pcloud.content.CloudEntryContentProvider from ProcessRecord{18064f4 "

[LogKeepass2Android.txt](https://github.com/PhilippC/keepass2android/files/3548285/LogKeepass2Android.txt)

**Comment by PhilippC** [comment]
as far as I know, KP2A will only access the app folder inside pCloud which you should find in Applications/Keepass2Android. This is explained better in the next version. 
Please re-open if this does not solve your issue.

**Comment by bernisim** [comment]
I resolved choosing WebDAV interface instead of pCloud; using
*webdav.pcloud.com
<http://webdav.pcloud.com> *as server, I can choose files from my pCloud
account.

Il giorno gio 29 ago 2019 alle ore 15:48 PhilippC <notifications@github.com>
ha scritto:
