### ISSUE TITLE
KP2A keyboard doesn't paste credentials when TOTP Settings field is present 

### ISSUE THREAD

**Issue by k1r4v** [PhilippC/keepass2android#933]
Steps to reproduce the bug:
- Open the app
- unlock database
- select entry with TOTP Settings and TOTP Seed fields prorerly filled
- switch to any app 
- select a text field
- change keyboard to KP2A Keyboard
- press the keepass button

What happens:
A pop-up shows up, asking to select an entry.

**Comment by PhilippC** [comment]
already fixed, please switch to https://play.google.com/apps/testing/keepass2android.keepass2android
