### ISSUE TITLE
Merge results in overwriting of entry, even if it happens in two different fields of same entry.

### ISSUE THREAD

**Issue by ashjas** [PhilippC/keepass2android#94]
I was testing DB merging, when two devices simultaneously change in a database.
I figured out, that if the users modify different entries, the merging works fine, but the merging results in overwriting when both users make change in a single entry but different fields.
I can understand, that if the user modifies uses same entry and same field, there is know way to know the merge, and that can result in overwriting. 
But, as i checked, even if the users work on different fields of the same entry, the merging results in overwriting.
E.g both user work on entry "A"
user1 modifies comments,
user2 modifies url.
but when the merge happens, even though the app says to merge, but actually, overwriting happens, and one of the user's edits are lost.
Posting this as an issue, as discussed over email.
Anyways, thanks for creating and maintaining this wonderful app.

**Comment by Wuestengecko** [comment]
You might want to take a look at the "Technical Information" about database synchronization here: https://keepass.info/help/v2/sync.html
This explains the philosophy behind the current behavior.

**Comment by ashjas** [comment]
Ok, I get the sync policy of keepassx file format, so it's not an issue of this app.. But I couldn't find any way to view the history entries of any entry/field?

**Comment by PhilippC** [comment]
currently this is only possible on the PC. Feel free to open another issue for this.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
#298
