### ISSUE TITLE
[feature request] import option

### ISSUE THREAD

**Issue by Almenon** [PhilippC/keepass2android#943]
It would be awesome if there was a import option like on keepass on the desktop where key entries with newer timestamp would overwrite key entries with a old timestamp.

In the meantime the workaround is to do the operation on the desktop keepass.

**Comment by Almenon** [comment]
https://i.imgur.com/C4r9j5r.png

**Comment by PhilippC** [comment]
what's your use case for this? I was assuming that such features are use for rare maintenance tasks only and deliberately decided to keep this out of the app?

**Comment by Almenon** [comment]
I have multiple computers and I don't trust my secrets on Google drive.  I use the import option to sync secrets between the computers (I copy over the file to the computer first to import from)

**Comment by PhilippC** [comment]
I think KP2A should work without "importing" in this scenario: if you open the file from external storage (e.g. USB stick over OTG adapter) you can work with the app (read/write) even without the stick being attached (KP2A has a local cache copy). If you later re-attach the USB stick, you can choose the "Sync" option in KP2A from the menu. It will apply the same merge strategies as the desktop version. (i.e. it works even if you changed the kdbx on the USB stick *and* made changes in KP2A's cache copy) 

Please re-open if this does not solve your issue.
