### ISSUE TITLE
k2a keyboard: cannot select entry with traytotp data

### ISSUE THREAD

**Issue by fubar-coder** [PhilippC/keepass2android#948]
I cannot select entries that contain TrayTOTP data from the K2A keyboard.

How to reproduce:

1. Create an entry in Keepass 2 (Windows, with TrayTOTP)
2. Add the TrayTOTP data to the entry
3. Load the kdbx file into K2A
4. Klick on an input field (to get the virtual keyboard)
5. Switch to the K2A keyboard
6. Select the TrayTOTP entry

What happens:

I see the default (non-K2A) virtual keyboard.

What I expected to happen:

I see the K2A virtual keyboard that allows access to the username, password and the OTP.

**Comment by osiox** [comment]
+1
In my case it started happening after upgrade to Android 9 on Samsung Note 8 and after k2a keyboard fix for samsung phones.

**Comment by JohnLGalt** [comment]
I was having issues until a new beta was released, 1.07b-pre1 - that fixed the issue.

https://github.com/PhilippC/keepass2android/issues/933
