### ISSUE TITLE
Pixel 2 XL - fingerprint authentication crashes

### ISSUE THREAD

**Issue by badgooner** [PhilippC/keepass2android#95]
Error initializing fingerprint unlock.
Java.Lang.RuntimeException was thrown at keepass2android.Fingerprint.Decryption.Init() 0x000a3

**Comment by whiten01se** [comment]
I have that happening on Pixel 1 XL too, i believe since Android 8.

**Comment by MinceMan** [comment]
I was getting this til I wiped data.

**Comment by badgooner** [comment]
Awesome! That worked for me. I cleared the cache and data for the app.

**Comment by whiten01se** [comment]
Confirmed working.
