### ISSUE TITLE
Android 10 Inputstick Plugin not showing devices 

### ISSUE THREAD

**Issue by 2ec98lwlhimflzx2** [PhilippC/keepass2android#951]
My Pixel 3 XL was updated to Android 10 yesterday. 

The only problem I have right now, is that KeePass2Android don't show the InputStick devices  screen when I try to connect to one of them. Yes, I have more then one of the InputSticks setup with the phone. 

Have to open the plugin itself, choose "Remote (keyb/mouse)". Connect from the plugin in to the InputStick. Then I could send the data from KeePass2Android to the Inputstick. 

Maybe a change in the Api for the windows, bu it worked with Android P without a problem.

Kind regards

**Comment by PhilippC** [comment]
Input stick plugin is developed by Jakub Zawadzki. Please contact him about this (http://www.inputstick.com/contact/).
