### ISSUE TITLE
Cannot select (local) key file path (Android 10) (V 1.07-r1)

### ISSUE THREAD

**Issue by dennisboeck** [PhilippC/keepass2android#953]
After pressing "Change path of storage location" (translated from german - sorry - I don't know the english version of the button) for the key file, I select "Anroid file browser". Then (I guess) the default android file browser appears, but I cannot navigate to a certain folder, but only see the last used files or navigate to pictures, videos, audio, downloads. 
The same happens if I click on "open with external app".
How can I navigate to a specific local path for the key file? (if it is not located in the pictures, videos, audio, downloads - folder)
Thank you for your help/ideas.

**Comment by JohnLGalt** [comment]
Well, is you key file using a cloud service to be shared to your phone?  Or did you just manually copy the file from your computer via USB cable?

**Comment by dennisboeck** [comment]
I copied the key file manually via USB cable to the internal storage. 
For security reasons I don't want to have the key file on a cloud service.
With the app "File Manager Pro", I can easily navigate to the path: Internal Storage/folder-x/key-file-z
If you need any screenshots to understand the problem better - I can provide them.

**Comment by JohnLGalt** [comment]
If you copy the file to the downloads folder under internal storage, then
you can use the hamburger menu to select downloads and access the key file
like that.

**Comment by dennisboeck** [comment]
I tried it - it works with the download folder, but a key file is a very important file which I don't want to mix with downloads/video/audio/picture-files, therefore I was looking for a solution to keep in a dedicated/own/self created folder.

**Comment by JohnLGalt** [comment]
Ok, then what you need to do is just the system file picker, then use the 3
vertically aligned fits in to right corner to enable internal storage, then
use hamburger menu to pick your phone / internal storage, then navigate to
the file.

**Comment by JohnLGalt** [comment]
Vertically aligned *dots*

**Comment by dennisboeck** [comment]
Thank you very much - that was the solution (the display of internal storage was deactivated).
Now I can select the internal storage and the folder and the key file.
