### ISSUE TITLE
Support for upcoming Google Face Unlock

### ISSUE THREAD

**Issue by RobBiddle** [PhilippC/keepass2android#955]
Anyone know if Face Unlock on the Pixel 4 will work immediately as a replacement for the existing Fingerprint authentication in Keepass2Android?  I'm hoping the Android API doesn't distinguish between the sensor difference on the back end.

**Comment by betasheet** [comment]
There's a new BiometricPrompt API since Android P: https://www.xda-developers.com/android-p-new-biometrics-api/amp/

I doubt that keepass2android uses it yet.

**Comment by PhilippC** [comment]
duplicate of https://github.com/PhilippC/keepass2android/issues/795
