### ISSUE TITLE
Entire Password Doesn't Show

### ISSUE THREAD

**Issue by dlnycs** [PhilippC/keepass2android#96]
When an entry has a long password string, only the first 15 characters show and there is no way to scroll unless you edit the entry.  Can you please wrap the password or make the field scrollable?

**Comment by Kingwad** [comment]
@dlnycs As a crude half-workaround, long passwords can be viewed by rotating the screen to landscape. Of course this just kicks the can further out and _very_ long password strings still don't show.

**Comment by dlnycs** [comment]
Thanks, Kingwad, that’s a good workaround for medium length passwords.

**Comment by PhilippC** [comment]
implementation note: "unprotected" string fields are correctly displayed/wrapped. -> Don't toggle transformation method but completly hide one control and show another.
