### ISSUE TITLE
Unable to unlock using fingerprint on Android 10

### ISSUE THREAD

**Issue by TheMadRuffian** [PhilippC/keepass2android#961]
Tried configuring fingerprint unlock but it would show the option to unlock.

Device: Mi A1
Android version: 10
Rooted: Yes
App version:  1.07b-pre1

**Comment by PhilippC** [comment]
is this a duplicate of https://github.com/PhilippC/keepass2android/issues/934 or do you mean something else?

**Comment by TheMadRuffian** [comment]
No, it was not the same issue. But I made a mistake in configuring the database. Now everything is working properly. Kindly mark this issue "irrelevant" or delete it.
