### ISSUE TITLE
"Kill App Process" not shown when closing DB

### ISSUE THREAD

**Issue by waaweech** [PhilippC/keepass2android#968]
When opening the DB, where you are asked to type in your master password, there is a useful option to "Kill App Process". 

But,

After closing the DB, the last screen shows up only with "Open file..." and "Create new database..." fields. No "Kill App Process" option is available anymore.

Confirmed on Android 9, 10.

**Comment by fzbyaa** [comment]
samw issue ,difficult to make it available anymore

**Comment by fzbyaa** [comment]
android6

**Comment by PhilippC** [comment]
not going to implement this. I don't think this button is necessary at all :-)
