### ISSUE TITLE
"Notes" Field Editing - KP2A app on Chromebook

### ISSUE THREAD

**Issue by waaweech** [PhilippC/keepass2android#970]
When running KP2A app on Chromebook (Chrome OS), using the "Ctrl" + "Enter" keys to go to a new line in the "Notes" places the cursor at a next field instead.

The workaround:
"Shift" + ""Enter" keys instead.

**Comment by PhilippC** [comment]
This sounds totally valid to me. Please reopen if i misunderstood.
