### ISSUE TITLE
Database file modified externally

### ISSUE THREAD

**Issue by LHuisingh** [PhilippC/keepass2android#971]
I added an entry to my database and when I clicked on the Save icon it said "The database file was modified externally. Do you want to load and merge the changes before saving? Select No if you want to overwrite the external changes."
Why does it say "external changes" when it was KP2A that made the change. I've not seen this behavior before. I've tried reselecting the database again using the System file picker but with the same results.

**Comment by PhilippC** [comment]
Before KP2A saves a file, it reads the existing file and compares that to what was loaded before. Are you 100% sure that no other app could access the file? What storage type are you using?

**Comment by LHuisingh** [comment]
I'm using the device storage, not external or removable.  The only other app would have been Dropbox or DropSync which I use to sync the file into my Dropbox account.  I've never seen this issue before in all the years I've used the app.  The one thing different this time was that I had created a new entry at the root of the file, not within a sub-folder.

**Comment by PhilippC** [comment]
Well that sounds to me like the file was updated by DropSync while it was open in KP2A - then that's totally expected behavior. Please re-open if you think this is a bug, but to me it sounds very reasonable with the current information.

**Comment by lost2** [comment]
Well, that happens to me also. I have no external storage (storage card, Dropbox, cloud sync, etc) and store a unique KP2A DB file on internal phone storage. This is creepy! If this warning is true, some other installed app is unexpectedly accessing this DB file while open!!

**Comment by PhilippC** [comment]
@lost2  is your database stored under a "content://..." URI? (this should be visible on the password screen if you pull down the header of the screen)
