### ISSUE TITLE
Add support for Personal Vault One Drive

### ISSUE THREAD

**Issue by bHb013** [PhilippC/keepass2android#972]
Just started playing with this, the native file explorer doesn't see the (shortcut/symbolic link/whatever it is) to access personal vault.

**Comment by PhilippC** [comment]
I don't believe there is access for third-party apps to this folder, but I asked this on https://stackoverflow.com/questions/58195061/access-onedrive-personal-vault-through-api. Maybe someone proves me wrong.

**Comment by PhilippC** [comment]
closing this. please re-open if anybody has information how to access the personal vault.

**Comment by LubomirH** [comment]
please vote for the extension of the Graph API extension https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/40554916-add-support-for-onedrive-personal-vault-folder
