### ISSUE TITLE
"Notes" Field Editing - KP2A app on Chromebook Laptop

### ISSUE THREAD

**Issue by waaweech** [PhilippC/keepass2android#973]
When running KP2A app on Chromebook laptop (Chrome OS), using the "Enter" key to go to a new line in the "Notes" field, the app places the cursor at a next field instead.

The workaround:
"Shift" + ""Enter" keys instead.

**Comment by waaweech** [comment]
I've reopened this issue. Isn't the "Enter key" on the physical keyboard supposed to take you to the new line?

**Comment by PhilippC** [comment]
I don't think so. E.g. in the web UI for WhatsApp, pressing the Enter key sends the message. Shift+Enter adds a new line.

**Comment by waaweech** [comment]
OK, Philippe. If Shift+Enter is normal then you can close this issue. Thanks.
