### ISSUE TITLE
AutoFill can't be disabled

### ISSUE THREAD

**Issue by Przbl** [PhilippC/keepass2android#977]
I am using KP2A Offline on Android 8 and decided to try the AutoFill feature.
So I went to "Anwendung > Tastatur" and set the check mark to the AutoFill setting.
Then I installed the AutoFill Plugin.

Later on, I decided not to use it anymore and tried to disable it, so I did the following:
• I removed the setting's check mark under "Anwendung > Tastatur"
• I deinstalled the Plugin
• Additionally I found an entry in Android's settings under "Eingabehilfe > Dienste". I set it to off. Several reboots later that KP2A-entry in this setting was gone.
• I cleared the app's cache

But I still get the the prompt to fill the fields using KP2A and the prompt to store the user/password in my database.

The issues discussed here on GitHub regarding AutoFill mainly focus on the text in the settings of "Passwort-Zugriff >Autofill-Dienst" that still says "enabled" even if it's not. This is also the case with me but I don't bother what is written there as long as I can switch off Autofill. The second things that is discussed here is the message _"Keepass2Android supports Android's Autofill feature but it looks like you haven't enabled it yet."_ but since it's apparently enabled on my system I don't see this message anymore.

So are there any ideas how to finally get rid of the AutoFill feature?

**Comment by Przbl** [comment]
Still no idea how this can be turned off once it has been activated but I solved the problem by completely removing the app and the app's cache. After reinstalling I just declined using the AutoFill feature.

**Comment by PhilippC** [comment]
it looks like you are talking about different types of "Autofill". The prompts you saw came from Android 8's Autofill service which you need to disable in Android settings/Autofill.
