### ISSUE TITLE
Documentation request: Difference between Database Caching and Local Backup

### ISSUE THREAD

**Issue by RedEye2063** [PhilippC/keepass2android#978]
In the application settings there are two options that sound very similar:
- Database Caching
- Local Backup

I can activate/deactivate these independently. Both seem to save copies of my database. Could someone please describe the exact difference and why both exist? Perhaps this would be a reasonable addition for the official documentation file. Thank you.

**Comment by PhilippC** [comment]
added this on https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md
