### ISSUE TITLE
Error initializing Fingerprint Unlock on Nokia 8

### ISSUE THREAD

**Issue by jeff-schram** [PhilippC/keepass2android#98]
At Fingerprint Rotionderdelen.init()[0x000d0]
...
caused by
InvalidKeyException: Only SecretKey is supporter

Note that the Nokia 8 integrated the fingerprint sensor in the (capacitive) home button. Placing a finger on the sensor results in returning to the home screen

**Comment by PhilippC** [comment]
please add this as a comment to #37 .
