### ISSUE TITLE
OneDrive Keepass2Android App folder access token issue

### ISSUE THREAD

**Issue by wikisonpr** [PhilippC/keepass2android#986]
A few days ago I updated to version 1.07b-pre2 and saw that access to OneDrive own app folder seemed to be a new addition, so I tried it out and was able to synchronize.  But have been having issues getting the database to sync again.  I get a CompactToken validation error.  

The only workaround is to choose "Change Database" and opening it again from Onedrive.

This issue seems to be simillar to [#983](https://github.com/PhilippC/keepass2android/issues/983) but since that one indicates it's for OneDrive for Business I figure I should open a different issue number.

Attached log file from Keepass2android during event.
[keepass2android_log_10102019.txt](https://github.com/PhilippC/keepass2android/files/3714243/keepass2android_log_10102019.txt)

**Comment by PhilippC** [comment]
please check if this is fixed in 1.07-r0 which I uploaded to PlayStore just at the time when you wrote this.

**Comment by nischl** [comment]
Looks good, synced perfectly well with Onedrive for Business

**Comment by wikisonpr** [comment]
Has been working perfectly since the latest update.
