### ISSUE TITLE
Theme switch on time of day

### ISSUE THREAD

**Issue by daevidvincent** [PhilippC/keepass2android#987]
The light dark theme should have a 3rd option to switch based upon time of day or battery as other google apps do.

![Screenshot_20191011-105304_Keepass2Android](https://user-images.githubusercontent.com/20825058/66673752-18bd3700-ec16-11e9-9c4b-820f400015b5.jpg)
![Screenshot_20191011-105442_Calendar](https://user-images.githubusercontent.com/20825058/66673761-207cdb80-ec16-11e9-9cfb-facc94b69569.jpg)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
I would prefer to let it follow inheritance the system wide dark mode settings of Android 10. Make it consistent. Than set your system settings accordingly as wished. Not per app.

**Comment by warkx** [comment]
Theme following system would be great with Android 10 and more 👍

**Comment by PhilippC** [comment]
this has been implemented in the meantime
