### ISSUE TITLE
Add support for Mega

### ISSUE THREAD

**Issue by louismaxx** [PhilippC/keepass2android#99]
Hi, 
Great work on the app so far 👍 

Will it be possible to add support for Mega ? I have to download back the .kdbx file everytime I want to get the latest additions I made on PC.

**Comment by gloomy-ghost** [comment]
They do provide a [SDK](https://mega.nz/sdk) written in C++. I don't have any experiences in Android development, but I guess NDK can be used here?

**Comment by DaPutzy** [comment]
Would also love Mega support :)

How about this package as a start?

https://www.nuget.org/packages/MegaApiClient/

**Comment by PRoots** [comment]
I currently use Keepass v2.x on Linux and Keepass2Android, using Dropbox to sync between the two. With DropBox becoming more Linux unfriendly I would love to be able to sync via Mega instead.
Thanks for the App, it very useful and work

**Comment by ZigZaggh** [comment]
I would love to see a MEGA implementation too, Dropbox has become unusable on Linux and MEGA got an awesome support.

**Comment by gilbsgilbs** [comment]
@PRoots @ZigZaggh and other people concerned by Dropbox recent decision of dropping proper Linux support, be aware that PCloud integration has been merged in #523 and should land soon in an upcoming KP2A release. I implemented it because of Dropbox' announcement and because their desktop client supports Linux (as far as I can tell).

Before choosing to implement PCloud, I had a quick look into the alternatives, and I chose not to implement MEGA because it seemed to be a way harder task. A C++ SDK means you need some bindings and use the NDK. Definitely not impossible, but not worth the effort as far as I am / I was concerned. I already had to workaround building a Xamarin.Android app with Java dependencies on my Linux machine and it was all I could take.

That being said, MEGA support would indeed be interesting to see IMO.

**Comment by luispablo** [comment]
MEGA seems to be superior to Dropbox in many aspects, and I suppose that many people, like myself, are starting to discover them because of the recent problems with Dropbox (claiming to stop syncing from Novembre 2018)
I don't know if this conditions make your effort more worthy, but the scenario is going to change from this moment on.

**Comment by nanowinner** [comment]
Definitely would love to see support for MEGA. For me, this is pretty much the only obstacle for using it!

**Comment by leomayer** [comment]
+1 for Mega

**Comment by ivan1986** [comment]
for now may help https://play.google.com/store/apps/details?id=com.ttxapps.megasync

**Comment by leomayer** [comment]
Does NOT really help cuz I can sync with a folder - defined in Mega. From there the file is taken (via Android AppBrowser) and copied into keepass2android. But an update of the same file in not detected from keepass2android :-/

**Comment by deutrino** [comment]
I believe MEGA is end to end encrypted, which is a significant advantage over some other cloud storage providers. An option for those who specifically would prefer such a provider for cloud storage of their keyfile would be nice :)

**Comment by boggle247** [comment]
+1 would like to see mega integration

**Comment by rsevero** [comment]
Looking for MEGA support also...

**Comment by VecH** [comment]
Are there any plans to add a MEGA cloud?

**Comment by vabatta** [comment]
+1

**Comment by Gyilkos91** [comment]
Nice, looking forward to the MEGA support!

**Comment by aguinaldo92** [comment]
it'd be great to have MEGA support 👍

**Comment by refex** [comment]
willing to work on it if someone would mentor me

**Comment by gilbsgilbs** [comment]
@refex I don't think I can really mentor you on this since I'm not a Xamarin expert, but you can see how I implemented PCloud support here: https://github.com/PhilippC/keepass2android/pull/523

However, I think that making MEGA work would be way harder since you'd need to use the NDK to make use of the MEGA API (they don't have a plain Java API like PCloud AFAICT). I could probably dig a bit more, but developing a Xamarin app under Linux is still a huge pain. I don't think I want to face this again.

Still, if you have very specific question, do not hesitate to ask. I can try to help.

**Comment by zeled** [comment]
+1

**Comment by 14geronimo** [comment]
+1

**Comment by bo712** [comment]
+1, I'm waiting Mega)

**Comment by gujou** [comment]
+1 :)

**Comment by stefanocog** [comment]
+1

**Comment by nexist418** [comment]
I just wanted to add my $0.02 for adding this.

**Comment by hamiltonrn** [comment]
Much needed feature, the only reason I have Dropbox is because of KeePass2Android, MEGA is much better on Linux and have much more free space.

**Comment by tigerduck** [comment]
MEGA support would be very mega great! VOTE!

**Comment by Terra972** [comment]
Up please

**Comment by madsamjp** [comment]
Would also appreciate support for Mega. Their strong open source encryption is the only way I trust to sync my passwords with my device.

**Comment by PhilippC** [comment]
I finally found a way and the time to implement this. Please note that I'm not 100% happy with the API, which - as far as I can tell - requires me to request the metadata of all nodes (i.e. files, folders etc.) in the Mega account for the implementation to work properly. I do not use Mega personally, so I do not have access to an account with many files in it. Please give me some feedback if the implementation is unusable because it is slow or anything.

**Comment by c-erb** [comment]
Thank you very much for this. Brilliant.

**Comment by PRoots** [comment]
Thanks for this, that sounds great. Will this be in the next release or do I need to be on the beta release to give it a try?

**Comment by louismaxx** [comment]
> I finally found a way and the time to implement this. Please note that I'm not 100% happy with the API, which - as far as I can tell - requires me to request the metadata of all nodes (i.e. files, folders etc.) in the Mega account for the implementation to work properly. I do not use Mega personally, so I do not have access to an account with many files in it. Please give me some feedback if the implementation is unusable because it is slow or anything.

Hello @PhilippC 

I've installed the beta update for the Mega Integration and tried it.
I encountered an error when logging at first due to the fact that I've setup 2FA on my Mega account. see screenshot below ![Screenshot](https://user-images.githubusercontent.com/11667048/152985055-ba107d56-4aa7-4dda-9026-71e1f05b031b.jpg)

I've disabled 2FA to try again and it worked.
MEGA's API documentation doesn't mention 2FA and this issue seems to be shared by other projects as well.

Let me know if you need actions on my part

**Comment by DaPutzy** [comment]
I dont have 2FA and can confirm it worked as expected 👍  however I did not test it long term, I only checked opening the database once.

If you want me to test it for a longer period of time let me know and I migrate my database to mega.
Thanks for your work on this perfect piece of software ❤️

**Comment by PhilippC** [comment]
thanks for the feedback! I think 2FA is currently not possible. Did you guys have a large number of files in your mega account? How was the performance?

**Comment by DaPutzy** [comment]
I have about ~100 files and performance was excellent.

**Comment by iamludal** [comment]
Hello, thanks for adding MEGA support to the app.

Apparently, 2FA is not working by now. I saw that it was not easy to implement, and that the MEGA's API documentation doesn't mention it.

However, I've seen that [this app](https://play.google.com/store/apps/details?id=com.ttxapps.megasync&hl=en&gl=US) if using the 2FA feature of MEGA, and it works perfectly. The app does not seen to be open source, but you could try to contact the developer to get information about how they implemented 2FA ?

**Comment by PRoots** [comment]
Just to update my previous comment having been using the Mega option for over a week now.
some days when I try to open the database i do see quite a long delay and a couple of times I have given up, backed out of the app and tried again. When I have done that the database has opened almost immediately. Other days there is probably a bit more of a delay in opening the database than I used to see with Dropbox. Is it enough to bother me? No, it works, and I am happy.
Great work
Thanks

**Comment by sbar42** [comment]
I would like to try KP2A with Mega but the Play store says beta programme is full. Is there another way I can get the latest version?

**Comment by iamludal** [comment]
@sbar42 You can get the APK from [the latest release](https://github.com/PhilippC/keepass2android/releases/tag/1.09d-r0)

**Comment by sbar42** [comment]
Many thanks @iamludal 👍

**Comment by zero-skill** [comment]
Hello everyone, congrats for the app, its amazing.

Im testing the [1.09d-r0](https://github.com/PhilippC/keepass2android/releases/tag/1.09d-r0) release, specifically the Mega integration feature.

I have about `~90 GB` of files on my Mega storage and can report that the performance of the keepass2droid app to be quite slow on that account ... about `60~80 seconds` for the first database open and another `60~70 seconds` on a database save.
Its acceptable for me, b'cause when reopen a database, the app uses the local cache and works faster.

So, great work guys.

But my question is, Will this feature be optimized in the future?


The only quick fix to fix it at the moment is to create a new account just for the keepass db (but not the ideal case use)

**Comment by doraeric** [comment]
Hello,
I am using 1.09d-r0, and I have sync issue with mega.

I first import database from mega. I can see all my record. Then, I added a new record from pc and uploaded to mega. I tried to sync from keepass2android, it said it's already synced, but I can't see the new record.
I have to delete app data and re-import database from mega to see the change. Am I doing something wrong?

**Comment by lackovic** [comment]
> Hello, I am using 1.09d-r0, and I have sync issue with mega.

Same here: I make a change from the computer, wait until the file is uploaded to Mega, open Keepass2Android, I see _Source file and cache are synchronized_, once I enter the database I cannot see the change made from the computer.

As temporary workaround I rolled back to the Google Play version, used [Autosync for MEGA - MegaSync](https://play.google.com/store/apps/details?id=com.ttxapps.megasync&hl=en&gl=US) (thank you @ivan1986!!!) to keep a local database on my phone in sync with the one on Mega and then open my database from Keepass2Android with _System file picker_. The only downside of using this approach is that the minimum synchronization interval is 5 minutes, so I either need to wait that time to get the changes made on the computer synchronized to the phone or trigger a manual synchronization, which is not that big of a deal after all. Changes on the phone are synchronized instantly to the computer.

<details>
  <summary>Reasons why I migrated from Dropbox to Mega.</summary>

- Dropbox does not offer a plan smaller than 2TB
- Dropbox free plan has recently introduced a limit of 3 connected devices
- Dropbox user interface is ugly and clunky
- Dropbox is suffering from several bugs
- Mega free plan is 20GB (was 50GB when I opened my account)
- Mega offers a reasonably sized small plan of 400GB
- Mega feels much faster than Dropbox
- Mega user interface is more user-friendly than Dropbox

</details>

**Comment by mhrivnak** [comment]
Any updates on when this will be released? It looks like the prior version, [v1.09c-r0](https://github.com/PhilippC/keepass2android/releases/tag/v1.09c-r0), is what's still available from the play store.

**Comment by master-bob** [comment]
> Hello everyone, congrats for the app, its amazing.
> 
> Im testing the [1.09d-r0](https://github.com/PhilippC/keepass2android/releases/tag/1.09d-r0) release, specifically the Mega integration feature.
> 
> I have about `~90 GB` of files on my Mega storage and can report that the performance of the keepass2droid app to be quite slow on that account ... about `60~80 seconds` for the first database open and another `60~70 seconds` on a database save. Its acceptable for me, b'cause when reopen a database, the app uses the local cache and works faster.
> 
> So, great work guys.
> 
> But my question is, Will this feature be optimized in the future?
> 
> The only quick fix to fix it at the moment is to create a new account just for the keepass db (but not the ideal case use)

That seems to be an issue with the Mega API at the moment, per what the main dev said [here](https://github.com/PhilippC/keepass2android/issues/99#issuecomment-1030639047) or the implementation of the gpailler/MegaApiClient, which is being used to access Mega.

So, assuming the [current implementation](https://github.com/PhilippC/keepass2android/commit/26f0ab66616cb6f9ca00b32927a6d5e6c19ffce8) is correct, performance could be improved if the MegaAPIClient allows for not all metadata to be retrieved or the Mega API is changed to allow this.

My suggestion to you would be to create an issue here about improving Mega Performance (and reference this issue), ask the MegaAPIClient dev person if the Mega API allows for not retrieving all the metadata, and / or ask Mega to have the API allow for partial metadata retrieval. Feel free to due none or all of course.

Cheers and thanks to the main dev.

**Comment by alpenblauwtje** [comment]
First, thank you for supporting Mega! Why this is "necessary" see #2301.
Compared to pCloud (and Dropbox I assume) there are sync issues with the Mega implementation. See the following scenario:

1. Store the database somewhere in the Mega cloud. 
2. Open this keepass database on a laptop (e.g. with KeepassXC) and on Android with Keepass2Android.
3. Make a change on the laptop and then a change on Android.
4. KeepassXC on the laptop will warn that a change was made and offers to merge the changes. Merge these changes.
5. K2A on Mega sees changes, with doesn't offer to merge them, instead a "API error ..." occurs.

Even worse, after repeating this scenario suddenly K2A is aware of changes, offers a menu to merge changes, but after that it only shows a "Busy" dialog where it tries to write changes. Even after closing the K2A app it comes back in this state. There is nothing a regular user can do to get out of this situation. This is quite worrying.

**Comment by stg93** [comment]
Thank you for the great app. I really would love to see 2FA support for Mega.

**Comment by Micha00000** [comment]
By the way and off-topic:

Keepass Android (2.56 latest version) says that the file on Googledrive is identical to the one on the smartphone.
Total nonsense.
I have changed data on the PC several times and saved it in Googledrive.
When I go to Synchronize database in the Keepass Android app, I get the message: Remote and cache files are identical.
No, they are not!
This behavior has already occurred several times, sporadically.

**Comment by alpenblauwtje** [comment]
@Micha00000 K2A *does* work with Mega, though with severe disadvantages.  The implementation for Mega is also not stable. E.g. when I change an entry simultaneously on a desktop and with K2A on a phone, the change is seen on desktop but not in K2A, and when i manually synchronise I get an exception (Java.IO.FileNotFoundException).

I do appreciate Philips work though, and I consider the implementation for Mega as 'experimental' :-)
Implementations for e.g. Dropbox of pCloud are solid as a rock.
