### ISSUE TITLE
Allow autofill in Vivaldi browser

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#990]
"com.vivaldi.browser" is added but a user says it doesn't help.

**Comment by Psyph8** [comment]
Keepass2android is fantastic and worked great with Firefox but I've switched to vivaldi and miss the ability of auto fill.

**Comment by skobkin** [comment]
> "com.vivaldi.browser" is added but a user says it doesn't help.

Yes, it doesn't. If you need any testing, let us know. I can try to help because I'm using Vivaldi on a daily basis.

**Comment by ouzowtf** [comment]
Maybe com.vivaldi.browser.snapshot could be added too.

**Comment by Faoc** [comment]
According to https://forum.vivaldi.net/topic/40036/lastpass this seems to be a general problem with Vivaldi, that affects multiple password managers. Looks like it's being worked on right now.

**Comment by tome9111991** [comment]
In chrome works autofill.
But still dosen't in vivaldi

**Comment by PhilippC** [comment]
it sounds a lot like autofill service is simply not supported by Vivalid. Please reopen (or comment here) if you find an app that works (but with autofill service, not accessibility)

**Comment by skobkin** [comment]
Good news everyone!

[![2021_07_26__18_17_20](https://user-images.githubusercontent.com/967576/127014276-331c06ea-6922-45af-8ad6-76c9930f46ce.png)](https://play.google.com/store/apps/details?id=com.vivaldi.browser)

More details in the [blog post](https://vivaldi.com/blog/android-3-9-2299-3/) for related snapshot.
