### ISSUE TITLE
Missing the `*-nonet.apk` of v1.07

### ISSUE THREAD

**Issue by IzzySoft** [PhilippC/keepass2android#992]
v1.07-r1 was tagged back in August with its `.apk` file attached. Usually there was also an APK for the offline version, but it didn't show up yet. Could you please attach that as well? Thanks!

**Comment by PhilippC** [comment]
this one? https://github.com/PhilippC/keepass2android/releases/download/1.07b-r0-offline/keepass2android.keepass2android_nonet-1.07b-r0.apk

**Comment by IzzySoft** [comment]
Ugh – yes, and it's even already here. Ah, you're using separate tags now – and the offline version was simply not tagged yet "back then". OK, guess this means we can close the ticket. Thanks a lot!
