### ISSUE TITLE
Keepass2Android 1.07-r1: Cannot specify key file on Android 4.4.4 

### ISSUE THREAD

**Issue by ThomasBiehl** [PhilippC/keepass2android#994]
Hello,

I have a kdbx file that requires master password and key file to open. It is stored in the cloud and used on multiple devices. One of them is an old smart phone with Android 4.4.4 (no further Android updates available :-( ).

Everything worked fine until I had to reinstall Keepass2Android. Now I cannot specify the location of the key file! This is what happens after starting Keepass2Android:

1. I select "Open file".
2. I specify the location of the database (access by SFTP).
3. Keepass2Android accesses the file and presents the screen on which one may specify the type of the lock. The default is "Password only" (in German: "Nur Kennwort").
4. I change the type of the lock to "Password + key file" (in German: "Kennwort + Schlüsseldatei". This adds a section with key file details to the dialog. It has "No key file specified" and a button "Change location" (in German: "Speicherort ändern").
5. I press "Change location" and select the key file. Keepass2Android returns to the previous screen without signalling any error or warning. But it still has "No key file specified"!

The attaced file contains the log of step 5 (trying to specify the location of the key file).

What I tried without success:

- Use a different copy of the key file that works on another Android device (OS version 6.0.1).
- Rename the key file.
- Select the key file via Android file chooser from SD card as well as from internal memory.
- Select the key file via Android file chooser and SFTP.
[keepad2android-Log.txt](https://github.com/PhilippC/keepass2android/files/3734974/keepad2android-Log.txt)

Any ideas what I could do to open the database on that device?

Best regards,
Thomas
(formerly living in Stu-Bla-Bü, now in KA! :-) )

**Comment by dhellmich1** [comment]
I have the same issue on Android 4.4.2 since some month. Keyfile and database are stored locally. The database can be opened in KeePassDroid. On Android 8 it works with same database and keyfile.

Best regards
Dirk

**Comment by ThomasBiehl** [comment]
@Dirk: Thank you for the proposition; but it seems that KeePassDroid does not support remote database file. Since my database is stored on an FTP server, I would have to use some additional means to synchronize that master file with a local copy.

Greetings,
   Thomas

**Comment by bezunartea** [comment]
Same issue on Android 4.4.4: I can select the database from Google Drive, but when I follow the same process to select the keyfile (filename.key), the app comes back to the login screen and the Key file entry states: "No key file selected."
I downloaded the file, saved it in the sdcard, and the same thing happened after I selected it from the sdcard: went back to the login screen, and "No file selected." is shown in the "Key file" section.

**Comment by jcemerson** [comment]
This sounds like the same thing as reported in [#939](https://github.com/PhilippC/keepass2android/issues/939), which itself was a version of #808. As a temporary measure until this is resolved, you can reinstall [v1.06f](https://github.com/PhilippC/keepass2android/releases/tag/1.06f) which still supports selecting the key file with older Android versions (my phone is capped at Android 4.1.2, yet it works with this release).

**Comment by mdwy62** [comment]
Just installed on a tablet with Android 4.4.2 and have the same problem. Will not select the key file.

**Comment by ThomasBiehl** [comment]
jcemerson wrote:
 
     > This sounds like the same thing as reported in [#939], which itself was a version of #808. As a temporary measure until this is resolved, you can reinstall [v1.06f](https://github.com/PhilippC/keepass2android/releases/tag/1.06f) which still supports selecting the key file with older Android versions (my phone is capped at Android 4.1.2, yet it works with this release).

Thank you for pointing at  [#939](https://github.com/PhilippC/keepass2android/issues/939) and still functioning version [v1.06f](https://github.com/PhilippC/keepass2android/releases/tag/1.06f). I will therefore close this issue.

Best regards,
   Thomas
